쥬스메이커[STEP 1] : 호랭이, aCafela coffee
yagom-academy/ios-juice-maker pull request #106
Opened 2021-10-19 13:07 UTC by horeng2

@corykim0829 
@horeng2 @aCafela-coffee

안녕하세요 Cory, 쥬스메이커 Step 1 PR입니다.
리뷰 부탁드립니다. 감사합니다!

## 고민했던 점

#### 과일 가게 재고 초기화 함수

```swift
var fruitQuantity = Dictionary(uniqueKeysWithValues: zip(uniqueKeys, Array(repeating: repeating, count: uniqueKeys.count)))
```

```swift
extension Dictionary {
    init<T>(uniqueKeys: T, repeating value: Value) where T: Collection, T.Element == Key {
        self = Dictionary(uniqueKeysWithValues: zip(uniqueKeys, Array(repeating: value, count: uniqueKeys.count)))
    }
}

var fruitQuantity: Dictionary<Fruit, Int> = Dictionary(uniqueKeys: Fruit.allCases, repeating: 10)
```

코딩을 하는 과정에서 이전 코드는 읽기 힘들어지는 문제가 있었습니다. 그래서 이니셜라이저를 추가하는 방식으로 수정했습니다.

### 고차함수 사용

```swift
var fruitQuantity: Dictionary<Fruit, Int>

func changeQuantity(of fruit: Fruit, count: Int, by operation: (Int, Int) -> Int) {
    guard let stock: Int = fruitQuantity[fruit] else {
        return
    }
    fruitQuantity[fruit] = operation(stock, count)
}

// 사용 예
changeQuantity(of: fruit, count: count, by: -)
```

재고 증감을 위한 함수에서 **함수를** 입력받습니다.

## 조언을 얻고 싶은 부분

```swift
changeQuantity(of fruit: Fruit, count: Int, by operation: (Int, Int) -> Int)
```

위 함수의 파라미터 이름이 괜찮나요? 더 좋은 이름을 원해요.🥲

2021-10-20 02:00 UTC, corykim0829 requested changes
수고많으셨습니다! 커피☕️, 호랭🐯! 👏👏👏👏

전반적으로 깔끔하게 잘 구현하셨습니다.
커밋 규칙도 잘 지키셔서 커밋한 부분도 좋았습니다!

전반적으로 메소드도 기능단위로 잘 나누어서 좋았습니다!
피드백 확인하시고 같이 이야기해봐요!

2021-10-20 03:14 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init<T>(uniqueKeys: T, repeating value: Value) where T: Collection, T.Element == Key {
이 extension은 Fruitstore안에서 과일 재고 관리 Dictionary를 위하여 명시해놓은 것이라서 Fruitstore 안에 있는 게 맞다고 생각했어요. 근데 조금 더 의논해보니 추후에 다른 기능에서 활용될 수도 있을 것 같아서, 그런 경우가 생기면 코드 위치를 수정하기로 했습니다.

2021-10-20 03:15 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeQuantity(of fruit: Fruit, count: Int, by operation: (Int, Int) -> Int) {
operation에는 함수가 들어가요. (Int, Int) 파라미터와 Int 리턴이 있다면, 뭐든 들어갈 수 있어요.
이름은 do로 고쳤어요.

2021-10-20 03:16 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let recipes: [Fruit : Int] = order.juiceRecipe
필요한 과일 종류가 여럿일 수 있어서 그랬어요. 지금 보니 조금 어색하네요. ingredients로 변경합니다.

2021-10-21 07:53 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        var recipe: Dictionary<Fruit, Int> {
변수명 깔끔하네요! 👍

2021-10-21 07:58 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(seletedJuice: Menu) throws {
makeJuice와 selectedJuice의 Juice의 중복을 줄이면 더 깔끔한 함수가 될 것 같아요. 관련 내용은 [공식문서](https://swift.org/documentation/api-design-guidelines/)를 참고하면 좋아요!

한번 더 설명해드리면 이 함수를 사용할 때, `makeJuice(selectedJuice: .mangoKiwiJuice)`와 같이 juice 중복이 생겨버립니다.
함수나 변수는 직접 사용했을 때에도 어색하지 않은지 한번 점검해보면 좋습니다!

2021-10-21 07:58 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let ingredients: [Fruit : Int] = seletedJuice.recipe
ingredients, recipe중 하나로 통일하는게 좋을 것 같아요. 이 코드를 처음보는 사람은 헷갈릴 수 있을 것 같아요!

2021-10-23 13:24 UTC, merged