쥬스 메이커 [Step1] 신나, Jerry
yagom-academy/ios-juice-maker pull request #110
Opened 2021-10-20 12:43 UTC by smart8612

@delmaSong 안녕하세요 delma😃쥬스 메이커 프로젝트를 함께 진행하는 신나와 Jerry입니다.
Step 1 코드 구현이 완료되어서 PR 보내드립니다. 고맙습니다!

## 고민했던 점

- **Order 메서드의 예외 처리가 탄생한 과정**
    
    Controller는 과일 주스를 주문하기위해 JuiceMaker의 order 메서드를 호출합니다. 
    
    과일 재고가 부족한지 확인하는 과정에서 다음의 생각이 등장했습니다.
    
    - 방안 1: order 을 호출할 때 모델은 주스를 만들어보고 과일의 재고가 부족한지 확인한다.
    - 방안 2: order 을 호출할 때 주스를 만들기 전 과일의 재고를 확인해보고 주스를 만들 수 있다.
    
    방안 1의 초기 구현에는 FruitStore의 subtractFruit 메서드에서 재고 확인 기능이 함께 구현되었습니다. 
    
    subtractFruit가 재고 관리 및 오류 검증의 두 기능을 구현해서 다음과 같이 기능을 분리하였습니다.
    
    1. FruitStore의 subtractFruit 메서드에서 재고 확인 기능을 분리 후 해당 함수를 호출한다.
    2. FruitStore의 재고를 확인하는 checkInventory 메서드를 선언한다.
    3. order의 첫 과정으로 checkInventory를 호출해준다.
    
    JuiceMaker의 order 메서드를 위 방식으로 다시 구현했습니다.
    
    make 함수가 호출하는 FruitStore의 subtractFruit에 이미 checkInventory 기능을 포함하고 있습니다.
    
    방안 2를 도입 했을 때 order에서 checkInventory 과정을 한번 더 확인하는 문제점이 있었습니다.
    
    따라서 JuiceMaker의 order 함수는 주스를 만들면서 subtract 메서드가 던지는 오류를 통해 재고를 파악하게 되었습니다.
    

- **현재 JuiceMaker의 Order 코드가 갖고 있는 문제점**
    
    JuiceMaker의 Order 코드는 재고가 부족할 때 Error를 던집니다.
    
    재고가 부족하지 않아서 정상적으로 주스를 만드는 경우 어떠한 값도 반환하지 않습니다. 
    
    즉, 재고 현황에 사용한 과일의 양을 FruitStore에 반영하고 끝납니다. 
    
    지금의 구조를 사용하면 컨트롤러가 정상적인 상황을 파악하기 어려울 수 있다고 생각되어 고민입니다.
    

- **타입 추론(Type Inference) vs 타입 어노테이션(Type Annotation)**
    
    코드를 작성할때, 변수에 초기값이 들어있어도 타입 어노테이션으로 자료형을 명시해주었습니다. 이때 변수에 자료형을 다 써주시나요..? 라는 질문을 하셔서 어느 부분에 타입 추론을 사용하고 어느 부분에 타입 어노테이션을 사용할 지 고민을 해보았습니다.
    
    먼저 둘의 정의를 살펴보았습니다.
    
    - Type Annotation
        
        상수 또는 변수를 선언할 때 상수 또는 변수가 저장할 수 있는 값의 종류를 명확히 하기 위해 사용하는 것
        
    - Type Inference
        
        상수 또는 변수를 초기 값으로 선언할 때 특히 유용한 것으로 Literal을 선언하는 지점에서 상수 또는 변수에 할당하여 수행.
        
    
    신나와 저는 swift에서는 타입 추론이라는 좋은 기능이 있으니ㅎㅎ 잘 써먹었보자 했습니다.
    
    선언과 초기화가 분리된 경우, 타입이 변경되거나 보기에 헷갈리는 부분 외에는 최대한 타입 추론을 이용해서 코드를 작성해 보았습니다.
    
    ```swift
    # type annotation
    private var fruitInventory: [Fruits: Int]
    
    # type inference
    let defaultStock = 10
    ```
    
- **FruitStore가 class인 이유와 JuiceMaker가 struct인 이유**
    
    스위프트 공식문서에서 구조체와 클래스 사이의 선택 방법을 알려줍니다. [링크](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)
    
    `Use classes when you need to control the identity of the data you're modeling.`
    
    라는 문장에서 모델링한 데이터의 아이덴티티를 제어하는 경우에는 클래스를 사용해야한다고 하는데요.
    
    FruitStore는 과일들을 저장하는 역할로 모델링한 데이터를 조작하는 책임을 가진 타입으로 앱 내의 어떤 코드에서 주소값으로 저장되므로 해당 값의 변화는 없어야 합니다. 따라서 해당 데이터의 아이덴티티를 제어하는 경우로서 class로 정의되었다고 생각합니다.
    
    반대로, 구조체는 데이터의 아이덴티티를 제어하지 않기 때문에 local 인스턴스에 대한 변경 사항이 값을 변경할 위험이 없습니다. JuiceMaker는 주스를 만드는 역할로서 데이터의 아이덴티티를 통제하지 않아도 되기 때문에 Struct로 정의되었습니다.
    

- S**truct JuiceMaker에서 Class FruitStore 생성하는 경우**
    
    struct JuiceMaker에서 class FruitStore 를 소유합니다. 이때 struct JuiceMaker 내부에 class FruitStore 인스턴스를 생성할때 default initializer를 사용하는 경우 JuiceMaker 인스턴스가 생성될 때마다 fruitStore 인스턴스 또한 같이 생성이 되는 것이라고 생각했습니다. 이는 class의 데이터의 identitiy를 제어하는 데에 문제가 생깁니다. 따라서 struct JuiceMaker 인스턴스를 생성 할때, 변수로 생성된 class FruitStore 인스턴스를 가져오면 유일한 class FruitStore를 보장할 수 있을 것이라고 생각했습니다. (이부분은 STEP1 요구사항이 아니라서 구현하지는 않았습니다..)
    
    그리고 struct이므로 memberwise initailizer를 init 방식을 이용하여 코드를 작성하였습니다.
    
    ```swift
    class FruitStore {
    
    private var fruitInventory: [Fruits: Int]
    ```
    

- C**ustomStringConvertable 과 LocalizedError 와의 차이**
    
    직접 열거형으로 정의한 에러 description을 반환할 때 어떤 프로토콜을 사용해야하는지 고민해보았습니다.
    
    customstringConvertable 은 인스턴스를 문자열로 변환할 때 사용할 고유한 표현을 제공합니다. 그리고 localizedError는 오류 및 발생한 이유를 설명하는 description을 제공합니다.
    
    localizedError는 Error프로토콜을 상속받으므로, Error 프로토콜을 채택하지 않아도 Error기능을 사용할 수 있습니다. 추가로 errordescription. failureReason와 같은 상세 프로퍼티로 명시 가능합니다.
    
    직접 찾아보니 두 프로토콜의 용도가 완전히 달랐다는 것을 깨달았고, 적합한 프로토콜을 사용할 수 있었습니다.
    
    ```swift
    extension JuiceMaker.MakingJuiceError {
        var errorDescription: String? {
            switch self {
            case .soldOut:
                return "품절되었습니다."
            }
        }
    }
    ```
    

## 조언을 얻고 싶은 부분

1. **에러처리가 일어나지 일을 에러 처리**
    
    에러처리가 일어나지 일을 에러 처리 저희가 열거형 case를 이용해서 dictionary를 구성했는데요. dictionary[key]를 이용해서 value를 가져오는 방식을 사용했습니다. 이때, value값을 담은 변수는 옵셔널 변수를 반환하여 guard문 처리를 했습니다.
    
    ```swift
    guard let numberOfFruit = fruitInventory[fruit], difference >= 0 else {
    				return
    }
    ```
    
    의문이 들었던 것은 코드 구성상 절대 에러가 일어나지 않을 텐데 에러를 정의해줘야하는가?
    
    코다의 의견은 "return을 이용해도 된다. guard else 문을 쓴것만으로도 충분히 에러를 명시하고 처리해주었다고 생각한다" 하고 말씀해주셨습니다.
    
    delma의 의견은 어떠신지 궁금합니다.😃
    

1. **에러를 명시한 enum 타입에 대한 extension 처리**
    
    사용자에게 발생한 에러에 대해 세부 사항을 설명해주기 위해 error 타입이 **LocalizedError**를 충족하도록 구현했습니다.
    
    ```swift
    enum MakingJuiceError: LocalizedError {
        case soldOut
    }
    ```
    
    타입을 명시하는 부분과 프로토콜을 충족하는데 필요한 요구사항의 구현부를 분리하기위해 extension을 사용하였습니다.
    
    ```swift
    extension JuiceMaker.MakingJuiceError {
        var errorDescription: String? {
            switch self {
            case .soldOut:
                return "품절되었습니다."
            }
        }
    }
    ```
    
    extension을 통해 구현된 errorDescription을 ErrorUtility.swift라는 하나의 파일에 모아서 에러에 대한 정보를 쉽게 찾을 수 있도록 모아두었습니다.
    
    에러가 선언된 곳과 같은 파일에 extension을 명시하는 것과 별도의 파일로 분리하는 방식에 대한 delma의 의견을 여쭤보고 싶습니다!

2021-10-20 16:01 UTC, delmaSong requested changes
신나와 제리 안녕하세요! 수고 많으셨습니다.!
고민했던 점과 함께 왜 코드를 이렇게 작성했는지에 대한 근거들을 잘 작성해주셔서 아주 좋았습니다 👍🏼
아래에 제 생각과 코멘트 달아놨으니 확인해주세요 🌴

### 타입 추론과 어노테이션
 큰 규모의 프로젝트에 의미가 더 있겠지만 타입을 추론하느라 시간 소모를 좀 더 하게되어 빌드 속도를 향상시키기 위해서는 되도록 타입 추론은 지양하는 것이 좋습니다. [참고](https://tv.naver.com/v/15354884) 그래도 나름의 기준을 가지고 잘 작성하셨네요!
### error를 던지는 메서드
이 부분은 아래 코멘트에 작성했지만 어떤 결과값을 반환하도록 하면 메서드가 좀 더 능동적으로 일을 하고 메서드를 호출하는 쪽에서도 결과값에 따른 더 명확한 처리를 해줄 수 있을 것 같습니다. 자세한 사항은 코멘트를 확인해주세요.

### 에러처리가 일어나지 않을 일
그렇다면 어떤 상황에 에러처리가 필요한 걸까요? 에러 처리가 필요한 상황은 어떤 상황일까요?

### 에러를 명시한 enum 타입에 대한 extension 처리
 에러에 대한 정보를 한데 모았다는 의미가 있지만, `InventoryManageError`가 선언된 `FruitStore`에서는 `errorDescription`이 어떻게 정의되었는지 곧바로 확인하기 어려울 것 같고, 에러끼리만 모아놨대도 같은 의미의 에러가 아닌 이상 큰 의미가 없을 것 같습니다. 정의하기 나름이겠지만 어떻게 연관있는 것들을 묶어놓고 분리할것인가. 에 대해 조금 더 고민할 지점이 있는 것 같습니다.

2021-10-21 10:14 UTC, llghdud921 commented on JuiceMaker/JuiceMaker/Model/ErrorUtility.swift
> +        }
저희가 해당 코드를 작성할 당시, controller에 에러 상황을 전부 설명할 필요가 없다고 생각하여 품절이라는 description을 반환할 수 있게 만들었는데요. 비슷한 에러를 구분해서 사용한다면 코드가 분산되고 가독성이 떨어진다는 단점이 생길 수 있을 것 같습니다.

현재 수정한 코드는 에러를 사용하지 않고 재고를 확인하는 메서드와 확인된 경우 주스를 만드는 메서드 이렇게 분리해서 구현을 하였습니다!

2021-10-21 10:16 UTC, smart8612 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            try fruitStorage.subtractFruit(fruit, of: count)
`juiceRecipe`는 필요한 주스에 대해 요구되는 재료를 담고 있는 딕셔너리 타입의 값이에요!
따라서 필요한 과일에 대해서만 반복문을 돌면서 `fruitStorage` 에 과일 재고를 줄여주는 기능을 담당하고 있어요!
이번 리팩토링 과정에서 반복문의 `juiceRecipe` 를 메서드의 인자로 받아온 juice의 recipe를 꺼내오는 방식으로 개선하여
코드를 읽기 쉽게 개선해보았어요!

2021-10-21 10:16 UTC, llghdud921 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private func make(juice: Juice) throws {
네! 맞아요ㅎㅎ 
저희가 코드 수정을 조금 진행했는데요! 주스를 만들면서 재고부족을 알아차리기 보단 주스를 만들기전에 재고를 확인하여 확인된 경우 주스를 만들어 **주스를 반환하는 메서드**를 구현했습니다!

2021-10-21 10:22 UTC, llghdud921 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            return [.strawberry: 10, .banana: 1]
네 해당 코드에서 레시피는 레시피를 반환하여 알려줍니다. 여기서 행위를 설명하는 메서드보다는 연산프로퍼티를 사용하는 것이 `juice.recipe` 를 설명하는데에 더 정확할 것같습니다! 수정했습니다!

2021-10-21 10:28 UTC, smart8612 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`fruitInventory[fruit]`는  Dictionary type에서 `subscript` 문법을 사용하여 특정 키에 대한 값을 받아오는 코드입니다.
어느 키에대한 값이 존재하지 않을 수 있기 때문에 `Optional`값으로 반환하게 됩니다.
`differece`는 정수 타입이고 `fruitInventory[fruit]`는 `Optional` 값이어서 타입이 다른 문제로 인해
`+=` 연산자를 활용할 수 없는 문제점이 있었습니다.

2021-10-21 10:33 UTC, llghdud921 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        self.fruitInventory = [:]
두가지 방식이 있습니다.
1. Default Parameter Values
init 메서드의 매개변수에 값을 할당하여 기본값을 지정할 수 있습니다. 이때는 해당 인스턴스를 생성할 때 `FruitStore() ` default initializer를 이용하면 기본값인 10으로 지정이 되고,  `FruitStore(defaultStock: Int=99) ` 를 이용해서 재고갯수를 다르게 지정해줄 수도 있습니다.
```swift
init(defaultStock: Int=10) {
        self.fruitInventory = [:]
        Fruits.allCases.forEach { fruitInventory[$0] = defaultStock }
}
```
2. convenience initializer를 이용
convenience initializer는 desingnated initializer를 보조하여 만들어진 것으로, designated initializer의 파라미터 중 일부를 기본값으로 설정해서, convenience init안에서 Designated init을 호출 하여 초기화를 진행할 수 있는것 입니다.
위의 Default Parameter Values처럼 해당 인스턴스를 생성할 때 다르게 지정할 수 있고 convenience를 이용하면 designated initializer내부는 수정하지 않고 convenience 내부만 변경해줄 수 있다는 장점이 있습니다.
```swift
init(defaultStock: Int) {
        self.fruitInventory = [:]
        Fruits.allCases.forEach { fruitInventory[$0] = defaultStock }
    }
    
    convenience init() {
        self.init(defaultStock: 10)
    }
```
저희는 convenience initializer 를 이용해 코드를 수정해 보았습니다!

2021-10-22 04:54 UTC, delmaSong approved these changes
수고하셨습니다! 다음 스텝에서 만나요 🙌🏻

2021-10-22 08:59 UTC, merged