쥬스메이커 [STEP 2] : 호랭이, aCafela coffee
yagom-academy/ios-juice-maker pull request #128
Opened 2021-10-28 10:12 UTC by aCafela-coffee

팀원 : @horeng2, @aCafela-coffee

안녕하세요. @corykim0829 
쥬스메이커 [STEP 2] PR 제출합니다.
이번 피드백도 잘 부탁드립니다. 감사합니다.

## 고민했던 점

- 쥬스 주문 버튼을 같은 함수에서 받아서 내부에서 처리할지, 각각 따로 받을지 고민했습니다.
    → 각각 따로 함수를 만들면 비슷한 기능을 하는 함수가 여러개가 생겨서, 같은 함수에서 받아서 내부에서 처리하는 방식으로 작성했습니다.
    
- 쥬스 주문 함수 실행을 위해서, 버튼의 입력을 어떤 형식의 값으로 변환할지 고민했습니다.
    → switch문을 사용하여 Menu타입으로 변환했습니다.
    
- 쥬스 주문 성공 여부에 따라 달라지는 알림 메세지를 어떻게 구분할지
    → showAlert함수 매개변수로 isSuccess(성공여부)를 Bool값으로 입력하여 orderJuice함수 내에서 if문으로 구분
    

## 조언을 얻고 싶은 부분

### 화면 전환 방법

- 재고 수정 화면을 모달로 보여주기 위해서 아래 코드를 사용했습니다. 다른 방법도 있나요?
    
    ```swift
    func moveEditView() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let editViewController: EditViewController = storyboard.instantiateViewController(identifier: "EditViewController")
        let navigationController = UINavigationController(rootViewController: editViewController)
        present(navigationController, animated: true, completion: nil)
    }
    ```

- 재고 관리 화면을 팝오버로 구현해보고 싶은데 방법을 찾아봐도 해결하지 못했어요. 도움될만한 참고자료가 있을까요?

2021-10-31 14:41 UTC, corykim0829 requested changes
수고하셨습니다!! 👏👏👏

제가 해드린 리뷰 바탕으로 코드를 더 보완해 나가면 좋을 것 같습니다!!!

어려운 부분이나 이슈가 발생하면 편하게 DM으로 말씀해주세요!

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/EditViewController.swift
> +class EditViewController: UIViewController {
EditViewController만 보면 어떤 것을 Edit하는 ViewController 객체인지 잘 모를 수도 있을 것 같아요. 클래스명을 변경하면 더 읽기좋은 코드가 될 것 같아요!

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/EditViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(doneButtonTrigger))
viewDidLoad에는 나중에 많은 코드들이 들어가는데, 모두 viewDidLoad에 구현하면 코드를 읽기 어렵기 때문에 함수로 분리하면 가독성이 더 좋습니다!

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet var stockOfStrawberry: UILabel!
`stockOfStrawberry` 변수명만 봤을 때에는 어떤 클래스인지 유추하기 어렵습니다. 특히나 UIKit과 같은 클래스들은 뒤에 해당 클래스를 명시해주면 더욱 코드를 읽기 좋아집니다.
여기서는 `stockOfStrawberryLabel`로 바꾸면 좋을 것 같아요.

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let currentStock = juiceMaker.checkFruitStock()
`checkFruitStock()`은 어떤 객체를 반환하는지 짐작이 잘 가지 않는 함수명인 것 같아요.
그냥 봤을 때에는 반환하는게 없을 것 같은 함수 같아요! 함수명을 변경해보면 좋을 것 같아요.

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func changeStockLabel() {
함수와 프로퍼티는 외부에서 꼭 바꿔야하는 경우를 제외하고는 우선적으로 private으로 고려하는게 좋습니다. 객체지향적이기 떄문이죠!
또한 changeStockLabel이라고 하면 어떤 값을 받아서 StockLabel을 교체 또는 변경해줘야할 것 같은 느낌이 있어서 updateStockLabel이라고 하면 더 자연스러울 것 같아요~

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func switchMenuToUIButton(button: UIButton) -> Menu {
switchMenuToUIButton이라는 함수명을 보면 Menu를 UIButton으로 바꿔주는 함수 같은데, Menu 타입을 반환하는 함수여서 어색하네요. 더 멋진 함수명으로 바꿔보아요! 😎

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let isSuccess: Bool = juiceMaker.make(juice)
juiceMaker 객체가 make함수로 juice를 만들면 juice 객체를 반환할 것 같은데, 성공여부 Bool 값을 반환하는게 어색하게 느껴져요. 개선해봅시다! 💪

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            fatalError("Non-Existent Button")
만약 fatalError가 발생하게 되면 앱이 종료되기 때문에 좋은 코드가 아닌 것 같습니다. 또한 button title은 String이기 때문에 실수로 인해서 switch case 구문에서 여기로 빠질 위험성도 있어요.
이쪽 로직에서는 String 보다 조금 더 안전한 방법을 고민해보면 좋을 것 같아요!

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func make(_ seletedJuice: Menu) -> Bool {
이 부분은 위에서 얘기 했듯이 make라는 함수가 Bool을 반환하는게 어색해요! 개선해봅시다 ㅎ

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func moveEditView() {
`moveEditView`라고 하면 영문법상 EditView를 움직이라고 말하는 함수같아요.
`moveToEditViewController`나 해당 ViewController로 전환한다는 의미를 담는 함수명으로 바꾸면 좋을 것 같아요!

2021-10-31 14:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func hitEditButton(_ sender: UIBarButtonItem) {
위에 Button action에 대해서 doneButtonTrigger와 같은 네이밍을 사용했는데, 버튼 액션에 대한 네이밍 컨벤션을 잡아서 통일하면 좋을 것 같아요!

2021-11-01 08:44 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Controller/EditViewController.swift
> +class EditViewController: UIViewController {
EditFruitStockViewController로 변경했습니다!

2021-11-01 08:44 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func hitEditButton(_ sender: UIBarButtonItem) {
함수 doneButtonTrigger를 hitDoneButton으로 수정했습니다.

2021-11-01 08:44 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Controller/EditViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(doneButtonTrigger))
configureNavigationButton 함수로 분리했습니다!

2021-11-01 08:44 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func moveEditView() {
`moveToEditViewController`로 변경했습니다.

2021-11-01 08:45 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet var stockOfStrawberry: UILabel!
각 Label명 뒤에 "Label"을 추가했습니다. 더 명확한 이름이 되었어요 👍

2021-11-01 08:45 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func make(_ seletedJuice: Menu) -> Bool {
함수 이름을 `isCompletMaking(_:)`로 변경했습니다.

2021-11-01 08:45 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let currentStock = juiceMaker.checkFruitStock()
isCompletMaking으로 변경하여 완성여부를 반환한다는 뜻을 나타낼 수 있도록 했습니다.

2021-11-01 08:46 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            fatalError("Non-Existent Button")
`switchMenuToUIButton`함수를 삭제하고, `orderJuice`함수 내에서 button의 tag값을 이용해서 `Menu(rawValue:)` 이니셜라이저를 사용했습니다.

2021-11-01 08:46 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func switchMenuToUIButton(button: UIButton) -> Menu {
`switchUIButtonToMenu`로 변경했습니다ㅏ.

2021-11-01 08:51 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func switchMenuToUIButton(button: UIButton) -> Menu {
피드백 반영 과정에서 switchMenuToUIButton함수를 삭제했습니다!!

2021-11-02 11:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/EditViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(doneButtonTrigger))
좋은 네이밍이네요! 👍

2021-11-02 11:55 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +
공백 줄 정리 부탁해요!

2021-11-02 11:55 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction private func orderJuice(_ sender: UIButton) {
버튼의 IBAction도 버튼 액션 함수는 통일하면 좋을 것 같아요

2021-11-02 11:55 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let currentStock = juiceMaker.checkFruitStock()
문법적으로 어색한 것 같아요. 조동사를 활용하는 방법도 있습니다. 꼭 is로 시작하지 않아도 됩니다. 이 부분 참고해서 조금 더 개선해보면 좋을 것 같아요!

2021-11-02 12:01 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            fatalError("Non-Existent Button")
button tag 값을 받아서 처리하게되면 유지/보수가 어려워지게 됩니다. 다른 방법을 고민해보는게 좋을 것 같아요.

2021-11-02 12:02 UTC, corykim0829 requested changes
수고하셨습니다!! 👍

많이 코드가 깔끔해진게 느껴져요!
조금만 더 개선해봅시다!!

2021-11-03 02:58 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print("Non-Existent Button")
print문을 제거하여 버튼 이외의 입력이 들어오는 오류가 있을 때에는 아무런 반응이 없도록 하였습니다.

2021-11-03 02:59 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction private func orderJuice(_ sender: UIButton) {
`hitOrderJuiceButton(_:)`로 변경합니다.

2021-11-03 02:59 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let currentStock = juiceMaker.checkFruitStock()
"쥬스를 만들수 있다"라는 의미에서 canMake로 변경하였습니다.

2021-11-03 02:59 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +
수정 했습니다.

2021-11-03 03:00 UTC, horeng2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            fatalError("Non-Existent Button")
tag 대신 currentTitle과 Menu타입의 rawvalue를 사용했습니다.

2021-11-03 12:44 UTC, corykim0829 approved these changes
수고하셨습니다!! 👍👍👍

다음 스텝 목표 일정 저한테 DM으로 말해주시고 다음 스텝 진행해주세요! ㅎ

2021-11-03 12:44 UTC, merged