쥬스메이커 [STEP 2] 호댕, vayne
yagom-academy/ios-juice-maker pull request #130
Opened 2021-10-29 07:16 UTC by vayne77

담당 리뷰어: @corykim0829

안녕하세요! Cory! 7모둠 호댕과 Vayne입니다.
프로젝트 Step2 완료해서 PR 보내드립니다! 잘 부탁드립니다 🙏

## 코드 작성 시 고민했던 부분 / 해결한 과정

1. unrecognized selector sent to instance 0x1577067d0 오류
 + 주스 주문을 받는 버튼을 하나의 함수로 구현하려고 했으나 위의 오류가 발생했습니다.
 + 버튼에서 각각 함수를 생성하여 해결했으나 정확한 원인을 파악하지 못했습니다.
    (현재는 연결 문제로 인한 오류라고 생각하고 있습니다.)

2. 재고는 정상적으로 감소하나 `MainViewController`의 `label`에 표시가 안되는 문제
+ `FruitStore`를 계속 초기화해서 `label`에 재고가 10으로 뜨는 문제가 있었습니다.
+ `FruitStore`를 싱글톤으로 구현해서 해결했습니다.

3. 재고 수정에 대한 `view`를 `modal` 방식으로 화면 전환
+ 앱을 사용하면서 재고가 부족하면 재고 수정이라는 단편적인 기능을 수행해야하기 때문에 `modal` 방식을 채택하여 사용했습니다.
+ alert의 재고 수정 버튼을 눌렀을 때도 재고 수정 `view`로 넘어가야 하는데 이 때 `navigation` 방식을 사용해 `view`를 보여주는 것은 맞지 않다고 판단했습니다.

4. `alert`의 버튼 구성
+ H.I.G 가이드 라인을 따라 `alert` 버튼을 구성했습니다.
+ `Alert Button`을 yes or no는 사용하지 않는 것이 좋다고 하여 재고수정, 취소로 구성했습니다.
+ 작업을 취소하는 버튼은 언제나 왼쪽에 있다라고 하여 취소버튼을 왼쪽에 배치했습니다.

5. `modal` 방식으로 전환한 `view`에 닫기 버튼 구현
+ H.I.G 문서의 `Always include a button that dismisses the modal view` 문장에 따라 `modal view`의 닫기 버튼을 구현했습니다.

## 조언을 받고 싶은 점
1. `viewController`의 이름을 `MainViewController`와 `ModifyStockViewController`로 정했는데 이런식으로 네이밍을 바꿔주는 것이 적합한지 궁금합니다.

2. `MainViewController`에서 `label`과 버튼의 액션에 `private` 접근제어를 설정해줬습니다.  
+ 추후 다른 사람이 `label`과 `Button`을 임의로 수정할 수 있는 상황이 발생할 수도 있다고 판단하여 `private`을 설정했는데 이 판단이 맞을까요?
+ `Controller` 대부분의 함수와 변수를 `private`으로 설정해줬는데 이렇게 사용해도 괜찮을까요?

2021-10-31 15:09 UTC, corykim0829 requested changes
수고 정말 많았어요!! 호댕, 베인! 👍
제가 남겨드린 리뷰를 바탕으로 보완해 나가봅시다! 💪

> 조언을 받고 싶은 점

> viewController의 이름을 MainViewController와 ModifyStockViewController로 정했는데 이런식으로 네이밍을 바꿔주는 것이 적합한지 궁금합니다.

좋습니다! 보통 클래스명에는 조금 더 명사형태로 사용하기 때문에 ModifyStockViewController는 조금 어색한 느낌이 있는 것 같아요. modify를 살리고 싶다면 저는 StockModificationViewController와 같이 명명할 것 같아요.

> MainViewController에서 label과 버튼의 액션에 private 접근제어를 설정해줬습니다.
> 추후 다른 사람이 label과 Button을 임의로 수정할 수 있는 상황이 발생할 수도 있다고 판단하여 private을 설정했는데 이 판단이 맞을까요?

아주 좋아요! 객체지향적으로 코드를 작성하고 다른 객체가 접근하여 값을 수정해버릴 수 있는 현상을 방지하기 위해서 private을 항상 우선하여서 사용하는게 좋습니다

> Controller 대부분의 함수와 변수를 private으로 설정해줬는데 이렇게 사용해도 괜찮을까요?

네 지금까지 봤을 때에는 아주 좋았습니다! 👍

2021-10-31 15:09 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func orderJuice(juice: Juice) {
jucie가 중복되네요! 더 가독성 있게 바꿀 수 있을 것 같아요!

2021-10-31 15:09 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func showExistStockAlert(message: String) {
Exist라기 보다는 current라는 단어가 더 자연스러울 것 같아요!

2021-10-31 15:09 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            showExistStockAlert(message: "\(juiceMaker.tell(name: juice)) 쥬스 나왔습니다. 맛있게 드세요!")
여기에서는 쥬스가 나왔다는 alert만 뜨는거여서 Stock이랑은 관련이 없어보이네요! 그래서 여기 함수를 호출하는게 어색해보입니다!

2021-10-31 15:09 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +    @IBAction private func touchUpDismissButton(_ sender: UIButton) {
버튼들 이름 통일한 부분 좋습니다! 👍
읽기좋네요 ㅎ

2021-11-01 06:15 UTC, vayne77 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private let fruitStore = FruitStore.shared
FruitStore에서 stock은 JuiceMaker 앱에서 전역적으로 사용되는 변수라고 생각합니다. StockModificationViewController 에서도 stock을 사용해야 한다고 생각했고, MainViewController 에서도 사용되기 떄문에 싱글톤을 사용했습니다. 만약 싱글톤을 사용하지 않는다면 어떤 방법이 있을지 궁금합니다!

2021-11-01 06:34 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        }
아래 피드백을 수정하며 수정 완료했습니다!!

2021-11-01 06:38 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            print("없는 과일입니다.")
일단 `viewDidLoad`에서 해당 함수를 호출하게 되면 재고 수정 화면을 갔다가 와도 다시 `viewDidLoad`가 실행이 안되기 때문에 `viewWillAppear`에 함수를 적어줬습니다.
또한 `updateFruitStockLabel`이 오류를 throws하고 있어 위처럼 작성을 했었는데 에러도 사실 발생할 수 없는 오류라고 판단하여 `try!`를 사용했습니다.

2021-11-01 06:52 UTC, vayne77 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func orderJuice(juice: Juice) {
orderJucie 함수를 order 함수로 이름을 수정해주었습니다!!

2021-11-01 07:01 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func showExistStockAlert(message: String) {
현재 재고가 존재할 때 Alert와 재고가 존재하지 않을 때 Alert로 나눠서 각각 `showExistStockAlert`, `showNoExistStockAlert` 이런 함수 명을 적었는데 current라는 이름이 더 적합할까요?

'현재 재고에 대한 Alert' 같은 느낌이 있어 현재 네이밍보다 적합한가 고민이 됩니다.

2021-11-01 07:13 UTC, vayne77 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            showExistStockAlert(message: "\(juiceMaker.tell(name: juice)) 쥬스 나왔습니다. 맛있게 드세요!")
쥬스를 주문받고 받은 주문의 대한 alert와 재고를 소비하는 역활로 함수로 만들었습니다. 먼저 재고를 소진하는 `consumeStock` 함수를 호출했고, 재고가 있다면 `showExistStockAlert`가 나오고 label에 반영될 수 있도록 `updateFruitStockLabel` 함수를 호출하도록 차례대로 구현했습니다. 또 여기서 `consumeStock` 함수에서 `notEnoughStock` 에러가 나왔을 떄는 `showNoExistStockAlert` 함수가 호출되도록 만들었습니다. 
혹시 이 함수를 분리시켜주면 좋다라는 말씀이실까요?

2021-11-02 11:37 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private let fruitStore = FruitStore.shared
MainViewController가 fruitStore 객체를 가지고 있게 해당 객체를 StockModificationViewController가 참조만 하는 방법으로 사용하면 하나의 인스턴스로 사용할 수 있을 것 같네요!

2021-11-02 11:42 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            print("없는 과일입니다.")
발생할 수 없는 오류라고 판단되면 이 오류를 던질 필요도 없을 것 같아요. 그러면 굳이 try!를 쓰지 않아도 되죠. 이 부분은 조금 더 고민해보면 좋을 것 같네요!

2021-11-02 11:48 UTC, corykim0829 requested changes
수고하셨습니다 👏👏👏👏

`updateFruitStockLabel()` 부분을 중심적으로 수정하면 좋을 것 같아요!

2021-11-02 11:48 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            showExistStockAlert(message: "\(juiceMaker.tell(name: juice)) 쥬스 나왔습니다. 맛있게 드세요!")
아하 `showExistStockAlert`와 `showNoExistStockAlert` 함수가 분리되어있었군요! 하나의 함수로 제가 착각했습니다.
`showExistStockAlert` 함수명은 어색한 느낌이 있네요. 함수명만 수정하면 될 것 같아요.

2021-11-02 11:48 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func showExistStockAlert(message: String) {
위에 답변을 보고 보니까 이 함수명은 다시 변경하면 이 대화는 큰 의미가 없을 것 같네요!

2021-11-03 02:48 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private let fruitStore = FruitStore.shared
저번에 FruitStore의 인스턴스만 생성했을 땐 View에서 볼 때 초기재고에서 변하지 않는 문제가 있었는데 다시 인스턴스를 생성해주니 잘 작동하네요..? 😭 
말씀해주신대로 FruitStore의 객체를 사용하는 곳이 많지 않아 싱글톤이 적합하지 않을 수 있다 판단했고 MainVeiwController에 FruitStore의 인스턴스를 생성하는 방법으로 수정했습니다.

2021-11-03 03:02 UTC, vayne77 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            print("없는 과일입니다.")
해당 오류는 발생하지 않는다고 판단이 되어 throw noExistFruit를 return 으로 수정해줬고 try!를 사용하지 않도록 했습니다.

2021-11-03 03:08 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            showExistStockAlert(message: "\(juiceMaker.tell(name: juice)) 쥬스 나왔습니다. 맛있게 드세요!")
주문이 성공했을 때 나오는 알림이라 `showSuccessfulOrderAlert`()로 수정해봤는데 이 네이밍은 어떨까요?

2021-11-03 12:46 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            showExistStockAlert(message: "\(juiceMaker.tell(name: juice)) 쥬스 나왔습니다. 맛있게 드세요!")
`showOrderSuccessAlert`가 깔끔하고 명확한 것 같아요. 명사를 많이 쓰는게 더 명확해서 좋아요!

2021-11-03 12:50 UTC, corykim0829 approved these changes
수고 많으셨습니다! 👍👍👍👍👍

다음 스텝 진행 전에 DM으로 목표 일정 말해주세요!

2021-11-03 12:51 UTC, merged