ios-juice-maker [STEP 3] nicholas, 고사리
yagom-academy/ios-juice-maker pull request #132
Opened 2021-10-31 09:26 UTC by Kim-EunsooSilver

안녕하세요 도미닉(@AppleCEO )!! ^^7
2모둠 Nicholas(@Kim-EunsooSilver), 고사리(@FIIIIN)입니다~!

[step 3]
생각했던 저희 예상 소모시간보다 빨리 기능 구현이 완성되었습니다.
리팩터링을 저희 내부에서도 진행 완료하였고, 도미닉의 의견을 더 많이 듣고자 빠른 PR 드립니다.

이번에도 많은 의견 부탁드립니다.

# 궁금한 점
- 아래와 같이 guard let 바인딩 진행시 else 스코프내에 보통 어떤 것을 구현 혹은 호출하는지 궁금합니다.
    ```swift
    @IBAction func orderJuice(_ sender: UIButton) {
        guard let orderedJuice = JuiceMenu(rawValue: sender.tag) else {
            return
        }
        
        if juiceMaker.make(orderedJuice) {
            showSuccessAlert(menu: orderedJuice)
        } else {
            showFailureAlert()
        }
    }
    ```
- setFruitQuantityStepper 함수 내부에서 Stepper의 속성을 설정해보았는데, 현업에서 nil 변산 연산자를 많이 사용하는지 궁금합니다.
    
    ```swift
    func setFruitQuantityStepper() {
            ...
            strawberryQuantityStepper.value = Double(Int(strawberryQuantityLabel.text ?? "0") ?? 0)
            ...
    }
    ```

- 저희는 segue를 이용하여 화면 간 데이터 전환을 진행하였습니다. 이때, 타 예제들(`if segue.destination is TertiaryViewController {}`)과는 다르게 아래처럼 진행하였습니다.
    
    ```swift
    if segue.destination.children.first is ManageStockViewController {}
    ```
    
    * 저희는 이 차이가 `Navigation Controller` 의 존재유무에서 온다고 생각하는데, 도미닉의 생각은 어떠신지 궁금합니다.

- 기존 쥬스주문 버튼에 라벨을 할당했던 것처럼, 각 Stepper에게 태그를 붙여주었습니다. 현업에서는 어떻게 많이 사용되나요? 다른 식별 방법이 있다면 알려주세요.

- [adjustsFontSizeToFitWidth](https://developer.apple.com/documentation/uikit/uilabel/1620546-adjustsfontsizetofitwidth) 공식문서를 참고, 적용하여 iPhone SE2 까지 정상적으로 주문 버튼의 전체 텍스트가 노출되는 것을 확인할 수 있었습니다. 혹시 오토레이아웃을 이용하여 버튼 타이틀의 폰트 사이즈를 기기별로 수정할 수 있을까요?
    - 반복을 피하기 위해 모든 버튼을 배열로 받아, 각 버튼에 속성을 부여하였습니다.

- makeCurrentAllStock의 함수명이 고민스럽습니다. 사실 저희는... makeCurrentAllStockToArray로 네이밍을 하고 싶었는데요. 배열을 보여준다는 의미를 가지는 더 나은 네이밍이 있을까요?

# 해결하지 못한 문제
- iPhone 4s로 구동할 시, stepper의 사이즈가 줄지 못하고 밀리는 현상이 발생합니다. iPhone SE까지는 문제없이 노출되며, 선배 캠퍼분들과 이야기를 나눈 후 AutoLayout으로는 stepper 고유의 사이즈를 줄일 수 없는 것으로 판단되어  해결하지 못한 문제로 남겨두었습니다.
  저희가 놓친 부분이 있다면 말씀 부탁드립니다!
<img width="396" alt="스크린샷 2021-10-31 오후 2 57 55" src="https://user-images.githubusercontent.com/83689084/139575576-3d9b4bda-c2d9-447b-a9a5-dbab6b49844b.png">

- 아래와 같이 append가 반복되는 상황을 피하기 위해 UILabel을 배열로 받아와, forEach를 통해 반복문을 돌리고자 하였습니다.
```swift
        currentAllStock.append(strawberryQuantityLabel.text ?? "0")
        currentAllStock.append(bananaQuantityLabel.text ?? "0")
        currentAllStock.append(pineappleQuantityLabel.text ?? "0")
        currentAllStock.append(kiwiQuantityLabel.text ?? "0")
        currentAllStock.append(mangoQuantityLabel.text ?? "0")

```

그러나 아래와 같은 상황에 대해서는 forEach를 돌리기에 무리가 있다고 판단하여 리팩토링이 불가했습니다.

```swift
strawberryQuantityLabel.text = String(fruitStoreInventory[.strawberry] ?? 0)
```

`열거형`을 활용해볼까도 생각했는데, 여러 오류로 잘 되지 않았습니다... 이와 같은 반복을 피하기 위한 방법으로 어떤 것이 있을까요?

* switch 문을 피하고 싶었지만 UILabel을 열거형으로 관리하는 법을 알지 못해 리팩토링 진행이 불가했습니다. 방법이 있을까요?
```swift
func fetchLabel (_ tag: Int) -> UILabel {
        switch tag {
        case 0:
            return strawberryQuantityLabel
        case 1:
            return bananaQuantityLabel
        case 2:
            return pineappleQuantityLabel
        case 3:
            return kiwiQuantityLabel
        case 4:
            return mangoQuantityLabel
        default:
            return strawberryQuantityLabel
        }
    }
```
* IBOutlet의 메서드명을 리팩토링하는 과정에서 rename하여도 버튼과의 연결은 리팩토링이 적용되지 않아 하나씩 수정을 거쳤습니다. 왜 이런 걸까요😂

2021-11-01 04:54 UTC, AppleCEO requested changes
Nicholas, 고사리 고생하셨습니다!
PR 속도가 굉장히 빨랐네요 ㅎㅎ
전에 이야기했던 의문들을 해결해보는 시간도 가지면 좋겠습니다.

아래와 같이 guard let 바인딩 진행시 else 스코프내에 보통 어떤 것을 구현 혹은 호출하는지 궁금합니다.
- 보통 예제 코드처럼 return 만 하는 경우가 많습니다.

setFruitQuantityStepper 함수 내부에서 Stepper의 속성을 설정해보았는데, 현업에서 nil 변산 연산자를 많이 사용하는지 궁금합니다.
- 저는 많이 사용하지는 않습니다. 옵셔널 바인딩을 하게 되면 기본값 사용을 줄일 수 있을 것 같습니다. 또한 한 줄에서 너무 많은 변환이 일어나는 것 같습니다. 여러 줄로 풀어서 한번씩 형변환을 하면 좋겠습니다!

저희는 segue를 이용하여 화면 간 데이터 전환을 진행하였습니다. 이때, 타 예제들(if segue.destination is TertiaryViewController {})과는 다르게 아래처럼 진행하였습니다.

if segue.destination.children.first is ManageStockViewController {}
저희는 이 차이가 Navigation Controller 의 존재유무에서 온다고 생각하는데, 도미닉의 생각은 어떠신지 궁금합니다.
- segue.destination.children.first 와 segue.destination 의 차이가 네비게이션 컨트롤러의 유무에 따른다는 이야기죠? 저도 한번 찾아보고 공유하겠습니다!

기존 쥬스주문 버튼에 라벨을 할당했던 것처럼, 각 Stepper에게 태그를 붙여주었습니다. 현업에서는 어떻게 많이 사용되나요? 다른 식별 방법이 있다면 알려주세요.
- 태그를 사용한 방법 좋습니다! Stepper 를 이렇게 여러개 사용한 경험은 저는 없습니다. 과일처럼 스태퍼가 많지 않다면 각 스테퍼마다 IBAction 함수를 각각 설정할 것 같습니다.

adjustsFontSizeToFitWidth 공식문서를 참고, 적용하여 iPhone SE2 까지 정상적으로 주문 버튼의 전체 텍스트가 노출되는 것을 확인할 수 있었습니다. 혹시 오토레이아웃을 이용하여 버튼 타이틀의 폰트 사이즈를 기기별로 수정할 수 있을까요?
- 오토레이아웃을 사용해서는 힘들 것 같습니다. 오토레이아웃은 기기의 크기에 따라 자동적으로 뷰의 사이즈가 결정됩니다. 제가 아는 분은 현재 기종을 가져오는 코드를 사용해서 각 기종마다 enum에 정해놓은 폰트 사이즈 등을 설정하는 것을 본 적은 있습니다.

반복을 피하기 위해 모든 버튼을 배열로 받아, 각 버튼에 속성을 부여하였습니다.
makeCurrentAllStock의 함수명이 고민스럽습니다. 사실 저희는... makeCurrentAllStockToArray로 네이밍을 하고 싶었는데요. 배열을 보여준다는 의미를 가지는 더 나은 네이밍이 있을까요?
- 배열을 보여준다는 의미인데 make 가 동사로 쓰인 것은 좀 어색한 것 같네요. 보여준다는 동사를 한번 찾아보면 어떨까요? ㅎㅎ

switch 문을 피하고 싶었지만 UILabel을 열거형으로 관리하는 법을 알지 못해 리팩토링 진행이 불가했습니다. 방법이 있을까요?
- UILabel 타입의 배열을 사용하면 어떨까요? ㅎㅎ

IBOutlet의 메서드명을 리팩토링하는 과정에서 rename하여도 버튼과의 연결은 리팩토링이 적용되지 않아 하나씩 수정을 거쳤습니다. 왜 이런 걸까요😂
- 흐음.. 엑스코드 버그가 아닐까 싶네요. 엑스코드를 껐다가 켜면 다시 되는 경우가 있을 것 같습니다.. ;

2021-11-01 04:54 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/AppDelegate.swift
> -
의미없는 공백을 제거한 부분 좋습니다! 👍

2021-11-01 04:54 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet var oderButtons: [UIButton]!
버튼의 배열을 사용해보셨군요! 💯

2021-11-01 04:54 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
이러한 동작은 함수로 빼낼 수 있으면 좋을 것 같네요!

2021-11-01 04:54 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        setFruitQuantityLabel()
과일의 양을 설정해주는 메소드를 따로 빼낸 부분 좋습니다 🥇

2021-11-01 04:54 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        mangoQuantityLabel.text = deliverdAllStock[4]
과일 양을 나타내는 label 을 oderButtons 처럼 배열로 작성하지 않은 이유가 있을까요? ㅎㅎ

2021-11-01 04:54 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        mangoQuantityLabel.text = deliverdAllStock[4]
만약 뷰컨트롤러간에 통신이 실패해서 deliverdAllStock 배열이 비어있을 때 앱이 어떻게 될까요?

2021-11-01 06:18 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
넵~!
말씀하셨던게 좋아서 setButtonFontSize 함수를 구현하였습니다.
추가적으로, 기존 oderButtons 배열은 폰트 사이즈를 조절하기 위해 선언한 배열이였습니다. 해당 배열의 이름을 명확히 하고자 needToChangeButtonsFontSize로 이름을 변경하였습니다.

2021-11-01 06:20 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        setFruitQuantityLabel()
이전 킹미닉의 훌륭한 리뷰덕분입니다~!🙈

2021-11-01 13:25 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        mangoQuantityLabel.text = deliverdAllStock[4]
1. 배열로 작성하지 않은 이유는...  배열로 구현시, 사용에 편의성은 확실히 좋아지만, 코드 가독성으로 따졌을때, 몇번째 배열이 어떤 라벨을 나타내는지 코드상에서 알수 없기에 구현하지 않았습니다. 피드백 주신부분은 배열로 작성했는데 도미닉은 비슷한 경우에 어떻게 사용하시고 가독성은 어떻게 해결하시나요?

2. 통신 실패로 배열이 비어있을 경우, out of range 로 런타임 오류로 앱 종료가 되는 것으로 파악하였습니다. 이 부분을  해결하기 위해서, deliveredAllStock 배열에 초기값을 주거나 throw를 이용한 오류처리를 진행해야 하는 것으로 판단됩니다.
이 피드백을 받고 저희는 의문점이 들었었는데요!! 🤔🤔저희가 앱을 사용할때 일반적으로 격는 오류는 네트워크 관련된 오류만 접해봤습니다. 뷰 컨트롤러 간에 통신관련해서는 오류를 경험해 보지 못했는데,,, 일반적으로 뷰 컨트롤러간 통신시에 통신 실패에 대해서도 대비를 해야하는지 궁금합니다.

2021-11-01 13:57 UTC, Kim-EunsooSilver commented
안녕하세요 도미닉~😉7

이번 피드백에 대해서 반영을 해보았습니다. 저희는 이번 피드백으로 저희 프로젝트가 지금 당장 머지되기를 바라지는 않습니다. 
도미닉이 말씀하셨던 `전에 이야기했던 의문들을 해결해보는 시간도 가지면 좋겠습니다.` 관련해서 저희가 시간을 갖고 더 생각해보려 합니다.
일단 저희의 이 코멘트는 스텝 3 관련한 부분만 확인 부탁드리도록 하겠습니다. `전에 이야기했던 의문`은 별도로 코멘트 달아보도록 하겠습니다.

# 개선한 점
* 버튼 타이틀의 폰트사이즈를 자동으로 지정하는 함수 선언 하였으며, 버튼의 배열명 변경하였습니다.
    * (oderButtons -> needToChangeButtonsFontSize)
*  setFruitQuantityStepper 함수를 반복문을 이용하여 개선하였습니다.
```swift
        var labelTexts = [String]()
        
        for label in fruitQuantityLabels {
            labelTexts.append(String(label.text ?? "0"))
        }
        
        for index in 0...fruitQuantityLabels.count - 1 {
            fruitQuantityStepper[index].value = Double(Int(labelTexts[index]) ?? 0)
        }

```
* fruitQuantityLabels, fruitQuatitySteppers 배열 선언하였습니다.
* touchUpFruitQuantityStepper 함수 개선하였습니다.
* setFruitQuantityLable 함수를 반복문을 이용하여 개선하였습니다.

# 궁금한점
- `updateStock` 메서드를 두 가지 로직으로 구현해보았습니다. 전자의 경우 유지보수가 용이하며, 후자의 경우 직관적이므로 가독성이 올라가는 것으로 판단됩니다. 도미닉은  어떤 방식을 선호하시나요?

```swift
func updateStock() {
        var fruitNames = [Fruit.Name]()
        for name in Fruit.Name.allCases {
            fruitNames.append(name)
        }
        
        var updatingFruitsQuantity = [Fruit]()
        for index in 0...fruitQuantityLabels.count - 1 {
            updatingFruitsQuantity.append(Fruit(name: fruitNames[index],
                                   quantity: Int(fruitQuantityLabels[index].text ?? "0") ?? 0))
        }

        juiceMaker?.updateStock(to: updatingFruitsQuantity)
    }
```

```swift

let updateArray: [Fruit] = [Fruit(name: .strawberry, quantity: Int(strawberryQuantityLabel.text ?? "0") ?? 0),
                                Fruit(name: .banana, quantity: Int(bananaQuantityLabel.text ?? "0") ?? 0),
		                Fruit(name: .pineapple, quantity: Int(pineappleQuantityLabel.text ?? "0") ?? 0),
		                Fruit(name: .kiwi, quantity: Int(kiwiQuantityLabel.text ?? "0") ?? 0),
                              	Fruit(name: .mango, quantity: Int(mangoQuantityLabel.text ?? "0") ?? 0)]
```
- `makeCurrentAllStock` 함수명 관련해서 이전 PR 커멘트에는 `보여진다`로 기재되었는데 잘못된 기재였습니다. 해당 함수는 현재 label의 text의 값들을 배열로 만들어 리턴해주는 역활입니다. 함수명 관련 고민중 api 디자인 가이드라인을 확인해봤는데 함수명에 명사를 사용한 예시를 포착했습니다. 해당 함수명을 `currentAllStocks` 이렇게 생각해 보았는데 어떠신가요?

2021-11-03 02:52 UTC, Kim-EunsooSilver commented
😭7
도미닉 안녕하세요~!!!!!!
`전에 이야기했던 의문들을 해결해보는 시간도 가지면 좋겠습니다.` 관련해서 고사리와 제가 개선을 해봤습니다.
DM으로 말씀하셨던 열거형으로의 변환을 고사리와 제가 고민하고 구현을 시도해 보았지만, 저희 뜻대로 되지 않았습니다.
1. enum을 새롭게 정의하고 원시값을 [fruit]으로 설정해봤지만, enum의 원시값은 문자열, 문자, 또는 정수 또는 부동소수 타입만 가능하므로 불가했고 추가적인 방법은 찾지 못했습니다.

2. 이런 의도이실까 구현은 해봤지만 동일한 기능을 하는 열거를 내부에 다시  만들었다는 생각을 해서 제외했습니다.🙈🙉🙈🙉
    ![스크린샷 2021-11-03 오전 11 46 22](https://user-images.githubusercontent.com/83689084/140003441-e14dec5d-6205-41df-839a-1ad5b0285cba.png)

이상입니다.... 도미닉께서 스텝 2에서 코멘트해주신 부분에 대해 어떤 구현을 생각하신건지 정말 너무 많이 진짜 무지 궁금합니다....

2021-11-03 03:59 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        mangoQuantityLabel.text = deliverdAllStock[4]
1. 딕셔너리를 활용해 볼 수도 있을 것 같습니다!
2. 뷰 컨트롤러 간 통신의 문제라기보다는 이 뷰컨트롤러(재고 수정)에 과일이 추가된 상태에서 다른 뷰컨트롤러에서 그 부분이 작성되지 않았을 경우 등 여러 경우에 누락되면 앱이 중단될 수 있습니다. 그래서 최대한 안전하게 이 정도는 대비를 하는 것이 좋다고 생각합니다.

2021-11-03 07:19 UTC, AppleCEO requested changes
니꼴라스, 고사리 고생하셨습니다.
여러가지 도전해보고 시도해보는 것 아주 좋아보입니다!
아래 코멘트들 한번 확인해주세요.

updateStock 메서드를 두 가지 로직으로 구현해보았습니다. 전자의 경우 유지보수가 용이하며, 후자의 경우 직관적이므로 가독성이 올라가는 것으로 판단됩니다. 도미닉은 어떤 방식을 선호하시나요?
- 생활코딩에서도 많이 나오는 말인데 한번 과일의 종류가 100개, 1억개가 된다고 상상해보면 좋을 것 같습니다.

makeCurrentAllStock 함수명 관련해서 이전 PR 커멘트에는 보여진다로 기재되었는데 잘못된 기재였습니다. 해당 함수는 현재 label의 text의 값들을 배열로 만들어 리턴해주는 역활입니다. 함수명 관련 고민중 api 디자인 가이드라인을 확인해봤는데 함수명에 명사를 사용한 예시를 포착했습니다. 해당 함수명을 currentAllStocks 이렇게 생각해 보았는데 어떠신가요?
- 오.. 좋은 것 같습니다. 저도 공식 문서를 보다가보니 메소드명을 명사로 사용하는 경우를 보았습니다. 이럴 때 활용할 수 있는 방법인 것 같습니다.

enum을 새롭게 정의하고 원시값을 [fruit]으로 설정해봤지만, enum의 원시값은 문자열, 문자, 또는 정수 또는 부동소수 타입만 가능하므로 불가했고 추가적인 방법은 찾지 못했습니다.
- Associated Values 를 활용해보는 방법이 있을 것도 같네요~

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet var needToChangeButtonsFontSize: [UIButton]!
이 이름은 버튼의 목록이 아니라 폰트 사이즈의 목록으로 오해할 수 있을 것 같습니다. 😢

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      }
뷰가 로드될 때 어떤 동작이 필요한지 그리고 폰트 사이즈를 수정해야 하면 viewDidLoad가 아닌 setButtonFontSize() 메소드를 수정하면 되도록 알기 쉬워서 유지보수가 좋아진 것 같습니다 👍

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet var fruitQuantityStepper: [UIStepper]!
위에 label 타입의 배열을 Labels 라고 복수형으로 했던 것처럼  Stepper 배열도 변수명을 변경해보면 좋겠습니다! 👍

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        }
훨씬 보기 좋아진 것 같습니다. 🔢 
labelTexts.append(String(label.text ?? "0")) 이 줄은 조금 복잡한 것 같습니다.
String(label.text ?? "0") 코드를 상위에서 상수에 넣어주는 것은 어떨까요?

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        }
및 이나 와, 과 같이 연결해주는 단어가 커밋 메시지에 쓰이면 잘못된 가능성이 높습니다.
<refactor: setFruitQuantityStepper 함수 개선> 커밋 하나,
<fruitQuantityLabels, fruitQuatitySteppers 배열 선언> 커밋 하나가 있으면 나중에 찾아보기 더 좋을 것 같습니다.

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        fruitQuantityLabels[sender.tag].text = String(Int(sender.value))
String(Int(sender.value)) 코드는 한 눈에 알아보기 어렵습니다.
형 변환이나 . 으로 타고 들어가는 것은 한 줄에 한번만 하는 것이 좋습니다.
개선해보면 좋겠습니다~

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +                                    Fruit(name: .mango, quantity: Int(fruitQuantityStepper[4].value))]
?? 0 으로 기본값을 넣어주던 부분이 없어져서 훨씬 깔끔해졌습니다. 💯

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +                                    Fruit(name: .mango, quantity: Int(fruitQuantityStepper[4].value))]
?? 0 과 같이 기본값을 꼭 넣어줘야 한다면 이 초기화 함수 밖에서 상수에 넣어주고 초기화 함수에서는 그 상수명만 넣어주는 것이 가독성이 좋습니다.

2021-11-03 07:19 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet var fruitQuatityLabels: [UILabel]!
많이 시도해보고 여러가지 수정해보셨군요. 이렇게 하나를 만들더라도 여러가지 방식(배열에 넣어보는 방법, 따로 변수에 넣어주는 방법, 딕셔너리를 사용하는 방법 등)을 해보고 어떤 것이 좋은지 고민해보고 하는 것은 좋은 자세라고 생각합니다. 🥇

2021-11-04 05:58 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet var needToChangeButtonsFontSize: [UIButton]!
needToChangeFontSizeButtons 으로 변경했습니다.🙉

2021-11-04 06:00 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet var fruitQuantityStepper: [UIStepper]!
fruitQuantitySteppers 로 수정했습니다!!!

2021-11-04 06:40 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        }
```swift
func setFruitQuantityStepper() {
        var labelTexts = [String]()
        
        for label in fruitQuantityLabels {
            guard let labelText = label.text else {
                return
            }
            
            labelTexts.append(labelText)
        }
        
        for index in 0...fruitQuantityLabels.count - 1 {
            guard let labelTextsIndex = Int(labelTexts[index]) else {
                return
            }

            fruitQuantitySteppers[index].value = Double(labelTextsIndex)
        }
    }
```
요렇게 개선해 봤습니다~!

2021-11-04 06:49 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        fruitQuantityLabels[sender.tag].text = String(Int(sender.value))
소중한 가르침 감사합니다.🙇🏻
아래와 같이 개선했습니다.
```swift
@IBAction func touchUpFruitQuantityStepper(_ sender: UIStepper) {
        let changedFruitQuantityLabels = fruitQuantityLabels[sender.tag]
        let stepperValue = Int(sender.value)

        changedFruitQuantityLabels.text = String(stepperValue)
}
```

2021-11-05 03:24 UTC, Kim-EunsooSilver commented
🙇🏻도미닉 안녕하세요~!

보너스(^^;)과제 관련해서 저희의 의견을 공유드립니다.
### 도미닉의 방법
```swift
protocol JuiceMenuProtocol {
  func showRecipe(_: JuiceMenu) -> JuiceMenus.Juice
}

enum JuiceMenus: JuiceMenuProtocol {
  enum Juice {
    case oneFruitRecipe(Fruit)
    case multiFruitRecipe([Fruit])
  }
  
  func showRecipe(_ juiceMenu: JuiceMenu) -> JuiceMenus.Juice {
    switch juiceMenu {
    case .bananaJuice:
      return Juice.oneFruitRecipe(Fruit(name: .banana, quantity: IngredientsQuantity.bananaOfBananaJuice))
    case .ddalbaJuice:
      return Juice.multiFruitRecipe([Fruit(name: .strawberry, quantity: IngredientsQuantity.strawberryOfDdalbaJuice), Fruit(name: .banana, quantity: IngredientsQuantity.bananaOfDdalbaJuice)])
    case .kiwiJuice:
      return Juice.oneFruitRecipe(Fruit(name: .kiwi, quantity: IngredientsQuantity.kiwiOfKiwiJuice))
    case .mangKiJuice:
      return Juice.multiFruitRecipe([Fruit(name: .mango, quantity: IngredientsQuantity.mangoOfMangKiJuice), Fruit(name: .kiwi, quantity: IngredientsQuantity.kiwiOfMangKiJuice)])
    case .mangoJuice:
      return Juice.oneFruitRecipe(Fruit(name: .mango, quantity: IngredientsQuantity.mangoOfMangoJuice))
    case .pineappleJuice:
      return Juice.oneFruitRecipe(Fruit(name: .pineapple, quantity: IngredientsQuantity.pineappleOfPineappleJuice))
    case .strawberryJuice:
      return Juice.oneFruitRecipe(Fruit(name: .strawberry, quantity: IngredientsQuantity.strawberryOfStrawberryJuice))
    }
  }
  
  enum IngredientsQuantity {
      static let strawberryOfStrawberryJuice = 16
      static let bananaOfBananaJuice = 2
      static let kiwiOfKiwiJuice = 3
      static let pineappleOfPineappleJuice = 2
      static let mangoOfMangoJuice = 3
      static let strawberryOfDdalbaJuice = 10
      static let bananaOfDdalbaJuice = 1
      static let mangoOfMangKiJuice = 2
      static let kiwiOfMangKiJuice = 1
  }
}
```

### 저희의 개선방법
```swift
static let recipe = [[Fruit(name: .strawberry, quantity: JuiceMenu.IngredientsQuantity.strawberryOfStrawberryJuice)],
                         [Fruit(name: .banana, quantity: JuiceMenu.IngredientsQuantity.bananaOfBananaJuice)],
                         [Fruit(name: .kiwi, quantity: JuiceMenu.IngredientsQuantity.kiwiOfKiwiJuice)],
                         [Fruit(name: .pineapple, quantity: JuiceMenu.IngredientsQuantity.pineappleOfPineappleJuice)],
                         [Fruit(name: .mango, quantity: JuiceMenu.IngredientsQuantity.mangoOfMangoJuice)],
                         [Fruit(name: .strawberry, quantity: JuiceMenu.IngredientsQuantity.strawberryOfDdalbaJuice),
                          Fruit(name: .banana, quantity: JuiceMenu.IngredientsQuantity.bananaOfDdalbaJuice)],
                         [Fruit(name: .mango, quantity: JuiceMenu.IngredientsQuantity.mangoOfMangKiJuice),
                          Fruit(name: .kiwi, quantity: JuiceMenu.IngredientsQuantity.kiwiOfMangKiJuice)]]

var ingredients: [Fruit] {
    JuiceMenu.recipe[self.rawValue]
}
```
# 우리가 후자를 선택한 이유
* 도미닉의 방법 및 이전 저희가 구현했었던 코드는 주문이 들어올때마다 인스턴스를 생성후 참조값을 리턴하는 방식입니다.
* 저희가 개선한 코드는 앱이 구동할 때 최초 1회만 각 쥬스 레시피의 인스턴스를 생성후, 주문이 들어오면 참조값을 리턴합니다.
* 성능적으로 보았을 때 🤔🧐
    * 주문이 들어올때마다 생성을 해주는게 성능적으로 소모가 된다고 생각했습니다.
        * 예를 들어 딸기 쥬스 10개의 주문이 들어올 경우
            * 전자: (Fruit() -> return) * 10: 주문이 들어올때마다 레시피 북을 10번 펼친다(?)
            * 후자: (Fruit()) * 1 -> return * 10: 주문이 들어올때마다 벽에 붙여둔 레시피를 10번 확인한다(?)
---
도미닉의 의견은 어떠신가요?

2021-11-05 05:01 UTC, AppleCEO requested changes
nicholas & 고사리 고생하셨습니다.
적극적으로 소통하고 성장하고자 노력하는 모습 보기 좋았습니다.
몇가지 생각할 점들 남겨봤습니다.

저는 recipe 코드를 보기가 힘든 점들이 좀 고민이됩니다.
배열에 과일 타입들이 2차원으로 채워지는데 이게 어떤 주스의 레시피인지 제가 드린 코드가 조금 더 명확하게 드러난다고 생각합니다.

2021-11-05 09:31 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +                                   quantity: Int(fruitQuantityLabels[index].text ?? "0") ?? 0))
아래와 같이 수정했습니다 ^.<

```swift
for index in 0...fruitQuantityLabels.count - 1 {
    guard let fruitQuantityLabelText = fruitQuantityLabels[index].text else {
        return
    }
            
    updatingFruitsQuantity.append(Fruit(name: fruitNames[index],
                           quantity: Int(fruitQuantityLabelText) ?? 0))
}
```

2021-11-05 09:35 UTC, Kim-EunsooSilver commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +
🧐처음 팀 그라운드 룰 정할때 저와 고사리가 합의하여 컨벤션을 정했습니다.
다른 소스 코드들과 비교해 보시면 gurd 구문 다음에는 공백라인이 있습니다...
줄바꿈의 의미...?라기에는 뭐하지만 저희가 이렇게 합의한 이유는 좀더 소스보기에 적합하다고 생각했습니다.

2021-11-05 09:40 UTC, Kim-EunsooSilver commented
🤗🤗도미닉!!!! 
`recipe` 를 딕셔너리로 구현해 보았습니다.
말씀하셨던 어떤 쥬스의 레시피인지에 대한 모호성을 키 값을 이용하여 어떤 쥬스의 레시피인지 명확히 구분할 수 있을거 같다고 저희는 생각했습니다.
혹시 저희가 개선한 부분에 대해서 부족한 부분이 있다면 말씀 부탁드리도록 하겠습니다. 🙇🏻

2021-11-06 01:22 UTC, merged

2021-11-06 01:22 UTC, AppleCEO commented
3주동안 고생 많으셨어요~