쥬스 메이커 [STEP3] 예거, Yohan
yagom-academy/ios-juice-maker pull request #137
Opened 2021-11-02 13:53 UTC by YohanBlessYou

@lina0322 @Jager-yoo)
안녕하세요 엘림~ 
벌써 마지막 STEP PR이네요!
이번 PR도 잘 부탁드려요ㅎㅎ 🙏🏻
(예거, 요한 9모둠입니다!)

이번에도 고민했던 점과 궁금한 점으로 정리해봤어요

---

## 🐶 고민했던 점 

### 1. Modal 전환임에도 Navigation Controller를 하나 더 추가한 이유
Modal로 전환되는 화면의 경우, Navigation Controller에 의해 자동으로 Navigation Bar가 생성되지 않으나, 프로젝트 구현 요구사항으로 첫 번째 화면과 (modal로 전환될)두 번째 화면이 동일한 디자인의 Navigation Bar를 가져야 했습니다

그래서, Navigation Bar를 수동으로 만드는 것보다, Navigation Controller를 하나 더 만들어 자동으로 만들어주는게, 유지보수나 확장성 측면에서 더 나은 것 같다고 판단했습니다!
<br>
### 2. KVO를 도입하려다 문제가 있어, NotificationCenter로 구현
app에는 두 개의 뷰컨이 존재하며 두 뷰컨은 하나의 Model(`FruitStore`)를 참조하여 Label 값을 display하고 있습니다.
거기에, 두 뷰컨 모두에서 Model의 값을 수정할 수 있으므로 동기화 작업도 필요하였습니다. (한 뷰컨이 Model을 수정하면 다른 뷰컨에서 이를 감지하고 자신의 View를 업데이트하도록)

이를 위해, 3가지 (싱글톤+노티센터 / KVO / 프로퍼티옵저버)를 고려해보았고, 가장 먼저 KVO를 적용시도해보았는데 문제가 있었습니다
값 변경 감시대상인 `FruitStore`의 과일 재고를 저장하는 `inventory`라는 프로퍼티가 dictionary인데 key의 타입이 `enum`이어서 `NSObject`를 상속할 수 없어 KVO 사용이 불가했습니다 😂😂

그래서 NotificationCenter로 구현하게 되었습니다.
(delegate 패턴은 배우면 하려고 아껴뒀습니다ㅎㅎ...)
<br>
### 3. 두번째 화면에서 재고 수정한 것을, 첫 화면의 view로 언제 update시킬 것인가? (modal이 종료될 때?)

우선, 두 번째 화면의 stepper의 값을 변경하면 실시간으로 Model의 값도 변경하도록 구현하였습니다 (+Label도)
그러므로, 첫 번째 화면의 Label이 정상적으로 업데이트되려면 단지 Model의 값을 읽어오기만 하면 됩니다
두 번째 화면을 dismiss 하는 버튼을 누르는 시점에, `post`를 보내어 첫 번째 화면이 변경된 Model을 읽어 Label을 업데이트하도록 구현하였습니다

사실 일반적으론 Modal을 dismiss하는 방법으로 버튼을 누르는 게 아닌 gesture도 있으므로 버튼 Action에 넣는게 적절하지 않지만, landscape only App이므로 gesture 사용이 불가해 버튼 Action이 유일한 dismiss 방법이므로 `post`를 구현하였습니다
<br>
### 4. Auto Layout 추가 적용
프로젝트 제약사항 중 오토레이아웃을 적용해보라는 사항이 있었습니다

이미 거의 적용되어 있었어서 다양한 device에서 테스트해봤을 때 대부분 문제가 없었습니다.
다만, 화면이 작은 device에서 버튼 title이 긴 경우, "..."으로 축약되어 보이지 않는 점이 있어 이를 개선해보았습니다

우선, `adjustFontSizeToFitWidth`를 true로 설정하여 축약되지 않게 설정하였습니다
그리고, 버튼 title이 버튼의 border와 너무 붙어있어서 스토리보드 Attribute Inspector에 있는 title-insets를 적용했어요
(그러고보니... 얘네는 오토 레이아웃의 범주가 맞나요..?)
<br>
### 기타
- ViewController 파일명과 타입이름을 명확하게 변경하였습니다
(`ViewController` -> `JuiceOrderViewController`)
- NotificationCenter는 `Foundation` Framework에 구현되어 있다!(import필요)
- 스토리보드 Attribute Inspector의 'Line Break'의 `Truncate Options`는 text가 길어져서 생략되어야 할 때, 그 생략 지점을 의미한다
- viewDidLoad가 끝나지 않으면, viewWillAppear가 실행되지 않는다는 사실 발견 (유저가 View를 볼 수 없다)

---

## 🤔  궁금한 점

### 1. NotificationCenter.addObserver 메서드에서 #selector에 throws 메서드를 try없이 사용할 수 있는 이유가 궁금해요

아래 예제에서 selector 함수로 지정해준 `updateAllFruitAmountLabels`는 에러를 던지는 메서드인데 `try`가 없어도 잘 동작하는 이유가 궁금합니다!
```swift
notificationCenter.addObserver(self,
                                    selector: #selector(updateAllFruitAmountLabels),
                                    name: .didEditAmount,
                                    object: nil)
```
<br>
### 2. Notification.Name 인스턴스를 생성하는 방식
원래는 전역변수로 생성하여 사용했는데 블로그 예제들을 보니 죄다 extension으로 구현을 해놓아서 어떤 장점이 있길래 extension으로 구현하는걸까 고민해보았습니다

```swift
// 원래 사용하던 전역변수 방식
let notiName = Notification.Name("value was changed")

// extension방식
extension Notification.Name {
    static let notiName = Notification.Name("value was changed")
}
```

저희가 생각해본 바로는, 이렇게 extension을 활용하여 타입 프로퍼티로 정의하면 `addObserver`에서 사용할 때, dot만 입력해도 사용가능한 Name의 목록이 나오므로 여기저기 코드가 흩어져있는 NotificationCenter의 특성 상, 사용하기 편해서이지 않을까하고 생각해봤어요!
(왜 다들 extension을 쓰는걸까요? 어떤 장점이 있길래🤔)

현업에서나 엘림은 이런식으로 extension 방식을 사용하는지 궁금해요!

---

## 🦊 추가로 해보고 싶은 것
1. STEP2 PR에서 fatalError에 대해 피드백주셨었는데 이를 Alert로 유저에게 알리고 3초 후에 app이 종료되도록 구현해볼까 싶어요 (Alert -> sleep 3초 후 fatalError)

2. Stepper에도 selection스타일 햅틱을 넣어줄까 싶습니다! 유저 interaction 차원에서 Stepper는 피드백이 없으면 많이 허전한 것 같아요

2021-11-03 03:39 UTC, YohanBlessYou commented
#### [ 추가 Comment ]
**fatalError를 Alert+`exit()`으로 대체해봤어요!**

exit 안에 들어가는 exit status code는 [Stackeoverflow](https://stackoverflow.com/questions/2434592/difference-in-system-exit0-system-exit-1-system-exit1-in-java)를 참고하였고
app 구조상 절대 실행되지 않을 코드라 unexpected system error로 분류하여 -1로 주었습니다

```swift
private func showAppTerminatingAlert() {
    let title = "시스템 오류가 발생했습니다."
    let message = "앱이 5초 뒤 종료됩니다...\n개발자에게 문의해주세요."
    let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
    let terminateAction = UIAlertAction(title: "지금 종료", style: .destructive) { _ in
        exit(-1)
    }
    
    alert.addAction(terminateAction)
    present(alert, animated: true) {
        sleep(5)
        exit(-1)
    }
}
```

![image](https://user-images.githubusercontent.com/39155090/140005580-5104779c-dce6-4e64-aa16-bee543c7bb0d.png)

2021-11-03 06:11 UTC, Jager-yoo commented
**[ 추가 Comment ]**

### `Stepper` 가 눌릴 때, `약한 햅틱 피드백`이 발생하는 기능을 추가했습니다. 

유저가 버튼과 인터랙션할 때 더 좋은 경험을 느끼게 해주고 싶었어요!
햅틱 피드백에는 3가지 타입이 있습니다. 저희는 아래 3가지 중에서, `Notification` 과 `Selection` 타입을 선택해서 사용했습니다

![image](https://user-images.githubusercontent.com/71127966/140016105-573e0f3f-7d69-4bd2-bd29-77700d5d88d2.png)

```swift
// [JuiceOrderViewController] 에는 UINotificationFeedbackGenerator 타입의 인스턴스 생성
private let feedbackGenerator = UINotificationFeedbackGenerator()

// [JuiceOrderViewController] 쥬스 주문이 성공했을 때
feedbackGenerator.notificationOccurred(.success)

// [JuiceOrderViewController] 재고가 없어서 Alert Modal 이 뜰 때
feedbackGenerator.notificationOccurred(.warning)

// [EditAmountViewController] 에는 UISelectionFeedbackGenerator 타입의 인스턴스 생성
private let feedbackGenerator = UISelectionFeedbackGenerator()

// [EditAmountViewController] Stepper 가 눌릴 때
feedbackGenerator.selectionChanged()
```

2021-11-03 11:39 UTC, lina0322 requested changes
안녕하세요 두분!
마지막 스텝까지 열심히 달려왔네요!! 멋집니다~

### 1. Modal 전환임에도 Navigation Controller를 하나 더 추가한 이유
> Navigation Bar를 수동으로 만드는 것보다, Navigation Controller를 하나 더 만들어 자동으로 만들어주는게, 유지보수나 확장성 측면에서 더 나은 것 같다고 판단했습니다!

저는 이 말이 조금 이해가 잘 안갔는데요! 왜 자동으로 생성해주는게 유지보수나 확장성 측면에서 나은 것 같나요?
또 어짜피 navigation bar가 필요한거라면, modal로 하지 않고 push를 했다면 화면만 생각했을땐 오히려 간편하지 않은가요?😀

### 2. delegate
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ그러면 다음에 배울때 완전 꼼꼼하게 하기로 약속해요

### 3. 언제 update시킬 것인가?
그냥 이건 생각해보시라고 드리는 질문인데!
만약에 modal이 아니었다면 viewLifeCycle로도 변경시킬 수 있었을까요??

### 4. viewDidLoad가 끝나지 않으면, viewWillAppear가 실행되지 않는다는 사실 발견
viewDidLoad와 같은 view와 관련된 메소드들을 순서대로 설명해 줄 수 있나요?!

### 5.  #selector에 throws 메서드를 try없이 사용할 수 있는 이유
오, 저는 생각해본적이 없는 포인트네요!!
멋집니다. 이런 부분까지 고민해보고!
흠, 그런데 대답은 글쎄요.. 지금 생각에는 selector, ojbc의 특성일것 같은데 한번 함께 알아볼까요!!💪

### 6. Notification.Name은 String이죠.
이름으로 서로를 구분하는데 대,소문자까지 일치해야하며 오타가 생기면... 당연히 안돌아가겠죠?
보통 string이나 특정한 매직넘버들은 따로 저장해서 사용하게 좋죠.
그런 관점에서 저도 Notification.Name은, 관리측면에서 extension 해서 사용하는 것이 더 편하다고 느끼고 사용했습니다!

---

멋집니다. 여러분! 매번 놀라움을 안겨주네요~👍

2021-11-03 11:39 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/EditAmountViewController.swift
>      }
오, 좋은 시도에요:)
공부할 것이 참 많이 생겼어요~~

1. 과연 애플은 exit를 권장할까요? 그래도 꼭 사용해야한다면 어떻게해야 애플이 OK 할까요?🥺
2. exit() 함수를 사용했을때 부작용은 없을까요? 다른 방식으로 앱을 종료할 수는 없을까요??
3. 여러분 지금 이 alert가 실제로 발생했을때 OK 버튼이 눌리나요?😉

2021-11-03 11:39 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +class JuiceOrderViewController: UIViewController {
크, 이름을 바꾸다니 좋습니다!

2021-11-03 11:39 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    private let feedbackGenerator = UINotificationFeedbackGenerator()
변경한 이유를 설명해줄 수 있나요:)

2021-11-03 11:39 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    @objc private func updateAllFruitAmountLabels() throws {
왜 objc가 붙을까요?😀

2021-11-03 11:39 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        let terminateAction = UIAlertAction(title: "지금 종료", style: .destructive) { _ in
알람의 style에는 어떤게있고, 어떨때 어떤 스타일을 사용하는게 좋을까요?🙂

2021-11-03 11:39 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    }
스토리 보드에 있는
<img width="264" alt="스크린샷 2021-11-03 오후 8 12 11" src="https://user-images.githubusercontent.com/49546979/140050494-a9e32c0b-9418-42a5-9e38-b754b961dd88.png">
이 설정과 차이가 있을까요??😀

2021-11-03 11:39 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/NotificationCenter.swift
> +let notificationCenter: NotificationCenter = NotificationCenter.default
NotificationCenter.default가 이미 전역적으로 사용이 가능한데, 따로 전역변수로 선언한 이유가 있나요?😄

2021-11-04 07:25 UTC, Jager-yoo commented
안녕하세요 엘림! 빠르게 리뷰해주셔서 감사합니다.
요한과 함께 다시 대댓글 작성해봅니다. 😄 

## Modal 전환임에도 Navigation Controller를 하나 더 추가한 이유

> (저희 의견) Navigation Bar를 수동으로 만드는 것보다, Navigation Controller를 하나 더 만들어 자동으로 만들어주는게, 유지보수나 확장성 측면에서 더 나은 것 같다고 판단했습니다!

> (엘림 코멘트) 저는 이 말이 조금 이해가 잘 안갔는데요! 왜 자동으로 생성해주는게 유지보수나 확장성 측면에서 나은 것 같나요?
또 어짜피 navigation bar가 필요한거라면, modal로 하지 않고 push를 했다면 화면만 생각했을땐 오히려 간편하지 않은가요?😀

저희가 STEP 2 까지는 두번 째 화면을 `Modal` 이 아닌, 네비게이션 컨트롤러로 `Push` 를 해주는 식으로 만들었다가
STEP 2 PR 리뷰에서 대화나눴듯이, 맥락 상 `Modal`을 사용하는 게 더 적절한 것 같았습니다.

![image](https://user-images.githubusercontent.com/71127966/140273424-a4f79988-8f34-4180-ad39-67bbc12917d3.png)

화면 전환을 `Modal`로 변경한 이후에, STEP 3 요구사항을 확인해보니, 상단에 `Navigation Bar` 형태를 만들어줘야 하더라구요.
저희는 2가지 방법을 떠올렸는데요, 하나는 라이브러리에서 Navigation Bar 를 들고와서 View 에 `직접 추가`하는 것이고, 하나는 Navigation Controller 를 하나 더 추가함으로써 `자동으로` Bar 모양을 만들어주는 방법이었습니다.

앞의 방법으로 시도하다가, 디자인을 동일하게 맞추는 게 번거롭고, 만약 화면이 더 추가된다면 이런 Bar 를 복사해서 계속 붙여넣어야 하는 과정이 불편함을 줄 것이라 생각했습니다.

그래서 `Modal` 앞에 Navigation Controller 를 추가해줬고, 이렇게 하면 이후에 구현하는 화면들이 모두 동일한 디자인의 Navigation Bar 를 가지게 할 수 있으니 `유지보수/확장성` 측면에서 더 나은 것 같다고 판단했어요. 😄 

<br>

## 두번째 화면에서 재고 수정한 것을, 첫 화면의 view로 언제 update시킬 것인가? (modal이 종료될 때?)

> (엘림 코멘트) 그냥 이건 생각해보시라고 드리는 질문인데! 만약에 modal이 아니었다면 viewLifeCycle로도 변경시킬 수 있었을까요??

네. `Modal`이 아니었다면 저희는 `LifeCycle` 을 이용해서 화면 간의 정보 전달을 구현했을 것 같습니다.

두 번째 화면이 dismiss 될 때, 첫 번째 화면의 `viewWillAppear()`, `viewDidAppear()` 메서드 안에 과일 재고의 Label 업데이트하는 메서드를 넣어두면 가능합니다! 👍🏻 

저희가 `Modal`로서 구현하느라 위 방법으로 접근하지 못했지만, Modal 의 `Presentation 스타일`을 `full-screen`으로 변경한다면, 첫 번째 화면의 `viewWillAppear()`, `viewDidAppear()` 메서드를 이용할 수 있다는 걸 알고 있었습니다.

하지만 일부로 `Portrait 화면`(세로모드)에서 가능한 `Page Sheet` 스타일의 Modal 이라고 가정하고, `LifeCycle` 을 이용하지 않는 화면 간의 데이터 전달을 고민해봤던 거였어요 ㅎㅎㅎ

<br>

## ViewController Life Cycle

> (엘림 코멘트) viewDidLoad와 같은 view와 관련된 메소드들을 순서대로 설명해 줄 수 있나요?!

![image](https://user-images.githubusercontent.com/71127966/140268734-ae17b107-b342-4aa2-8d61-051ef7e9f2e2.png)

넵 엘림! 우선, `ViewController Life Cycle` 은 야곰 활동학습 시간에 배운 개념이고, 저희도 따로 추가 학습을 진행했습니다.

위 이미지를 보면서 설명 드리겠습니다.

- `init` -> 뷰컨의 인스턴스를 생성합니다.
- `loadView` -> 뷰컨이 가지고 있는 view 프로퍼티를 메모리에 올리는 메서드입니다.
- `viewDidLoad` -> view 가 메모리에 완전히 올라간 이후에 호출됩니다. 여기에서는 아직 사용자는 화면을 시각적으로 볼 수 없습니다.
- `viewWillAppear` -> view 가 화면에 실제로 나타나기 직전에 호출되는 메서드입니다.
<📱 이 사이에서 사용자가 구현된 화면을 볼 수 있습니다 !! >
- `viewDidAppear` -> view 가 화면에 나타난 뒤 호출되는 메서드입니다.
- `viewWillDisappear` -> view 가 화면에서 사라지기 직전에 호출되는 메서드입니다.
- `viewDidDisappear` -> view 가 화면에서 사라진 뒤 호출되는 메서드입니다. ( ⚠️ 아직 view 의 메모리는 해제되지 않은 상태입니다.)
- `viewDidUnload` -> view 가 메모리에서 내려간 이후에 호출되는 메서드입니다. Navigation Controller 계층에서 화면이 pop 될 때, 뷰컨의 인스턴스가 해제되며 view 또한 메모리에서 해제됩니다.

<br>

## #selector에 throws 메서드를 try없이 사용할 수 있는 이유

> (엘림 코멘트) 오, 저는 생각해본적이 없는 포인트네요!! 멋집니다. 이런 부분까지 고민해보고!
흠, 그런데 대답은 글쎄요.. 지금 생각에는 selector, ojbc의 특성일것 같은데 한번 함께 알아볼까요!!💪

ㅎㅎㅎ 스위프트도 이제 배우는 중인데, Objective-C 개념까지 나오니까 많이 어렵더라구요 😢 
우선, 요한과 `#selector`의 개념을 더 찾아보고 정리해봤습니다!

스위프트에서 함수는 `1급객체`입니다. 그래서 상수나 변수에 함수 자체를 저장하거나, 다른 함수의 argument 로 넘길 수 있는데요.

Objective-C 에서의 함수는 위와 같이 사용할 수 없습니다. 함수의 주소값을 저장할 수 있는 타입이 딱 정해져있는데요. 그게 `Selector` 입니다.

`#selector()` 의 괄호 안에 함수를 넣어야, 스위프트의 `1급객체` 처럼 사용할 수가 있는데요.
아쉽게도 #selector() 에 순수 스위프트 함수를 넣으면 인식하지 못합니다.

Objective-C 에 인식시키기 위해서는 selector 안에 넣을 메서드의 정의부 앞에 `@objc` 특성을 추가해주어야 합니다!

```swift
@objc private func updateAllFruitAmountLabels() throws {
    ...
}
```

그리고 저희가 실험을 해봤는데, selector 안에 들어간 메서드가 에러를 던지게 되면, `런타임 에러`가 터지더라구요. 🤔 
Objective-C 의 에러 핸들링 방식이 스위프트와 다르기 때문이지 않을까 싶어요.

결론은, 지금 상황에서 안전하게 코드를 고쳐야 한다면 selector 안에 들어갈 메서드를 `에러를 던지지 않는 메서드`로 고쳐줘야 할 것 같습니다! 👍🏻

2021-11-04 08:50 UTC, YohanBlessYou commented on JuiceMaker/JuiceMaker/Controller/EditAmountViewController.swift
>      }
> 1. 과연 애플은 exit를 권장할까요? 그래도 꼭 사용해야한다면 어떻게해야 애플이 OK 할까요?🥺

https://developer.apple.com/library/archive/qa/qa1561/_index.html

![image](https://user-images.githubusercontent.com/39155090/140278053-409e70c6-cf0d-4978-9d2e-8e81497bbcb6.png)

말씀해주신대로 `exit`은 유저에게 crash가 발생한 것으로 비춰져 애플이 사용을 금하고 있었어요. 
"graceful termination  / animating back to the Home screen"이라는 문구로 보아 app 종료가 필요하면 유저가 crash처럼 느끼지 않도록 우아하게(?) 하고  Home 화면으로 부드럽게 나가지도록(?) 하라는 것으로 해석했습니다!

---

> 2. exit() 함수를 사용했을때 부작용은 없을까요? 다른 방식으로 앱을 종료할 수는 없을까요??

**부작용**
`exit`은 app을 강제종료시키므로, 유저 정보를 백업하는 코드를 종료되기 전에 수행하도록 챙겨야 합니다
그리고, exit으로 인해 crash처럼 꺼지면 App 심사도 탈락한다는 글도 있네요!

**다른 방식**
app 종료를 유발하는 메서드는 `exit` 외에는 찾지 못했습니다. 다만, 1번에서 살펴봤던 것처럼 graceful한 종료를 위해, 홈화면으로 부드럽게 나간 후 background에서 `exit`을 호출하여 crash처럼 종료되지 않도록 하는 방식이 있을 것 같아요

---

> 3. 여러분 지금 이 alert가 실제로 발생했을때 OK 버튼이 눌리나요?😉

`sleep`은 유저가 화면과 interaction을 할 수 없게 만듭니다(frozen) 테스트를 꼼꼼히 하지 못했네요🥲
의도대로 구현하려면 `sleep` 대신 `Timer`를 등록하는 등의 방식을 사용해야 할 것 같아요

2021-11-04 08:53 UTC, YohanBlessYou commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    private let feedbackGenerator = UINotificationFeedbackGenerator()
사실 예제를 퍼오면서 var까지 가져와버렸는데..😅 
`feedbackGenerator`를 변경할 일이 없어서 상수로 변경해주었습니다!

2021-11-04 08:55 UTC, YohanBlessYou commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    @objc private func updateAllFruitAmountLabels() throws {
요건 아래 큰 댓글에 같이 설명을 남겨놓았는데요~ 
Objective-C runtime에서 사용하기 위해 순수 Swift 메서드에 objc attribute를 붙혀주었습니다!

2021-11-04 09:10 UTC, YohanBlessYou commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        let terminateAction = UIAlertAction(title: "지금 종료", style: .destructive) { _ in
알람과 관련한 `preferredStyle`에는 `Alert`와 `Action Sheet`가 있었어요
H.I.G 문서를 기반으로 정리해보았습니다~

첫 번째로, 근본적인 용도 차이!
- Alert : app이나 device의 상태정보 알림 / 유저에게 feedback 요청하는 경우
- Action Sheet : 현재 context와 관련된 선택지를 제시

다음으로, Alert가 필요한 경우더라도 선택지(action)가 3개 이상이면 Action sheet를 고려

2021-11-04 09:15 UTC, YohanBlessYou commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    }
저희도 스토리보드에 있을 것 같아서 열심히 찾아봤었는데 (Label에는 있는데) 버튼 title에 적용해주는걸 찾지 못했습니다🥲

첨부해주신 이미지처럼 스토리보드에서 설정하는 방법은 혹시 Label에만 존재하는걸까요...

2021-11-04 09:17 UTC, YohanBlessYou commented on JuiceMaker/JuiceMaker/Controller/NotificationCenter.swift
> +let notificationCenter: NotificationCenter = NotificationCenter.default
이름이 길기도 해서 편하게 사용하려고 별도의 상수를 할당해주었습니다!
예제들에서 저렇게 많이 하길래 습관적으로 한 부분도 있는 것 같아요😅

2021-11-04 12:12 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    }
맞아요! 같은 설정이고 여러분이 하신 것 처럼 Button은 코드에서만 가능해요~👍

2021-11-04 12:14 UTC, merged

2021-11-04 12:33 UTC, YohanBlessYou commented
![ScreenRecording Nov 4, 2021 9:32:18 PM](https://user-images.githubusercontent.com/39155090/140314045-d08d5482-3684-41f3-8a7d-d3c87a916e2c.gif)
kkk

2021-11-04 12:35 UTC, Jager-yoo commented
## 우아한 앱종료 (mp4 버전)
https://user-images.githubusercontent.com/71127966/140314205-83c07faf-ce7a-4936-aa20-0987682271a3.mp4