쥬스메이커 [STEP 3] : 호랭이, aCafela coffee
yagom-academy/ios-juice-maker pull request #139
Opened 2021-11-04 09:31 UTC by horeng2

팀원 : @horeng2, @aCafela-coffee

안녕하세요. @corykim0829
쥬스메이커 [STEP 3] PR 제출합니다.

고민했던 점, 조언을 얻고 싶은 부분 함께 작성했습니다.
마지막 스텝 피드백도 잘 부탁드립니다.
감사합니다.😀

## 고민했던점 & 조언을 얻고 싶은 부분

- stepper를 사용하는 방법
    - 처음에는 버튼과 비슷하게 생각하여 값을 계산해서 다시 넣어주는 함수를 쓰려고 했는데, 같이 공부하다보니 버튼과는 다르게 IBOutlet과 stepper의 값을 이용할 수 있다는 점을 깨달아서 이부분을 적용했습니다.
- 접근제어에 관련한 고민
    - 프로젝트 코드 안에서 해당 객체에 접근할만한 가능성이 없는 경우에도 접근제어를 설정해주는 것이 바람직할까요? 예시: `@IBAction private func`
- weak가 @IBOutlet 등을 선언할때만 자동으로 붙는 이유는 뭘까?
    - var 이외에 아무 수식어도 붙지 않는 strong이 디폴트값이라고 생각되는데 @IBOutlet을 선언할때만 자동으로 붙는 이유는 무엇일까 고민했습니다.
    - strong을 사용하는 경우, 뷰가 해제된 이후에도 레이블에 접근할 수 있지만, weak를 사용하는 경우에는 뷰가 해제되면서 레이블이 같이 해제된다고 이해했습니다. 
    혹시 이런 이유 때문에, 다른 뷰에서 해당 뷰의 레이블에 접근할 경우가 없기 때문에? weak가 자동으로 붙는 걸까요?
- 화면 사이의 데이터 공유에 관한 부분
    - 저희는 fruitStore를 두번째 뷰에서 사용해서 이부분을 해결했는데, 다른 캠퍼들과 이야기를 나누다보니 다른뷰나 클래스를 참조하지 않고 데이터 공유를 하는 방법에 대한 피드백을 많이 받았다고 들었습니다. 일단 저희는 이번주 시간이 많이 남지 않아서...다시 코드를 고치지 않고 일단 PR을 제출한 후에 피드백을 기다리는 동안 더 좋은 방법이 있을지 찾아보기로 이야기했습니다. 피드백 주시는 동안 다른 다양한 방법에 대해서 공부해보겠습니다!

2021-11-05 08:52 UTC, corykim0829 requested changes
고민했던점 & 조언을 얻고 싶은 부분

> 접근제어에 관련한 고민
프로젝트 코드 안에서 해당 객체에 접근할만한 가능성이 없는 경우에도 접근제어를 설정해주는 것이 바람직할까요? 예시: @IBAction private func

➡️ 네 private으로 처리하는게 좋습니다. 외부에서 호출이 필요한 경우에만 public으로 사용한다고 이해하면 좋을 것 같아요!

> weak가 @IBOutlet 등을 선언할때만 자동으로 붙는 이유는 뭘까?
var 이외에 아무 수식어도 붙지 않는 strong이 디폴트값이라고 생각되는데 @IBOutlet을 선언할때만 자동으로 붙는 이유는 무엇일까 고민했습니다.
strong을 사용하는 경우, 뷰가 해제된 이후에도 레이블에 접근할 수 있지만, weak를 사용하는 경우에는 뷰가 해제되면서 레이블이 같이 해제된다고 이해했습니다.
혹시 이런 이유 때문에, 다른 뷰에서 해당 뷰의 레이블에 접근할 경우가 없기 때문에? weak가 자동으로 붙는 걸까요?

➡️ 스토리보드에서 IBOutlet을 만들게 되면 weak, strong을 선택할 수 있습니다. default가 weak입니다. 자세한 설명은 참고 링크를 읽어보면 좋을 것 같아요!
http://monibu1548.github.io/2018/05/03/iboutlet-strong-weak/

> 화면 사이의 데이터 공유에 관한 부분
저희는 fruitStore를 두번째 뷰에서 사용해서 이부분을 해결했는데, 다른 캠퍼들과 이야기를 나누다보니 다른뷰나 클래스를 참조하지 않고 데이터 공유를 하는 방법에 대한 피드백을 많이 받았다고 들었습니다. 일단 저희는 이번주 시간이 많이 남지 않아서...다시 코드를 고치지 않고 일단 PR을 제출한 후에 피드백을 기다리는 동안 더 좋은 방법이 있을지 찾아보기로 이야기했습니다. 피드백 주시는 동안 다른 다양한 방법에 대해서 공부해보겠습니다!

➡️ protocol로 통신하는 방법이 있는데 그것도 해보면 좋을 것 같아요!

2021-11-05 08:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/EditFruitStockViewController.swift
> +        updateStepperValue()
함수 분리한 부분이 좋네요! 가독성이 좋아요 👍

2021-11-05 08:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeQuantity(of fruit: Fruit, step: Int, by operation: Operation) {
여기 step 파라미터는 어떤 의미로 step이라고 하셨나요?

2021-11-05 08:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        super.viewWillAppear(animated)
viewWillAppear로 처리한 부분이 깔끔하고 좋네요!

2021-11-05 14:39 UTC, aCafela-coffee commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeQuantity(of fruit: Fruit, step: Int, by operation: Operation) {
원래 값에서 step 만틈 더하거나 뺀다는 의미로 썼어요.
`changeQuantity(of: Fruit, to: Int)` 이 함수의 to와 구분하려고 했어요.

2021-11-06 12:19 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeQuantity(of fruit: Fruit, step: Int, by operation: Operation) {
step이라고 하면 의도한 의미로 생각하거나 Int 값으로 생각하기가 어려운 것 같네요! 더 고민해봐도 좋을 것 같아요! 😀

2021-11-06 12:19 UTC, merged