쥬스메이커 [STEP 3] 호댕, Vayne
yagom-academy/ios-juice-maker pull request #143
Opened 2021-11-05 09:38 UTC by yanghojoon

담당 리뷰어: @corykim0829

안녕하세요! Cory! 7모둠 호댕과 Vayne입니다.
프로젝트 Step3 완료해서 PR 보내드립니다! 
명세에 있던 기한보다 많이 늦었네요 😢  
잘 부탁드립니다!! 🙏 

## 코드 작성 시 고민했던 부분 / 해결한 과정
`MainViewController`에서 `StockModificationViewController`로 데이터를 전달하는 방법에 대해 고민했습니다. 이 부분은 `prepare`와 `performSegue`를 통해 화면 전환 시 segue를 통해 데이터가 전달되도록 하여 해결했습니다. 통일된 방법을 사용하고 싶었으나 Alert를 통해 재고 수정 페이지로 갈 경우 `prepare`함수를 사용할 수 없었고, Alert의 경우 `performSegue`를 통해 데이터를 전달해주는 방법을 사용했습니다.

Stepper를 통해 바로 `FruitStore`의 재고를 수정해주고 싶었습니다. `FruitStore`의 `stock`을 `private(set)`으로 읽기 전용으로 해놓았기 때문에 외부에서 이를 수정할 수 없었습니다. 따라서 Controller에 있는 것이 더 적합하다고 판단했지만, 불가피하게 Stepper를 통해 재고를 수정하는 함수를 Model인 `FruitStore`에 생성해주었습니다.

Stepper를 눌렀을 때 Stepper의 Value가 0으로 되어 있어 Stepper를 클릭하면 무조건 0부터 더해지는 문제가 있었습니다. 따라서 현재 각 과일의 재고 label로 보여지는 값을 Stepper의 Value로 설정해주었습니다.

`StockModificationViewController`에서 `MainViewController`로 데이터를 전달하는 방법에 대해 고민했습니다. `StockModificationViewController`에서 `MainViewController`로는 따로 Segue가 연결되어 있지 않았기 때문에 Segue를 통한 데이터 전달 방식은 적합하지 않다고 판단했습니다. 따라서 Notification Center를 활용하여 데이터를 전달하는 방식을 선택했습니다. 또한 현재 재고를 즉각적으로 반영해주기 위해 싱글톤을 사용했습니다.

화면이 작은 디바이스 시뮬레이터로 실행을 했을 경우 버튼의 글씨가 생략되는 문제가 있었습니다.

```swift
if kiwiOrderButton.titleLabel?.adjustsFontSizeToFitWidth == false {
        kiwiOrderButton.titleLabel?.adjustsFontSizeToFitWidth = true
        kiwiOrderButton.titleLabel?.lineBreakMode = .byWordWrapping
        kiwiOrderButton.titleLabel?.textAlignment = .center
}
```
.adjustsFontSizeToFitWidth메서드를 활용하여 버튼의 titleLabel이 버튼 넓이에 맞는지 확인해줬고 맞지 않다면 조절할 수 있도록 해주었습니다. 또한 .lineBreakMode를 .byWordWrapping로 해주어 단어 단위로 버튼의 넓이가 부족하면 띄워쓰기를 할 수 있도록 구현했고, 가운데로 정렬될 수 있도록 .textAlignment를 .center로 해주었습니다.

## 조언을 얻고 싶은 부분
1. Stepper를 통해 재고를 수정해주기 위해 Model인 `FruitStore`에 `modifyStock`이라는 함수를 생성했습니다. 
이 부분은 Controller에 가는 것이 맞는 함수라고 생각이 드는데 stock이 읽기 전용(`priavate(set)`)으로 접근 제어가 되어 있어 해당 위치에 함수를 생성했습니다. 
이 부분에 관해서 Model에 해당 함수를 만들어도 괜찮은지 조언을 얻고 싶습니다. 
2. `StockModificationViewController`에서 `MainViewController`로 데이터를 전달하면서 Notification Center를 사용했습니다. 이 때 `StockModificationViewController`에 FruitStore의 인스턴스를 생성하여 post를 하니 재고가 정상적으로 전달이 되지 않는 문제가 있었습니다. 따라서 싱글톤 방식을 사용하여 정상적으로 재고를 전달하도록 수정했습니다. 
FruitStore의 재고를 `StockModificationViewController`와 `MainViewController` 모두 동일하게 가지고 있어야 하기 때문에 인스턴스를 생성해주는 것보다 싱글톤이 적합하다고 생각하는데 이에 대해 Cory의 의견이 궁금합니다.
3. 현재 저희가 사용하고 있는 View Controller 간 데이터 전달 방식에 대해서도 Cory의 의견이 궁금합니다 👀

2021-11-06 12:14 UTC, corykim0829 requested changes
수고 많으셨습니다! 호댕, 베인 👍

많은 고민을하고 코드를 작성한게 느껴지네요 👏👏👏

> 조언을 얻고 싶은 부분

> Stepper를 통해 재고를 수정해주기 위해 Model인 FruitStore에 modifyStock이라는 함수를 생성했습니다.
이 부분은 Controller에 가는 것이 맞는 함수라고 생각이 드는데 stock이 읽기 전용(priavate(set))으로 접근 제어가 되어 있어 해당 위치에 함수를 생성했습니다.
이 부분에 관해서 Model에 해당 함수를 만들어도 괜찮은지 조언을 얻고 싶습니다.

➡️ `FruitStore`는 모델로 분류하기 어려운 객체입니다. stock이 private이니 함수를 만들어서 해당 데이터 값을 변경하는 것은 매우 좋습니다 👍

> StockModificationViewController에서 MainViewController로 데이터를 전달하면서 Notification Center를 사용했습니다. 이 때 StockModificationViewController에 FruitStore의 인스턴스를 생성하여 post를 하니 재고가 정상적으로 전달이 되지 않는 문제가 있었습니다. 따라서 싱글톤 방식을 사용하여 정상적으로 재고를 전달하도록 수정했습니다.
현재 저희가 사용하고 있는 View Controller 간 데이터 전달 방식에 대해서도 Cory의 의견이 궁금합니다 👀

➡️ Notification은 Observer도 사용하고, 브로드캐스트 방식이라 여기에서 사용되기에는 적합하다고 생각은 들지 않습니다.
protocol이나 클래스 참조 방식을 사용해도 컨트롤러간 데이터를 쉽게 전달할 수 있어요!

> FruitStore의 재고를 StockModificationViewController와 MainViewController 모두 동일하게 가지고 있어야 하기 때문에 인스턴스를 생성해주는 것보다 싱글톤이 적합하다고 생각하는데 이에 대해 Cory의 의견이 궁금합니다.

➡️ 결론 먼저 말하면, 싱글톤을 사용하지 않는게 더 좋습니다. 지금은 두 뷰컨트롤러간의 데이터 이동이 필요한 경우인데, 하나의 뷰컨트롤러가 다른 뷰 컨트롤러를 생성해서 present하는 경우라 데이터를 전달하기가 쉬운편입니다. 그래서 싱글톤까지 사용할 필요가 없습니다. 싱글톤이 틀린 방법은 아닙니다.

2021-11-06 12:14 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            showOrderSuccessAlert(message: "\(juiceMaker.tell(name: juice)) 쥬스 나왔습니다. 맛있게 드세요!")
제가 이전 PR에서 이 부분을 제대로 확인하지 못했군요. 죄송합니다. 🥲

그리고 `JuiceMaker`가 `Juice` 타입을 인자로 받아서 이름을 반환하는 함수를 가지고 있는게 어색합니다.
또한 `juiceMaker.tell(name: juice)`와 같이 `juiceMaker`인스턴스가 `tell`이라는 함수를 쓰는게 어색한 것 같아요.
객체들을 실제 환경에 맞게 네이밍할 수도 있지만, 그렇게 네이밍을 하면 혼란을 줄 수도 있습니다.

2021-11-07 07:50 UTC, vayne77 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        notificationCenter.addObserver(self, selector: #selector(updateFruitStockLabel), name: .stockDataTransmission, object: nil)
addObserver 이름의 함수로 따로 분리해 주었습니다!

2021-11-07 09:03 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func adjustButtonFontSize() {
outlet collection을 통해 모든 주문 버튼을 통합해서 관리해주는 orderButtons라는 프로퍼티를 만들어줬고, 이를 통해 `adjustButtonTitleLibelSize` 함수도 코드를 많이 줄였습니다!!

2021-11-07 09:04 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            strawberryBananaOrderButton.titleLabel?.adjustsFontSizeToFitWidth = true
처음에 `adjustsFontSizeToFitWidth`가 false인지 확인해주고 true를 넣어줘야 한다고 생각했는데 바로 true로 고정시켜도 아무 문제가 없겠네요... 감사합니다!!

2021-11-07 09:10 UTC, vayne77 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            showOrderSuccessAlert(message: "\(juiceMaker.tell(name: juice)) 쥬스 나왔습니다. 맛있게 드세요!")
Juice에 name이라는 연산프로퍼티를 만들어서 JuiceMaker의 함수가 아닌 Juice의 연산 프로퍼티를 호출하도록 수정했습니다.

2021-11-07 09:15 UTC, yanghojoon commented
`JuiceMaker는 FruitStore를 소유하고 있습니다.` 요구사항을 충족시키기 위해 JuiceMaker 에서 FruitStore의 인스턴스를 생성해 주었습니다. 
`MainViewController`에서도 `JuiceMaker`의 인스턴스만 생성해준 후 `FruitStore`에 접근하기 위해선 반드시 `juiceMaker`를 거치도록 수정했습니다.

2021-11-07 09:17 UTC, vayne77 commented
`JuiceMaker는 FruitStore를 소유하고 있습니다.` 요구사항을 충족시키기 위해 JuiceMaker 에서 FruitStore의 인스턴스를 생성해 주었습니다. 
`MainViewController`에서 JuiceMaker의 인스턴스만 생성해준 후 FruitStore에 접근하기 위해선 반드시 jucieMaker를 거치도록 수정했습니다.

2021-11-07 09:28 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/StockModificationViewController.swift
> +        notificationCenter.post(name: .stockDataTransmission, object: strawberryStepper.value)
오... 지금까지 찾아봤던 자료 중에 제일 이해가 잘 가네요 👍  ViewController 간 데이터 전달도 칼럼이 따로 있고... 감사합니다!!

2021-11-07 09:35 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            self.performSegue(withIdentifier: "segue", sender: UIAlertAction.self)
Segue란 스토리보드에서 앱의 인터페이스 흐름을 나타내는 객체로 스토리보드에서 뷰 컨트롤러 간의 이동을 나타내는 화살표를 추상화시킨 것이라 생각합니다. 
단순히 화면 전환을 연결해주는 것이라고 생각해서 `segue`라는 이름을 지었는데 다시 생각해보니 segue가 많아진다면 segue 간 구분도 어려워지는 나쁜 이름인 것 같네요... 😭 

재고 수정 화면으로 넘어가도록 해주는 segue라 `modifyStock`이라는 이름으로 수정했습니다.

2021-11-07 10:36 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/StockModificationViewController.swift
> +        mangoStockLabel.text = mangoStock
위 코드는 그대로 사용하고 싱글톤을 사용하지 않는 방향으로 수정했습니다!!

2021-11-07 10:36 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/StockModificationViewController.swift
> +    var mangoStock = ""
위 코드는 그대로 사용하고 싱글톤을 사용하지 않는 방향으로 수정했습니다!!

2021-11-07 10:39 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/NotificationCenter.swift
> +let notificationCenter: NotificationCenter = .default
Notification.default의 반복 사용을 줄이기 위해 notificationCenter를 따로 상수로 생성을 해주었습니다. 
또한 NotifiactionCenter에 대해 따로 소스파일을 관리해주고자 전역변수로 설정했습니다. 

NotificationCenter를 사용하는 곳에서 생성을 해주는 것이 좋을까요?

2021-11-07 10:39 UTC, yanghojoon commented on JuiceMaker/JuiceMaker/Controller/StockModificationViewController.swift
> +        notificationCenter.post(name: .stockDataTransmission, object: strawberryStepper.value)
잘못 이해했던 부분에 대해 수정 완료했습니다!!

2022-02-11 01:53 UTC, closed without merging