쥬스 메이커 [STEP 1] paul, rieul
yagom-academy/ios-juice-maker pull request #145
Opened 2022-02-15 10:29 UTC by jwonyLee

안녕하세요 @Monsteel  !
폴(@ParkHyeongSeok), 리을(@jwonyLee) 입니다.

`STEP 1` 완료해서 PR 요청 드립니다. 😁

## 코드를 작성하면서 고민되었던 점

- `FruitStore`에서 `changeStock(fruit:of:)` 메서드 하나로 특정 과일의 수량을 변경하는 게 좋은 지, 아니면 `increase(fruit:to:)`, `decrease(fruit:to)`를 별도로 두는 게 좋은 지 고민입니다. 현재 방식은 후자를 선택하게 되었는데, 이 방식을 사용한 이유는 `FruitStore`에게 요청하는 객체(`JuiceMaker`) 입장에서 보았을 때 조금 더 명확하다고 생각이 되어서입니다.

## 해결이 되지 않은 점

## 조언을 얻고 싶은 부분

- 테스트 작성시 네이밍을 어떻게 하는게 좋은지에 대한 고민이 있습니다. 테스트 대상, 조건, 결과로 구성해서 적었는데, 일정한 형식이나 컨벤션이 있는지 궁금합니다.
- `JuiceMaker.makeJuice(_:)`에서 재고가 있는 지 여부를 판별하는 반복문과 재고를 감소시키는 반복문을 별도로 두었는데, 더 좋은 방법이 있을까요? 이렇게 작성하게 된 이유는 딸기바나나 쥬스, 키위 망고 쥬스의 경우 과일이 두 개가 필요합니다. 이 때, 반복문을 하나로 합치게 되면 첫번째 과일의 재고가 충분하지만, 두번째 과일의 재고가 부족할 때 에러를 던집니다. 그러면 두 과일의 대한 재고가 `JuiceMaker.makeJuice(_:)` 호출 전과 같아야 하는데, 첫번째 과일의 재고는 이미 감소시킨 후이기 때문에 값이 보장되지 않아서 반복문을 별도로 두게 되었습니다.
- `Juice`의 타입을 `enum`으로 선언했는데, 아래의 구조체랑 비교했을 때 어떤 코드가 더 명확한 지 궁금합니다.
  ```swift
  protocol Juice {
      var recipe: [(fruit: Fruit, count: Int)] { get }
  }
  
  struct StrawberryJuice: Juice {
      var recipe: [(fruit: Fruit, count: Int)] {
          return [(fruit: Fruit.strawberry, count: 16)]
      }
  }
  ```
  ```swift
  enum Juice {
    case strawberryJuice
    case bananaJuice
    case kiwiJuice
    case pineappleJuice
    case mangoJuice
    case strawberryBananaJuice
    case mangoKiwiJuice
    
    func recipe() -> [(fruit: Fruit, count: Int)] {
        switch self {
        case .strawberryJuice:
            return [(fruit: Fruit.strawberry, count: 16)]
        // 생략
  }
  ```

2022-02-16 03:06 UTC, Monsteel requested changes
@jwonyLee @ParkHyeongSeok 
안녕하세요! 안녕하세요 폴 리을~! 이번 쥬스메이커 리뷰를 맡게된 토니입니다! 🙌

첫번째 스텝 잘 진행해 주셨습니다 🚀

우선, 코드를 작성하면서 고민되었던 점, 조언을 얻고싶은부분에 대한 답변을 먼저 드리도록 하겠습니다.
### 1. 코드를 작성하면서 고민되었던 점
우선, 두 방법중 어느 방법이 얻을 수 있는 효용이 큰지에 대해 고민해보면 좋을것 같습니다.
제 생각에는, `chagneStock(fruite:of:)`로 나타내면, of의 값이 -인지 +인지 명확하지 않을 경우에 두가지 케이스에서 모두 사용할 수 있다는 장점이 있을것 같고,
`increase(fruit:to:)`, `decrease(fruit:to)` 로 분리하여 나타내면 -와 +가 명확한 경우에 `-,+`를 잘못 작성하여 생길 수 있는 HumanError를 사전에 방지할 수 있다고 생각합니다.

제가 말씀드린 것 이외에도 이번 주스메이커 프로젝트의 요구사항을 보고 여러가지 장단덤을 비교하셔서 어떤점이 더 효용성이 높은지 고민해보면 좋을것 같습니다. 🚀
### 2. 테스트 네이밍
저는 개인적으로 테스트 코드의 네이밍으로 대상 조건 결과가 모두 잘 들어가있는 좋은 네이밍이였다고 생각합니다.
   다른 사람이 정해놓은 컨벤션을 따르는것도 중요하지만, 우리가 나타내고자 하는 것이 무엇인지 파악하고, 우리가 한번 정한 네이밍 컨벤션을 잘 따라가는것이 중요하다고 생각합니다. 🙋🏻‍♂️
### 3. 반복문을 별도로 두었는데 더 좋은 방법이 있을까요?
같은 recipe를 다른 역할을 수행하기 위해 for문을 두번 도는 것이 비효율적으로 와닿을 수 있다고 생각하지만,
딸바를 시켰는데 딸기만 넣어서 줄 수 는 없는 상황이기에 for문을 불가피하게 두번 도는 방법밖에는 없다고 생각합니다.

물론 아래와 같이for문이아닌 고차함수를 이용하는 방법도 있습니다만
```
      guard recipe.contains(where: { self.fruitStore.isAvailable(fruit: $0.fruit, of: $0.count) }) else {
        throw JuiceMakerError.outOfStock
      }
```
하지만 for문이 오히려 성능적인 면에서 고차함수보다 우세할 수 있다는 점 참고하셔서 선택해 주시면 되겠습니다 🙌 

### 4. Struct VS Enum
두 코드 모두 같은 역할을 진행한다고 했을 때에 개인적으로는 enum으로 선언한 방식이 좋은것 같습니다.
하지만 각 주스별로 가져야 할 별도의 변수나 함수가 있다면, `Struct`를 만드는 것이 더 좋은 방식이 될 수 있겠네요 🙋🏻‍♂️

두가지 상황에서 하나를 선택해야 한다면 어떤 장단점이 있는지, 그 효용의 가치를 비교해 보시면 선택에 도움이 되지 않을까 싶습니다 🙋🏻‍♂️

이어서, 리뷰에 대해서 이야기를 해보면,

이번 PR에서는 몇가지 개선이 되었으면 하는 부분들이 있어, 몇가지 코멘트를 남겨보았습니다! ☀️
대응작업(수정/리코멘트 등..)진행하신 후 다시 리뷰요청 주시면 감사하겠습니다! 🙌

추가로,
![스크린샷 2022-02-16 오전 11 13 16](https://user-images.githubusercontent.com/52942409/154183296-107fe344-a224-4f9e-afd9-b74502173783.png)
작성해주신 테스트 케이스가 모두 통과하지 않는 문제가 있습니다. 해당 부분 확인 부탁드립니다 🙏

짧은 기간이지만 잘 부탁드립니다 🙇🏻‍♂️ 감사합니다 🙇🏻‍♂️

2022-02-16 05:00 UTC, Monsteel commented
아아 테스트코드의 경우 제가 조금 수정해본 부분에서 오류가 났었던거였네요~!! 😓  착오드려 죄송합니다🙏🙏

![스크린샷 2022-02-16 오후 1 58 30](https://user-images.githubusercontent.com/52942409/154199179-629aa46d-df8a-41c7-a1cc-b7712fe9b44a.png)

잘 작동합니다 🚀

2022-02-16 07:10 UTC, ParkHyeongSeok commented
### guard 문을 자주 사용하는 이유?
* 들여쓰기를 줄이기 위해서
* guard 문이 주는 early return이 주는 느낌을 선호해서

### 레시피 재료 검사의 대한 책임 분리
* FruitStore는 Recipe에 대해 알 필요가 없기에, 현재 과일과 그 갯수를 가지고 재고여부를 반환(hasStock())하는 역할만 하도록 책임을 분리했습니다. 
* JuiceMaker는 사용 가능한 Recipe인지 여부를 조사(isAvailable)합니다. 이 때 FruitStore에서 재고가 있는지 확인하는 hasStock()를 사용합니다.
* 각 타입이 맡는 책임이  juiceMaker와 FruitStock의 검증 역할을 분리해 구현했습니다.

### Recipe, Material 타입으로 분리

코드 리뷰 피드백을 바탕으로 기존에 사용하고 있었던 튜플 (fruit: Fruit, count: Int)을 Recipe, Material 타입으로 분리했습니다. 두 개의 타입으로 나눈 이유는, 처음 단일 타입인 Recipe를 만들었을 때는 아래의 코드와 같은 형태였는데요.
```swift
struct Recipe {
    var fruits: [Fruit]
    var count: [Int]
}
```
이렇게 작성했을 때 각 배열(fruits, count)에 대한 값의 짝이 보장될 수 없어서 현재 형태와 같이 Material 이라는 타입을 별도로 분리하게 되었습니다.

### Number 타입

- 기존에 재료에 개수를 관리하기 위해서 Int형을 사용하고 있었는데, 이것을 별도의 타입인 Number로 분리했습니다. 이렇게 분리한 이유는 연산에 대한 책임을 FruitStore가 아닌 별도의 책임을 가진 타입이 필요하다고 생각했기 때문입니다. 
- ExpressibleByIntegerLiteral 채택
ExpressibleByIntegerLiteral라는 프토토콜을 채택해서 깔끔한 생성자를 만들고자 했습니다.
```swift
    var number1: Number = Number(31) // 기존
    var number2: Number = 26 // 현재
```

2022-02-16 07:31 UTC, ParkHyeongSeok commented
## 질문 있습니다!
### 단순한 타입을 만드는 것에 관해
DTO가 아닌 단순히 데이터를 넣고 꺼내는 타입이 좋은가에 대한 고민이 있습니다. 저희가 아래 사용한 타입처럼 단순 구현된 타입이 있는데요. 앞으로 데이터 타입을 작성할 때 이런 타입을 계속 사용하는게 좋을지 궁금합니다! 

```swift
struct Recipe {
    var materials: [Material]
}

struct Material {
    var fruit: Fruit
    var count: Number
}
```
### 에러 처리를 얼마나 해야 하나요?
아직 throw를 사용하는 것이 익숙하지 않아서 그런지 모르겠지만... nil이나 return으로 값 없음이나 함수를 실행하지 않는 방식으로 에러를 처리를 많이 해왔는데 throw로 관련 에러를 처리하는게 좀 더 일반적인지 궁금합니다. nil이나 return은 에러에 대한 throw로 던지는 Error보다 불명확함이 있어서 실제로 지양하는건 아닌지 의문이 들어 질문합니다:)

2022-02-16 09:59 UTC, Monsteel requested changes
@ParkHyeongSeok , @jwonyLee 
안녕하세요 폴 리을~! 
아주 빠르고 정확하게 리뷰 반영해주셔서 감사합니다~! 🎉

`책임 분리`를 중심으로 코드를 작성해 나가신 점과
ExpressibleByIntegerLiteral 프로토콜을 사용하여 깔끔한 생성자를 만드신 점이 굉장히 인상깊었습니다 🎉
또한, 진행해 주신 과정을 남겨주셔서, 폴과 리을이 어떤 생각의 흐름으로 진행했는지 느낄 수 있어서 좋았어요 🙌

다만, 한가지 우려되는 점이 있었는데요, 오히려 과한 `책임분리`원칙을 추구하다 보면 너무 극하게 오버엔지니어링이 되지는 않을까🤔 고민이 되었습니다. 오버엔지니어링과 `책임분리` 그 사이 어딘가 합의점을 잘 찾는것이 중요하다고 생각합니다 👍

말씀하신 ealry return 같은 경우, 해당 라인에서는 early return 보다, if문을 사용하는것이, 더 효용가치가 높지 않을까 생각됩니다 🤔 (개인적인 취향 차이일수도 있는 문제라 if문을 사용했을 때 / gaurd문을 사용했을 때 해당 상황에서 무엇이 더 큰 이점을 가지고 가는지 고민해보면 좋을것 같습니다.)

이어서 남겨주신 질문에 대해 제 의견을 남겨보겠습니다.
### 1. 단순한 타입을 만드는 것에 관하여
해당 맥락에서 `Material` struct를 정의한 점은 굉장히 좋았고, 이전 tuple을 사용했을 때보다 훨씬 안정적인 값 관리가 가능해졌습니다. 다만, Recipe의 경우에는 몇가지 조금 더 생각해 보면 좋은 포인트들이 있는데요,

해당 구현의 경우 materials 하나의 변수를 가지고 있어, 불필요한 struct로 옮기는건 불필요한 오버엔지니어링이 아닐까 생각합니다 🤔

Recipe가 확장가능성이 있는 경우 해당 구현이 충분히 이점이 있겠지만, 그렇지 않은 상황이라면
`materials: [Material]`를 굳이 `Recipe`로 감싸서 얻을 수 있는 이점이 `materials: [Material]`로 사용하는것 보다 약할것 같다는 생각이 듭니다 🙌
### 2. 예외 처리를 얼마나 해야하는지에 관하여
폴님이 작성해주신것 처럼, 오류발생 시 nil을 return 하는것은 정확한 오류정보를 담기가 어렵습니다.

실제로 프로그래밍 언어들이 발전되어 온 히스토리를 보면 함수의 리턴타입만으로는 명확하게 오류 처리를 하기 어렵다는 한계가 있었기에, 리턴타입과는 별개로 throw하는 형태의 Error 타입이 생겨나게 되었습니다.
\+ C언어와 Swift를 비교해 보아도 알 수 있습니다.

이런 사실을 보았을 때, 굳이 리턴타입으로만 오류처리를 할 필요는 없다고 생각합니다 🙋🏻‍♂️

당장 오류처리를 얼마나 해야되는지 그 범위를 정하기 어려우시다면, 나중에 오류가 발생하여 디버깅을 했을 때 어디까지 알아야 코드의 결함을 파악할 수 있을지 생각해보면 조금 도움이 될 것 같습니다.

당연히 오류의 Scope를 줄이면 줄일수록 디버깅할 때에는 쉽겠지만, 실제 프로덕트에서 메소드 단위까지 오류처리를 진행하기에는 어려움이 있기에, 그 중간 어딘가 합의점을 잘 찾는것이 중요합니다.  

개인적인 판단으로는, 메소드가 곧 기능인 해당 프로젝트에서는 [메소드 단위]로 오류처리를 진행하면 적당하지 않을까 싶습니다! 🙋🏻‍♂️  (예시 `레시피 재료 검사 기능에서 재고 부족 오류 발생`)

말씀주신 내용이 어느정도 해소가 되셨을까요?! 😓
추가로 궁금한점이 있으시면 코멘트 남겨주시고, 제가 남긴 코멘트를 바탕으로 함께 고민해보신 후 다시 리뷰요청 주시면 감사하겠습니다 🙏

2022-02-16 10:57 UTC, ParkHyeongSeok commented
@Monsteel 꼼꼼히 리뷰해주셔서 감사합니다:)
저희도 제작 과정에서 오버엔지니어링과 역할이나 책임의 분리의 적정선에 대한 고민을 많이 했던 것 같습니다.
매번 코드를 작성할 때 마다 고민해야 하는 부분인 것 같은데,  오버엔지니어링을 판가름 할 수 있는 소소한 팁 같은게 있으신가요? ^^;; 
(오류 처리에 대한 답변 감동적입니다 감사해요ㅠ)

2022-02-16 11:38 UTC, jwonyLee commented
안녕하세요 토니! @Monsteel
피드백 감사합니다!

### guard 와 if에 대해서 

* 피드백에서 `해당 라인에서는 early return 보다, if문을 사용하는것이, 더 효용가치가 높지 않을까 생각됩니다` 라는 내용을 읽고, guard 와 if가 만들어진 배경에 대해서 찾아보았고, guard는 에러나 원하지 않는 값을 처리할 때 사용하는 것이 목적이고, if는 여러 케이스에 따라 분기처리를 하는 것이 목적으로 이해했습니다.
* 그래서 에러 처리를 하는 `decrease(_:)`와 `increase(_:)`의 경우에는 유지하고 
```swift
mutating func increase(_ amount: Number) throws {
    guard amount.value >= 0 else {
        throw NumberError.isNegativeValue
    }
    self.value += amount.value
}
```
* `hasStock(of:to:)의 경우에는 if문으로 레시피 제작 여부를 분기하도록 수정했습니다.
```swift
func hasStock(of fruit: Fruit, to count: Number) -> Bool {
    if self.fruits[fruit, default: Number()] >= count {
        return true
    }
    return false
}
```

### `Recipe` 타입 제거
말씀하신대로 `Recipe` 타입은 다음 STEP2, 3를 고려해도 추가적으로 확장할 필요가 없는 것 같아서 제거했습니다. 대신 `JuiceMaker`에서 `[Material]`를 직접 작성하는 것보다, 보다 명확하게 이해하고자 `typealias`를 이용해 `Recipe`를 정의했습니다. 
```swift
typealias Recipe = [Material]
```

2022-02-16 14:55 UTC, Monsteel requested changes
폴 리을~! 수고많으셨습니다 🎉

남겨주신 코멘트와 수정된 콛, 잘 확인했습니다! 🙌 아주 좋습니다. 👍

딱 하나 궁금한 점이 있는데요..!!
`Number`라는 struct를 만들기 보다는, `Int`에 extension을 통해서 해당 내용을 구현하는 방법이 더 좋을것 같다는 생각이 드는데, `Number`라는 struct를 정의하신 이유가 따로 있으신지 궁금합니다 🙋🏻‍♂️


그리고 이어서 폴이 남겨준 질문에 대한 저의 생각을 적어볼게요
> 오버엔지니어링을 판가름 할 수 있는 소소한 팁 같은게 있으신가요? ^^;;

지금까지 리뷰에서 계속 강조해 왔던, **"무엇이 더 큰 이점을 가지고 가는지 계속 고민해 보는 것"** 이라고 생각합니다. 그리고 **그 판단력을 기르는것**이 개발자에게 중요한 소양중 하나라고 생각합니다.

\+ 추가로, 고민을 위해 개발자는 진행하는 프로젝트에 대한 관심도가 높으면 도움이 될거라 생각합니다.
어떤 스펙이고, 어떻게 발전될 것인지 등... 관심을 통해 쌓은 프로젝트에 대한 전반적인 지식을 활용하여
내가 짜는 코드가 "효용가치가 있는가"를 계속해서 판단해 보면 좋을것 같습니다.
(= **이점을 판단할 수 있는 전반적인 상황 인지의 중요성**)

너무 극단적인 예시라 와닿지 않으실수도 있지만,
버튼을 누르면 배열에 담긴 Text를 랜덤으로 뿌려주는 앱을 만드는데에, 추후 확장 가능성을 고려하여 "MVVM"을 도입한 것은 좋은 설계일까요?

확장이 되지 않는다라는 정보가 있다면 오버 엔지니어링으로 판단할 수 있고,
확장이 된다는 정보가 있다면 확장에 대비한 현명한 설계라고 판단할수도 있을거라 생각합니다.

정리하면
1. "무엇이 더 큰 이점을 가지고 가는지 계속 고민해 보는 것"
2. 그 이점을 판단할 수 있는 전반적인 상황 인지의 중요성
3. 그리고 판단할 수 있는 능력

에 대한 내용을 이야기 했습니다.

개인적인 의견이니.. 슥 참고만 부탁드리구요, 앞으로 부딛히면서 자신만의 방법을 찾아가는 것도 좋은 방법이라고 생각합니다  🚀

2022-02-17 03:37 UTC, ParkHyeongSeok commented
@Monsteel 
토니 리뷰 및 답변 감사합니다:)

`Number`라는 타입을 사용하게 된 이유를 간단히 설명할게요!
* 야곰의 강의를 들으며 원시타입을 Wrapping해서 해당 원시타입의 사용 용도를 명확하게 하자(또는 제한하자)는 아이디어를 시도해 본 것입니다:)
* 해당 원시타입(Int)이 앱의 비지니스 로직의 핵심이기에 역할을 분명히 하고, 무분별한 남용이나 변화를 제한할 필요가 있다고 생각했습니다.
* 쥬스메이커에서 필요한 연산은 1만큼 증감, n만큼 증감이기 때문에 Int의 모든 연산을 허용할 필요가 없어 제한했습니다.
* 쥬스메이커에 필요한 Int의 범위는 UInt와 동일합니다. 그래서 Int의 범위를 제한하고 관련한 오류를 처리하기 위해 사용했습니다.
* Int보다 과일의 수를 나타내는 타입을 분명하게 해서 가독성이 좋게 하려고 사용했습니다.

이런 이유가 있는데 토니는 어떻게 생각하시나요?

2022-02-17 03:47 UTC, Monsteel commented
@ParkHyeongSeok 아주 좋습니다~! 🎉 폴의 생각을 잘 말씀해 주셔서 어떤 의도인지 명확하게 이해할 수 있었습니다 🙌
다시 리뷰요청 주시면, 해당 PR Approve 할 수 있도록 하겠습니다.

2022-02-17 05:27 UTC, Monsteel approved these changes
Step1 수고하셨습니다~!!  🎉
이어서 Step2 진행해 주시면 될것 같아요~! 🙌

2022-02-17 05:44 UTC, merged