쥬스 메이커 [STEP 1] milsa, z3rosmith
yagom-academy/ios-juice-maker pull request #146
Opened 2022-02-15 10:49 UTC by milsakim

안녕하세요 그린 @GREENOVER ! milsa와 z3rosmith입니다. 

STEP1의 PR를 보냅니다. 코드 리뷰를 받을 생각하니 굉장히 설레고 기대됩니다.
코드와 문서에 저희의 생각이 잘 반영되어있길 바랍니다.

# 1. 의존성 낮추기

![https://user-images.githubusercontent.com/46441723/154043259-7c87ee7e-ae87-4dff-871d-d124f29b9028.png](https://user-images.githubusercontent.com/46441723/154043259-7c87ee7e-ae87-4dff-871d-d124f29b9028.png)

- 처음에는 위와 같이 `JuiceMaker`가 `fruitStore` 프로퍼티로 `FruitStore`를 참조하고, `makeJuice(of:completion:)` 메소드의 내부 구현은 FruitStore를 참조하는 형태로 모델링 했습니다.
- 제로가 `FruitStore`의 구현을 맡고, 저는 `JuiceMaker` 구현을 맡아 개발을 진행하며 제로가 `FruitStore`의 메소드를 아직 구현하지 않았거나 `FruitStore`를 변경하면 `JuiceMaker`도 영향을 받는 것을 깨달았습니다.
- `JuiceMaker`가 `FruitStore`를 소유하고, 주스를 만드는 행위 자체가 `FruitStore`의 과일 재고를 사용합니다.
- 따라서 `JuiceMaker`는 `FruitStore`에 의존적입니다.
- 이 의존성을 없애기 위하여 아래와 같은 프로토콜을 만들고,
    
    ```
    protocol FruitStoreType {
        var store: [Fruit: Int] { get }
        func addStock(to fruit: Fruit, count: Int)
        func useStocks(from requests: [Fruit: Int]) throws
    }
    
    ```
    
- JuiceMaker의 fruitStore 프로퍼티를 아래와 같이 수정했습니다.
    
    ```
    struct JuiceMaker {
        /* 생략 */
    
        var fruitStore: FruitStoreType
    
        init(fruitStore: FruitStore) {
            self.fruitStore = fruitStore
       }
    
        /* 생략 */
    }
    
    ```
    

# 2. 캡슐화

```
protocol FruitStoreType {
    var store: [Fruit: Int] { get }
    func addStock(to fruit: Fruit, count: Int)
    func useStocks(from requests: [Fruit: Int]) throws
}

```

- 앞서 이야기했던 FruitStoreType 프로토콜의 store 프로퍼티를 get으로만 가능하게 한 이유는 FruitStoreType을 conform 하는 타입이 store의 값을 함부로 변경하지 못하도록 하기 위함이었습니다.
- FruitStoreType을 conforming 하는 FruitStore는 store 프로퍼티에 private(set) access control을 사용하여 외부에서 store의 값을 볼 수는 있지만 설정하지 못하도록 했습니다.

```
class FruitStore: FruitStoreType {
    /* 생략 */

    private(set) var store: [Fruit: Int] = [:]

    /* 생략 */
}

```

# 3. struct와 class

- 주스 메이커의 베이스 프로젝트를 보면 FruitStore 타입은 class로, JuiceMaker 타입은 struct로 선언이 되어 있었습니다.
- 결론적으로 저는 베이스 타입에서 선언된 것을 유지했고, 지금부터 그 이유를 설명하겠습니다.
- FruitStore 타입은 말 그대로 과일들의 재고를 관리하는 친구고, JuiceMaker 타입 역시 이름 그대로 주스를 만드는 친구입니다.
- 여러 개의 JuiceMaker 타입이 하나의 FruitStore를 공유할 수 있을거라 판단했고, 그러기 위해서는 FruitStore 타입은 reference type인 class로 선언하는게 맞겠다 생각이 들었습니다.
- JuiceMaker 같은 경우는 여러 곳에서 JuiceMaker 객체의 상태를 변화시키고, 또 관리해야하는 포인트가 없기 때문에 struct를 사용했습니다.
- 제가 고민이 되는 부분은 struct인 JuiceMaker가 FruitStore의 레퍼런스를 갖고 있고, 이런 경우 reference counting에 대한 오버헤드가 생길 수 있다는 것입니다.
- 하지만 현재 JuiceMaker가 참조하고 있는 레퍼런스가 하나밖에 없기 때문에 우려하는 오버헤드 문제는 없을거라고 생각했습니다.

# 4. final class

- FruitStore는 더 이상 상속될 일이 없고, FruitStore 타입의 메소드를 호출할 때 static dispatch 되도록 하여 성능을 향상시키기 위해 final class로 만들었습니다.

# 5. Nested Type

- Fruit 을 FruitStore의 nested type에서 독립적인 하나의 type으로 수정 → FruitStoreError와 JuiceMaker에서 쓰이기 때문에 독립적인 하나의 type으로 바꾸는게 낫다고 판단되어 수정하였습니다.

# 6. 명확한 에러 핸들링

- makeJuice method를

```swift
func makeJuice(of juice: Juice, completion handler: ((JuiceMakerResult<FruitStoreError>) -> Void)) {
    do {
        try fruitStore.useStocks(from: juice.recipe)
        handler(.success)
    }
    catch {
        guard let fruitStoreError: FruitStoreError = error as? FruitStoreError else {
            handler(.fail(error: FruitStoreError.outOfStock([])))
            return
        }
        handler(.fail(error: fruitStoreError))
    }
}
```

에서

```swift
func makeJuice(of juice: Juice, completion handler: ((JuiceMakerResult<FruitStoreError>) -> Void)) {
    do {
        try fruitStore.useStocks(from: juice.recipe)
        handler(.success)
    }
    catch FruitStoreError.outOfStock(let outOfStockFruits) {
        handler(.fail(error: FruitStoreError.outOfStock(outOfStockFruits)))
    }
    catch {
        handler(.fail(error: FruitStoreError.unkown))
    }
}
```

로 개선시키는 방향을 생각해보았습니다.

- 기존 코드는 하나의 catch구문에서 하나의 error을 처리하지 못하고 전달된 error가 FruitStoreError타입으로 캐스팅 실패하면 FruitStoreError.outOfStock error만 표시한다는 문제가 있었습니다.
- 이를 catch구문마다 하나의 error를 처리하도록 하였습니다.
- 그래서 새로운 error가 추가되어도 좀더 쉽게 코드를 변경하도록 하였습니다.

2022-02-15 13:04 UTC, GREENOVER requested changes
@milsakim @z3rosmith 
안녕하세요! 이번 쥬스메이커 리뷰를 맡게된 그린입니니다🙌
비록 짧은 일주일의 간단한 프로젝트지만 잘 부탁드립니다🙇🏻
***
전체적으로 코드들이 로직적으로 잘 분리되었고 가독도 좋아 리뷰하기 편했습니다👍
또한 PR메시지를 통해 구현과 고민의 과정들을 상세히 기재해주셔서 좋았어요👍 (특히 UML 크..👍)
스텝1에서 요구되는 사항들은 전부 충족했다고 판단하며 다음 스텝으로 가기에 문제는 없다고 생각합니다!
다만 몇가지 개선되면 좋을 부분과 궁금한 부분에 대해 리뷰를 드렸습니다.
이에 우선은 request changes를 드리겠습니다!
수정 혹은 다른 의견이 있으시면 진행 후 리뷰 재요청을 주시면 감사하겠습니다🙋🏻

2022-02-15 13:11 UTC, milsakim commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
>  				C73DAF39255D0CDD00020D38 /* SceneDelegate.swift in Sources */,
단순하게 쥬스 메이커 베이스 프로젝트의 내용을 수정하지 않아서 발생한 상황입니다. STEP 1에 대한 구현에 급급해서 전체적인 프로젝트 형태를 생각하지 못했네요. 이 부분 제로 @z3rosmith 와 상의 후 수정하도록 하겠습니다!

2022-02-15 13:14 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentCount = store[fruit], currentCount >= willingAmount else {
어.. 딱히 생각없이 작성했어요 😂 생각해보니 if let이 의미상 더 나을것같네요

2022-02-15 13:15 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkStock(of fruit: Fruit, willingAmount: Int) -> Bool {
- 없습니다.
- FruitStore 내부에서만 사용되는 메소드이니 private으로 access 지정을 하는 것이 좋을 것 같습니다.

2022-02-15 13:21 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
감사합니다. 참고해서 리팩토링 진행할게요!

2022-02-15 13:28 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        if fruitsOutOfStock.count > 0 {
감사합니다. count보다 isEmpty가 빠른지 몰랐네요

2022-02-15 13:29 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkStock(of fruit: Fruit, willingAmount: Int) -> Bool {
private func으로 수정해보겠습니다!

2022-02-15 13:30 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Error/FruitStoreError.swift
> +
음 저는 한 타입의 시작은 한줄 띄우고 시작하는게 제 스타일이었는데 milsa와 상의 후 통일하도록 해보겠습니다

2022-02-15 13:35 UTC, milsakim commented on JuiceMaker/JuiceMaker/Error/JuiceMakerResult.swift
> +    case success
- 특정 동작의 수행 결과를 나타낸다는 공통점이 있다고 생각해 FruitStoreError가 있는 Error 그룹에 포함시켰습니다.
- Error 그룹 안에 Result 타입이 들어가 있는게 앞뒤가 안 맞는 느낌이네요. 
- 제로와 상의하여 수정하겠습니다.

2022-02-15 13:35 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkStock(of fruit: Fruit, willingAmount: Int) -> Bool {
수정했습니다!

2022-02-15 13:40 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
- JuiceMaker들이 서로 다른 쥬스를 만드는 경우에는 nested type으로 Juice 타입이 들어가 있으면 안 될 것 같습니다.
- 위와 같은 상황을 해결하려면 JuiceMaker가 지원하는 쥬스 종류에 대한 정보를 가지고 있어야할 것 같아 [Juice] 타입의 프로퍼티를 추가하려고 하는데 그린의 의견이 궁금합니다.

2022-02-15 13:53 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(of juice: Juice, completion handler: ((JuiceMakerResult<FruitStoreError>) -> Void)) {
handler가 실제로 데이터를 핸들링 하는게 아니고 결과값을 받는 것이기 때문에 result가 더 어울린다고 이해했는데 맞게 이해했는지 궁금합니다!

2022-02-15 13:54 UTC, milsakim commented on JuiceMaker/JuiceMaker/Error/FruitStoreError.swift
> +
수정했습니다!

2022-02-15 14:02 UTC, milsakim commented on JuiceMaker/JuiceMaker/Error/JuiceMakerResult.swift
> +
수정했습니다!

2022-02-15 14:03 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentCount = store[fruit], currentCount >= willingAmount else {
@milsakim  제 생각에는 
```swift 
func checkStock(of fruit: Fruit, willingAmount: Int) -> Bool {
        guard let currentCount = store[fruit], currentCount >= willingAmount else {
            return false
        }
        
        return true
}
```
에서 return false와 return true가 동등한?관계에 있기 때문에 굳이 guard 를 안 써도 될것같다고 이해하였습니다

@GREENOVER 혹시 제 해석이 맞을까요?

2022-02-15 14:08 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentCount = store[fruit], currentCount >= willingAmount else {
동등한 관계라는게 정확하게 이해되지 않습니다 😭

2022-02-15 14:15 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentCount = store[fruit], currentCount >= willingAmount else {
@milsakim 
guard 같은 경우는 조건에 맞지 않으면 멈추고 그 외의 경우는 제대로 진행해라 라는 의미가 강한데 위의 코드같은 경우에는 조건에 맞지 않아 멈춘다기 보다는, 두 return의 상태가 마치 if ~~ { return false } else { return true } 로 할수있을 정도로 대칭적이라고 보아서 동등한 관계라고 표현했습니다.

2022-02-15 14:22 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
@milsakim 
동의합니다!

2022-02-15 14:23 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentCount = store[fruit], currentCount >= willingAmount else {
이해했습니다. 이 부분에서는 guard를 사용하나 let을 사용하나 큰 차이가 없고 guard가 주는 의미성이 크지 않은 상황이니 사용하는게 더 간단한 것 같네요.

2022-02-15 14:29 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(of juice: Juice, completion handler: ((JuiceMakerResult<FruitStoreError>) -> Void)) {
@milsakim 
네 그런 의도로 말씀드렸습니다~!

2022-02-15 15:07 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
수정했습니다!

2022-02-15 23:13 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(of juice: Juice, completion handler: ((JuiceMakerResult<FruitStoreError>) -> Void)) {
수정했습니다 그린! 생각하지 못했던 부분인데 감사합니다!

2022-02-16 02:15 UTC, milsakim commented on JuiceMaker/JuiceMaker/Error/JuiceMakerResult.swift
> +    case success
Result 라는 별도 그룹을 만들어 분리했습니다!

2022-02-16 02:17 UTC, milsakim commented on JuiceMaker/JuiceMaker/Error/JuiceMakerResult.swift
> +
수정했습니다!

2022-02-16 04:26 UTC, milsakim commented
그린 @GREENOVER 말씀해주신 부분 수정 완료했습니다! 리뷰 재요청 드립니다!

2022-02-16 05:19 UTC, GREENOVER requested changes
고생하셨습니다!
크게 수정할 사항은 없지만 인지하셨지만 반영에 누락된 부분이 있어 코멘트를 남겨봅니다..!
추가로, 리뷰 재요청을 하실때 우측 상단에 리뷰어 탭에서 리프레쉬 버튼을 눌러주시면 더 간결하게 요청해주실 수 있습니다👍
![스크린샷 2022-02-16 오후 2 00 19](https://user-images.githubusercontent.com/72292617/154200936-3a659a93-6797-441d-b818-d7317a497498.png)
+ 커밋 메시지가 조금 컨벤션이 어긋나는게 있다고 느껴졌습니다!
refactor: 프리픽스가 이미 붙었는데 메시지에 또 Refactor로 문장이 시작하는 부분과
private 접근제어 레벨을 붙이는건 feat이 아닌 refactor가 적합하지 않을까란 의견도 있습니다!
(저는 feat은 정말 새로운 기능과 같은걸 추가할때 사용하곤 합니다!ㅎㅎ)
***
한번만 더 검수후 재요청 해주시면 감사하겠습니다👍

2022-02-16 05:19 UTC, GREENOVER commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		16144BD927BBE93A00F2DC0F /* AppDelegate */ = {
SceneDeleage 파일도 AppDelegate 그룹 네이밍에 들어가는게 조금 어색해보여요🤔
보통 이러한 딜리게이트 파일들을 묶어서 저는 Application 최상단 폴더 아래에 그룹핑 없이 두거나 SupportingFile과 같은 그룹화를 시켜주기도 하는데 요 부분은 스타일 차이기도 해서 다른 라이브러리들은 어떻게 관리하는지 보면 좋을것 같습니다🙋🏻

2022-02-16 05:19 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    case mango = "망고"
케이스에 바로 rawValue로 관리하는것과 해당 타입안에서 연산 프로퍼티를 만들어 case별 관리해주는것에는 어떤 차이가 있을까요?

2022-02-16 05:28 UTC, z3rosmith commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    case mango = "망고"
만약에 여러 언어를 지원하게 된다면 연산 프로퍼티를 여러개 만들어서 사용하는게 좋을것같아요.  (확장성)

제가 생각한 게 그린의 질문의도에 맞았나요??🤔

2022-02-16 05:31 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    case mango = "망고"
- rawValue를 지정하게 되면 Fruit이라는 enum 타입이 정의될 때 채워지게 됩니다. 
- localize를 고려하게 되는 값이니만큼 computed property를 사용하는게 맥락상 더 맞을 것 같습니다.

2022-02-16 05:41 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    case mango = "망고"
두분의 의견과 동일합니다🙌
다만 여러 언어를 지원하게되도 연산 프로퍼티는 name이라는 하나의 프로퍼티로 만들어 충분히 사용할 수 있습니다.
Localize.string파일에서 각 언어별 지정해주고 return 값으로 
```
String(format: NSLocalizedString(key: String), comment: String))
```
의 포맷의 문자열로 넘겨주면 여러 연산 프로퍼티를 만들 필요까지는 없습니다🙋🏻

2022-02-16 05:44 UTC, milsakim commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    case mango = "망고"
넵 이해했습니다!!

2022-02-16 05:59 UTC, GREENOVER approved these changes
두분 모두 스텝1 고생하셨습니다👍👍👍
다음 스텝도 화이팅입니다!

2022-02-16 05:59 UTC, merged