쥬스 메이커 [STEP 1] Davy, 추니
yagom-academy/ios-juice-maker pull request #150
Opened 2022-02-15 16:41 UTC by kch1285

리뷰어 : @lina0322  잘부탁드립니다😀

1. FruitStore클래스에서 과일과 재고를 저장하는 타입을 구조체로 선언하였다가 딕셔너리 타입으로 변경하였습니다.
구조체로 선언하였을 경우 특정 과일의 인덱스를 찾는 과정에서 불필요한 과정이 추가되어 딕셔너리 타입으로 변경하였습니다.

```swift
struct Fruit {
    let name: FruitName
    var amount: Int = 10
}

private func findCertainIndex(in store: [Fruit], fruit: Fruit) -> Int? {
    guard let index = store.firstIndex(where: { $0.name == fruit.name } ) else {
        return nil
    }

    return index
}
```

위 함수의 사용없이 단순히 딕셔너리로 선언하는 것이 더 편리하다 생각했습니다.

2. 에러 처리를 하면서 throw에 대해 알아보고 처음 사용해보았습니다. try-catch문을 사용하면서 들여쓰기를 2회 이상 하게되어 따로 validateMakeJuice 메소드를 구현했습니다. 에러 처리 부분에 대해서 좀 더 깔끔하게 하고싶은데, 조언 부탁드립니다!
```swift
func makeJuice(juice: Juice) {
    switch juice {
    case .딸기쥬스:
        validateMakeJuice(fruits: [(Fruit.딸기, -16)])
                      ...생략...
    }
}

private func validateMakeJuice(fruits: [(Fruit, Int)]) {
    do {
        try fruitStore.changeAmountOfFruit(fruits: fruits)
    } catch let error as FruitError {
        print(error.description)
    } catch {
        print(error.localizedDescription)
    }
}
```

3. validateMakeJuice() 메소드에서 Fruit타입과 수량을 인자로 받아 구현했었는데, 두 개의 과일을 사용하는 쥬스를 처리하는 게 원하는대로 결과가 나오지 않았습니다. ex) 딸바쥬스를 만들 때 딸기의 수량이 부족하고 바나나의 수량은 충분할 경우 재고가 부족하여 만들지 못하지만 바나나의 수량은 줄어드는 결과
그래서 튜플의 배열을 인자로 변경하여 모든 배열의 재고가 충분할 때만 수량을 변경하도록 구현하였습니다.

4. 에러 처리할 때, 메세지를 원하는 문구로 나타내기 위해 
```swift
enum FruitError: String, Error {
    case outOfAmount = "재고가 부족합니다."
    case noFruit = "과일이 존재하지 않습니다."
}
```
이렇게 구현하였었는데, 메세지가 출력되지않아 고민하였습니다.

```swift
extension FruitError: LocalizedError {
    var description: String {
        switch self {
        case .noFruit:
            return "과일이 존재하지 않습니다."
        case .outOfAmount:
            return "재고가 부족합니다."
        }
    }
}
```
에러 메세지 출력 방법에 대해 공부하고 이렇게 구현하였습니다.

5. UML 다이어그램 관련해서 저희가 많이 미숙합니다.. UML 다이어그램 잘 그리는 방법(?), 조언 부탁드립니다!!

2022-02-16 13:16 UTC, lina0322 requested changes
안녕하세요, Dave & 추니 🙇🏻‍♀️

이번 쥬스메이커 리뷰어로 만나게된 엘림입니다!
제가 다는 리뷰는 하나의 의견이고 방향이지 정답은 아니니 편하게 봐주세요.
궁굼하거나 어려운 부분 있으시다면 주저하지 마시고 말씀해주십쇼:)

----

주신 질문들에 대해 답을 먼저 드리자면,

1. LGTM💕
2. throw 구문을 사용할때 함수로 분리한 것 아주 좋았습니다! 
지금은 깔끔한 상태이고, 상황이 더 생기면 점차 복잡해질테니 하면서 좀 더 고민해볼까요?!
3. 관련해서 코멘트 남겼습니다:)
4. 요것도 코멘트 남겼어요!
5. UML.. 저는 잘 안 그리긴 하는데 https://cacoo.com/ 이 툴이 좋다는 소문은..?ㅎㅎ;


---


제가 생각한 것 보다 훨씬 코드가 깔끔해서 전체적으로 파악하기 좋았습니다.
커밋도 두분이 잘 나눠서 해주신 것 같고, 커밋 메세지도 심플하고 좋았네요.😆
아래에 코멘트 달았으니 확인하신 후에 수정도 해보시고, 코멘트도 달아주세요!

감사합니다~🙏

2022-02-16 13:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) -> String {
쥬스를 만드는데 string을 반환한다...? 흠...😅

+ 추가로 함수의 전달인자 레이블 관련해서 알고있나요?☺️

2022-02-16 13:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            return "성공"
validate라는 함수인데 String을 반환하는 부분과
"성공"이라는 문자열이 반환되는 것이 다소 어색해보여요..😥

2022-02-16 13:16 UTC, lina0322 commented on JuiceMaker/JuiceMakerTests/FruitStoreTests.swift
> +        }
else도 테스트 될 순 없을까요?🤔

2022-02-16 14:18 UTC, kch1285 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//  Created by 추니 & Davy.
감사합니다!

2022-02-16 14:24 UTC, kch1285 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    case 망고
한글이 보기 편해서 네이밍을 한글로 하였습니다.
코드를 봤을 때 저희가 쉽게 알아볼 수 있는 점이 장점이라 생각합니다.
단점은 그 반대로 외국인이 본다면 못 알아볼 수 있는 것입니다🥲

영어로 작성하는 것이 더 좋아보여 영어로 수정하겠습니다!😃

2022-02-16 14:51 UTC, kch1285 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +extension FruitError: LocalizedError {
에러를 캐치해서 에러의 내용에 대해 프린트 할 때, 실수로 해당 에러를 FruitError로 타입 캐스팅을 하지 않아 출력이 안됐었습니다...😭

2022-02-16 15:05 UTC, kch1285 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var store: [Fruit: Int] = [.딸기: 10, .바나나: 10, .파인애플: 10, .키위: 10, .망고: 10]
엘림 말대로 초기값을 변경하려면 귀찮음이 있을 것 같습니다!

Fruit 열거형이 CaseIterable을 채택하고, 

```swift
var store: [Fruit: Int] = Fruit.allCases.reduce(into: [:]) { store, fruit in
    store[fruit] = 10
}
```
이런 식으로 변경하였습니다.

2022-02-16 15:09 UTC, kch1285 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            if fruitAmount + amount < 0 { throw FruitError.outOfAmount }
else 문안에 짧은 코드가 들어갈 경우 줄바꿈을 안 하면 더 깔끔해보인다 생각해서 줄바꿈을 하지않았는데, 엘림 말을 들어보니 브레이크 포인트 잡을 때 불편할 것 같아 수정하였습니다!😁

2022-02-16 15:43 UTC, kch1285 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
엘림 말을 참고하여 튜플의 배열보다는 구조체를 이용하여 코드를 수정하였습니다.
구조체를 이용하니 이 함수가 호출되었을 때 어떤 인자를 넣어야하는지 쉽게 파악할 수 있을 것 같습니다!😊

2022-02-16 16:00 UTC, kch1285 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            return "성공"
validateMakeJuice 함수 마찬가지로 JuiceResult 타입을 리턴하도록 하였습니다.
JuiceResult 타입으로 리턴한 이유는 추후에 뷰컨트롤러에서 쥬스를 만들지 못하였을 경우 얼럿의 메세지로 표시하기 위함입니다!😆

2022-02-16 16:11 UTC, kch1285 commented on JuiceMaker/JuiceMakerTests/FruitStoreTests.swift
> +        }
fruitStore.store[.딸기]가 nil일 경우가 있을 것 같습니다!
else 구문도 만들어서 nil인지 아닌지 XCTAssertNil(fruitStore.store[.strawberry]) 로 테스트코드를 추가하였습니다.🤗

2022-02-16 16:14 UTC, kch1285 commented
리뷰해주신거 토대로 코드를 수정하였습니다! 리뷰 고마워요 엘림!

2022-02-17 13:07 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
좋습니다! 구조체도 좋고, 튜플에 이름을 달아주는 것도 방법이 될 수 있었을 것 같아요!👍

2022-02-17 13:11 UTC, lina0322 approved these changes
두 분 짧은 시간동안 다양한 시도를 해보았네요~ 좋습니다😆
좀 더 수정하고 다듬을 것들이 있지만, 다음 스텝에서 디벨롭 해봅시다 STEP2로 고고!🏃‍♀️

2022-02-17 13:11 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Enums+Struct.swift
> +}
ErrorMessages가 여기에 포함될 수 있는 방법은 없을까요?🤔

2022-02-17 13:11 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeAmountOfFruit(fruits: [Recipe]) throws {
전달인자 레이블과 와일드 카드에대해서 공부해보면 좋겠어요😀

2022-02-17 13:11 UTC, merged

2022-02-17 14:05 UTC, db97828 commented on JuiceMaker/JuiceMaker/Model/Enums+Struct.swift
> +}
잘 이해가 안되는데.. 좀 더 상세히 설명해주실 수 있으신가요?😭

2022-02-17 15:48 UTC, db97828 commented on JuiceMaker/JuiceMaker/Model/Enums+Struct.swift
> +}
네! 조언해주신대로 파일 분리하였습니다☺️

2022-02-17 15:57 UTC, db97828 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeAmountOfFruit(fruits: [Recipe]) throws {
와일드 카드 적용시켜서 func changeAmountOfFruit(_ fruits: [Recipe]) throws { } 로 변경하였습니다!