쥬스 메이커 [STEP 1] Ohtt, JAEYOUNGYUN
yagom-academy/ios-juice-maker pull request #151
Opened 2022-02-16 00:30 UTC by ohtt-iOS

@lina0322 
안녕하세요 엘림 :) 
첫 PR이네요 잘부탁드립니다 😊

---

## 🤔 고민했던 점
1. Juice의 종류마다 사용되는 재료가 다르고, 이를 관리해주기 위해서 Juice enum을 정의하였습니다.
주스 enum에 extension으로 Ingredients를 만들어 각 주스의 재료를 받아올 수 있도록 하였습니다.

2. JuiceMaker와 FruitStore를 책임 주도 설계를 하여 어떤 책임을 줄 수 있을까 고민하였습니다.
JuiceMakable과 FruitStorable이라는 역할을 만들었습니다.

</br>

## 🤔 궁금한 점
1. 재고 수량을 Int를 감싼 Stock이라는 타입으로 사용하고, Stock의 init에 검증 코드를 넣어 0미만인 수가 들어갔을 때 nil이 return 되게 하였습니다. 이렇게 하니까 매번 Stock을 만들어 사용할 때마다 optional을 벗겨내야해서 코드가 지저분해지는 느낌을 받았습니다. 그래서 JuiceMaker 부분에서는 Int를 사용했습니다. 이 부분을 어떻게 처리하면 더 좋은 코드가 될지 엘림의 생각이 궁금합니다

2022-02-16 14:17 UTC, lina0322 requested changes
안녕하세요, Ohtt & JAEYOUNGYUN🙌

이번 쥬스메이커 리뷰어로 만나게된 엘림입니다!
제가 다는 리뷰는 하나의 의견이고 방향이지 정답은 아니니 편하게 봐주세요.
궁굼하거나 어려운 부분 있으시다면 주저하지 마시고 말씀해주십쇼:)

또, 남겨주신 궁금한 점에 대해서 함께 답을 찾기 위해서는, 
Int 대신 Stock을 사용하려고 하신 이유를 먼저 알 수 있을까요?🤔

그리고....! 네이밍을 잘하시는 것 같아요😽
그 외에도 protocol을 사용하여 의존성 주입을 시도하신 부분이 감명 깊었습니다.

다만, 커밋이 한분으로만 되어있던데 함께 화면 공유하면서 작업하신건지 궁금하네요😀 
또, 테스트 코드는 따로 작성하지 않으시는 건지요!
작업 계획이 없으시다면 넘어가도 좋습니다. 확인차 여쭤봅니다~

아래에 코멘트 달았으니 확인하신 후에 수정도 해보시고, 코멘트도 달아주세요!

감사합니다~🙏

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +  typealias Ingredient = (Fruit, Int)
Juice 내부에 선언해주신 이유가 있을까요?🧐

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +  }
LGTM💕

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +}
protocol을 선언하신 이유가 있을까요?☺️

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  }
파일을 분리해주시면 더 좋을 것 같네요🙏

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +  }
과일이 2가지 필요한 경우면서,
레시피에서 두번째 과일이 부족한 경우에 첫번째 과일이 사용되지는 않나요?🧐

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Stock.swift
> +struct Stock {
struct와 class를 선택하는 여러분만의 기준을 알 수 있을까요?😀

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Stock.swift
> +    guard quantity >= 0 else { return nil }
저는 개인적으로 이런 else 구문이 있을때 줄바꿈을 하는 편이에요!
브레이크 포인트로 디버깅을 할 때 좀 더 편하거든요:) 
요건 그냥 저의 이야기니 참고만 해주세요!

2022-02-16 14:17 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +  }
LGTM2💚

2022-02-16 14:33 UTC, ohtt-iOS commented
안녕하세요 엘림 ! @lina0322 
> 다만, 커밋이 한분으로만 되어있던데 함께 화면 공유하면서 작업하신건지 궁금하네요😀
또, 테스트 코드는 따로 작성하지 않으시는 건지요!
작업 계획이 없으시다면 넘어가도 좋습니다. 확인차 여쭤봅니다~

우선 이부분에 대해서 답변드립니다 !
저희는 페어 프로그래밍으로 진행하고 있고, 서로 번갈아가며 step을 진행하고 있습니다. 
step2 부분은 재영이 작성하고 제가 볼 예정입니다 ㅎㅎ
테스트 코드는 우선 프로젝트를 완성하고나서 작성해 볼 예정입니다!
빠르면 금요일 아니면 주말을 생각하고있습니다 😄 리뷰 감사드려요 !!

2022-02-17 13:03 UTC, lina0322 commented
오뜨~ 리뷰에 대한 수정이나 제가 달아들인 내용에대한 코멘트는 아직 준비 중인건가용?🤔
준비되면 디스코드 메세지 주시면 감사하겠습니당🙏

2022-02-17 13:48 UTC, ohtt-iOS commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    }
필요할 것 같아서 만들었는데 안쓰게 되었습니다 😭
수정하며 삭제하였습니다.

2022-02-17 14:02 UTC, ohtt-iOS commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  }
감사합니다 :) 분리하였습니다

2022-02-17 14:03 UTC, ohtt-iOS commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +      store[$0] = Stock(10)
init 함수에 전달인자를 두어 과일 초기개수를 유동적으로 바꿔줄 수 있도록 변경하였습니다. 그리고 기본값 세팅도 완료하였습니다. ㅎㅎ

2022-02-17 14:08 UTC, ohtt-iOS commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +  typealias Ingredient = (Fruit, Int)
주스의 재료를 주스 외부에서 결정하고 싶지 않아서 extension을 활용하여 구현하였습니다.

2022-02-17 14:11 UTC, ohtt-iOS commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +}
1. 쥬스 메이커를 구현하기 전에 쥬스 메이커의 기능을 우선적으로 생각해보려고 프로토콜을 만들었습니다.
2. 그리고 JuiceMaker를 사용하는 곳과 JuiceMaker 간의 결합도를 낮추기 위해서 사용하였습니다 :)

2022-02-17 14:21 UTC, ohtt-iOS commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +  }
와 엘림 ... ! 저희의 버그를 찾아주셔서 감사해요 :)
수정해서 올렸는데 조금 더 깔끔한 코드를 작성할 수 있을 것 같은데 좋은 생각이 떠오르질 않았습니다 😭 이 부분에 대해서 코멘트 주실 수 있으실까요? ㅎㅎ 감사합니다 ...

2022-02-17 14:23 UTC, ohtt-iOS commented on JuiceMaker/JuiceMaker/Model/Stock.swift
> +struct Stock {
FruitStore 같은 경우에는 재고라는 상태를 가지고 있어야 하기때문에 class를 선택하였습니다. 그렇지 않으면 기본적으로 struct를 선택하였습니다.

2022-02-18 10:29 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Stock.swift
> +struct Stock {
`재고라는 상태를 가지고 있어야 하기 때문에`에 대한 부가적인 설명을 좀 더 들어볼 수 있을까요?😀

2022-02-18 10:32 UTC, lina0322 approved these changes
두 분 고생하셨습니다! 
짧은 기간 동안에도 소중한 발전이 있었네요👍
좀 더 수정해야할 부분들은 다음 스텝에서 한번 해보죠~

2022-02-18 10:32 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +  }
앗, 제가 말한 기본값은 
`init(qauntity: Int = 10)` 요런 느낌이었답니다^.~

2022-02-18 10:32 UTC, merged