쥬스메이커 [STEP 1] 카리나, 콩이
yagom-academy/ios-juice-maker pull request #152
Opened 2022-02-16 04:58 UTC by beansbin

📌  구현 기능
-----------
* JuiceMaker 타입 정의
* FruitStore 타입 정의
* TDD 적용 : JuiceMaker, FruitStore

📌  진행하면서 궁금했던 점
-----------
  - FruitStore.stocks.value를 미리 제한하는 것이 좋을지 아니면 현재 코드처럼 Int으로 하고 함수로 처리하는 것이 좋은지 고민하였습니다. 
  - FruitStore.init이 현재 모두 같은 값 Init되게 되어 있는데 나중에 확장성 부분에서 문제가 되지않을까 해서 바꿔보고 싶은데 간결한 코드로 바꿔볼 수 있을까요?
  - FruitStore.stocks는 dictonary라서 순서가 없는데 이 부분은 문제가 되지 않을까요?
     -> 제가 생각한 해결법은 [Fruit: Int] 대신 [튜플]로 해결하거나 [새로운 struct]로 하는 방법인데 이 부분에 대해서는 어떻게 생각하시나요?

📌  담당 리뷰어
-----------
@zdodev

2022-02-16 11:16 UTC, zdodev requested changes
안녕하세요! @beansbin , @p41155a !
리뷰를 진행하게 된 소대입니다!😁

스텝1 PR 축하합니다! 간결하게 작성되어 읽기 수월했습니다.👍

먼저 고민한 점에 대한 제 생각은 다음과 같습니다.

- FruitStore.stocks.value를 미리 제한하는 것이 좋을지 아니면 현재 코드처럼 Int으로 하고 함수로 처리하는 것이 좋은지 고민하였습니다.

지금과 같은 Int 타입으로 처리하는 것도 좋은 방법이라고 생각합니다.👍

- FruitStore.init이 현재 모두 같은 값 Init되게 되어 있는데 나중에 확장성 부분에서 문제가 되지않을까 해서 바꿔보고 싶은데 간결한 코드로 바꿔볼 수 있을까요?

지금과 같이 구현하신 방법도 간결하게 구현했다고 생각합니다.👍

- FruitStore.stocks는 dictonary라서 순서가 없는데 이 부분은 문제가 되지 않을까요? > 제가 생각한 해결법은 [Fruit: Int] 대신 [튜플]로 해결하거나 [새로운 struct]로 하는 방법인데 이 부분에 대해서는 어떻게 생각하시나요?

과일을 처리함에 있어서 순서의 비중이 높지 않다고 생각이 들어서 지금처럼 `dictionary` 로 구현한 것도 괜찮다고 생각합니다. 그런데 의견 주신 것 처럼 별도의 타입을 만들어서 관리를 하는 방법도 좋은 방법이라고 생각합니다.👍

그 이외에 UML 작성에서 아직 미작성된 부분이 있어보입니다.
구현하신 타입과 타입 간의 관계를 더 작성해주시면 좋을 것 같습니다.😁

몇 가지 궁금한 점을 남겨보았습니다. 
코멘트에 대해서 같이 의견 나눠보면 좋을 것 같습니다.🤗

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMaker/Enum/Fruit.swift
> +enum Fruit: CaseIterable {
`enum`을 사용하여 Fruit를 표현해보셨네요. 좋습니다.👍

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMaker/Enum/Juice.swift
> +enum Juice {
`enum`을 사용하여 Juice를 표현해보셨네요. 좋습니다.👍

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var stocks: [Fruit: Int]
`stocks` 프로퍼티의 접근 수준을 internal로 선언하신 이유가 궁금합니다!🤔

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init(initalValue: Int = 10) {
init과 디폴트 매개변수를 사용하여 초기 재고를 10개로 초기화하신 점 좋습니다.
만약 이후에 확장성(과일 별로 초기 재고가 달라져야 한다면?)을 고려한다면 별도의 init을 작성하는 것도 좋지 않을까 싶었습니다.😁
지금 구현하신 방법도 좋습니다.👍

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var stocks: [Fruit: Int] = [:]
초기화를 위한 `stocks`을 생성하고 과일 초기화를 진행하는 코드라고 판단됩니다.
초기화를 위한 `stocks`을 생성하지 않고 초기화 구문을 작성해보는 것은 어떨까요?🤔 지금 방식으로 진행하셔도 괜찮습니다!

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore: FruitStore = FruitStore.init()
`FruitStore`를 생성할 때, `init()` 메서드를 명시적으로 사용한 이유가 궁금합니다!🤔

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_바나나가_하나_추가되면_11() {
테스트를 작성하고 메서드명도 `_`를 사용하여 잘 나눠주셨네요. 좋습니다👍
메서드 이름만 보면 마지막에 `11` 이라는 숫자가 명확히 어떤 의미를 가지는지 알기 어려워 보입니다.
아래 다른 테스트 메서드처럼 숫자에 의미를 나타내는 이름으로 바꿔보는 건 어떨까요?😁

2022-02-16 11:16 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_딸기수량이_부족한데_주스를_만들면_안됨() {
실제 테스트하는 내용과 테스트 이름과 다르게 동작하는 것 처럼 보입니다.😲
테스트 이름을 보면 '딸기 수량이 부족할 경우'(조건) -> '주스를 만들지 않는다'(라는 결과를 예상)라고 보이지만,
실제 테스트는 딸기 재고가 존재하면 테스트가 통과하도록 동작하고 있습니다.
보다 명확하게 주스를 만들 수 없다는 의미를 가지도록 테스트 구문을 변경해보는 것은 어떨까요?🤔
또는 주스 제조의 성공과 실패를 테스트 해볼 수 있다면 더욱 좋을 것 같습니다.😁

2022-02-16 11:37 UTC, beansbin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var stocks: [Fruit: Int]
JuiceMakerTest.swift 파일에서 stocks를 접근할 수 있도록 internal로 선언했습니다.
stocks를 private으로 선언하게 되면 test 파일에서 stocks에 접근할 수 없게 되네요🥲
이런 경우에 stocks에 직접 접근하지 않도록 별도의 메소드를 선언하는 것이 좋을까요? 

@zdodev

2022-02-16 11:48 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var stocks: [Fruit: Int] = [:]
오 필요 없는 코드를 넣었네요 감사합니다

2022-02-16 12:04 UTC, yoojin19 commented
FruitStore.stocks는 dictonary라서 순서가 없는데 이 부분은 문제가 되지 않을까요?
-> 제가 생각한 해결법은 [Fruit: Int] 대신 [튜플]로 해결하거나 [새로운 struct]로 하는 방법인데 이 부분에 대해서는 어떻게 생각하시나요?

이 부분에 대해서 추가 질문해도 될까요?
[튜플]로 해결하거나 [새로운 struct]로 하게 되면 과일을 찾아서 사용하는 부분에서 반복문으로 배열을 돌아 특정 과일을 찾아줘야 한다고 판단해서
현재 처럼 dictionary로 작업했는데요
혹시 반복문이 아닌 다른 방법으로 특정 과일의 수량을 바꾸는 방법이 있을까요?

2022-02-16 12:05 UTC, yoojin19 commented
필요 없는 부분이나 naming이 이상한 부분을 꼼꼼히 봐주신것 같아
덕분에 열심히 고민중입니다:D

2022-02-16 12:15 UTC, beansbin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init(initalValue: Int = 10) {
72bb3b74f
말씀하신대로 과일 별로 초기 재고가 달라지도록 메서드를 수정해보았습니다 😎

2022-02-16 12:15 UTC, beansbin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var stocks: [Fruit: Int] = [:]
72bb3b74f
stock을 정의할 때 빈 딕셔너리를 참조하도록 선언하도록 했습니다 😎

2022-02-16 12:22 UTC, beansbin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore: FruitStore = FruitStore.init()
5d0332
다시 생각해보니 명시적으로 사용할 필요가 없을 듯 하여 제거했습니다!

2022-02-16 12:41 UTC, yoojin19 commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_딸기수량이_부족한데_주스를_만들면_안됨() {
[2d84d9a](https://github.com/yagom-academy/ios-juice-maker/pull/152/commits/2d84d9a594776b4e2ea0bb958028ac1f1bee4868)
네이밍을 변경하여 해결 하였습니다.

2022-02-16 12:41 UTC, yoojin19 commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_바나나가_하나_추가되면_11() {
[2d84d9a](https://github.com/yagom-academy/ios-juice-maker/pull/152/commits/2d84d9a594776b4e2ea0bb958028ac1f1bee4868)
네이밍을 변경하여 해결 하였습니다.

2022-02-17 01:10 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var stocks: [Fruit: Int]
`stocks` 을 internal로 만들게 되면 외부에서 직접 접근이 가능하고, `addFruit`, `useFruit` 메서드를 선언한 의미가 조금 없어지지 않을까 싶었습니다. 말씀해주신 것 처럼 필요한 연산(방법)을 제공해주는 메서드를 하나 생성해보는 것은 어떨까요?😁

2022-02-17 02:11 UTC, zdodev commented
> [튜플]로 해결하거나 [새로운 struct]로 하게 되면 과일을 찾아서 사용하는 부분에서 반복문으로 배열을 돌아 특정 과일을 찾아줘야 한다고 판단해서
현재 처럼 dictionary로 작업했는데요
혹시 반복문이 아닌 다른 방법으로 특정 과일의 수량을 바꾸는 방법이 있을까요?

튜플이나 새로운 struct를 사용한다면, 특정 과일의 수량을 바꾸기 위해서는 해당 과일을 찾는 로직이 필요할텐데, 
튜플이나 새로운 struct에서는  반복문을 사용하지 않고는 찾기 쉽지 않아보입니다.(고차함수(ex. filter)를 사용해 볼 수 있겠지만 dictionary 보다 번거롭지 않을까 싶었습니다. 추후 확장성을 고려하면 이 방법이 더 좋을 수도 있을 것 같아요!😁)
현재 상태에서는 dictionary도 적합한 stocks의 타입이라는 생각이 듭니다.

혹시 수정이 완료되셨다면 리뷰 재요청 해주시면 됩니다~😁

2022-02-17 06:37 UTC, zdodev requested changes
안녕하세요. @beansbin , @yoojin19 !

피드백 드린 부분 대부분 잘 반영해주셨습니다!👍

약간의 피드백 사항을 남겨보았습니다! 
해당 부분에 대한 궁금증 또는 의견 나눠보면 좋겠습니다!🤗

2022-02-17 06:37 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_딸기수량이_10인데_딸기_16개를_사용하려하면_주스를_만들지_않음() {
테스트 이름을 바꿔보셨네요. 좋습니다.👍
다만 현재 테스트가 실패하고 있습니다! 이 부분 한번 확인 부탁드립니다!

2022-02-17 06:37 UTC, zdodev commented on README.md
> +![step1-UML](https://user-images.githubusercontent.com/39825738/154270669-c61f5ef9-c4b5-4c49-942a-a4658f7c5585.png)
구현하신 타입들이 모두 작성되어 있네요. 좋습니다.👍
다만 타입간의 관계 화살표 방향이 구현 코드와 달라 보입니다. 
포함 관계에 따른 화살표 방향을 한 번 확인해보면 어떨까요?😁

2022-02-17 06:37 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
초기 재고는 10개에 주어진 과일에 따라 개수가 달라지겠네요. 좋습니다.👍
답변드린 `stocks` 의 접근 제어 부분도 한번 확인 부탁드립니다!

2022-02-17 06:37 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_바나나가_1개가_추가되면_바나나가_11개가_된다() {
좋습니다. 👍

2022-02-17 07:17 UTC, beansbin commented on JuiceMaker/JuiceMakerTests/JuiceMakerTests.swift
> +    func test_딸기수량이_10인데_딸기_16개를_사용하려하면_주스를_만들지_않음() {
2d01ce7
FruitStore의 useFruit()에서 과일 재고를 검증하는 과정에서, 변경 이후 재고가 아닌 변경 이전 재고를 파라미터로 넣어서 테스트가 실패했습니다.
해당 부분 수정했습니다! 😎 👍

2022-02-17 07:32 UTC, yoojin19 commented on README.md
> +![step1-UML](https://user-images.githubusercontent.com/39825738/154270669-c61f5ef9-c4b5-4c49-942a-a4658f7c5585.png)
[e0d71de](https://github.com/yagom-academy/ios-juice-maker/pull/152/commits/e0d71de2696edcab6428ec7175594e8301dab5df)
그렇네요 바꿔 보았는데 맞는건지 확인 부탁드려요

2022-02-17 07:54 UTC, beansbin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
3cd6773326
특정 과일의 재고를 반환하는 getFruitCount()를 생성하고 stock, fruitStore을 private로 선언해 직접 접근하지 못하도록 변경했습니다!

2022-02-17 09:55 UTC, zdodev approved these changes
안녕하세요. @beansbin , @yoojin19 !

UML과 피드백 부분 잘 반영해주셨습니다!
작은 기능이지만 다양한 경험을 해보셨을 것 같습니다!

스텝1은 여기서 마무리 하도록 하겠습니다. 고생하셨습니다.🤗

2022-02-17 09:55 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
좋습니다.👍

2022-02-17 09:55 UTC, zdodev commented on README.md
> +![step1-UML](https://user-images.githubusercontent.com/39825738/154426606-df609c5e-a88f-4c7e-8c29-a06e9891501a.png)
UML 잘 작성해주셨습니다.👍

2022-02-17 10:41 UTC, merged