쥬스 메이커 [STEP 1] momo, DayeonJung
yagom-academy/ios-juice-maker pull request #153
Opened 2022-02-16 07:25 UTC by momo-youngg

# 변경 사항
- `Step 1 : 쥬스 메이커 타입 정의` 개발
-  FruitStore.swift 파일에  FruitStore 타입을 정의 및 구현
- JuiceMaker.swift 파일에 JuiceMaker 타입을 정의 및 구현
- Quantity.swift 파일에 Quantity 타입을 정의 및 구현
- 추가된 타입입의 메소드들에 테스트 작성

# 고려 사항
## struct `Quantity`
- 전반적으로 양(quantity)의 정보를 표현 할 수 있는 Int type이 쓰이게 될 것이 필연적입니다.
- 이 중 양의 특성을 가지고 그 특성의 연산만을(0 이상의 정수만 갖고 있음, 결과가 음이 되는 연산 불가) 할 수 있는 Quantity struct를 만들어 주었습니다.
- 양의 정보를 표현해야 할 경우에 전부 Quantity 인스턴스로 생성 해 사용하게 됩니다. 
## struct `FruitStore`
- 각 과일의 재고를 열람 및 조절 할 수 있는 역할을 갖고 있습니다.
- 과일<을 구분해야 하므로 `Fruit` enum을 생성 해 주었는데 이는 `FruitStore` 안에 nested 되어 있습니다. `FruitStore` 가 `Fruit` 의 존재 이유이기 때문입니다. `FruitStore` 없는 `Fruit` 은 존재 할 이유가 없습니다. 
- `Fruit` 은 그 전체 case에 대해 초기 재고값으로 초기화해줄 필요가 있기 때문에 `CaseIterable` 프로토콜을 준수 합니다.
- 각 과일과 그 갯수는 Dictionary 타입의 인스턴스 변수로 관리하고 있습니다. 원하는 과일에 대해 빠르게 그 갯수를 알기 위해서 입니다.
- 과일쥬스를 만들기 전에 확실히 그 모든 재고가 존재하는지 확인 해야 할 필요가 있습니다. 과일을 만들던 중 일부 재료가 없음이 확인 되었을 경우를 대비하기 위해서 입니다. 따라서 재고를 조절 하는 역할 외에 열람 할 수 있는 역할또한 갖고 있습니다. (`getStock(of:)` 메소드)
## struct `JuiceMaker`
- 과일쥬스< 를 구분해야 하므로 `Juice` enum을 생성 해 주었습니다. 
- 과일쥬스에 대해 필요한 과일과 그 양을 알아야 합니다. 그것을 private struct `Recipe`를 통해 구현 해 주었습니다. 각 `Juice` case안에 연관값을 통해 구현하기엔 `Juice`가 타입 외부에서도 접근 가능하기 때문에 연관값으로 사용하고 싶지 않았습니다. 
- `Recipe` 안에서 과일쥬스에 대한 필요한 `과일의 종류와 개수`는 `NeededFruit` DTO로 관리되고 있습니다. 튜플로 하기에는 튜플은 저에게는 임시적인 느낌이 있는데 그보다 더 블록 밖에서도 쓰이는 중요도가 있는 타입이 사용되야 한다고 생각되었기 때문입니다.
- 과일 쥬스를 만드는 과정은 `validateStock(of:)` 와 `useStock(of:)` 의 과정으로 나누어져 있습니다. 모든 과일의 재고가 충분하다는 보장이 되었을 경우에 재고를 사용 하기 위함입니다. 각 과일의 종류 별로 재고를 차감 할 텐데 중간에 그 재고 부족이 발견되었을 경우 그걸 복구해주는 방법보다 깔끔하다고 생각했기 때문입니다.

2022-02-16 13:42 UTC, zdodev requested changes
안녕하세요! @momo-youngg , @DayeonJung
리뷰를 진행하게 된 소대입니다.😁

스텝1 PR 축하합니다! 타입 및 메서드의 역할이 잘 분리되어 있고, 간결하게 작성되어 있어서 읽기 수월했습니다.👍

대부분의 프로젝트 제약사항도 잘 지켜주셨습니다.👍
다만 UML를 작성하신 부분이 놓치신 것 같습니다. 이 부분도 추가해주시면 좋을 것 같습니다!

그리고 현재 프로젝트를 어떤식으로 하는지 궁금합니다. (@momo-youngg 의 커밋 내용만 보여서 궁금했습니다.😅)

몇 가지 궁금한 점을 남겨보았습니다.
코멘트에 대해서 같이 의견 나눠보면 좋을 것 같습니다.🤗

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private static let DEFAULT_FRUIT_QUANTITY: Quantity = Quantity(10)
`DEFAULT_FRUIT_QUANTITY` 프로퍼티명을 대문자 및 `_` 로 작성하신 특별한 이유가 있을까요?🤔
`API Design Guidelines` 의 네이밍 가이드처럼 변경해보는 것은 어떨까요?😁

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Quantity.swift
> +struct Quantity: Equatable {
과일의 수량을 나타내기 위해 별도의 `Quantity` 타입을 구현하신 점이 좋습니다.👍

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Quantity.swift
> +    }
`Quantity` 의 연산자를 잘 구현해주셨네요. 👍

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/Quantity.swift
> +    static let ZERO: Quantity = Quantity(0)
`ZERO` 프로퍼티명을 대문자로 작성하신 특별한 이유가 있을까요?🤔
`API Design Guidelines` 의 네이밍 가이드처럼 변경해보는 것은 어떨까요?😁

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/Model/FruitStoreTests.swift
> +class FruitStoreTests: XCTestCase {
좋습니다.👍

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/Model/FruitStoreTests.swift
> +    private var sut: FruitStore!
sut 네이밍 좋습니다.👍

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/Model/JuiceMakerTests.swift
> +        sut = JuiceMaker(fruitStore: FruitStore(everyStock: Quantity(Int.max)))
`Quantity(.max)` 표현법도 괜찮아 보입니다. 의견이 궁금합니다!😁

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/Model/JuiceMakerTests.swift
> +        XCTAssertNoThrow(try sut.make(of: juice))
테스트 이름을 보면 쥬스를 만들 수 있다(성공)는 것을 기대할 수 있는 네이밍이지만,
실제 작성된 테스트의 경우 에러가 발생하지 않으면 통과하도록 작성되어 있습니다.
'에러가 발생하지 않았다'는 결과가 '쥬스를 만들 수 있다'라는 결과로 바로 연관 짓기에는 조금 불명확하지 않을까 생각이 들었습니다.🤔
의견이 궁금합니다! 이대로 진행하셔도 괜찮습니다.😁

2022-02-16 13:42 UTC, zdodev commented on JuiceMaker/JuiceMakerTests/Model/QuantityTests.swift
> +    }
setUp, tearDown 에서 특별하게 수행하는 작업이 없다면 제거해보는 것은 어떨까요?🤔

2022-02-16 13:57 UTC, DayeonJung commented
> 안녕하세요! @momo-youngg , @DayeonJung 리뷰를 진행하게 된 소대입니다.😁
> 
> 스텝1 PR 축하합니다! 타입 및 메서드의 역할이 잘 분리되어 있고, 간결하게 작성되어 있어서 읽기 수월했습니다.👍
> 
> 대부분의 프로젝트 제약사항도 잘 지켜주셨습니다.👍 다만 UML를 작성하신 부분이 놓치신 것 같습니다. 이 부분도 추가해주시면 좋을 것 같습니다!
> 
> 그리고 현재 프로젝트를 어떤식으로 하는지 궁금합니다. (@momo-youngg 의 커밋 내용만 보여서 궁금했습니다.😅)
> 
> 몇 가지 궁금한 점을 남겨보았습니다. 코멘트에 대해서 같이 의견 나눠보면 좋을 것 같습니다.🤗

안녕하세요 반갑습니다! DayeonJung 입니다! 
STEP 1을 모모가, STEP 2는 제가, STEP 3는 역할을 나누어 맡은 사람이 주도하여 구현을 합니다.
각자 구현한 부분을 fork 받은 레파지토리의 main 브랜치에 PR을 올려 서로 의견을 나눕니다.
그 후 합의가 된 부분을 이 PR에 올리는 방식으로 진행하고 있습니다. 😃

2022-02-16 15:43 UTC, momo-youngg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private static let DEFAULT_FRUIT_QUANTITY: Quantity = Quantity(10)
다른언어에서 쓰이던 습관을 신경을 못썼네요 😅
API Design Guidelines 의 내용대로 `프로토콜, 타입 외에는 lowerCamelCase` 반영 완료 했습니다!

2022-02-16 15:43 UTC, momo-youngg commented on JuiceMaker/JuiceMaker/Model/Quantity.swift
> +    static let ZERO: Quantity = Quantity(0)
요것 또한 변경 완료 했습니다!

2022-02-16 15:43 UTC, momo-youngg commented on JuiceMaker/JuiceMakerTests/Model/JuiceMakerTests.swift
> +        sut = JuiceMaker(fruitStore: FruitStore(everyStock: Quantity(Int.max)))
타입프로퍼티 또한 타입명이 생략 가능하군요...! 변경 했습니다!

2022-02-16 15:44 UTC, momo-youngg commented on JuiceMaker/JuiceMakerTests/Model/QuantityTests.swift
> +    }
제거 완료 했습니다!

2022-02-16 15:47 UTC, momo-youngg commented
> 안녕하세요! @momo-youngg , @DayeonJung 리뷰를 진행하게 된 소대입니다.😁
> 
> 스텝1 PR 축하합니다! 타입 및 메서드의 역할이 잘 분리되어 있고, 간결하게 작성되어 있어서 읽기 수월했습니다.👍
> 
> 대부분의 프로젝트 제약사항도 잘 지켜주셨습니다.👍 다만 UML를 작성하신 부분이 놓치신 것 같습니다. 이 부분도 추가해주시면 좋을 것 같습니다!
> 
> 그리고 현재 프로젝트를 어떤식으로 하는지 궁금합니다. (@momo-youngg 의 커밋 내용만 보여서 궁금했습니다.😅)
> 
> 몇 가지 궁금한 점을 남겨보았습니다. 코멘트에 대해서 같이 의견 나눠보면 좋을 것 같습니다.🤗

UML 파일 루트에 포함 시켰으며 PR 본문에도 추가 완료 했습니다! ㅎㅎ

2022-02-17 12:01 UTC, zdodev approved these changes
안녕하세요! @momo-youngg , @DayeonJung !

UML과 피드백 부분 잘 반영주셨습니다!
문서화 주석과 커밋 메시지가 인상적이었습니다.👍

스텝1은 여기서 마무리하도록 하겠습니다. 고생하셨습니다.😁

2022-02-17 12:01 UTC, merged