쥬스메이커 [STEP 1] Derrick, Ryan
yagom-academy/ios-juice-maker pull request #158
Opened 2022-02-16 15:08 UTC by ryan-son

@wonhee009 

라자냐, 안녕하세요. 쥬스메이커 Step 1 PR 드립니다.

## 고민한 점
#### 1. 과일과 과일의 재고를 다룰 때 딕셔너리를 활용하였습니다.
  - 과일 타입과 재고를 가지는 커스텀 타입을 정의하여 사용하는 것보다 딕셔너리를 활용하면 키 값을 통해 재고에 빠르게 접근할 수 있다는 장점이 있다고 판단하였습니다.
  - 딕셔너리의 키 값은 `Hashable`을 준수하여 딕셔너리 내부에 유일한 값임을 보장할 수 있습니다.
#### 2. `ViewController`에서 사용될 최종적인 인터페이스를 고려하여 `FruitStore`와 `JuiceMaker` 타입을 설계하였습니다.
  - 예를들어, `UIStepper`의 value 프로퍼티가 `JuiceMaker`를 통해 `FruitStore`의 재고를 설정할 수 있도록 만들었습니다.
#### 3. 쥬스 제조에 필요한 재료 타입 (딕셔너리)을 생성하는데 빌더 패턴을 활용했습니다.
  - 쥬스 재료 인스턴스를 생성하기 위해 과일의 종류, 개수 등 결정하여야하는 요소가 다양하기에 이를 단순화하는데 패턴을 활용하였습니다.
  - 쥬스를 열거형으로 정의하여 새로운 쥬스가 추가되거나 기존의 쥬스가 삭제될 경우 `IngredientsDirector` `ingredients(for:)`의 switch 구문에서 컴파일 에러를 통해 재료 추가/삭제 여부를 즉시 파악할 수 있습니다 (휴먼 에러 방지).
#### 4. 로직에 대한 검증을 위해 상정할 수 있는 케이스에 대해 유닛 테스트를 작성하였습니다.

---

아쉬운 점이 있으시면 조언 부탁드립니다!

즐거운 하루 보내세요~ 😊

2022-02-17 04:59 UTC, wonhee009 requested changes
@ryan-son @derrickkim0109 스텝1 수고하셨습니다!🎉
코드가 굉장히 깔끔하고 extension, protocol을 적극 활용하신 점 좋았습니다👍
몇몇 코멘트 남겨두었으니 확인 부탁드립니다! 🙏

2022-02-17 04:59 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`subtracted`의 타입이 Fruits = [Fruit: Int]일거 같은데용
Fruits의 모든 element가 0보다 많다면 O(n)번을 탐색하겠네용
> 과일 타입과 재고를 가지는 커스텀 타입을 정의하여 사용하는 것보다 딕셔너리를 활용하면 키 값을 통해 value에 빠르게 접근(O(1))할 수 있다는 장점이 있다고 판단하였습니다.

위와 같이 적어주셨는데 이런 딕셔너리의 O(1) 장점을 살리도록 개선할 수 있을까요?

2022-02-17 07:59 UTC, derrickkim0109 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +protocol FruitStoreType {
@ryan-son 과 상의 후 다시 수정하여 올려 두겠습니다.

2022-02-17 15:22 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
O(1)의 복잡도를 달성하려면 딕셔너리 내부의 어떤 과일이 가장 적게 남아있는지 알아야 가능할 것 같은데, 정답을 모르는 상황에서 어떤 키가 가장 작은 수를 가지고 있는지 알 수 있는 방법이 있을지 궁금합니다. 

저희가 고민한 후보들은 아래와 같습니다.
1. sort 후 최소값이 0보다 작은가 (`sorted()` -O(nlogn))
2. value들의 min값이 0보다 작은가 (`min()` -O(n))
3. value가 0보다 작은 값을 가지고 있는가 (`contains(where:)` - O(n))

이 중에서 저희가 이러한 선택을 한 이유는 정답을 모르는 상태에서 해당하는 것 (음수)이 등장했을 때 다음 결과를 도출하지 않고 바로 결론을 도출할 수 있기 때문이었습니다. 라자냐가 의도한 다른 방법은 어떤 것인가요?

2022-02-17 15:24 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +protocol FruitStoreType {
자격조건 또는 그 자체를 나타내는 `-able`, `-ible`, `-ing`, `명사형` 중에서 `-able`을 채택하여 아래와 같이 명칭을 변경하였습니다.
`FruitStorable`, `JuiceMakeable`

2022-02-17 15:31 UTC, ryan-son commented
라자냐, 리뷰해주신 내용에 답변을 남겼습니다.

시간복잡도에 관련된 질문은 이야기 나누어 보았으면 좋겠네요.

즐거운 하루 보내세요. 😊

2022-02-18 11:15 UTC, wonhee009 commented
> 라자냐, 리뷰해주신 내용에 답변을 남겼습니다.
> 
> 시간복잡도에 관련된 질문은 이야기 나누어 보았으면 좋겠네요.
> 
> 즐거운 하루 보내세요. 😊


네넵 좋아요~ 이후에 디코에 방하나 만들어서 얘기해보도록 해요! 우선 이 부분은 얘기 나눈 이후에 반영하도록 하고 머지하겠습니다!

2022-02-18 11:15 UTC, merged