쥬스 메이커 [STEP 1] 훈하, 강경
yagom-academy/ios-juice-maker pull request #159
Opened 2022-02-16 18:20 UTC by HoonHaChoi

안녕하세요 라쟈나😀

이번 쥬스메이커 프로젝트의 캠퍼인 훈하, 강경입니다.

리뷰에 있어 적절한 당근과 채찍 잘 부탁드리겠습니다.🥲

저희 팀이 생각한 다이어그램 구조는 이렇습니다. 

<img width="700" alt="스크린샷 2022-02-17 오전 2 29 14" src="https://user-images.githubusercontent.com/33626693/154321976-67018756-0256-494e-ba7f-9fcb4ad7c1bd.png">

--- 
## 코드를 작성할 때 고민되었던 점

코드를 작성하면서 고민했던점은 다형성을 어떻게 주어야 할까 를 고민했습니다. 그리고 그 중 한가지를 목표를 정했었는데 
최대한 Switch case , if else 를 다형성을 주기위해서 사용하지 말자 라는 목표를 생각했습니다.
이유는 Switch case , if else가 변화에 생겼을때 연쇄적인 수정이 발생할 수 있어 지양하려고했습니다. 

먼저 FruitStore에서 데이터 타입의 다형성으로 무엇으로 가지고 있을지 배열부터, 2차원배열, 딕셔너리 등 여러 타입등을 비교를 해봤고
|<img width="400" alt="스크린샷 2022-02-17 오전 2 44 20" src="https://user-images.githubusercontent.com/33626693/154324461-c0ffaf5b-aadc-4579-9bbf-a1b325e322d8.png">|<img width="400" alt="스크린샷 2022-02-17 오전 2 44 31" src="https://user-images.githubusercontent.com/33626693/154324504-12d635a5-41e2-47c9-9f52-c8193106b66c.png">|<img width="400" alt="스크린샷 2022-02-17 오전 2 44 44" src="https://user-images.githubusercontent.com/33626693/154324537-01072ffd-994c-4006-a51a-c3faa6ead178.png">|
|------|---|---|

그 중 딕셔너리를 사용하는것이 데이터 타입에 다형성을 주기 용이하다 판단되어 사용를 하게 되었습니다.

- 상속을 이용하지 않은 이유:  각 과일별로 특징을 추가하지 않았기 때문에 상속을 할 이유가 없다고 생각했습니다.

그다음으로 고민했던 다형성은 주문이 되었을때 필요한 과일과 개수을 표현한 Recipe 라는 객체에 대한 다형성을 어떻게 줄수 있을까에 대해 고민했습니다.

```swift
struct JuiceRecipesMapper {
    private let mapping: [JuiceRecipeType: JuiceRecipe]
    
    init(jucieRecipeTypes: [JuiceRecipeType], recipes: [JuiceRecipe]) {
        self.mapping = Dictionary(uniqueKeysWithValues: zip(jucieRecipeTypes, recipes))
    }
    
    subscript(recipeType: JuiceRecipeType) -> JuiceRecipe? {
        return mapping[recipeType]
    }
}
```
그런 고민의 결과로 
레시피 타입들과 레시피 가진 배열을 결합하여 딕셔너리를 가진 Mapper라는 객체를 구현을 했습니다.
어떤 레시피타입이 들어와도 해당 타입에 맞는 레시피 객체가 나오도록 하였고 추가 및 삭제의 경우 레시피 타입과 레시피 해당배열의 값을 추가,삭제 하더라도 변화에 용이할 수 있었습니다.
- 하지만 주문할 수 있는 쥬스가 백만개가 있다면..🤔 더 좋은 다형성을 가질 수 없을지 고민을 해야될거 같습니다. 

마지막으로 클린코드의 "모든 원시 값과 문자열을 포장합니다" 이 규칙을 지키려고 노력을 했었습니다.
처음 레시피 타입의 경우 아래와 같이 작성했었지만
```swift
let recipe: [[Fruit], [Int], name] = [[.banana, .mango], [2, 3], "망고바나나"]]
```
수업을 통해서 3개의 프로퍼티를 가지지 않도록 해라 규칙이 계속 생각이 들어 
현재타입보다 더 포장할 수 없을지에 대해 고민하며 "Ingredient" 타입이 나올 수 있었던 거 같습니다.

## 아쉽게 생각한 코드

한가지 일을 하도록 작성하려고 노력을 했지만 FruitStore 객체에서 
재고 검증 후 재고소진 기능 코드를 작성하면서 중복되는 코드를 작성하는것이 느껴졌습니다.

재고 검증 후 재고소진에 대한 로직은 2개의 과일이 필요한 경우 한가지라도 재고가 있지않으면 재고소진이 되지 않도록 하고 있다면 소진되도록 작성을 했는데 

이과정에서 중복되는 코드가 있어 좋은 방법을 없을까 고민을 했었는데 뚜렷한 방법을 찾지 못하고 진행을 했습니다.

2022-02-17 05:47 UTC, wonhee009 requested changes
@KangKyung @HoonHaChoi 스텝1 수고하셨습니다!🎉
코드 역할을 나누려고 노력하신 모습이 보이는 코드였습니다!
몇몇 코멘트 남겨두었으니 확인 부탁드려요🙏

2022-02-17 05:47 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
```swift
mutating func increase(in fruit: Fruit, stock: Int = 1) throws { ... }
```
이렇게 기본 값을 갖는 형태는 어떨까요?
재고가 1개만 추가되지 않을거 같아서용

2022-02-17 05:47 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Ingredient.swift
> +}
과일, 수량을 갖는 구조체를 정의하셨군요👍
`private var inventory: [Fruit: Int]`와 비슷한 부분이 있는거 같은데요.
하나의 타입으로 정리하는건 어떨까요?
(다른 의견 혹은 이유가 있다면 언제든지 알려주세요!)

2022-02-17 05:47 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`is-`인데 Bool 값을 반환하지 않아도 괜찮을까요?
주스를 만드는데 재고가 부족한게 에러 상황일까요? 에러 상황이라면 재고가 부족한 곳에서의 에러가 아닌 주스를 만드는 곳에서의 에러일거 같은데 어떻게 생각하실까용?.?

`hasStock()`은 어떨지 의견 드려봅니당🤔

2022-02-17 05:47 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +struct FruitStore: Store {
struct로 구현하신 이유가 궁금합니다!

2022-02-17 05:47 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`makeJuice()`는 어떨지 의견 드려봅니당

2022-02-17 05:47 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
JuiceMaker에도 `increase`와 `decrease`가 있는 이유가 있을까요?

2022-02-17 05:47 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Util/JuiceRecipesMapper.swift
> +}
이런 형태는 결국
```swift
[enum JuiceRecipeType : ([Ingredient], name)]
```
이런 모양일거 같은데요.
좀 더 간결한 모양을 갖을 수 있을까요?

또한, JuiceRecipesMapper와 JuiceRecipes의 차이는 무엇인가요?

2022-02-17 08:07 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +struct FruitStore: Store {
struct를 사용한 이유는 
반대로 생각하면 class를 사용할 필요가 있을까? 에 대해 생각했습니다.
현재 상황에서 참조 값을 사용해 구현을 해야하는것이 있는지, 상속을 해야하는지, RC를 이용해야하는지 들을 고민한 결과 
고민들에 대한 합당한 이유도 없으며 Class로 사용해야될 필요성도 없다고 판단하여 Struct로 구현을 했습니다.

2022-02-17 08:17 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
좋은 생각이신거 같습니다.
increase, decrease에 +1, -1을 생각했던 이유는 
재고 수정을 하는 상황(재고 수정 화면) +,- 두 액션의 경우만 요구사항에 맞게 구현을 생각 하다보니 +1 -1 지정을 하게 되었습니다.
앞으로의 대한 유지보수를 생각한다면 기본값을 제공하는게 좋을거같습니다!

2022-02-17 09:17 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/Ingredient.swift
> +}
얘기 해주시니 비슷해보이기도 하네요

Store의 경우는 창고의 생각하며 Fruit는 창고의 칸, Int는 칸의 있는 개수를 딕셔너리로 표현을 생각하며 구현을 했었고
Ingredient의 경우에는 레시피에 적힌 필요한 재료 표현을 생각하며 구현했었습니다.

하나의 타입으로 정리하는것을 시도 해보고 원하는 방향대로 동작?이 안된다고 생각되면 현재 구현된 타입으로 진행해도 괜찮을까요??

2022-02-17 09:20 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
재고 부족이 에러 상황일까에 대해서 생각지도 못했던 부분이네요 원하는 동작이 안되면 에러를 나타내야지 그렇게 생각했었는데🥲

이부분에 대해서도 수정하기 위해 고민해봐야겠습니다! 
네이밍도 참고하겠습니다!

2022-02-17 09:23 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
네이밍 잘 떠오르지 않아서 같은 이름을 제공했었습니다. ㅠㅠ
이름 잘 짓는 네이밍의 길은 쉽지 않네요😩

2022-02-17 09:25 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
참고하겠습니다!.

2022-02-17 11:09 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Ingredient.swift
> +}
'다형성을 주고자 딕셔너리로 표현' 했다는 말씀이 잘 이해가 가지 않는데요. 좀 더 자세하게 설명해주실 수 있을까용~?
그리고 struct 대신 튜플을 사용해도 같은 기능을 지원할 수 있을거 같은데 struct를 선택한 부분도 궁금합니다:)

2022-02-17 11:29 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
`increase`, `decrease`가 fruitStore의 `increase`, `decrease`를 호출만해주는거로 보이는데요.
JuiceMaker에서 fruitStore의 증가/감소를 호출하는 경우는 어떤 경우인가요?

2022-02-17 11:40 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Util/JuiceRecipesMapper.swift
> +}
```swift
// JuiceRecipes
self.recipes = [
            JuiceRecipe(ingredients: [.init(fruit: .strawberry, number: 16)], name: .strawberryJuice),
            JuiceRecipe(ingredients: [.init(fruit: .banana, number: 2)], name: .bananaJuice),
            JuiceRecipe(ingredients: [.init(fruit: .kiwi, number: 3)], name: .kiwiJuice),
            JuiceRecipe(ingredients: [.init(fruit: .pineapple, number: 2)], name: .pineappleJuice),
            JuiceRecipe(ingredients: [.init(fruit: .strawberry, number: 10),
                                      .init(fruit: .banana, number: 1)], name: .strawberryBanananJuice),
            JuiceRecipe(ingredients: [.init(fruit: .mango, number: 3)], name: .mangoJuice),
            JuiceRecipe(ingredients: [.init(fruit: .mango, number: 2),
                                      .init(fruit: .kiwi, number: 1)], name: .mangoKiwiJuice)
        ]

// JuiceRecipesMapper
init(jucieRecipeTypes: [JuiceRecipeType], recipes: [JuiceRecipe]) {
        self.mapping = Dictionary(uniqueKeysWithValues: zip(jucieRecipeTypes, recipes))
    }
```

두개의 생성부인데요.
현재 구조에서 주스가 추가된다면 enum JuiceType case와 JuiceRecipes의 self.recipes의 순서를 맞춰야 원하는대로 동작할거 같은데요. 이해한 바가 맞을까요?

2022-02-17 14:42 UTC, KangKyung commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
> JuiceMaker에서 fruitStore의 증가/감소를 호출하는 경우는 어떤 경우인가요?

말씀해주신대로, 어떤 경우에 호출하는지를 생각해보면 명확한 이름짓기에 도움이 될거 같네요👍🏻

2022-02-17 14:53 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/Ingredient.swift
> +}
과일에 대한 다양한 타입을 딕셔너리로 가질수 있기에 딕셔너리로 다형성을 주고자 표현했다는 뜻이었습니다!

구현을 진행하면서 튜플도 고민했었지만 이번 프로젝트에선 클린코드의 규칙인 "원시값과 문자열을 포장"이란 목표로 정하며 진행을 했었고
struct를 타입으로 만드는 선택을 하게 되었습니다.

2022-02-17 14:58 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
재고 수정 화면에서 + - 버튼 액션을 통해 JuiceMaker가 fruitStore에 해당 과일 증가,감소 하라는 메시지를 보내는 경우입니다.

2022-02-18 04:12 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Ingredient.swift
> +}
어떤 목적을 가지고 struct로 구현하셨는지는 이해했습니다!
딕셔너리가 다양한 과일 타입을 갖는다고 다형성을 갖게 될까요?🤔
(이 부분은 이 프로젝트를 진행하면서 계속 생각해봐도 좋을 주제일거 같네용)

2022-02-18 04:14 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
`JuiceMaker`가 재고를 수정하는 역할을 갖는게 맞을까요?
`JuiceMaker`가 갖는 역할은 어떤걸가요?

2022-02-18 04:49 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Util/JuiceRecipesMapper.swift
> +}
이후에 강경이나 훈하가 아닌 다른 개발자가 enum의 케이스들이 abc순으로 정렬된게 좋아서 아래와 같이 변경을 했습니다.
```swift
// 원래 코드
 enum RecipeName: String, CustomStringConvertible {
   case strawberryJuice = "딸기쥬스"
   case bananaJuice = "바나나쥬스"
   case kiwiJuice = "키위쥬스"
   case pineappleJuice = "파인애플쥬스"
   case strawberryBanananJuice = "딸바쥬스"
   case mangoJuice = "망고쥬스"
   case mangoKiwiJuice = "망고키위쥬스"
}

// 변경된 코드
 enum RecipeName: String, CustomStringConvertible {
   case bananaJuice = "바나나쥬스"
   case pineappleJuice = "파인애플쥬스"
   case strawberryJuice = "딸기쥬스"
   case strawberryBanananJuice = "딸바쥬스"
   case mangoJuice = "망고쥬스"
   case mangoKiwiJuice = "망고키위쥬스"
   case kiwiJuice = "키위쥬스"
}
```
그럼 이 개발자는 recipes의 순서를 바꿔야하는걸 인지하고 있을까요?
인지하고 있다고 하더라도 `self.recipes`의 모양을 보고 어떤게 어떤 주스의 레시피인지 한 번에 알 수 있을까요?
그리고 변경하는 과정에서 휴먼 에러가 안 날 수 있을까요?
좀 더 편하지만 휴먼 에러가 없는 방식/좀 불편하지만 휴먼 에러를 방어할 수 있는 방식이 있다면 휴먼 에러를 방어할 수 있는 방식이 좀 더 좋다고 생각합니다.

2022-02-18 08:34 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Util/JuiceRecipesMapper.swift
> +}
변경하는 과정에서 충분히 휴먼에러가 날 수 있는 방식이라 인지 하고 있었습니다. 타입의 순서가 변경된다면 레시피들에 대한 수정도 불가피하게 이뤄저야하며 수정 중에 에러가 발생할 수 있을거라 생각했습니다.

```swift
switch recipeType {
        case .strawberryJuice:
            <#code#>
        case .bananaJuice:
            <#code#>
        case .kiwiJuice:
            <#code#>
        case .pineappleJuice:
            <#code#>
        case .strawberryBanananJuice:
            <#code#>
        case .mangoJuice:
            <#code#>
        case .mangoKiwiJuice:
            <#code#>
        }
```

Switch case 변화에 일일이 맞춰야하는 단점을 최대한 이용하지 않으려 했던 과도한 노력이였고 적당한 swiftch case의 활용이 휴면에러를 방지 할 수 있다는점, 좀 더 한눈에 알 수 있다는 점을 이런 과도한 노력을 통해서 느낍니다.
이런 도전을 하려 했었구나 라고 생각해주시면 감사하겠습니다!

Switch case 에 질문이 있는데
Switch case는 depth가 1 일까요? 2일까요?
들여쓰기 1로 지키려고 노력했는데 Switch case가 2이지 않을까 싶어서 안쓰려고 했던 이유도 있습니다😅

2022-02-18 08:37 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
먼저 STEP 1 의 요구사항 정의에 이런 문구가 있습니다.
	◦	JuiceMaker는 FruitStore를 소유하고 있습니다

제 생각은 
FruitStore가 JuiceMaker의 소유가 아니라면 
재고 수정 화면에서는 JuiceMaker를 알지 않아도 FruitStore에게 재고 수정 메시지를 전달 할 수 있다고 생각합니다

하지만 JuiceMaker는 FruitStore를 소유하고 있기에 증가, 감소 메시지를 JuiceMaker를 통해 전달하도록 하는 흐름을 생각했었습니다.

역할에 대한 생각은 JuiceMaker역할은 쥬스를 만드는 역할이며 
과일 재고를 소유하고 있기에 FruitStore에 수행해야 될 책임을 할당해주는 역할도 가지고 있다고 생각합니다.

2022-02-18 11:11 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
재고에 관한 부분은 스텝2에서 좀 더 얘기해보도록 해요:)

2022-02-18 12:10 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Util/JuiceRecipesMapper.swift
> +}
음... 제가 드린 예시처럼 case의 순서만 바뀔 경우에는 컴파일/런타임 에러는 안 날텐데요. 로직 에러라서 사실상 디버깅도 힘들고요.
`switch case`를 사용하지 않으면서 휴먼 에러를 방지할 수 있는 방식도 있을거 같습니다.
```swift
enum juiceType: CaseIterable, Int {
   case 딸기주스 = 0
   case 바나나주스 = 1
   case 망고주스 = 3
   case 망키주스 = 2
}
```
이런식으로 주스와 사용되는 재료들 사이에 순서를 지정해서 사용하는 방식도 있을거 같구요.
휴먼 에러가 날 수 있음을 작성자는 인지하고 있을 수 있지만 다른 개발자들은 그런 부분들을 고려하지 않고 봅니다.
또한, 이렇게 컴파일/런타임 오류가 나지 않고 로직 오류라면 더더욱 알아채기 힘들고요.
보통 다른 개발자들과 **협업**을 하면서 일하게 되는데 User의 휴먼 에러가 아닌 작성자의 휴먼 에러를 잠재적으로 갖고 있는 코드라면 지양하는게 맞지 않을까요?
그리고 depth에 대해서는 `switch case`에 대해서는 1이지 않을까 싶네용

2022-02-18 15:19 UTC, HoonHaChoi commented on JuiceMaker/JuiceMaker/Util/JuiceRecipesMapper.swift
> +}
맞습니다. 컴파일 뿐만 아니라 런타임에도 에러를 찾을수 없다면 다음 누군가가 다시 개발한다면은 문제 발생하더라도 원인을 쉽게 찾을수 없을거라 생각하고 그런 코드는 지양하는게 맞다고 생각합니다.
그래서 적절히 switch case를 이용하면서 연쇄적인 수정이 발생하게되면 그때 로직을 한번 고민해보도록 하려합니다!

2022-02-18 15:27 UTC, HoonHaChoi commented
재고 수정에 관련된 메서드 제거 했으면
어색했던 네이밍 수정
불필하게 느낀 메서드 제거
Mapper 또한 제거를 하였습니다
쥬스 만드는 과정에 대한 로직 처리에 집중하며 변경 하였습니다.
쥬스타입에 switch case를 사용해 타입에서 쥬스레시피를 가지고 있어 순서에 상관 없고 컴파일 상황에서도 에러를 쉽게 찾을수 있도록 변경했습니다.

2022-02-19 05:02 UTC, wonhee009 approved these changes
스텝1 수고하셨습니다!👍

2022-02-19 05:02 UTC, merged