쥬스 메이커 [STEP 2] 지니, 힉스
yagom-academy/ios-juice-maker pull request #163
Opened 2022-02-17 14:44 UTC by JIINHEO

안녕하세요! Tony :) @Monsteel 지니(@JIINHEO), 힉스(@higgs1022) 입니다.

### STEP2 에 대해 두번째 PR요청 드립니다! ✨
시간이 너무 촉박하네요 🥲
그럼 이번에도 잘 부탁드립니다 !!🤩

## 🧐 고민했던 점
### 1. 화면 이동방식
화면 이동방식에 대해 고민해봤는데 흐름이 이어지는 방식이 아닌
 멈췄다가 되돌아오는 방식이라 모달로 구현하는게 맞다고 생각해서 모달로 구현했습니다!

### 2. do-catch 
이전 리뷰에서 계속 언급해주셨던 do-catch 문에 대해 고민해봤습니다. 
ViewController에서 사용자에게 얼럿을 띄우려고 하다 보니 정말 do-catch를 이르게 했다는 생각이 들었습니다.! 그래서 ViewController에서 에러를 처리하게 변경하였습니다! 😄

### 3. 객체지향 원칙과 클린코드
객체지향 원칙과 클린코드에 대해 고민하면서 한 메서드에서 한 기능만 수행하려고 노력했습니다!

### 4. 네이밍
네이밍에 대해 굉장히 많을 고민을 했습니다. 
STEP1 리뷰에서 말씀해주신 것처럼 맡은 역할을 잘 표현해야 한다는 말을 계속 생각했고, 
고민하여 아래처럼 변경하니 훨씬 명확해졌다고 생각합니다. !!😊
``` 
makeJuice(juice: Juice)를 
make(of juice: Juice)로 변경
juiceMaker.makeJuice(juice: .bananaJuice)에서
juiceMaker.make(of .bananaJuice)
``` 

## 🤔 궁금한 점
### 1. 각 버튼이 눌렸을 때 어떤 버튼이 눌렸는지 알 수 있는 방법
IBAction{}이 버튼별로 생성(7개)되니 중복을 줄여주는게 좋겠다고 생각하여 
각 Button의 IBAction을 하나의 메서드로 연결했습니다. 

그 과정에서 누른 버튼의 주스를 찾아 그 주스를 주문하게 구현했는데, 
이 방식을 버튼타이틀과 주문네임을 비교해서 맞는 쥬스가 있다면 쥬스를 만들게끔 만들었습니다. 

그런데 직접적으로 ButtonTitle과  juice.name을 비교하는 방식이라 안 좋은 방법이라 생각합니다. 

다른 방법을 고민해보고 있는데.. 혹시 이런 경우에 어떤 버튼이 눌렸는지 알 수 있는 방법이 있을까요?!🤔

2022-02-18 09:06 UTC, Monsteel requested changes
안녕하세요 지니, 힉스~!
두번 째 스텝도 수고 많으셨습니다 🎉🎉
고민했던점, 그리고 커밋을 세세하게 나눠주셔서 두분이 어떤 생각을 하셨는지 쉽게 파악할 수 있었습니다 ~!

특히 
> IBAction{}이 버튼별로 생성(7개)되니 중복을 줄여주는게 좋겠다고 생각하여
각 Button의 IBAction을 하나의 메서드로 연결했습니다.

부분이 인상적이였습니다 👀

그리고 작성해주신 질문에 대해 답변을 남겨보겠습니다~! 🙌

### Q 각 버튼이 눌렸을 때 어떤 버튼이 눌렸는지 알 수 있는 방법

변경이 잦은 타이틀을 코드단에서 식별자 처럼 사용하시는게 불안하셨을것 같아요~!
이 부분은 UIView에 정의된 tag를 사용해서 해결해 볼 수 있을것 같은데요!

이 부분을 어떻게 활용하면 좋을지, 혹은 어떻게하면 보다 안전하게 사용할 수 있을지 등을 고민해보면 좋을것 같습니다! 🙌


두분이서 아주 깔끔하게 잘 진행해 주셔셔 코드에 대한 리뷰는 마이너한 몇가지 밖에 없습니다 🙌

확인해 보시고 다시 재 리뷰요청 주시면 감사하겠습니다 🙇🏻‍♂️🙇🏻‍♂️

스텝2도 수고 많으셨습니다! 🙌

2022-02-18 09:12 UTC, Monsteel requested changes

2022-02-18 09:12 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ModalViewController.swift
> +class ModalViewController: UIViewController {
어떤 역할을 하는지 조금 더 명확한 네이밍을 가져가면 좋을것 같습니다 📝

2022-02-18 09:12 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
어떤 역할을 하는지 조금 더 명확한 네이밍을 가져가면 좋을것 같습니다 📝

2022-02-18 16:28 UTC, JIINHEO commented on JuiceMaker/JuiceMaker/Model/Result.swift
> +enum Result<Success, Failure: Error> {
`orderMenu()`에서 성공 여부를 처리하는 과정에서 사용했었는데, 
 **STEP1** 리뷰에서 do-catch 문이 이르다고 말씀해주셨던 `makeJuice()`의 do-catch 문이  `orderMenu()`로 나오면서 불필요하게 되었습니다! step1 리뷰를 기다리는동안 step2를 진행하고 추 후에 변경사항을 merge 하는 과정에서 미처 삭제하지 못했네요 🥺 알려주셔서 감사합니다 :)

2022-02-18 16:39 UTC, JIINHEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        for needFruit in juice.recipe.fruitList {
음.. 저도 그 부분을 고민했었는데! 

프로젝트 수행시 제약사항에 "들여쓰기를 1번을 초과하지 않는다"라고 되어있어서 
그 부분을 지키기 위해 이렇게 진행하게 되었습니다.
아래의 reduce()도 같은 이유입니다! 

만약 이 반복문이 checkEnough()로 들어가게 되면 for, guard로 두번의 뎁스가 생겨버리는데..🤔 
혹시 토니의 생각은 어떠한가요? 🙋🏻‍♀️

``` 
    /// 사용해야할 과일이 매장재고에 있는지 검사한다.
    func checkEnough(for juice: Juice) throws {
        for needFruit in juice.recipe.fruitList {
            guard let storeFruitQuntity = stock[needFruit.fruit], storeFruitQuntity >= needFruit.quantity else {
                throw FruitStoreError.notEnoughFruit
            }
        }
    }
```

2022-02-18 16:47 UTC, JIINHEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    case notEnoughFruit = "과일이 부족합니다."
네! 변경 과정에서 불필요해져서 제거했습니다. 😊

2022-02-18 16:56 UTC, JIINHEO commented on JuiceMaker/JuiceMaker/Controller/ModalViewController.swift
> +class ModalViewController: UIViewController {
FruitQuntityViewController 면 괜찮을까요..? 🥲

2022-02-18 16:57 UTC, JIINHEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
JuiceOrderViewController 면 괜찮을까요..? 🥲

2022-02-18 17:07 UTC, JIINHEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            showNotEnoghAlert()
네! 확인했습니다! 이 부분 처리하도록 하겠습니다 😊

2022-02-18 17:26 UTC, JIINHEO commented
안녕하세요. 토니!
STEP2도 역시 꼼꼼하고 세심한 리뷰 남겨주셔서 감동입니다..🥺🥰

> Q 각 버튼이 눌렸을 때 어떤 버튼이 눌렸는지 알 수 있는 방법
변경이 잦은 타이틀을 코드단에서 식별자 처럼 사용하시는게 불안하셨을것 같아요~!
이 부분은 UIView에 정의된 tag를 사용해서 해결해 볼 수 있을것 같은데요!
이 부분을 어떻게 활용하면 좋을지, 혹은 어떻게하면 보다 안전하게 사용할 수 있을지 등을 고민해보면 좋을것 같습니다! 🙌

이 부분에 대해서 고민해봤는데! 
찾아보니 tag는 Int값을 정해줘서 만약 버튼이 100개가 생성된다고 하면 각 태그값이 어떤 버튼을 의미하는지 어려울것으로 예상됩니다. 그래서 각 버튼을 @IBOutlet 변수로 만들고 `tapOrderButton()`에서 버튼을 sender로 받아 switch로 각 버튼 case를 구분하는 방식으로 변경하는게 더 안전하다고 생각되어 이렇게 변경하게 되었습니다. !   

> 두분이서 아주 깔끔하게 잘 진행해 주셔셔 코드에 대한 리뷰는 마이너한 몇가지 밖에 없습니다 🙌

감사합니다 !!! 🙌 
다시 리뷰 요청드립니다.😊

2022-02-19 11:37 UTC, Monsteel approved these changes
지니 힉스 안녕하세요~!🙇🏻‍♂️

오.. 지니가 설명해주신 `@IBOutlet`을 사용하여 switch문으로 사용하신건 정말 좋은 생각이신것 같아요! 👍
아주 멋집니다~!! 👏👏

Step2 수고 많으셨습니다~! 이어서 Step3 리뷰를 진행해보도록 할게요~!

2022-02-19 11:38 UTC, merged