쥬스 메이커 [STEP 3] 지니, 힉스
yagom-academy/ios-juice-maker pull request #164
Opened 2022-02-17 14:59 UTC by higgs1022

안녕하세요! Tony :) @Monsteel  지니(@JIINHEO), 힉스(@higgs1022) 입니다.

STEP3 에 대해 PR요청 드립니다! ✨
목요일까지 step3를 끝내고싶어서 step2에 이어서 전달드립니다 !!🤩

## 🧐 고민했던 점
수정화면을 닫을때 자기 자신의 ViewController가 dismiss를 호출 할지 부모가 dismiss를 호출 할지 조금 고민이었습니다. (어디서 부모가 자식의 라이프 사이클을 관리하는편이 낫다고 본것 같아서)

2022-02-19 11:39 UTC, Monsteel requested changes
안녕하세요 지니 힉스~!
우선 conflict 나는 부분부터 우선 수정 부탁드립니다 🙏

2022-02-19 12:05 UTC, higgs1022 commented
@Monsteel 

step2 리뷰가 끝나기전에 step3 리뷰를 올려두었더니 step2 수정사항에서 충돌이 발생했었습니다~
conflict를 수정하고 merge하였습니다.

merge할 때 코드 수정이 좀 많이 이뤄졌는데 혹시 이상한점 있는지 한번 확인 부탁드립니다~ @JIINHEO

2022-02-19 12:11 UTC, higgs1022 commented
앗 그리고 저희가 페어 프로그래밍을 중간중간에 하고나서 제가 git 설정이 섞이는걸 제대로 관리 못해서 제 대신 지니 이름으로 커밋이 된 경우가 있었습니다.
(지니 커밋량이 압도적으로 많아보여서 ^^;; 조금 이상해 보이네요)

다음부터 커밋 작성자 관리를 좀 더 철저히 하겠습니다.

2022-02-19 12:48 UTC, Monsteel commented
@higgs1022 아하 그러셨군요~! 👀 안그래도 함께 작업하신듯 해 보였습니다~! ㅎㅎ :)
늦은)) 저녁만 먹고... 얼른 리뷰해보도록 할게요!!

2022-02-20 02:28 UTC, Monsteel requested changes
안녕하세요 지니 힉스~ 🙇🏻‍♂️ 리뷰가 늦어져 죄송합니다 🙏
Step3도 정말 잘 진행해 주셨어요~! 👍👍

`FruitQuntityViewDelegate`를 선언하고, 화면이 dismiss되었을 때 과일 수량을 새로고침 해주는 방식이 인상깊었습니다 🙌 

하지만, 보통 한 화면이 아니라 여러개의 화면에 의해 해당 화면에서 보여주어야 할 데이터가 변경될 수 있기 때문에 lifecycle을 활용하여, ViewWillAppear 내지 ViewWillAppear에 화면을 새로고침 하는 로직을 넣는 방식도 있습니다! 🙌

리뷰는 마이너한 부분에 대해서 코멘트 몇개 달았습니다! 🙋🏻‍♂️

고민했던 점에 남겨주신 부분에 대해 저의 생각을 남겨보자면요 📝
lifecycle을 부모가, 혹은 제3자가 관리하는 방법이 있긴 합니다만..

해당 프로젝트에서 부모가 자식의 lifecycle을 관리해서 얻을 수 있는 이점이 어떤 것들이 있을까요?!
`좋은 방향`이라고 소개된 방법을 신봉하기보다는, 각 상황에서 효용성을 따져보면 좋을것 같아요! 🙋🏻‍♂️

주말 잘 보내시구요 🙌 Step3 진행하시느라 수고 많으셨습니다 🙏

2022-02-20 02:28 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        guard let modalViewController = self.storyboard?.instantiateViewController(withIdentifier: "modalViewController") as? FruitQuntityViewController else {return}
ViewController의 이름이 변경됨에 따라 이부분도 대응이 필요합니다 🙌

2022-02-20 02:28 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        let navigaionViewController = UINavigationController(rootViewController: modalViewController)
`UINavigationController`로 감싼 이유가 있으신지 궁금합니다! 🙋🏻‍♂️
`NavigationBar`를 사용하기 위함이라면 다른 방법도 있을것 같아요 🤔

2022-02-20 08:16 UTC, higgs1022 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        guard let modalViewController = self.storyboard?.instantiateViewController(withIdentifier: "modalViewController") as? FruitQuntityViewController else {return}
옙 네이밍을 맞추겠습니다

2022-02-20 08:20 UTC, higgs1022 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        let navigaionViewController = UINavigationController(rootViewController: modalViewController)
옙 이 코드에서 UINavigationController로 감싸지 않고 호출했더니 NavigationBar없이 화면이 나타나게되어 추가했습니다.
NavigationBar에 닫기 버튼이 있어서 닫기 불가능상태로 빠지게 되었었어요.

NavigationBar를 사용하기 위함이면 다른방법이 있으실것 같다고 하셨는데 바로 방법이 떠오르지 않네요... 좀 더 고민해보겠습니다

2022-02-20 23:24 UTC, closed without merging