쥬스메이커 [STEP 2] 카리나, 콩이
yagom-academy/ios-juice-maker pull request #168
Opened 2022-02-18 08:21 UTC by yoojin19

안녕하세요 소대!
카리나, 콩이 입니다.

STEP2도 구현해보았어요

🤔 고민했던 점
기존에 makeJuice를 Bool로 받아오는 값에 대한 필요성
-> 기존에 makeJuice를 Bool로 받아왔습니다. 실제 view에서 기능을 사용해보니 if-else문을 써야 했고 코드를 글처럼 읽을때 잘 읽힐까 고민을 하게되었습니다. 예외처리문이 더 적합하다고 판단 후 수정했어요
뷰의 특성상 각 과일이름을 각자 넣어주어야 하지만 코드를 줄일 수 없을 까 고민해보았어요
-> fruitsLabels을 dictonary로 만들어서 해결하는 방법으로 코드를 살짝이나마 깔끔하게 만들어보았어요
❓ 진행하면서 궁금했던 점
JuiceKioskViewController.orderJuice(of:)에서 alert부분을 함수로 처리했습니다. 하지만 보기에 orderJuice 메서드에서 alert를 해주고 그 뒤에 어떤 행동을 하는지 포함하는것이 더 좋은것인지 고민했어요.
소대는 어떻게 생각하나요?
ex) patchData()라는 행동을 하는 것이 orderJuice함수에서 보이지 않음
patchData를 ViewWillAppear에도 호출하고 다른 함수에서도 호출하니까 나중에 어디서 쓰이는지 보기 힘들것 같아요.
다른방식이 있을까요?
이와 같이 구성해보았답니다.
다른 고민할 점을 이야기 해주어도 좋고
이건 다른 방식으로 만들어도 좋을것 같은데?? 싶은것도 상관 없으니
많이 알려주시면 감사하겠습니다(꾸벅) 😄 👍

@zdodev

2022-02-18 12:39 UTC, zdodev requested changes
안녕하세요. @yoojin19 , @p41155a !

스텝2 PR 축하합니다.🎉

기능 구현 잘해주셨습니다.
전보다 간결해지고 고민한 부분이 많이 보였습니다.👍

>JuiceKioskViewController.orderJuice(of:)에서 alert부분을 함수로 처리했습니다. 하지만 보기에 orderJuice 메서드에서 alert를 해주고 그 뒤에 어떤 행동을 하는지 포함하는것이 더 좋은것인지 고민했어요.
소대는 어떻게 생각하나요?
ex) patchData()라는 행동을 하는 것이 orderJuice함수에서 보이지 않음 

- 지금도 좋다고 생각합니다! 오히려 `orderJuice` 메서드를 간결하게 작성하신 부분이 더 좋았습니다.👍

> patchData를 ViewWillAppear에도 호출하고 다른 함수에서도 호출하니까 나중에 어디서 쓰이는지 보기 힘들것 같아요.
다른방식이 있을까요?

- 여러곳에서 사용할 수 있다는 것이 나중에 찾기 힘들 수 있지만, 두 시점 모두 필요에 의해서 작성했고, 적절한 시점에 잘 호출해주신 것 같습니다. 두 시점을 한 곳에서 캐치할 수 없다면 지금 방식이 좋아보입니다.👍

수정보다는 궁금한 의견을 좀 남겨보았습니다.
궁금한 점 의견 나눠보면 좋겠습니다.🤗

2022-02-18 12:39 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func answerWhenMaked(of answer: String) {
역할로 보아 `success` 로 시작하는 이름을 지어봐도 좋아보입니다.😁

2022-02-18 12:39 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func answerWhenOrderError(of error: Error) {
역할로 보아 `fail` 로 시작하는 이름을 지어봐도 좋아보입니다.😁

2022-02-18 12:39 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +typealias Fruits = [Fruit: Int]
좋습니다! 👍

2022-02-18 12:39 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +        navigationController?.pushViewController(vc, animated: true)
재고 수정 뷰 컨트롤러의 화면전환방식을 navigation push 방식으로 구현하신 이유가 궁금합니다!🤔

2022-02-18 13:34 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +        navigationController?.pushViewController(vc, animated: true)
저도 고민했던 부분인데요. 실제 프로젝트로 만들었다면 재고 추가 화면과 같은 디자인이 왔다면 present로 만들었겠지만, 다음 뷰가 present처럼 보이지만 과제에서 핵심경험이 내비게이션 바 및 바 버튼 아이템의 활용이라고 되어 있어서 과제의 의도가 push라고 판단했어요.

2022-02-18 13:34 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    }
Step 3를 만들어 놓았는데 그 뷰에서는 하나의 action으로 만들어 보았어요
현재 action이 하는 행동이 간단하여 각자 써주었는데 이 부분은 다음 STEP3에서 보고 질문주시면 말해보는 기회가 될것 같습니다.👍🏻

2022-02-18 13:36 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func gotoModifyViewContoller() {
저는 단순이 이동한다는 개념을 함수에 넣고 싶었어요
어떻게 이동하는 지는 함수이름에서 보이진 않아도 된다고 생각했어요
하지만 소대의 네이밍도 좋다고 생각해요

2022-02-18 13:38 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func answerWhenOrderError(of error: Error) {
오~ 그러게요. 주문이 오류났다고 하기 보다는 실패한게 맞는것 같아요

2022-02-18 13:42 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func answerWhenMaked(of answer: String) {
successWhenMaked를 말하는 건가요?
흠 함수를 호출할 때 뭐할지가 보이는것보다
success fail과 같은 구성 요소가 보이는게 중요할까요?
오 새로운 고민요소이네요 소대는 어떻게 생각하시나요?

2022-02-18 14:02 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +typealias Fruits = [Fruit: Int]
이 부분의 네이밍도 조금 고민했어요 어떻게 보면 Fruit와 헷갈릴수도 있고
여기에서 의미는 어떤 fruit의 수인데

만약 소대가 네이밍 했다면 뭐로 했을건가요?

2022-02-18 14:47 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func answerWhenMaked(of answer: String) {
> WhenMaked는 주문을 받고 이미 만든 후라는 것을 알려주려고 했고 성공했는지 보다 뭘 하는지를 보여주는것이 중요하다고 생각해서 네이밍했어요

의견 말씀해주셔서 감사합니다! 좋은 의견이라고 생각합니다~ 
`answerWhenMaked` 이름을 봤을 때 '(음료를)만든 후 대답'이라는 의미로 받아들였는데 메서드 명만 보면 어떤 어떤 역할을 수행하는지 조금 불분명하지 않을까?(이 메서드를 호출하면 어떤 대답을 하는 메서드일까?) 라는 생각이 들었습니다.
그래서 `answer` 보다 `success` 가 명확하지 않을까 한번 의견을 드려봤습니다.😁

하나의 의견으로만 생각해보면 좋을 것 같아요.👍

2022-02-18 14:48 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func answerWhenOrderError(of error: Error) {
위의 코멘트와 의견을 한번 생각해봐도 좋을 것 같습니다.👍

2022-02-18 14:55 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func gotoModifyViewContoller() {
이동한다는 의미도 좋습니다!
개인적으로 뷰(화면, scene)을 표시한다는 의미로 `present`를 사용하고는 합니다.(UIKit 에서도 새로운 뷰 컨트롤러를 표시할 때 `present`를 사용하는 것을 참고하기도 했습니다.😅)

> 저는 단순이 이동한다는 개념을 함수에 넣고 싶었어요
어떻게 이동하는 지는 함수이름에서 보이진 않아도 된다고 생각했어요
하지만 소대의 네이밍도 좋다고 생각해요

의견을 말씀해주셔서 감사합니다!👍

2022-02-18 14:55 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func answerWhenMaked(of answer: String) {
넵! 의견 말해줘서 고마워요 소대
그런 궁금증이 들었다니 네이밍할때 좀 더 생각해봐야겠네요

2022-02-18 14:57 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func gotoModifyViewContoller() {
아앗! 애플이 하면 그게 표준이죠ㅋㅋㅋㅋ
혹시 그 부분 어디서 찾을 수 있는지 알 수 있을까요?

2022-02-18 14:58 UTC, zdodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +typealias Fruits = [Fruit: Int]
먼저 `[Fruit: Int]` 를 `typealias` 를 통해 명확하고 간략하게 표현하신 점이 좋았습니다.👍
그리고 복수의 과일을 담을 수 있는 타입이라서 `Fruits` 라는 네이밍을 저도 사용했을 것 같아요!

2022-02-18 15:04 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func gotoModifyViewContoller() {
가장 간단한 거라면 [present](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-present) 에서 찾아보실 수 있습니다!

2022-02-19 03:15 UTC, yoojin19 commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func gotoModifyViewContoller() {
아 이 부분은 모달에 관한 문서인데, 소대는 이 부분 모달이 맞다고 판단하셨나요?

2022-02-19 04:13 UTC, zdodev commented on JuiceMaker/JuiceMaker/Controller/JuiceKioskViewController.swift
> +    private func gotoModifyViewContoller() {
해당 부분은 모달에 관련한 내용인데 모달이 맞아서 판단했다기 보다는 주로 UIKit에서 화면 전환 또는 출력 부분을 `present` 라는 표현을 많이 사용했던 점을 참고했었습니다. 물론 다른 표현도 사용하기 때문에 정답은 없을 것 같습니다!

2022-02-19 04:15 UTC, zdodev approved these changes
안녕하세요. @yoojin19 , @p41155a !

스텝2 진행하시느라 고생 많으셨습니다!
여러 의견을 나눠볼 수 있어서 좋았습니다.👍

이번 스텝은 여기서 마무리하도록 하겠습니다.🤗

2022-02-19 04:24 UTC, merged