쥬스 메이커 [STEP 2] dayeonjung, momo-youngg
yagom-academy/ios-juice-maker pull request #173
Opened 2022-02-18 17:34 UTC by DayeonJung

## 구현사항

##### User Interaction과 비즈니스 로직을 고려하여 MVVM 패턴 적용.
##### 주스 주문 버튼을 눌러 뷰컨트롤러에서 클릭 이벤트를 감지했을 때, 뷰모델에 주문을 요청합니다.
#####  뷰모델 내의 JuiceMaker가 주스를 제조합니다.
##### 성공/실패 여부에 따라 얼럿 내용을 다르게 노출시킵니다.

## 고민되었던 점
 
### JuiceMaker 내의 enum Juice
현재는 주문 버튼의 왼쪽위(딸바주스)부터 오른쪽 아래(망고주스)까지 순서대로 0부터 6까지 tag를 붙여, 해당 태그에 해당하는 주스로 특정지었습니다. IBOutlet Collection으로 버튼을 만들었기 때문에, 만약 주스 주문 버튼의 위치가 바뀌거나 추가 된다면 주스 enum이 초기화 될 때 혼란을 야기시킬 수 있을 것 같습니다.
IBOutlet Collection과 tag 조합보다 더 유연할 수 있는 방법이 있을 지 궁금합니다.

2022-02-19 04:07 UTC, zdodev requested changes
안녕하세요. @DayeonJung , @momo-youngg!

스텝2 PR 축하합니다.🎉

이번 스텝도 간결하고 잘 작성해주셔서 읽기 편했습니다.👍

먼저 고민되었던 점에 말씀드리면

> 현재는 주문 버튼의 왼쪽위(딸바주스)부터 오른쪽 아래(망고주스)까지 순서대로 0부터 6까지 tag를 붙여, 해당 태그에 해당하는 주스로 특정지었습니다. IBOutlet Collection으로 버튼을 만들었기 때문에, 만약 주스 주문 버튼의 위치가 바뀌거나 추가 된다면 주스 enum이 초기화 될 때 혼란을 야기시킬 수 있을 것 같습니다.
IBOutlet Collection과 tag 조합보다 더 유연할 수 있는 방법이 있을 지 궁금합니다.

해당 문제를 근본적으로 생각해보면 버튼 타이틀, 태그, 액션을 정의하는 부분이 분리(스토리보드에서 정의하는 부분과 코드에서 정의하는 부분)되어 있어서 이런 혼란이 야기되지 않았나 싶었습니다. IBOutlet을 활용하면서 정의하는 부분을 한 지점에서 할 수 있다면 보다 유연하게 처리할 수 있지 않을까 싶습니다!😁

> JuiceMaker 내에 재고 조회, 쥬스 만들기(+유효성 체크, 재고 계산) 이렇게 4개의 메서드가 존재합니다.
재고 조회와 쥬스 만들기는 다른 책임이라 생각이 들었습니다.
JuiceManufacturer 이라는 타입을 생성하여 "제조"와 관련된 쥬스 만들기(+유효성 체크, 재고 계산) 메서드를 JuiceManufacturer에 이동하려 합니다. 그럼에 따라 JuiceMaker의 프로퍼티를 모두 갖는 initializer가 필요합니다.
이러한 역할 분리가 타당할까요?

말씀하신 `JuiceManufacturer` 의 역할을 위해 새로 만들기보다는 `FruitStore` 가 해당 책임을 더 가지고 가는건 어떨까 싶었습니다. `JuiceMaker`은 음료 제작을 위해 과일을 요청하고 재고 판단(유효성 체크 및 재고 계산)을 `FruitStore` 가 가져가는 것도 좋아보입니다. 의견이 궁금합니다.😁

전체적으로 잘 구현해주셔서 코멘트 정도만 확인하시고 스텝을 마무리해도 될 것 같습니다!

2022-02-19 04:07 UTC, zdodev commented on JuiceMaker/JuiceMaker/CustomTypes/JMObservable.swift
> +class JMObservable<T> {
범용적으로 사용할 수 있다고 생각이 들어서 `Observable` 로 이름을 지어도 괜찮겠다 라고 생각했습니다.👍
직접 바인딩 타입을 구현하신 점 좋습니다.👍

2022-02-19 04:07 UTC, zdodev commented on JuiceMaker/JuiceMaker/CustomTypes/UIAlertShowable.swift
> +extension UIAlertShowable {
Alert 생성을 담당하는 타입을 따로 작성하신 점이 좋았습니다.👍

2022-02-19 04:07 UTC, zdodev commented on JuiceMaker/JuiceMaker/Extensions/UIBarButton.swift
> +}
버튼에 액션을 보다 편하게 추가할 수 있겠네요.👍

2022-02-19 04:07 UTC, zdodev commented on JuiceMaker/JuiceMaker/MakeJuice/View/MakeJuiceViewController.swift
> +        )
바인딩하는 부분과 뷰를 설정하는 부분을 메서드로 나눠보는 것은 어떨까요?
지금은 코드가 적어서 한 눈에도 보이지만 역할을 나누면 보다 명확해질 것 같습니다.😁

2022-02-19 04:07 UTC, zdodev commented on JuiceMaker/JuiceMaker/MakeJuice/ViewModel/MakeJuiceViewModel.swift
> +struct MakeJuiceViewModel {
뷰모델 좋습니다.👍

2022-02-19 05:33 UTC, momo-youngg commented on JuiceMaker/JuiceMaker/CustomTypes/JMObservable.swift
> +class JMObservable<T> {
말씀대로 JuiceMaker 주제?에 종속되지 않아도 될것 같아서 `Observable`로 변경 했습니다!

2022-02-19 05:34 UTC, momo-youngg commented on JuiceMaker/JuiceMaker/MakeJuice/View/MakeJuiceViewController.swift
> +        )
`bindLabel()`
`targetOrderButtons()`
`targetManageStockButton()`
으로 분리 했습니다!

2022-02-19 06:14 UTC, momo-youngg commented
> > 현재는 주문 버튼의 왼쪽위(딸바주스)부터 오른쪽 아래(망고주스)까지 순서대로 0부터 6까지 tag를 붙여, 해당 태그에 해당하는 주스로 특정지었습니다. IBOutlet Collection으로 버튼을 만들었기 때문에, 만약 주스 주문 버튼의 위치가 바뀌거나 추가 된다면 주스 enum이 초기화 될 때 혼란을 야기시킬 수 있을 것 같습니다.
> > IBOutlet Collection과 tag 조합보다 더 유연할 수 있는 방법이 있을 지 궁금합니다.
> 
> 해당 문제를 근본적으로 생각해보면 버튼 타이틀, 태그, 액션을 정의하는 부분이 분리(스토리보드에서 정의하는 부분과 코드에서 정의하는 부분)되어 있어서 이런 혼란이 야기되지 않았나 싶었습니다. IBOutlet을 활용하면서 정의하는 부분을 한 지점에서 할 수 있다면 보다 유연하게 처리할 수 있지 않을까 싶습니다!😁

혹시 태깅하는 부분을 스토리보드 설정으로 변경 하면, 버튼의 위치나 enum의 추가(`Juice` enum에서 설정된 index는 수정되지 않는다 라는 전제하에)에서 좀더 자유로워 질것 같은데 어떻게 생각하시나요?!

2022-02-19 11:33 UTC, DayeonJung commented
> > > 현재는 주문 버튼의 왼쪽위(딸바주스)부터 오른쪽 아래(망고주스)까지 순서대로 0부터 6까지 tag를 붙여, 해당 태그에 해당하는 주스로 특정지었습니다. IBOutlet Collection으로 버튼을 만들었기 때문에, 만약 주스 주문 버튼의 위치가 바뀌거나 추가 된다면 주스 enum이 초기화 될 때 혼란을 야기시킬 수 있을 것 같습니다.
> > > IBOutlet Collection과 tag 조합보다 더 유연할 수 있는 방법이 있을 지 궁금합니다.
> > 
> > 
> > 해당 문제를 근본적으로 생각해보면 버튼 타이틀, 태그, 액션을 정의하는 부분이 분리(스토리보드에서 정의하는 부분과 코드에서 정의하는 부분)되어 있어서 이런 혼란이 야기되지 않았나 싶었습니다. IBOutlet을 활용하면서 정의하는 부분을 한 지점에서 할 수 있다면 보다 유연하게 처리할 수 있지 않을까 싶습니다!😁
> 
> 혹시 태깅하는 부분을 스토리보드 설정으로 변경 하면, 버튼의 위치나 enum의 추가(`Juice` enum에서 설정된 index는 수정되지 않는다 라는 전제하에)에서 좀더 자유로워 질것 같은데 어떻게 생각하시나요?!

소대가 리뷰해주신 부분처럼 타이틀과 태그(등 뷰 관련 설정), 액션 설정을 한군데에서 할 수 있다면 혼란이 적을 것 같네요. 지금의 스토리보드 활용을 유지한다고 한다면 모모가 말한 것 처럼 tag를 인터페이스 빌더에서 설정해주는 것이 어느정도 혼란은 생기지 않을 것 같아요 좋습니다!

2022-02-19 11:34 UTC, momo-youngg commented
> > > > 현재는 주문 버튼의 왼쪽위(딸바주스)부터 오른쪽 아래(망고주스)까지 순서대로 0부터 6까지 tag를 붙여, 해당 태그에 해당하는 주스로 특정지었습니다. IBOutlet Collection으로 버튼을 만들었기 때문에, 만약 주스 주문 버튼의 위치가 바뀌거나 추가 된다면 주스 enum이 초기화 될 때 혼란을 야기시킬 수 있을 것 같습니다.
> > > > IBOutlet Collection과 tag 조합보다 더 유연할 수 있는 방법이 있을 지 궁금합니다.
> > > 
> > > 
> > > 해당 문제를 근본적으로 생각해보면 버튼 타이틀, 태그, 액션을 정의하는 부분이 분리(스토리보드에서 정의하는 부분과 코드에서 정의하는 부분)되어 있어서 이런 혼란이 야기되지 않았나 싶었습니다. IBOutlet을 활용하면서 정의하는 부분을 한 지점에서 할 수 있다면 보다 유연하게 처리할 수 있지 않을까 싶습니다!😁
> > 
> > 
> > 혹시 태깅하는 부분을 스토리보드 설정으로 변경 하면, 버튼의 위치나 enum의 추가(`Juice` enum에서 설정된 index는 수정되지 않는다 라는 전제하에)에서 좀더 자유로워 질것 같은데 어떻게 생각하시나요?!
> 
> 소대가 리뷰해주신 부분처럼 타이틀과 태그(등 뷰 관련 설정), 액션 설정을 한군데에서 할 수 있다면 혼란이 적을 것 같네요. 지금의 스토리보드 활용을 유지한다고 한다면 모모가 말한 것 처럼 tag를 인터페이스 빌더에서 설정해주는 것이 어느정도 혼란은 생기지 않을 것 같아요 좋습니다!

요거 제가 지금 작업중인거에 포함시켜놓을께요~!

2022-02-19 11:56 UTC, DayeonJung commented
> > JuiceMaker 내에 재고 조회, 쥬스 만들기(+유효성 체크, 재고 계산) 이렇게 4개의 메서드가 존재합니다.
> > 재고 조회와 쥬스 만들기는 다른 책임이라 생각이 들었습니다.
> > JuiceManufacturer 이라는 타입을 생성하여 "제조"와 관련된 쥬스 만들기(+유효성 체크, 재고 계산) 메서드를 JuiceManufacturer에 이동하려 합니다. 그럼에 따라 JuiceMaker의 프로퍼티를 모두 갖는 initializer가 필요합니다.
> > 이러한 역할 분리가 타당할까요?
> 
> 말씀하신 `JuiceManufacturer` 의 역할을 위해 새로 만들기보다는 `FruitStore` 가 해당 책임을 더 가지고 가는건 어떨까 싶었습니다. `JuiceMaker`은 음료 제작을 위해 과일을 요청하고 재고 판단(유효성 체크 및 재고 계산)을 `FruitStore` 가 가져가는 것도 좋아보입니다. 의견이 궁금합니다.😁

FruitStore 의 책임으로 이동시킬 수 있을 것 같네요.! 
FruitStore 내의 메서드를 호출하는 부분이기도 해서 좋다고 생각합니다👍 

궁금한 것이 있습니다! 
인스턴스의 책임을 분리할 때는 보통 어떤 기준으로 나누시나요? 그리고 나눈다면, 어떤 방식이 나눈다고 할 수 있는 걸까요? (메서드의 분리? 타입의 분리?)
예를 들면, 위의 FruitStore의 책임으로 이동시킨다 했을 떄,
```
struct FruitStore {
  private var fruitStocks: [Fruit: Quantity]

// 1. 재고 조회
// 2. 재고 개수 늘리기 기능
// 3. 재고 개수 줄이기 기능
// 4. 제조 유효성 판단(1. 재고 조회 기능 필요)
// 5. 재고 계산(3. 재고 개수 줄이기 기능 필요)
```
으로 구성되게 됩니다. 이는 더 이상 분리할 것은 없는 타입이라고 생각하실 지 궁금합니다

2022-02-20 13:26 UTC, zdodev commented
> 궁금한 것이 있습니다!
인스턴스의 책임을 분리할 때는 보통 어떤 기준으로 나누시나요? 그리고 나눈다면, 어떤 방식이 나눈다고 할 수 있는 걸까요? (메서드의 분리? 타입의 분리?)
예를 들면, 위의 FruitStore의 책임으로 이동시킨다 했을 떄,
으로 구성되게 됩니다. 이는 더 이상 분리할 것은 없는 타입이라고 생각하실 지 궁금합니다

책임을 분리할 때 해당 타입(인스턴스)의 역할과 책임을 명확히 해보려고 합니다. 현재 프로젝트에서는 `JuiceMaker` 는 음료를 제작하는 책임을 가지고, `FruitStore` 는 재고를 관리하는 책임을 가지도록 나눠볼 수 있겠다 생각이 들었습니다.
`JuiceMaker` 는 음료 제작만을 책임지고 재고 부분은 `FruitStore`이 책임지면서 서로 메시지를 주고 받도록 하면 프로젝트에서 요구하는 기능은 어느정도 수행할 수 있지 않을까 싶습니다.

작성해주신 코드의 재고 관리 부분(책임)도 `FruitStore` 가 잘 가져갔다고 생각이 듭니다. 더 이상 분리하지 않아도 되지 않을까 싶습니다!

2022-02-20 13:26 UTC, merged

2022-02-20 13:36 UTC, DayeonJung commented
네 타입이 갖는 역할과 책임에 포커스를 맞춰 분리해보도록 해야 겠네요 의견 감사합니다~!