쥬스 메이커 [STEP 1] onetool, 두두
yagom-academy/ios-juice-maker pull request #182
Opened 2022-02-22 13:06 UTC by FirstDo

@1Consumption
안녕하세요 올라프!
onetool, 두두 입니다!
쥬스 메이커 STEP 1을 완료하여 PR 보냅니다!
많이 부족하지만 잘 부탁드려요 ㅎㅎ 😊

## 주요 함수

### struct JuiceMaker

`makeJuice()` : 쥬스를 만드는 함수 
`deleteStockFromRecipeRequired()`: 레시피에 적힌 만큼 재고에서 삭제하는 함수

### class FruitStore

`canMakeJuice()`: 레시피대로 쥬스를 만들수 있는지 재고를 확인하는 함수
`changeFruitStock()`: fruit의 재고를 amount 만큼 낮추는 함수

### ❗️고민한 점

- FruitStore에서 과일을 저장하려고 [Fruit: Int]의 딕셔너리를 사용했는데, 더 좋은 방법이 있을까요? value 값을 매번 바인딩 해서 써주려니 힘듭니다
- API Design Guidelines 에 기반하여 네이밍 을 하려고 고민했습니다.
- FruitStore의 fruits  딕셔너리를 어떤식으로 초기화 해줄지 고민했습니다. 

### ❓궁금한 점

- enum을 쓰면, case가 추가삭제 될때마다, switch문에 case를 계속 추가해줘야해서 관리가 힘들다는 말을 들었습니다.  protocol을 사용해서  더 개선시킬 수 있다는 말을 들었는데, 어떤식으로 하는지 궁금합니다.
    - 원툴은 해당 방식으로 프로젝트를 개선시켜보고 싶어하고, 두두는 굳이 쓸 필요가 있나 라는 생각입니다. 올라프의 생각이 궁금합니다

- 이니셜라이저 사용해서 초기화 하는것과, 프로퍼티의 초기값을 지정하는것의 차이가 있을까요? 

- for문안에 guard문을 사용했는데, 해당 방식이 들여쓰기 2회 위반인가요? 만약 위반이라면, 개선방법이 있을까요?

2022-02-22 17:00 UTC, 1Consumption requested changes
안녕하세요~ 두두, 원툴! 저도 잘부탁드려요 🙇🙇🙇

올려주신 코드, 커밋 잘 읽었어요.
깃모지가 너무 예쁘네요 🤩

----------------------

먼저 고민한 점, 궁금한 점에 대한 제 생각을 말씀드릴게요!

> FruitStore에서 과일을 저장하려고 [Fruit: Int]의 딕셔너리를 사용했는데, 더 좋은 방법이 있을까요? value 값을 매번 바인딩 해서 써주려니 힘듭니다

Fruit이 유니크하기 때문에 key가 되기 딱 좋은 조건을 가지고 있어서 딕셔너리를 사용하는게 좋아보입니다. 그런데 바인딩을 매번 해준다는게 힘들다는 말은 동의를 못하겠네요.

> enum을 쓰면, case가 추가삭제 될때마다, switch문에 case를 계속 추가해줘야해서 관리가 힘들다는 말을 들었습니다. protocol을 사용해서 더 개선시킬 수 있다는 말을 들었는데, 어떤식으로 하는지 궁금합니다.
원툴은 해당 방식으로 프로젝트를 개선시켜보고 싶어하고, 두두는 굳이 쓸 필요가 있나 라는 생각입니다. 올라프의 생각이 궁금합니다

음... 글쎄요 protocol을 어떻게 사용한다는건지 자세한 정보가 없어서 뭐라 답변드리기 어렵네요. 그런데 enum의 case가 추가 / 삭제 될 때마다 관리를 해줘야함이 불편하다면 protocol도 마찬가지 아닐까요? protocol에 메소드나 변수를 추가해도 해당 protocol을 채택하고있는 객체는 변경사항을 대응해야합니다.

> 이니셜라이저 사용해서 초기화 하는것과, 프로퍼티의 초기값을 지정하는것의 차이가 있을까요?

이니셜라이저는 초기화 하는 로직을 넣을 수 있는 메소드인데, 저장 프로퍼티는 값을 할당하기만 한다는 점이 차이 아닐까요?

> for문안에 guard문을 사용했는데, 해당 방식이 들여쓰기 2회 위반인가요? 만약 위반이라면, 개선방법이 있을까요?

따지자면 들여쓰기 위반이 맞는거 같네요. 사실 for문을 돌면서 throw를 할 이유가 없어보이는 로직이긴 합니다... 이부분은 코멘트로 따로 남겼어요.

--------------------------------

이제 커밋에 대해 아쉬운 점을 말해볼게요.

* [➕[ADD] : Fruit, Juice 열거형 추가](https://github.com/yagom-academy/ios-juice-maker/pull/182/commits/b872f57cdcae55ded4719f2c18d2bac0e578a02c)[](https://github.com/kimt4580)
  * 이 커밋은 한번에 두개의 역할을 하고있는 것처럼 보입니다. `Fruit`와 `Juice`는 꼭 동시에 만들어져야 했나요? 커밋은 최소한의 작업단위여야 합니다.

* [✨[FEAT] : JuiceMaker 구현](https://github.com/FirstDo/ios-juice-maker/commit/88903440774fdf3538c164181a0a695b139b64ec)[](https://github.com/FirstDo)
  * 커밋의 이름에 JuiceMaker의 어떤 부분을 구현했는지에 대한 정보가 없어서 너무 추상적인 네이밍이라고 생각됩니다.
  * 또한 아래와 같은 코드는 커밋하지 않는게 좋아보여요. 메소드 이름도 이름이고, 구현과 무관해보입니다,.
  * <img width="429" alt="image" src="https://user-images.githubusercontent.com/37682858/155180044-923d148f-131b-4c09-be6b-a40db66a276c.png">

* [✨[FEAT] : FruitStore 구현](https://github.com/FirstDo/ios-juice-maker/commit/d852ea51c027ba68aea896c17be65d20321006f6)
  * 이 커밋도 한번에 두개의 역할을 하고 있어요. 그런데 커밋의 이름은 마치 한가지 역할만 하고 있는 것 처럼 보이네요. 다시 한번 말하지만 커밋은 최소한의 작업단위여야 합니다.

* 아래 스샷만 보면 어떤 이름을 수정했는지, 어떤 메소드를 분리했는지 전혀 알수가 없네요. 이런 경우는 커밋 로그를 한번 더 타고 들어가야한다는 불편함이 있습니다.
  * <img width="366" alt="image" src="https://user-images.githubusercontent.com/37682858/155180572-33257d36-382f-4468-8519-520322b5ad99.png"> 
 
-------------------------------------------

나머지 코드에 대한 피드백은 코멘트에 남겼습니다.
고생하셨어요!

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
왜 `}`가 삭제되고 추가되었을까요? 커밋에는 공백 하나에도 의미가 있어야합니다.

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +}
열거형을 사용하셨군요~ 사용한 이유를 알 수 있을까요?

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        let initialStock = 10
상수를 활용한 모습 보기 좋습니다 👍

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
오... throws를 사용하셨네요. 이건 어떤 역할을 하나요? Bool을 반환하는 것과 차이는 뭔가요?
또한 `조동사 + 동사 원형`은 주로 Bool을 반환하는 메소드나 변수로 사용이 됩니다.

-----------------------------------

Juice라는 개념을 Fruit에서 알아야할까요? FruitStore의 역할은 Fruit에 대한 비즈니스 로직을 담당하는게 아닌가요?

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    }
👍👍👍👍 제가 말씀드리려 했던 건데 이미 하셨군요! 이러면 레시피 정보가 한곳으로 모여서 보기 좋네요.

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits = [Fruit: Int]()
외부에서 알아야하는 값인가요?

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore()
이부분도 외부에서 알아야하는 값인가요?

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
에러를 catch하는 이유는 뭔가요? 여기서 catch한다면 error에 대한 정보를 알아야하는 사용자에게까지 전달이 될까요?

추가적으로.. 성공 / 실패 여부를 반환하는 `Result`라는 타입도 있습니다.

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let recipe = fruitJuice.recipe
recipe을 넘기기보다는 Fruit를 넘겨서 사용가능한지를 체크하고, 가능하다면 사용하는게 어떨까요?

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
이 메소드는 밖에서 알아야하나요?

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="19519"/>
이 변경사항은 어떤걸 의미하나요? 커밋할 때는 자기가 어떤걸 커밋했는지를 알아야합니다.

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeFruitStock(fruit: Fruit, amount: Int) {
메소드 이름에도 fruit이 들어가있고 매개변수에도 fruit이 들어가있네요. 중복이 발생하지 않게 이름을 바꿀 수 있을까요?

2022-02-22 17:00 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func deleteStockFromRecipeRequired(recipe: [Fruit: Int]) {
여기도 메소드와 매개변수에 중복되는 이름이 있네요.

2022-02-24 12:38 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +}
이 프로젝트에서 사용되고 있는 과일이 다섯가지로 정해져있기 때문에, 열거형을 사용하여 관리하는 것이 좋다고 생각했습니다.

2022-02-24 12:55 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits = [Fruit: Int]()
private 으로 접근 제어자를 선언해 주었습니다!

2022-02-24 12:55 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore()
private 으로 접근 제어자를 선언해 주었습니다!

2022-02-24 13:19 UTC, FirstDo commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="19519"/>
앞으로 필요없는건 discard를 하겠습니다!

2022-02-24 14:34 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeFruitStock(fruit: Fruit, amount: Int) {
changeStock으로 변경했습니다!

2022-02-24 14:34 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func deleteStockFromRecipeRequired(recipe: [Fruit: Int]) {
deleteStockFrom으로 변경했습니다!

2022-02-24 14:34 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
private 으로 바꿔주었습니다!

2022-02-24 14:37 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let recipe = fruitJuice.recipe
fruitStore는 과일과 필요량만 받아서 만들수 있는지 없는지 검사하도록 변경했습니다

2022-02-24 14:37 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
에러를 viewController에서 catch하도록 변경했습니다

2022-02-24 14:46 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
> 오... throws를 사용하셨네요. 이건 어떤 역할을 하나요? Bool을 반환하는 것과 차이는 뭔가요?

- bool을 반환하게 되면 true와 false만 반환하게 되어 다양한 오류를 핸들링 할 수 없게 됩니다. 하지만 throws를 사용하게 되면 다양한 오류를 핸들링 할 수 있게 됩니다.

> Juice라는 개념을 Fruit에서 알아야할까요? FruitStore의 역할은 Fruit에 대한 비즈니스 로직을 담당하는게 아닌가요?

- 아뇨 몰라도 됩니다. 그래서 canMakeJuice 함수를 없애고, 한 가지 과일의 갯수만 체크하는 checkStock 함수로 변경해주었습니다.

2022-02-28 10:32 UTC, 1Consumption approved these changes
고생하셨습니다~ 늦어져서 죄송해요ㅠㅠ

throws를 적극 활용한 모습 보기 좋습니다. 코드도 훨신 깔끔해졌네요!

코멘트를 하나 남겼는데 이거는 다음 스텝에 반영하도록 하죠.

2022-02-28 10:32 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func deleteStockFrom(recipe: [Fruit: Int]) {
``` suggestion
func deleteStock(from recipe: [Fruit: Int]) {
```

from을 전달인자로 빼면 더 읽기 좋을거같아요!

2022-02-28 10:33 UTC, merged

2022-03-01 03:59 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func deleteStockFrom(recipe: [Fruit: Int]) {
말씀대로 변경했습니다!
deleteStock(from recipe: [Fruit: Int])