쥬스 메이커 [STEP 1] 쿼카, Donnie
yagom-academy/ios-juice-maker pull request #187
Opened 2022-02-23 09:47 UTC by Quokkaaa

안녕하세요 개굴!! @yoo-kie 굴
리뷰받게되어 영광입니다 ❤️ ❤️ 
STEP1 PR 잘부탁드릴게요 !!

# 고민되었던점
- `class`와 `struct` 사용에대해 고민했습니다.
- `FruitStore`내에 `Fruit`타입을 두는게 좋을지에 대해서 `FruitStore`안에 과일이 있다고 생각되어 중첩타입으로 묶었습니다.
- `changeFruitQuantity()`메서드에대한 재사용성을 고려했습니다. `plus`를 시키는 메서드와 `minus`를 시키는 메서드 둘다 만들기보다 `minus`를 해야하는 수에 `-` 를 붙여서 마이너스인 경우는 차감하고 플러스인경우는 더하게끔 구현을 해보았습니다.

# 해결되지않은점
- 오류처리는 공식문서를 통해 학습하고 구현할 예정입니다.

# 조언을 얻고 싶은 부분
- `subtractFruitQuantity`메서드 내 `self.fruitStore.changeFruitQuantity`코드가 중복되는데 코드 개선을 해볼수있을까요 ?
- `FruitStore`내에 있는 fruits 프로퍼티의 네이밍이 외부에서 사용할때 자연스럽게 읽혀지는것도 같은데 `fruits`라는게 사실 과일들이라는 의미로 파악이되는데 과일과 수량을 다 포함하고 있어서 이게 적절한 네이밍일지 궁금합니다.
- 타입간 역할분리에대한 기준을 나누는것이 너무 어렵네요 ㅜㅜ 혹시 `JuiceMaker`와 `FruitStore`의 메서드를 구분하는데 역할 분리를 할 수 있는 기준을 만든다면 어떻게 생각해볼 수 있을까요 ?
- `class`가 `struct`의 사용목적을 학습했으나 현재로써 `FruitStore`를 `struct`로 바꿔도 동작에는 이상이 없었는데 `class`로 지정이되어있는 이유가 궁금합니다.

2022-02-23 16:46 UTC, yoo-kie requested changes
안녕하세요! 쿼카 & Donnie! 개굴입니다.🐸

코드에서 데이터 구조화와 네이밍 관련해서 고민 많이 하신게 느껴져서 덕분에 코드를 보기 수월했던 것 같아요!
그리고 makeJuice 메서드  print문에서 웃음이 터졌어요.😂

그럼 각 사항들에 대한 제 생각을 말씀드릴게요!

# 고민되었던점
- class와 struct 사용에대해 고민했습니다.
`👍👍👍👍`

- FruitStore내에 Fruit타입을 두는게 좋을지에 대해서 FruitStore안에 과일이 있다고 생각되어 중첩타입으로 묶었습니다.
`"과일 가게에서 파는 과일”과 “주스 레시피에 사용되는 과일”은 동일한 데이터인가요?? 만약 동일하다면 FruitStore에만 종속되어 있는 데이터 타입은 아닐 것 같은데 한번 고민해주시면 좋을 것 같아요!`

- changeFruitQuantity()메서드에대한 재사용성을 고려했습니다. plus를 시키는 메서드와 minus를 시키는 메서드 둘다 만들기보다 minus를 해야하는 수에 - 를 붙여서 마이너스인 경우는 차감하고 플러스인경우는 더하게끔 구현을 해보았습니다.
`저는 재사용을 위한 코드는 주어진 역할에 대해 혼란을 야기하지 않고, 나중에 기획이 변경되었을 때 리팩토링이 복잡하지 않도록 고려하면서 작성하는 편입니다. changeFruitQuantity에서 파라미터로 음수를 전달하는 것보다 직접 재고에 -=와 +=연산을 해서 “재고에 n개 만큼 차감(가산)해주겠다”를 표현하면 더 좋을 거 같아요.`

# 해결되지않은점
- 오류처리는 공식문서를 통해 학습하고 구현할 예정입니다.
`👍👍👍👍`


# 조언을 얻고 싶은 부분
- subtractFruitQuantity메서드 내 self.fruitStore.changeFruitQuantity코드가 중복되는데 코드 개선을 해볼수있을까요 ?
`커멘트로도 남겼는데요! changeFruitQuantity 메서드의 파라미터로 사용되는 데이터들을 juice에서 가지고 올 수 없을까요? 가지고 오면서 중복된 changeFruitQuantity 메서드를 개선할 수 있는 방법도 고민해보시면 좋을 것 같습니다.`

- FruitStore내에 있는 fruits 프로퍼티의 네이밍이 외부에서 사용할때 자연스럽게 읽혀지는것도 같은데 fruits라는게 사실 과일들이라는 의미로 파악이되는데 과일과 수량을 다 포함하고있어서 이게 적절한네이밍일지 궁금합니다.
`흠… fruits도 괜찮은 네이밍이라고 생각되는데요! 좀 더 직관적으로라면… fruitsStock도 나쁘지 않을 것 같네요..ㅎㅎ`

- 타입간 역할분리에대한 기준을 나누는것이 너무 어렵네요 ㅜㅜ 혹시 JuiceMaker와 FruitStore의 메서드를 구분하는데 역할 분리를 할 수 있는 기준을 만든다면 어떻게 생각해볼 수 있을까요 ?
`우선 기능요구서를 보고 각 타입이 하는 역할을 파악하는게 가장 중요한 것 같은데요. 추가적으로 정의되어있는 프로퍼티와 메서드의 활용을 고려해볼 수 있을 것 같습니다. 예를 들어 isReadyToMakeJuice같은 경우에는 FruitStore 내 fruits의 재고를 확인해야 함으로 FruitStore에 정의된 것이 좋아보입니다.`

- class가 struct의 사용목적을 학습했으나 현재로써 FruitStore를 struct로 바꿔도 동작에는 이상이 없었는데 class로 지정이되어있는 이유가 궁금하다.
`이 부분은 STEP을 진행하시면서 조금 더 고민해보시면 좋을 것 같아요. 저는 class로 작성된 데에 fruits(과일 재고)도 중요한 포인트인 것 같습니다!`

STEP1 고생 많으셨습니다!🐸

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
기능과 상관없는 변경사항은 커밋에서 제외하면 더 깔끔할 것 같아요!

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let juiceMaker = JuiceMaker()
let 활용 좋은 것 같아요!👍

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    enum Fruit: CaseIterable {
enum 활용 정말 좋네요!

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func isReadyToMakeJuice(for juice: Juice) -> Bool {
is로 시작하는 네이밍은 주로 Bool타입의 데이터에 많이 사용하는 것 같아요! 메서드는 주로 동사로 시작해서 메서드가 수행하는 기능을 설명하면 좋을 것 같습니다!

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        var isReady = false
is 네이밍으로 Bool타입이 확인하는 내용이 뭔지 알기 편하네요!

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    case strawberryJuice
Juice 열거형으로 캡슐화가 되어 있는데 case 네이밍에도 Juice를 작성하신 이유가 있을까요?🐸

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var fruitStore = FruitStore()
fruitStore은 변경될 가능성이 있는 프로퍼티인가요??

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        if self.fruitStore.isReadyToMakeJuice(for: juice) {
디코에서 말씀드렸던대로 self는 명시가 필요할 때만 붙여주면 가독성이 더 좋을 거 같아요!

2022-02-23 16:46 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            self.fruitStore.changeFruitQuantity(by: .strawberry, count: -16)
만약 strawberryJuice를 만드는데 strawberry가 20개가 필요한 걸로 기획이 변경되면 또 어디를 수정해줘야 할까요?

2022-02-24 01:21 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func isReadyToMakeJuice(for juice: Juice) -> Bool {
`isMakeReady()`로 수정하겠습니다.

2022-02-24 01:29 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    case strawberryJuice
`Fruit` 타입의 `case`와 겹치는 부분이있어 명시적으로 적어주면 좋겠다는 생각을했었던것같아요.
그런데 `Juice`타입의 `case`값들의 `Juice`라는 단어를 뺴고 무방하고 깔끔한것같습니다. 수정할게요!

2022-02-24 01:39 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var fruitStore = FruitStore()
내부의 과일재고들이 변경되기때문에 `var`로 지정했던것같습니다. 사실 클래스는 상수여도 내부의 값이 변경이 가능하다보니 `let`으로 지정해도되지않을까 생각이드는데 어떻게생각하시나요 ?

2022-02-24 01:40 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        if self.fruitStore.isReadyToMakeJuice(for: juice) {
수정했습니다!

2022-02-24 02:00 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            self.fruitStore.changeFruitQuantity(by: .strawberry, count: -16)
`Juice`의 `recipe`도 변경되야하니 하드코딩이 발생하네요 !!
저기서 `count` 매개변수에 `juice.recipe[.strawberry] ?? 0` 이런식으로 값을 넣거나 또는 강제추출도 이용해볼 수 있을것같은데 
더 좋은방법이 있을까요 ?

2022-02-24 13:08 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            self.fruitStore.changeFruitQuantity(by: .strawberry, count: -16)
넵 지금 방식도 괜찮지만 juice를 좀 더 활용할 수 있을 것 같아요!

2022-02-24 14:04 UTC, yoo-kie approved these changes

2022-02-24 14:04 UTC, merged