쥬스 메이커 [STEP 1] 로이 , 에디
yagom-academy/ios-juice-maker pull request #189
Opened 2022-02-23 13:29 UTC by Roy-wonji

안녕 하세요  @AppleCEO 
로이 , 에디 입니다 리뷰 잘부탁 드립니다
쥬스 메이커 step1 pr 입니다

## UML

![](https://i.imgur.com/4EOUmDQ.png)

## 고민한점 & 조언 받고 싶은 점
1. `makeJuice` 함수 에서 에러 처리에서  `do catch` 문으로 처리를 했는데  이걸  `result` 라는 함수 참거짓을 판별 하는 함수라는 게 있어서 이 함수를 어떻게 적용을 시켜서 사용을 많이 할까 고민을 했습니다 
2. 역시나  네이밍은  항상  어렵고  힘드네요 .. ㅠㅠ🤣🤣
```swift=
 result를 안쓰고 한 경우 
 func makeJuice(fruitJuice: FruitsTypes) {
        let recipe = fruitJuice.recipe
        do  {
            try fruitStore.countFruit(recipe: recipe)
        } catch JuiceMakerError.outOfStock {
            print("재고가 없습니다")
        } catch {}
    }

```
</br>

result를 쓰고 한 경우인데  아직은 result에 대한 공부가 부족해서 
do catch문으로 코드를 구현해서 pr을 요청드립니다

```swift=
 func make(fruitJuice: Int) -> Result<Bool, JuiceMakerError>{
    
        guard fruitJuice > 10 else {
            return .failure(.outOfStock)
        }
        return .success(true)
```

3. 처음 UML 작성처럼 기능을 클래스 단위로 분리해서 코드를 구현해볼까 고민해봤습니다. 그래서 가장 슈퍼클래스에서 이들을 상속받아서 하려고 했으나, 찾아보았더니 다중상속을 swift는 지원을 하지 않는 것으로 알게 되었습니다. 그래서 기능을 다른 클래스에서 상속받아서 연달아 사용하는 방식(마치 함수들을 연결짓기 위해 매개변수를 활용하는 방식)을 생각했는데, 이렇게 되면 초기화 함수 같은 것을 구현했을 떄 매번 사용할 떄 불편할 뿐만 아니라 이렇게 기능단위로 클래스 구분이 맞는가 의심이 되었습니다. 작은 단위로 기능을 구현하는 것도 좋지만 한 클래스 안에 속할 수 있는 기능은 클래스 하나로 묶어서 하는 것이 저는 더 맞는 구현 방향이라고 생각하는데 이에 대한 조언을 듣고 싶습니다.

4. UML에서 저희가 상속을 사용하지 않고 예를 들어 구조체로 구현한 것을 인스턴스하여 사용하거나 enum을 하나의 딕셔너리를 초기화할 떄 사용하는 식으로 했는데 이런 경우에는 어떻게 연결관계를 해야할지 고민이 되었습니다. 단순히 연관이 있다고 해서 현재에는 선을 통해서 표현했는데, UML Class diagram 같은 경우에는 클래스의 상속 등과 같은 객체적 연관관계와 이에 따른 화살표 모양이 존재하는데 구조체같은 경우에는 이처럼 선으로만해서 이를 사용하고 있다고 봐도 될까요? 상속이 아닌 인스턴스 만드는 것이라 저는 그부분이 맞다고 생각이 들었었습니다.

2022-02-23 14:38 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@Roy-wonji , @kimkyunghun3 고생하셨습니다.
상수에 대입해서 역할을 알 수 있는 등 코드들이 읽기 좋았습니다~
개선할 점들 남겨놨습니다!

질문에 대한 답변
1. makeJuice 함수 에서 에러 처리에서 do catch 문으로 처리를 했는데 이걸 result 라는 함수 참거짓을 판별 하는 함수라는 게 있어서 이 함수를 어떻게 적용을 시켜서 사용을 많이 할까 고민을 했습니다
- 조금 더 자세하게 말씀해주실 수 있을까요? 문장을 조금 짧게 줄여봐도 좋을 것 같습니다!

2. result를 쓰고 한 경우인데 아직은 result에 대한 공부가 부족해서
do catch문으로 코드를 구현해서 pr을 요청드립니다
- 보통 result 를 안 쓰고 진행하는 것 같습니다. 에러가 표시되야하면 throw 해서 상위 함수에서 에러 처리를 한다던지 해서요. 이렇게 하면 result를 따로 사용하지 않아도 괜찮을 것 같습니다.

3. 작은 단위로 기능을 구현하는 것도 좋지만 한 클래스 안에 속할 수 있는 기능은 클래스 하나로 묶어서 하는 것이 저는 더 맞는 구현 방향이라고 생각하는데 이에 대한 조언을 듣고 싶습니다.
- 하나의 클래스에서 너무 많은 동작을 하면 읽기도 힘들고 객체지향적이지 않게 됩니다. 각자 역할을 나눠서 여러 객체가 상호작용하면서 동작이 진행되는 것이 더 좋다고 생각합니다. 물론 기능이 연관되 있으면 하나의 클래스에서 최대한 구현하는 것도 괜찮겠죠!

4. 단순히 연관이 있다고 해서 현재에는 선을 통해서 표현했는데, UML Class diagram 같은 경우에는 클래스의 상속 등과 같은 객체적 연관관계와 이에 따른 화살표 모양이 존재하는데 구조체같은 경우에는 이처럼 선으로만해서 이를 사용하고 있다고 봐도 될까요?
- 클래스와 구조체는 같은 객체라서 클래스와 거의 같게 그릴 수 있을 것 같습니다. 상속같은 부분은 구조체에서는 못하니까 못그리는게 맞겠지만요~

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -
의미없는 공백을 지운 점 좋습니다~ 👍

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +}
에러인 경우 모아놓은 열거형을 만들어보셨군요! 💯 
다른 에러 케이스는 없을까요?

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        let initialStock = 10
10을 바로 넣지 않고 상수에 넣어서 의미를 분명히한 부분 좋네요! 🥇 
상수명은 조금 더 명확하면 좋겠네요.
초기 재고라고 하면 이게 위에처럼 [FruitsTypes:Int] 와 같은 열거형으로 오해할 수 있을 것 같아요~

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
CaseIterable 을 사용해보셨군요!
고급집니다. 🥇

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
과일 숫자로 읽히는데요. 과일 숫자를 리턴하는 메소드로 오해할 수 있을 것 같아요.
더 적합한 이름으로 개선해볼까요?

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitsCount.swift
> +        }
위에 FruitStore 를 초기화할 때 있는 코드와 같군요.
중복을 제거해 볼 수 있을까요?

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitsType.swift
> +enum FruitsTypes: CaseIterable {
과일의 모음인지 쥬스의 모음인지 이름으로는 헷갈리네요!
아래 내용들은 쥬스에 대한 내용인 것 같은데 이름은 과일 타입이네요~

2022-02-23 14:38 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let recipe = fruitJuice.recipe
바로 사용하지 않고 상수에 대입하는 부분 좋네요~ 💯

2022-02-24 01:08 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +}
먼저 요구사항을 보았을 때 재고없을 때 에러에 대한 케이스가 존재한다고 생각해서 저희가 열거한 것이고, 먼저 예시에는 인풋과 아웃풋에 대한 설명이 없어서 유저 입력값에 대한 에러를 처리하기에는  섣부른 판단 같다고 생각했습니다. 음.. 저희 생각에는 다른 에러 케이스가 보이지 않는데 혹시 도미닉이 보았을 때 다른 에러 케이스가 존재할까요? 만약 있다면 힌트라도 주시면 고민해보겠습니다 :)

2022-02-24 01:12 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        let initialStock = 10
고민해본 결과 초기 재고라고하면 오해를 불러일으킬 수 있는 상수명이라고 생각해서 이를 '재고 수'인 stockCount라고 생각해봤습니다. 초기화한 재고처럼 보이지 않고 기능에 맞게 재고의 수에 대해 상수를 지정하고 있기에 이렇게하면 오해가 사라지고 어떤 것을 의미할지 알 수 있을것이라고 판단했습니다.😄

2022-02-24 01:22 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
먼저 과일을 count하라는 메소드명 자체가 실제로 안에서 실행되는 코드와 매치가 되지 않는 것을 알게 되었습니다. 내부에서는 재고에서 주스에 사용할 과일의 수 만큼 빼주고 있기 때문에 저희는 이를 '과일을 소비한다'라고 판단하게 되었습니다. 그래서 네이밍을 고민한 끝에 consumeFruit라고 하면 기능에 따라 명확한 네이밍이지 않을까 생각하게되었습니다!

2022-02-24 01:23 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Model/FruitsCount.swift
> +        }
앗 저희가 처음에 생각했던 레거시 코드인데 이는 마지막 PR 전에 파일을 없애고 초기화할 때 쓰는 함수를 하나로 바꿨습니다 :)

2022-02-24 01:28 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Model/FruitsType.swift
> +enum FruitsTypes: CaseIterable {
저희가 내부에서는 주스에 대한것인데 열거형 네이밍을 이상하게 적은거같습니다 ㅎㅎ.. 그리고 더 고민했던게 처음에는 case에 대해서도 과일이름으로 한 것에 대해서 주스로 바꿔야되나 고민했으나, 이 열거형 case를 사용하는 곳이 예를 들어 재고를 각각 10으로 초기화하는 곳도 있어서 이를 과일명만 하는 것이 맞다고 생각했으며 주스에 따라 구분하는 스위치에서 이를 구분해주는게 맞다고 판단했습니다!!!

2022-02-24 03:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +}
ㅎㅎ 아직 발견하지 못했으면 굳이 만들 필요는 없죠!

2022-02-24 03:55 UTC, merged