쥬스 메이커 [STEP 1] Doogie, Malrang
yagom-academy/ios-juice-maker pull request #190
Opened 2022-02-24 03:46 UTC by doogie97

@yoo-kie
안녕하세요 개굴! 첫 번째 STEP1 PR 드립니다!

# 📝 고민된 점 & 조언 받고 싶은 점
1. 에러가 날 수 없는 경우
```swift
func calculateStock(fruit: Fruits, amount: Int, calculationType: CalculationType) throws {
guard let stock = fruitList[fruit] else {
throw FruitStoreError.invalidSelection
}
```
위 코드에서 매개변수 *`fruit`* 는 잘못 선택될 일이 없고 단순히 *`fruitList[fruit]`* 의 값이 nil일 경우는 없을 것이라고 생각하는데 옵셔널 바인딩을 위해 guard let을 사용하게 될 경우 else 내부에 어떤 내용을 적어줘야 하는지 궁금합니다.
(일단은 에러 중 하나인 *`invalidSelection`* 으로 던지긴 했지만 return을 사용한다거나 혹은 다른 방법이 있는지...)

2. Error 프로토코콜을 채택한 열거형의 네이밍을 무엇으로 할지 고민입니다.

3. *`JuiceMaker는 FruitStore를 소유하고 있습니다`* 라는 말의 뜻을 어떻게 해석해야할지 고민 했으며
일단은, *`JuiceMaker`* 안에서 *`FruitStore`* 의 인스턴스를 생성하는 것으로 해석 했는데 
이런 경우 *`(A 클래스 안에 B 클래스의 인스턴스를 생성한 경우)`* A 클래스를 B클래스의 부모로 볼 수 있는지 궁금합니다.

4. UML 작성 방법
![스크린샷 2022-02-24 오후 12 14 55](https://user-images.githubusercontent.com/82325822/155453844-d11dddeb-7aaf-4ebf-b4bf-01275b78c219.png)

원래는 flowchart를 그리고 싶었으나 해당 스텝에서는 어떤 기능등이 순서에 따라 이뤄지는 과정이 아니라고 생각했으며 대신 UML로 작성을 해봤는데 올바르게 UML이 작성됐는지 조언 부탁드립니다!

2022-02-24 12:43 UTC, yoo-kie requested changes
안녕하세요 Doogie, Malrang! 개굴입니다.

네이밍이 정말 명료해서 코드를 이해하기 편했어요!☺️ 그리고 재사용성과 에러핸들링에 대해서도 고민하신게 느껴졌습니다! 정말 가~~끔 오타가 눈에 띄기는 했지만 관련해서 커멘트는 따로 남기지 않았어요! (하지만 한번 체크해보셔도 좋을 것 같아요.ㅎㅎ)

그럼 남기신 고민된 점과 조언 받고 싶은 점에 대한 제 생각을 말씀드리도록 하겠습니다!

# 📝 고민된 점 & 조언 받고 싶은 점
1. 에러가 날 수 없는 경우
```swift
func calculateStock(fruit: Fruits, amount: Int, calculationType: CalculationType) throws {
guard let stock = fruitList[fruit] else {
throw FruitStoreError.invalidSelection
}
```
위 코드에서 매개변수 *`fruit`* 는 잘못 선택될 일이 없고 단순히 *`fruitList[fruit]`* 의 값이 nil일 경우는 없을 것이라고 생각하는데 옵셔널 바인딩을 위해 guard let을 사용하게 될 경우 else 내부에 어떤 내용을 적어줘야 하는지 궁금합니다.
(일단은 에러 중 하나인 *`invalidSelection`* 으로 던지긴 했지만 return을 사용한다거나 혹은 다른 방법이 있는지...)

`🐸 딕셔너리는 Key에 해당하는 value가 없다면 nil을 반환하지만, 현재는 fruitList가 Fruits의 allCases를 가지고 있어서 nil일 경우가 없을 것 같네요. 하지만 나중에 fruitList 값이 변경될 가능성이 있을 수 있어서 옵셔널에 대한 예외처리가 필요하다고 생각합니다. else에는 지금처럼 invalidSelection이나 fruitList에 key로 전달된 과일이 없다는 메시지를 표시해주면 좋을 것 같아요!`

2. Error 프로토코콜을 채택한 열거형의 네이밍을 무엇으로 할지 고민입니다.

`🐸 보통 역할+Error 형태로 많이 사용합니다. Ex. NetworkError, APIError`

4. *`JuiceMaker는 FruitStore를 소유하고 있습니다`* 라는 말의 뜻을 어떻게 해석해야할지 고민 했으며
일단은, *`JuiceMaker`* 안에서 *`FruitStore`* 의 인스턴스를 생성하는 것으로 해석 했는데 
이런 경우 *`(A 클래스 안에 B 클래스의 인스턴스를 생성한 경우)`* A 클래스를 B클래스의 부모로 볼 수 있는지 궁금합니다.
```
🐸
내부 프로퍼티로 인스턴스를 생성한 것은 상속의 개념과 다릅니다. 부모-자식이라는 개념은 “상속”에 적용되는 것으로 아래와 같은 형태인데요.

class Parent {
    // 부모 클래스
}
class Child: Parent {
    // 자식 클래스
} 

이건 아직은 배우시지 않은 진도라 나중에 생각해보셔도 좋을 것 같습니다.ㅎㅎ
```

5. UML 작성 방법
![스크린샷 2022-02-24 오후 12 14 55](https://user-images.githubusercontent.com/82325822/155453844-d11dddeb-7aaf-4ebf-b4bf-01275b78c219.png)

원래는 flowchart를 그리고 싶었으나 해당 스텝에서는 어떤 기능등이 순서에 따라 이뤄지는 과정이 아니라고 생각했으며 대신 UML로 작성을 해봤는데 올바르게 UML이 작성됐는지 조언 부탁드립니다!

`🐸 아..! 저는 UML 활용을 본격적으로 해본적은 없는데요..! 점선 화살표가 상속관계를 표현하는 것이 아니라면 타입 정리는 명료한 것 같습니다!`

STEP1 고생 많으셨습니다!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
기능과 상관없는 커밋은 제외하는게 깔끔할 것 같아요!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/ErrorCase.swift
> +enum FruitStoreError: Error {
Error 프로토콜 활용이 좋습니다! 네이밍도 좋아요👍

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//  Created by Doogie & Malrang.
오 세심한 수정사항이네요😂

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
class만 한 줄 띄어서 작성하신 이유가 있을까요? 특별한 이유가 없다면 enum과 struct처럼 공백 제거해주면 좋을 것 같아요!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitList = [Fruits: Int]()
fruitList는 외부에서 접근하거나 변경될 가능성이 있는 프로퍼티인가요? 아니라면 접근제어 private과 상수 let을 활용해서 코드의 무결성(데이터가 일관성을 유지할 것을 보장)을 지켜줄 수 있을 것 같아요!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        let defaultStock = 10
let 활용 좋습니다!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    case strawBerryJuice
Juice 열거형으로 캡슐화가 되어 있는데 case에 다시 Juice를 붙여주신 이유가 있을까요?
직관적이라 좋지만 `makeJuice(juice: . strawBerryJuice)` 이렇게 사용됐을 때 Juice라는 단어가 3번 중복 작성 될 수 있을 것 같아요. 좀 더 깔끔한 네이밍을 고민해보시면 좋을 것 같습니다.

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +        }
get을 작성해주셨네요:) set을 생략하고 get만 사용한다면 get을 제거해서 더 깔끔한 코드를 작성할 수 있을 것 같아요!
```suggestion
        switch self {
        case .strawBerryJuice:
            return [.strawberry : 16]
        case .bananaJuice:
            return [.banana : 2]
        case .kiwiJuice:
            return [.kiwi : 3]
        case .pineappleJuice:
            return [.pineapple : 2]
        case .ddalBaJuice:
            return [.strawberry : 10, .banana : 1]
        case .mangoJuice:
            return [.mango : 3]
        case .mangKiJuice:
            return [.mango : 2, .kiwi : 1]
        }
```

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  // 쥬스 메이커 타입
중요하지 않은 주석은 제거하면 좋을 것 같아요:)

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) {
위에서 언급했던 것처럼 이렇게 되면 Juice를 3번 작성해줘야 하네요!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/ErrorCase.swift
> +//  ErrorCase.swift
파일명은 구체적이면 좋을 것 같아요! 해당 파일에서는 FruitStoreError가 구현되어 있으니 FruitStoreError를 추천드립니다!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
Main 스토리보드를 커밋에 포함하신 이유가 있을까요? 🐸 기능과 상관없는 커밋은 제외하는 것이 좋습니다!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        } catch {}
에러 핸들링 좋습니다!☺️ 혹시 catch에서 error를 바인딩 및 타입 캐스팅하는 방법에 대해 아실까요?🐸

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func calculateStock(fruit: Fruits, amount: Int, calculationType: CalculationType) throws {
CalculationType을 활용해서 깔끔하게 calculateStock메서드를 재사용 하셨군요!👍

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            fruitList[ingredent] = stock - amount
아래의 calculateStock을 활용할 수는 없을까요?

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/ErrorCase.swift
> +    case outOfRange
`outOfStock`과 `outOfRange`의 차이는 무엇인가요?🐸?

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            fruitList[ingredent] = stock - amount
딸바와 망키같이 재료가 2개 이상일 경우, 첫번째 재료는 재고가 있어서 fruitList에서 차감되었다가 두번째 재료가 재고소진으로 주스를 만들 수 없을 때(outOfStock 에러 발생) 주스를 만들지 못했는데도 재료가 차감되는 문제가 발생할 수 있을 것 같아요!

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard amount <= stock else {
if문 대신 guard문을 활용하신 이유가 있나요?🐸?

2022-02-24 12:43 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        } catch {}
앞선 catch문에서 잡히지 않는 에러를 잡는 마지막 catch문에도 "알 수 없는 이유로 주스를 만들 수 없습니다!"와 같은... 메시지를 추가해줘도 좋을 것 같아요!

2022-02-25 01:13 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
이 부분은 저희가 캐치하지 못했습니다 ㅠㅠ 수정하도록 하겠습니다!

2022-02-25 01:15 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitList = [Fruits: Int]()
일단 현재는 과일리스트가 생성되면 과일이 추가될 일은 없기에 let으로 선언되는게 맞는 것 같습니다.
다만 private사용에 관련해서는 아직 사용이 미흡한 부분이 사실입니다. 이 부분은 한 번 더 고민 및 적용을 시도해 보도록 하겠습니다.

2022-02-25 01:22 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +        }
이 부분은 말랑이 생략 가능하다고 말해주긴 했는데 제가 연산프로퍼티 사용이 처음이어서 헷갈려서 적어두자고 제안 했습니다!
프로젝트 최종본 제출시에는 생략해주도록 하겠습니다!

2022-02-25 01:25 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  // 쥬스 메이커 타입
중요하지 않은 주석을 지우면서 Foundation 또한 사용되지 않고 있어 제거 해 주었습니다!

2022-02-25 01:29 UTC, doogie97 commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
아! 생각하지 못했던 부분입니다. add 할 때 변경사항이 조금이라도 있으면 전부 추가를 했었는데 이 부분 생각하면서 커밋 진행하도록 하겠습니다!

2022-02-25 01:40 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/ErrorCase.swift
> +    case outOfRange
outOfStock 은 쥬스 제작시 재고가 모자른 경우고 outOfRange는 차감시 현재 재고보다 차감하려는 개수가 더 많은 경우로 분리하여 생각을 했었습니다.
그런데 개굴의 리뷰를 보고 말랑과 상의한 결과 재고가 부족한 건 제작할 때나 차감할 때나 동일하다고 생각해 outOfStock으로 통일하였습니다.

2022-02-25 01:55 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard amount <= stock else {
저희는 if 구문이 더 직관적이라고 생각해서 if를 선호하긴 합니다만 들여쓰기를 최소화 하기 위해서 guard 구문을 사용 했습니다.

2022-02-25 01:56 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        } catch {}
마지막 catch를 어떻게 할 지 고민 했었는데 알 수 없는 오류라고 메세지를 주면 좋을 것 같습니다!

2022-02-25 05:43 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitList = [Fruits: Int]()
pr 받고 수정 전 코드에서는 private을 사용해주는게 맞다고 생각해 추가했으나 밑에 리뷰를 보고 코드를 수정하는 과정에서 JuiceMaker또한 fruitList에 접근하는 경우가 생겼습니다.
그렇기에 변경된 코드에서는 적절하지 않다고 생각해 다시 제거해주었습니다.

2022-02-25 05:44 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    case strawBerryJuice
case 이름을 strawBerryJuice에서 그냥 strawBerry로 바꾸면 fruitList에 있는 strawBerry와 혼동될 것 같아서 enum 이름을 Menu로 바꾸고 그에 따라서 매개변수 이름도 수정 하였습니다.

2022-02-25 05:45 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) {
위에서 말씀드렸듯이 열거형의 이름을 변경하였습니다!

2022-02-25 05:45 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/ErrorCase.swift
> +//  ErrorCase.swift
해당 의견 반영하여 FruitStoreError로 변경하였습니다!

2022-02-25 05:46 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        } catch {}
이 부분은 저는 처음 들어보는 얘기고 말랑은 사용하는 걸 본 적은 있다고 하는데 둘 다 사용방법에 대해서는 모르는 상태 입니다.
혹시 공부를 위한 키워드 같은 것을 알려주시면 감사하겠습니다!

2022-02-25 05:47 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            fruitList[ingredent] = stock - amount
이 부분은 아래 의도치 않게 차감되는 부분에 대해 리뷰 남겨주신 곳에 같이 답변 달도록 하겠습니다!

2022-02-25 05:50 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            fruitList[ingredent] = stock - amount
일단은 의도치 않은 차감 문제를 해결하기 위해 단순히 재고만 체크하는 checkStock 함수를 JuiceMaker에, 재고가 있다면 주스 제작을 위해 재고를 차감하는 minusStock 함수를 FruitStore에 분리해 구현하였습니다.
(재고 확인은 JuiceMaker가 하고  재료를 차감한다면 차감되는 건 FruitStore라고 생각해 이렇게 함수 배치를 하였습니다.)

분리를  하고 보니 minusStock 함수와 calculateStock의 빼는 부분이 유사하다고 생각해 병합해보려고 고민을 해봤습니다.
그런데 minusStock 함수는 만드려고 하는 쥬스 레시피가 리턴하는 딕셔너리의 키를 가지고 현재 과일의 재고를 체크하는 반면
calculateStock 함수에서는 과일을 직접 대입해서 체크를 하기 때문에 병합하는 것에 어려움을 겪었습니다.
minusStock의 키와 값을 변수로 저장해 이용해보려고도 했으나 레시피에 따라서 for구문을 두번도는 경우도 있기에 병합이 어려울 것 같다는 결론이 나왔는데 혹시 어떻게 생각하실까요?

2022-02-25 05:52 UTC, doogie97 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
해당 부분은 dm으로 추가 질문 드렸습니다!

2022-03-01 10:35 UTC, yoo-kie approved these changes

2022-03-01 10:35 UTC, merged