쥬스 메이커 [STEP 1] minseong, papri
yagom-academy/ios-juice-maker pull request #191
Opened 2022-02-24 04:14 UTC by Minseong-yagom

안녕하세요 또치 😄
minseong, papri 입니다
리뷰를 받게 되어 영광입니다
STEP 1 PR 잘부탁드립니다 🙏🏼
# UML
<img src ="https://user-images.githubusercontent.com/94295586/155451528-fa9ba753-61da-4ce2-9307-f750c8073a50.png" width = 700 height = 500>

# 구현함수
- `makeJuice()`: 음료를 입력받아 음료제작이 가능한지 확인 후 가능하면 제작
- `isEnoughStock()`: 음료에 필요한 재료가 있는지 확인
- `decreaseFruitStock()`: 음료제작에 필요한 재료만큼  과일저장소의 정보최신화
# 고민한 점
- `Enum Fruit`를 `FruitStore`에 종속되게 해줄지 아니면 파일을 따로 빼줄지 고민했습니다. `FruitStore`가 과일종류와 재고의 관한 목록만 있으면 된다고 판단하여 파일을 분리했습니다.
- `Class FruitStore`에서 과일과 과일재고의 구현. 
  - a. `enum Fruit`을 만들어 해당 과일과 재고를 `Dictionary`의 `key`와 `index`로 두어 관리할지
  - b. `Fruit`이란 구조체를 만들어 그 안에 과일이름과 과일재고를 넣고 `struct Fruit`객체들의 배열로 관리할지 
> b를 선택하면 과일 객체를 하나하나 다 만들어줘서 배열에 넣어야 하고, 과일 값을 줄일 때 배열.과일구조체인스턴스.재고 << 이렇게 접근해야해서, a 방식을 선택하였습니다. 
> 추후에 `FruitStore`에서 취급하는 과일의 종류가 다양해지더라도 `Fruit enum`에 `case`를 추가하면 되기 때문에 a방식으로 결정했습니다.
- 매직넘버
  - `Class FruitSore`에서 초기화를 진행할 때, 초기 재고인 10이 매직넘버이기 때문에 `DefaultSetting`이란 `enum`을 만들어 해결하였습니다.
- 접근지정자
  - `Class FruitStore`의 재고관리는 `decreaseFruitQuantity()`메소드를 통해 `private`한 과일인벤토리에 접근하는 식으로 이뤄져야겠다고 생각했습니다. 
  - 과일을 만드는 것 외에 다른 이유로 과일인벤토리를 건들지 못하게 만들어야 한다고 생각했습니다.
- 에러처리 - `throw`를 하는 부분과 `catch`를 할 부분
  - 재고를 검사하는 동시에 `Error`를 던져줄지 검사가 끝나고 `Bool`값으로 반환받아 그 결과값에 따라서 `Error`를 던져줄지 고민하였습니다.
> 재고를 확인하는 부분은 `FruitStore`에서 진행해야 한다고 생각하여 `Error`를 `isEnoughStock()`서 던져주었습니다.
- 네이밍
  - `JuiceMakeError`, `JuiceMakerError`라는 네이밍을 고민하였습니다
> 쥬스를 만드는 과정에서 에러가 생기는 것이기 때문에 JuiceMakeError라는 이름을 선택하였습니다.
# 조언을 얻고 싶은 부분
```swift
func decreaseFruitStock(by juiceIngredient: [Fruit : Int]) {
    for (fruit, requiredAmount) in juiceIngredient {
        if var fruitStoreStock = fruitsInventory[fruit] {
            fruitStoreStock -= requiredAmount
            fruitsInventory[fruit] = fruitStoreStock
        }
    }
}
```
- 위 코드의 네이밍을 고민을 많이 했는데 가독성이 좋은지 조언 부탁드립니다! 
- 이번 프로젝트를 수행함에 있어 읽고 참고해야 하는 문서를 이틀간 읽고 프로젝트를 실행하였습니다, 막상 시작하려니 알고 있는 지식들을 어떻게 활용해야 할지 어떤 방향으로 갈지 계속 방황했습니다. 어떤식으로 공부를 해야 할까요?? 조언을 얻고 싶습니다.

2022-02-24 14:52 UTC, TTOzzi requested changes
안녕하세요! @papriOS, @Minseong-yagom  
저도 리뷰를 맡게 되어 영광입니다 ㅎ0ㅎ
많이 부족하지만 열심히 할 테니 잘 부탁드려요! 🙇🙇🙇 

### 고민한 점

> - `Enum Fruit`를 `FruitStore`에 종속되게 해줄지 아니면 파일을 따로 빼줄지 고민했습니다. `FruitStore`가 과일종류와 재고의 관한 목록만 있으면 된다고 판단하여 파일을 분리했습니다.

해당 타입이 정말 그 파일 내에서만 쓰이는 게 아니라면, 분리해주는 게 좋다고 생각합니다. 
현재는 `Juice` 타입에서도 `Fruit` 타입을 사용하고 있네요!

> - `Class FruitStore` 에서 과일과 과일재고의 구현.
>   - a. `enum Fruit`을 만들어 해당 과일과 재고를 `Dictionary`의 `key`와 `index`로 두어 관리할지
>   - b. `Fruit`이란 구조체를 만들어 그 안에 과일이름과 과일재고를 넣고 `struct Fruit`객체들의 배열로 관리할지
> - b를 선택하면 과일 객체를 하나하나 다 만들어줘서 배열에 넣어야 하고, 과일 값을 줄일 때 배열.과일구조체인스턴스.재고 << 이렇게 접근해야해서, a 방식을 선택하였습니다.
>   추후에 `FruitStore`에서 취급하는 과일의 종류가 다양해지더라도 `Fruit enum`에 `case`를 추가하면 되기 때문에 a방식으로 결정했습니다.

코드를 작성하신 이유가 명확해서 좋네요! 저도 같은 생각을 했을 것 같습니다 :thumbsup:

> - 매직넘버
>   - `Class FruitSore`에서 초기화를 진행할 때, 초기 재고인 10이 매직넘버이기 때문에 `DefaultSetting`이란 `enum`을 만들어 해결하였습니다.

그냥 숫자로 표현되는 값을 상수로 선언해서 의미를 부여해주신 점 너무 좋습니다!

> - 접근지정자
>   - `Class FruitStore`의 재고관리는 `decreaseFruitQuantity()`메소드를 통해 `private`한 과일인벤토리에 접근하는 식으로 이뤄져야겠다고 생각했습니다.
>   - 과일을 만드는 것 외에 다른 이유로 과일인벤토리를 건들지 못하게 만들어야 한다고 생각했습니다.

의도도, 작성하신 코드도 훌륭합니다 :thumbsup:

> - 에러처리 - `throw` 를 하는 부분과 `catch` 를 할 부분
>   - 재고를 검사하는 동시에 `Error`를 던져줄지 검사가 끝나고 `Bool`값으로 반환받아 그 결과값에 따라서 `Error`를 던져줄지 고민하였습니다.
>
> > 재고를 확인하는 부분은 `FruitStore`에서 진행해야 한다고 생각하여 `Error`를 `isEnoughStock()`서 던져주었습니다.

요건 코멘트로 남겨드렸어요!

> - 네이밍
>   - `JuiceMakeError`, `JuiceMakerError`라는 네이밍을 고민하였습니다
>
> > 쥬스를 만드는 과정에서 에러가 생기는 것이기 때문에 JuiceMakeError라는 이름을 선택하였습니다.

요건 관점의 차이일 것 같네요 :thinking:
`JuiceMaker` 가 발생시킨 에러인가, `Juice` 를 만드는 과정에 발생한 에러인가..? 
`쥬스를 만드는 과정에서 에러가 생기는 것` 의 관점에서 네이밍 해주셨는데, 개인적으론 `JuiceMakeError` 보단 `JuiceMakingError` 가 더 나을 것 같아요. 
(`JuiceMakeError` 는 단어 그대로 직역했을 때, 조금 어색한 것 같습니다 +_+)

### 조언을 얻고 싶은 부분

> ```
> func decreaseFruitStock(by juiceIngredient: [Fruit : Int]) {
>     for (fruit, requiredAmount) in juiceIngredient {
>         if var fruitStoreStock = fruitsInventory[fruit] {
>             fruitStoreStock -= requiredAmount
>             fruitsInventory[fruit] = fruitStoreStock
>         }
>     }
> }
> ```
>
> - 위 코드의 네이밍을 고민을 많이 했는데 가독성이 좋은지 조언 부탁드립니다!

요건 코멘트로 남겼습니다!

> - 이번 프로젝트를 수행함에 있어 읽고 참고해야 하는 문서를 이틀간 읽고 프로젝트를 실행하였습니다, 막상 시작하려니 알고 있는 지식들을 어떻게 활용해야 할지 어떤 방향으로 갈지 계속 방황했습니다. 어떤식으로 공부를 해야 할까요?? 조언을 얻고 싶습니다.

우와 굉장히 어려운 질문.......! 이거 어떻게 답변드릴지 고민하다가 리뷰가 늦어질 것 같으니.. 일단 리뷰 먼저 달겠습니다 😁

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +}
오- 상수를 네임스페이스까지 적용해서 선언해주셨군요.
요기서 개인적인 의견을 사알짝 더하자면, `DefaultSetting`을 다른 곳에서 사용하지 않는 것으로 보여 사용하는 곳(`FruitStore`)에서만 접근하도록 위치를 옮겨주는 게 좋을 것 같아요 🤔

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
다른 클래스가 상속받지 않는 클래스라면 `final` 키워드를 명시해주어 상속받을 수 없는 클래스임을 표현해주는 게 좋습니다.
추가로 아주 약간의 성능 향상도 챙길 수 있구요. 시간 여유 있으실때 https://developer.apple.com/swift/blog/?id=27 요 문서 한 번 읽어보시면 좋을 것 같아요 🙂 
지금부터 `final`, `private`은 습관적으로 붙이는 게 좋아요! (아래에 `private`을 사용하셔서 셋트로 코멘트 남겨봅니다 +_+)

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitsInventory : [Fruit : Int] = [:]
`FruitStore`의 `fruitsInventory` 이니 비슷한 성격의 다른 `inventory`가 `FruitStore`내에 존재하는 게 아니라면, 그냥 `inventory`로 표현해줘도 될 것 같아요!
(`private` 은 너무 좋아요 👍 )

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitsInventory : [Fruit : Int] = [:]
```suggestion
    private var fruitsInventory: [Fruit: Int] = [:]
```
`:` 앞에는 공백을 없애고, 뒤에만 띄워주는 게 일반적인 컨벤션입니다 🙂

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`isEnoghStock`은 이름만 봤을 땐, 재고가 충분한지 여부를 Bool 값으로 반환해줄 것 같은데 에러를 던지고 있네요 🤔 
제가 생각했을 때의 에러 처리를 사용하는 기준은 **의도한 로직이 정상적으로 동작하지 않았을 때** 에러를 던져야 한다고 생각해요.
지금 이 메서드에서 의도한 로직은 `재고가 충분한지 여부를 확인하는 것` 이라 지금처럼 정상 동작을 했음에도 그 결과를 에러로 처리하기보단, 결과를 Bool 값으로 반환하는 게 좋을 것 같습니다.

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
만약 재고의 수량이 부족한 상태에서, 이 메서드를 호출하게 되면 어떻게 되나요? 👀 
아마 아래의 `JuiceMaker` 에서 이 메서드를 호출하기 전 `isEnoughStock`을 호출하기에 방어로직이 없는 것 같은데, 이 메서드를 호출하기 전 반드시 `isEnoughStock`을 호출해서 재고 수량 체크를 해야한다는 것을 모르는 사람이 이 코드를 사용하게 되면 언제든지 단독으로 호출 될 가능성이 있어보여요 🤔 
`outOfStock`에 대한 처리를 해야한다면, 여기서 해야할 것 같습니다.

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    }
```suggestion
    var recipe: [Fruit: Int] {
        switch self {
        case .strawberryJuice:
            return [.strawberry: 16]
        case .bananaJuice:
            return [.banana: 2]
        case .kiwiJuice:
            return [.kiwi: 3]
        case .pineappleJuice:
            return [.pineapple: 2]
        case .strawberryBananaJuice:
            return [.strawberry: 10, .banana: 1]
        case .mangoJuice:
            return [.mango: 3]
        case .mangoKiwiJuice:
            return [.mango: 2, .kiwi: 1]
        }
    }
```
요기도 컨벤션 맞춰주면 좋을 것 같아요!

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
여기서 에러에 대한 메세지를 구분하기 보다 에러가 자신에 대한 메세지를 가지는 건 어떨까요? 👀 
[localizedDescription](https://developer.apple.com/documentation/foundation/nserror/1414418-localizeddescription) 에 대해 찾아보시고 적용해보시면 좋을 것 같아요!

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            fruitStore.decreaseFruitStock(by: juiceRecipe)
지금 로직으론, 만들 수 있는 `recipe` 가 들어오면 재고가 충분한지 여부를 확인하기 위해 반복문을 한 번 돌고, 사용한 과일의 재고만큼 수량을 조절해주기 위해 다시 한 번 반복문을 돌 것 같아요.
극단적인 예시이긴 하나 `FruitStore`가 관리하는 과일의 종류가 엄청나게 많아지고 무수히 많은 종류의 과일을 사용하는 `recipe`로 주스를 만드는 상황이 온다면, 성능 차이가 더 두드러질 것 같습니다 🤔

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func decreaseFruitStock(by juiceIngredient: [Fruit : Int]) {
인자의 이름이 `juiceIngredient`인데, 인자로 넘어오는 `[Fruit: Int]`가 꼭 주스의 재료일 필요가 있을까요? 👀 
FruitStore는 주스를 만드는 데에도 사용 가능하고, 아이스크림을 만드는 데에도 사용할 수 있을 거예요.
인자 이름을 좀 더 일반적인 이름으로 변경하면 좋을 것 같아요 🙂 
(위의 `isEnoughStock`도 포함되는 코멘트입니다!)

2022-02-24 14:52 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            }
`fruitStoreStock` 이란 단어가 모호하고, 여기에 뭔가 변경을 해주고 그걸 다시 `inventory`에 집어넣고 있어 개인적으론 코드 이해가 어려운 것 같아요 🤔 
```suggestion
            if let currentAmount = fruitsInventory[fruit] {
                fruitsInventory[fruit] = currentAmount - requiredAmount
            }
```
현재 재고라는 것을 명확하게 명시하고, 주스를 만드는 데 필요한 양을 `requiredAmount`로 선언해주셨으니 같은 맥락으로 `amount`로 표현해주고 코드도 좀 더 간결하게 선언하는 게 좋을 것 같아요.

여기서 의미를 한 번 더 부여해주자면,
```suggestion
            if let currentAmount = fruitsInventory[fruit] {
                let remainingAmount = currentAmount - requiredAmount
                fruitsInventory[fruit] = remainingAmount
            }
```
요렇게도 가능할 것 같구요 🙂 
가독성에 대한 건 개인적인 의견이니 참고만 해주세요 🙏

2022-02-25 02:38 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
첨부해주신 공식문서와 인터넷 자료들을 읽어본 결과, 
`Indirect call (Dynamic Dispatch)`는 어떤 `property`를 부르는 지가 명확,직접적이지 않아(예를 들어 클래스의 상속으로 override한 method가 생기는 경우, )
확인과정을 거치는 과정이고, 이것이 런타임에 일어나 성능상 손해가 생기는 것으로 이해했습니다. 
때문에 `final` , `private` 키워드를 사용하거나 `WMO`(모듈 전체 파일을 동시에 같이 컴파일 해 내부적으로 final를 붙이는 것) 를 통해 Direct call이 되게끔하여 성능효과를 챙기는 것으로 이해했습니다!
그래서 `FruitStore` 클래스에` final `키워드를 붙여보았습니다. 읽어볼 문서 알려주셔서 감사합니다~!

2022-02-25 03:15 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`decreaseFruitStock()`에서 `outOfStock`을 처리하다 보니 `isEnoughStock`의 기능을 합치는 것 보다 코드가 길어지는 것 같아 
`fruitStoreStock >= requiredAmount`부분을 `decreaseFruitStock()`의 방어로직으로 만들어 주었습니다!

2022-02-25 03:30 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
또치~ 적용해봤습니다 잘 한 건지 모르겠네요😂😂
```swift
extension JuiceMakeError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .outOfStock:
            return "과일재고가 부족해서 제조 불가"
        }
    }
}
```

2022-02-25 05:02 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            fruitStore.decreaseFruitStock(by: juiceRecipe)
위에 문제를 해결하면서 줄여주었습니다!

2022-02-25 05:09 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            }
두번째로 제안해 주신 의견이 확실히 이전 코드보다 가독성이 좋아서 적용해보았습니다!!

2022-02-25 11:49 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
오우 그냥 링크만 툭- 던져드렸던 건데 되게 자세하게 공부하셨군요 👍

2022-02-25 11:49 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
우와 완전 좋아요 🥳

2022-02-25 12:10 UTC, TTOzzi approved these changes
고생하셨습니다 @Minseong-yagom @papriOS !! 🙇 
제가 생각하기에 이번 스텝은 충분히 진행하셨다고 판단되니 민성, 파프리가 코멘트 확인하시고 다음 스텝으로 넘어가도 되겠다고 생각되시면 코멘트 남겨주세요! 머지 들어가겠습니다! 🚀

2022-02-25 12:10 UTC, TTOzzi commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		E581838F27C652590084B0EC /* JuiceMakingError.swift in Sources */ = {isa = PBXBuildFile; fileRef = E581838E27C652590084B0EC /* JuiceMakingError.swift */; };
파일명까지 변경해주시는 섬세함 너무 좋네요! 👍

2022-02-25 12:10 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>              }
요런 특정 조건을 만족하지 못했을 때 함수를 early-return 시켜버리는 로직은, if 보단 guard로 작성해주면 더 코드의 이해가 쉬워집니다 🙂

2022-02-25 12:10 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            if let currentAmount = inventory[fruit], currentAmount >= requiredAmount {
지금도 충분하지만, 에러를 조금 더 상세하게 구분해보자면 `inventory`에 인자로 받은 `Fruit` 이 없을 때와 수량이 부족할 때로 나눠볼 수 있을 것 같아요.
남은 재고가 0개인 것과 아예 `Fruit`를 키로 하는 값이 없는 것은 다르니까요 🙂 
(물론 지금은 `init` 에서 `Fruit`의 모든 케이스를 순회하면서 `inventory`에 넣어주기에 딱히 필요 없는 로직이기도 합니다 🤔 )

2022-02-25 12:10 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>          }
👍 
error는 기본으로 제공해주므로 따로 캐스팅이 필요없다면,
```suggestion
        } catch {
            print("\(error.localizedDescription)")
        }
```
으로도 표현 가능합니다 🙂

2022-02-28 01:40 UTC, Minseong-yagom commented
@TTOzzi 
안녕하세요 또치 피드백 확인하였습니다. 😄
머지 부탁드립니다~

2022-02-28 13:18 UTC, merged