쥬스 메이커 [STEP 2] Roy, Eddy
yagom-academy/ios-juice-maker pull request #194
Opened 2022-03-01 08:19 UTC by kimkyunghun3

안녕하세요 @AppleCEO   Step2 PR입니다 :) 
잘 부탁드립니다!

## 구현내용

- `@IBAction func changeViewControllerTapped(_ sender: Any)` 눌렀을때 재고 수정 화면으로 넘어가는 액션 함수
- `orderJuices` 공통으로 쓰는 함수 주스의 메뉴별로 다르게 적용하는 함수
- `updateFruitsLabel` 라벨의 값을 업데이트 하는 함수
- `orderFruitsButton` 버튼을 눌렀을때 누른 주스 함수로 이동하도록 하는 함수
- `showWithoutStockAlertMessage` 재료가 모자라요. 재고를 수정할까요?라는 문구를 출력후 확인 버튼을 누르면 재고 수정으로 넘어가는 함수
-  `showJuiceAlertMessage` 주스버튼을 눌렀을때 어떤 주스가 완성됐다고 알려주는 alert 메세지 함수
- `initFruits` 과일의 초기값을 10으로 초기화 해주는 함수

## 고민했던점 & 궁금한점

- `orderFruitsButton` 함수에서 default를 어떤식으로 처리해야할지 고민이 되었습니다. 현재 저희가 버튼 클릭에 따라 각각 구현하는 곳을 다르게 했는데 default에 들어갈 버튼이 존재하지 않습니다. 그래서 사실상 default로 가는 부분은 없다고 하지만 switch에서 default 부분에 대한 처리가 필수이기 때문에 어쩔 수없이 Error 케이스를 하나 만들어서 넣었습니다. 하지만 알다시피 이곳은 사용되지 않는 다는 노란색 경고창이 뜨는데 이는 당연하다고 하지만 이를 어떤 식으로 처리하면 좋을지 궁금합니다.
- `updateFruitsLabel`에서 각각의 케이스에 따라 변화하는 재고의 text를 뷰에 보여지도록 구현했습니다. 하지만 딕셔너리가 딕셔너리 자체에서는 옵셔널 타입이 아닌데, 딕셔너리에서의 값을 접근하여 이를 활용하려고 하면 옵셔널 타입이 되는 것을 파악하게 되었습니다. 그래서 옵셔널 바인딩을 통해 옵셔널을 벗겨야되는데 사실 이것을 사용하는 시점이 case 안 이기 때문에 이 순간을 제외하고는 옵셔널이 아니라 옵셔널 바인딩을 사용하는 곳이 case 안에서만 필요하다고 느끼게 되었습니다. 그래서 저는 코드의 가독성을 위해 nil-coalesing 를 활용하는 것이 더 적절하다고 하는데 어떻게 생각하시는지 궁금합니다. 또한 그 값을 따로 빼서 0으로 지정했는데 그 이유로는 여기에서는 재고가 없으면 0 이 되므로 옵셔널로 nil인 경우 0으로 해줘도 될 것이라고 판단했는데 잘못된 방향의 생각인지 궁금합니다.
- `initFruits` 함수에서 저희는 딕셔너러의 키와 값을 통해 초기화 해주는 방법을 생각했습니다. 처음에는 스위치로 하면 더 보기 좋은 코드가 되겠다고 생각했지만 이 딕셔너리 속에는 딸바쥬스, 망고키위쥬스가 같이 존재하기 때문에 default로 이 딕셔너리가 가는 것을 확인하게 되었습니다. 그래서 if- else if 로 구현하게 되었는데 코드 상에서 가독성이 떨어지지만 이렇게 할 수 밖에 없는 이유가 있었는데 괜찮을지 궁금합니다.
- `IBOutlet, IBAction` 네이밍에 대한 정보가 공식문서에서 찾아볼 수 없어서 이곳저곳 찾아봤는데 Label를 쓰는경우 마지막에 Label 표시와 button를 탭한경우 Tapped 라는 것을 마지막에 쓰는 것을 보았는데 이것이 일반적인 네이밍 방식인지 궁금합니다. 아니면 저희가 컨벤셔널한 네이밍을 찾지 못한것인지..? 궁금합니다.
- 일단 저희가 생각하기에 class 2개에 대해서는 현재로서는 상속받을 일이 없기에 final로 구현을 했습니다. 또한 `ViewController`에서 필요한 부분을 캡슐화했는데 캡슐화한 것이 제대로 한것인지, 또 추가로 할 수 있는데 안한 곳이 있는지 궁금합니다.
- 설계한 방식이 model에 있는 것을 사용해서 ViewController에서 View와 연관짓도록 만들려고 노력을 했는데 혹시 저희가 설계하여 구현한 방식이 MVC 패턴을 활용한 적절한 방법인지 궁금합니다.

2022-03-02 00:52 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@kimkyunghun3 , @Roy-wonji  고생하셨습니다~
CustomStringConvertible 을 사용해본다던지 열심히 노력한 부분들이 코드에서 많이 보였습니다.
몇가지 개선하면 좋을 점 남겨놨습니다!

질문에 대한 답변
orderFruitsButton 함수에서 default를 어떤식으로 처리해야할지 고민이 되었습니다. 
- 열거형을 활용하면 switch문에서 꼭 default 를 작성하지 않아도 됩니다. 이 특성을 활용해보면 어떨까요?

그 값을 따로 빼서 0으로 지정했는데 그 이유로는 여기에서는 재고가 없으면 0 이 되므로 옵셔널로 nil인 경우 0으로 해줘도 될 것이라고 판단했는데 잘못된 방향의 생각인지 궁금합니다.
- 이 과일에 재고가 0인건지 이 과일이 없는 과일인지 구분이 되면 더 좋다고 생각은 듭니다. 그런 부분은 try catch 를 활용해서 처리가 가능할 것 같은데요!

initFruits 함수에서 저희는 딕셔너러의 키와 값을 통해 초기화 해주는 방법을 생각했습니다.
- 매칭해주는 다른 방법을 고려해볼 수 있을까요? 저는 이럴 때 enum 의 rawValue 를 많이 활용하는 편입니다~

아니면 저희가 컨벤셔널한 네이밍을 찾지 못한것인지..? 궁금합니다.
- 보통 label 은 붙이는 것이 맞습니다. tap 은 저는 앞 쪽으로 작성을 합니다. 예를 들면 tappedStrawberryButton 과 같이요. 이런 것은 정확한 규칙은 없습니다. 통일감 있게만 작성하면 될 것 같습니다.

iewController에서 필요한 부분을 캡슐화했는데 캡슐화한 것이 제대로 한것인지, 또 추가로 할 수 있는데 안한 곳이 있는지 궁금합니다.
- 캡슐화라는 것이 메소드들에 접근제어자를 설정한 것을 말씀하시는거죠? 다른 객체에서 쓰이지 않는다면 label, button 과 같은 프로퍼티들도 접근제어자를 설정해 볼 수 있을 것 같네요~

설계한 방식이 model에 있는 것을 사용해서 ViewController에서 View와 연관짓도록 만들려고 노력을 했는데 혹시 저희가 설계하여 구현한 방식이 MVC 패턴을 활용한 적절한 방법인지 궁금합니다.
- 보통 폴더명을 나누는 것도 MVC를 작성하는데 좋지만 모델이라는 객체에서만 필요한 것들(에러를 선언한 열거형 등)은 모델 객체 안에서 선언해주는 것도 좋을 것 같습니다. 예를 들면 JuiceMaker 에서 발생할 에러들을 따로 model/Error.swift 라고 놓는 것이 아니라 JuiceMaker 객체 안에서 열거형을 선언하는 방식 등으로 조금 더 모델에 연관성있게 붙여놓을 수 있을 것 같네요!

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +final class ViewController: UIViewController {
여기 final 을 붙인 이유가 있을까요?
ViewController 라는 이름은 적절할까요?

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +class SecondViewController: UIViewController {
뷰컨트롤러를 새롭게 만들어보셨군요~ 👍 
SecondViewController 는 어떤 역할을 할까요?
조금 더 좋은 이름이 있을까요?

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var mangoKiwiButton: UIButton!
레이블과 버튼이 많군요. 이렇게 같은 타입을 모아놓을 수 있는 자료형은 무엇이 있을까요?
그 자료형을 사용하지 않은 이유가 있을까요?

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        guard let pushViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") else { return }
guard let 구문을 사용하셨군요.
한 줄로 작성한 것도 좋지만 아직은 기본형으로 여러 줄로 작성해도 좋을 것 같습니다!

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.pushViewController(pushViewController, animated: true)
위에 줄과 옵셔널 체이닝을 한번 지워볼까요?
옵셔널 체이닝은 간편하게 쓰기 좋지만 이것이 잘 동작할지 직관적으로 알기 힘들 수도 있습니다.
옵셔널 체이닝을 지우고 다른 방법으로 옵셔널 바인딩을 해보고 지금 코드와 차이점을 한번 생각해보면 좋겠네요~

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
쥬스 종류에 따라 반복되고 있군요. 반복을 한번 줄여볼 수 있을까요?

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        if juicesStock.isEmpty {
이 if문을 영어처럼 자연스럽게 읽히네요~ 💯

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let orderJuice = JuiceMaker()
이 함수가 호출될 때마다 쥬스 메이커를 생성해주고 있군요!
혹시 생성하지 않아도 makeJuice 메소드를 사용할 수 있도록 구성해보는 것은 어떨까요?

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
이 부분 조금 어색한 것 같네요. ?? 가 매 케이스마다 들어가있군요.
다른 방식으로 이 ?? 가 매 줄마다 붙어있지 않게 개선해 볼 수 있을까요?

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func showWithoutStockAlertMessage() {
길게 메소드명을 지은 것 좋습니다! 🥇
다만 조금 불명확한 것 같네요. 번역기를 돌려보니 "재고 경고 메시지 없이 표시" 라고 나오는군요.
재고 경고를 제외한 메시지들을 표시하는 메소드일까요?
그렇다면 오히려 무엇을 제외한다는 메소드명보다 A와 B를 표시한다는 메소드명이 더 적합할 것 같습니다~

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/AlerMessage.swift
> +}
하드코딩하지 않고 이렇게 사용되는 문자열들을 모아놓은 점 좋습니다! 💯

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/Error.swift
>  }
진행하면서 발견하는 에러들을 이렇게 추가하는 방식으로도 진행을 많이합니다~ 👍

2022-03-02 00:52 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitsType.swift
> +enum JuiceTypes: CaseIterable, CustomStringConvertible {
CustomStringConvertible 을 사용해보셨군요! 고급집니다~ 🥇 
이 프로토콜을 채택하면 어떤 것들이 가능해지나요?

2022-03-02 12:08 UTC, Roy-wonji commented on JuiceMaker/JuiceMaker/Model/FruitsType.swift
> +enum JuiceTypes: CaseIterable, CustomStringConvertible {
CustomStringConvertible 을 사용하면  사용자 정의에 따른 텍스트 출력이 가능하는 걸로 알고 있습니다!

2022-03-02 12:11 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +final class ViewController: UIViewController {
먼저 final를 붙인 이유는 현재에는 이를 상속할 곳이 없다고 판단했습니다. 그래서 추후에 만약 생기면 final 를 지우는 방식이 낫다고 생각해서 먼저 final를 붙여서 Dynamic dispatch로 되는 것을 Static dispatch로 바꿔서 런타임시 vTable를 찾아 메서드를 실행하는 것을 할 필요가 없게 만들 수 있다고 생각해서 메모리 성능 개선을 위해 붙였습니다. 
정확한 네이밍을 위해 JuiceMakerViewController로 바꿨습니다!!

2022-03-02 12:13 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +class SecondViewController: UIViewController {
앗 현재에는 그것을 지우고 커밋을 했는데 남아있나보네요..? 일단 저 뷰컨트롤러를 만든다면 재고수정하는 뷰컨으로 사용할 예정입니다.  그래서 네이밍을 ChangeStockViewController 로 할 예정입니다!

2022-03-02 12:17 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Model/Error.swift
>  }
감사합니다~😁

2022-03-02 12:31 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func showWithoutStockAlertMessage() {
아 이게 변역기를 돌리게 되면 without 전치사 뒤에 모든 것이 포함되어서 해석이 되는 것 같습니다. 그래서 오해를 사지 않기 위해서 네이밍을 `showStockChangeAlertMessage`으로 변경했으며, 주요 기능은 재고가 없을 경우 재고 변경할 수 있는 얼럿이므로 이렇게 네이밍을 지었습니다.

2022-03-02 12:33 UTC, Roy-wonji commented on JuiceMaker/JuiceMaker/Model/AlerMessage.swift
> +}
감사합니다!

2022-03-03 02:07 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.pushViewController(pushViewController, animated: true)
직관적으로 알기 위해서 먼저 옵셔널 체이닝을 지워서 해봤습니다! 그 코드로는 아래와 같습니다.
```swift
    @IBAction private func changeViewControllerTapped(_ sender: Any) {
        let storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let ChangeStockViewController = storyboard.instantiateViewController(withIdentifier: "ChangeStockViewController")
        if let naviController = navigationController {
            naviController.pushViewController(ChangeStockViewController, animated: false)
        } else {
            JuiceMakerError.notExistNavigationController
        }
    }
```
먼저 다른 방식으로 해볼 수 있는 것은 타입 캐스팅 되는지 여부를 통해 옵셔널 바인딩을 할 수 있을 것 같습니다. 코드로 보여드리면, 
```swift
   @IBAction private func changeViewControllerTapped(_ sender: Any) {
        let storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        if let ChangeStockViewController = storyboard.instantiateViewController(withIdentifier: "ChangeStockViewController") as? ChangeStockViewController {
            navigationController?.pushViewController(ChangeStockViewController, animated: false)
        } else {
            print("Type casting error")
        }
    }
```
이것도 생각해봤던 것인데, 이렇게 하는 것이 맞을지 의문이 되었습니다. 그리고 저렇게 하게되면 아직 ChangeStockViewController class에 아무것도 없어서 그런지 버튼 동작이 안됩니다. 이부분은 불필요한 다운캐스팅이 아닌가 싶습니다!

2022-03-03 02:10 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        guard let pushViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") else { return }
아래 커멘트에 한번에 남겼습니다!

2022-03-03 08:08 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
아하 ! tag를 활용해서 스위치 문에 넣으니까 더 깔끔하게 된것같습니다!!! 이렇게 하라는 말씀이신거죠??😄

2022-03-03 08:28 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
아 그런데 궁금한게, 태그로 하게되면 코드에서 사실상 태그를 통해 switch문을 구분하는데, 이게 가독성을 높일 수 있는 방식인지 의문이 순간 들었습니다. 물론 위의 코드를 줄일 수 있는 장점은 있지만 이부분에 대해서 적절한지에 대해 고민이 되었습니다!!

2022-03-03 08:38 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let orderJuice = JuiceMaker()
아 함수를 호출할 때마다 계속 구조체인 쥬스메이커를 생성하는 것은 비효율적이라는 것을 알게 되었습니다. 그래서 처음에는 매개변수로 넣으면 어떨까 고민을 했었는데, 그렇게하면 이 함수를 사용하는 곳에서도 매개변수에 맞는 인자를 대입해야 되는 불필요성이 발견되었습니다. 그래서 이는 적절한 방법 같지 않다고 생각해서 오히려 이를 전역으로 빼서 하나만 생성해주는게 맞다고 생각하는데 혹시 잘못된 생각이였을까요??

2022-03-07 02:17 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var mangoKiwiButton: UIButton!
Collection를 통해 하나로 묶는 방식으로 바꾸었습니다! 그렇게 나눌 수 있는지 몰랐으나 도미닉의 리뷰를 보고 찾아본 결과 합칠 수 있는 방법이 존재한다는 것을 파악하고 이를 합쳐서 구현했습니다! 구현해보니 확실히 더 보기 쉽고 tag를 통해 접근하기 편해서 좋아진것 같네요!!

2022-03-07 02:18 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
따로 말씀해주신 방식바꿔서 해보니 더 쉽고 편하게 되는 것을 파악할 수 있었습니다! 감사합니다 ㅎㅎ

2022-03-07 02:19 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
이 부분에 대해서도 init의 rawValue 활용하여 IBOutletCollection이랑 태그를 사용해서 바꾸는 방식으로 개선해보았습니다!!!

2022-03-07 04:59 UTC, merged