쥬스 메이커 [STEP 2] minseong, papri
yagom-academy/ios-juice-maker pull request #195
Opened 2022-03-01 08:37 UTC by Minseong-yagom

@TTOzzi 
안녕하세요 또치~ 
minseong, papri입니다
STEP 2 구현해보았습니다
리뷰 늘 감사드립니다. 
STEP 2도 잘 부탁드리겠습니다~ 😄😄🙌

# ios-juice-maker
# 팀원
- minseong, papri

# 구현함수
- `makeJuice()`: 음료를 입력받아 음료제작이 가능한지 확인 후 가능하면 제작. 제작에 성공하면 `true`, 실패하면 `false` 리턴
- `canDecreaseFruitStock()`: 음료제작에 필요한 양만큼 재고를 깎고, 필요한 재료의 재고가 부족하다면 `error`를 `throw`한다. 만약 재고가 충분해 재고를 깎을 수 있다면, `inventory`에 재고상황을 반영하고 `ture`를 리턴
- `updateFruitsStock()`: 과일 `inventory`의 현황을 `VC`의 `UILabel`에 각각 표시
- `showSuccessAlert()`: 과일 제조에 성공했을 때 `Alert`표시
- `showFailAlert()`: 과일 제조에 실패했을 때 `Alert`표시 후 재고 수정시 화면전환

# 고민한 점 및 해결
- 각각의 과일의 재고를 표시하는 `UILabel`을 한번에 관리할 수 있게 하고 싶었습니다
> `IBOutlet Collection`을 사용했습니다.
- `ViewControl`에서 과일 수량 표시하는 `label`의 값을 띄워줘야 하는데 어떻게 `FruitStore` 인벤토리의 값을 가져올지 고민하였습니다.
> 싱글턴패턴을 이용하여 `FruitStore` 인벤토리에 접근하여 반복문을 통해  각각의 `Label` 세팅해 주었습니다
- 주문버튼을 눌렀을 때 재고가 있을 경우와 없을 경우를 어떻게 구별해야 할지 고민하였습니다.
> `makeJuice()`의 `return` 타입을 `bool`타입으로 주어 제조에 성공한 경우와 실패한 경우를 구분해 주었습니다.
- 각각의 쥬스주문버튼의 기능들이 중복이 되는데 하나의 액션으로 다양한 버튼의 기능을 수행할 수 있게 만드는 방법이 있을까요?? 혹시;;; 있다면 그 (정보or기법??)에대한 키워드등을 얻을 수 있을까요??😭
- 과일의 재고가 변경될 때마다 `updateFruitsStock()`를 실행해 주었습니다 매번 실행해 주는게 비효율적이라는 생각이 들었습니다 더 좋은 방법이 있을까요???

2022-03-01 15:07 UTC, TTOzzi requested changes
안녕하세요 @Minseong-yagom @papriOS !
대부분의 피드백은 코멘트로 남겼습니다!

> - 과일의 재고가 변경될 때마다 `updateFruitsStock()`를 실행해 주었습니다 매번 실행해 주는게 비효율적이라는 생각이 들었습니다 더 좋은 방법이 있을까요???

음 아무래도 값이 변경된(업데이트가 필요한) 뷰만 다시 그려주는 게 더 효율적이겠죠?
버튼이 눌렸을 때, 어떤 주스를 만들었는지 알고 있으니 업데이트 해줘야 하는 뷰의 정보를 얻어와 필요한 뷰만 업데이트해줄 수 있을 것 같아요.
`IBOutlet Collection`으로 과일의 `index`와 매핑해서 그려주고 있으니 다시 그려줘야 할 뷰를 찾을 수 있는 정보인 변경된 과일의 `index`와 변경할 `String`값..? 정도를 전달받을 수 있지 않을까요? :thinking:

혹시나 이해가 어려운 부분이 있다면 말씀해주세요! (제가 잘못된 정보를 전달할 수도 있으니 항상 의심하면서 봐주세요 😁)
고생하셨습니다 :bow:

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
기본으로 제공된 `ViewController` 란 이름을 그대로 사용하기보단, 해당 화면이 어떤 화면인지를 표현할 수 있도록 이름을 바꿔보는 건 어떨까요? 👀 
(다른 클래스가 상속받지 않는다면 `final`도 명시해주면 좋을 것 같아요 🙂 )

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet var fruitLabelCollection: [UILabel]!
UI 요소도 외부에서 접근하지 않는다면 `private` 으로 선언해주면 좋을 것 같아요!
(요건 전체적으로 한 번 확인 부탁드립니다 🙏 )

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateFruitsStock()
`ViewController`는 `viewDidLoad` 외에 어떤 라이프사이클 메서드들을 가지고 있나요? 👀 
(아직 기능까지 구현되진 않은 것 같지만) 재고 수정 화면으로 이동해 재고를 수정해주는 기능이 있는 것 같은데, 해당 화면으로 이동했다가 돌아왔을 때도 정상적으로 재고 현황을 UI에 업데이트 할 수 있을까요? 🤔

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        var index:Int = .zero
```suggestion
        var index: Int = .zero
```
요기 살짝 띄워주면 더 좋을 것 같아요 +_+

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            fruitLabelCollection[index].text = String(stock)
배열에서 `index`로 값을 꺼내오는 로직은 배열의 `index` 범위를 벗어나는 값이 들어오더라도 Xcode가 컴파일타임에 체크해주지 못하기에 자칫 잘못하면 크래시를 유발할 수 있습니다 😮
`index`로 값을 꺼내오기 전엔 항상 `index`가 해당 배열의 `index` 범위 내에 있는지 확인해주는 게 좋아요 🙂 
`Array`를 확장해 `index`로 값을 꺼내올 때 항상 방어 로직을 타도록 `subscript` 를 구현해주는 방법도 있으니, 이 글을 한 번 읽어보시면 좋을 것 같습니다!
https://www.hackingwithswift.com/example-code/language/how-to-make-array-access-safer-using-a-custom-subscript

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            index += 1
배열의 요소와 `index`가 매핑된 반복 로직을 수행해야할 때 [enumerated](https://developer.apple.com/documentation/swift/array/1687832-enumerated)를 활용하면, 더 간단하게 구현할 수 있어요 🙂

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            guard let stock = FruitStore.shared.inventory[fruit] else {
현재 `ViewController`가 의존성을 가지는 객체는 `JuiceMaker` 뿐인데, `Fruit` 와 `FruitStore` 까지 `ViewController`가 알고 있어야 할 이유가 있을까요? 🤔 
`JuiceMaker`가 자기 자신이 가진 재고를 보여주는 것 또한 `JuiceMaker`의 역할로 보고, `JuiceMaker`에서 정보를 가져올 수 있으면 더 좋을 것 같아요.

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
인자로 전달되는 주스 정보를 제외하면 버튼의 액션을 처리하는 7개의 메서드가 동일한 로직을 가지고 있네요 🤔 
이벤트가 발생한 버튼이 어떤 `Juice`를 가리키는지 알 수 있다면, 하나의 메서드에서 처리할 수 있을 것 같아요.
힌트를 드리자면, 하나의 `IBAction`에 여러 개의 버튼을 연결해줄 수 있고 이벤트가 발생한 버튼에 대한 정보는 인자인 `sender`로 전달됩니다!

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
싱글톤 패턴의 적용 이유가 어디서든 해당 인스턴스에 접근하기 위함 뿐이라면, 싱글톤보단 다른 방법을 찾아보는 게 좋을 것 같아요.
어디서든 접근할 수 있어 편리하지만, 역으로 생각하면 어디서든 접근할 수 있기에 어디서 어떻게 내부의 값이 수정될지 모른다는 것과 같거든요 🙂 
싱글톤 패턴을 사용하는 이유와 사용했을 때의 장/단점에 대해 좀 더 찾아보시면 좋을 것 같습니다!

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var inventory: [Fruit: Int] = [:]
외부에서 `inventory`에 접근해 내부 값을 수정하는 경우가 있나요? 
쓰기는 막고, 읽기만 허용해주는 `private(set)` 접근 제어자도 있습니다 🙂

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      }
헉 에러처리를 구현했음에도 `Bool`값을 반환하도록 구현하신 이유가 궁금해요! 👀

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: String {
`enum`에 `rawValue`를 설정해주는 것은 어떤 의미를 가질까요? 👀 
`rawValue`를 설정해주면 자동으로 `enum`이 [RawRepresentable](https://developer.apple.com/documentation/swift/rawrepresentable) 프로토콜을 채택하게 되는데, 이 프로토콜에 대해서 공부해보시면 좋을 것 같아요!
단순히 각각의 `case`를 `String`으로 표현하는 것이 목적이라면, [CustomStringConvertible](https://developer.apple.com/documentation/swift/customstringconvertible) 이 더 적합할 것 같습니다 🙂

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        guard let result = try? FruitStore.shared.canDecreaseFruitStock(by: juiceRecipe) else {
싱글톤 객체에 접근하더라도 직접 `.shared`에 접근하기 보단, 생성자를 통해 외부로부터 주입받아 내부 프로퍼티에 할당하고 해당 프로퍼티를 통해 접근하는 게 좋습니다.
요건 지금 이해하긴 어려울 수 있으니 키워드만 살짝.. 시간 여유 있으시다면, 추상화와 의존성 주입에 대해 알아보시면 좋을 것 같아요!

2022-03-01 15:07 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        return result
요기도 위와 같은 궁금증!
에러처리를 없애신 이유가 있을까요? 👀

2022-03-02 05:37 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateFruitsStock()
ViewController의 라이프 사이클은 다음과 같았습니다!
1. `init`
2. `loadView`
3. `viewDidLoad`
    * 뷰의 컨트롤러가 메모리에 로드되고 난 후 호출됨
    * 뷰 로딩 완료되면 자동으로 호출됨
    * 초기화면 구성의 용도
    * 화면 처음 만들어 질 때 한번 만 실행
4. `viewWillAppear`
    * 뷰가 나타나기 직전에 호출 됨
    * 다른 뷰에 갔다가 돌아오는 상황일때 해주고 싶은 처리를 여기서 할 수 있음. 다시 돌아와서 뷰를 나타내기 전에 실행이 되는거임!
5. `viewDidAppear`
    * 뷰가 화면에 나타난 직후 실행됨
    * 뷰가 나타났다는 것을 컨트롤러에게 알림.
    * 화면에 적용될 애니메이션을 그려줌
6.` viewWillDisappear`
    * 뷰가 사라지기 직전에 호출
    * 뷰가 삭제되려고 하는 것을 컨트롤러에 공지
7. `viewDidDisappear`
    * 뷰가 제거되었음을 알림
8. `viewDidUnLoad`

view가 stack 처럼 쌓이는 점을 유의해야하며, (Last in, First out)
그래서 root VC에선 한번 Load하면 또 할 필요 없는데, 만약 화면을 전환하는 상황이 온다면, 예를 들어 VC1 -> VC2인 경우엔
화면 전환을 할때마다 VC2의 viewDidLoad를 해줘야하는 것을 알게 되었습니다(스택에 올려줘야하니까)

재고 수정하는 부분은 STEP3에서 진행하는 것으로 알아 이번에 미처 고려하지 못한 것 같습니다!!

재고현황을 업데이트 해주려면 `viewWillAppear() `에서 `updateFruitsStock()`을 실행하면 될 것 같습니다

2022-03-02 05:44 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        var index:Int = .zero
앜 감사합니다~😉

2022-03-02 08:06 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
처음 시작하는 View를 담은 `ViewController`라는 의미로 `RootViewController` 라고 이름 지었는데, 
`JuiceMakerViewControlle`r 처럼 화면에 표시되는 내용을 표현하는 이름을 지었어야 했을까요? 
둘 중에 고민이 되었습니다!

2022-03-02 11:10 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
iOS에서 [rootViewController](https://developer.apple.com/documentation/uikit/uiwindow/1621581-rootviewcontroller)는 다른 곳에서도 많이 쓰이고 있어서 화면의 역할, 표시되는 내용을 표현하는 이름이 좋을 것 같아요.

2022-03-03 10:41 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            fruitLabelCollection[index].text = String(stock)
`View`에서 과일의 재고를 표현하는 `UILabel`들의 `Array`인 `fruitLabelCollection`에 `UILabel`이 추가되지 않은 상태에서
`Fruit enum`에서 과일의 종류를 추가한다면(예를 들어 `case blueberry`를 추가),
말씀하신대로 `for문`을 돌았을때 `index` 범위를 벗어나 크래시를 유발하게 될 수 있어 
알려주신 링크 참고하여, 다음코드를 추가해 `Array를 확장`시켰습니다.

```swift
extension Array {
    public subscript(safeIndex index: Int) -> Element? {
        guard index >= .zero, index < endIndex else {
            return nil
        }

        return self[index]
    }
}
```

2022-03-03 10:43 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            index += 1
말씀해주신대로 `enumerated`를 찾아보아 적용해보았습니다.
Fruit.allCases가 배열인 덕분에 `enumerated()`를 활용할 수 있었습니다.

```swift
    private func updateFruitsStock() {
        for (index, fruit) in Fruit.allCases.enumerated() {
            guard let stock = FruitStore.shared.inventory[fruit] else {
                return
            }
            
            guard let fruitLabel = fruitLabelCollection[safeIndex: index] else {
                return
            }
            
            fruitLabel.text = String(stock)
        }
    }
```

2022-03-03 12:13 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
어디서나 `FruitStore`의 `inventory`에 접근할 수 있도록 싱글톤 패턴을 적용해 본 것이 맞습니다.
말씀하신대로 싱글톤 패턴의 사용이유와 장단점을 찾아보았는데,
전역으로 접근할 수 있다는 장점이 동시에 단점이 되더라구요.
말씀하신 것 처럼 각기 다른 곳에서 `inventory`의 상태를 마구 변경시킬 여지가 있다보니, 상태를 가진 객체는 `Singleton`으로 만들면 안된다는 이야기를 읽었습니다. 그래서 무상태 객체 혹은 설계상 유일해야하는 시스템 컴포넌트를 `Singleton`으로 만들어야 한다고 하네요! (이 부분에 대해서 또치의 의견도 들어보고싶습니다!)
그래서 `싱글톤 패턴`을 적용하는 것이 아닌` KVO 패턴`를 적용해 보는게 더 적합해 보입니다!

2022-03-03 18:48 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      }
우선 처음 저희가 Bool 값이 반환되도록 한 이유는 다음과 같습니다.
ViewController(JuiceMakerViewController로 이름 변경) 에서 주문 버튼을 누르고,
쥬스를 만드는데 성공한다면 - 즉 JuiceMaker의 makeJuice()를 진행하는데, 재고가 충분히 있어 FruitStore의 canDecreaseFruitStock()가 true여서 makeJuice()의 리턴값도 true가 되면,
showSuccessAlert()를 호출하고
false라면(쥬스를 만들 수 없다면 , 즉 재고가 부족하다면) showFailAlert()를 호출하고자 하는 코드를 작성했기 때문입니다.

즉 bool 값을 기준으로 실패알림과 성공알림을 띄우려고 했기 때문에, Bool 값을 반환하도록 구현하였습니다!

```swift
    @IBAction func makeStrawberryJuiceButton(_ sender: UIButton) {
        switch juiceMaker.makeJuice(by: .strawberryJuice) {
        case true:
            showSuccessAlert(juice: Juice.strawberryJuice.rawValue)
            updateFruitsStock()
        case false:
            showFailAlert()
        }
    }
```

```swift
// FruitStore 클래스의 메소드
    func canDecreaseFruitStock(by ingredient: [Fruit: Int]) throws -> Bool {
        for (fruit, requiredAmount) in ingredient {
            guard let currentAmount = inventory[fruit], currentAmount >= requiredAmount else {
                throw JuiceMakingError.outOfStock
            }
            let remainingAmount = currentAmount - requiredAmount
            inventory[fruit] = remainingAmount
        }
        return true
    }
```
여기서 반환값을 bool값으로 받으면

```swift
 // JuiceMaker 구조체의 메소드
    func makeJuice(by order: Juice) -> Bool {
        let juiceRecipe = order.recipe
        guard let result = try? fruitStore.canDecreaseFruitStock(by: juiceRecipe) else {
            return false
        }
        
        return result 
    }
```
return result에서 바로 true값을 리턴할 수 있습니다.

2022-03-04 02:10 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: String {
`enum`에 `String `타입의` rawValue`를 설정해주면, 
`enum`의 각 `case`들이 `원시값`을 가지게 되어, 원시값에 접근하려면  일일히 `.rawValue를` 붙여야합니다.

알려주신 CustomStringConvertible 프로토콜로 enum을 확장시켜, case를 String으로 표현되는 것이 가능하게끔 만들었습니다!

```swift
extension Juice: CustomStringConvertible {
    var description: String {
        switch self {
        case .strawberryJuice:
            return "딸기쥬스"
        case .bananaJuice:
            return "바나나쥬스"
        case .kiwiJuice:
            return "키위쥬스"
        case .pineappleJuice:
            return "파인애플쥬스"
        case .strawberryBananaJuice:
            return "딸바쥬스"
        case .mangoJuice:
            return "망고쥬스"
        case .mangoKiwiJuice:
            return "망키쥬스"
        }
    }
}
```

2022-03-04 02:19 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
각각의 버튼에 고유한 `tag`값을 정해줘서 `IBAction`에 여러 개의 버튼을 연결하였습니다!

```swift
 @IBAction func clickMakeJuiceButton(_ sender: UIButton) {
        var order: Juice
        switch sender.tag {
        case 1:
            order = .strawberryBananaJuice
        case 2:
            order = .mangoKiwiJuice
        case 3:
            order = .strawberryJuice
        case 4:
            order = .bananaJuice
        case 5:
            order = .pineappleJuice
        case 6:
            order = .kiwiJuice
        case 7:
            order = .mangoJuice
        default:
            order = .strawberryJuice
        }
        
        switch juiceMaker.makeJuice(by: order) {
        case true:
            showSuccessAlert(juice: order)
            updateFruitsStock()
        case false:
            showFailAlert()
        }
    }
```

2022-03-04 02:20 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        return result
위에 함께 적어두었습니다!!

2022-03-04 02:24 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            guard let stock = FruitStore.shared.inventory[fruit] else {
```swift
    func getFruitsStock() -> [Int] {
        var fruitStockArray: [Int] = []
        
        for fruit in Fruit.allCases {
            if let stock = fruitStore.inventory[fruit] {
                fruitStockArray.append(stock)
            }
        }
        return fruitStockArray
    }
```
JuiceMaker에 다음과 같이 재고를 담은 배열을 리턴하는 함수인 getFruitsStock()을 만들어서

```swift
    private func updateFruitsStock() {
        for (index, stock) in juiceMaker.getFruitsStock().enumerated() {
            guard let fruitLabel = fruitLabelCollection[safeIndex: index] else {
                return
            }
            fruitLabel.text = String(stock)
        }
    }
```
ViewController에서 JuiceMaker만 알고 있어도 되게끔 수정해보았습니다!

2022-03-04 02:28 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
STEP2 에서는 화면끼리 데이터 값을 전달하는 것 까지 요구하고 있지는 않아 Notification Center 활용은 하지 않은 상태로 Singleton 패턴만 해제하였습니다!

2022-03-04 02:36 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
`JuiceMakerViewController`  로 변경하였습니다!

2022-03-04 15:09 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateFruitsStock()
앗 요거 전에 볼 때 놓친 것 같은데, `viewDidUnLoad`는 deprecated 됐어요!

2022-03-04 15:13 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
switch-case 문에선 항상 모든 경우의 수에 대한 처리를 빠짐없이 해줘야 하기 때문에 default 는 작성해주어야 합니다 😢

2022-03-04 15:15 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
> 그래서 무상태 객체 혹은 설계상 유일해야하는 시스템 컴포넌트를 Singleton으로 만들어야 한다고 하네요! (이 부분에 대해서 또치의 의견도 들어보고싶습니다!)
저도 같은 생각이에요! 싱글톤 패턴을 적용하는 이유가 전역에서의 인스턴스 접근 보단, 앱 전체에서 하나의 인스턴스만 존재해야 할 때가 되어야 한다고 생각해요.

2022-03-04 15:19 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      }
음! 쥬스를 만드는 데에 실패하는 케이스를 에러로 정의해주셨으니, viewController에서 try-catch를 활용해 에러를 캐치했을 때 실패에 대한 처리를 해줄 수 있지 않을까요? 👀 
정의해두신 에러의 `localizedDescription`를 활용해서 발생한 에러마다 다른 메세지를 사용자에게 보여줄 수도 있구요!

2022-03-04 15:23 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: String {
원시값을 가지게되어 `rawValue`로 원시값에 접근할 수 있다는 것도 있지만, 자동으로 생성자가 만들어져 원시값으로 `enum`의 `case`를 생성해줄 수 있게 됩니다.
생성자를 만들어주는 것도 의도한 동작이라면 `rawValue`를 설정해주고, 단순 문자열로 표현하기 위함이라면 `CustomStringConvertible`을 사용하면 될 것 같아요! 🙂

2022-03-04 15:50 UTC, TTOzzi requested changes
고생하셨습니다!!
추가 코멘트 남겨드렸으니 확인해주세요! 
(뭔가 계속 트집잡는 것 같아 살짝 죄송하네요.. 조금만 더 힘내보아요 🙇 )

2022-03-04 15:50 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +}
별도의 파일로 분리해주면 더 좋을 것 같아요!
이런 유틸성 extension은 앱 내 어디서든 쓰일거니까요 🙂 

추가로 `public` 접근제어자는 필요할까요? 👀 
예제 코드를 그대로 가져오기보단, 로직이 어떻게 구현되어 있는지 참고하는 정도로만 보고 필요한 부분만 가져오는 게 좋습니다.

2022-03-04 15:50 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
이 메서드에서 이벤트가 발생한 버튼이 어떤 쥬스와 매핑되는지 확인하는 로직을 별도의 메서드로 분리할 수 있을까요? 👀 

그리고 추가로 살짝 말씀드리면, `tag`는 각각의 `tag` 값이 어떤 의미를 가지는지 파악이 어렵고, 어떤 뷰가 `tag` 값을 갖고있는지 확인이 어려워 선호되는 방식은 아닙니다. 
(잘못된 방식은 아니니 참고만 해주세요 🙏  사실 지금 상황에선 괜찮은 것 같아요!)

2022-03-04 15:50 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +   init() {
이 친구 한칸 이동했어요! +_+

2022-03-04 15:50 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +}
코드를 읽을 땐, 파일의 위에서 아래로 내려가면서 읽게 되는데요.
개인적인 생각으론 `Juice` 타입이 어떻게 선언되어 있는지 먼저 보여주고, 이런 부가적인 기능을 보여주는 게 코드 이해가 쉬울 것 같아요.
(주관이 담긴 코멘트니 참고만 해주세요 🙏 명확한 이유를 갖고 코드를 작성한 이유를 설명할 수 있다면 전혀 문제 없습니다!)

2022-03-04 15:50 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>          }
이건 수정 안 하셔도 됩니다. 여유있으시면 해보는걸로!

[map](https://developer.apple.com/documentation/swift/array/3017522-map) 고차함수를 활용하면 좀 더 깔끔하게 처리할 수 있을 것 같아요 🙂 
(좀 더 보태면 [compactMap](https://developer.apple.com/documentation/swift/sequence/2950916-compactmap) 까지도..!)

2022-03-04 15:53 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBAction func clickMakeJuiceButton(_ sender: UIButton) {
요기도 외부 접근이 없다면 `private` 붙여주세요! 🙏

2022-03-07 11:48 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +}
🙏🏼

2022-03-07 12:27 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>          }
고차함수가 뭔지는 알겠는데 적재적소에 활용을 잘 못하겠네요😂 감사합니다!!🙏🏼

2022-03-07 12:28 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
`checkClickedJuice()`메서드로 매개변수를 sender로 받아 어떤 버튼인지 체크해주었습니다

2022-03-07 12:30 UTC, Minseong-yagom commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      }
에러처리를 이용하여 리팩토링 해보았습니다 저희가 고친게 말씀해주신 의도에 맞게 한 것 일까요??

2022-03-07 14:40 UTC, TTOzzi approved these changes
고생하셨습니다! 🙇 
에러처리 부분도 잘 구현해주셨네요 🥳 
사소한 코멘트 몇 개 남겨뒀는데, 크게 중요한 부분은 아니니 수정할 부분이 있다면 다음 스텝과 함께 생각해보아요!
그럼 머지하겠습니다 🚀

2022-03-07 14:40 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func checkClickedJuice(Button: UIButton) -> Juice {
`Button` 첫 글자가 대문자에요! +_+

2022-03-07 14:40 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            return .strawberryJuice
`default`는 현재 로직에선 사실상 들어올 일이 없겠지만, 이렇게 의미 없는 값을 넣어주기보단 `nil`을 반환해 해당 버튼에 대한 쥬스가 없음을 표현해주는 게 좋을 것 같습니다 🙂 
아니면 여긴 절대절대 도달할 수 없는 곳이다! 라는 표현을 `fatalError`로 해줄 수 있으나.. 여긴 누군가 버튼 `tag`를 잘못 설정하면 도달할 수 있기에 `nil`을 반환하는게 좋겠네요.

2022-03-07 14:40 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        fruitStockArray = Fruit.allCases.compactMap { fruitStore.inventory[ $0 ] }
오호 금방금방 적용하시는군요! 👍 
`[ $0 ]` 이 친구 방이 넓은 건 의도하신 컨벤션 인가요? 👀

2022-03-07 14:41 UTC, merged

2022-03-08 01:42 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        fruitStockArray = Fruit.allCases.compactMap { fruitStore.inventory[ $0 ] }
아니요! 수정하였습니다 😅