쥬스메이커 [STEP2] Onetool, 두두
yagom-academy/ios-juice-maker pull request #198
Opened 2022-03-01 11:48 UTC by FirstDo

@1Consumption
안녕하세요 올라프!
onetool, 두두 입니다!
쥬스 메이커 STEP 2을 완료하여 PR 보냅니다!
잘부탁드립니다 :)

## 구현내용
`updateFruitLabel` : 과일의 재고를 Label에 표시해주는 함수  
`tapStockEditButton` : 재고 관리 버튼과 연결된 함수  
`moveToStockViewController` : StockViewController를 modal로 띄워주는 함수  
`order` : 쥬스 주문 시, 실행되는 함수  
`check` : 어떤 버튼이 눌렸는지, 판단해서 만들 Juice를 retun해주는 함수  
`showSotckErrorAlert()` :  쥬스 재고가 부족할때 alert을 띄우는 함수  
`showOkAlert()` : 확인 버튼 하나인 alert을 띄우는 함수  
`enum AlertMessage` : AlertController에 쓰이는 문자열들을 관리하기 위한 namespace  

❗️고민한 점

1. juiceMakerController의 fruit Label들을 업데이트 하려면, 과일 재고를 가져와야 했습니다.  
그래서 fruitStore의 fruitStock을 private(set)으로 바꾸고,  
JuiceMaker에 fruitStock라는 연산 프로퍼티를 추가하는 식으로 구현했습니다.  더 좋은 방법이 있을까요? 

2. AlertContrller의 title, AlertAction의 title등을 쓸때, 문자열 그대로 쓰는것 보다, namespace로 관리를 하는게 좋다고 생각했습니다.  
그래서  enum과, static으로 관리를 했는데, 해당방법이 괜찮은가요?

3. StockViewController를 생성할때 "StockViewContrller" 라는 storyboard ID를 지금 문자열로 바로 적어주고 있는데, 이것도 따로 관리하는게 좋을까요?  저희 생각은, 똑같이 enum StoryBoardID {} 같은걸 만들어서 static let으로 해주면 어떨까 싶습니다.

4. alert을 띄우는 함수들을 다른 파일에 쓰고 싶었는데, 인스턴스인 juiceMaker에 private이 결려있어서 다른 파일에 만들지 못했습니다.  
그래서 extension으로 따로 빼줬는데, 적절한 방법일까요?

2022-03-02 12:03 UTC, 1Consumption requested changes
안녕하세요 원툴 두두~ 고생하셨습니다!

커밋이 한번에 하나의 역할만 하고 있어서 정말 읽기 좋았습니다 👍👍👍
메소드도 잘 나눠주셔서 좋았습니다.

그런데 커밋을 보다가 조금 아쉬운 점이 있었어요.
https://github.com/yagom-academy/ios-juice-maker/pull/198/commits/736c60c1137b21a451c1050e31acd1fbd87b8222
https://github.com/yagom-academy/ios-juice-maker/pull/198/commits/c4446bfd9dbc85c7675289284a2cbb10d2518d3a
이 두개의 커밋을 보니 class이름을 바꾼 커밋과 바뀐 이름이 proj파일에 적용된 커밋이 분리가 되어있네요. 이러면 어떤 문제가 발생할까요?

-----------------------------

주신 질문에 대한 제 생각입니다.

> 1. juiceMakerController의 fruit Label들을 업데이트 하려면, 과일 재고를 가져와야 했습니다.  
그래서 fruitStore의 fruitStock을 private(set)으로 바꾸고,  
JuiceMaker에 fruitStock라는 연산 프로퍼티를 추가하는 식으로 구현했습니다.  더 좋은 방법이 있을까요? 

이정도는 괜찮다고 생각이되네요. 결국 어디선가는 접근을 해야하거든요.

> 2. AlertContrller의 title, AlertAction의 title등을 쓸때, 문자열 그대로 쓰는것 보다, namespace로 관리를 하는게 좋다고 생각했습니다.  
그래서  enum과, static으로 관리를 했는데, 해당방법이 괜찮은가요?

이건 정말 좋은 방법이네요. 저도 종종 써요ㅎㅎ. 그런데 Error에 대한 String은 다른 방법이 있긴합니다!

> 3. StockViewController를 생성할때 "StockViewContrller" 라는 storyboard ID를 지금 문자열로 바로 적어주고 있는데, 이것도 따로 관리하는게 좋을까요?  저희 생각은, 똑같이 enum StoryBoardID {} 같은걸 만들어서 static let으로 해주면 어떨까 싶습니다.

좋은 생각입니다! 이름을 붙이는게 읽기좋은 코드를 짜는 방법이죠

> 4. alert을 띄우는 함수들을 다른 파일에 쓰고 싶었는데, 인스턴스인 juiceMaker에 private이 결려있어서 다른 파일에 만들지 못했습니다.  
그래서 extension으로 따로 빼줬는데, 적절한 방법일까요?

이건 정확히 어떤걸 말하는지 잘 모르겠네요... 나중에 디코에서 얘기를 나눠보도록해요.

나머지는 코멘트로 남겼으니 확인 부탁드려요~

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        updateFruitLabel()
추상화 좋습니다👍

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +    }
```suggestion
    @IBAction func didTapStockEditButton(_ sender: UIBarButtonItem) {
        moveToStockViewController()
    }
```

은 어떨까요?

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        let stock = self.juiceMaker.fruitStock
어디는 self가 붙고 어디는 안붙네요. 기준이 있을까요?

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        }
오~ 이 코드 설명해주실 수 있을까요?

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        self.present(navigationController, animated: true)
네비게이션컨트롤러를 present해주는 이유가 있을까요?

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        do{
공백이 없네요
```suggestion
        do {
```

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +            let juice = try check(button: sender)
이 check 메소드는 정확히 어떤걸 하는 메소드인가요? 이름과 반환값을 가지고 예측이 안되네요

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +            updateFruitLabel()
하나의 주스가 바뀌면 전체 레이블을 업데이트 하네요? 다른 방법은 없을까요?

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +    }
아하... 버튼과 주스 타입을 바인딩하는 메소드였군요... 이름을 좀 더 알아볼 수 있게 바꿔볼까요?

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +            self.moveToStockViewController()
강한 참조를 했네요! 이부분을 어떻게 바꿀 수 있을까요?

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +}
error 메세지는 `LocalizedError`를 이용해 따로 빼는건 어떨까요

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +//  Created by 원툴, 두두 on 2022/02/22.
👍

2022-03-02 12:03 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: CustomStringConvertible {
`CustomStringConvertible`은 어떤 기능을 하는건가요?

2022-03-07 08:32 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +    }
버튼이 눌린후 호출되는 메서드이므로, 올라프 말대로 바꿨습니다!

2022-03-07 08:36 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +            let juice = try check(button: sender)
버튼에 맞는 쥬스를 찾는다는 의미로
findJuice(of button: UIButton) -> Juice 로 바꿨습니다

2022-03-07 08:51 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        do{
공백 추가 하였습니다..!

2022-03-07 08:59 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        self.present(navigationController, animated: true)
step3에서 재고 수정 및 닫기 버튼을  추가할 때 사용하는 것을 대비해 Navigationbar를 생각해서 Navigationcontroller를 present했습니다. main storyboard에 있는 사용하지 않는 Navigationcontroller를 제거했습니다.

2022-03-07 10:02 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +    }
위에서와 같이 매서드 이름변경 하였습니다

2022-03-07 10:02 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +}
JuiceMakerError에 LocalizeError 프로토콜을 채택해서 적용해주었습니다.

2022-03-07 10:03 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +            updateFruitLabel()
기존함수를 삭제하고 updateMultipleLabel, updateLabel 두 함수를 만들어서, 사용한 과일만 업데이트 되도록 하였습니다..!

2022-03-07 10:06 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        let stock = self.juiceMaker.fruitStock
원래는 클로저 안에 있어서 self를 사용했지만, Refactoring 이후moveToStockViewController 함수에서 사용해서 self를 사용 할 필요가 없어져서 삭제하였습니다.

2022-03-07 10:08 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        }
JuiceMakerController에서 stockViewController의 프로퍼티에 직접 접근하는건 좋지 않다고 생각했습니다.
그리고, 이니셜라이저를 쓸 수 없으므로 무조건 선언을 옵셔널로 해야하는 문제도 있었습니다.

이때, `instantiateViewController(identifier:creator:)`를 사용하면, 이니셜라이저를 이용할 수 있다는걸 알아서 해당 방법으로 구현해 보았습니다

2022-03-07 11:19 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: CustomStringConvertible {
굳이 필요하지 않다고 여겨서 삭제후, name 프로퍼티를 추가했습니다

2022-03-07 11:20 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +            self.moveToStockViewController()
해당 부분은 alert을 리펙토링하는 과정에서 제거되었습니다

2022-03-07 11:27 UTC, FirstDo commented
@1Consumption 피드백 수정완료하였습니다! :)

2022-03-07 17:31 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: CustomStringConvertible {
왜 필요하지 않다고 생각했나요?

2022-03-07 17:37 UTC, 1Consumption commented
반영 사항 잘 확인 했습니다! 훨씬 보기 좋군요.

> 아래 함수를 쓰다보니, 굳이 do catch를 해야하나라는 의문이 들었습니다.
잘못된 버튼(이 프로젝트에서는 일어날 일이 없는)을 눌렀을때, 그냥 아무일이 일어나지 않게 해도 좋을것 같아요

이부분은 정말 취향차이 같네요. 사실 do catch를 하지 않고 `try?`를 통해 옵셔널로 사용할 수도 있거든요. 하지만 이런 사소한 것부터 고민을 하고, 이유가 있다는게 정말 좋네요!

이번 스텝은 여기서 마무리를 하도록 하고, 다음 스텝을 진행해도 좋을 거 같아요. 고생하셨습니다!

2022-03-07 17:38 UTC, merged

2022-03-08 02:26 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: CustomStringConvertible {
원래 let title = juice + " " + AlertMessage.makeJuice 이렇게 하려고 했는데, let title = "\(juice)" + " " + AlertMessage.makeJuice 이런식으로 보간법을 사용해야지만 사용이 가능했어서 깔끔하게 사용하는 목적이 맞지 않다고 생각하여 필요하지 않다고 생각했습니다.