쥬스메이커 [STEP2] 쿼카, Donnie
yagom-academy/ios-juice-maker pull request #199
Opened 2022-03-01 12:12 UTC by Quokkaaa

@yoo-kie 
개굴 STEP2 PR보내드립니다 잘부탁드릴게요 ❤️ ❤️ 

# [STEP2]
# 고민되었던점&문제해결
- 쥬스주문하는 `Action`메서드들을 구현하게될때 중복코드가 발생하였던 것을 `convertToJuice` 메서드로 `Juice`값을 확인해주어 해결해주었습니다.
- 재고수정화면으로 이동시 `identifier`를 이용한 하드코딩 문제를 `identifier`타입 메서드 생성하여 해결하였습니다.
- 얼럿메세지 출력시 쥬스 이름값을 같이 출력하는 부분을 매개변수로 `Juice Type`를 받고 `Juice` 타입 내 `name`이라는 연산프로퍼티를 만들어 `string`값을 반환해주었습니다.
- STEP2 기능구현보다 더 많은 기능구현을 하게된것을 알게되어 요구사항에 맞는 기능구현을 준수하기위해 커밋을 `reset`하여 다시 진행하였습니다.
-  얼럿에 사용되는 문자열들이 하드코딩이 발생하여 이를 방지하기위해 `AlertMessage`라는 열거형으로 담아주었습니다.

# 조언을 얻고 싶은 부분
* 화면이동시 `identifier`로 접근을 시도하였는데 `ViewController`를 다운캐스팅하여 타입을 확인하는 방법도 있었지만 단순한 `identifier`를 사용해보았습니다. 조언해주실 부분이 있다면 조언부탁드립니다.
* `updateFruitStockCountLabel()` 메서드내 `bringStockValue`중복 코드를 개선해볼 수 있을까요 ??
* `bringStockValue()` 메서드의 `return`처리를 `""`로 진행하였는데 이부분도 처리를 에러로 빼거나? 별도로 해주는게 좋을까요 ?

2022-03-02 14:27 UTC, yoo-kie requested changes
# 고민되었던점&문제해결
- 쥬스주문하는 `Action`메서드들을 구현하게될때 중복코드가 발생하였던 것을 `convertToJuice` 메서드로 `Juice`값을 확인해주어 해결해주었습니다.

`🐸 중복코드에 대해 재사용성을 높여 주셨더라구요! 아주 좋은 접근이었던 것 같아요!`

- 재고수정화면으로 이동시 `identifier`를 이용한 하드코딩 문제를 `identifier`타입 메서드 생성하여 해결하였습니다.

`🐸 String(describing:)을 활용하셨더라구요! 이것도 좋은 활용이었습니다! 나중에 모든 class에서 적용되는 identifier를 만드시는 것도 도전해보시면 좋을 것 같아요!`

- 얼럿메세지 출력시 쥬스 이름값을 같이 출력하는 부분을 매개변수로 `Juice Type`를 받고 `Juice` 타입 내 `name`이라는 연산프로퍼티를 만들어 `string`값을 반환해주었습니다.

`🐸 Enum의 장점을 잘 활용하신 것 같아요:) 👍👍👍👍`

- STEP2 기능구현보다 더 많은 기능구현을 하게된것을 알게되어 요구사항에 맞는 기능구현을 준수하기위해 커밋을 `reset`하여 다시 진행하였습니다.

`🐸 오! 말씀하신 부분이 사라지고 커밋은 깔끔하게 진행된 것 같아요. 어떻게 reset하셨는지 나중에 공유해주시면 좋을 것 같습니다!🙇🏽‍♀️`

-  얼럿에 사용되는 문자열들이 하드코딩이 발생하여 이를 방지하기위해 `AlertMessage`라는 열거형으로 담아주었습니다.

`🐸 얼럿을 정리해준 부분 깔끔해서 좋았습니다! 다만 description 관련해서 커멘트를 남겨두었는데요! 고민해보시고 다시 커멘트 부탁드립니다ㅎㅎ`

# 조언을 얻고 싶은 부분
* 화면이동시 `identifier`로 접근을 시도하였는데 `ViewController`를 다운캐스팅하여 타입을 확인하는 방법도 있었지만 단순한 `identifier`를 사용해보았습니다. 조언해주실 부분이 있다면 조언부탁드립니다.

`🐸 identifier를 문자열 그대로 사용하지 않고 매직넘버 처리하신 부분 좋았어요! 지금은 EditFruitStockViewController에 한정되는 identifier 타입메서드지만 모든 클래스에 적용이 가능한 identifier가 있으면 더 좋을 것 같아요!`

* `updateFruitStockCountLabel()` 메서드내 `bringStockValue`중복 코드를 개선해볼 수 있을까요 ??

`🐸 이 부분은 각 label을 Fruit별로 구분할 수 없을까요? 먼저 고민해보시면 좋을 것 같아요!`

* `bringStockValue()` 메서드의 `return`처리를 `""`로 진행하였는데 이부분도 처리를 에러로 빼거나? 별도로 해주는게 좋을까요 ?

`🐸 이건 도니와 쿼카가 어떻게 기획하는지에 따라 다를것 같아요! 지금처럼 빈값으로 처리해줘도 좋고 “-“ 또는 “0" 이런 디폴트 값 표시도 좋겠네요! 그리고 지금과 같이 사용자의 이벤트로 발생할 수 있는 에러가 아니라면 최대한 fruitsStock에 존재하는 과일인지를 보장해줄 수 있으면 더 좋을 것 같습니다!`

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/EditFruitStockViewController.swift
> +class EditFruitStockViewController: UIViewController {
클래스 네이밍은 명사로 시작하면 좋을 것 같아요:)

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/EditFruitStockViewController.swift
> +
공백을 남겨둔 이유가 있으실까요??

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +
이 공백에도 이유가 있을까요??

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +    @IBOutlet weak var strawberryCountLabel: UILabel!
역할+UI 컴포넌트로 구성된 네이밍 좋습니다!👍

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        if sender == strawberryBananaJuiceButton {
오! UIButton의 sender의 활용 좋은 접근입니다! 다만 UIButton 자체를 파라미터로 전달하는 것 외에 다른 방법을 없을까요? 각 UIButton의 고유값을 가지고 싶다면 `tag` 데이터를 활용해보는 것은 어떨까요?

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/EditFruitStockViewController.swift
> +        return String(describing: self)
`String(describing: self)`을 활용해보셨군요!

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>              _ = try fruitStore.makeReady(for: juice)
makeReady가 반환하는 값은 사용되지 않는 것 같은데 Bool타입을 반환하도록 한 이유가 있을까요?

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +    func updateFruitStockLabels() {
PR 코드 전반적으로 접근제어가 고려되지는 않은거 같아요:) 코드의 접근 범위를 구분해서 접근제어자를 추가해주시면 더 안정적인 프로젝트가 될 수 있을 것 같습니다.🐸

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/AlertMessage.swift
> +    case cameOut
AlertMessage의 case 네이밍은 어떤 기준으로 작성하신걸까요?

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +                                             message: AlertMessage.enjoyDrink.description,
AlertMessage 내 description을 각각 따로 title과 message로 작성하지 않고, 하나의 AlerMessage에서 title과 message를 가져올 수는 없을까요?

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) -> Bool {
try-catch로 에러를 핸들링하다 Bool타입을 반환하도록 처리하신 이유가 있으실까요??

2022-03-02 14:27 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        present(editFruitStockViewController, animated: true, completion: nil)
present로 화면 이동을 하셨네요! present를 선택하신 이유가 있으신가요?
Main 스토리보드에서는 EditFruitStockViewController에 네비게이션컨트롤러가 embed되어 있던데 어떻게 화면을 구상하셨는지 설명해주실 수 있나요?☺️

2022-03-03 01:56 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/EditFruitStockViewController.swift
> +class EditFruitStockViewController: UIViewController {
`FruitStockEditViewController` 로 수정했습니다.

2022-03-03 02:01 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/EditFruitStockViewController.swift
> +
저희 기준에서 메서드는 위아래 공백이있는게 습관화되있다보니 공백을 넣은것같습니다. 
공백 제거하였습니다!

2022-03-03 02:03 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +
`UILabel`과 `UIButton`을 시각적으로 잘 구별되게하기위해서 공백을 주었습니다!

2022-03-03 02:52 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        if sender == strawberryBananaJuiceButton {
개굴의 조언대로 코드의 가독성이 좋아지는 방향인것같아서 수정해볼 수 있을것같아요. 그런데 궁금한점이 `tag`를 사용하게되면 명시적으로 데이터를 입력해야하는 상황이 발생하는데 (예: 1, 2, 3, 4) 이런부분도 하드코딩이라고 하지않나요 ??? 🤔🤔🤔

2022-03-03 02:55 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>              _ = try fruitStore.makeReady(for: juice)
`orderJuices` 메서드내 `juiceMaker.makeJuice(juice) ? showSuccessAlert(of: juice) : showFailureAlert()`  이렇게 사용하고 있습니다!!

2022-03-03 07:09 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/AlertMessage.swift
> +    case cameOut
Alert메세지들을 최대한 직관적이고 간단하게 번역하려고 했던것같습니다

2022-03-03 07:21 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +                                             message: AlertMessage.enjoyDrink.description,
혹시 말씀하신 의도가 `showSuccessAlert` 메서드내에서 `AlertMessage`타입으로 값을 다 명시해주는것에서 각각 `타입.case.property`를 명시해주느것이 아니라 더 좋게 표현할 수는 없을까 라고 받아들여지는데 맞을까요 ???

2022-03-03 07:26 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) -> Bool {
`JuiceStoreViewController`에서 `orderJuices`내 메서드에서 사용되기때문에 반환값을 넣어주었습니다.
혹시 ..저희가 의도하신 질문에 맞게 답변을 했을까요 ??

2022-03-03 07:29 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        present(editFruitStockViewController, animated: true, completion: nil)
모달을 사용을 하는게 적합하다고 판단했습니다.
이유는 계층구조로 넘어가는 것보다 특정한 기능을 수행하고 종료하는 것에 가깝다고 생각되어 `Modal`방식으로 `present`를 하였습니다.
추가로 `embed`되어있는 네비게이션 컨트롤러는 사용할 이유가없어 삭제하겠습니다 ㅎㅎ

2022-03-03 14:05 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        if sender == strawberryBananaJuiceButton {
tag를 활용해보셨네요:) 아 그런 상황이라면 Juice 열거형에서 rawValue를 활용해보시는건 어떤가요?

2022-03-03 14:09 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) -> Bool {
아 그럼 Bool타입으로 반환하지 않고 에러를 throw해서 orderJuices 메서드에서 어떤 얼럿창을 띄워줄지 결정할 수는 없을까요?

2022-03-03 14:12 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +                                             message: AlertMessage.enjoyDrink.description,
아! AlertMessage에 title과 message 프로퍼티를 생성해서 사용하는 방식을 말씀드린거였습니다!🐸

2022-03-04 06:19 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        if sender == strawberryBananaJuiceButton {
좋은 방법인것같습니다...!!!
```swift
    private func convertToJuice(_ sender: UIButton) -> Juice? {
        switch Juice(rawValue: sender.tag) {
        case .strawberryBanana:
                return .strawberryBanana
        case .strawberry:
                return .strawberry
        case .banana:
                return .banana
        case .pineapple:
                return .pineapple
        case .kiwi:
                return .kiwi
        case .mango:
                return .mango
        case .mangoKiwi:
                return .mangoKiwi
            default:
                return nil
            }
        }
``` 이러한 방법으로 값을 받아 `case`각각을 쥬스 `case`로 지정할 수 있네요!! 이런느낌으로 구현하는게 맞을까요 ?

2022-03-04 06:45 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) -> Bool {
```swift
        guard let juice = convertToJuice(sender) else { return }
        do {
            try juiceMaker.makeJuice(juice)
            showSuccessAlert(of: juice)
        } catch {
            showFailureAlert()
        }
        updateFruitStockLabels()
    }
```
조언해주신 대로 진행해보았습니다.
`Bool`타입을 반환해서 사용하는것보다 없이 처리하는게 유연하다는 생각이들고 `Bool`을 굳이 사용하지않고 `error`를 처리할 수 있었던것같네요!!

2022-03-04 07:48 UTC, Quokkaaa commented
@yoo-kie
개굴!! 피드백 주신대로 반영해보았습니다. 
혹시 의도하신 부분과 다르게했다거나 추가의견있으면 팍팍 부탁드릴게요 ㅎㅎ
감사합니다.

2022-03-04 11:12 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        if sender == strawberryBananaJuiceButton {
네! 맞습니다!👍👏 이제 `Juice(rawValue: sender.tag)`와 return되는 값이 동일하게 되었네요? 그럼 `convertToJuice`가 필요할까요?? `orderJuices` 메서드에서 바로 `Juice(rawValue: sender.tag)`를 이용해서 juice를 가져올 수 있지 않을까요?🐸

2022-03-06 14:37 UTC, yoo-kie approved these changes

2022-03-07 12:34 UTC, merged