쥬스 메이커 [STEP 2] Doogie, Malrang
yagom-academy/ios-juice-maker pull request #201
Opened 2022-03-02 03:36 UTC by doogie97

@yoo-kie
안녕하세요 개굴 두 번째 PR 요청드립니다!

고민 & 궁금한 점
1. 이번 프로젝트에서 Modality의 활용 이라는 키워드가 있었는데 Modality방식으로 화면 전환을 할거면 굳이 navigation을 사용해야하나? 라는 의문이 들었습니다.
예를 들어서 Modality방식을 이용하려면 굳이 navigation을 이용하는 것이 아닌 단순히 present만 해주면 된다고 생각했고 navigation을 이용할 거라면 다른 방식으로(push 같은) 전환하는 것이 더 나은 방법이 아닌가? 하는 의문이 있습니다.

2. AlertAction 버튼 글씨 색을 바꾸기 위해서 알아본 결과 setValue를 사용 해서 바꿔 주며 그 메서드에는 forKey라는 매개변수가 있는데 해당 키값이 “titleTextColor”라고 하는데 이 키 값이 어디에 정의가 되어있는지 궁금합니다.

3. 이 프로젝트에서 반영을 한 부분은 아니지만 화면전환시 네비게이션 바에 대한 궁금증
화면 전환을 segue로 하면 네비게이션 바가 자동으로 생성되고 이 바 안에 버튼도 넣고 할 수 있는데 code로 push해서 전환할 경우 네비게이션 바가 생기기는 하나 어떻게 버튼을 추가해야 하는지 궁금합니다.
(일단은 네비게이션 바를 스토리보드에서 직접 추가하고 버튼을 넣어봤는데 이 경우 자동으로 생성되는 뒤로가기 버튼 위에 네비게이션 바를 생성하는 느낌이 들어서 맞는 방법이 아닌것 같다는 생각이 들었습니다.)

2022-03-03 13:56 UTC, yoo-kie requested changes
고민 & 궁금한 점
1. 이번 프로젝트에서 Modality의 활용 이라는 키워드가 있었는데 Modality방식으로 화면 전환을 할거면 굳이 navigation을 사용해야하나? 라는 의문이 들었습니다.
예를 들어서 Modality방식을 이용하려면 굳이 navigation을 이용하는 것이 아닌 단순히 present만 해주면 된다고 생각했고 navigation을 이용할 거라면 다른 방식으로(push 같은) 전환하는 것이 더 나은 방법이 아닌가? 하는 의문이 있습니다.

```
🐸 아 관련해서 저도 커멘트를 남겼는데요! Main 스토리보드를 보니 MainViewController에 navgationController가 embed되어 있지만 활용이 되지는 않더라구요:) 이런 고민이 있으셨군요. 
흠 이번 프로젝트에서는 기능요구사항을 참고하는 것이 중요해보입니다. 두기와 말랑이 고민하셨던 것처럼 어떤 화면전환이 더 나은지 고민해보는 것도 좋습니다! 하지만 이번에는 “재고 수정” 버튼이 네비게이션 바 버튼으로 활용되고 재고수정 화면에서도 “닫기”로 화면 뒤로가기를 구현해줘야 하는데요:) 고려해서 두기와 말랑이 적절한 방식을 구현해주시면 될 것 같습니다.
```

2. AlertAction 버튼 글씨 색을 바꾸기 위해서 알아본 결과 setValue를 사용 해서 바꿔 주며 그 메서드에는 forKey라는 매개변수가 있는데 해당 키값이 “titleTextColor”라고 하는데 이 키 값이 어디에 정의가 되어있는지 궁금합니다.

`🐸 저도 이번에 대략적으로 살펴봤는데요:) UIAlertAction에서 KVC를 활용하여 key “titleTextColor”로 버튼 글씨 색에 접근하는 것으로 파악됩니다. 자세히 살펴보지는 못해서 다음에 디코에서 구현부를 저희가 직접 살펴볼 수 있는지에 대해 같이 논의해보면 좋겠네요!👀 그 전에 제가 말씀드린 내용 관련해서 먼저 살펴보시고 잘못 파악되었거나 더 알게 되신 내용이 있다면 공유부탁드립니다!`

3. 이 프로젝트에서 반영을 한 부분은 아니지만 화면전환시 네비게이션 바에 대한 궁금증
화면 전환을 segue로 하면 네비게이션 바가 자동으로 생성되고 이 바 안에 버튼도 넣고 할 수 있는데 code로 push해서 전환할 경우 네비게이션 바가 생기기는 하나 어떻게 버튼을 추가해야 하는지 궁금합니다.
(일단은 네비게이션 바를 스토리보드에서 직접 추가하고 버튼을 넣어봤는데 이 경우 자동으로 생성되는 뒤로가기 버튼 위에 네비게이션 바를 생성하는 느낌이 들어서 맞는 방법이 아닌것 같다는 생각이 들었습니다.)

`🐸 네비게이션 바에 아이템 버튼을 코드로 추가하는 방법을 질문하신게 맞을까요? 이는 구글링 후 참고하시는게 나을 것 같아요! 검색어로 “navigationBar item 추가”를 추천드립니다!☺️`

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private let juiceMaker = JuiceMaker()
final과 private을 사용해서 프로젝트의 안정성을 높여주셨네요!👍

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +
이 공백은 의미가 있는 공백인가요?

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    @IBOutlet weak var strawberryStockLabel: UILabel!
역할+UI컴포넌트 네이밍 좋습니다:)

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        for (fruit, stock) in  juiceMaker.store.fruitList {
```suggestion
        for (fruit, stock) in juiceMaker.store.fruitList {
```
공백 오타있습니다.🐸

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +
띄어쓰기가 2번 되었네요! 실수이신 것 같지만 라인은 되도록 한번만 띄워주세요!

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        }
action 메서드를 주문버튼만큼 생성하지 않고 참조로 연결하신 점 좋은 활용인 것 같습니다!
여기에서 `makeJuice` 메서드를 반복 생성하지 않을 수 있는 방법이 있을까요? sender(UIButton)의 tag 데이터와 Menu의 rawValue를 활용해보면 어떨까요?

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.present(manageVC, animated: true, completion: nil)
navigationController에서 ManageViewController를 present로 화면전환하셨네요? 모달형태로 present하신 이유가 있을까요? MainViewController에 navigationController가 embed되어 있는 이유도 궁금합니다!

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func presentBasicAlert(title: String?, message: String) {
재사용성이 있는 얼럿 관련 메서드 좋네요!☺️

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        presentBasicAlert(title: nil, message: menu.orderMessage)
메서드 내부에서 바로 다른 메서드를 호출하고 있네요. 그럴 경우 `presentCompleteAlert`를 따로 정의하는 것보다`presentBasicAlert`을 바로 사용하는 것이 더 깔끔할 것 같습니다.

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +
아직 사용되지 않는 뷰컨트롤러라도 (라인 공백 같은) 컨벤션 정리가 필요해보입니다:)

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func makeJuice(menu: Menu) {
오! `makeJuice` 메서드를 MainViewController로 옮기셨네요:)👍 옮기시게 된 이유를 얘기해주실 수 있나요??

2022-03-03 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +                return "딸기 쥬스 나왔습니다! 맛있게 드세요!"
"(쥬스이름) 나왔습니다! 맛있게 드세요!" 형태의 문자열이 중복해서 정의되었네요!
쥬스 이름을 정의하는 프로퍼티를 따로 만들어서 orderMessage에서 "(쥬스이름) 나왔습니다! 맛있게 드세요!"만 return 하는 것은 어떨까요?

2022-03-04 02:21 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +
label과 button을 기능별로 구별하기 위해서 띄워놨습니다.

2022-03-04 02:22 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        for (fruit, stock) in  juiceMaker.store.fruitList {
컨벤션 실수가 많네요 ㅠ

2022-03-04 02:30 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.present(manageVC, animated: true, completion: nil)
일단 최초 프로젝트 상태가 navigationController가 추가 되어 있는 상태였고 navigationController를 이용해 push해서 사용하고자 하였으나 기능요구서에는 모달 형태를 사용하라는 내용이 있어 기존 추가되어있던 navigationController를 이용해보고자 navigationController를 통해 present하게 되었습니다.
그런데 이렇게 모달 형식으로 화면전환을 하게 되면 navigationBar가 생기지 않았고(적어도 저희가 실험해 본 결과로는...) 이러면 스토리 보드에서 navigationBar를 추가해 주어야 하는데 그럼 결국 navigationController를 이용하지 않는 것이어서 navigationController를 제거하기로 했습니다.

2022-03-04 02:36 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func makeJuice(menu: Menu) {
`makeJuice` 의 주 기능은 재고 확인함수가 던지는 에러를 캐치해줘서 상황에 맞는 동작을 하는 함수인데 JuiceMaker안에서 오류 캐치 후 프린트는 문제없이 가능하나 alert창을 띄우는 방법을 찾지 못해 MainViewController로 옮기게 되었습니다.

2022-03-04 03:21 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        presentBasicAlert(title: nil, message: menu.orderMessage)
`Menu`를 매개변수로 받아와야 한다는 생각에 함수를 하나 더 만들어줬는데 애초에 사용되는 부분에서 `Menu`를 받고 있어서 추가적으로 만들어주지 않고 말씀해 주신 대로 `presentBasicAlert`을 바로 사용 해서 작성하였습니다.

2022-03-04 05:39 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        }
말씀해 주신 부분으로 적용을 해보니 반복 생성이 아예 필요없어서 훨씬 깔끔하다고 생각은 했습니다
다만, 이게 과연 가독성을 더 높이는 방법인지에 대해서는 의문이 들기는 합니다. 
물론 이 주문 버튼에서는 크게 지장이 없기는 한데 label에 과일 개수를 표시해 주는 기능을 tag를 이용해 간략화하려고 했을 때는 너무 가독성이 좋지 않다고 생각 해 원래대로 돌아오기는 했습니다만 개굴은 tag사용이 가독성 부분에 있어 어떻게 생각하시는지 궁금합니다.
기존 코드

``` swift
    private func showStock() {
        for (fruit, stock) in juiceMaker.store.fruitList {
            switch fruit {
            case .strawberry:
                self.strawberryStockLabel.text = String(stock)
            case .banana:
                self.bananaStockLabel.text = String(stock)
            case .pineapple:
                self.pineappleStockLabel.text = String(stock)
            case .kiwi:
                self.kiwiStockLabel.text = String(stock)
            case .mango:
                self.mangoStockLabel.text = String(stock)
            }
        }
    }
```
태그 사용 코드
```swift
    private func showStock() {
        for i in 8...12 {
                guard let fruit = Fruits(rawValue: i) else { return }
                let label = self.view.viewWithTag(i) as! UILabel
                label.text = String(juiceMaker.store.fruitList[fruit]!)
        }
```
(태그는 버튼이 1 부터 7까지 사용을 하기에 레이블은  8 부터 12 까지 할당해 준 모습 입니다.)

2022-03-04 13:35 UTC, kinggoguma commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        for (fruit, stock) in  juiceMaker.store.fruitList {
매번 확인하는것 같은데도 놓칩니다 ㅠㅠ

2022-03-04 13:54 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        }
아! viewWithTag 메서드를 활용하셨네요:) 먼저 제안드렸던 경우는 sender를 action 파라미터로 받아 tag를 활용할 수 있는 button이었는데요. label도 tag를 활용하면 좋겠지만 그렇게 되면 위에서 작성하신것처럼 8...12와 같은 button에서는 sender를 통해 받았던 값을 직접 입력해줘야해서 적절하지 않은 방식인 것 같아요.🤔

** 그리고 위에 예시로 작성해주신 코드에서 강제 언래핑(!)은 지양하는 것이 좋습니다!

2022-03-04 13:56 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.present(manageVC, animated: true, completion: nil)
아 기능요구서에 모달 형태를 사용하라고 정의되어 있군요?? 참고하겠습니다☺️

2022-03-04 14:02 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private func makeJuice(menu: Menu) {
말씀해주신 이유도 충분한 설명인 것 같습니다:) 더불어 ViewController에서의 비즈니스 로직 처리를 고민하신 것 같아서 따봉을 남겼습니다!

2022-03-05 10:13 UTC, kinggoguma commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.present(manageVC, animated: true, completion: nil)
기능 요구서에 어떤 것을 사용하라는  언급은 없었으나..!
아래와 같은 문구가 작성되어있어 
Modal 을 활용하라는 뜻으로 이해했습니다..!

**이번 스텝 수행 중 핵심 경험**
-  내비게이션 바 및 바 버튼 아이템의 활용
-  얼럿 컨트롤러 활용
-  Modality의 활용

2022-03-05 10:17 UTC, kinggoguma commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        }
네! 개굴이 말씀해주신 부분은 sender를 action 파라미터로 받아 tag를 활용하여 수정했습니다!
비슷한 방법으로 Label 에서도 사용할수있지않을까 하여 예시 코드를 작성했었습니다!
강제추출은 지양..! 명심하겠습니다!

2022-03-06 14:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +                return "딸기 쥬스 나왔습니다! 맛있게 드세요!"
혹시 이 커멘트는 반영이 된 걸까요?

2022-03-07 03:16 UTC, yoo-kie approved these changes

2022-03-07 12:34 UTC, merged