쥬스메이커 [step3] 우롱차, vayne
yagom-academy/ios-juice-maker pull request #204
Opened 2022-03-07 14:25 UTC by dnwhd0112

@AppleCEO 
안녕하세요 도미닉 이번 PR도 잘 부탁드려요!!!

## 코드를 작성할때 고민했던점

1. JuiceMaker가 struct인대 이걸 싱글톤 처럼 기능을 구현해 놓아서 이게 잘못된건 알겠는대 어떻게 수정해야될지 모르겠습니다... 하...
2. 기능은 작동하는대 이게 잘 구현한건지 잘 모르겠습니다.

2022-03-08 12:47 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.
이번 스텝도 진행하느라 고생하셨습니다!
한 줄이 길어서 이해하기 힘든 경우가 많이 있었습니다.
상수에 할당을 하더라도 여러 줄로 나눠서 읽기 좋게 개선해보면 좋겠습니다~

질문에 대한 대답
JuiceMaker가 struct인대 이걸 싱글톤 처럼 기능을 구현해 놓아서 이게 잘못된건 알겠는대 어떻게 수정해야될지 모르겠습니다... 하...
- 조만간 회의실에서 같이 이야기 나눠봐요~

기능은 작동하는대 이게 잘 구현한건지 잘 모르겠습니다.
- 조금 읽기 어려운 코드들이 많이 있었습니다. 조금 이해하기 좋게 개선해보면 좋겠습니다. 강제 언레핑이 사용되기도 하였는데 강제언레핑은 지양하고 옵셔널 체이닝의 사용도 조금 줄여서 안정적인 프로그램으로 개선해보면 좋겠습니다!

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +            try? JuiceMaker.juiceMaker.getFruitStore().fixStock(fruit: targetFruit, amount: Int(sender.value))
어후.. 이 줄은 너무 길고 복잡하네요.
한 줄에 점(.) 은 하나만 사용하는게 좋다는 의견도 있습니다.
여러 줄로 나눠져도 상수에 할당하는 식으로 이 줄의 길이를 줄여보면 좋겠습니다.

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +        mangoStockLabel.text = String(JuiceMaker.juiceMaker.getFruitStore().getStock(fruit: .mango))
여기도 줄이 너무 기네요. 어떻게 줄여볼 수 있을까요?

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +                vcName?.modalPresentationStyle = .fullScreen
여기서 옵셔널 체이닝을 안 써보면 어떨까요?

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
>                  self.present(vcName!, animated: true, completion: nil)
강제 언레핑은 제거해보면 좋겠습니다!
저는 프로젝트를 진행하면서 강제 언레핑은 전혀 사용하지 않습니다~

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    case strawberry = 1 ,
여기 1 뒤에 공백이 하나 있는데 어떤 의미일까요?
공백 하나에도 의미가 있어야합니다!

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func fixStock(fruit: Fruit, amount: Int) throws {
재고를 고치다로 메소드명이 이해가 가는데요!
조금 더 자세한 메소드명이 있을 것 같아요~ 개선해보면 좋겠습니다

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +    }
닫기라고 읽히는데요. 저는 보통 tapCloseButton 과 같은 형식으로 메소드명을 작성합니다.
더 좋은 메소드명을 고민해보면 좋겠어요~

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +        updateStock()
재고를 업데이트한다라고 읽히는데요.
조금 더 상세한 메소드명 고민해 볼 수 있을까요?

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +    @IBOutlet weak var strawberryStockStepper: UIStepper!
UIStepper 를 사용해보셨군요! 👍

2022-03-08 12:47 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +    @IBOutlet weak var mangoStockLabel: UILabel!
레이블명들이 명확하네요~ 💯

2022-03-09 10:29 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +            try? JuiceMaker.juiceMaker.getFruitStore().fixStock(fruit: targetFruit, amount: Int(sender.value))
fruit store에 접근하기가 너무 긴거 같네요. 변수에 fruitStore을 담아둔 뒤 접근하거나 static으로 fruitStore를 저장해준뒤 접근하는 방식을 생각해보겠습니다.

2022-03-09 10:29 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +        mangoStockLabel.text = String(JuiceMaker.juiceMaker.getFruitStore().getStock(fruit: .mango))
위와 같은 방식으로 접근해야될꺼같아요.

2022-03-09 10:44 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +                vcName?.modalPresentationStyle = .fullScreen
네! 시도해 볼게요!

2022-03-09 10:45 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
>                  self.present(vcName!, animated: true, completion: nil)
넵 ㅎㅎㅎ 지난번에도 말씀해주셨는대 또 썻네요 ㅠ 죄송합니다.

2022-03-09 10:45 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +    case strawberry = 1 ,
아... 고치도록 하겠습니다!

2022-03-09 10:46 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func fixStock(fruit: Fruit, amount: Int) throws {
네! changeStock 로 고치면 좋을꺼 같아요.

2022-03-09 10:46 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +    }
closingTab 정도가 적당한거 같아요.

2022-03-09 10:47 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +        updateStock()
사실 view에 보여줄 재고를 보여주는 식이니까 load stock 정도가 적당하지 않을까 싶네요?

2022-03-09 11:01 UTC, dnwhd0112 commented on JuiceMaker/JuiceMaker/Controller/FruitStockController.swift
> +        updateStock()
재고를 불러와서 label에 담는다는 의미로 loadStockLabel로 고쳐볼려구요.

2022-03-16 03:54 UTC, merged