쥬스 메이커 [STEP 3] Tiana, 마이노
yagom-academy/ios-juice-maker pull request #206
Opened 2022-03-08 06:13 UTC by Mino777

안녕하세요 린생! @jungseungyeo 
STEP 3 PR입니다!
환절기 건강 조심하세요!
잘 부탁드립니다🥰

---

## 구현내용

- **final** **class** CompositionRoot
    - **struct** Dependency: 주입되어야할 의존성 목록을 가지고 있는 구조체
    - **func** resolve(window: UIWindow) -> Dependency: 의존성을 주입하여 Dependency 구조체로 반환해주는 메서드
    - **func** setWindow(dependency: Dependency): 반환된 Dependency로 window에 의존성을 주입해주는 메서드
- **final** **class** FruitStore
    - **func** modify(fruit: Fruit, amount: Int): 파라미터로 전달받은 과일과 개수에 따라 재고를 수정해주는 메서드
- **final** **class** ModifyingStockViewController: UIViewController: 재고 수정 작업을 하는 ViewController
    - **@IBAction** **func** touchUpDismissButton(_ sender: UIButton): 닫기 버튼을 터치했을 때 실행 되는 메서드
    - **@IBAction** **func** touchUpStepper(_ sender: UIStepper): Stepper를 터치했을 때 실행 되는 메서드
    - **static** **func** instance(fruitStore: FruitStore) -> ModifyingStockViewController: 의존성 주입 및 ViewController 생성을 위한 타입 메서드
    - **private** **func** updateUI(): UI 업데이트에 대한 에러 핸들링 처리를 해주는 메서드
    - **private** **func** configureStockUI() **throws: stockUIComponent**를 Fruit에 매칭시켜 현재 해당 과일에 대한 재고를 label과 stepper에 할당해주는 메서드
    - **private** **func** findStockUIComponent(of fruit: Fruit) -> (UILabel, UIStepper): label과 stepper에 Fruit을 매칭 시키고, 매칭된 label과 stepper를 반환해주는 메서드
    - **private** **func** modifyFruitStock(stepper: UIStepper) **throws:** updateFruitStock 메서드를 stepper와 매칭 시켜주는 메서드
    - **private** **func** updateFruitStock(fruit: Fruit, stepper: UIStepper): 해당 stepper의 값에 따라 원본 과일 재고를 수정해주는 메서드

---

## 고민한 점

- naming
- composition root
    - 자료를 찾기가 너무 어려웠습니다😭
    - 저희가 찾아본바로는, DIContainer를 활용하는 방법과 Container를 사용하지않고 바로 주입해주는 Pure DI가 있었고, 우선 조금 더 오래된 개념부터 진행을 해보고자 Pure DI로 흉내를 내보았습니다.
    - entry point에서 의존성 트리를 만들어서 한 곳에서 모든 의존성을 주입하는 것이라고 이해했습니다. 주입이 필요한 것들을 구조체로 생성하고 resolve()에서 각 인스턴스에 적합한 값을 주입하였습니다. 사실 저희가 잘한지 못한지도 잘 판단이 되지 않는 정도이어서 해당 부분 피드백 자세하게 부탁드리겠습니다!
- 강한 참조 순환
    - AlertBuilder의 프로퍼티가 클래스이므로 weak을 통해 강한 참조 순환 문제가 발생하지 않도록 수정했습니다.
    - AlertBuilder에서 @escaping closure를 사용하는 부분에 [weak self]처리를 진행하면 handler가 처리 되기전에 self의 메모리가 해제되버려서 정상적으로 동작하지 않습니다. 테스트를 해보니, showAlert이 마지막으로 호출된 후에, 알럿이 화면에 띄워지면 AlertBuilder가 nil처리가 되어서 그런거 같은데, 이런식으로 동작하는 정확한 이유가 궁금합니다! 그리고 @escaping closure를 사용하는 경우 [weak self]를 꼭 사용해야 한다고 생각을 해왔는데, 이러한 경우에 weak 처리를 안해도 문제가 없는 지도 궁금합니다!
    
    ```swift
    func setConfirmHandler(_ confirmHandler: @escaping (() -> Void)) -> AlertBuilder {
            product.confirmHandler = confirmHandler
            return self
     }
    
    func showAlert() {
            let alert = UIAlertController(title: product.title, message: product.message, preferredStyle: .alert)
        				...
    	    let confirmButton = UIAlertAction(title: product.confirmTitle, style: .default, handler: { _ in
    		  // 해당 부분에서 [weak self]로 진행했을 경우 핸들러를 처리하기 전에 self가 nil이 되어서 동작하지 않습니다.
                  self.product.confirmHandler?()
            })
    				...
    }
    ```
    
- 중복 구현 지양
    - ModifyingStockViewContoller에서 `configureStockUI()`, `match(stockUIComponent: [(label: UILabel, stepper: UIStepper)], with fruits: [Fruit])`, `findstockUIComponent(of fruit: Fruit) -> (UILabel, UIStepper)` 메서드의 매개변수로 튜플 타입을 사용해서 중복 구현을 개선했습니다.
- 비슷한 구조로 구현
    - JuiceMakerViewController에서 정의한 메서드 3개 (`configureStockLabels()`, `match(amountLabels: [UILabel], with fruits: [Fruit])`, `findStockLabel(of fruit: Fruit) -> UILabel`) 와 유사한 기능 구현이  ModifyingStockViewController에서도 필요해서 비슷한 형태로 구현했습니다.
- 액션 메서드
    - `touchUpDismissButton(_ sender: UIButton)` 가 연결된 UI가 BarButton인데, 매개변수로 UIButton을 해도 잘 동작합니다. 상속관계가 아님에도 기능상 문제가 없는 이유가 궁급합니다.
- 옵셔널 프로퍼티
    - JuiceMakerViewController에서 init을 통한 프로퍼티 초기화가 되지 않아서 타입 메서드로 초기화를 했습니다. 그러면, 프로퍼티를 옵셔널로 가져야만 하는데요, 논리상으로 프로퍼티는 옵셔널이 아닌게 좋을 것 같은데 현 구현 상태에서 옵셔널을 제거하는 방법이 궁금합니다.

2022-03-09 02:04 UTC, jungseungyeo requested changes
1. composition root

`자료를 찾기가 어렵죠? ㅎㅎ 저도 구현을 요청하면서 잘 할 수 있을까? 이런 생각을 하면서 요구를 하였습니다. 그래도 너무 잘 만들어주셨어요. Pure Di를 참고 하셨지만 SwInject를 많이 사용하는 것으로 알고 있어요. 이 것은 처음 sceneDelegate에서부터 시작하여 하위객체로 자신을 넘겨주어야해요. 아니면 전역적으로 접근이 가능한 static func으로 사용해요. 이건 좀 설명이 필요할 수도 있을거 같아요. 혹시 시간 괜찮은 시간 알려주시면 잠시 이야기 나눠봐요 충분히 이정도면 좋지만 싱글톤만 해결해주세요 `

2. 강한 참조 순환

`escaping closure를 사용 할 때 무조건 weak self를 붙어주어야 한다는 생각은 잘 못 된 생각이예요.  내부적으로 closure를 사용하면 캡쳐가 되어 순환참조가 되어 메모리 릭이 발생 할 수 있는 거는 사실입니다. `

![image](https://user-images.githubusercontent.com/32052386/157356573-88b133b2-b686-4ce2-bea0-b392fb6c31af.png)

![image](https://user-images.githubusercontent.com/32052386/157356645-26cb77bb-f48b-4617-8c34-5165a2de4ea1.png)

```
두 그림의 차이점은 AlertBuilder를 사용하고 메모리 해지가 언제 되냐의 따라 다른거를 보여주고 있어요. 
첫 그림은 티아나와 마이노가 작업한 방식으로 하였고, 두번 째 그림을 전역변수로 AlertBuilder를 두고 사용했습니다. 

잘 전달이 되었는지 모르겠네요 ㅎㅎ
무조건 사용해도 된다 안된다가 아니라 내부 클로져를 사용하여 메모리 릭이 난다면 weak와 같은 약한 참조를 사용해야 되고 순환참조가 안된다면 사용 self. 이렇게 사용해도 좋습니다. 

제가 추천하는 방식은 함수내에서 바로바로 생성해서 사용하는 방식이 아닌 전역 변수로 두고 클로져를 weak로 사용하는 방식을 추천드려요. 이것이 코드의 가독성을 좋게 하는 거 같아요.
```

3. 액션 메서드

`저는 이렇게 사용하는 방법도 문제가 없다고 생각해요`

4. 옵셔널 프로퍼티

`JuiceMaker를 외부에서 주입 받기 때문에 옵셔널이 아닌 !를 사용해서 옵셔널을 해지 하는 것이 좋지 않나는 질문이거 같아요. 아니면 옵셔널하지 않게 구현하는게 좋지 않을까? 라는 질문이거 같기도 하구요. 

맞아요. 옵셔널을 제고 할 수 있으면 제거하는게 좋죠 이 객체를 들어올때 외부에서 무조건 주입이 필요한 프로퍼티이면 옵셔널이면 안돼요. 이것이 없는 경우가 있다는 것을 개발자들이 혼돈 할 수 있기 때문이죠. init()에서 주입을 해주고 외부에서는 static instance함수로 생성하면 좋을거같아요.`

티아나, 마이노 정말 고생하셨어요. 내부적으로 모든 구현도 거의 완벽하네요 코멘트로 남겨 둔 부분만 수정해서 pr 보내주세요 ㅎㅎ 고생많으셨습니다

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Application/CompositionRoot.swift
> +    static let shared = CompositionRoot()
싱글톤을 사용한 이유가 있나요? static 객체는 어떤가요?

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Application/SceneDelegate.swift
> +        let compositionRoot = CompositionRoot.shared
싱글톤은 안사용하는 방향이 좋은거같아요

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Common/Extension/UIViewController.swift
> +        return String(describing: self)
이렇게 사용하는거 너무 좋네요

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/AlertBuilder/AlertBuilder.swift
> +    private weak var viewController: UIViewController?
좋습니다 :)

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/ModifyingStockViewController.swift
> +    @IBAction func touchUpDismissButton(_ sender: UIButton) {
네이밍 좋네요 ㅎㅎ

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/ModifyingStockViewController.swift
> +    static func instance(fruitStore: FruitStore) -> ModifyingStockViewController {
인스터스 생성하는거 좋네요

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Application/AppDelegate.swift
> -
코드 정리하는 모습 너무 좋아요 사소한거 하나하나가 코드를 대하는 태도를 보여주는거 같아요 나중에 사전과제 같은 것을 할 경우 코드를 정리 해서 주면 채점자 입장에서 정말 기분이 좋습니다:)

2022-03-09 02:04 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Application/CompositionRoot.swift
> +    static let shared = CompositionRoot()
전역적으로 주입을 해줄려고 하다보니 싱글톤을 생각했던거 같아요. 제가 요구하는 내용이 자료가 많이 없긴하죠 ㅎㅎ 

많은 어려움이 있었을텐데 정말 잘 만들어주셨어요. CompostionRoot 사용 가져갈 수 있는 장점은 상위에서 하위로 모듈을 주입이 가능하다는 겁니다. 이게 왜 장점인지 의문이 들수 있지만 새로 생성하지 않고 상위가 하위로 주입을 계속해주면 하나의 객체가 계속 주입을 해주기 때문에 싱글톤이 아니지만 싱글톤과 같은 효과를 가져 갈 수 있어요

이런것을 지원하는 라이브러리로는 [Swinject](https://github.com/Swinject/Swinject)와 리드미에 적어주신 [Pure](https://github.com/devxoul/Pure)가 있습니다. 

이런 이유에서 CompositionRoot는 싱글톤이면 안될거 같아요 혹시 궁금한 점이 있으면 질문해주세요 :)

2022-03-10 01:29 UTC, Mino777 commented
안녕하세요 린생! @jungseungyeo 
1차 피드백 반영 해보았습니다!
감사합니다!

---

1. Composition Root Refactoring
- 싱글톤을 사용하는 대신에, 프로토콜을 활용하여 싱글톤을 쓰지 않고 싱글톤의 효과를 낼 수 있도록 수정 해보았습니다.

2. AlertBuilder 전역변수 설정
- 린생께서 알려주신 프로토콜을 활용하는 방식을 이해하지 못해서 혹시 한번만 더 설명 부탁드려도 될까요?🥺
- 우선 UIViewController를 확장해서 진행을 해보았습니다.  

---

3주동안 바쁘신데도 정성어린 리뷰 해주셔서 정말 감사드립니다!
린생 덕분에 의존성 주입, 프로토콜의 활용, 디자인 패턴의 중요성을 정말 많이 느끼게 되었습니다!
감사합니다!🥰

2022-03-11 11:01 UTC, jungseungyeo approved these changes
마이노, 티아나 3주라는 시간을 벌써지났네요. 

처음 두분의 리뷰어가 되어서 너무 좋습니다. 제가 요심을 가지고 요구하는 내용을 너무 잘 해주셔서 너무나 감사합니다. 
질문을 주신 내용을 답변을 드리겠습니다.

Composition Root는 앞으로 두분이 잘 해주신 DI 구조를 만들다 보면 언제가는 반드시 시도하게 될 객체라고 생각이 들어서 도전을 해주실길 원했습니다. 정말 잘 만들어주셨습니다.

질문의 주신 AlertBuilder는 다음에 시간을 잡고 이야기 나누면 좋을거같네요. 

이 pr은 머지하겟습니다. 너무 고생하셨습니다.

2022-03-11 11:01 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Application/SceneDelegate.swift
> +        self.compositionRoot = CompositionRoot()
여기보다 `func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions)`에서 생성해주세요 sceneDelegate를 오버라이드하면 애플이 init 시점에 무슨일을 하는지 모르기 때문에 알 수 없는 오류를 초래할수도 있어요.

2022-03-11 11:01 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        alertBuilder
너무 좋습니다. alertBuilder의 소유권이 누구에게 있는지 판단하면서 작성하는 습관이 좋습니다.

2022-03-11 11:01 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +protocol Observer: AnyObject {
너무 좋습니다.

2022-03-11 11:01 UTC, jungseungyeo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private weak var observer: Observer?
weak를 붙여주니 너무 좋습니다.

2022-03-11 11:01 UTC, merged