쥬스 메이커 [STEP 3] OneTool, 두두
yagom-academy/ios-juice-maker pull request #210
Opened 2022-03-08 11:12 UTC by FirstDo

@1Consumption
안녕하세요 올라프! ☃️
onetool, 두두 입니다!
쥬스 메이커 맥북 침수 이슈 🌊로 인해 STEP 3를 약속드린 시간🕰 보다 늦게 완료하여 PR 보냅니다 ㅠㅠ 😪
마지막 리뷰 잘부탁드립니다!! :)

### 구현내용
---
`findStepper()` : fruit에 맞는 stepper를 찾는 함수   
`findLabel()` : fruit에 맞는 label을 찾는 함수  
`initalizeData()` : 두번째 VC의 데이터들을 초기화 해주기 위한 함수  
`initalizeViewController()` : 두번째 VC의 속성들을 초기화 해주기 위한 함수  
`dismissVC()` : 두번째 VC를 dismiss해주는 함수  
`didTapStockEditStepper()` : Stepper가 눌릴때마다 호출되는 함수  
`findFruit()` : stepper에 맞는 과일을 찾는 함수  
`UpdateDeglate protocol` : StockViewController의 값을 JuiceMakerController로 업데이트 시켜주는 프로토콜  
`update()` : 두 번째 view를 업데이트 해서 첫 번째 view로 업데이트 해주는 함수  
`makeButtonTiltleDynamic()` : 주문 버튼의 title을 dynamic size가 가능하도록 해주는 함수  
`changeStock()` : 변경된 값만큼, 재고를 업데이트 해주는 함수  

### ❗️고민한 점 & 궁금한점

1. 데이터 전달방법은 크게 네가지가 있다고 생각했습니다

    - 싱글톤을 이용하는 방법
    - notificationcenter을 이용하는 방법
    - delegate를 사용하는 방법
    - JuiceMaker 구조체 자체를 넘겨버리는 방법
    
> 싱글톤은 굳이 사용해서 결합도를 높힐 필요가 없다고 생각했습니다.

> notificationcenter도 말씀해주신 것처럼 코드 점핑이 있고, 무엇보다 디버깅이 어렵다는 단점이 있어서 사용하지 않았습니다.

> juiceMaker 구조체 자체를 넘기는 방법도 있는데, 해당 방법에 대해서 얘기를 나눠봤습니다.
delegate를 사용해 보고 싶어서 해당 방법을 채택하지 않았습니다

> 그런데, 해당 방법을 사용하면, 데이터 전달 코드가 필요없고, 두 곳 모두에서 stock을 변경하는 함수를 호출할 수 있어서 매우 간단하게 구현할 수 있더라고요.
이런 방법이 문제가 되는지 궁금합니다..!! 

2. 작은 디바이스에서는 주문 버튼의 title이 cliping되길래 , button의 title에 adjustsFontSizeToFitWidht, minimumScaleFactor 를 사용해서 조절이 되게 했는데, 이렇게 해버리니 cliping은 안되는데, 버튼마다 모두 사이즈가 달라서 조금 어색합니다. 더 좋은 방법이 있을까요?

3. 재고 처리 화면에서, 여러 디바이스 크기에 대응하기 위해서 큰 stackView의 spcaing을 최소로 하였습니다. 그런데, pro max와 같은 큰 화면에서는 spacing을 넉넉하게 주고 싶고, ipod touch 7세대 같은 좁은 화면에서는 spacing을 촘촘하게 하는 식으로 구현하고 싶은데, 해당 방법이 뭘까요? 또, Stepper의 사이즈를 조절할 수 있는지 궁금합니다
  
4. viewDidLoad에서 초기화때 실행될 함수들을 호출하는 식으로 초기화 했는데, 일반적으로 그런 함수들 이름짓는 방법이 있을까요?

- `initalizeViewController`
- `initalizeData`
- `makeButtonTitleDynamic`
- `updateMultipleLabel`

이런식으로 네이밍했는데, 적절치 못한것 같습니다..ㅠㅠ
보통 어떤식의 네이밍을 사용하나요?

5. makeFruitAmountChangedDictionary 네이밍이 길기도 하고, makeFruitAmountChangedDictionary함수는 아래와 같은 역할을 하는데 올라프라면 어떻게 지으실 것 같나요?

> StockViewController에 처음들어올때 재고를 stock에 저장하고, stepper의 값을 그때의 값으로 설정해 줍니다
그리고 StockViewController를 dismiss하기 전에, 처음값과 비교해서 얼마나 증감되었는지를 JuiceMakerViewController에 전달하기 위해서 [Fruit: Int] 를 만드는 함수입니다

```
ex) 초기값이 딸기 = 4개라면

딸기초기값 = 4
stepper.value = 4

로 초기화

stepper '+' 를 세번 눌렀다면

dismiss하기전에
딸기의 증감량을 구해야 하므로, 7 - 4 = 3
[딸기: 3] 이런 딕셔너리를 만드는 함수입니다
```

6. 유지보수 측면에서 불리하다고 생각하여 tag를 쓰지 않았는데, button, label, stepper를 tag를 쓰고, fruit과 juice의 rawValue를 1,2,3,4,5 이런식으로 정해서 둘이 매칭되게 하면 코드가 훨씬 간결해질것 같습니다.  
올라프의 생각이 궁금합니다. 그리고 혹시 실제로 tag를 어디에 쓰는 편인지 궁금합니다!!

2022-03-10 09:35 UTC, FirstDo commented
추가로 delegate와 RC에 대해서 질문이 있습니다!
delegate를 weak으로 써주는 이유는 순환참조 오류를 방지하기 위함이라고 알고 있습니다.


JuiceMakerController를 JuiceVC, StockViewController를 StockVC라고 지칭하겠습니다
- 최초에 JuiceVC가 메모리에 올라가고 `JuiceVC의 RC = 1, StockVC의 RC = 0`
- JuiceVC에서 StockVC를 present하기 때문에 'JuiceVC의 RC = 1, StockVC의 RC = 1'
- StockVC.delegate = self(JuiceVC) 를 하기 때문에 'JuiceVC의 RC = 2, StockVC의 RC = 1'

이 상황이 되면, JuiceVC와 StockVC가 서로를 가르키고 있기 때문에, JuiceVC가 정상적으로 메모리에서 해제되지 않는다고 생각을 했습니다.  
한번 확인해 보고자 테스트를 해봤는데

ex) DummyVC -> JuiceVC -> StockVC 의 구조
delegate에 weak을 쓰나 안쓰나, JuiceVC, StockVC의 deinit이 모두 정상적으로 호출되는 것을 확인했습니다.
delegate를 strong으로 하면 순환참조 오류가 일어나는것이 아니었나요..?  
어느부분을 놓치고 있는지 궁금합니다..!!

2022-03-10 14:11 UTC, 1Consumption requested changes
고생하셨습니다 두두 원툴! 👍👍 

코드가 전체적으로 깔끔해서 보기 좋았어요.
하지만 아쉬운점이 조금 있긴 해서 코멘트로 남기긴했어요.

아래는 고민한 점에대한 제 코멘트 입니다!

-----------------------------------------

### ❗️고민한 점 & 궁금한점
> 그런데, 해당 방법을 사용하면, 데이터 전달 코드가 필요없고, 두 곳 모두에서 stock을 변경하는 함수를 호출할 수 있어서 매우 간단하게 구현할 수 있더라고요.
이런 방법이 문제가 되는지 궁금합니다..!! 

구조체를 넘겼다는 뜻인가요? 사실 이 질문이 잘 이해되지 않아서... 디코에서 얘기를 해보도록하죠.

> 작은 디바이스에서는 주문 버튼의 title이 cliping되길래 , button의 title에 adjustsFontSizeToFitWidht, minimumScaleFactor 를 사용해서 조절이 되게 했는데, 이렇게 해버리니 cliping은 안되는데, 버튼마다 모두 사이즈가 달라서 조금 어색합니다. 더 좋은 방법이 있을까요?

글쎄요... 이부분은 어쩔수없다고 생각이됩니다. 보통 모든 디바이스를 신경쓰기는 어렵고, 주요 디바이스 리스트를 뽑고 해당 디바이스에서 잘 나오는지를 지키는 편이긴해요.

> 재고 처리 화면에서, 여러 디바이스 크기에 대응하기 위해서 큰 stackView의 spcaing을 최소로 하였습니다. 그런데, pro max와 같은 큰 화면에서는 spacing을 넉넉하게 주고 싶고, ipod touch 7세대 같은 좁은 화면에서는 spacing을 촘촘하게 하는 식으로 구현하고 싶은데, 해당 방법이 뭘까요? 또, Stepper의 사이즈를 조절할 수 있는지 궁금합니다

음... `UIScreen` 객체에서 디바이스의 크기를 받아올 수 있어요. 이 크기를 기반으로 spacing 값을 변경해주면 될거같긴한데, 오버헤드가 조금 있을거같아요. 이런 경우는 `무조건 지원해야겠다`가 아니라 위에 말한거처럼 주요 디바이스인지, 유지보수는 어떤지를 판단해서 행하는게 좋아보입니다.
  
> viewDidLoad에서 초기화때 실행될 함수들을 호출하는 식으로 초기화 했는데, 일반적으로 그런 함수들 이름짓는 방법이 있을까요?
- `initalizeViewController`
- `initalizeData`
- `makeButtonTitleDynamic`
- `updateMultipleLabel`
이런식으로 네이밍했는데, 적절치 못한것 같습니다..ㅠㅠ
보통 어떤식의 네이밍을 사용하나요?

저는 `initialize~` 는 정말로 객체를 초기화할 때 사용하고, 뭔가를 세팅하는 과정은 `setUp~` 을 사용합니다. 또한 레이블의 텍스트를 바꾸는 용도라면 `update~`도 좋아보여요. 다만 `make~`는 개체를 만들어서 반환해줄 때 사용하는 편입니다.

> makeFruitAmountChangedDictionary 네이밍이 길기도 하고, makeFruitAmountChangedDictionary함수는 아래와 같은 역할을 하는데 올라프라면 어떻게 지으실 것 같나요?
StockViewController에 처음들어올때 재고를 stock에 저장하고, stepper의 값을 그때의 값으로 설정해 줍니다
그리고 StockViewController를 dismiss하기 전에, 처음값과 비교해서 얼마나 증감되었는지를 JuiceMakerViewController에 전달하기 위해서 [Fruit: Int] 를 만드는 함수입니다

저는 메소드의 동작을 나타내기위해 네이밍이 어느정도 길어지는건 괜찮다고 봐요. 다만 Dictionary같이 타입이 들어가는건 지양하는 편입니다. 이미 반환형으로 타입이 정의되어있으니까요.

> 유지보수 측면에서 불리하다고 생각하여 tag를 쓰지 않았는데, button, label, stepper를 tag를 쓰고, fruit과 juice의 rawValue를 1,2,3,4,5 이런식으로 정해서 둘이 매칭되게 하면 코드가 훨씬 간결해질것 같습니다.  
올라프의 생각이 궁금합니다. 그리고 혹시 실제로 tag를 어디에 쓰는 편인지 궁금합니다!!

저는 절대로 사용하지 않아요. 오히려 지금 사용해주신 방식이 코드를 읽기도 좋았고 유지보수 측면에서도 좋다고 생각했습니다.

``` swift 
if tag == 0 {
    //...
} else if tag == 1 {
    //...
} else if tag == 2 {
    //...
}
//...

if buttonType == .apple {
    //...
} else if buttonType == .mango {
    //...
} else if buttonType == .strawberry {
    //...
}
//...
```

위 두 코드 중 어떤게 더 알아보기 쉬운가요? 그리고 코드를 처음 보는 사람이 이해하기 좋을까요?

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +    }
make~ 는 뭔가를 만들어서 반환해야할거 같은데, apply는 어떨까요?

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +}
UpdateDelegate 라는 네이밍이 조금 어색한데요, `누군가의 일을 대신해준다.` 라는 관점에서 네이밍을 해보면 어떨까요?

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        updateMultipleLabel(of: fruits)
고차함수를 사용하셨군요! 고차함수를 사용하면서 어떤 점이 좋았나요?

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    static let identifier = "StockViewController"
이거 아주 좋네요ㅎㅎ 혹시 extension을 이용해 얘를 빼줄 수 있을까요?

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    @IBOutlet weak private var mangoStepper: UIStepper!
와! private을 붙이셨군요. 이 프로퍼티들은 외부에서 몰라도 되니까요👍 
추가적으로 강제 언래핑도 없애보는건 어떨까요?

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        navigationItem.rightBarButtonItem = closeButton
뷰컨 자체를 init하는 메소드인가요? 아니면 뷰컨의 subview들을 설정하는 곳인가요? 이름이 이상해요.

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    }
음.. 여기도 위 코멘트와 동일합니다.

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    }
VC는 약어네요. 네이밍에 약어는 지양해주세요. 혹시나 다른 해석이 생길수도 있습니다.

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> -                                <nil key="highlightedColor"/>
이부분은 변경사항이 너무 길어서 조금만 표시할게요. 어떤 오토레이아웃을 수정했다는건가요?

2022-03-10 14:11 UTC, 1Consumption commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    private let stock: [Fruit: Int]
var로 선언하고 얘 자체의 값을 바꾸고, delegate로 전달하면 어떨까요

2022-03-11 09:57 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +    }
말씀대로 setUpButtonTitleDynamic 로 변경하였습니다 :)

2022-03-11 10:00 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    }
setUpData로 변경하였습니다 :)

2022-03-11 10:00 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +        navigationItem.rightBarButtonItem = closeButton
역할이 다르다고 생각하여 setUpTitle과, setUpRightBarButton로 분리했습니다 :)

2022-03-11 10:02 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    }
dismissViewController로 변경했습니다

2022-03-11 10:05 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +}
재고 수정을 대신해준다고 생각하여 StockUpdateDelegate로 변경하였습니다

2022-03-11 10:14 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerController.swift
> +        updateMultipleLabel(of: fruits)
많은 기능들을 한 줄로 사용할 수 있다는 점이 정말 편하고 좋았습니다 :)

2022-03-11 10:31 UTC, kimt4580 commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    static let identifier = "StockViewController"
Extension 폴더를 생성해서, `UIViewController+Extension` Swift 파일을 생성하여 UIViewController를 Extenstion 해서 
```swift
extension UIViewController {
    static var identifier: String {
        return String(describing: self)
    }
}
```  
`StockViewController.identifier` 이런식으로 사용했습니다.

2022-03-11 10:34 UTC, FirstDo commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> -                                <nil key="highlightedColor"/>
스토리보드로 고칠때에도, 확실히 나눠서 하겠습니다.. 
근데 스토리보드로 할때 커밋을 딱딱 나누는건 너무 어려운거 같습니다 ㅠㅠ 눈에 안보여서

2022-03-11 10:40 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    @IBOutlet weak private var mangoStepper: UIStepper!
싹다 !로 바꿨습니다

2022-03-11 10:47 UTC, FirstDo commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +    private let stock: [Fruit: Int]
기존 JuiceMaker의 함수를 활용하려고, 일부로 차이를 구했습니다.

딸기쥬스를 만들때, 딸기 -9
딸기 재고를 +3 했을때

를 모두 동일한 함수에서 처리하고자 하였습니다

2022-03-15 01:53 UTC, merged