쥬스메이커 [STEP 3] 쿼카, Donnie
yagom-academy/ios-juice-maker pull request #212
Opened 2022-03-08 14:16 UTC by Quokkaaa

@yoo-kie 
개굴!! 🐸  
마지막 리뷰를 받게되네요..ㅠㅠ
그저 아쉬울따름...입니다  😭😭 
목표시간보다 늦었지만 열과 성을 다했습니다.
리뷰 잘 부탁드릴게요 👍👍 

# 고민했던점
> - 버튼 생성 및 오토레이아웃 코드로 구현하는 방법에대해 고민하였습니다.
> - 화면전환시 데이터 공유 방법
>    * 첫번째 뷰에서 두번째 뷰로 데이터를 전달하는 방법으로 프로퍼티값 전달방식을 시도해 보았습니다. 처음에는 과일당 한가지의 프로퍼티를만들어 전달해보았으나 코드가 길어지는점이 발생하는것같아 `Array`로 값을 전달해주었습니다. 추가로 `delegate`나 `Notification`을 사용한 방식으로 시도는 해보았으나 두번째뷰의 인스턴스들이 로드가 되지않았는지 전달하는게 쉽지않았습니다. 구글링을 해보아도 대부분은 두번째뷰에서 첫번째뷰로 돌아올때 `Notification`이나 `Delegate`방식을 사용하는것을 보고 이 두가지방법은 돌아올때 데이터 전달을 할 수 있는건가? 라는 궁금증도 생겼습니다.
>    * 객체지향프로그래밍 방식에 가까운 `Delegate`방식을 시도하였습니다. 프로토콜을 사용하여 대리자를 선택하여 위임하는 방식이 재사용성에 좋다는 장점과 `Notification`으로 구현했을때보다는 `Delegate`패턴이 덜 복잡한부분 있어 이 방식을 선택하였습니다.

> - `Stepper`구현시 각각의 `Action`함수로 조정해주면 코드중복이 발생하기도하고 `Stepper`인스턴스를 생성시에도 `collection`으로 생성할 수 있는걸 확인하여 `collection`으로 시도해 볼 수 있겠다고 판단되었습니다.
이전에 사용했던 `tag`를 `index`로 사용해 과일의 순서와 `stepper`의 순서를 동일시하여 구현해보았는데 약간 걸렸던점이 있었습니다. `Label`이나 `button`이나 열거형의 `rawValue`를 지정할때 대부분 `1`로 시작하였는데 `stepper`는 인덱스로 활용해야하다보니 이부분만 `0`을 시작점으로 잡아주었는데 `1`로 시작점을 잡게되면 `tag - 1`를 해줌으로써 인덱스를 구현해야하다보니 하드코딩이 발생하는점에서 전자를 선택했습니다. 
이 부분에 대해서 개굴의 의견은 어떤지 궁금합니다. `0`을 시작점으로 가는게좋을지 아니면 `1`로하고 `-1`을 더해주는게 좋을지 아니면 다른방법이 있을지 조언부탁드립니다.

# 조언을 얻고 싶은점
> - 빌더 패턴을 사용한 얼럿에 대해서 간단한 시연을 볼 수 있을까요?
> - 데이터전달하는 방법 중에서 첫번째뷰에서 두번째뷰로 데이터전달을 하고자할때 `delegate`와 `Notification` 시도해봤던결과 데이터 전달이 안되었었는데 이유가 두번째뷰가 아직 로드되지 않았기 때문에 데이터를 전달할 수 없었던것같았습니다. 하지만 저의가 사용했떤 프로퍼티로 값 전달은 할 수 있었던것같아서 약간 혼란스럽습니다. 혹시 이 차이점에대한 설명과 첫번째뷰에서 두번째뷰로 데이터전달을 할 수 있는 추가적인 방법이 있을지 조언을 얻고 싶습니다.
> - `button`이나 `label`프로퍼티를 생성하여 `= {}` 클로저를 열어 기능을 추가해주고 오토레이아웃을 `setConstraintUI`라는 메서드내에 다 구현을 해주었는데 가독성에 문제는 없는지 궁금합니다.

# 문제해결
> - 두번째뷰인 재고 추가를 한 과일 데이터들을 첫번째뷰로 가져왔을때 까지는 데이터 전달이 잘 이루어졌는데 다시 쥬스주문버튼을 눌렀을때 과일데이터가 재고 추가하기이전의 데이터로 계산이되어 `FruitStore`내에 `updateStock`이라는 메서드를 생성하여 재고를 업데이트해주는 기능을 추가하였습니다.

# 해결하지못한점
> - `Stepper`의 액션이벤트와 연동되어 있는 레이블의 `width`가, 숫자가 바뀌면 미세하게 움직이는걸 고정시키고자 하였는데 해결하지 못하였습니다. 그냥 레이블의 `width`를 넓히면 해결되는 문제일까요?
> - 재고 수정 화면에서 `Stepper`의 액션이벤트를 주게 되면 현재의 값에서 값이 `+=, -=` 되는 것이 아니라 2에서 부터 시작하는 모습을 볼 수 있습니다. 왜 이런 현상이 일어나는 걸까요?
> - 개굴이 조언해주었던 빌더 패턴으로 얼럿을 구성해 보고자 하였는데 아직 학습이 부족하여 기존의 코드로 사용하게 되었습니다. 시간이 주어진다면 살짝 맛만 볼 수 있는 경험을 해봤으면 좋겠습니다.

2022-03-09 17:10 UTC, yoo-kie requested changes
# 고민했던점
> - 버튼 생성 및 오토레이아웃 코드로 구현하는 방법에대해 고민하였습니다.

`👏👏👏👏`

> - 화면전환시 데이터 공유 방법
>    * 첫번째 뷰에서 두번째 뷰로 데이터를 전달하는 방법으로 프로퍼티값 전달방식을 시도해 보았습니다. 처음에는 과일당 한가지의 프로퍼티를만들어 전달해보았으나 코드가 길어지는점이 발생하는것같아 `Array`로 값을 전달해주었습니다. 추가로 `delegate`나 `Notification`을 사용한 방식으로 시도는 해보았으나 두번째뷰의 인스턴스들이 로드가 되지않았는지 전달하는게 쉽지않았습니다. 구글링을 해보아도 대부분은 두번째뷰에서 첫번째뷰로 돌아올때 `Notification`이나 `Delegate`방식을 사용하는것을 보고 이 두가지방법은 돌아올때 데이터 전달을 할 수 있는건가? 라는 궁금증도 생겼습니다.
>    * 객체지향프로그래밍 방식에 가까운 `Delegate`방식을 시도하였습니다. 프로토콜을 사용하여 대리자를 선택하여 위임하는 방식이 재사용성에 좋다는 장점과 `Notification`으로 구현했을때보다는 `Delegate`패턴이 덜 복잡한부분 있어 이 방식을 선택하였습니다.

`넵 말씀하신대로 Delegate와 Notification은 이벤트가 실행될 수 있는 객체(인스턴스)가 존재해야 합니다. PR에서 Delegate 패턴 활용 잘하셨더라구요! 그런데 delegate 프로퍼티를 주입해줄 때 retain cycle로 메모리 누수가 발생할 수 있는 위험이 있기 때문에 weak 활용을 찾아보셨으면 좋겠습니다.`

> - `Stepper`구현시 각각의 `Action`함수로 조정해주면 코드중복이 발생하기도하고 `Stepper`인스턴스를 생성시에도 `collection`으로 생성할 수 있는걸 확인하여 `collection`으로 시도해 볼 수 있겠다고 판단되었습니다.
이전에 사용했던 `tag`를 `index`로 사용해 과일의 순서와 `stepper`의 순서를 동일시하여 구현해보았는데 약간 걸렸던점이 있었습니다. `Label`이나 `button`이나 열거형의 `rawValue`를 지정할때 대부분 `1`로 시작하였는데 `stepper`는 인덱스로 활용해야하다보니 이부분만 `0`을 시작점으로 잡아주었는데 `1`로 시작점을 잡게되면 `tag - 1`를 해줌으로써 인덱스를 구현해야하다보니 하드코딩이 발생하는점에서 전자를 선택했습니다. 
이 부분에 대해서 개굴의 의견은 어떤지 궁금합니다. `0`을 시작점으로 가는게좋을지 아니면 `1`로하고 `-1`을 더해주는게 좋을지 아니면 다른방법이 있을지 조언부탁드립니다.

`저도 위의 상황이라면 rawValue를 0으로 시작하는 것이 나을 것 같아요. 흠 그런데 이전 button의 경우에는 액션으로 넘어오는 sender의 tag를 활용하면 원하는 쥬스의 데이터만 활용할 수 있었는데요.(Stepper도 비슷하구요) 하지만 지금 label은 이벤트로 전달받은 tag와 연관이 없어보이네요. 예를들어 현상태에서 Stepper의 tag값들이 변경되면 label의 tag도 함께 변경해줘야 할 것 같습니다. 고민해보시고! 개선 부탁드립니다:)`

# 조언을 얻고 싶은점
> - 빌더 패턴을 사용한 얼럿에 대해서 간단한 시연을 볼 수 있을까요?

`빌더 패턴은 구글링을 통해서 몇가지 코드를 참고할 수 있을 것 같은데요! 다음에 같이 이야기해보면 좋을 것 같습니다.`

> - 데이터전달하는 방법 중에서 첫번째뷰에서 두번째뷰로 데이터전달을 하고자할때 `delegate`와 `Notification` 시도해봤던결과 데이터 전달이 안되었었는데 이유가 두번째뷰가 아직 로드되지 않았기 때문에 데이터를 전달할 수 없었던것같았습니다. 하지만 저의가 사용했떤 프로퍼티로 값 전달은 할 수 있었던것같아서 약간 혼란스럽습니다. 혹시 이 차이점에대한 설명과 첫번째뷰에서 두번째뷰로 데이터전달을 할 수 있는 추가적인 방법이 있을지 조언을 얻고 싶습니다.

`프로퍼티로 값을 전달할 때에는 두번째 뷰컨트롤러 인스턴스 초기화하고 난 이후라 가능한 것입니다. 그리고 커멘트로 남기기도 했는데요. 패턴, 아키텍처 활용 등과 같이 여러가지 다양한 방법을 더 생각해볼 수 있겠지만 현재는 구상하셨던 프로퍼티로 전달하는 방식을 더 개선해보시면 좋을 것 같아요.☺️`

> - `button`이나 `label`프로퍼티를 생성하여 `= {}` 클로저를 열어 기능을 추가해주고 오토레이아웃을 `setConstraintUI`라는 메서드내에 다 구현을 해주었는데 가독성에 문제는 없는지 궁금합니다.

`넵 가독성에 문제 없었어요. 그런데 스토리보드에서 직접 추가하시지 않고 코드로 UI를 구현해주신 이유가 있을까요? (문제가 있는건 아니고 다른 이유가 있었는지 궁금합니다!)`

# 문제해결
> - 두번째뷰인 재고 추가를 한 과일 데이터들을 첫번째뷰로 가져왔을때 까지는 데이터 전달이 잘 이루어졌는데 다시 쥬스주문버튼을 눌렀을때 과일데이터가 재고 추가하기이전의 데이터로 계산이되어 `FruitStore`내에 `updateStock`이라는 메서드를 생성하여 재고를 업데이트해주는 기능을 추가하였습니다.

`넵 update가 필요하네요. 그리고 커멘트를 남기기도 했는데요. 현재는 UILabel에 text로 적용된 데이터를 전달하여 데이터를 운용하셨더라구요. 그런데 이 방식은 UILabel의 text가 다른 이유로 변경이 되었을 때 처음 UILabel에 대입해주셨던 juiceMaker.fruitStore.fruitsStock 데이터와의 무결성이 위배될(데이터가 일관적이지 못할) 가능성이 있고 코드 가독성이 저해되는 문제가 있습니다. juiceMaker.fruitStore.fruitsStock 데이터를 계속 안정적으로 활용할 수는 없을까요?`

# 해결하지못한점
> - `Stepper`의 액션이벤트와 연동되어 있는 레이블의 `width`가, 숫자가 바뀌면 미세하게 움직이는걸 고정시키고자 하였는데 해결하지 못하였습니다. 그냥 레이블의 `width`를 넓히면 해결되는 문제일까요?

`레이블의 width가 미세하게 움직이는(변경되는)건 UILabel의 intrinsic content size를 찾아보시면 좋겠어요!`

> - 재고 수정 화면에서 `Stepper`의 액션이벤트를 주게 되면 현재의 값에서 값이 `+=, -=` 되는 것이 아니라 2에서 부터 시작하는 모습을 볼 수 있습니다. 왜 이런 현상이 일어나는 걸까요?

`Stepper 탭 액션에서 sender.value를 출력해보시고 sender.value가 의미하는 것을 다시 한번 고민해보셔야 할 것 같아요! (sender.value는 label에서 보여주는 재고 숫자인가요?)`

> - 개굴이 조언해주었던 빌더 패턴으로 얼럿을 구성해 보고자 하였는데 아직 학습이 부족하여 기존의 코드로 사용하게 되었습니다. 시간이 주어진다면 살짝 맛만 볼 수 있는 경험을 해봤으면 좋겠습니다.

`다음에 같이 이야기해보는 시간 가져보아요!☺️`

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +
라인은 두칸 띄우셨네요! 의도하신걸까요?

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +protocol FruitStockDelegate: AnyObject {
Delegate 패턴을 사용해보셨네요:) AnyObject를 채택하신 이유를 설명해주실 수 있나요?

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +    func sendData(_ fruitStockLabels: [UILabel]!)
강제 언래핑(!)은 지양해주세요! 여기에서 강제 언래핑 타입을 정의하신 이유가 있으신가요?

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +    var delegate: FruitStockDelegate?
retain cycle에 대해 설명 부탁드립니다!

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +        fruitStockLabels[sender.tag].text = Int(sender.value).description
현재 stepper를 터치하면 과일 재고를 기준으로 카운트 되지 않습니다.🐸
혹시 `sender.value`로 들어오는 값을 출력해보셨나요? `sender.value`는 어떤 데이터가 들어오는걸까요?

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +final class JuiceStoreViewController: UIViewController, FruitStockDelegate {
Delegate로 정의된 메서드의 경우 extension으로 따로 정의해주면 가독성이 좋습니다!
```
extension JuiceStoreViewController: FruitStockDelegate {
    func sendData(_ fruitStockLabels: [UILabel]!) {
        for index in fruitStockLabels.indices {
            self.fruitStockLabels[index].text = fruitStockLabels[index].text
        }
        juiceMaker.fruitStore.updateStock(fruitStockLabels)
    }
}
```

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +            fruitStockEditVC.fruitsStock.append(label)
UILabel text를 그대로 fruitsStock 데이터로 전달하고 있네요:) 흠 이 방식은 데이터가 안정적으로 운용되는 방식은 아닌 것 같습니다.

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        appendFruitStockLabelsText(to: fruitStockEditViewController)
FruitStockEditViewController에 JuiceStoreViewController에서 사용중인 fruitsStock 데이터를 그대로 전달해주는 방식은 어떨까요?

예를들어, 아래와 같은 형식이면 좋을 것 같은데요. 
`fruitStockEditViewController.fruitsStock = juiceMaker.fruitStore.fruitsStock`
그렇다면 `fruitStockEditViewController.fruitsStock`의 데이터 타입이나 로직은 변경되어야 할 것 같아요..!

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +import UIKit
UI를 구성하지 않는 FruitStore에서 UILabel이 사용되어 UIKit import가 필요한 것 같은데요! 확실한 역할 분리를 위해 데이터 운용 방식을 개선해서 FruitStore에서는 UIKit을 import하지 않도록 할 수 있을까요?

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +    private let dismissButton: UIButton = {
접근제어 활용 좋습니다👍

2022-03-09 17:10 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        guard let fruitStockEditViewController = self.storyboard?.instantiateViewController(withIdentifier: FruitStockEditViewController.identifier) as? FruitStockEditViewController else { return }
`identifier` extension으로 확장시켜주셨네요!👏

2022-03-10 10:46 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +    func sendData(_ fruitStockLabels: [UILabel]!)
IBOutlet으로 만든 fruitStockLabels의 배열 UILabel타입또한 강제언랩핑이라서 그대로 변수를 가져다주면 되지않을까 ? 라는 취지로 여기도 강제언랩핑을 써줘도 괜찮겠다고 생각했어요
하면서도 살짝 찝찝한건있었는데 ,,,ㅎㅎ 지양하겠습니다.

2022-03-10 10:47 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +protocol FruitStockDelegate: AnyObject {
AnyObject는 object-c에서 만든 클래스 최상위계층으로 AnyObject를 상속받으면 class에게만 사용될 수 있다는 명확성때문에 사용했습니다.

2022-03-10 10:48 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +
전혀 의도하지않았습니다..^^
확인감사드려요

2022-03-10 10:50 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +        fruitStockLabels[sender.tag].text = Int(sender.value).description
팀원과 다시 확인해본결과 sender.value는 기존에 속성에서 설정한 값이 전달되는것을 알게되었습니다.
그래서 저의가 의도한 대로 현재재고+1이라는 값이 증가되려면 sender.stepValue+현재재고를 더해주면 되더라구! 확인감사합니다.

2022-03-10 11:12 UTC, westeastyear commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditViewController.swift
> +    var delegate: FruitStockDelegate?
직역하자면 주기를 유지하다라는 뜻인데 서로 참조하고 있는 인스턴스에서 나타나는 현상이며 순환참조라고도 합니다. 
기본적으로 참조는 강한참조로 이루어져 있는데 각 레퍼런스 카운트가 동일하게 올라가며, 메모리해제가 되지 않아  메모리 누수가 발생하게 됩니다. 
그래서 둘중 하나에 `weak` 접두사를 작성하고 하나는 강한참조, 하나는 약한참조로 만들어 순환참조를 미연에 방지하고 메모리에서 해제할수 있게 만들어 줍니다.

2022-03-10 13:12 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +            fruitStockEditVC.fruitsStock.append(label)
더 명확한 데이터를 전달하는것이 좋다는 피드백을 해주셔서 fruitStock: [Fruit: Int] 값자체를 전달하는 코드로 수정해보았습니다.

2022-03-10 13:40 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +import UIKit
UILabel타입을 사용하지않는 방향으로 리펙토링하여 UIkit을 import하지않도록 하였습니다!

2022-03-10 13:51 UTC, Quokkaaa commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        appendFruitStockLabelsText(to: fruitStockEditViewController)
개굴이 조언해주신 방법대로 수정해보려고 했으나 Dictionary로 값을 받아서 labels에 재고를 업데이트하고 다시 재고를 업데이트하여 값을  첫번째 뷰컨으로 가져가는 과정에서 코드의 중복과 가독성이 떨어지지는 않을까 ? 라는 우려가 생겼습니다.
개굴이 말씀해주신 포인트가 fruitStore에서 재고 데이터를 그대로 전달한다는 의미를 살려 [String] 타입으로 전달을하면 값을 업데이트 하거나 주고받을때 코드도 간결해지는것 같고 가독성도 좋아지는것같다는 생각이 들었어요 개굴에 생각은 어떠한가요 ?

2022-03-10 14:16 UTC, Quokkaaa commented
@yoo-kie
개굴 피드백주신대로 리펙토링 후 커밋까지 완료했습니다!!
추가로 궁금한 사항은 댓글로 질문달았으니 확인해주시면 감사하겠습니다~!!

2022-03-11 13:45 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        appendFruitStockLabelsText(to: fruitStockEditViewController)
흠 저는 아래 2가지가 명확하면 현재 느끼시는 중복과 가독성 문제도 개선될 수 있을 것 같아요:)

1. FruitStockEditViewController은 재고를 수정(편집)하는 뷰컨트롤러이기 때문에 내부적으로 계산이 필요한 프로퍼티는 String타입이 아닌 연산이 가능한 Int 타입이면 좋을 것 같아요. (지금은 형(타입)변환이 빈번하게 이루어지고 있네요!)
2. IBOutlet인 fruitStockLabels가 fruitStockSteppers 활용이 어려운 이유는 각 Label과 Stepper가 대표하는 과일이 무엇인지 알기 어렵기 때문인 것 같아요!

개선할 수 있는 방법에 대한 제 생각은
1번 - fruitStockEditVC.fruitsStock으로 과일의 재고 연산이 편한 데이터 타입을 전달하면 좋을 것 같아요! 그리고  JuiceStoreViewController 내 updateFruitStockLabels에서 FruitStore의 fruitsStock을 가져와서 과일의 재고를 표시해주고 있기 때문에 데이터의 무결성을 생각해서 FruitStockEditViewController에서도 FruitStore의 fruitsStock을 그대로 전달해주어야 할 것 같아요!
2번 - Step을 진행하면서 UI컴포넌트 관련해서 비슷한 코드 중복을 피하기 위해 여러 방안에 대해서 이야기 나눠봤었는데요! 지금과 비슷한 방식으로 구현한다면 tag를 더 활용해볼 수 있을 것 같고 이전에 제안드렸던 Dictionary를 활용한 방법도 있겠네요!

2022-03-11 13:47 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/JuiceStoreViewController.swift
> +        appendFruitStockLabelsText(to: fruitStockEditViewController)
이는 제 의견을 공유드리는거라! 반드시 수정하시라는 의미는 아닙니다!

2022-03-14 11:05 UTC, yoo-kie approved these changes

2022-03-14 11:05 UTC, merged