쥬스메이커 [step3] doogie, malrang
yagom-academy/ios-juice-maker pull request #213
Opened 2022-03-09 04:54 UTC by malrang-malrang

@yoo-kie 안녕하세요 개굴! step3 Pr 드립니다.

고민했던 것들
data전달 방식의 선택
값을 넘겨 줄 때
let manageVC = self.storyboard?.instantiateViewController(withIdentifier: "ManageViewController")
코드로 화면 전환을 구현하기 위해 manageVC 라는 ManageViewController 의 인스턴스를 생성 했으며 이미 생성된 인스턴스를 활용하고자 해당 인스턴스를 ManageViewController 로 다운캐스팅만 진행해 data를 넘겨줌.

guard let manageVC = self.storyboard?.instantiateViewController(withIdentifier: "ManageViewController") as? ManageViewController else { return }
재고 관리 화면에서 변경된 값을 가져올 때(delegate패턴 vs notification)
notification의 userInfo는 [AnyHashable : Any] 타입의 딕셔너리로 값을 주고 받기에 딕셔너리의 key와 value를 꺼내서 쓰는 해당 어플에서는 delegate패턴이 더 유리하다고 생각.
조언을 받고 싶은 부분
코드를 간소화 시킬 때 가독성의 문제
dictionary를 통해서 코드를 많이 간소화 시켰고 가독성 또한 크게 떨어지지 않는다고 생각합니다.
변경전

    @IBAction func touchStepper( sender: UIStepper) {
     switch sender {
        case strawberryStepper:
            self.strawberryStockLabel.text = String(Int(sender.value))
        case bananaStepper:
            self.bananaStockLabel.text = String(Int(sender.value))
        case pineappleStepper:
            self.pineappleStockLabel.text = String(Int(sender.value))
        case kiwiStepper:
            self.kiwiStockLabel.text = String(Int(sender.value))
        case mangoStepper:
            self.mangoStockLabel.text = String(Int(sender.value))
        default:
            print("에러")
        }   
    }
변경 후

    @IBAction func touchStepper( sender: UIStepper) {
            let selectedStepperDic = stepperDic.filter{ $0.value == sender }
            selectedStepperDic.forEach{ fruit, stepper in labelDic[fruit]?.text = String(Int(sender.value)) }
    }
다만 위 코드는 간소화를 시켰으나 코드를 볼때 직관성이 많이 떨어진다고 생각하는데 기능적인 측면에서는 큰 차이가 없다고 생각이 든다면 코드가 길어져도 상관이 없는건지 조언을 받고 싶습니다.
(길어진 코드의 가독성이 더 좋다고 생각된다면.)

2022-03-11 12:30 UTC, yoo-kie requested changes
안녕하세요 두기 말랑! 리뷰가 다소 늦어진 점 죄송합니다!🥲
이번 PR에서 프로젝트 코드가 전반적으로 정말 깔끔해지고 가독성도 좋아졌다고 느꼈어요!
쥬스메이커 고생 많으셨습니다!

# 고민했던 것들
data전달 방식의 선택
값을 넘겨 줄 때
let manageVC = self.storyboard?.instantiateViewController(withIdentifier: "ManageViewController")
코드로 화면 전환을 구현하기 위해 manageVC 라는 ManageViewController 의 인스턴스를 생성 했으며 이미 생성된 인스턴스를 활용하고자 해당 인스턴스를 ManageViewController 로 다운캐스팅만 진행해 data를 넘겨줌.

`🐸 좋습니다☺️`

guard let manageVC = self.storyboard?.instantiateViewController(withIdentifier: "ManageViewController") as? ManageViewController else { return }
재고 관리 화면에서 변경된 값을 가져올 때(delegate패턴 vs notification)
notification의 userInfo는 [AnyHashable : Any] 타입의 딕셔너리로 값을 주고 받기에 딕셔너리의 key와 value를 꺼내서 쓰는 해당 어플에서는 delegate패턴이 더 유리하다고 생각.

`🐸 이번 프로젝트에서 delegate 활용 좋았습니다! 다만 커멘트에도 남겼는데요. Delegate 패턴 활용 시 retain cycle을 가장 주의해주셔야 합니다. Retain cycle로 인한 memory leak이 발생할 수 있기 때문인데요! 이를 해결하기 위해 retain cycle이 무엇인지 + memory leak이 왜 문제가 되는지 + weak 키워드에 대해 학습해보시길 추천드립니다!`

# 조언을 받고 싶은 부분
코드를 간소화 시킬 때 가독성의 문제
dictionary를 통해서 코드를 많이 간소화 시켰고 가독성 또한 크게 떨어지지 않는다고 생각합니다.
변경전

    @IBAction func touchStepper( sender: UIStepper) {
     switch sender {
        case strawberryStepper:
            self.strawberryStockLabel.text = String(Int(sender.value))
        case bananaStepper:
            self.bananaStockLabel.text = String(Int(sender.value))
        case pineappleStepper:
            self.pineappleStockLabel.text = String(Int(sender.value))
        case kiwiStepper:
            self.kiwiStockLabel.text = String(Int(sender.value))
        case mangoStepper:
            self.mangoStockLabel.text = String(Int(sender.value))
        default:
            print("에러")
        }   
    }
변경 후

    @IBAction func touchStepper( sender: UIStepper) {
            let selectedStepperDic = stepperDic.filter{ $0.value == sender }
            selectedStepperDic.forEach{ fruit, stepper in labelDic[fruit]?.text = String(Int(sender.value)) }
    }
다만 위 코드는 간소화를 시켰으나 코드를 볼때 직관성이 많이 떨어진다고 생각하는데 기능적인 측면에서는 큰 차이가 없다고 생각이 든다면 코드가 길어져도 상관이 없는건지 조언을 받고 싶습니다.
(길어진 코드의 가독성이 더 좋다고 생각된다면.)

`🐸 흠 만약 코드의 재사용성과 효율성을 높일 수 있는 차이가 있는게 아니라면 그건 개인의 스타일의 차이라고 볼 수 있는데요! (다만 그렇게 작성한 데에 반드시 이유가 있어야 한다고 생각합니다.) 예시 코드의 경우에는 label의 text에 sender의 value를 대입해주는 코드가 반복적으로 작성되는데요. 저라면 코드 반복을 피할 수 있는 코드가 더 가독성이 높다고 느껴질 것 같습니다!`

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        manageVC.delegate = self
데이터 전달을 위해 프로퍼티와 delegate패턴을 활용하셨네요:) 좋습니다!
가독성을 조금 더 개선하자면 fruitDictionary -> `fruitsStockDictionary`같은 네이밍은 어떨까요!

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +extension MainViewController: ManageViewControllerDelegate {
extension으로 delegate 메서드를 분리시켜주셨네요! 너무 좋습니다:)

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +protocol ManageViewControllerDelegate {
Delegate 네이밍 좋습니다! 그리고 해당 프로토콜을 클래스 객체 타입에서만 채택할 수 있도록 하려면 아래와 같이 작성해줄수 있습니다. 이렇게 하면 Delegate 패턴 활용을 위한 안정적인 프로토콜이 될 수 있어요!
```suggestion
protocol ManageViewControllerDelegate: AnyObject {
```

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +                                                .mango: mangoStepper]
외부에서 사용되는 프로퍼티가 아니라면 접근제어 private 추가해주세요!

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +    var delegate: ManageViewControllerDelegate?
retain cycle로 인한 memory leak에 대해 설명해주실 수 있나요? 그리고 해당 코드를 어떻게 개선할 수 있을까요?

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +        selectedStepperDictionary.forEach{ fruit, stepper in labelDictionary[fruit]?.text = String(Int(sender.value)) }
filter 고차함수를 사용해보셨네요! sender 활용도 좋습니다!
그런데 지금은 filter와 forEach 두번의 iterator를 돌게 되는데요:) 아래와 같이 시간복잡도를 개선해보면 어떨까요?
```swift
stepperDictionary.forEach { fruit, stepper in
    if stepper == sender {
        labelDictionary[fruit]?.text = String(Int(sender.value))
    }
}
```

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +        fruitDictionary.forEach{ (fruit, stock) in stepperDictionary[fruit]?.value = Double(stock) }
이것도 한번의 forEach문으로 개선하면 좋을 것 같습니다!

2022-03-11 12:30 UTC, yoo-kie commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +    func sendStocks(stocks : [Fruits: Int])
띄어쓰기 조심해주세요!
```suggestion
    func sendStocks(stocks: [Fruits: Int])
```

2022-03-12 03:56 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        manageVC.delegate = self
재고를 나타내는 딕셔너리니 fruitsStockDictionary이 더 보기 좋은 것 같습니다!

2022-03-12 03:56 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +                                                .mango: mangoStepper]
lazy에도 private을 추가 할 수 있는지 몰랐습니다!
바로 추가 하였습니다

2022-03-12 04:00 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +        fruitDictionary.forEach{ (fruit, stock) in stepperDictionary[fruit]?.value = Double(stock) }
원래 처음에는 말씀하신대로 한번에 구현을 했는데 저희가 볼때 알아보기가 힘들어서 두번에 나눠서 구현했습니다.
그런데 생각해보니 한번에 구현하면 재고를 한번만 돌고 각각 값을 넣어주면 되는데 두번에 나눠서 구현하면 두번 반복하게 되는 것으로 생각되어 한번의 forEach문으로 변경하였습니다

2022-03-12 04:18 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +        selectedStepperDictionary.forEach{ fruit, stepper in labelDictionary[fruit]?.text = String(Int(sender.value)) }
이 부분도 아래 forEach구문과 같은 이유로 한번의 구현이 반복문을 덜 돌게 된다고 생각이 듭니다!

2022-03-12 04:53 UTC, doogie97 commented on JuiceMaker/JuiceMaker/Controller/ManageViewController.swift
> +    var delegate: ManageViewControllerDelegate?
말랑과 같이 공부해서 이해한 바로는
메모리에서 해제될 때 래퍼런스카운팅이 0이어야지 정상적인 해제가 가능한데 ManageView가 dismiss되더라도 protocol을 계속 참조 하고 있어 정상적인 메모리 해제가 불가하다고 이해했고 이 경우 weak으로 선언해서 해당 클래스가 메모리 해제되는 시점에 같이 해제 될 수 있도록 선언해야 한다고 이해했습니다.

2022-03-12 10:50 UTC, yoo-kie approved these changes

2022-03-12 10:52 UTC, merged