쥬스메이커 [STEP 3] minseong, papri
yagom-academy/ios-juice-maker pull request #214
Opened 2022-03-09 09:28 UTC by Minseong-yagom

@TTOzzi
안녕하세요 또치~
벌써 마지막 리뷰네요 ㅠㅠ 마지막도 잘 부탁드리겠습니다!

# ios-juice-maker
## 팀원
minseong, papri

## STEP 3 수행 내용
- 화면 제목 ‘재고 추가’ 및 ‘닫기’ 버튼 구현
- 닫기를 터치하면 이전화면으로 복귀
- 화면 진입시 과일의 현재 재고 수량 표시
- stepper의 -, + 를 통한 재고 수정
- iPhone 12 외에 다른 시뮬레이터에서도 UI가 정상적으로 보일 수 있도록 오토레이아웃 적용

## 구현함수
- `clickUpdateFruitStockButton()`: 재고수정 버튼 클릭시 재고추가 창으로 이동시켜줌
- `closeButton()`: 닫기 버튼 클릭시 현재 켜져있던 뷰가 닫힘
- `updateStepperValue()`: Stepper의 Value를 현재 재고에 맞게 설정해줌
- `tapStepper()`: Stepper를 탭할 때 마다 변경사항을 LabelText와 재고에 즉각반영
- `updateInventory()`: StepperValue를 inventory에 반영
## 고민한 점 및 해결
### **1. 화면전환 방식**
navigation vs present

![](https://i.imgur.com/ydtbzD2.png)

기능구현 명세서 그림에선` navigation bar`에 `닫기 버튼`만 존재했습니다.

`navigation 방식`을 활용하면, 이전 화면으로 돌아가는 버튼이 따로 왼쪽 상단에 생겼기 때문에
`present 방식`을 이용하여 화면을 전환하고,`dismiss를 활용`하여 닫기 버튼을 누르는 것으로만 화면을 닫고 이전화면으로 이동 할 수 있게 하였습니다.
```swift
//JuiceMakerViewController의 '재고 수정' 버튼을 누를 시
@IBAction func clickUpdateFruitStockButton(_ sender: UIBarButtonItem) {
        guard let fruitStoreVC = storyboard?.instantiateViewController(identifier: "FruitStoreVC") as? FruitStoreViewController else {
            return
        }
        fruitStoreVC.delegate = self
        fruitStoreVC.juiceMaker = juiceMaker
       
        present(fruitStoreVC, animated: true, completion: nil)
    }
```
```swift
// FruitStoreViewController에서 '닫기' 버튼을 누를 시
@IBAction func closeButton(_ sender: UIBarButtonItem) {
        delegate?.updateFruitStock()
        presentingViewController?.dismiss(animated: true, completion: nil)
}
```

### **2. stepper의 -, + 를 통한 재고 수정**
`text`와 별개로 `stepper`를 탭하면 0부터 시작하는 문제가 발생하였습니다.
> `value`의 값을 `viewDidLoad`에서 초기화 시켜주어서 해결했습니다.

### **3. ViewController간 데이터 전달 방식**
`JuiceMakerViewController` -> `FruitStoreViewControlle` 프로퍼티에 `직접접근`하여 데이터를 전달하였습니다
`FruitStoreViewControlle` -> `JuiceMakerViewController` `delegate`를 활용하여 데이터를 전달하였습니다.

### **4. ViewController간 데이터(JuiceMaker 인스턴스의 FruitStore의 inventory)를 공유하는데 문제 발생**
FruitStoreViewController에서 stepper로 재고 수정을 한 후, JuiceMakerViewController에서 수정된 만큼 Label에 표시가 되었지만 쥬스를 만들 때 재고 부족 알림이 뜨는 문제가 발생했습니다.

```swift
func updateInventory(fruit: Fruit, value: Int) {
        inventory[fruit] = value
}
```
> updateInventory 메소드를 FruitStore 클래스에 추가적으로 구현하여

```swift
@IBAction func tapStepper(_ sender: UIStepper) {
        guard let fruit = Fruit(rawValue: sender.tag) else {
            return
        }
        fruitLabelCollection[sender.tag].text = Int(sender.value).description
        juiceMaker?.fruitStore.updateInventory(fruit: fruit, value: Int(sender.value))
}
```
> FruitStoreViewController에서 stepper를 눌렀을 때 JuiceMaker의 FruitStore의 inventory에 접근 할 수 있게 하였습니다.

## 조언을 얻고 싶은 부분!
`UIStepper`의 크기가 고정이라서 작은 화면에서 겹치는 일이 발생하였습니다.
`UIstepper`의 경우 사이즈를 따로 처리해주는 방법이 존재할까요??🧐 (구글에서 관련 글을 못 찾았습니다ㅠ) 
![](https://i.imgur.com/tEHdqYC.png)

2022-03-10 16:42 UTC, TTOzzi requested changes
안녕하세요 @Minseong-yagom @papriOS !
마지막 스텝까지 고생 많으셨습니다 :bow:
짧은 기간이었지만 코드가 많이 발전한 게 보이는 것 같아 좋네요 🥰

### 조언을 얻고 싶은 부분

> `UIStepper`의 크기가 고정이라서 작은 화면에서 겹치는 일이 발생하였습니다.
> `UIstepper`의 경우 사이즈를 따로 처리해주는 방법이 존재할까요??🧐 (구글에서 관련 글을 못 찾았습니다ㅠ)

`UIStepper` 는 크기 변경은 지원하지 않는 것 같습니다 :cry:
[[transform](https://developer.apple.com/documentation/uikit/uiview/1622459-transform)](https://developer.apple.com/documentation/uikit/uiview/1622459-transform) 를 활용해 scale 값을 변경해 레이아웃을 늘려주는 방식을 사용할 순 있으나, 좋은 방법인진 모르겠네요 
:thinking:크기 변경이 자유자재로 가능한 `Stepper` 형태의 뷰가 필요하다면, 커스텀 뷰를 만들어야 할 것 같아요.

남겨드린 코멘트 보시고 이해가 어려운 부분이 있다면 말씀해주세요!

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
>  class FruitStoreViewController: UIViewController {
상속받지 않는 클래스라면 꼭 `final` 명시해주세요!

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var juiceMaker: JuiceMaker?
음 아마 이전 화면에서 사용하던 `JuiceMaker` 를 전달해주기 위해 옵셔널 변수로 접근을 열어둔 채 구현된 것 같은데, 다른 사람과 협업하다 보면 이렇게 구현부를 열어뒀을 때 작성자의 의도와 다르게 다른 시점에 `juiceMaker` 에 접근해 값을 바꾸는 등의 코드가 생길 수 있습니다. 🤔 
여기는 처음 할당 이후 값이 변경되지 않을테니 `private let`으로 선언해두고 생성자를 만들어 생성 시점에 주입하도록 변경해볼 수 있을까요?
[instantiateViewController(identifier:creator:)](https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller)를 활용해 구현해볼 수 있을 것 같아요. 
([Handling view controllers that have custom initializers](https://www.swiftbysundell.com/tips/handling-view-controllers-that-have-custom-initializers/) 이 글에 어떤 식으로 구현되는지 설명이 잘 나와있습니다!)

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var delegate: UpdateData?
`JuiceMakerViewController`가 `FruitStoreViewController`를 띄워주고, `FruitStoreViewController`의 `delegate`를 `JuiceMakerViewController`로 설정해주고 있어 서로가 서로를 잡고 있는 순환 참조가 발생할 수 있습니다.
`delegate` 패턴에서 `delegate` 프로퍼티는 `weak`로 선언해주어, 순환 참조가 발생할 가능성을 없애주는 게 좋아요 🙂

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        fruitLabelCollection[sender.tag].text = Int(sender.value).description
`tag` 사용으로 우려하던 부분이 생겨버린 것 같은데요.. 😨
현재 각 `Stepper`가 자기 자신에게 매핑된 과일 재고를 잘 올려주고 있나요? 
앱을 실행해보니 `sender`와 버튼의 `index`가 일치하지 않는 것 같아요 🤔

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        juiceMaker?.fruitStore.updateInventory(fruit: fruit, value: Int(sender.value))
`FruitStoreViewController`에서 `juiceMaker`가 `fruitStore`를 갖고있는지를 알 필요가 있을까요? 👀 
만약 `juiceMaker`가 `fruitStore`가 아니라 다른 곳(딱히 예시가 안 떠오르네요.. 😞)에서 과일을 가져오게 된다면, `juiceMaker`를 통해 `fruitStore`에 직접 접근하던 `FruitStoreViewController` 까지 코드 수정을 해야 합니다.

여기선 `juiceMaker`내부의 구체적인 구현을 모른 채, 
```swift
juiceMaker.updateInventory(fruit: fruit, value: Int(sender.value))
``` 
와 같은 방식으로 `juiceMaker`의 메서드를 호출하도록 구현해둔다면, `juiceMaker`의 `재고를 업데이트 한다`는 동작 자체가 바뀌지 않는 이상 내부 구현이 어떻게 바뀌든 `FruitStoreViewController`는 코드를 수정할 필요가 없을 거예요.

이런 개념을 조금 어려운 단어로 `디미터 법칙` 이라고 부르기도 하는데, 단어를 외우실 필요는 없고 관련된 개념에 대해서 공부해 보시면 좋을 것 같습니다 🙂

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore()
위에서도 언급하긴 했지만, `private`을 풀기전엔 꼭 접근을 허용해줘야만 하는 이유가 있는지 한 번 생각해보면 좋을 것 같아요!

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Util/Protocol/DelegateProtocol.swift
> +}
일단 파일 명은 프로토콜 이름과 동일하게 바꿔주는 게 좋을 것 같구요!
아니면 코드 가독성을 위해 해당 `delegate`의 주체가 되는 곳(`FruitStoreViewController`)의 위쪽에 선언해두셔도 됩니다 🙂 

추가로 `UIKit` 에서 제공하고 있는 `delegate` 프로토콜들의 네이밍을 살펴보시고 좀 더 `delegate` 스럽게 메서드 선언부를 바꿔보면 좋을 것 같아요.
대표적으로 [UIScrollViewDelegate](https://developer.apple.com/documentation/uikit/uiscrollviewdelegate)가 있겠네요!

지금은 이름만 보고는 이 프로토콜이 누구의 동작을 위임하여 처리하는 것인지, 어느 시점에 이 메서드가 불리게 되는지를 파악하기 어려울 것 같습니다 🤔

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        updateFruitsStock()
현재 `viewWillAppear` 에서도 `updateFruitsStock`로 뷰들을 다시 그려주고, 띄워줬던 `FruitStoreViewController`가 닫히는 시점(이 `delegate` 메서드가 불리는 시점)에도 다시 그려주고 있는데요.
한 번만 그려줘도 되지 않을까요? 👀

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            fruitStoreVC.juiceMaker = self.juiceMaker
`clickUpdateFruitStockButton` 에서 `FruitStoreViewController`를 생성하는 로직과 여기서 `FruitStoreViewController`를 생성하는 로직이 중복되네요.
이 부분 하나의 메서드로 분리해볼 수 있을까요?

2022-03-10 16:42 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let fruitStoreVC = storyboard?.instantiateViewController(identifier: "FruitStoreVC") as? FruitStoreViewController else {
요렇게 특정 뷰의 `identifier`를 갖고 뷰를 불러와야 할 때, 타이핑에서 발생하는 실수를 막기 위해
```swift
extension UIViewController {
    static var identifier: String {
        return String(describing: self)
    }
}
```
`extension`으로 클래스 이름을 가져오는 프로퍼티를 선언해두고, `Storyboard`의 `id`와 맞춰서 사용하기도 합니다.
(이렇게도 사용하는구나~ 를 알려드리기 위한 편의성을 위한 코드이니 참고만 해주세요 🙏 )

2022-03-11 06:37 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var juiceMaker: JuiceMaker?
FruitStoreViewController의 생성자를 다음과 같이 작성 한 후
```swift
 init?(juiceMaker: JuiceMaker, coder: NSCoder) {
        self.juiceMaker = juiceMaker
        super.init(coder: coder)
     }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```


```swift
    private func showFruitStoreVC() {
        guard let fruitStoreVC = storyboard?.instantiateViewController(identifier: "FruitStoreVC" , creator: { coder in
            FruitStoreViewController(juiceMaker: self.juiceMaker, coder: coder)
        }) else {
            return
        }

        fruitStoreVC.delegate = self

        present(fruitStoreVC, animated: true, completion: nil)
    }
```
JuiceMakerViewController에서 `showFruitStoreVC() 함수`를 작성해 FruitStoreViewController를 생성하도록 해

```swift
failAlert.addAction(UIAlertAction(title: "네", style: .default, handler: { _ in self.showFruitStoreVC()}))
```
`재고가 부족했을 때  알람이 떠 '네' 버튼을 누르거나,`

```swift
 @IBAction private func clickUpdateFruitStockButton(_ sender: UIBarButtonItem) {
       showFruitStoreVC()
    }
```
`재고 수정 버튼을 누르는` `생성 시점`에 주입시켰습니다!!

2022-03-11 06:48 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var delegate: UpdateData?
```swift
protocol UpdateData: AnyObject {
    func updateFruitStock()
}
```
class 타입만 프로토콜을 채택할 수 있게 하여 

`weak var delegate: UpdateData?`

weak로 선언해주어 순환참조 발생의 가능성을 없애보았습니다!

2022-03-11 08:09 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        fruitLabelCollection[sender.tag].text = Int(sender.value).description
해당 코드엔 버튼(UIButton)이 없는데,
sender(즉 UIStepper)의 tag 값과 과일 재고값을 나타내는 레이블들의 모임인 fruitLabelCollection의 index가 일치하지 않는 것 같다는 말씀이신가요?!

그 문제를 저희가 PR을 보낸 후에 30분이내로 바로 고쳐서 커밋을 보내고 푸시를 했는데 반영이 안된걸까요..???
저희 시뮬레이터 상으론 제대로 돌아가고있습니다😥

2022-03-11 12:24 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        juiceMaker?.fruitStore.updateInventory(fruit: fruit, value: Int(sender.value))
말씀해주신 디미터 법칙에 대해 알아보니, 캡슐화와 비슷한 개념이라고 생각이 들었습니다!
> 모듈은 자신이 조작하는 객체의 속사정을 몰라야 한다는 법칙
 객체 지향 방식에서, 객체는 자료를 숨기고 함수를 공개하는 방식
(https://ios-development.tistory.com/761)

이라는 포스팅을 읽고 나서 이해를 해보았습니다.
말씀해주신대로 JuiceMaker의 fruitstore 자료를 숨기고, 메소드로 접근할 수 있게끔 수정해보았습니다.

JuiceMaker에 다음 메소드를 추가하여
```swift
 func updateInventory(fruit: Fruit, value: Int) {
        fruitStore.updateInventoryStock(fruit: fruit, value: value)
 }
```
` juiceMaker?.updateInventory(fruit: fruit, value: Int(sender.value))`
다음과 같이 메소드를 호출하도록 바꿨습니다!

이 과정에서  updateInventory()와 updateInventoryStock()의 네이밍에 대해 고민을 많이 했는데 괜찮은 네이밍일까요...?!

2022-03-11 12:25 UTC, papriOS commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore()
메소드로 접근하게 만들어 private을 다시 붙여주었습니다!

2022-03-11 12:49 UTC, papriOS commented on JuiceMaker/JuiceMaker/Util/Protocol/DelegateProtocol.swift
> +}
말씀하신대로 찾아보니 프로토콜은 
`주체가 되는 클래스이름+Delegate` 으로 이름을 짓는 것이 관례로 파악되었습니다!

프로토콜 안 `메소드명`에 대해선 여러 사례를 찾아보았는데, 규칙을 찾기 어려웠습니다.. 함수의 역할만을 적은 것 같더라구요.
저희도 그래서 `updateFruitStock()`으로 가려고 하는데, 혹시 또치는 추천하는 이름 있으신지.. 여쭤봐도 될까요?!

2022-03-11 12:58 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        updateFruitsStock()
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        updateFruitsStock()
    }
```
화면이 띄워질때마다 실행되는 updateFruitStock을 viewWillAppear에서 없애주고,

viewDidLoad에서 모든 재고의 값이 10으로 초기화가 되어야 했기 때문에 
여기서 updateFruitStock 메소드를 한번 불러주는 것으로 수정했습니다!

2022-03-11 12:59 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            fruitStoreVC.juiceMaker = self.juiceMaker
` showFruitStoreVC() `메소드로 분리했습니다!

2022-03-11 13:12 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let fruitStoreVC = storyboard?.instantiateViewController(identifier: "FruitStoreVC") as? FruitStoreViewController else {
완전 꿀팁이네요! 감사합니다😉🥰

2022-03-11 14:08 UTC, papriOS commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        fruitLabelCollection[sender.tag].text = Int(sender.value).description
<img width="718" alt="스크린샷 2022-03-11 23 00 17" src="https://user-images.githubusercontent.com/98319774/157882908-9fb804b9-83bc-40b6-8f0d-c1c8e2992969.png">

다음 과정에서 fruitLabelCollection의 index에 일치하지 않게.. 만들어버렸단 걸 확인했습니다!! 감사합니다 또치!

2022-03-13 05:53 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        juiceMaker?.fruitStore.updateInventory(fruit: fruit, value: Int(sender.value))
넵! 두 네이밍 모두 메서드의 의도를 표현하는데엔 문제 없으니 괜찮은 것 같습니다!

2022-03-13 06:03 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Util/Protocol/DelegateProtocol.swift
> +}
`UIScrollViewDelegate`의 메서드를 참고해보면, 메서드의 이름이 동작을 위임하는 주체(`ScrollView`)의 관점에서 네이밍된 것을 보실 수 있을 거예요.
그리고 위임 받는 곳에서 어떤 객체가 메서드를 호출했는지 할 수 있도록 항상 첫 번째 인자로 동작을 위임하는 주체를 넘겨주고 있구요!
지금 `updateFruitStock` 메서드는 동작을 위임하는 주체(`FruitStoreViewController`)가 `dismiss` 되는 시점에 호출되는 것 같으니 (아니면 `close` 버튼이 눌렸을 때..?)
```swift
func didDismiss(_ fruitStoreViewController: FruitStoreViewController)
```
정도로 지어줄 수 있을 것 같아요 🙂

2022-03-13 06:18 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            }
이렇게 로직이 나뉘면 다시 `ingredient` 에 대한 순회 로직을 두 번 돌게 되는데요.
하나의 함수는 하나의 역할을 해야한다는 것과 효율성이 충돌할 때 어느 것을 선택할지는 참 어려운 것 같습니다 🤔 
(이건 정답이 있는 건 아니에요! 구현하신 이유를 설명하고, 다른 개발자를 설득할 수 있다면 전혀 문제 없는 코드입니다 🙂 )

2022-03-13 06:20 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Util/Extension/UIViewControllerExtension.swift
> +import UIKit
`Foundation`과 `UIKit`은 어떤 차이가 있나요? 👀 
둘 모두를 `import` 해야하는 상황이 있을까요? 🤔

2022-03-13 06:21 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Util/Extension/UIViewControllerExtension.swift
> -import Foundation
헉 여기서 지워주셨군요 😅
PR이 열린 이후 리뷰는 커밋 단위로 보다보니 그만..

2022-03-13 06:26 UTC, TTOzzi commented on JuiceMaker/JuiceMaker/Util/Protocol/DelegateProtocol.swift
> +
이 코드는 이제 지워도 될 것 같아요 +_+

2022-03-13 06:33 UTC, TTOzzi commented
(막 머지하면 안될 것 같아서..) 더 수정할 부분이 없다면, 말씀해주시면 머지할게요!
고생하셨습니다! 🙇

2022-03-13 06:33 UTC, TTOzzi approved these changes

2022-03-15 15:01 UTC, merged