쥬스메이커 [Step3 ] Roy , Eddy
yagom-academy/ios-juice-maker pull request #215
Opened 2022-03-09 12:35 UTC by Roy-wonji

안녕하세요 @AppleCEO  Step3 PR입니다 :)
어느새 시간이 지나 마지막 PR이네요! 마지막까지 잘 부탁드립니다 :)

### 구현내용
-  `showFruitsStock()` JuiceMakerViewController 뷰에서 받아온 현재 과일 재고를 initFruits() 라벨에 보여주고 + stepper의 value 값을 현재 재고로 지정 해주는 함수 
- `closedButtonTapped` 뒤로가기 + delegate가 sendData 를 전달 하는 함수 
-  `stepperPressed` 버튼별 Label.text 갱신 + currentStock 갱신 하는 함수  

### 고민했던점 & 궁금한점
- IBoutletCollection 과 enum rawValue를 이용해서 `ChangeStockViewController`에서 현재 재고를 보여주는 방식을 먼저 생각해보았습니다. 그래서 현재재고를 불러오는 것에는 문제가 없었는데 Stepper를 활용시에 문제가 생겻었습니다. 예를 들어 현재 재고가 10이면 + 버튼으로 계속 올라가지지고 마이너스도 되지만 최소 숫자가 10으로 지정되어있더라구! 이 부분에서 어떻게 해야할지 사실 코드에서 고민을 했는데 결국 switch문을 다시 써보게되었습니다 ㅠㅠ 그래서 혹시 리뷰 하실 때 시간 되시면 한번 설명드리고 문제가 무엇인지 이야기 해보고싶습니다..!
- 오토 레이아웃을 잡을 때 제 생각에는 전체 모든 것을 포함하는 스택뷰 안에 각각을 스택뷰로 잡아서 이를 수평 수직 중앙으로 오토레이아웃 하면 충분할 것 같다고 생각해서 이렇게 했는데, 혹시 더 괜찮은 방법이 있는지? 아니면 이 방법이 적절한 방향이였는지 궁금합니다.
- 코드가 중복이 되는 부분이 있었습니다. 하지만 이를 빼서 함수로 사용하려고 했는데 이러면 IBAction에 접근할 수 없더라구요. 이런 부분을 뺼 수 있는 방법이 있을까요? extension 같은것을 활용해야할지? 궁금합니다 코드는 아래에서 재고 없을 때의 ok 눌렀을 때의 화면전환인데, 이는 `changedViewControllerTapped`함수와 겹치는 부분이 있었습니다..!
```swift 
   private func showStockChangeAlertMessage() {
        let juiceOutOfStockAlert = UIAlertController(title: AlertMessages.outOfStock, message: "", preferredStyle: .alert)
        let yesButton = UIAlertAction(title: AlertMessages.ok, style: .default) {_ in
            guard let ChangeStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") as? ChangeStockViewController else { return }
            ChangeStockViewController.changedStock = self.fruitStore.fruits
            self.navigationController?.pushViewController(ChangeStockViewController, animated: true)
        }
        let noButton = UIAlertAction(title: AlertMessages.cancel, style: .destructive, handler: nil)
        juiceOutOfStockAlert.addAction(noButton)
        juiceOutOfStockAlert.addAction(yesButton)
        present(juiceOutOfStockAlert, animated: false, completion: nil)
    }
```

```swift 
    @IBAction private func changeViewControllerTapped(_ sender: Any) {
        guard let ChangeStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") as? ChangeStockViewController else { return }
        ChangeStockViewController.delegate = self
        ChangeStockViewController.changedStock = fruitStore.fruits
        if let naviController = navigationController {
            naviController.pushViewController(ChangeStockViewController, animated: true)
        } else {
            JuiceMakerError.notExistNavigationController
        }
    }
```
- 해결이 안된 부분인데, 딸바주스를 주문하고 재고가 없을 때 재고 수정으로 넘어갈 때 바나나의 재고가 원래는 9가 되야되는게 맞는데 가끔은 8이 되는 에러가 발생합니다. 이를 찍어보니 stock, fruitCount가 (10, 1)에서 (9, 1)로 되어서 문제가 생기는데 코드를 분석해보고 생각해보았는데 정확히 모르겠어서 어떤 부분을 놓친것인지 힌트를 얻고싶습니다!

2022-03-11 00:58 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@Roy-wonji , @kimkyunghun3 고생하셨습니다!
쉽지 않은 스텝인데 잘 완수하셨네요~
리뷰가 조금 늦어진 점은 죄송합니다.
오늘 밤에 시간 맞춰서 이야기 나눠도 좋을 것 같네요.

질문에 대한 답변
혹시 리뷰 하실 때 시간 되시면 한번 설명드리고 문제가 무엇인지 이야기 해보고싶습니다..!
- 오늘 밤에 시간 맞춰서 이야기 나눠봐요~

오토 레이아웃을 잡을 때 제 생각에는 전체 모든 것을 포함하는 스택뷰 안에 각각을 스택뷰로 잡아서 이를 수평 수직 중앙으로 오토레이아웃 하면 충분할 것 같다고 생각해서 이렇게 했는데, 혹시 더 괜찮은 방법이 있는지? 아니면 이 방법이 적절한 방향이였는지 궁금합니다.
- 네 스텍뷰를 사용하면 여러 뷰들을 어느 정도 통일되게 보여줄 수 있습니다. 잘하셨습니다~

코드가 중복이 되는 부분이 있었습니다. 하지만 이를 빼서 함수로 사용하려고 했는데 이러면 IBAction에 접근할 수 없더라구요. 이런 부분을 뺼 수 있는 방법이 있을까요?
- 객체 안 에서 사용하면 접근할 수 있지 않나요? 이 부분도 회의실에서 이야기 나눠볼 수 있겠네요!

해결이 안된 부분인데, 딸바주스를 주문하고 재고가 없을 때 재고 수정으로 넘어갈 때 바나나의 재고가 원래는 9가 되야되는게 맞는데 가끔은 8이 되는 에러가 발생합니다. 이를 찍어보니 stock, fruitCount가 (10, 1)에서 (9, 1)로 되어서 문제가 생기는데 코드를 분석해보고 생각해보았는데 정확히 모르겠어서 어떤 부분을 놓친것인지 힌트를 얻고싶습니다!
- 이 부분도 같이 만나서 코드를 조금씩 바꿔가며 같이 디버깅 해봐요~

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +protocol ChangeStockViewControllerDelegate: AnyObject {
AnyObject 를 상속 받은 이유가 있을까요?

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    weak var delegate: ChangeStockViewControllerDelegate?
delegate 패턴을 사용해보셨군요! 👍

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    var changedStock: [FruitsTypes: Int] = [:]
빈 딕셔너리를 만들어주신거죠? 코드가 조금 어색해보이기도 하네요.
스타일쉐어 스위프트 가이드에는 어떤 식으로 가이드가 되있는지 확인해봐도 좋을 것 같습니다~

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    var changedStock: [FruitsTypes: Int] = [:]
https://github.com/StyleShare/swift-style-guide

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        changedStock.keys.forEach{ fruits in
for 대신에 forEach 를 쓰신 이유가 있을까요? 🔢

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +                mangoStockStepper.value = Double(changedStock[.mango] ?? .zero)
이것도 매번 ?? .zero 가 붙는 것이 보기 안 좋네요.
이렇게 코드가 반복된 다는 것은 무언가 개선할 점이 있다고 생각해볼 수 있습니다.
어떻게 개선해 볼 수 있을까요?

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    @IBAction func closedButtonTapped(_ sender: Any) {
보통 메소드 이름은 동사로 시작합니다!
더 적합한 메소드 이름이 있을까요?

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        }
보통 이런 부분은 놓치기 쉬운데요.
에러에 대한 처리를 해준 것 좋네요~ 💯

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let ChangeStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") as? ChangeStockViewController else { return }
저는 보통 guard let 구문을 이렇게 한 줄로 줄여서 쓰지는 않습니다.
이 코드는 ? 도 여러개이고 읽기 복잡하네요. 개선해 볼 수 있을까요?

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            guard let ChangeStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") as? ChangeStockViewController else { return }
이 부분도 코드가 길군요.
개선해 볼 수 있을까요?

2022-03-11 00:58 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
익스텐션으로 해당하는 프로토콜 관련 코드들만 모아놓은 것 좋습니다! 🥇 
여기 텝이 한 칸 띄워져있는 것 같은데 의도한 것일까요?

2022-03-11 01:20 UTC, Roy-wonji commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +protocol ChangeStockViewControllerDelegate: AnyObject {
기존의 프로토콜은 클래스와 구조체 열거형 모두 채택할 수 있지만 AnyObject를 채택할 경우는 클래스만 채택하게 하여
`weak var delegate: ChangeStockViewControllerDelegate?`
이처럼 사용하여 약한참조를 걸기 위해 AnyObject를 채택합니다.

2022-03-12 08:52 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        guard let ChangeStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") as? ChangeStockViewController else { return }
말씀해주신 방법으로 개선했더니 더 명확해졌으며, self를 쓰게됨으로써 불명확하며 코드의 변동에 따른 대처가 쉽지 않기에 이에 따라 바꾸어 보았습니다!

2022-03-12 08:54 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            guard let ChangeStockViewController = self.storyboard?.instantiateViewController(withIdentifier: "ChangeStockViewController") as? ChangeStockViewController else { return }
위에 말씀하신 방향으로 동일하게 수정해보았습니다 :)

2022-03-12 08:54 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
의도된것은 없고 잘못입력한 부분같습니다..ㅠㅠ 다만 아까 말씀하신 부분에서 class로 하게되면 데이터 전송이 필요없어지고 메모리주소에 의해 이미 가지고 있다 판단하여 델리게이터 패턴은 제거했습니다!

2022-03-12 08:55 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    @IBAction func closedButtonTapped(_ sender: Any) {
`updateFruitStockButtonTapped` 라고 명칭을 바꾸었습니다. 이는 닫기 기능이 아닌 과일의 재고를 업데이트 하는 버튼이라고 생각하여 이리 바꾸었습니다!!

2022-03-12 08:59 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    var changedStock: [FruitsTypes: Int] = [:]
가이드라인을 통해 다양한 초기화방시기 있다는 것을 파악했습니다. 그것은 각각의 취향에 따라 선택할 수 있다는 도미닉의 말을 듣고 가독성이 높은 방식을 채택하는게 맞다고 판단했습니다. 도미닉이 제시해주신 `var changedStock = [FruitsTypes: Int]()` 방식이 위에 작성한 코드보다 보기 편했으며 키에 무엇이 들어가는지 값에 무엇이 들어가는지 바로 판단할 수 있다고 생각해서 이처럼 사용할 예정입니다! 하지만 이 코드는 fruitsStore 라는 FruitStore 인스턴스를 활용하면 더 객체지향적 설계가 가능하다는 것을 말씀을 통해 알려주셔서 위의 코드는 제거하게 되었습니다! 좋은 설명 감사합니다 😄

2022-03-12 09:01 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        changedStock.keys.forEach{ fruits in
for와 forEach는 동일하게 동작합니다. 이를 반복문으로 보느냐, 클로저로 보느냐 차이가 있었으며 반복문에서는 break, continue를 사용할 수 있지만 클로저에서는 사용못한다는 것을 알게 되었습니다. 하지만 도미닉이 말한 것처럼 forEach의 가독성은 조금 떨어지는 것을 인정하게 되었습니다. for문이 조금 더 영어스러운 표현방식이라고 생각하고 만약 이 반복 코드가 성능에 크게 지장이 없다면 for문을 사용하는 방향도 괜찮은 것 같습니다!

2022-03-12 09:04 UTC, kimkyunghun3 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +                mangoStockStepper.value = Double(changedStock[.mango] ?? .zero)
이 코드를 먼저 도미닉과 생각해봤던 것은 `FruitStore` 클래스 내에서 과일 수를 더하고 뺴는 함수를 구현해서 이를 이곳에서 사용하자는 취지였던 것 같습니다. 하지만 구현해보고 보니, 어떤 부분이 +이고 -인지 stepper가 구분해주고 있는데 굳이 필요한가 라는 의문이 생겼고 이 코드에 대해서는 불필요하다고 판단했습니다. 그리하여 다시 위 코드와 비슷하게 구현하게 되었고 .zero 부분은 변수로 지정해서 넣어주는 방식으로 구현했습니다!

2022-03-24 13:53 UTC, closed without merging