쥬스 메이커 [STEP 1] Judy, Finnn
yagom-academy/ios-juice-maker pull request #216
Opened 2022-04-26 03:14 UTC by finnn1

# 쥬스메이커 프로젝트 (Judy & Finnn)

담당 리뷰어 : @corykim0829
안녕하세요 Cory! 쥬스 메이커 STEP1 PR 보내드립니다 ☺️
잘 부탁드립니다 🙏

<br/>

# 기능구현 및 코드설명 🧑‍🏫
- `JuiceMaker` : 과일 재고와 쥬스 만드는 메서드를 가진 구조체
-> `makeJuice` : `Menu`를 받아 해당 과일의 재고를 변경하는 메서드
- `FruitStore` : 과일 재고를 관리하는 클래스
-> `fruitStock` : 과일별 재고를 저장한 딕셔너리
-> `subtractQuantity` : 과일의 재고를 n개만큼 줄이는 메서드
-> `convertToString` : 재고를 `String` 타입으로 변환하는 메서드
- `Fruit` : 과일 종류를 나열한 열거형
- `Menu` : 쥬스 메뉴를 나열한 열거형
-> `returnRecipe` : 쥬스 메뉴별로 필요한 과일 수를 튜플 배열`[(Fruit, Int)]`로 반환하는 메서드
- `ThrowError` : 오류 상황을 나열한 열거형

<br/>

# [STEP 1] 고민한점 및 해결방안 🤔
## 고민한점
### 1. 열거형 (rawValue, 연관값, 메서드)
쥬스마다 필요한 과일 개수가 정해져 있어 `Menu` 열거형에서 필요한 과일 개수를 나타내고 싶었습니다. 처음에 `rawValue`를 사용하려 했으나 `case`별로 유니크한 값을 가져야 해서 같은 개수가 필요한 경우 표현할 수 없었습니다.  다음 방법으로 열거형에 연관값이 있음을 알고 연관된 값으로 필요한 개수를 `Int`로 넣으려 했으나 연관값 사용은 `Switch`문에 제한된 것 같았습니다.  결국 열거형에 `returnRecipe` 메서드를 추가해서 `case`별로 필요한 과일과 개수를 알 수 있도록 해결했습니다.
<br/>

### 2. Dictionary 사용
과일과 과일의 재고, 쥬스레시피와 들어가는 과일의 개수는 항상 짝을 이루기 때문에 해당 데이터를 `Dictionary`로 사용하는 것을 고민했습니다. `Dictionary` 타입은 두 가지의 데이터 타입이 항상 짝을 이루며, `Hashable` 타입이기 때문에 키 값을 입력하면 해당하는 데이터를 메모리에서 빠르게 찾을 수 있다는 장점이 있습니다. 때문에 다양한 과일 및 레시피를 `Int`와 연관지어 짝으로 관리해야 하는 쥬스메이커 프로젝트에 최적이라고 판단했습니다. 또한, 과일 및 레시피가 추가될 경우 `Dictionary`에 넣어주는 작업만 해주면 되기 때문에 확장성까지 고려할 수 있었습니다.
<br/>

### 3. 오류처리
프로젝트 요구사항에는 상품이 품절될 경우 과일을 만들 수 없다는 제약이 있었습니다. 단순히 `if else`와 같은 조건문 등으로 처리할 수도 있었지만, 확장성 및 가독성을 고려하여 `do` `try` `catch` 오류처리문으로 해결하고자 노력했습니다. 결과적으로 `try` 하는 메서드 및 `throw`를 하는 메서드에서 오류가 발생할 수 있다는 것을 직관적으로 알 수 있게되어 코드의 가독성이 향상되었습니다.
<br/>

# 배운개념 💡

- `CaseIterable` : 모든 `case` 값들에 대한 컬렉션을 제공한다.
- `UIButton`의 `tag` : 애플리케이션의 개체를 식별할 수 있는 정수이다.

## 궁금한 점 🥲

1. 어떤 쥬스를 만드는 `UIButton`인지 구분하기 위해 `restorationIdentifier`를 사용해봤는데 복원 식별자라는게 의도한 사용 목적과 맞지 않는 것 같아 `tag` 방식으로 변경하였습니다. 혹시 `restorationIdentifier`는 어떤 상황에 사용하는 것인지 궁금합니다!

2. 레시피 데이터를 만드는데 있어 고민 끝에 튜플 배열을 활용해 `[(Fruit, Int)]` 와 같은 방식으로 사용했습니다. 하지만 이렇게 짜는 코드가 비효율적이라는 느낌이 들어 계속 고민해봤지만, 이 이상의 해결책이 떠오르지 않아 리뷰어의 의견을 여쭙고 싶습니다! 🙏

2022-04-27 04:40 UTC, corykim0829 requested changes
수고 많으셨습니다! Judy & Finnn 👏

남겨드린 커멘트 참고하셔서 개선해봅시다!

### 궁금한 점

> 1. 어떤 쥬스를 만드는 UIButton인지 구분하기 위해 restorationIdentifier를 사용해봤는데 복원 식별자라는게 의도한 사용 목적과 맞지 않는 것 같아 tag 방식으로 변경하였습니다. 혹시 restorationIdentifier는 어떤 상황에 사용하는 것인지 궁금합니다!

두가지 방식을 비교하자면 말씀하신대로 사용목적과 다르기 때문에 `tag`를 사용하는게 좋습니다. `restorationIdentifier`는 UIViewController와 안에 컨텐츠를 보존할 때 사용한다고 문서에는 나오는데, 저도 사용해보지 않은 친구라 정확한 사용방법은 모르겠지만, 이 identifier를 통해서 해당 VC를 기억하고 저장해둘 수 있는 것 같습니다!

> 2. 레시피 데이터를 만드는데 있어 고민 끝에 튜플 배열을 활용해 [(Fruit, Int)] 와 같은 방식으로 사용했습니다. 하지만 이렇게 짜는 코드가 비효율적이라는 느낌이 들어 계속 고민해봤지만, 이 이상의 해결책이 떠오르지 않아 리뷰어의 의견을 여쭙고 싶습니다! 

지금 상황에서는 나쁘지 않은 코드라고 생각이 듭니다. 이 프로젝트가 한정적인 환경이 있기 때문에, 현재는 이렇게 처리해도 괜찮습니다 😊 

여유가 되신다면 오류처리를 Result를 사용해서 처리해보는 것도 좋습니다!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var lblStrawberryStock: UILabel!
`lbl`이 의미하는게 무엇인가요? 👀

UIKit의 클래스를 프로퍼티로 만들 때에 프로퍼티들이 많아지면 헷갈리기 때문에 
UILabel이면 프로퍼티명 뒤에 Label을 붙이면 가독성이 좋아집니다!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private var order: JuiceMaker = JuiceMaker()
JuiceMaker의 인스턴스명이 order인 부분은 조금 어색한 것 같아요! 또한 JuiceMaker의 타입이 명확하기 때문에 굳이 명시하지 않아도 됩니다! 참고하세요

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore: FruitStore = FruitStore(quantity: 10)
이 부분도 타입이 명확하기 때문에 타입을 명시하지 않아도 됩니다!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(what juiceMenu: Menu?) throws {
해당 함수명과 파라미터명을 조금 더 개선할 수 있을 것 같아요! 함수명이나 파라미터명을 결정할 때 사용되는 부분의 코드를 읽어보면 더 매끄러운 이름을 정하는데 도움이 됩니다!
현재 직접 사용되는 부분을 보면 다음과 같습니다.
`order.makeJuice(what: juiceMenu)`

함수는 되도록이면 동사만 사용하고 목적어 자체를 parameter로 처리하면 더 가독성이 좋습니다!
한번 수정해보고 더 이야기를 나눠보면 좋을 것 같습니다! 😀

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(what juiceMenu: Menu?) throws {
해당 파라미터를 함수 외부에서 먼저 옵셔널 처리를 해서 Menu 객체를 파라미터로 받는게 함수의 기능에 한정지어서 일을 처리하는 것 같아요! 어떻게 생각하시나요?

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/ThrowError.swift
> +enum ThrowError: Error {
ThrowError 라는 이름보다는 어떤 에러인지 더 명확하게 알 수 있는 이름이 좋을 것 같아요!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitStock: [Fruit: Int] = [:]
해당 프로퍼티의 접근제어자는 private으로 변경해서 외부에서 값을 변경하지 못하게 해주세요!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func convertToString(fruit: Fruit) -> String {
함수명을 보면 fruit을 받아서 String으로 covert하는 함수여서 과일명을 문자열로 반환할 것 같아요!
수정해보면 좋을 것 같습니다!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +    func returnRecipe() -> [(Fruit, Int)] {
return이라고 명시하기 보다는 반환하는 함수면 바로 명사형을 사용하는 것도 Swift API Design Guide에 따른 네이밍입니다! 수정해보면 좋을 것 같아요 😀

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +            return [(Fruit.strawberry, 16)]
반환타입을 명시했기 때문에 Fruit은 생략할 수 있습니다. 참고하세요!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        for (juice, fruitCount) in menu.returnRecipe() {
`(juice, fruitCount)` 에서 juice가 아니라 fruit이여야 할 것 같아요!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        for (juice, fruitCount) in menu.returnRecipe() {
배열로 재료와 필요한 개수를 튜플로 처리한 부분이 좋은 것 같습니다! 👍

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func showStock() {
showStock이라고 하면 없던 뷰를 만들거나 hidden 처리를 통해서 뷰를 보여주는 일을 할 것 같아요.
함수명을 수정해보면 좋을 것 같아요!

2022-04-27 04:40 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +    case strawberryJuice = 0
현재 button tag로 구분하고 있는데, button tag의 default 값이 0이기 때문에 1부터 시작하는게 좋을 것 같아요!

2022-04-28 05:36 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var lblStrawberryStock: UILabel!
말씀해주신 부분 lbl을 삭제하고, UILabel 타입의 프로퍼티명 끝에 Label을 붙여주는 방식으로 변경했습니다 😊
결과적으로 가독성이 좋아질 수 있었습니다!
감사합니다 🙏🙏

2022-04-28 05:37 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +    case strawberryJuice = 0
`tag` 값이 0부터 시작해서 별 고민없이 사용했는데 구분하려면 1부터 시작하는게 맞는 것 같아서 수정했습니다!

2022-04-28 05:37 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private var order: JuiceMaker = JuiceMaker()
앗.. 그러고보니 단순 order라고 정의된 부분이 어색했던 것 같아요! 🥲
juiceMachine 으로 변경했습니다!
또한 타입이 이미 명확한 부분은 타입 명시를 없애주었습니다~!
감사합니다!! 🙏

2022-04-28 05:38 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore: FruitStore = FruitStore(quantity: 10)
해당 부분도 명시되어있던 타입을 없애주어, 코드가 깔끔해졌습니다! 🙏

2022-04-28 05:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func showStock() {
재고가 변경될 때마다 재고 Lable을 수정하므로 `updateStock`으로 변경했습니다.

2022-04-28 05:39 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        for (juice, fruitCount) in menu.returnRecipe() {
과일과 개수를 넣은 튜플이니 `fruit`이 맞네요..! 수정했습니다.

2022-04-28 05:39 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +            return [(Fruit.strawberry, 16)]
넵 `Fruit`은 생략했습니다!

2022-04-28 05:41 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +    func returnRecipe() -> [(Fruit, Int)] {
함수명은 동사형으로만 한다는 강박이 있었네요..! 간단하게 `recipe`로 변경했습니다.

2022-04-28 05:41 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(what juiceMenu: Menu?) throws {
말씀해주신대로 함수에는 동사만 사용하고, 목적어를 파라미터 명으로 집어넣었습니다! 😊
또한, 메서드에 있는 Menu 타입 파라미터가 옵셔널로 선언되어 있는 것에 대해서 옵셔널이 너무 한정적으로 처리되어있는 것 같아,
밖에서 미리 옵셔널을 처리하고 make 메서드 내부에서는 옵셔널이 아닌 값으로 받아주는 것으로 변경했습니다~ ☺️

2022-04-28 05:42 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func convertToString(fruit: Fruit) -> String {
밑에 주신 코멘트를 참고하여 재고의 개수를 반환하는 함수라 `stockCount`로 변경해봤습니다!

2022-04-28 05:42 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Model/ThrowError.swift
> +enum ThrowError: Error {
말씀해주신대로 ThrowError 라는 이름이 어떤 작업과 관련된 에러인지 명확히 알기가 어려워,
JuiceMakerError로 변경했습니다~! 🙏🙏

2022-04-28 05:43 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitStock: [Fruit: Int] = [:]
재고의 `Lable`을 채울 때 `convertToString`로 접근하는걸 밖에서 직접 접근한다고 착각했네요..! `private`로 변경했습니다.

2022-04-28 05:50 UTC, finnn1 commented
안녕하세요 Cory!
말씀해주신 부분들 수정 완료했습니다! 확인 부탁드립니다 🙏

오류처리에 관해서 저희가 처음에는 요구사항에 적혀있는 대로 (throw, try-catch)로 구현을 했었는데요,
Result Type으로 처리해보는 것을 조언해 주셔서 이 방법으로도 시도를 해봤는데
성공시에 따로 리턴할 타입이 존재하지 않아서 많은 고민 끝에 (throw, try-catch)를 사용 하는 것으로 결정했습니다 🥲
다음에 더 많은 오류처리가 필요하다면 시도해보겠습니다~!
감사합니다 🙏

2022-04-28 13:42 UTC, corykim0829 approved these changes
수고하셨습니다! 

맞아요! 말씀하신대로 Result를 사용하기에는 리턴타입이 없어서 애매한 부분이 있네요!
try catch로 깔끔하게 잘 구현하셨습니다 👍

이번에 남겨드린 피드백은 다음 스텝 진행하면서 반영해주세요!!

2022-04-28 13:42 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private var juiceMachine = JuiceMaker()
JuiceMaker 클래스 인스턴스명을 `juiceMachine`로 하신 이유가 있나요? 큰 이유가 있지 않으면 인스턴스명은 소문자로 하는게 더 명확하고 일반적인 방법이에요!

2022-04-28 13:42 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        for (fruit, fruitCount) in juiceMenu.recipe() {
파라미터명을 juiceMenu로 변경하던가, Menu 객체명을 `FruitJuice`와 같이 바꾸면 더 깔끔할 것 같습니다!

현재
`juiceMachine.make(juice: juiceMenu)`

---
`juiceMachine.make(juiceMenu: juiceMenu)`
`juiceMachine.make(juice: juice)`

2022-04-28 13:42 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        StrawberryStockLabel.text = juiceMachine.fruitStore.stockCount(fruit: .strawberry)
여기 뷰컨트롤러에서는 JuiceMaker만 알고 있기 때문에, juiceMaker의 함수만 사용하거나 프로퍼티까지만 읽어오는게 좋을 것 같습니다!
객체지향적으로 JuiceMaker에서 재고를 처리하는 코드를 작성해서 처리해보면 좋을 것 같아요.

2022-04-28 13:43 UTC, merged

2022-04-29 01:28 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private var juiceMachine = JuiceMaker()
말씀해주신 부분 juiceMachine을 조금 더 깔끔하도록 store 로 변경 했습니다! ☺️
인스턴스에 대문자를 섞어 쓰는 것은 지양하도록 하겠습니다 🙏

2022-04-29 01:29 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        for (fruit, fruitCount) in juiceMenu.recipe() {
파라미터명을 juiceMenu로 변경했습니다!
Cory의 말씀대로 변경하니 가독성이 훨씬 좋아졌습니다~
감사합니다 🙏

2022-04-29 01:31 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        StrawberryStockLabel.text = juiceMachine.fruitStore.stockCount(fruit: .strawberry)
저희가 했던 방법이 객체지향적이지 못했던 것 같아요!
JuiceMaker에서 함수를 하나 더 정의해주어 객체지향적으로 처리했습니다~! ☺️