쥬스 메이커 [STEP 1] Baekgom, KayAhn
yagom-academy/ios-juice-maker pull request #217
Opened 2022-04-26 05:27 UTC by KayAhnDS

안녕하세요 😃 @AppleCEO
Baekgom, Kay의 첫번째 쥬스 메이커 PR 보내드립니다. 잘 부탁 드립니다!

## 📖 함수 설명

- JuiceMaker 파일 내 makeJuice 함수
    - 매개변수 (JuiceKind)
    - 매개변수로 받은 JuiceKind로 쥬스 종류를 판단해 그에따른  재료 소진을 구현 했습니다.
    - 재료가 부족한 경우에 대비, try-catch문을 사용했습니다.
- FruitStore 파일 내 changeFruitAmount, subtractFruitAmount, addFruitAmount함수
    - 매개변수 (FruitKind, Int)
    - 쥬스메이커 타입 정의 섹션에서 “각 과일의 수량 n개를 변경하는 기능이 있습니다" 와 같은 조건이 있어 해당 과일의 수량을 바꿔주는 메서드를 각각 만들었습니다.
    - changeFruitAmount → 해당 과일의 수량을 지정 수량으로 변경 합니다.
    - subtractFruitAmount → 해당 과일에 현재 수량에서 지정 수량 만큼 빼줍니다.
    - addFruitAmount → 해당 과일에 현재 수량에 지정 수량을 추가 합니다.
    

## 📖 어려웠던점/ 해결한점

### FruitStore 파일 내

- 각 과일 수량을 변경하는 함수 구현이 어려웠습니다.
    - subtractFruitAmount함수에서 if let바인딩으로 구현했었는데 들여쓰기 2번이 초과되는것 같아 gurad let 바인딩으로 해결했습니다.
- 어려웠던 점은 아니지만 stock dictionary 변수를 만들면서 10을 사용하는 대신 상수를 만들어 썼으면 더 좋았을것 같습니다.
- 테스트를 해 보았을때는 문제가 되는 부분은 없었지만, 저희가 에러 처리한 방법이 좋은방법인지 알고 싶습니다.
<br>

2022-04-26 13:35 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@Baek-Gom-95 , @KayAhnDS 고생하셨습니다!
코드가 의도를 알기 쉽게 작성되어 있었습니다.
하드코딩된 숫자들만 한번 개선해보면 좋겠습니다~
그리고 폴더 구조에 대해 고민해봤으면 좋겠습니다.
Controller 폴더에 뷰컨트롤러가 아닌 AppDelegate, SceneDelegate 가 있었습니다. 스토리보드는 View 일지도 한번 생각해보면 좋겠네요!

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +}
과일 종류라고 잘 번역되네요.
좋은 열거형 이름 같습니다! 👍

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +enum JuiceKind {
쥬스 타입도 따로 선언해줬군요.
이름도 명확하네요~ 💯

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +    case cannotError
에러명은 다소 불명확하네요.
Input 에러라고 해서 입력 에러라고 생각했는데 내용은 입력과 상관 없어보이네요~
어떻게 개선해 볼 수 있을까요?

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    [FruitKind.strawberry: 10,
말씀하신대로 이 10을 하드코딩하지 않게 해 볼 수 있을까요?

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
메소드명 명확하네요~

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentNumber = stock[fruitName] else { throw InputError.cannotError}
한 줄로 작성하면 이 코드가 어떻게 끝나는지 알아보기 힘들 수 있습니다.
이 코드도 throw 앞에는 한 칸 띄어져있는데 끝날 때는 붙어있어서 이 else { 가 언제 끝나는지 알아보기 힘들었네요!

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
이 코드는 띄어쓰기가 되어있어서 읽기 좋았습니다~

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                try fruitStore.subtractFruitAmount(fruitName: .strawberry, amount: 16)
여기 숫자들도 혹시 하드코딩을 제거해 볼 수 있을까요?

2022-04-26 13:35 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }catch InputError.cannotError {
catch 앞에 띄어쓰기 한칸을 해주면 더 좋겠습니다~

2022-04-27 08:07 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +    case cannotError
에러명을 ErrorCategory 로 변경했습니다 🤔

2022-04-27 08:08 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    [FruitKind.strawberry: 10,
과일 초기 갯수를 enum 열거형으로 변경했습니다

2022-04-27 08:09 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let currentNumber = stock[fruitName] else { throw InputError.cannotError}
else {  뒤에 한칸 띄어서 변경했습니다 🙂

2022-04-27 08:10 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                try fruitStore.subtractFruitAmount(fruitName: .strawberry, amount: 16)
JuiceKind 열거형에 recipe를 추가해서 하드코딩을 제거하였습니다

2022-04-27 08:10 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }catch InputError.cannotError {
catch 앞에 띄어쓰기 적용해서 변경했습니다 🙂

2022-04-27 08:21 UTC, KayAhnDS commented
@AppleCEO 
안녕하세요 도미닉!
작성해주신 리뷰와 코멘트 천천히 읽어보고 수정했습니다!
많은 지적 부탁드립니다! 감사합니다!

# 💌 수정 사항

## 📖 JuiceMaker

- 이전 switch문으로 분류에 따라 실행하던 작업을 레시피만 넘기는 방식으로 수정해 가독성을 높였습니다.

## 📖 FruitStore

- stock 프로퍼티에서 선언과 동시에 넣어주던 리터럴 값 10을 initCount 열거형에 Case로 빼주었습니다.
- subtractFruitAmount 함수의 매개변수를 딕셔너리 값으로 받아와 1개이던지 2개이던지 안전하게 처리해주는 방법으로 수정했습니다.

## 📖 EnumCollection

- initCount 열거형을 선언과 동시에 구현 함으로써 의미있는 숫자들을 한곳으로 묶어주었습니다.
- 이전에 JuiceKind에 있었던 case들을 활용, 연관값에 해당 쥬스의 레시피를 넣어주었습니다.
- 말씀해 주신 InputError라는 열거형 명칭은 저희가 다시 생각해 보아도 원래 의미하고자 했던바와 많이 달라,
ErrorCategory라는 이름으로 수정 했습니다.
<br>

2022-04-28 00:33 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +    case cannotError
ErrorCategory 는 에러의 종류들일까요? 여전히 조금 불명확한 것 같아요!

2022-04-28 00:35 UTC, merged