쥬스 메이커 [STEP 1] minsson, seohyeon2
yagom-academy/ios-juice-maker pull request #225
Opened 2022-04-27 08:21 UTC by minsson

@leejun6694 

안녕하세요, 쿠마!
쥬스메이커 프로젝트 5조 민쏜과 현이입니다.☺️

Step 1 PR 보냅니다. 검토 부탁 드립니다! 🙇‍♂️

---

## 1. 민쏜과 현이가 고민한 점 😲

#### 객체의 권한과 책임
쥬스를 만들 때 과일 재고를 소모하는 것과 관련, 현재 코드에서는 JuiceMaker 객체의 `make` 메서드를 통해 FruitStore의 `reduceInventory` 메서드를 호출하고 있습니다. 객체지향 프로그래밍의 관점에서 이러한 구조를 어떻게 볼 수 있을지 궁금합니다.
1) 현재 코드처럼 JuiceMaker의 메서드 안에서 FruitStore의 재고를 감소시키는 메서드를 호출하는 게 FruitStore 객체의 역할을 침범하는 걸까요?
2) 아니면 JuiceMaker 안에서 직접 FruitStore의 저장 프로퍼티를 다른 값으로 초기화하지 않으니 역할을 침범하는 건 아닌 걸까요?
3) 만약 침범하고 있다면, 어떤 방식으로 구조를 가져가는 게 조금 더 객체지향 프로그래밍에 가까운 걸까요?

### 에러 처리
`FruitStore`의 `hasEnoughInventory` 메서드를 보면 필요한 재료에 비해 재고가 부족한 경우 `AppError.lackOfInventory`를 throw 하고 있습니다. 코드를 다시 정리하면서, 이 지점에서 에러를 던지는 게 맞는지에 대한 의문이 들었습니다. 재고가 있는 것과 없는 것 모두 일어날 수 있는 자연스러운 일로, 없다고 해서 `Error`가 될 이유는 없다는 생각이 들었습니다. 이런 경우 Error 처리를 할지, 아니면 자연스러운 경우이므로 false 등을 리턴하여 재고가 없음을 알릴지 고민입니다. (혹은 error라는 단어를 너무 단어의 의미로만 접근하여 프로그래밍 내에서의 의미와 혼동하고 있을 수 있다는 우려가 들기도 합니다.)

---

## 2. 코드 설명

### 과일 저장소 타입 (class FruitStore)

#### [타입]
`enum Fruit: CaseIterabl`  
- 초기화 시 Fruit를 **배열처럼 다루기 위해** CaseIterable 프로토콜을 사용했습니다.

 `var fruitsInventory: FruitsInventory = [:]` 
- 과일명을 key 값, 과일 재고를 value 값으로 갖는 변수를 사용했습니다.
- **과일 저장소 타입을 딕셔너리로 선언한 이유** : 과일명을 기반으로 과일 재고를 조회하고자 했습니다. 따라서 과일 재고의 변경 및 새로운 과일명 추가 가능성을 생각하여 데이터 수정 및 추가를 자유롭게 할 수 있는 딕셔너리 타입이 적합하다고 생각했습니다.

#### [그 외]
`typealias FruitsInventory = [Fruit: Int]` 
- 과일명과 과일 재고를 딕셔너리로 가져오는 경우가 많아 **가독성을 높이기 위해** typealias 를 사용했습니다.

#### [메서드]
`init()`
- 각 과일의 초기 재고를 10개로 **초기화하기 위해 init 사용**했습니다.
- **매직넘버 사용을 줄이기 위해** 초기값은 상수로 선언했습니다.
- **코드 가독성을 높이기 위해** `for-in loop` 대신 `forEach` 사용하여 각 과일에 10개씩 넣어주었습니다.

`reduceInventory(of ingredient: FruitsInventory)`
- **과일 재고를 줄일 때 사용하는 메서드**입니다.
- 메서드의 기능을 줄이기 위해 과일 재고를 줄이는 일을 하는 메서드와 채우는 일을 하는 메서드를 따로 선언했습니다.
- 매개변수 *ingredient*는 쥬스를 만들 때 필요한 재료들이 모여 있는 *FruitsInventory* 타입으로 선언했습니다.

`supplyInventory(of ingredient: FruitsInventory)`
- **과일 재고를 채울 때 사용하는 메서드**입니다.
- 매개변수 *indredient*는 채우고자 하는 과일들이 모여 있는 *FruitsInventory* 타입으로 선언했습니다.

`hasEnoughInventory(of ingredient: FruitsInventory, in inventory: FruitsInventory)`
- **쥬스 만들기가 가능한지 확인하는 메서드**입니다.
- 재고가 부족하면 에러메세지가 뜨도록 에러처리했습니다.

#### 쥬스 메이커 타입 (**struct** JuiceMaker)

#### [타입]

`var store = FruitStore()`  
- JuiceMaker는 FruitStore를 소유하고 있다는 요구서 조건을 만족하기 위해 선언했습니다.

`enum Menu`
- 주문할 수 있는 쥬스 메뉴들을 담았습니다.

#### [메서드]

`checkRecipe(of juice: Menu) -> [FruitStore.Fruit: Int]`
- 쥬스를 만드는데 필요한 레시피(재료)를 확인하는 메서드입니다.

`make(juice: Menu, at store: FruitStore)`
- 쥬스를 만드는 메서드입니다.

---

감사합니다! ☺️

2022-04-27 13:32 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit.allCases.forEach { eachFruit in fruitsInventory[eachFruit] = initialInventory }
생략을 좀 더 사용할 수 있습니다 : )

2022-04-27 13:34 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        let initialInventory = 10
값을 선언하고 사용해주셔서, 코드를 읽을 때 도움이 되었습니다 👍

2022-04-27 13:45 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            inventory -= amountOfIngredient
실제 fruitsInventory 값도 변경되는지 확인이 필요할 것 같네요...!
참고 : https://developer.apple.com/documentation/swift/dictionary

2022-04-27 13:45 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            inventory += amountOfSupply
위와 마찬가지 입니다~

2022-04-27 13:46 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            inventory -= amountOfIngredient
여기는 재고가 부족한 경우의 에러 처리가 필요 없을까요!?

2022-04-27 13:49 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func make(juice: Menu, at store: FruitStore) {
JuiceMaker 가 가지고 있는 store 에서 주스를 만드는게 아닐까요?

2022-04-27 13:51 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private func checkRecipe(of juice: Menu) -> [FruitStore.Fruit: Int] {
이미 `FruitsInventory` type 을 선언했는데, 여기선 사용되지 못하고 있네요ㅠ

2022-04-27 13:52 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var store = FruitStore()
`let` 이 아닌 `var` 로 선언한 이유가 궁금합니다~!

2022-04-27 13:54 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private func checkRecipe(of juice: Menu) -> [FruitStore.Fruit: Int] {
`Recipe` 를 위한 공간을 따로 만들고, 이를 활용하는 것은 어떨까요?
현재 구조에서는 recipe 가 추가될 때마다, method 의 길이가 계속 길어질 것 같습니다 @.@

2022-04-27 13:55 UTC, leejun6694 requested changes
읽기 편하게 구현을 잘해주셨습니다 : )
몇 가지 확인하셨으면 하는 부분이 있어서, 코멘트 남겼습니다~!

2022-04-28 05:44 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit.allCases.forEach { eachFruit in fruitsInventory[eachFruit] = initialInventory }
`eachFruit in` 생략하고 축약인자를 사용했습니다!

또 초기값을 상수로 선언해주었는데, 생각해보니 추후에 초기값이 변경된다면 
상수로 선언해주는 것보다 매개변수로 기본값을 설정하는게 수정에 용이할 듯 하여 이부분도 같이 수정했습니다.
(쿠마가 생각하시기엔 어떤게 더 유연한 코드로 느껴지시는지도 궁금합니다😯)
변경된 코드는 다음과 같습니다!

```
init(initialInventory:Int = 10) {
        Fruit.allCases.forEach { fruitsInventory[$0] = initialInventory }
}
```

2022-04-28 05:50 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            inventory -= amountOfIngredient
앗.. 바보같은 실수를 했네요..🥲 바로 수정했습니다😌

에러처리..! 고민한 점에 올려놓은 부분과 같은 고민이 듭니다..
이 부분도 6시에 쿠마와 얘기를 나눠보고 수정하고 싶어서 아직 수정 안했습니다..!🥺

2022-04-28 05:52 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func make(juice: Menu, at store: FruitStore) {
🥲🥲 맞는 말씀입니다 😭😭

`at store: FruitStore` 매개변수 삭제했습니다!

2022-04-28 05:54 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private func checkRecipe(of juice: Menu) -> [FruitStore.Fruit: Int] {
`enum Menu` 안에 연관값 처리를 해줄려고 했는데, 그렇게 되면 들여쓰기가 총 3번 되서 함수로 뺐습니다..!
혹시 말씀하시는 공간이 enum(타입)안에 공간이실까요? 아니면 새로 파일을 생성하여 만들어진 공간을 말씀하시는 걸까요?😯

2022-04-28 06:53 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var store = FruitStore()
let으로 썼어야 했는데.. 고려를 못 했습니다.😱😢😭

그런데 저희가 짠 코드는 store에서  FruitStore()에 있는 `reduceInventory`, `supplyInventory` 메서드에 접근을 하여 재고를 변경합니다.
현재 코드로만 보면 `private(set) var store = FruitStore()` 로 수정하는게 방법이 가장 짧게 수정하는 방법이라고 생각합니다.
`private let`으로 쓴다면 `FruitStore` 의 `supplyInventory` 메서드에 접근하려면 새로운 메서드를 생성해야 하는 반면, `private(set) var store = FruitStore()`으로 수정하면 `(set)`만 수정하면 되니 새

1.  로 수정하여 외부에서만 수정이 불가하도록 하게 한다.
2.

2022-04-29 06:21 UTC, minsson commented
쿠마, 안녕하세요! 😁

피드백 내용을 바탕으로 코드 개선하여 커밋했습니다.
검토 부탁드립니다.

감사합니다! ☺️

2022-04-29 06:23 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var store = FruitStore()
앗..!  private에 집중하다보니 놓쳤습니다ㅠㅠ
let으로 수정했습니다!

2022-04-29 09:03 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            let fruitInventory = self.fruitsInventory[fruit] ?? 0
`self.` 가 필요할까요?
다른 코드와 규칙을 맞추면 좋을 것 같네요~!

2022-04-29 09:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        guard fruitsToUse != nil else { throw AppError.lackOfInventory }
fruitsToUse 값이 사용되지는 않네요~!
`Bool` 이 아닌, `FruitsInventory` 로 return value 를 정한 이유가 있으실까요?

2022-04-29 09:05 UTC, leejun6694 approved these changes
리뷰 포인트를 알맞게 수정해주셨습니다 : )
몇 가지 코멘트를 더 드렸는데, step 2 구현하면서 같이 고민해보시면 좋을 것 같네요!

2022-04-29 09:06 UTC, merged