쥬스 메이커 [STEP 2] Judy, Finnn
yagom-academy/ios-juice-maker pull request #226
Opened 2022-04-29 03:13 UTC by finnn1

담당 리뷰어 : @corykim0829
안녕하세요 Cory! 쥬스 메이커 STEP2 PR 보내드립니다 ☺️
이번에도 잘 부탁드립니다 🙏

---

# [STEP 2] 기능구현 및 코드설명 🧑‍🏫
- `ViewController`
-> `showCompleteAlert` : 쥬스 제조 완료 알림을 띄우는 함수
-> `showOutOfStockAlert` : 과일 재고 부족 알림을 띄우는 함수
- `JuiceMaker`
-> `stockCount` : 특정 과일의 재고를 반환하는 함수
- `Menu` 
-> `juiceName` : 쥬스의 이름을 반환하는 연산 프로퍼티

<br/>

# [STEP 2] 고민한점 및 해결방안 🤔
## 고민한점

### 1. 화면 이동 방식
#### 1) 재고 수정 버튼
버튼을 터치 했을 때 이동하게 하는 것은 코드없이 스토리보드에서 연결해 `segue`를 통해 화면이동하도록 했습니다. 메인 View가 네비게이션 컨트롤러에 속해있으므로 네비게이션 방식으로 이동하여 재고 수정 화면에서 다시 메인 화면으로 돌아올 수 있습니다. 
#### 2) 재고 부족 알림
처음 시도할 때는 재고 수정 화면을 알림처럼 `present`로 띄우려고 했습니다. 하지만 화면은 넘어가지만 다시 이전 화면으로 되돌아갈 방법이 없어 문제가 됐습니다. 알림 버튼을 통해서도 네비게이션 방식으로 넘어가도록 해서 해결했습니다.
<br/>

### 2. 쥬스 이름 가져오기
쥬스 제조 완료 알림에는 쥬스 이름이 들어가 `String` 타입의 쥬스 이름이 필요했습니다. 하지만 쥬스 메뉴가 담긴 `Menu` 열거형은 이미 버튼의 `tag`를 구분하기 위해 `Int`형 `rawValue`를 사용하고 있었습니다. `Menu` 열거형에 연산 프로퍼티를 추가하여 케이스별로 쥬스 이름을 반환하게 했습니다.
<br/>

# [STEP 2] 배운개념 💡
- `storyboard?.instantiateViewController(withIdentifier:)` : 미리 지정해둔 `Identifier`를 통해 스토리보드의 인스턴스를 생성한다.
- `navigationController?.pushViewController(_:animated:)` : 파라미터로 전달된 `UIViewController` 타입의 인스턴스로 이동한다.
- `UIAlertController` : 화면에 띄울 수 있는 `alert` 창을 관리한다. 해당 인스턴스에 `UIAlertAction` 인스턴스를 추가하면 버튼 및 동작을 할당할 수 있다.

<br/>

---

## 궁금한 점 🥲
### 1. 열거형의 메서드와 연산 프로퍼티
쥬스 이름을 알림으로 띄우기 위해 `Menu` 열거형의 연산 프로퍼티를 통해 받아왔습니다. 처음에는 `recipe`를 불러온 방식과 동일하게 `String`을 반환하는 메서드를 생성해 쥬스 이름을 반환하게 했습니다. 하지만 반환만 하는 메서드이고, 파라미터로 보내는데 `()`가 붙어있는게 부자연스러워 연산 프로퍼티로 변경하고 비슷한 작업인 `recipe` 역시 메서드가 아닌 연산 프로퍼티로 변경했습니다. 메서드와 코드도 유사하고 결과도 같은데, 메서드 사용과 연산 프로퍼티 사용은 어떤 때 구분하면 좋을지 궁금합니다!
<br/>

### 2. 화면 이동 구현시 segue방식과 pushViewController방식
요구사항을 보면 하나의 '재고수정' 페이지로 이동하는 것을 두 가지 경우에 구현하도록 되어 있는데요, 스토리보드의 네비게이션바에 있는 버튼을 누르면 이동하는 것과, `alert`창을 띄워 버튼을 누르면 이동되는 것이었습니다. 첫 번째의 경우 네비게이션바의 버튼과 '재고수정' 페이지를 직접 연결해 `segue` 방식으로 구현했고, 두 번째는 코드로 스토리보드의 인스턴스를 만들어 `pushViewController` 메서드를 사용해 이동하는 방식을 채택했는데요. 이때 `segue`와 `pushViewController` 는 같은 역할을 하는 것으로 보이는데, 저희가 사용한 용도가 적절한지 의문이 들어 두 가지 방식의 차이점을 알고 싶습니다!

2022-05-01 09:03 UTC, corykim0829 requested changes
수고하셨습니다! 👍
커멘트로 남긴 부분들 확인해주시고 코드를 더 개선해봅시다 😃

1. 열거형의 메서드와 연산 프로퍼티

> 쥬스 이름을 알림으로 띄우기 위해 Menu 열거형의 연산 프로퍼티를 통해 받아왔습니다. 처음에는 recipe를 불러온 방식과 동일하게 String을 반환하는 메서드를 생성해 쥬스 이름을 반환하게 했습니다. 하지만 반환만 하는 메서드이고, 파라미터로 보내는데 ()가 붙어있는게 부자연스러워 연산 프로퍼티로 변경하고 비슷한 작업인 recipe 역시 메서드가 아닌 연산 프로퍼티로 변경했습니다. 메서드와 코드도 유사하고 결과도 같은데, 메서드 사용과 연산 프로퍼티 사용은 어떤 때 구분하면 좋을지 궁금합니다!

➡️ 메서드를 사용할 때에는, 반환이 없거나 파라미터가 필요한 상황에서 사용될 것 같네요. 같은 동작을 하기 때문에 꼭 어떤 걸 사용해야한다고 생각할 필요는 없을 것 같아요. 개인적으로 이번 미션에서 사용되는 단순한 값들을 반환할 때에는 프로퍼티로 처리하는게 깔끔한 것 같습니다!

2. 화면 이동 구현시 segue방식과 pushViewController방식

> 요구사항을 보면 하나의 '재고수정' 페이지로 이동하는 것을 두 가지 경우에 구현하도록 되어 있는데요, 스토리보드의 네비게이션바에 있는 버튼을 누르면 이동하는 것과, alert창을 띄워 버튼을 누르면 이동되는 것이었습니다. 첫 번째의 경우 네비게이션바의 버튼과 '재고수정' 페이지를 직접 연결해 segue 방식으로 구현했고, 두 번째는 코드로 스토리보드의 인스턴스를 만들어 pushViewController 메서드를 사용해 이동하는 방식을 채택했는데요. 이때 segue와 pushViewController 는 같은 역할을 하는 것으로 보이는데, 저희가 사용한 용도가 적절한지 의문이 들어 두 가지 방식의 차이점을 알고 싶습니다!

➡️ segue에 관해서는 [공식문서](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/UsingSegues.html)에 자세히 나와있어서 확인하면 될 것 같습니다!
직접 여러 뷰컨트롤러들을 segue를 이용해서 처리해보는 것도 좋은 방법입니다!

2022-05-01 09:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +    var recipe: [(Fruit, Int)] {
recipe 변수로 바꾸니까 더 깔끔하네요! 👍

2022-05-01 09:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private var store = JuiceMaker()
인스턴스명을 store라고 한 이유가 궁금해요!
인스터스명이 store이면 코드를 읽을 때에 헷갈릴 수 있을 것 같아요.

2022-05-01 09:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        StrawberryStockLabel.text = store.stockCount(of: .strawberry)
헛 이제 보니 Label들 프로퍼티명이 대문자로 시작하네요! 👀 소문자로 수정 부탁드려요!

2022-05-01 09:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func showCompleteAlert(juice: String) {
String이면 다른 값이 들어갈 수도 있다고 생각할 수 있을 것 같아요.
Menu 타입을 파라미터로 받게되면 어떤 파라미터를 넘겨줘야하는지 더 명확할 것 같아요!

2022-05-02 04:44 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Model/Menu.swift
> +    var recipe: [(Fruit, Int)] {
감사합니다 🙏

2022-05-02 04:54 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func showCompleteAlert(juice: String) {
피드백 주신 내용을 바탕으로 생각해본 결과, 파라미터를 String 타입으로 받는 것 보다 Menu 타입 자체로 받는 것이 더 명확하다고 판단해서 수정했습니다 ☺️
감사합니다

2022-05-02 04:54 UTC, finnn1 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        StrawberryStockLabel.text = store.stockCount(of: .strawberry)
소문자로 수정완료했습니다 🙏

2022-05-02 04:55 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private var store = JuiceMaker()
쥬스 가게에서 쥬스를 만들고 재고를 관리한다고 생각해서 가게라는 의미로 `store`라고 했는데 의미 전달이 확실하지 않은 것 같네요 🥲
메서드인 쥬스를 만드는 `make()`와 재고를 불러오는 `stockCount()`와 자연스럽게 읽히도록 `juice`로 변경했습니다!

2022-05-02 06:07 UTC, merged