쥬스 메이커 [STEP 2] Baekgom, Kay Ahn
yagom-academy/ios-juice-maker pull request #229
Opened 2022-05-03 02:44 UTC by KayAhnDS

@AppleCEO 
안녕하세요 도미닉!
쥬스 메이커 STEP2 PR입니다.🙇🏻‍♂️🙇🏻‍♂️
감사합니다!!

## 🌳 파일 및 함수 설명

### 🔥 MakerViewController

📖 extension [Notification.Name](http://notification.name/)

- post하는 이름을 상수화해서 사용하기 편하게 만들어 주었습니다.

📖 viewDidLoad()

- 각 과일의 레이블에 현재 과일 수량을 가져와 대입 해줍니다.
- 위의 Notification.Name.identifier가 post를 하면 #selector에있는 takeJuiceOrder함수를 실행하도록 옵져버를 추가 해주었습니다.

📖 takeJuiceOrder()

- 사용자로 부터 입력된 쥬스를 만드는 함수 입니다.
    - 성공과 실패 여부를 Alert창을 띄워 알려줍니다.

📖 bringFruitCount()

- 각 과일의 갯수를 가져와 해당 레이블에 대입 해줍니다.

📖 successAlert()

- 필요한 재고가 있는 경우 띄워지는 Alert창 입니다.
- 쥬스의 이름을 매개변수로 받아와 성공하였을때 설정된 문구를 출력 하도록 구현했습니다.
    - OK 버튼을 누르는 시점에 과일 갯수를 재 설정 해줍니다.

📖 failAlert()

- 재고가 모자란 경우 띄워지는 Alert창 입니다.
- ‘예’ 와 ‘아니오' 두개의 옵션을 제시하고 그 중,
    - ‘예'를 선택
        - 네비게이션으로 화면전환
    - ‘아니오'를 선택
        - 띄워져있는 Alert창을 종료

📖 orderProcess()

- UIButton을 매개변수로 받아와 클릭된 버튼의 쥬스 이름을 가져옵니다.
- 노티피케이션 객체에 전달할 정보를 담아서 발송 해주는 함수입니다.

### 🔥 ViewController

📖 bringStockFruitCount()

- 재고수정 화면의 레이블을 최신화 하는 함수입니다.

touchUpDismissButton()

- 네비게이션이나 모달로 화면전환이 되었을때 이전화면으로 돌아가는 함수입니다.

touchUpCompleteButton()

- 완료버튼은 기능구현 사항에는 없었지만 나중에 필요할 것으로 생각되어 넣었습니다.
    - 현재는 Alert만 띄워지도록 구현했습니다.

### 🔥JuiceMaker

- 추가된 함수
    - fruitCount()
        - 매개변수로 받은 과일의 갯수를 String 타입으로 반환 해주는 함수입니다.

### 🔥FruitStore

- 추가된 함수
    - confirmFruitAmount()
        - 재료가 충분하다면 레시피의 과일 갯수만큼 Stock에서 차감해주는 함수입니다.
- 수정된 함수
    - subtractFruitAmount()
        - 특정한 경우에 예상한대로 결과가 나오지 않아 로직을 수정했습니다. 해당 내용은 밑에 후술 하겠습니다.

## 🌳 어려웠던점 / 해결한 점

### 🔥 전체

- juiceMaker 객체를 MakerViewController와 ViewController 두 곳에서 사용하려고 고민하다 클래스 밖으로 빼주어 사용하는 방향으로 구현 했습니다.
- subtractFruitAmount 함수에서 두가지의 과일을 소비하는 레시피가 있는데, 두 가지중 하나의 과일의 수량이 부족할 때, 쥬스는 만들어지지 않고, 수량이 부족하지않은 과일의 수량이 소비되는 경우를 발견해 코드를 수정 했습니다.

## 🌳 궁금한점

- 재고수정 화면이 보여지는 두 가지 경우가 있는데,
    - 하나는 재고가 모자라 Alert창을 통해 화면전환이 되는 경우, (Navigation)
    - 하나는 재고수정 버튼으로 화면전환이 되는 경우 (Modal)
    - 모달로 넘어갔을때에도 네비게이션 바와 아이템이 보이는데 이유를 잘 모르겠습니다.
- subtractFruitAmount() 함수에서 더 좋은 구현 방법이 있는지 궁금합니다.
<br>

2022-05-03 11:29 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@Baek-Gom-95 , @KayAhnDS 고생하셨습니다.
몇가지 고민할 점들 코멘트 남겨놨습니다.
확인 부탁드려요!

질문에 대한 답변
재고수정 화면이 보여지는 두 가지 경우가 있는데,
- 하나는 재고가 모자라 Alert창을 통해 화면전환이 되는 경우, (Navigation)
- 하나는 재고수정 버튼으로 화면전환이 되는 경우 (Modal)
모달로 넘어갔을때에도 네비게이션 바와 아이템이 보이는데 이유를 잘 모르겠습니다.
-> 스토리보드를 보면 힌트가 될 것 같은데요. 재고수정을 눌렀을 때 뷰컨트롤러를 띄우도록 가리키고 있는 것이 아니라 네비게이션 컨트롤러를 가리키고 있네요!

subtractFruitAmount() 함수에서 더 좋은 구현 방법이 있는지 궁금합니다.
-> 자신이 이해하면 좋은 코드라고 생각합니다. 조금 더 간단히 바꿔볼 수도 있을 것 같은데요. 왜 이렇게 작성했는지 이유를 누가 물어봤을 때 당당하고 자세하게 얘기할 수 있으면 괜찮을 것 같습니다.

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +    @IBOutlet weak var mangoCount: UILabel!
보통 View 를 상속받으면 그 이름을 뒤에 붙여주는 식으로 많이 하는 것 같습니다.
저희가 위에서 UIViewController 를 상속받아서 MakerViewController 클래스를 생성한 것처럼 UILabel 을 상속받은 변수들에 이름을 정해보면 좋을 것 같습니다~

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +    }
함수 계층이 같아서 깔끔하고 읽기 수월하네요~

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +                                               object: nil)
줄 바꿈이 깔끔하네요. 저는 한 줄로 쭉 작성하는 것을 선호합니다.
하지만 이런 식으로 딱 각을 맞추니 괜찮은 것 같네요.
다만 selector: #selector(takeJuiceOrder(_:)) , 에서 함수명 뒤에 , 전에 공백이 하나 들어간 것 같네요!

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        guard let juiceName = juiceInfomation.userInfo?[JuiceInfo.JuiceName] as? String else{ return }
한 줄로 줄여서 쓰는 표현은 아직 안 쓰는 게 좋다고 생각합니다.
다른 if 문을 사용하는 것처럼 여러 줄로 나눠서 작성해보면 어떨까요?

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        }
switch 문을 사용해보셨군요~ 👍 
과일 종류가 매칭이 안 될 때 none 을 반환하는 것도 인상적이네요!

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        mangoCount.text = juiceMaker.fruitCount(fruitName: FruitKind.mango)
과일 종류에 따라 과일 이름만 빼고 반복되고 있는 것 같군요.
반복을 줄여볼 수 있을까요?

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        let successAction = UIAlertAction(title: "OK",
위에는 한 줄로 작성하였고 비슷한 코드인데 아래 쪽은 여러 줄로 개행을 하셨군요.
이런 스타일도 하나로 통일하는 것이 좋습니다!

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        })
여기  guard let 위에 부분을 한 줄로 작성해보면 어떨까요?
어디에서 guard let 이 시작되는지 왜 한 칸 들여쓰는지 찾기 어려운 것 같기도 하네요~

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +                                        userInfo: [JuiceInfo.JuiceName : juiceButtonName])
위에서 자주 보던 스타일에서 약간 다르네요
, 뒤에서는 한 줄씩 띄워졌던 것 같은데 이번에는 다르네요.
이런 부분 때문에 우선 한 줄로 쭉 작성하는 것이 좋을 수 있습니다.
디테일한 스타일은 나중에 회사에 입사하게 되면 동료와 맞춰서 어떨 때 한 줄을 띌지 정해서 사용할 수 있을 것 같습니다.
우선 공부하는 상황이기 때문에 기본형으로 작성하는 것을 추천드립니다~

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -        // Do any additional setup after loading the view.
사용하지 않는 코드를 제거한 것 좋습니다! 💯

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +var juiceMaker = JuiceMaker()
여기서 juiceMaker 를 선언하는 것은 많이 어색한 것 같네요!
적당한 위치가 있을까요?

보통 class, extension, enum 등은 하나의 파일로 작성하게 됩니다.
이 파일에 여러가지가 모여있는 것 같은데 나눠볼 수 있을까요?

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.popViewController(animated: true)
여기 self 를 붙인 이유가 있을까요?
self 를 지워도 잘 동작하나요?

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +}
열거형을 활용해보셨군요~ 🔢

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
함수명에 return 이 들어가면 어색한 것 같아요.
사용되는 곳에서 return 을 하는 것으로 착각할 수도 있고요.
더 나은 이름이 있을까요?

2022-05-03 11:29 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
과일의 숫자를 String 으로 리턴하는 이유가 있을까요?
"0" 을 리턴하는 것 대신에 없는 것을 의미하는 다른 것을 리턴해 볼 수도 있을까요?

2022-05-05 05:05 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +    @IBOutlet weak var mangoCount: UILabel!
@IBOutlet weak var strawberryCountLabel: UILabel!
    @IBOutlet weak var bananaCountLabel: UILabel!
    @IBOutlet weak var pineappleCountLabel: UILabel!
    @IBOutlet weak var kiwiCountLabel: UILabel!
    @IBOutlet weak var mangoCountLabel: UILabel!
    
    로 'Label' 을 붙여주어 변경했습니다 🙂

2022-05-05 05:06 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +                                               object: nil)
공백 제거후 한줄로 변경하였습니다

2022-05-05 05:08 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        guard let juiceName = juiceInfomation.userInfo?[JuiceInfo.JuiceName] as? String else{ return }
if 문 처럼 변경하였습니다
juiceInfomation.userInfo?[JuiceInfo.JuiceName] as? String
        else { return } 🙂

2022-05-05 05:09 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        mangoCount.text = juiceMaker.fruitCount(fruitName: FruitKind.mango)
반복을 줄이기 위해
func retrieveFruitCount(fruitName: FruitKind) -> String {
        return juiceMaker.fruitCount(fruitName: fruitName)
    }

함수를 만들어 매개변수의 과일갯수를 반환해주었습니다

2022-05-05 05:10 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        let successAction = UIAlertAction(title: "OK",
한줄로 변경했습니다🙂

2022-05-05 05:11 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        })
다시보니 어디서 시작되는지 찾기 어려운것 같아 🤔 한줄로 변경하였습니다 🙂

2022-05-05 05:11 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +                                        userInfo: [JuiceInfo.JuiceName : juiceButtonName])
넵 기본형으로 한줄로 변경하여 수정했습니다 🙂

2022-05-05 05:13 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +var juiceMaker = JuiceMaker()
ExtensionCollection 파일을 만들어주어 해당파일에 extension 을 선언 및 초기화 해주었습니다. 🙂

2022-05-05 05:17 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.popViewController(animated: true)
저희가 검색해봤을때 self가 있어서 그대로 했습니다
말씀을 듣고 없애보니 똑같이 작동이 되어 제거했습니다 혹시 차이점을 설명해 주실수 있을까요?

2022-05-05 05:19 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
retrieveStock() 로 함수명 변경해주었습니다 🙂

2022-05-05 05:20 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
Label 에 바로 값을 할당해주기위해 String 타입으로 반환했습니다

0 ->  return "EMPTY" 로 변경해주었습니다 🙂

2022-05-05 05:24 UTC, KayAhnDS commented
@AppleCEO
안녕하세요 도미닉!
작성해주신 리뷰를 바탕으로 수정 하였고 세부 수정 내용은 달아주신 코멘트에 남겼습니다!
감사합니다!

2022-05-05 08:28 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        self.navigationController?.popViewController(animated: true)
ㅎㅎ 한번 찾아보시고 정리해보셔서 이런게 맞나요? 라고 질문하시면 더 좋을 것 같습니다~

2022-05-05 08:39 UTC, AppleCEO commented
고생하셨습니다. 잘봤습니다~ 몇가지 짚고 넘어가면 좋겠습니다.
1. Label 에 할당하기 위해서 숫자를 String 으로 받는 것이 좋을까요? 그렇다면 모든 타입들은 String 으로 저장할 수도 있을 것 같네요.. 어떤 점이 좋거나 나쁠지 고민해보면 좋겠습니다! 한번 작성한 내용들을 디스코드 지식공유 채널에 공유해서 다른 분들 의견 들어봐도 좋을 것 같네요~
2. 코드를 작성하는데 이유가 있으면 좋을 것 같습니다. 특히 검색을 해서 self가 붙어있어서 그냥 붙였다라는 식이면 좋은 개발자가 되기 힘듭니다. 자신이 작성한 모든 코드에는 이유가 있고 그거에 대해 자신의 의견을 말할 수 있어야합니다! 검색해보는 것은 좋지만 이것이 왜 이렇게 작성되었을지, 어떻게 동작하는지 이해하려고 노력해보고 모르겠으면 물어봐서라도 자신이 작성한 모든 코드를 이해할 수 있어야합니다.

다음 스텝 진행하면서 이 내용들 생각해보셨으면 좋겠습니다.

2022-05-05 08:40 UTC, merged