쥬스메이커 [STEP 2] minsson, seohyeon2
yagom-academy/ios-juice-maker pull request #233
Opened 2022-05-03 06:44 UTC by minsson

@leejun6694 

안녕하세요, 쿠마! 😁
JuiceMaker 프로젝트 5조 민쏜과 현이입니다.

Step 2 PR 보냅니다. 검토 부탁드립니다! ☺️
감사합니다!

### 1. 두 화면에서 사용되는 과일 재고 Label
- 메인 화면과 재고 관리 화면에 나오는 과일의 재고는 같은 값입니다.
- 처음에는 두 화면의 뷰컨트롤러에서 각각 과일의 재고에 대한 Label을 @IBOutlet으로 가져왔지만, 코드의 중복이라는 생각이 들었습니다.
- 중복을 피하기 위해 클래스의 상속을 이용해봤더니, 과일 재고 Label이 메인 화면과 같아졌습니다.
- `질문👀`: 상속을 하면서 값은 가져올 수 있을 거라고 생각했지만, 스토리보드 상의 각 Label들과 연동까지 자동으로 될 거라고 생각하지는 못했습니다. 컴파일러가 메인 화면의 딸기 이미지 아래 Label과, 재고 관리 화면의 딸기 이미지 아래 Label이 같다는 걸 어떻게 알고 자동으로 연결할 수 있었던 건지 궁금합니다.

<img width="1855" alt="Pasted image 20220503110134" src="https://user-images.githubusercontent.com/96630194/166413531-10cd2198-db57-4e5b-bde2-7aa7731f8d03.png">

<img width="1515" alt="Pasted image 20220503110159" src="https://user-images.githubusercontent.com/96630194/166413468-c48b4e6e-5371-4527-a545-2c6fdc331003.png">

### 2. 쥬스 주문 버튼
- 처음에는 쥬스 주문 버튼 7개를 각각의 `@IBAction func`로 가져왔습니다.
- 7개의 버튼은 모두 같은 메서드를 사용하는 같은 역할의 버튼이라고 생각해 하나의 메서드로 묶어보았습니다.
- 개선하고 싶은 점:
	- 현재 코드에서는 스토리보드에서 버튼의 내용을 바꾸면 `juiceOrderButtonTapped` 메서드의 switch 문의 case와 일치하지 않아 분기처리에 문제가 생깁니다.
	- 만약 7개의 버튼 각각에 JuiceMaker.Menu 타입을 담을 수 있다면, `juiceOrderButtonTapped` 메서드의 아규먼트로 메뉴 자체를 전달 받고 싶습니다. 이런 방식의 구현이 가능하다면 switch문 분기를 사용하는 대신, 전달 받은 메뉴를 `order` 메서드에 넣어주기만 하면 코드가 훨씬 간결해지고, 버튼의 타이틀을 수정하면서 발생할 수 있는 문제도 해결될 것 같습니다.
	- `질문👀`: 이런 접근 방법으로 개선해보는 게 가능할까요? 가능하다면, 어떤 키워드를 검색해보면 좋을까요? 

<img width="1596" alt="Pasted image 20220503112639" src="https://user-images.githubusercontent.com/96630194/166413551-ea09892b-b654-457e-8a39-938a61a8e41f.png">

### 3. 재고 변동을 전달 받는 방식
활동학습에서 Notification으로 이벤트를 처리하는 방법을 배웠습니다. 이번 쥬스 프로젝트에도 적용해 볼 수 있을 것 같아 재고가 변화될 때마다 알림을 받아 재고 레이블을 업데이트하는 NotificationCenter를 아래와 같이 작성해보았습니다.

```swift
func notification(name: Notification.Name) {
        
        NotificationCenter.default.addObserver(forName: name, object: nil, queue: nil) 
        { 
            Notification in self.updateInventory()
        }
        
        NotificationCenter.default.post(name: name, object: nil)
}

// order에서 notifiation() 호출
func order(juice: JuiceMaker.Menu) {
        // ... 위에 코드 생략
        notification(name: Notification.Name("재고 변화"))
    }
```

`addObserver`와 `post`를 같은 메서드 안에서 호출한 건 이벤트가 일어나는 곳과 처리하는 곳이 동일하다고 생각했기 때문입니다. 현재 상태에서는 `order 메서드`의 `notification()` 호출 하는 자리에 `updateInventory()` 를 넣어도 동일하게 작동합니다.

활동학습 시간에 다뤘던 내용이기에 활용해보려고 했지만, 현재 프로젝트에서는 노티피케이션 센터의 개념을 활용할 때의 장점이 보이지 않았습니다. 오히려 코드가 더 길어지고 가독성이 떨어진다는 생각이 들어, 작성한 내용을 코드에 반영하지는 않았습니다.

1. 현재 코드에 노티피케이션을 활용할 때의 장점이 있을까요?
2. 만약 사용한다고 가정한다면, 아직 Notification 사용법이 익숙치 않아 위와 같이 구현했는데, 이벤트 발생과 처리를 동일한 함수에서 처리하는게 좋은 방향인지 궁금합니다.

2022-05-04 03:04 UTC, leejun6694 requested changes
구현을 잘해주셨지만, 몇 가지 놓친 부분과 고민해보면 좋을 것 같은 코드가 있네요.
확인 부탁드립니다~!

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/InventoryViewController.swift
> +    @IBAction func touchUpDismissButton(_ sender: UIButton) {
이제 우리 `access control` 도 고민해볼까요!?

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var strawberryCount: UILabel!
어떤 UI 인지 naming 에 담으면, 더 가독성이 올라갈 수 있습니다 : )
예) `strawberryCountLabel`

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        strawberryCount.text = String(juiceMaker.store.fruitsInventory[.strawberry]!)
강제 언래핑은 지양했으면 합니다.

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateInventory()
성공인 경우만 불려도 되지 않을까요?

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            self.present(storyboard, animated: true, completion: nil)
`self` 를 사용할 때, 다른 처리는 안해줘도 될까요?

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            (action) in
action 을 사용하지 않는다면 생략 가능해보여요~

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func juiceOrderButtonTapped(_ sender: UIButton) {
method 의 naming 은 동사로 시작하면 어떨까요?
동사 시작이 아니더라도, 다른 것들과 규칙이 통일되면 좋을 것 같습니다.

2022-05-04 03:04 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let selected = sender.currentTitle
button 의 title 을 직접 string 값과 비교하는 것은 예상하지 못한 에러를 발생하기 너무 좋은 환경인 것 같습니다.
어떤 방법들이 있을까요?

2022-05-08 05:57 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/InventoryViewController.swift
> +    @IBAction func touchUpDismissButton(_ sender: UIButton) {
넵, 수정했습니다! 😁

2022-05-08 05:59 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var strawberryCount: UILabel!
쿠마 말씀대로 고치고 나니, 코드를 읽을 때 훨씬 더 이해가 잘 되는 것 같아요 😄

2022-05-08 06:04 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateInventory()
넵 수정했습니다😌

2022-05-08 06:04 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func juiceOrderButtonTapped(_ sender: UIButton) {
다른 메서들 규칙들과 통일하여 동사로 시작하는 네이밍으로 수정했습니다!

2022-05-08 06:07 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        strawberryCount.text = String(juiceMaker.store.fruitsInventory[.strawberry]!)
넵, 닐 코얼레싱으로 언래핑했습니다. 

다만, 닐코얼레싱 쓰면서 nil일 경우 999가 나오게 설정해놨는데, 이런 식으로 써도 될지 궁금합니다. 처음에는 0을 넣으려다가, 오류가 났을 때 재고가 원래 0인 것처럼 보일 수 있을 거라 생각해, 누구든 오류로 인식할 수 있는 999를 넣어놨습니다. 이럴 때 혹시 웹사이트에서 404 에러가 나오듯, 숫자가 의미를 가질 수 있을까 싶어 검색을 해봤지만 그런 자료는 찾지 못했습니다. 

guard let 구문 등을 통해 언래핑 한다면 이런 고민을 하지 않아도 될 것 같은데, 닐코얼레싱이 코드상 더 깔끔해보여서 선택하다보니 이런 고민이 생긴 것 같습니다.

쿠마가 보시기에는 이런 방식으로 언래핑하는 게 적절하게 느껴지시나요?

2022-05-08 06:22 UTC, minsson commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            self.present(storyboard, animated: true, completion: nil)
이 부분에 대해 잘 알지 못해 검색을 해봤습니다. 저희가 이해한 바로는 강한 참조 레퍼런싱이 문제가 되어, 강한 참조를 풀기 위해 제출 코드와 같이 [weak self]를 붙여주면 되는 것 같습니다.

다만 이 부분을 정확하게 이해하기 위해 ARC에 대한 공식문서를 읽어보았지만, 저희 모두 아직 정확하게 이해하지는 못한 것 같습니다. Step 3 수행기간에 한번 더 공부해보겠습니다..!!

2022-05-08 06:29 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let selected = sender.currentTitle
딕셔너리를 이용하면 `switch-case`를 사용하지도 않고,
직접 string 값과 비교하지 않아도 될 듯하여 
최종적으로 딕셔너리로 처리하는 방식으로 수정했습니다.

다른 방법들에 대해서는 회의실에서 피드백 주신 것처럼 UIButton을 extension하여 수정해보는 방향으로도 도전 해보았습니다..!
다만 이게 쿠마가 생각하신 방향이 아닌 것 같아서 주석으로만 남겨 놨습니다.
주석으로 남겨둔 코드에 대한 쿠마의 의견이 궁금합니다😭 

UIButton을 extension하여 적용해 본 방향은 2가지 입니다.

1) `convertOrderButtonToMenuType` 메서드를 사용하여 sender로 받은 버튼아울렛이 어떤  `JuiceMaker.Menu`와 일치하는지 `forEach `구문을 이용해 찾고, 해당하는 쥬스메뉴를 반환하는 방식입니다.
이 방식은 `forEach`를 사용하지 않고 `convertOrderButtonToMenuType`메서드를 사용하는 `tapJuiceOrderButton`에서 바로 처리할 수 있을 것 같아 최종적으로 사용하지 않았습니다.

2) `tag`를 이용하여 각 버튼에 해당하는 `tag`와 `JuiceMaker.Menu`를 매치해보는 방식입니다.
이 방식을 사용하지 않은 이유는 결국 `switch-case`를 이용해서 값을 매치시켜줘야 했고, 무엇보다 태그 속성은 각 버튼에 고유한 태그를 설정하고 있는지 확인하는 메커니즘이 없기 때문입니다.

2022-05-08 06:35 UTC, seohyeon2 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            (action) in
위의 내용처럼 `[weak self]` 처리를 해주려고 보니 `(action) in` 구문이 생략이 되지 않아 그대로 남겨 두었습니다😅

혹시 클로저를 사용하지 않고 해당 내용을 수정하는 방향을 말씀하신 걸까요?😯

2022-05-10 13:03 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        strawberryCount.text = String(juiceMaker.store.fruitsInventory[.strawberry]!)
errorValue 로 사용한다면, `-1` 이 어떨까요?
재고는 음수가 될 수 없으니까요ㅎㅎ

2022-05-10 13:10 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        strawberryCount.text = String(juiceMaker.store.fruitsInventory[.strawberry]!)
아래와 같은 방법은 어떨까요?

```
extension Int {
   var text: String? {
      String(self)
   }
}
```

`strawberryCount.text = juiceMaker.store.fruitsInventory[.strawberry]`

2022-05-10 13:11 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            (action) in
action 을 사용하고 있지 않아서, 생략 가능합니다ㅎㅎ

```
{ [weak self] _ in
   ...
}
```

2022-05-10 13:58 UTC, leejun6694 approved these changes
LGTM

2022-05-10 13:58 UTC, merged