쥬스메이커 [STEP 2] bradheo65, bonf, ZZBAE
yagom-academy/ios-juice-maker pull request #234
Opened 2022-05-03 08:00 UTC by ZZBAE

안녕하세요! @GREENOVER 
쥬스메이커 step 2 PR 보냅니다 😁

#### 고민한 점/해결한 점
1. alert 이벤트
>- 고민한 점: alert 이벤트 생성 후 ViewController로 이동 가능 기능 구현을 어떻게 해야할지..</br>
>- 해결한 점: addAction의 UIAlertAction에서 handler에서 코드 입력 부분에 세그웨이 연결하는 방법 중 하나인 performSegue()를 사용해서 구현해보았습니다. withIdentifier인 부분은 View디렉토리 main에서 원하는 ViewController의 Identifier를 입력해주어 해결했습니다.
```swift
eventFail.addAction(UIAlertAction(title: "예", 
                                  style: .default, 
                                  handler: {_ in
                                            self.performSegue(withIdentifier: "moveToFruitStock",
                                                              sender: nil)}))
```
2. do-catch문의 위치 선정
> - 고민한 점: 처음 do-catch 문이 juiceMaker 클래스 안에 위치해 있었기에 alert 메시지를 어떻게 구현해야 할지 고민하였습니다.
> - 해결한 점: do-catch 문을 viewController에서 구현해주며 alert 메시지를 오류처리에서 구현할 수 있게 되었습니다.

3. 쥬스 생성 알람 한글로 변경
> - 고민한 점 : step01에서 생성하였던 Juice의 이름들이 그대로 나오는 것보다, 초기화면에 나와있는 한글로 변경하기 위해 고민하였습니다.
> - 해결한 점 : Juice 열거형에 한글 이름을 넣은 name 연산 프로퍼티를 추가하여, 초기화면에서 쥬스 생성에 성공할 때 뜨는 얼럿에 한글로 쥬스 이름이 나오게끔 구현할 수 있었습니다.

```swift
 var name: String {
        switch self {
        case .strawberry:
            return "딸기"
        case .banana:
            return "바나나"
        case .kiwi:
            return "키위"
        case .mango:
            return "망고"
        case .pineapple:
            return "파인애플"
        case .strawberryBanana:
            return "딸바"
        case .mangoKiwi:
            return "망키"
        }
    }
```

#### 조언을 구하고 싶은 부분
1. 오류처리 do-catch 문에서 마지막 catch 문을 넣지 않고 defaultError 케이스로 정리하고 싶은데, 어떤 식으로 해결해야할지 그린의 조언이 필요합니다. 😟
2. ViewController 파일에서 과일 재고에 대한 값을 옵셔널 처리를 하나하나 해주고 해당 라벨에 버튼 이벤트마다 호출을 해주었는데, 이 방법보다 더 좋은 방식이 있을지 조언을 구하고 싶습니다.
3. alert event를 기능에 따라 함수로 분리를 해보았는데, 가독성 부분에서 문제가 있지 않을까 고민되어 그린의 개인적인 의견은 어떤지 궁금합니다.

2022-05-03 09:23 UTC, GREENOVER requested changes
@ZZBAE @apwierk2451 @bradheo65 
세분 스텝2도 너무 빠르고 정말 잘 해주셨네요!!
한주의 초반부터 고생 너무 많으셨습니다🥳🥳🥳
이번 스텝에서는 전체적으로 코드가 깔끔하고 구조적이라 세부적인 부분에서만 코멘트를 남겨봤습니다ㅎㅎ
점점 코드적으로 이유있고 성장하시는게 보이네요👍
***
### 칭찬 드리고 싶은 부분
- 코드가 구조적이고 깔끔합니다 💯
- 네이밍이 이전 스텝보다 훨씬 나아졌습니다 💯
- 산출한 기한을 정확히 지키시는 일정관리에서 탁월한 모습 아주 나이스합니다! 💯
- 스텝1에서 요구드렸던 부분이 많이 잘 보완되었네요 💯
***
### 고민 후 해결하셨던 부분에 대한 저의 의견
1. alert 이벤트
- 너무 잘해주셔서 별도 코멘트 드릴게 없습니다!
하나 의견을 던져보고 싶은 부분은 얼럿들이 되게되게 많아지면 어떻게 컴포넌트처럼 사용해볼 수 있을까요?
2. do-catch문의 위치 선정
- 이것도 잘 고민해주시고 충분히 잘 해결해주셨네요.😁
에러처리는 정말 끝단에서 다 끌어와 처리해주는게 맞다고 저도 생각합니다!
3. 쥬스 생성 알람 한글로 변경
- 연산 프로퍼티를 정말 잘 사용하셨네요! 최고입니다.
***
### 조언을 구하시는 부분에 대한 저의 의견
1. do-catch 관련
- 요 부분은 제가 리뷰 코멘트로 조금 더 자세히 남겼습니다..!!
코드와 의견을 같이 남겼으니 확인해보시면 도움이 될것 같습니다ㅎㅎ
우선적으로 간결하게 말씀드려보면 에러처리의 찐 목적을 생각해보면 좋겠습니다😄
2. 과일 재고값 옵셔널 처리 & 버튼마다 updateStock 호출
- 이 부분은 구현자체가 잘못 사용되지 않아서 리뷰 코멘트로는 남기지 않았지만,
사실 지금의 구현도 괜찮지만 updateStock을 구현해주는 부분으로 버튼으로 눌려서 넘어온 과일들(예를들어 딸기쥬스는 딸기만)만 인자로 받아와 해당 과일 Label만 업데이트 쳐주는건 어떨까요?
다른 과일들까지 매번 갱신해줄 필요는 없지 않을까 생각합니다🤔
3. alert 메서드 분리
- 저는 현재 구현에서는 아주 명확하고 너무 좋습니다👍
다만 추후 동일 실패 얼럿에서 타이틀만 바뀌던가 하면 인자로 타이틀만 받아와 해당 얼럿 컴포넌트를 모듈처럼 재사용할수 있으면 좋겠네요!!
***
모두모두 고생 많으셨어요ㅎㅎ
리뷰에 대해서는 의견이니 한번 확인해보시고 리뷰 재요청을 해주시길 바랍니다🙌
화이팅이에요👍👍

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
뷰컨트롤러의 네이밍이 더 명확하면 어떨까요?
추후 VC가 여러개가 될 시를 고려해보면 좋겠습니다🙋🏻

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
@IBAction 선언 및 정의 시 반복되는 코드들에 대해 요러한 반복을 줄여줄 수 있는 방법이 있습니다🙋🏻
구현에 필수 사항은 아니고 스타일의 차이지만 한번 그런게 있구나~하고 찾아보시면 좋을것 같아요!
편리합니다 생각보다 꽤ㅎㅎ

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func strawberryButton(_ sender: UIButton) {
딸기의 갯수를 나타내는 strawberryLabel과의 차이는 Label / Button 이 단어차이인것 같은데 그러면 딸기버튼 이라고 느껴져서 과일쥬스를 주문하는 버튼인지 헷갈립니다🥲
조금 더 괜찮은 네이밍이 있을것 같습니다🙋🏻

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func buttonEvent(juice: Juice) {
버튼 이벤트라는 메서드명 만으로는 어떤 버튼인지 어떤 이벤트인지 잘 모를 수 있을것 같아요..!
해당 구현부가 하는 역할을 메서드로 간결하게 표현해보면 어떨까요?🙋🏻

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func buttonEvent(juice: Juice) {
외부에서 해당 메서드가 호출될 경우가 있나요~?🙋🏻

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateStock() {
요 메서드가 각 @IBAction 버튼들의 클로저로 들어가는것과 buttonEvent에서 호출하는것 어떤것이 더 여러분은 괜찮다고 생각하시나요?🤔

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateStock() {
외부에서 해당 메서드가 호출되는 경우가 있을까요?🙋🏻

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>          }
PR 질문으로 주셨던 부분인데 방법은 있긴합니다.
그런데 왜 마지막 catch문을 없애주고 싶으셨는지 궁금합니다..!
우선 저희가 StockError로 만들어준 케이스 외에도 에러가 발생할 수 있기에 안전장치같이 정말 case의 default 같은 느낌으로 마지막 catch 문이 있게 됩니다.
그런데 이것이 가독이 안좋고 우선적으로 들어온 에러가 저희가 정의해준 에러에 속하는지 파악하고 아니라면 빠르게 다른 처리를 해주고 속한다면 그것에 대해 switch로는 돌려볼 수 있을것 같아요.
음.. 말이 어려운데 코드로 보시죠!
```

do {
  try juiceMaker.makeJuice(of: juice)
  alertSuccessMakeJuice(juice: juice)
} catch {
  guard let error = error as? StockError else {
    return
    // StockError에 속하지 않는 에러가 들어올때 처리
  }
  switch error {
  case .outOfStock:
    alertFailMakeJuice()
    juiceMaker.fruitStore.insufficientStock.removeAll()
  case .defaultError:
    print("defaultError!!")
  }
}
```
저는 이런식을 생각했습니다!

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func alertSuccessMakeJuice(juice: Juice) {
이 메서드는 외부에서 호출될 경우가 있을까요~?🙋🏻

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func alertFailMakeJuice() {
이 메서드는 외부에서 호출될 경우가 있을까요~?🙋🏻

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func alertSuccessMakeJuice(juice: Juice) {
얼럿 메서드명 너무 명확하고 좋네요👍👍👍

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func alertFailMakeJuice() {
얼럿 메서드명 너무 명확하고 좋네요👍👍👍

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let eventSuccess = UIAlertController(title: "성공!", message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
조금 더 적합한 네이밍이 있을것 같습니다!
이 친구의 타입은 결국 UIAlertController이기에 쉽게 말해 얼럿이라는 네이밍을 가져야 되지 않을까해요🤔
밑에서 예를들어보면 present 해줄때 eventSuccess 즉 이벤트 성공을 보여준다보다 성공얼럿을 보여준다가 더 자연스럽지 않을까해서요..!

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let eventSuccess = UIAlertController(title: "성공!", message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
이건 정말 코드 스타일의 차이인데 저는 가로로 긴것보다 세로로 긴걸 선호합니다..!
가로로 길경우 개인의 장비마다 다르다고 생각하기에 가독성에서 조금 떨어지는 측면이 있더라구요ㅠ..
특히 파라미터들이 많아지고 길어지면 아래와 같이 저는 개행을 하는 컨벤션을 사용해요!
```
let eventSuccess = UIAlertController(
  title: "성공!",
  message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!",
  preferredStyle: .alert
)
```
이건 정말 정말 스타일의 차이이니 이런것도 있구나~ 하고 봐주시면 될것 같습니다😄

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print("알 수 없는 에러!!")
이 에러 케이스의 같은 경우에는 사용자에게 별도로 안내를 하지 않아도 괜찮을까요?🤔

2022-05-03 09:23 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Error/StockError.swift
> +    case defaultError
에러 케이스명이 조금 불명확한것 같아요..!
StockError.defaultError라고 생각해보면
재고에러.기본에러 느낌인데 에러라는 네이밍이 중첩되는것 같아요🙋🏻
추가로 기본에러를 어떤 느낌으로 사용하시는건지 의견이 궁금합니다🤔

2022-05-03 09:23 UTC, GREENOVER commented on README.md
> +### Step 02
크.. 스텝2까지도 리드미 작성을 성실히 잘 해주셨네요!!
최고입니다👍👍👍

2022-05-03 23:52 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        eventFail.addAction(UIAlertAction(title: "아니요", style: .destructive, handler: nil))
destructive는 HIG에서는 삭제/제거 시에 사용되는것 같아요~!
우리가 원하는 뷰의 형태와는 동일할 수 있으나 HIG에서 요구해주는것과는 약간 다른것 같습니다! 어떻게 하면 좋을까요~?🙋‍♂️

2022-05-04 02:58 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var pineappleLabel: UILabel!
이 프로퍼티들은 외부에서 호출될 일이 있을까요~?

2022-05-04 03:25 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func strawberryButton(_ sender: UIButton) {
그린의 추천대로 과일쥬스를 주문하는 뜻을 가진 order(과일이름)JuiceButton 으로 변경하였습니다! 😆
(그리고 추후 재변경 예정입니다)

2022-05-04 03:26 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func buttonEvent(juice: Juice) {
실행하다라는 execute 동사를 사용하여, executeFruitJuiceMaking 으로 변경해보았는데 그린의 의견은 어떠신가요? 🥸

2022-05-04 03:26 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func buttonEvent(juice: Juice) {
외부 호출될 경우가 없어 앞에 private 을 붙여줬습니다.

2022-05-04 03:26 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateStock() {
외부 호출될 경우가 없어 앞에 private 을 붙여줬습니다.

2022-05-04 03:27 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func alertSuccessMakeJuice(juice: Juice) {
외부 호출될 경우가 없어 앞에 private 을 붙여줬습니다. 메서드명 명확하다고 해주셔서 감사합니다! 😎

2022-05-04 03:27 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func alertFailMakeJuice() {
외부 호출될 경우가 없어 앞에 private 을 붙여줬습니다.

2022-05-04 03:28 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let eventSuccess = UIAlertController(title: "성공!", message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
그린의 조언대로, 성공얼럿과 실패얼럿을 보여준다는 의미로 eventAlertSuccess, eventAlertFail 로 네이밍 변경해주었습니다! 🫡

2022-05-04 03:28 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let eventSuccess = UIAlertController(title: "성공!", message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
🫡

2022-05-04 03:28 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print("알 수 없는 에러!!")
print(error) 로 변경해보았는데, 괜찮을까요? 별도로 안내를 해야하는지 안해도 되는지 잘 모르겠어서.. 그린의 의견은 어떠신가요? 🥲

2022-05-04 03:28 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Error/StockError.swift
> +    case defaultError
옵셔널 바이닝 오류 처리를 위해 사용한 defaultError 인데, 이 네이밍 대신 optionalBindingError 로 변경해주는게 명확해보일까요??

2022-05-04 03:29 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        eventFail.addAction(UIAlertAction(title: "아니요", style: .destructive, handler: nil))
빨간색으로 표시하려고 destructive을 사용 했었지만, HIG에서 cancel 시에 아니오 버튼을 왼쪽으로 이동시켜 주는 것을 확인하여 cancel 로 변경해주었습니다.

2022-05-04 03:29 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var pineappleLabel: UILabel!
@IBOutlet weak private var 로 바꾸어주었습니다!

2022-05-04 04:32 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func buttonEvent(juice: Juice) {
훨 명확해졌습니다!
그런데 다시 생각해보니 위 @IBAction의 메서드들부터 약간은 모호해서 여기까지 온것 같습니다.
저라면 `@IBAction func mangokiwiButtonTapped`와 같이 해당 메서드는 버튼이 탭되었다는 메서드 시그니쳐를 가질 것 같습니다.
이어서 해당 메서드 이름은 결국 쥬스 버튼이 탭되었을때 역할을 보면 쥬스를 만들어주는것이니
단순히 make(juice: )와 같은 네이밍이면 충분히 담을 수 있을것 같다고 생각이 들어요🤔

2022-05-04 04:32 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func strawberryButton(_ sender: UIButton) {
바로 아래 코멘트와 이어지는 느낌이 있어서 아래에서 리코멘트 남겼습니다🙌

2022-05-04 04:36 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let eventSuccess = UIAlertController(title: "성공!", message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
오호 더 명확해져서 좋습니다!
욕심내보자면 워딩 순서를 조금 변경해보는건 어떨까요?
eventAlertSuccess는 "이벤트얼럿성공"의 느낌이 들어서요..!
우리가 필요한건 얼럿 변수이니 단순히 eventSuccessAlert 혹은 successAlert으로도 충분할것 같다고 생각하는데,
어떠실까요~?🙋🏻

2022-05-04 04:37 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print("알 수 없는 에러!!")
아하 이건 현재 기획에는 없지만 추후 현업에서 일하게 되신다면 알 수 없는 에러가 발생했을때 뷰에 나타내서 사용자에게 알려줘야하지 않을까라는 관점에서 여쭤봤습니다!ㅎㅎ
얼럿을 통해 알려줘야되지 않을까해서요~!

2022-05-04 04:39 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Error/StockError.swift
> +    case defaultError
바인딩에러는 StockError와는 무관할것 같아요..!
바인딩에서 else로 떨어지는건 해당 코드쪽에서 처리하는게 맞을것 같다고 느껴집니다🙋🏻
어떤 에러가 발생할지 모르는 상황에서 defaultError를 처리하고 싶으시다면 단순히 unknown이라는 케이스명은 어떨까요?

2022-05-04 05:40 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
JuiceMakerViewController 으로 변경하였습니다!

2022-05-04 05:42 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func buttonEvent(juice: Juice) {
뒤에 Tapped 를 붙여주니까 메서드가 확실해지는 느낌이 듭니다! 저희가 버튼 관련해서 의논해보면서 수정해보겠습니다!
그린의 조언대로 make(juice: ) 라는 네이밍으로 변경 완료하였습니다!

2022-05-04 05:46 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let eventSuccess = UIAlertController(title: "성공!", message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
변수 이름을 eventAlertSuccess(+ eventAlertFail) 를 successAlert(failAlert) 로 바꿔줌으로 더 잘 읽히는 것 같습니다! 감사합니다 그린 ㅎㅎ

2022-05-04 05:49 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            print("알 수 없는 에러!!")
쥬스 메이커 기획에서는 생각을 못해봤지만, 추후에는 에러 발생을 사용자에게 알려줘야하는 부분을 생각해야겠네요..! 그린 조언대로 error 에 대한 얼럿을 새로 생성하였습니다!

2022-05-04 05:50 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Error/StockError.swift
> +    case defaultError
그렇군요! unknown 으로 변경 완료하였습니다!

2022-05-04 05:52 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
저희가 지금 당장 생각나는 것은, 열거형 처럼 switch-case 문을 사용해서 해당 juice가 들어올 때 마다 각각의 버튼의 정보를 넣어주는 방식입니다. 알아보고 있는 중이라 시간이 조금 걸릴 것 같습니다 😖

2022-05-04 06:40 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
아하 좋습니다ㅎㅎ
이에 비슷하게 선언 및 정의를 한번에 해줄 수 있는 방식으로 IBOutletCollection, IBActionCollection 주제로 찾아보셔도 좋을것 같아요!
이건 정말 선택 옵션입니다😄 
부담되는 구현이라면 과감하게 폐기를...!

2022-05-04 07:41 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
여러개의 버튼 이벤트를 sender를 이용하여 한 개의 이벤트로 반복을 줄여줄 수 있었습니다.
그린이 조언해주신 부분과 일치할지는 잘 모르겠지만..! 그린은 어떻게 생각하시나요?! 🫠

```swift
    @IBAction private func orderFruitJuice(_ sender: UIButton) {
        guard let juice = Juice(rawValue: sender.tag) else {
            return
        }
        make(juice: juice)
    }
````

2022-05-04 08:09 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
너무 간결하고 좋습니다!!👍

2022-05-04 08:26 UTC, ZZBAE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateStock() {
buttonEvent 에서 호출하는 것으로 변경하였습니다! 값이 변경된 이후에 업데이트되는게 괜찮다고 생각이 되어서 buttonEvent에서 호출하게 되었습니다. 😁

2022-05-04 08:27 UTC, GREENOVER approved these changes
크.. 여러분 왜이렇게 빠르고 잘하시나요!?
정말 빠른 시간내에 보완된 부분 아주 잘 확인했습니다👍👍👍
다음 스텝으로 넘어가기에 문제될건 없지만 사소한 부분과 로직적으로 생각해볼 부분들에 대해 코멘트를 남겨봤습니다!
만약 수정이 필요하다면 이후 스텝3에서 간단히 같이 보완되면 더 완벽할것 같아요🙌
이번 스텝도 너무 고생 많으셨어요🥳
어프로브 및 머지 하겠습니다!
어린이날 잘 보내세요😁

2022-05-04 08:27 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +//  JuiceMaker - ViewController.swift
사소한 부분이긴 하지만 주석에서는 파일명이 바뀌지 않았네요..!🙋🏻

2022-05-04 08:27 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +          }
여기는 코드 컨벤션(인덴트 수)가 다른것 같은데 이유가 있을까요~?🙋🏻

2022-05-04 08:27 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            return
요 구문을 타면 그냥 return 되는걸로 이해되는데 StockError외에 error가 발생했을때의 처리는 필요 없을까요~?🙋🏻

2022-05-04 08:27 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        self.present(successAlert, animated: false)
파라미터 개행 및 인덴트 컨벤션이 Fail / Unknown 얼럿의 컨벤션과 조금 상이합니다..!

2022-05-04 08:27 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func alertUnknownError() {
한줄 띄워주는 컨벤션들을 유지하셨던것 같은데 여기도 한줄 개행이 되면 어떨까요~?🙋🏻

2022-05-04 08:27 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
크.. 클래스명이 명확해졌네요👍

2022-05-04 08:27 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            updateStock()
updateStock 구현을 보면 쥬스를 만들때마다 모든 사용되지 않은 재고들도 모두 업데이트 쳐줘야되는것 같아요!
그렇다면 지금은 과일이 5개지만 추후 수백/수천가지가 될때 성능이 괜찮을까요..??🙋🏻
해당 과일을 만들때 필요한 과일을 updateStock에 인자로 넘겨줘 판단해서 해당 과일 Label만 업데이트 해주는것은 어떨까라는 의견이 있습니다..!🤔

2022-05-04 08:27 UTC, merged