쥬스메이커 [STEP 3] Baekgom, Kay Ahn
yagom-academy/ios-juice-maker pull request #239
Opened 2022-05-09 12:46 UTC by KayAhnDS

@AppleCEO 
안녕하세요~
쥬스 메이커 STEP3 PR입니다!!
항상 좋은 리뷰와 코멘트 감사합니다!

## 📖 STEP 2에서 받은 리뷰

- Label은 String? 타입이라 String 타입으로 값을 넣어줘야 한다고 생각했습니다. 말씀하신대로 코드에 정답은 없지만 저희가 생각하기엔 String타입이 가장 적합하다고 판단했습니다.
- 코드를 잘 짜는것도 중요하지만 적어도 저희가 작성한 코드에 답변을 할 수 있도록 그런 자세로 임하겠습니다.

## 📖 STEP 3 요구사항

- 네비게이션 아이템 → 오른쪽 닫기  1개
- 화면 진입시 과일의 현재 재고 수량 표시
- -,+ 를 통한 재고 수정
- 오토레이아웃 적용

## 📖 코드 및 구조 설명

### 공통

- 리터럴 값들을 최대한 enum으로 묶어주려 했습니다.

### MakerViewController

- viewDidLoad()에 있었던 bringFruitCount() 함수를 화면이 새로 나타날때 마다 호출 하는 방식으로 수정 했습니다.
- setUpStockValues()에서 네비게이션 방식으로 재고수정 scene을 띄우는 동작 전, ViewController의 프로퍼티 MakerController를 이용하는 방식으로 VC와 VC사이 데이터 전달 통로를 구현했습니다.

### ViewController

- 재고수정 scene title을 코드로 구현했습니다.
- var MakerController: UIViewController? 프로퍼티를 추가해 MakerViewController와 ViewController 사이에 데이터 전송이 가능하게 해주었습니다.
- 재고수정 scene이 새로 띄워질때 마다 각각의 Stepper의 값을 현재 수량과 맞춰주었습니다.
- takeJuiceOrder에서 juiceName에 공백, 개행문자가 들어와도 처리할 수 있도록 구현했습니다.

### JuiceMaker / FruitStore

- 과일 하나의 수량을 수정하는 함수와 과일 전체 수량을 수정하는 함수를 각각 만들어주었습니다.

```swift
func updateAmount(fruitName: FruitKind, fruitAmount: Int) {
	fruitStore.changeFruitAmount(fruitName: fruitName, amount: fruitAmount)
}
    
func updateTotalAmount(editedStock: Dictionary<FruitKind, Int>) {
	fruitStore.changeAllFruitAmount(latestStock: editedStock)
}
```

## 📖 궁금한 점

- MakerViewController 내 orderProcess 함수는 한곳에서 들어오는 값에 따라 처리를 해주었습니다. 반대로 ViewController 내 stepperStrawberryValueChanged와 같이 Stepper의 value를 올려주는 함수는 stepper마다 만들어 주었습니다. 여러개의 버튼을 하나의 IBAction함수에서  처리하는 경우, 각각의 함수를 만들어 처리하는것 중 언제 무엇을 사용해야 좋은지 알고 싶습니다.

2022-05-09 14:16 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.
이번 스텝 쉽지 않았을텐데 빠르게 보내주셨네요! 
@KayAhnDS , @Baek-Gom-95 고생하셨습니다~

질문에 대한 답변
- MakerViewController 내 orderProcess 함수는 한곳에서 들어오는 값에 따라 처리를 해주었습니다. 반대로 ViewController 내 stepperStrawberryValueChanged와 같이 Stepper의 value를 올려주는 함수는 stepper마다 만들어 주었습니다. 여러개의 버튼을 하나의 IBAction함수에서 처리하는 경우, 각각의 함수를 만들어 처리하는것 중 언제 무엇을 사용해야 좋은지 알고 싶습니다.
- 각각의 함수를 만들어주는 것보다 하나에서 처리가 가능하면 더 좋을 것 같습니다. 이 부분 한번 보너스로 진행해봐도 좋을 것 같네요!

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/AppDelegate.swift
> -
사용하지 않는 코드를 지워준 것 좋네요!

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +    }
오호.. bringFruitCount 의 위치를 viewWillAppear 로 변경하셨군요! 이유가 무엇일까요?
viewDidLoad 에는 첫 줄에 super.viewDidLoad() 가 있는데요.
viewWillAppear 에는 super.viewWillAppear 가 필요하지는 않을까요?

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +        case JuiceKind.mangoKiwiJuice.juiceNameRecognize:
오호.. 한글로 하드 코딩 된 것을 열거형을 활용해서 작성한 것 좋네요~ 🔢

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    var MakerController: UIViewController?
변수 이름은 보통 소문자로 시작합니다.
저번에 이야기했던 것처럼 뷰컨트롤러 타입이면 이름에 viewController 가 들어가면 더 좋을 것 같습니다!

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        stockStrawberryStepper.value = retrieveFruitValue(fruit: juiceMakerController.retrieveFruitCount(fruitName: .strawberry))
위에 stockMangoCount 에는 self 를 붙이고 아래 stockStrawberryStepper 에는 self 를 붙이지 않은 이유가 있을까요?
self 는 어떤 의미일까요? ㅎㅎ

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        return fruitAmount
이 부분은 if let 으로 작성해보면 코드가 어떨까요?

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +    var amountInInteger: Int {
"숫자 안에 양"이라고 번역이 되는데요.
어떤 의미일까요?

2022-05-09 14:16 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
for 문을 사용해서 반복이 잘 되게 작성하셨군요! 👍

2022-05-12 06:00 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/MakerViewController.swift
> +    }
- UIViewController을 상속받은 뷰를 로드할때 여러가지 설정들을 마무리해주는 작업을 viewDidLoad()에서 해줍니다. 만약 재정의된 viewDidLoad() 메서드에서 super.viewDidLoad()를 가장먼저 호출하면 viewController 설정을 마무리 하고 필요한 다음 수행문장을 실행합니다.
`
override func viewDidLoad() {
    super.viewDidLoad()
    xxx()
    yyy()
    zzz()
}
`

- 반대로 재정의된 viewDidLoad() 메서드의 마지막에 super.viewDidLoad()가 있다면 viewController 설정을 어떤 작업들 후에 실행해주겠다는 의미입니다.
`
override func viewDidLoad() {
    xxx()
    yyy()
    zzz()
    super.viewDidLoad()
}
`

- 만약 viewDidLoad안에서 아무것도 안하면 선언 안해줘도 된다면
`override func viewDidLoad() {}`


- 무언가 수행하는 문장이 있다면 super.viewDidLoad를 선언 해주는것이 좋습니다.
`
override func viewDidLoad() {
    super.viewDidLoad()
    doSomething()
}`

2022-05-12 06:03 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    var MakerController: UIViewController?
컨벤션은 확인해도 계속 나오는거 같습니다 ㅠㅜ `makerViewController`로 변경하였습니다 🙂

2022-05-12 06:04 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        stockStrawberryStepper.value = retrieveFruitValue(fruit: juiceMakerController.retrieveFruitCount(fruitName: .strawberry))
프로퍼티나 메서드 앞에 붙는 self는 부른 객체를 나타내는 것으로 알고있습니다.

여기서는 ViewController는 실제 인스턴스는 아니지만 UIViewController의 관점에서 볼 때 인스턴스와 비슷한 개념으로 사용됩니다. 즉 여기서 self 는 부른 객체 즉 해당 viewController를 나타냅니다. self가 없어도 현재 구조에서는 해당 viewController는 하나밖에 없기때문에 누가 불렀는지 알 필요는 없는것 같습니다. 🙂

2022-05-12 06:05 UTC, Baek-Gom-95 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        return fruitAmount
생각해보니 guard let 을 사용할 이유가 없는거 같아 말씀하신 if let으로 수정하였습니다 🙂

2022-05-12 06:19 UTC, KayAhnDS commented on JuiceMaker/JuiceMaker/Model/EnumCollection.swift
> +    var amountInInteger: Int {
amountInInteger에서 amountInIntergerType으로 수정했습니다.
원래 표현하려던 의미는 "amount를 정수형으로 표현한" 이였는데 뒤에 Type을 붙여서 형이라는것을 명시해 주었습니다.

2022-05-12 06:20 UTC, KayAhnDS commented
@AppleCEO
안녕하세요 도미닉!
말씀해주신것 수정완료했습니다.
그동안 저희 리뷰 해주셔서 정말 감사합니다!🙇🏻‍♂️🙇🏻‍♂️

2022-05-16 00:41 UTC, merged