쥬스 메이커 [STEP 3] - bradheo65, bonf, ZZBAE
yagom-academy/ios-juice-maker pull request #242
Opened 2022-05-10 07:17 UTC by ZZBAE

@GREENOVER 안녕하세요 !
쥬스 메이커 STEP 3 PR 보냅니다 🥰

# 고민한 점 / 해결한 점

1.  첫 Stepper 기능 구현 시 value에 값을 연결하고 동작해 본 결과 계속 기존 stock에 있던 값을 불러와서 계산을 했었는데, viewdidLoad에서 초기값을 선언해주어서 해결해주었습니다.

2. Stepper 기능 실행 할 때, + 를 누르면 과일재고 초기값인 10에서 더해주는게 아니라 0으로 되돌아가서 하나씩 추가가 되는 문제가 있었습니다. 그래서 Label에 초기값을 설정해준 것 처럼 Stepper에도 value값을 넣어주어 stepper 작동 시 기존값에서 수량이 늘어나고 줄어들 수 있게끔 해주었습니다.

```swift
func setStockAndStepper() {
        if let strawberry = fruitStore.stocks[.strawberry],
           let banana = fruitStore.stocks[.banana],
           let kiwi = fruitStore.stocks[.kiwi],
           let mango = fruitStore.stocks[.mango],
           let pineapple = fruitStore.stocks[.pineapple] {
            
            strawberryLabel.text = "\(strawberry)"
            bananaLabel.text = "\(banana)"
            pineappleLabel.text = "\(pineapple)"
            kiwiLabel.text = "\(kiwi)"
            mangoLabel.text = "\(mango)"
            
            strawberryStepper.value = Double(strawberry)
            bananaStepper.value = Double(banana)
            pineappleStepper.value = Double(pineapple)
            kiwiStepper.value = Double(kiwi)
            mangoStepper.value = Double(mango)
        }
    ````
3. show의 경우 네비게이션이 없을 경우 모달로 표현되는 것을 알게 되었습니다. 근데 present의 경우 Presentation을 automatic으로 할 경우 값이 넘어가지 않고 FullScreen을 해야지만 값이 넘어가게 됩니다. FullScreen을 해야만 JuiceMakerViewController가 DisAppear 되는 것을 확인하여 해결하였습니다.

# 조언을 구하고 싶은 부분

1. 각 라벨에 초기값 설정해 줄 때 for문을 사용해서 구현해보았는데 막상 아래의 코드처럼 작성해보니 계속 맞는지 의문점이 들어서 더 좋은 코드 스타일에 대해 조언을 구하고 싶습니다.
```swift
   private func setStock() {
        let test = [strawberryLabel,
                    bananaLabel,
                    kiwiLabel,
                    mangoLabel,
                    pineappleLabel]
        var i = 0
        for stock in Fruit.allCases {
            guard let stocks = juiceMaker.fruitStore.stocks[(stock)] else {
                return
            }
            test[i]?.text = "\(stocks)"
            i += 1
        }
    }
```

2. Stepper 의 크기가 수정이 안되어 오토레이아웃 변환 시 Stepper를 기준으로 설정 했는데 Stepper 크기가 고정으로 되어 있어 그런건지 조언을 구하고 싶습니다. 

3. 강제 언래핑 !을 사용하지 않는지, 실제로 현업에서는 사용하지 않는지 UILabel!처럼 UI에서 가져오는 프로퍼티들의 강제언래핑은 어떤 의미인지 알고 싶습니다!🥺

2022-05-10 08:47 UTC, GREENOVER requested changes
@ZZBAE @apwierk2451 @bradheo65 
세분 모두 스텝3까지 너무 고생많으셨습니다!!🥳🥳🥳
정말 스텝1부터 3주간 달려오시면서 코드적으로 깔끔해지고 발전해주신게 눈에 보이네요👍
이번 스텝3도 요구사항 및 기능적인 부분에서 전혀 문제되는것이 없었습니다 크..👍
그렇기에 리뷰 코멘트가 주로 놓치셨을것 같거나 코드를 선택하는 부분에 있어 여러분들의 선택 의도나 기준을 묻는 부분이 많았어요ㅎㅎ
아..! 추가로, 스텝3를 잘 깔끔히 끝내주셨고 빠르게 해주셔서 시간이 되신다면 도전해보실만한 로직적으로 분리하는 보너스 스텝같은 코멘트를 남겨보았어요!
(이 부분은 정말 세분의 선택에 의한것으로 부담갖지 않고 해보고 싶으시다면 해보셔도 됩니다.
지금 구조에서 너무 어려울것 같고 많은 리팩토링이 필요할것 같다면 다음 프로젝트에서 요런 로직을 초기부터 생각해보고 하셔도 됩니다🙌)
서론이 너무 길었네요ㅎㅎ
저도 여러분들과 3주간 리뷰를 하면서 놓쳤던것에 대해 다시 학습하게 되고 많이 배울 수 있어 정말 좋은 시간이였습니다!
감사합니다🙇🏻🙇🏻🙇🏻
그럼 리뷰 코멘트와 별개로 PR 코멘트에 대한 답변을 드려보겠습니다🏃🏻🏃🏻
***
### 칭찬 드리고 싶은 부분
- 전체적으로 코드가 많이 깔끔해지고 분리가 잘 되었네요 💯
- 오토레이아웃이 잘 적용되어 어느 디바이스에서나 어색하지 않네요 💯
- 커밋 메시지를 잘 나눠서 해주신 점 💯
- VC, 프로퍼티, 메서드들의 명확한 네이밍! 💯
- 싱글턴을 잘 활용해보신 점 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. ViewDidLoad에서의 초기값 설정
- 아주아주 퍼펙트합니다!
구현 자체는 정말 퍼펙트하고 로직적으로 분리도 잘 되어 있네요ㅎㅎ
하나 욕심내보자면 리뷰 코멘트로도 남기긴했는데 초기 설정을 해주는 반복된 코드들을 로직적으로 줄여보면 어떨까 싶습니다🙋🏻
2. Stepper 동작에 따른 수량 업데이트
- 요 부분도 코드로 잘 구현해주신것 확인했습니다👍
이것도 1번 항목과 마찬가지로 반복되는 코드들만 로직적으로 잡아주면 더 완벽 그자체일것 같아요🙌
3. view present
- 여러분이 생각하실때 그러면 왜 fullscreen이 아니면 기존 뷰가 disappear되지 않는것일까요~?🙋🏻
더 나아가 모달과 네비게이션을 앞으로 어떤 상황에서 써야겠다는 세분의 명확한 기준이 잡히셨는지 어떤것인지 궁금합니다!
***
### 조언을 요청하시는 부분에 대한 저의 의견
1. 라벨 초기값 설정 시 코드 스타일에 대해
- 예제 샘플 코드 잘 보았습니다..!
그런데 이전에 한번 스쳐지나가면서 언급한것 같은 부분이 있어서요..!
지금같은 IBOutlet 프로퍼티에 대해 반복적으로 초기값을 설정해주실때 저렇게 어레이에 담는것도 방법이겠지만,
IBOutlet Collection이라는 개념을 활용하면 조금 더 깔끔하고 어레이에 label을 넣어줄때 반복되어 나타날 수 있는 휴먼에러를 피할 수 있을것 같습니다🙋🏻
그렇게 된다면 반복을 시켜줄때도 별도의 i 변수가 필요없이 forEach를 활용하면 몇줄의 코드로 깔끔하게 표현될 수 있을것 같아요!
요 부분에서 핵심 개념은 outlet collection과 forEach가 될것 같습니다😀
2. Stepper의 사이즈에 대해
- 제가 알기로는 UIStepper나 UISwitch와 같은 친구들은 자체적으로 지금 시도하셨던 방법으로는 사이즈 조절이 안됩니다😭
즉, 기본적으로 지원하지 않습니다ㅠ..
그럴때 방법은 네가지가 생각나는데요..!
하나, 커스텀하게 UIStepper를 자체적으로 만들어보는 방법
이 방법은 사실 많은 코드적인 부분이 들어가기에 현재 단계보다는 추후 한번 도전해보는것이 좋을것 같아요.
둘, 상속을 통해 재정의해버리기!
요것도 저는 안해봤기에 이렇게 하면 될것 같긴합니다만 UIStepper를 까봐야 알겠네요🥲
셋, 코드로 만들어버리기~
```swift
let stepper = UIStepper (frame:CGRect(x: 0, y: 0, width: 100, height: 50))
```
이렇게 스토리보드로 뷰를 만드는것이 아닌 코드로 만들어버리면 가능합니다.
(코드로 뷰를 짜는것이 익숙하면 제일 좋은 방법이겠네요..!)
넷, transform을 활용하기
요건 레퍼가 더 정확할것 같아 이런 방법도 있다는 레퍼를 공유드리겠습니다!
https://stackoverflow.com/questions/12180182/changing-the-size-of-uistepper/28446973

3. 강제 언래핑에 대해
- 기본적으로 저는 UI요소 외에는 강제 모든 코드에서 강제 언래핑을 하고 있지 않습니다..!
일단 여러분들도 잘 아시겠지만 강제 언래핑은 앱의 크래쉬를 일으키는 가장 주요 원인입니다.
(나중에 코드가 복잡해지면 어디서 크래쉬가 터졌는지 찾는것도 일ㅠㅠ..)
그렇기에 많은 회사에서 SwiftLint, SwiftFormat과 같은 코드 컨벤션을 강제로 맞춰주는 라이브러리를 통해 강제 언래핑에 대해 금지되도록 하는 룰을 많이 따르고 있어요! (저도 그렇구요..!)
그런데 IBOutlet에서 강제 언래핑을 왜 해줄까요?
분명 저도 바로 위에서까지 강제 언래핑 절대안돼 네버네버 했는데 말이죠..!?
우선 IBOutlet을 정확히 알아볼 필요가 있을것 같아요.
이 친구는 스토리보드나 nib에서 UI 요소 즉 뷰를 설정해주는 프로퍼티입니다.
즉 여기서 짚고 넘어갈점은 View와 관련이 깊다는것이죠!
IBOutlet은 스토리보드의 View와 IB(Interface Builder)를 연결해줍니다.
그렇기에 IBOutlet이 만약 강제 언래핑을 통해 에러가 나는 상황이라면 올려준 뷰가 정상적으로 보이지 않는것이 될거에요.
즉 조금 정리하자면, IBOutlet은 강제언래핑만 되는것이 아니고 IBOutlet에 한해서만 강제 언래핑을 권장합니다.
이유는 예를들어보면 우리가 IBOutlet으로 어떤 요소를 올려서 나타낸다고 생각해보죠.
그럴때 만약 IBOutlet이 nil이게 되면 우리가 표현하고자하는 뷰 자체가 정상적이지 않게 될거에요.
그럴때는 앱의 크래시가 중요한게 아니고 꼭 고쳐야하는 부분입니다.
그렇기에 앱의 크래시보다 IBOutlet이 올바르지 않다면 고치는것이 권장되기에 강제 언래핑을 해주고 있습니다.
또한 사실 IBOutlet 객체를 사용하지 않는다면 선언 및 정의도 하지 않아야되는것이 맞으니 정말 제대로 사용만 한다면 강제 언래핑을 해주는것이 오히려 이득이 될 수 있겠어요!
써놓고 보니 너무 주절주절 말이 길었네요🥲
혹시 이해가 안가신다면 디엠 주세요!ㅋㅋ
***
다시 한번 고생많으셨어요ㅎㅎ
시간적 여유가 있어 우선은 보완되면 좋을 부분도 있기에 request Change로 남겨놓겠습니다~!
언제나 리뷰 재요청 주시면 됩니다🙌

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
해당 프로퍼티들은 외부에서 사용될 경우가 있을까요??🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBAction func changeStepperValue(_ sender: UIStepper) {
요 메서드도 외부에서 사용될 경우가 있을까요~?🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    }
viewDidLoad에서 올바른 일을 해주고 있네요👍

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            }
구현 좋네요..!👍
로직에 전혀 이상은 없습니다.
다만 현재 마지막 스텝이고 정말 옵션적인 부분인데 만약 재고를 stepper로 조정해줘야하는 과일이 한 백가지가 된다면 현재 코드가 너무 방대해질것 같아요!
로직적으로 반복되는것들을 분리해보거나 개선해볼 수 있을까요~?
만약 하다가 현재에서는 너무 어렵다 판단되면 추후에도 충분히 해볼 수 있으니 너무 부담갖지 않으셔도 됩니다🙌
(여러분들이 빠르고 구현을 잘해주셔서 보너스 스텝같은..!?)

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +
해당 개행을 해주신 의도가 있으실까요~?🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBAction func backButton(_ sender: UIBarButtonItem) {
해당 메서드가 외부에서 호출되는 경우가 있을까요~?🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    func setStockAndStepper() {
해당 메서드도 외부에서 호출되는 경우가 있을까요~?🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            mangoStepper.value = Double(mango)
위 코멘트와 중복이 되는것 같은데 약간의 보너스 스텝같이 느껴보시면 좋을것 같아서요..!
정말 극과 극으로 과일의 갯수를 생각해봤을때 추후에 코드의 유지보수가 힘들지 않을까해서요🤔
어떻게하면 이런 반복적인 보일러 플레이트 코드들을 로직적으로 풀어낼 수 있을까요?🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      }
viewWillAppear로 로직을 전환시켜준 이유가 어떤것이셨는지 궁금합니다🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +//  JuiceMaker - JuiceMakerViewController.swift
명확한 VC명 좋네요!👍👍

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            make(juice: juice)
if let 바인딩을 택하신 이유가 어떤걸까요~?
여러분들은 guard let과 if let을 어떤 차이를 기준으로 사용하시나요?🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            make(juice: juice)
make(juice: juice)를 풀어보면
make juice juice인데 조금 중복되는 부분이 어색하게도 느껴집니다🥲
해당 함수의 파라미터를 언더바 처리를 해주면 어떨까요~?

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            pineappleLabel.text = "\(pineapple)"
요기도 어떤 기준에서 if let을 사용해주셨는지 궁금합니다🙋🏻
(정답이 없는 부분으로 정말 궁금해서 여쭤봅니다ㅎㅎ)

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func make(juice: Juice) {
위에서 언급한 부분이긴한데 여기서 언더바 처리가 있다면 호출 시 더 자연스러울것 같아요😄

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +    let fruitStore = FruitStore.shared
싱글턴으로 잘 활용해주셨네요👍

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    init() {
외부에서 fruitStore을 이니셜 시 과일 초기 수량을 주입해서 넣어주던 부분을 제외해주셨는데 어떤 이유가 있으셨을까요??🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    let fruitStore = FruitStore.shared
요 프로퍼티를 외부에서 사용될 경우가 있을까요~?🙋🏻

2022-05-10 08:47 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func updateStock() {
해당 updateStock 메서드가 쥬스를 만드는 make에서도 성공 시 불리게 되는데 딸기, 바나나만 사용해서
과일을 만들었어도 updateStock을 부르게 되어 사실상 모든 재고를 다시 update해주게 되는데 추후 과일이 수백개가 되면 성능에 문제는 없을까요?🤔

2022-05-10 08:48 UTC, GREENOVER commented
아..! 스텝3도 리드미를 작성해놓으시면 훨씬 도움 많이 되실겁니다🙌🙌🙌

2022-05-12 07:31 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBAction func changeStepperValue(_ sender: UIStepper) {
없네요..🫡
```swift
    @IBAction private func changeStepperValue(_ sender: UIStepper) {
```
로 변경했습니다.

2022-05-12 07:31 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
IBOutlet Collection을 이용하여 코드의 간결화 및 은닉화를 표현하겠습니다.

2022-05-12 07:31 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    }
😜

2022-05-12 07:31 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBAction func backButton(_ sender: UIBarButtonItem) {
```swift
    @IBAction private func backButton(_ sender: UIBarButtonItem) {
```
로 변경해주었습니다.

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    func setStockAndStepper() {
```swift
    private func setStockAndStepper() {
```
로 변경해주었습니다.

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      }
viewDidLoad() 인 경우 최초 실행 시 한번만 실행 되기 떄문에 viewWillAppear를 이용해서
JuiceMakerViewController 로 전환 시 라벨에 대한 재고를 업데이트 해줘야하기때문에 사용했습니다.

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +//  JuiceMaker - JuiceMakerViewController.swift
🫡

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            make(juice: juice)
첫번쨰 질문에 대한 답변으로는 guard let 사용 시 return 값에 대한 처리 해주기 애매해서 if let 바인딩을 사용해주었습니다.

두번째 질문에 대한 답변은
아래의 코드처럼 변경해 보았습니다. 언더바 보단 to를 사용해주어서 좀 더 명확하게 표현해 보았습니다.
```swift
    private func make(to juice: Juice) {
```
```swift
    private func alertSuccessMakeJuice(to juice: Juice) {
```

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            pineappleLabel.text = "\(pineapple)"
위에 있는 질문에 대한 답변과 동일하게 guard let 사용 시 return 값에 대한 처리 해주기 애매해서 if let 바인딩을 사용해주었습니다.

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func make(juice: Juice) {
```swift
    private func make(to juice: Juice) {
```
로 변경하겠습니다.

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +    let fruitStore = FruitStore.shared
😜

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    init() {
싱글턴 사용 시 이니셜라이져의 파라미터를 제외해야 되서 상수로 선언 해주었습니다.

2022-05-12 07:32 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    let fruitStore = FruitStore.shared
```swift
    private let fruitStore = FruitStore.shared
```
로 변경해주었습니다.

2022-05-12 07:33 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +
실수인 것 같습니다.

2022-05-12 07:36 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            }
IBOulet Collection 을 사용해서 정리해보았는데 GREEN의 의견은 어떤지 궁금합니다!
```swift
    @IBAction private func changeStepperValue(_ sender: UIStepper) {
        if let fruit = Fruit(rawValue: sender.tag) {
            fruitLabels[sender.tag].text = Int(fruitSteppers[sender.tag].value).description
            fruitStore.stocks[fruit] = Int(fruitSteppers[sender.tag].value)
        }
    }
```

2022-05-12 07:37 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            mangoStepper.value = Double(mango)
IBOulet Collection 을 사용해서 정리해보았는데 GREEN의 의견은 어떤지 궁금합니다!

```swift
    private func setStockAndStepper() {
        for fruitIndex in 0..<fruitLabels.count {
            guard let fruit = Fruit(rawValue: fruitIndex),
                  let fruitStock = fruitStore.stocks[fruit] else {
                return
            }
            fruitLabels[fruitIndex].text = fruitStock.description
            fruitSteppers[fruitIndex].value = Double(fruitStock)
        }
    }
```

2022-05-12 07:39 UTC, bradheo65 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func updateStock() {
IBOulet Collection 을 사용해서 정리해보았는데 GREEN의 의견은 어떤지 궁금합니다!

선언 메소드
```swift
    private func make(to juice: Juice) {
        do {
            try juiceMaker.makeJuice(of: juice)
            alertSuccessMakeJuice(to: juice)
            juice.recipe.keys.forEach { fruit in
                if let fruitStock = juiceMaker.fruitStore.stocks[fruit] {
                    updateStock(fruit: fruit, stock: fruitStock)
                }
            }
        } catch {
```

초기 실행 시 각 과일 라벨에 대해 업데이트 해주는 메소드
```swift
    private func setStock() {
        for fruitIndex in 0..<fruitLabels.count {
            guard let fruit = Fruit(rawValue: fruitIndex),
                  let fruitStock = juiceMaker.fruitStore.stocks[fruit] else {
                return
            }
            fruitLabels[fruitIndex].text = fruitStock.description
        }
    }
```

2022-05-12 08:59 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            }
크 너무 잘 사용하셨습니다!
너무 좋네요👍

2022-05-12 09:01 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            mangoStepper.value = Double(mango)
위와 더불어 너무 깔끔하고 로직적이네요👍👍

2022-05-12 09:05 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            make(juice: juice)
오 to 전치사 활용 좋네요👍👍
guard let 으로 else 구문에서 return 처리가 애매한게 이해가 잘 되지 않았습니다..!
해당 메서드는 Void를 반환함으로 else에서 return으로 할때 어떤게 애매했을까요~?🙋🏻
guard let과 if let을 명확히 어떤 기준으로 사용하는지가 상세히 궁금했어요🤔
조금 더 자세히 설명해주시면 감사하겠습니다!
(아 물론 if let이 어색하고 guard let으로 하는게 더 적절하다 라는 소리는 아닙니다..!!)

2022-05-12 09:14 UTC, GREENOVER approved these changes
모두 고생 많으셨습니다!
사소한 코멘트 몇개만 참고사항으로 남겨보았어요ㅎㅎ
기능 구현도 아주 잘 되어있고 코드 로직도 깔끔하고 흠잡을데가 없네요👍
3주간 너무 발전하셨고 수고하셨습니다🙌
언제든 리뷰어와 리뷰이가 아니더라도 소통하면서 지내요 여러분!

2022-05-12 09:14 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +class FruitStoreViewController: UIViewController {
더이상 다른 부분에서 상속 하지 않는 클래스라고 판단되면 final 키워드를 붙여 성능을 높이는 방법도 있습니다🙋🏻
https://developer.apple.com/swift/blog/?id=27

2022-05-12 09:14 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private func setStock() {
순서상 setStock 메서드가 먼저 정의 및 구현되어 있는것이 더 가독이 좋을것 같습니다🙋🏻

2022-05-12 09:14 UTC, GREENOVER commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +                                             preferredStyle: .alert)
요런 코드 스타일은 어떠신가요?
가독성이 저는 더 좋다고 판단해서 사용합니다🙋🏻
```swift
let successAlert = UIAlertController(
  title: "성공!",
  message: "\(juice.name)쥬스 나왔습니다! 맛있게 드세요!",
  preferredStyle: .alert
)
```

2022-05-12 09:14 UTC, GREENOVER commented on README.md
> +# 쥬스메이커
마지막까지 리드미 작성 최고입니다 👍👍

2022-05-12 09:14 UTC, merged