쥬스메이커 [STEP 3] hugh, yeton
yagom-academy/ios-juice-maker pull request #244
Opened 2022-05-11 14:29 UTC by yeeton37

안녕하세요 제이슨! @ehgud0670 
step3 PR을 기한 안에 못 제출해서 아쉽습니다 ...🙈🙈

이번에는 데이터 전달 방식(Notification Center, delegate, 저장 프로퍼티를 넘겨주는 방식) 3가지를 모두 사용해보았습니다.
덕분에 데이터 전달 방식에 대해 빠삭하게 공부한 것 같습니다...📝

기능 구현과 고민한 점에 대해 아래에 적어보았습니다! 

## Step3 기능구현
- EditStockViewController
  - stepper를 통해 EditStockViewController의 fruitsStock을 변경하고 delegate를 통해 HomeViewController에 전달
  - 메서드 tapCloseButton을 통해 화면 닫기
- HomeViewController
  - EditStockViewController로 부터 전달받은 데이터를 메서드의 파라미터로 사용해 FruitStore의 stock 변경
- Stepper 타입 만들기
  - 각각의 Stepper의 타입을 만들어주었다. 
- 화면간의 데이터 전달
  - HomeViewController에서 EditStockViewController로 저장 속성을 통해 데이터 전달
  - EditStockViewController에서 HomeViewController로 Delegate를 통해 데이터 전달
- Delegate 패턴
  - Delegate를 사용하기 위해 프로토콜 생성
  - HomeViewController에서 프로토콜 채택
  - HomeViewController에서 대리자 설정
  - EditStockViewController에서 Delegate를 통해 HomeViewController로 데이터 전달
- Auto Layout
  - 다양한 기기에서 View가 잘 적용되도록 Auto Layout설정
- StoryBoard 나누기
  - Main 스토리보드에서 나눌 ViewController를 선택해 editor의 Refactor To Storyboard를 사용하면 새로운 Storyboard 파일 생성
  - 중요한 point! Main Storyboard파일에 생성된 Storyboard Reference의 Referenced ID를 새로운 파일에 있는 ViewController의 ID와 동일하게 설정
 
## 고민했던 것들
1. 화면 간의 데이터를 전달하는 방법에 대해 고민했습니다.

  - Model에 있는 FruitStore의 stock을 HomeViewController에 전달하는 방법은 NotificationCenter를 사용했습니다.
  - HomeViewController와 EditStockViewController 사이의 데이터 전달은 저장속성을 통한 전달 방법과 Delegate 패턴 전달 방법을 사용했습니다.
 
 이번 프로젝트에서는 코코아 버전의 MVC를 사용했기에 View와 Controller가 명확히 구분되지 않았습니다... 그래서 편의상 설명할 때 ViewController라고 칭하겠습니다!.
 
 먼저 저희가 애플 문서를 읽어보니 Model과 ViewController사이에서는 Observer패턴을 자주 사용한다고 나와있어서 Model과 ViewController 사이의 데이터 전달 방식을 Notification으로 했습니다. 다수의 이벤트가 발생했을 때 사용하기 편리한 방법인데, 이번 프로젝트에서는 다수의 이벤트가 발생하지는 않았지만 공부한 김에 사용해보고 싶어서 써봤습니다..! 
 또, ViewController끼리는 의존성이 강해지면 분리하기 어려워 좋지 않다고 생각을 해서 프로토콜을 채택하는 방식인 delegate 패턴 전달 방식을 사용해서 의존성을 낮춰주는 방식을 사용했습니다. 두 번째 화면이 present될 때 데이터를 전달해 주도록 했습니다!
 
**_데이터 전달 방식을 괜찮게 선택한 것인지 궁금합니다!_**

  - Delegate의 대리자 설정 관련하여 고민했습니다.
 
`editStockVC.delegate = self`

처음에는 EditStockViewController에서 HomeViewController의 메서드를 실행시키기 위한 데이터를 전달해 주기 때문에, HomeViewController이  EditStockViewController에게 너가 데이터를 보내줘! 라고 하면서 EditStockViewController을 대리자로 만들어준다고 생각을 했습니다.  

그런데 다시 고민해보니 EditStockViewController는 데이터를 전달만 해주고 HomeViewController에서 데이터를 받아 일을 대신해주기 때문에( 함수의 정의도 이 곳에서 일어나기 때문) 대리자가 HomeViewController가 된다는 것을 알게되었습니다.
처음 delegate를 사용해보니 개념이 매우 헷갈렸던 것 같습니다...

- Stepper를 통한 데이터 전달을 어떻게 해줄지 고민했습니다.

updateStepperValue에서 생성된 데이터를 화면의 ` 닫기` 버튼이 눌렸을 때 한 번만 전달할지, Stepper 이벤트가 발생할 때마다 전달할지를 고민했습니다. 
저희가 생각하기로는 Stepper 이벤트가 발생할 때마다 데이터를 전달해주면 변경될 때마다 FruitStore의 stock을 계속 변경해서 notificationCenter로 post를 해주기 때문에 이 방식은 비효율적이라 생각했습니다. 

반면, 데이터를 화면 닫기 버튼을 눌렀을 때만 전달하게 되면 한 번에 데이터를 전달한다는 장점은 있지만, FruitStore의 stock 자체를 변경해준다기보다는 EditStockViewController에서 전달받은 stock으로 대체한다는 느낌이 들어 약간 어색함이 느껴졌습니다.

**_닫기 버튼이 눌렸을 때 데이터를 전달하는 방식과 stepper의 value가 변경될 때마다 데이터를 전달해주는 방식 중 어떤 것이 더 괜찮은 선택이었을지 여쭤보고 싶습니다!_** 

이번 PR도 잘부탁드려요✨✨

2022-05-12 03:26 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private(set) var store = FruitStore()
잘하셨어요. 이제야 보이네요.
솔직히 FruitStore는 객체가 아닌 자료구조 같아요! 보면 FruitStore는 메소드도 stock의 값을 get/set 하거나 decrease 하는 정도 밖에 없으므로, 즉 자신의 내부 값인 모델 관련해서만 메소드가 있으므로 자료구조로 보는게 맞겠습니다.
즉 JuiceMaker는 객체로서 역할을 하니 class가 어울리지만 
FruitStore는 자료구조이므로 struct가 어울립니다. 
객체와 자료구조가 무엇인지는 궁금하다면 클린코드 6장 [객체와 자료구조](https://github.com/BoyScout2021/CleanCode/blob/main/Chapter_06_%EA%B0%9D%EC%B2%B4%EC%99%80_%EC%9E%90%EB%A3%8C_%EA%B5%AC%EC%A1%B0/ehgud0670.md)를 읽어보세요! 😁

ps. 참고용으로 제 요약글을 링크로 드린거지 책으로 읽는게 훨씬 낫습니다 ㅋㅋㅋ

2022-05-12 03:41 UTC, ehgud0670 commented on JuiceMaker/EditStock~.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
이 파일은 지워줘도 될듯 합니다

2022-05-12 03:47 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/EditStockStepper.swift
> +class EditStockStepper: UIStepper {
View는 View 폴더에 이동시키면 될 듯 합니다. 
그리고 클래스 하나 당 하나의 파일로 또 나눠주시면 파일 및 클래스를 파악하기 좋습니다. 
View 폴더안에 Stepper 폴더를 하나 더 만들어서 파일들 나눠주시면 더 좋겠네요~

아 그리고 스토리보드파일 들은 보통 StoryBoard 폴더를 만들어서 따로 분류하고 assets 파일은 Resource 폴더를 만들어 관리하곤 합니다. 정답은 없기때문에 한번 고민해보시고 폴더링해보세요~

ps. 화면별로 View/Controller/Model 폴더를 따로 만들어도 됩니다.
ex) Home > View, Controller, Model
ex) Edit > View, Controller, Model 
이렇게 하면 파일이 많이 늘어나도 파일들을 파악하기 더 수월하다는 장점이 있습니다.

2022-05-12 06:44 UTC, ehgud0670 requested changes
지금 시간이 없어서 이정도만 리뷰 드리겠습니다.
이따가 더 드릴게요, 화이팅하세요! 
의문 있는거 있으시면 말씀주세요~~

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    private var transferStock = [Fruit: Int]()
transferStock을 따로 만들기 보다는 juiceMaker.fruitStore.stock 만으로 모델이 관리가 되어야 합니다. editVC에게 전달할때도 editVC로부터 다시 받아서 업데이트할때도 juiceMaker.fruitStore.stock로만 사용하세요.

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
>              label.text = "\(fruitLabel)"
label.configure(with: stock)이 되도록 하는 건 어떨까요?
메소드로 인수정도로 모델을 알고 있는 것은 괜찮습니다.
그리고 이렇게 메소드를 만들어버리면 label 관련해서 모델값과 관련해 변경할 게 많을때 한번에 처리도 되서 좋습니다.
뷰도 객체이므로 뷰의 변화를 뷰의 메소드를 만듦으로서 처리할려고 노력해보세요

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(getFruitStock), name: .notifyStock, object: nil)
updateFruitStockLabel이 더 나을 듯 하네용 
getFruitStock가 무슨 의도인지는 알겠으나 옵저빙하면 notification의 데이터를 가지고 오는 것은 어떻게 보면 당연한 거라서,
옵저빙함으로써 어떤 처리를 할것인지 좀더 의도가 분명히 보이는 updateFruitStockLabel(notification:)이 더 괜찮을 듯 하네요 :)

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
>              label.text = "\(fruitLabel)"
그리고 stock[fruit] 이 Int인데 fruitLabel이라고 하는게 좀 어색하네요. 
UILabel이 반환된 것 같아서요~

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
>          }
여기도 한번 더 메소드를 추상화할수 있습니다
configureOrderButtons 이런식으로요

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
>          }
또 보통 Action 함수의 네이밍은 '주어 + 동사 + 목적어' 형태를 사용합니다.
따라서 selector의 order 메소드 말고 orderButtonDidTap으로 네이밍 변경하면 좋을 것 같아요 :)
order는 orderButtonDidTap 안에서 호출되고요 😁

[참고 링크](https://github.com/StyleShare/swift-style-guide#%ED%95%A8%EC%88%98) 드릴게요~

> 좋은 예

```

func backButtonDidTap() {
  // ...
}
```

> 나쁜 예

```
func back() {
  // ...
}

func pressBack() {
  // ...
}
```

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/TransferDelegate.swift
> +protocol TransferDelegate: AnyObject {
EditStockViewController의 Delegate라면 보통 EditStockViewControllerDelegate라고 짓습니다. 
`대상자 + Delegate` 로요
참고하세요.

https://github.com/StyleShare/swift-style-guide#delegate

2022-05-12 06:44 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/TransferDelegate.swift
> +    func transfer(changedStock: [Fruit: Int])
그리고 함수는 자기자신이 함수명에 들어가 있고, 보통 자기 자신을 넘길 수 있도록 만듭니다 

ex) `editStockViewControllerDidChangeStock(_ editStockViewController: EditStockViewController)`

2022-05-12 06:55 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +    var fruitsStock = [Fruit: Int]()
private으로 제한 부탁드립니다. 
아예 fruitStore을 HomeVC에서 EditVC로 넘기는 건 어때요?
그럼 fruitStore의 fillStock도 다시 살아날 수 있겠네요.
모델 값으로서 딕셔너리나 배열 타입이 있다면 한번 더 래핑하여 해당 값들을 관리 하는 객체가 따로 있는게 좋습니다.

2022-05-12 06:59 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +    var fruitsStock = [Fruit: Int]()
fruitStore 처럼 fruitsStock를 관리하는 struct나 class 를 만들어보세요~
private으로 굳이 할 필요는 없네요. 이해했습니다.

2022-05-12 07:17 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private(set) var store = FruitStore()
하지만 FruitStore 가 NotificationCenter post 를 직접하므로 struct 인 것은 애매하네요. 노티를 store에서 한다면 그대로 class 두시는게 나을 듯 합니다. 
다만 JuiceMaker를 class, FruitStore가 struct가 되어 FruitStore의 변화가 있을때 레퍼런스 타입인 JuiceMaker가 post를 하면 괜찮긴합니다. 
이 코멘트 포함하여 이해가 잘 안되신다면 현재처럼 그냥 두시면 될 듯해요~

2022-05-12 07:31 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
notify는 저번에 말씀드린것처럼 노티를 보낼때 어울리는 네이밍이라 다른 네이밍으로 변경할 필요가 있겠습니다!
store.stock을 그대로 써도 되긴해요 사실 둘 다 private(set)으로 read only 여서요!

2022-05-12 11:00 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +        <!--EditStockViewController-->
지금도 좋긴한데 Main.storyboard 에서 아예 EditStockVC가 빠지도록, 즉 아예 독립적으로 되도록 해보시는 건 어떨까요?
그렇게 보통 더 사용해서요!

2022-05-12 11:49 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +    weak var delegate: TransferDelegate?
weak var 잘하셨습니다! 👏👏👏

2022-05-12 14:38 UTC, Hugh-github commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +    weak var delegate: TransferDelegate?
감사합니다!! 🥳🥳🥳

2022-05-13 09:15 UTC, yeeton37 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    private var transferStock = [Fruit: Int]()
transferStock을  제거하고 juiceMaker.fruitStore.stock만 사용해서 editVC로 전달해는 것으로 수정했습니다!

2022-05-13 09:18 UTC, yeeton37 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
>              label.text = "\(fruitLabel)"
변화되는 로직이 있을 땐 메서드로 만들 수 있는지 먼저 고민을 해봐야겠군요...! 감사합니다 🧐🧐
그리고 fruitLabel은 amountOfFruit 으로 변경해주었습니다. Int 형인데 라벨은 좀 어색하긴 하네요..ㅎㅎ

2022-05-13 09:26 UTC, yeeton37 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(getFruitStock), name: .notifyStock, object: nil)
아.. 여기서 이름을 변경하는 거에 대해 고민을 많이 했는데요 ㅠㅠ  

저희가 짠 코드는 updateFruitStockLabel 안에서 노티피케이션센터로부터 데이터를 받아오고,  그 데이터를 다른 메서드로 보내서 label의 text를 변경해주도록 코드를 짰습니다.
그렇게 되면  label의 text를 변경해주는 메서드를 updateFruitStockLabel이라고 칭하는 게 맞지 않나?라고 생각을 해서 원래 updateFruitStockLabel라고 했던 것을 getFruitStock으로 변경해준 것이었습니다!

그치만 노티피케이션센터로부터 데이터를 받아오는 게 당연히 알 수 있는 일이라면 굳이 적지 않고 목적을 정확히 표현해주는 것이 좋다는 피드백을 보고  updateFruitStockLabel 안에서 또 호출되는 메서드명을  updateLabel 이라고 변경해주었는데.... 뭔가 더 구체적인 표현이 있을까요 ?
메서드 안에서 비슷한 메서드를 호출하는 경우..이런 경우가 항상 네이밍이 고민이 되는 것 같습니다 ㅠㅠ

2022-05-13 09:32 UTC, yeeton37 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
>          }
주문 버튼을 구성한다를 의미하는 군요! 이런 코드들도 다 로직이니 메서드로 변경하면 추후에 변경해주기 수월하겠네요 🧐 감사합니다!!
또 말씀해주신 참고링크는 저번에 주셨는데 꼼꼼하게 읽지 않았나봅니다...ㅠㅠ 앞으로 자주 꺼내보겠습니당

그리고 액션함수 네이밍 위와 같이수정하면서 노티피케이션센터 옵저버하는 부분도 메서드로 만들어서 fruitStockAddObserverDidChanged 이런식으로 네이밍을 해주었는데 괜찮을까요..?

2022-05-13 09:34 UTC, yeeton37 commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +    var fruitsStock = [Fruit: Int]()
이전에 말씀해주셨던 DTO 형태(공개 변수만 있고 함수가 없는 구조체)로 구조체를 생성해주었습니다..!

2022-05-13 09:34 UTC, yeeton37 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
store.stock을 그대로 쓰기로 해서 이 notify메서드는 아예 지워주었습니다

2022-05-13 09:50 UTC, Hugh-github commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +        <!--EditStockViewController-->
storyboard reference를 사용하지 않고 화면이 전환되도록 수정했습니다.
EditStock 스토리보드에 있는 Navigation Controller의 ID를 설정해 HomeViewController에서 인스턴스를 생성하니
storyboard reference를 main 스토리보드에서 제거해도 정상적으로 화면이 바뀌는 걸 확인했습니다.

2022-05-13 14:02 UTC, Hugh-github commented on JuiceMaker/EditStock~.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
제거해 주었습니다.
혹시 왜 제거해야 하는지 알 수 있을까요?

2022-05-13 14:03 UTC, Hugh-github commented on JuiceMaker/JuiceMaker/Controller/EditStockStepper.swift
> +class EditStockStepper: UIStepper {
네 폴더를 나누어 파일을 관리하게 수정했습니다!

2022-05-13 14:03 UTC, Hugh-github commented on JuiceMaker/JuiceMaker/Controller/TransferDelegate.swift
> +protocol TransferDelegate: AnyObject {
프로토콜 네임을 변경했습니다!

2022-05-13 14:03 UTC, Hugh-github commented on JuiceMaker/JuiceMaker/Controller/TransferDelegate.swift
> +    func transfer(changedStock: [Fruit: Int])
명심하겠습니다.

2022-05-14 05:30 UTC, ehgud0670 commented on JuiceMaker/EditStock~.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
아 사용안하시는것 같아서 코멘트 드렸습니다~

2022-05-14 05:31 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/EditStockStepper.swift
> +class EditStockStepper: UIStepper {
좋습니다 훌륭합니다! 👍

2022-05-14 05:33 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    private var transferStock = [Fruit: Int]()
좋습니다. 항상 어떤 프로퍼티를 만들지 말지를 항상 고민하시면 좋아요 :)
굳이 필요없는 프로퍼티나 상태값이 생기는 것을 방지합니다 💪

2022-05-14 05:41 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(getFruitStock), name: .notifyStock, object: nil)
아예 겹쳐도 됩니다. 실제로 겹치게끔 메소드 많이 써요. 결국에 파라미터의 타입이 다르기 때문에 다른 동료들이 봐도 어색하지 않아요.
```swift
updateFruitStockLabel(notification:)
updateFruitStockLabel(with:)
```
여기서 위에껀 아, 노티를 받아서 레이블을 업데이트 하나보다. 아래껀 아, 그대로 모델 값을 받아와서 레이블을 업데이트 하나보다 라고 생각을 합니다. 
이처럼 메소드 이름을 동일하게 하게 하는 경우가 있는데, 이를 자바나 다른 언어에선 [오버로딩](https://whatisthenext.tistory.com/38)
이라고 합니다(스위프트에서는 따로 개념으로 지칭하진 않는 것 같아요).
링크 글 보시고 한번 더 고민해보세요 ㅎㅎ

2022-05-14 05:46 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
>          }
해당 함수는 액션함수는 아닌것 같고 Observer 를 추가하는 작업이기 때문에 setting 하는 함수라 보통 여러개 옵저버를 추가한다면
`addObservers` 라고 합니다. 한개면 저는 해당 예제로는 보통 `addObserverForFruitStock` 이런식으로 합니다.
저는 보통 이런식으로 처리하는데 네이밍에 정답은 없으니 여러분들이 편하신대로 하시면 좋을 것 같아요!
옵저버를 하나만 추가하므로 그냥 viewDidLoad에 
`NotificationCenter.default.addObserver(self, selector: #selector(updateFruitStockLabel), name: .notifyStock, object: nil)` 를 그대로 옮기는 것도 괜찮습니다.

2022-05-14 05:53 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/TransferDelegate.swift
> +    func transfer(changedStock: [Fruit: Int])
네네 가장 대표적인 예로 UITextFieldDelegate를 들수 있겠습니다. VC가 복수 개의 UITextField를 가진 상태에서 
UITextFieldDelegate를 채택하고 있다면 UITextFieldDelegate의 함수들이 호출될 때, 파라미터로 전달된 UITextField로 해야될 기능들을 수향할 수 있는거죠. 만약 UITextFieldDelegate의 함수들이 UITextField 를 파라미터로 가지고 있지 않다면 복수개의 UITextField 중에 어떤 UITextField 가 액션이 이뤄졌는지 모르기 때문에 해야 될 일을 수행할 수 없게 됩니다. 

참고링크: https://velog.io/@delmasong/UITextFieldDelegate

ps. 제가 설명을 좀 어렵게 한 것 같은데 와닿지 않으시면 불러주세요 😂 직접 예시로 보여주며 설명드리도록 하겠습니다.

2022-05-14 05:56 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
좋습니다. 단순히 notify라는 네이밍때문에 언급드렸습니다. 참고 부탁드려요 🙏

2022-05-14 05:59 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +        <!--EditStockViewController-->
잘하셨습니다 🎉🎉🎉
그래서 제가 Navigation Controller의 Storyboard ID(`EditStock`)을 지워봤는데 화면이 잘 나옵니다.

2022-05-14 06:15 UTC, ehgud0670 approved these changes
정말 고생들 많으셨습니다. 👏👏👏
* viewDidLoad에 잘 추상화된 함수(`= 함수들이 한가지 역할만 하도록 잘게 나누셔서`)들이 있어서 읽기가 편했고,
* 고차함수(ex. forEach)도 잘 사용하셨고
* VC 간에 데이터 전달도 잘 하셨고
* 오토레이아웃도 잘 적용하셨네요! 👏👏👏

두분 다 3주동안 고생이 많았고 그럼 남긴 코멘트만 봐주시면 되겠습니다.
다음 프로젝트도 화이팅 하세요! 🔥

2022-05-14 06:15 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +        updateLabel(to: juiceMaker.store.stock)
`EditStockViewController의 updateLabel(from:)` 메소드처럼 이 메소드도 인자레이블이 to 보다는 from이나 with 이 맞는것 같네용 🧐

2022-05-14 06:15 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +            style: .default) { _ in
오 되게 깔끔해보이네요! 👍

2022-05-14 06:15 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    private var orderButton: [UIButton] {
타입이 배열타입이므로 복수가 더 어울립니다 :)
orderButtons

2022-05-14 06:15 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    @IBOutlet private var fruitStockLabel: [FruitStockLabel]!
이것도 타입이 Array 이므로 이름은 단수 말고 복수가 어울립니다 ^^
`fruitStockLabels`

2022-05-14 06:15 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +            self.presentEditStockViewController()
여기 인덴트 실수로 들어가 있네요!

2022-05-14 06:16 UTC, merged

2022-05-14 06:36 UTC, ehgud0670 commented
추가 말씀드립니다 
[instantiateInitialViewController(creator:)
](https://useyourloaf.com/blog/better-storyboards-with-xcode-11/) 이걸 쓰면 VC도 custom init을 사용할 수 있습니다. 
즉 editVC를 생성할때 깔끔하게 모델 값을 주입할 수 있다는거죠. 
꼭 참고해보세요!!

2022-05-14 10:39 UTC, yeeton37 commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(getFruitStock), name: .notifyStock, object: nil)
오... 똑같이도 쓰는군요..처음알았네요.... 오버로딩에 대해 알고는 있었는데 이런 경우에 사용하는 것인지 몰랐어요 감사합니다!

2022-05-15 00:17 UTC, ehgud0670 commented on JuiceMaker/JuiceMaker/Model/FruitInventory.swift
> +    var currentStock: [Fruit: Int] {
추가로 첨언드리면 currentStock 이랑 stock 은 다른 점이 없어 보입니다. 🧐 그래서 사실 stock을 그대로 외부로 노출되어 보이긴 해요. 제가 말씀드리고 말씀주신 것처럼 FruitInventory가 자료구조이지만 stock,currentStock을 private(set)으로 외부에 read only로 되게끔 하고 나머지들은 메소드로 표현하는 건 어떨까요~? stock 자체가 EditStockVC가 dismiss 될때 필요한 거라 외부에 노출은 되는 것이 어쩔수 없이 좋겠지만, 그래도 변화는 줄이기 위해 메소드로 표현하면 좋을 것 같아서요!