쥬스 메이커 [STEP 1] rhovin, mangdi
yagom-academy/ios-juice-maker pull request #246
Opened 2022-08-30 04:57 UTC by yuvinrho

@lina0322 

안녕하세요 엘림! 로빈, 망디 입니다. 이번 스텝1 잘부탁드리고, 지적할 부분 아낌없이 팍팍 부담없이 마구 부탁드립니다~~😆

# 진행 단계 : Step 1

## 🤔 코드를 작성할 때 고민되었던 점
- 주스 종류에 따른 과일 종류와, 개수를 어떤식으로 가져와야될까 고민했습니다.
이번스텝 참고할 문서에 Nested Type 이라는 것이 있어서 이 부분을 공부하개되었고, 이를 이용해서 과일 종류에 따른 재료를 가져올 수 있도록 하였습니다.
- `FruitStore.swift`에 각 과일과 수량을 담는 `fruitList` 타입에 대해서 고민했습니다. 과일만 담는 리스트, 과일 개수를 담는 리스트 각각을 만들지 고민했었는데, 최종적으로 과일종류와 개수를 쌍으로 담을 수 있는 딕셔너리로 타입을 정했습니다.
- step1요구사항에는 나오지 않았지만 추가적으로 
만든 주스의 이름과 수량도 출력하게 만들고싶었습니다.
주스를 만들었는데 결과물이 나오지않고 그저 재료만 소진하게하니 먼가 허전했습니다.
주스들을 담는 타입을 똑같이 딕셔너리타입으로 생성해주고
주스를 생성할때마다 딕셔너리 키값에 +1을 해주어 개수를 출력하게 만들었습니다!

## 🆘 조언을 얻고 싶은 부분 등 상세하게 작성
- Enums파일에 enum들을 모아두었는데 각 enum마다 사용하는 용도가 다릅니다.
이들을 각각 하나의 파일로 분리하는것에 대해 고민했습니다. 
이에 대한 엘림의 의견 궁금합니다!

2022-08-30 11:16 UTC, lina0322 requested changes
두 분 고생하셨습니다~🙏

전체적으로 깔끔하고 네이밍도 잘 되어있어서 읽기 쉬웠습니다.

다만, 요구 사항에 없던 부분을 구현하셨었는데요!
콘솔에 찍히는 정도는 당연히 유저에게 보여지지 않는 부분이라 상관이 없지만
실제로 업무를 하게되면 임의로 무언가를 보여주거나, 안보여주거나 하는 일은 당연히 있어선 안되겠죠?

그 외에는 달아드린 코멘트를 바탕으로 얘기 나눠볼게요~🙂

2022-08-30 11:16 UTC, lina0322 commented on CODEOWNERS
> +* @lina0322
음, 요거 아니고! PR 화면 우측 위에 리뷰어 설정 있어요ㅎㅎ 제가 해놨답니당!!👏

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		099DE0FC28BCDA7E00E9E7EE /* Enums.swift in Sources */ = {isa = PBXBuildFile; fileRef = 099DE0FB28BCDA7E00E9E7EE /* Enums.swift */; };
Enums라고 파일명을 했다고 가정했을때, 
프로젝트가 커지고 enum이 100개 200개가 된다면 모두 여기에 들어가겠네요ㅎㅎ?
어디에 어떤게 있는지 파일명만으로는 찾기힘들겠군요?😅

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -
주석을 모두 지운 이유가 있나요?

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        juiceMaker.handleMakeFruitJuiceError(fruitJuice: .strawberryBananaJuice)
이번 스텝은 타입을 정의하는 것이었는데요!
이쪽에 코드도 타입 정의에 필요한가요?🧐

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Enums.swift
> +        let second: (Fruits, Int)?
옵셔널 활용을 적절하게 했네요. 좋습니다!

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/Enums.swift
> +}
위 enum들과 관련이 있나요?🧐

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -import Foundation
`import Foundation`을 지우신 이유가 궁금합니다~

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    ]
`private var fruitList: [Fruits: Int] = []`
이렇게 비어있는 상태에서 넣어줄 수 있는 방법은 없을까요?
과일 목록은 enum Fruits에서 가져올 수 있을 것 같네요~

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init(fruitAmount: Int) {
기본값을 여기에도 지정할 수 있는데요, 혹시 방법을 알고있나요~

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
class로 만든 이유가 무엇일까요?😃
아마 아직 배우지 않으셨을 것 같긴해서ㅎㅎ 아직 이쪽까지 수업 안나갔다면 고민만 ㅎ ㅐ보세요~

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
쥬스 메이커는 struct네요! 마찬가지로 고민해보세요!

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    ]
위쪽에서 말씀 드렸던것과 같은 방향으로 한번 확인해주세요~!

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var fruitStore = FruitStore(fruitAmount: 50)
LGTM😄

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func bringIngridients(of fruitJuice: FruitJuice) throws {
mutating이라는 키워드는 어떤것을 의미하나요?
bring이라는건 어떤 의미로 사용하셨나욥?🙂

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            fallthrough
fallthrough를 사용한 것 자체가 나쁘다고 보긴 어려워요.
자주 사용되느냐 하면 그렇지는 않지만, 존재하는 이유가 있고 좋은 곳에 활용할 수 있다면 좋죠.

그런데 만약에 첫번째 재료가 없으면 어떻게되나요? 두번째 재료만 소진되는건가요?🥲

추가로, 차후에 3번째 재료가 있는 상품이 생긴다면 어떻게 될지에 대해 고민해보시면 답이 나올거같습니다.

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                print("Default Error Message")
유저가 사용하는 앱에 print문이 필요한가요? print는 콘솔에만 찍히는데요!🙂
참고로 print는 생각보다 무거운 함수라고 합니다.

여러분이 콘솔에 찍히는 메세지를 확인하려면 어떤 함수를 사용하는게 더 좋을까요?

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func handleMakeFruitJuiceError(fruitJuice: FruitJuice) {
함수명이 에러를 핸들링하는 것인데, bringIngridients이 내부에 있네요..??🧐

2022-08-30 11:16 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            print("\(fruitJuiceNumber)개")
위와 아래 조건이 다른거에요???

2022-08-31 05:14 UTC, yuvinrho commented on CODEOWNERS
> +* @lina0322
해당파일 삭제하였습니다ㅎㅎ

2022-08-31 05:20 UTC, yuvinrho commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		099DE0FC28BCDA7E00E9E7EE /* Enums.swift in Sources */ = {isa = PBXBuildFile; fileRef = 099DE0FB28BCDA7E00E9E7EE /* Enums.swift */; };
Enums에 있던 열거형들을 Fruits, FruitJuice, ErrorHandling 파일로 각각 분리하였습니다. 이렇게 파일분리 하였을때 커밋 메시지 타입을 refactor로 할지 style로 할지 고민한 결과 refactor로 정했습니다. 적절한 커밋 메시지 타입인지 궁금합니다!

2022-08-31 05:20 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -
코드와 관련하여 필요하지 않은 주석이라 판단하여 삭제하였습니다.

2022-08-31 05:25 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        juiceMaker.handleMakeFruitJuiceError(fruitJuice: .strawberryBananaJuice)
스텝1을 구현하고 결과물이 어떻게 나올까 궁금하여 작성한 테스트용 코드였습니다. 코드 수정하고 재리뷰요청 드리기전에 삭제하겠습니다~

2022-08-31 05:26 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/Enums.swift
> +}
각 enums들 파일분리 하였습니다~

2022-08-31 05:27 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -import Foundation
step1에서 구현한 코드는 swift standard library 기능으로 충분하기 때문에 Foundation이 불필요하다고 생각하여 삭제하였습니다~

2022-08-31 05:40 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    ]
Fruits 열거형에 CaseIterable을 채택하였고
아래와 같이 이니셜라이저를 이용해 수정하였습니다~
```swift
private var fruitList: [Fruits: Int] = [:]
    
    init(fruitAmount: Int = 10) {
        for fruit in Fruits.allCases {
            fruitList[fruit] = fruitAmount
        }
    }
```

2022-08-31 05:41 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init(fruitAmount: Int) {
생각해보니 파라미터에 기본값을 설정하면 되는 방법이 있었습니다~ 
 아래와 같이 수정하였습니다!
`init(fruitAmount: Int = 10)`

2022-08-31 05:45 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    ]
위에서 수정한 방법과 같이 코드를 수정하였습니다~
```
private var fruitJuiceList: [FruitJuice: Int] = [:]
    
    init(numberOfFruitJuice: Int = 0) {
        for fruitJuice in FruitJuice.allCases {
            fruitJuiceList[fruitJuice] = numberOfFruitJuice
        }
    }
```

2022-08-31 05:46 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
class는 값의 참조 struct는 값의 복사가 이루어집니다. 게다가 class는 상속이란 기능을 사용할수있는데
이번스텝에서는 class를 사용할 필요가 없어보여 struct타입으로 변환했습니다!

2022-08-31 05:47 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
요것도 class로 바꿔줄 이유가 없어서 struct로 유지하겠습니다!

2022-08-31 06:01 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func bringIngridients(of fruitJuice: FruitJuice) throws {
*struct타입은 메서드 내에서 기본적으로 가지고있는 프로퍼티의 값을 변경할수없습니다.
하지만 mutating 키워드를 써준다면 값의 변경이 가능해집니다!

*FruitJuice에 사용하는 재료를 가져오고싶어서 bring이라는 단어를 붙여주었습니다. 하지만 함수의 기능을 상기해보며 다시 생각해보니 네이밍의 수정이 필요하다 생각되어 makeFruitJuice로 수정했습니다!.

2022-08-31 06:07 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func handleMakeFruitJuiceError(fruitJuice: FruitJuice) {
이것도 다시 생각해보니 네이밍의 수정이 필요하다 생각되어 takeAnOrder 로 수정했습니다!.

2022-08-31 06:41 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                print("Default Error Message")
저희가 구글링 하여 알아본바는 이렇습니다!
1. dump :  dump는 객체의 내용을 출력하는것에 쓰이는것 같습니다. 직접 써보니 객체의 내용을 자세하게 출력이 되는걸 확인했습니다!
2. debugPrint : "디버깅에 가장 적합한 지정된 항목의 텍스트 표현을 표준 출력에 씁니다."  개발자문서에서 작성된 문단을 그대로 긁어왔습니다 엘림이 말한 콘솔에 찍히는 메시지를 확인하는데 가장 적절한 함수가 이거이지않나 생각합니다!

2022-08-31 06:42 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                print("Default Error Message")
> 유저가 사용하는 앱에 print문이 필요한가요? 

이 부분에 초점을 맞춰서 생각해보니 저는 디버그 모드에서만 콘솔로 출력이 되게 하시라는 말씀이신가? 라고 생각이 들었습니다. 그래서 디버그 모드에서만 작동하는 assert 를 찾아보았는데 엘림의 의견이 궁금합니다~

2022-08-31 07:47 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            print("\(fruitJuiceNumber)개")
주문한 쥬스가 나옴과 동시에 주문한사람에게 나왔다는것을 알리고 만든 주스의 수량을 체크하는용도로 만들었습니다.
if let을 두번 쓴 이유가 위에 if let은 음료를 제조하기 전 원래 있었던 개수를 출력하는 용도고
아래 if let은 개수가 추가된 음료를 나타내기위해 이렇게 코드를 짰었습니다.
지금 보니까 먼가 어색한 느낌이 들어서 저 함수를 

사용자에게 음료가 나왔음을 알리는 notifyJuiceComesOut 함수와
지금까지 제조한 음료의 개수를 알려주는 checkQuantity 함수로 2개로 나누는 생각을 했습니다.

하지만 이는 캠프사이트의 요구사항에 나와있지 않은 사항으로 삭제하겠습니다!

2022-08-31 08:34 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            fallthrough
*재료2개가 필요한 주스들은 첫번째 재료가 없으면 두번째 재료만 사라지는 오류를 발견했습니다! 이점을 고칠겸 fallthrough없이 구현을 시도했습니다!

*switch문에서 재료가 1개,2개 들어가는 주스를 case별로 나누어 subtractAmountOfOneIngridients() 함수와 
fruitStore.subtractAmountOfTwoIngridients() 함수로 보내어 처리하게 만들었습니다!

2022-08-31 08:52 UTC, lina0322 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		099DE0FC28BCDA7E00E9E7EE /* Enums.swift in Sources */ = {isa = PBXBuildFile; fileRef = 099DE0FB28BCDA7E00E9E7EE /* Enums.swift */; };
커밋 메세지는 여러분들의 약속이니, 두 분이서 관련해서 정의를 잘 내리고 활용하시면 될거같습니다🙏
참고로 저희 회사는 이슈넘버로 커밋 메세지 타입을 정하고 있어서, refactor나 style 등을 사용하진 않습니다ㅎㅎ
두 개가 굳이 어색하시면, 새로운 커밋 타입을 만들어보시는 것도 가능할거같아요!

2022-08-31 08:59 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                print("Default Error Message")
`디버그 모드에서만 콘솔로 출력이 되게 하라`는 것 맞고요!

- dump가 디버깅 모드에서만 출력되나욥?🙃
- 저에게 assert는 테스트할때 쓰는 느낌이랗ㅎㅎㅎ 저는 잘 안쓰는거같아요... 그냥 출력만을 위한 용도인가?에 대한 의문도 들고요!
 
debugPrint 좋습니다! log도 한번 알아보면 좋을거같아욥~

2022-08-31 09:00 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            print("\(fruitJuiceNumber)개")
아하! 제가 문구를 잘못 파악했네요ㅎㅎ
0개 -> 1개 이런식으로 된거군요.
만약에 그대로 둔다고해도, 굳이 따로 조건문 쓸 필요 없이 내부에서 더 해주는 방법도 있을거같네요🙂

2022-08-31 12:51 UTC, lina0322 reviewed
조금만 더 디벨롭 해봅시다!

2022-08-31 12:51 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
changeAmountOfFruits를 위쪽 init에서 사용할수도 있겠네요?!🙃

네이밍은 아래가 나은거같아요~ 
```swift
changeAmount(of fruit: Fruits, amount: Int)
//or
changeAmount(of fruit: Fruits, to amount: Int)
```

2022-08-31 12:51 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
줄 간격이 이상해요~! 잘 살펴보세요~

```swift
use(_ fruit: Fruits, of amount: Int)
```

이런 네이밍과 비교했을때는 어떤가요?

2022-08-31 12:51 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        _ amount2: Int
이건 오히려 매게변수명을 보여주는게 좋지 않을까요?
사용할 과일 2개를 먼저 적고 뒤에 숫자 두개인가? 혹은
숫자 먼저 적고, 과일인가에 대한 혼돈이 있을 수 있을 것 같아요.

변수명도 1, 2보다는 firstFruit, secondAmount 는 어떨까요?

2022-08-31 12:51 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
early exit으로 사용되는 guard를 활용해보면 어떻게될까요?🙂

2022-08-31 12:51 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/ErrorHandling.swift
> +enum ErrorHandling: Error {
ErrorHandling?
에러를 핸들링하는 enum인가요? 네이밍이 다소 어색하네요!

2022-08-31 12:51 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
debugPrint 사용한 부분 좋습니다! 

다만, 저 문구는 error 자체가 들고있는게 맞지 않을까요? 
여기저기서 사용되면 매번 복붙하고, 100군데서 사용중이면 모두 찾아서 바꿀순 없잖아욤?!🙂

2022-08-31 13:39 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
오 생각치도 못했습니다. 아래와 같이 코드 수정하였습니다~
```
init(fruitAmount: Int = 10) {
        for fruit in Fruits.allCases {
            changeAmount(of: fruit, amount: fruitAmount)
        }
    }
    
    mutating func changeAmount(of fruit: Fruits, amount: Int) {
        fruitList[fruit] = amount
    }
```

2022-08-31 13:50 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
아래와 같이 수정하였습니다~
```
case JuiceMakerError.underFlowOfAmount:
    debugPrint(JuiceMakerError.underFlowOfAmount.rawValue)
case JuiceMakerError.notExistFruits:
    debugPrint(JuiceMakerError.underFlowOfAmount.rawValue)
default:
    debugPrint(JuiceMakerError.underFlowOfAmount.rawValue)
```

2022-08-31 13:50 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/ErrorHandling.swift
> +enum ErrorHandling: Error {
JuiceMakerError 로 수정하였습니다~

2022-08-31 14:13 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
줄간격 컨벤션 확인을 못했었네요 ㅠㅠ 다음부턴 다 작성하고 전체드로그 해서 컨트롤 i 눌러야겠습니다..!

저렇게 복잡하게 네이밍 하지 않고 그저 심플하게 use를 사용하면 편하겠군요..
엘림의 의견대로 subtractAmountOfOneIngridients() 와 subtractAmountOfTwoIngridients() 를 -> use() 으로 바꾸었습니다! use() 함수를 2개 작성하면 충돌이 일어날것같지만 매개변수의 개수를 다르게 하여 (오버로딩) 작성하면 실행이 되는것을 확인했습니다!

2022-08-31 14:23 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        _ amount2: Int
과일이름을 먼저 2번쓰는건지 번갈아서쓰는건지 헷갈릴수 있겠네요..! 엘림 의견대로 수정 진행했습니다!

2022-08-31 14:45 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
if let을 사용하면 한번 true 블록을 거쳐 false 블록으로 넘어가는데 비해 
guard 를 사용하면 바로 false 블록으로 넘어가기때문에 Early Exit라고 불리는군요!
Early Exit가 멀까 했는데 로빈의 도움으로 공식문서를 통해 알게되었습니다!

엘림의 의견 반영하여 guard문으로 수정 진행했습니다!

2022-09-01 12:33 UTC, lina0322 approved these changes
고생하셨습니다! 다음 스텝에서 더욱 더 힘내보죠~

2022-09-01 12:33 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +enum JuiceMakerError: Error {
요기 줄바꿈 필요할거같아요!

2022-09-01 12:33 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
LGTM👏

2022-09-01 12:33 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +              let numberOfFruit2 = fruitList[secondFruit] else {
number보다는 count 혹은 amount가 좀 더 자연스럽겠네요!

2022-09-01 12:33 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +}
좋아요~ 
https://www.advancedswift.com/custom-errors-in-swift
이 글도 한 번 참고해볼게요!

2022-09-01 12:34 UTC, merged