쥬스 메이커 [STEP 1] 제이푸시, stone🪨
yagom-academy/ios-juice-maker pull request #247
Opened 2022-08-30 06:15 UTC by jjpush

@Monsteel
안녕하세요 토니!!!!!!!
첫 PR 보냅니다..! 잘부탁드립니다 🙇‍♂️

## 기능 구현
---
### JuiceMaker
- 프로퍼티
    - **let fruitStore**
- 메서드
    - **makeJuice(_ juice: Juice)**
        1. 쥬스타입의 값을 받아서 레시피정보를 받은 후 레시피에 해당하는 과일들이 부족하지 않은지 체크합니다. 
        2. 레시피에 해당하는 과일을 사용해서 음료를 완성합니다.
    - **validFruitAmount(_ recipe : [Fruit : Int]) throws**
        1. 레시피를 반복문으로 (과일명, 필요한양)을 받아와서 `fruitStore`내의 메서드로 과일재고를 받아오고 값이 충분한지 체크합니다. 
        2. 재고가 충분하지 않다면 `fruitAmountError`를 던집니다.

### FruitStore
- 프로퍼티
    - **(타입) static let shared**
        - `싱글톤` 패턴을 사용하기 위하여 타입 프로퍼티 shared를 선언하였습니다.
    - **var fruits**
        - 과일과, 갯수를 초기화 하기위한 변수입니다.
- 메서드
    - **private init()**
        - `싱글톤` 패턴을 사용하기 위해 생성자에 `private` 접근 제어자를 명시해주었습니다.
        - 해당 생성자를 통하여 `fruits` 변수에 초기 값을 셋팅해줍니다.
    - **useFruits(recipe: [Fruit : Int]) throws**
        - 쥬스 생성시, 사용 할 과일과 과일의 갯수를 받아 감소시키는 역할을 하는 함수입니다.
        - [Fruit : Int] 형식의 `Dictionary`값을 받아 `fruits`변수에서 과일의 갯수 만큼을 감소시킵니다.
        - 만약에, `Fruit` 값의 과일이 존재하지 않을 경우 `fruitExistError`에러를 던집니다.
    - **fetchFruitAmount(fruit: Fruit) throws**
        - 과일의 갯수를 체크하는 함수입니다. `Fruit`타입을 받아 `fruits`변수에서 해당 타입의 과일의 갯수를 리턴하는 함수입니다.
        - 만약에, `Fruit` 값의 과일이 존재하지 않을 경우 `fruitExistError`에러를 던집니다. 

### Fruit
- Fruit 열거형에 과일의 종류를 `case`로 정의하였습니다.
- `FruitStore`에서 `.allCases`계산속성을 사용하기 위해 `CaseIterable`프로토콜을 채택하였습니다.

### Juice 
- Juice 열거형에 String 원시 값을 채택하여, 각 `case`에 String 값을 할당해주었습니다.
- recipe
    - 계산 속성의 `getter` 를 통하여 해당 Juice의 레시피의 값인 `[Fruit : Int]` 타입으로 반환합니다.
    ```Swift
    var recipe: [Fruit : Int] {
        switch self {
        case .strawberry:
            return [.strawberry : 16]
        case .banana:
            return [.banana : 2]
        case .kiwi:
            return [.kiwi : 3]
        case .pineapple:
            return [.pineapple : 2]
        case .strawberryBanana:
            return [.strawberry : 10, .banana : 1]
        case .mango:
            return [.mango : 3]
        case .mangoKiwi:
            return [.mango : 2, .kiwi : 1]
        }
    }
    ```

### JuiceMakerError
- **fruitAmountError**
    - 쥬스를 만드는데 필요한 과일 재고가 부족한 경우
- **fruitExistError**
    - 해당 과일이 과일저장소에 존재하지 않을 경우
- **LocalizedError**
    - localizedDescription 를 사용하기 위해 프로토콜을 채택하였습니다.

## 고민한 부분
- **`FruitStore`인스턴스의 싱글톤패턴**
    - 추후에 재고를 증가,감소 시키는 재고관리, 쥬스생성시 관리를 하는 `FruitsStore`는 프로그램 상 하나의 클래스 인스턴스만 존재하여야 한다고 생각하여, `싱글톤`패턴을 적용해 보았습니다.
- **`[STEP1]` 요구 사항 중 `각 과일의 수량 n개를 변경하는 기능이 있습니다.` 라는 요구 사항이 있습니다.**
    - 여기서 과일을 감소시키는 로직을 요구하는건지, 과일 재고를 보충하는 로직을 요구하는건지 고민을 하였는데, 요구사항 상으로는 감소시키는 로직만 필요하다고 판단되어서, 감소시키는 로직만 구현했습니다..!

- 레시피를 만들때 튜플 배열 or 딕셔너리
    - 레시피를 만들 때 둘 중 어떤 방식을 채택할지 고민하였습니다.
        - [.strawberry : 10, .banana : 1]
        - [(.strawberry, 10), (.banana, 1)]
    - 별 다른 차이점을 느끼지 못해서 가독성이 조금 더 좋다고 생각한 딕셔너리를 사용했습니다.

 - switch문을 사용해서 에러 메세지를 catch 할 때 case별로 체크를 해 주면 마지막에 예상외의 에러를 체크해주는 부분을 한번에 묶어주기 위해서 `LocalizedError`를 사용했습니다.
    ```swift
    // localizedError 미사용
    catch errorCase1 {}
    catch errorcase2 {}
    catch {}
    // localizedError 사용
    catch { print(error.localizedDescription) }
    ```
## 조언을 얻고 싶은 부분
    
**이미 유효성을 확인 한 후에 `Dictionary`의 값을 사용할 때**
- `fetchFruitAmount`함수를 사용하여, 과일의 유효성 체크를 하는데, 유효성 체크 후 `useFruits`함수를 사용하여 과일의 갯수를 감소시킵니다.
- `useFruits`함수 내부에서 `Dictionary`값인 `fruits`를 사용하는데,이미 유효성 검사가 끝난 값이라 굳이 `throw`로 에러를 던지지 않고 `return`으로 처리해도 되는지 조언을 얻고싶습니다..!!
```swift
func useFruits(recipe: [Fruit : Int]) throws {
    for (fruit, amount) in recipe {
        guard let fruitAmount = fruits[fruit] else {
            throw JuiceMakerError.fruitExistError
        }

        self.fruits[fruit] = fruitAmount - amount
    }
}
```

**쥬스의 레시피를 가져올 때 고민했던 점**
- enum에서 원시값으로 딕셔너리를 주는 방법을 찾지 못했기 때문에 지금의 enum의 연산프로퍼티로 구현하기 전 `Recipe` struct 타입을 만들어서 구현해주었습니다. 
- 결국은 enum의 값들과 중복되는 부분이 많아서 삭제되었는데 struct를 통해서 현업에서는 이런 struct 데이터 모음을 잘 사용하는지, enum 타입으로 잘 사용하는지, enum을 잘 사용한다면 딕셔너리 원시값의 경우는 어떻게 처리하는지 궁금합니다
    
```swift 
struct Recipe {
static let strawberry: [Fruit : Int] = [.strawberry : 16]
static let banana: [Fruit : Int] = [.banana : 2]
static let kiwi: [Fruit : Int] = [.kiwi : 3]
static let pineapple: [Fruit : Int] = [.pineapple : 2]
static let strawberryBanana: [Fruit : Int] = [.strawberry : 10, .banana : 1]
static let mango: [Fruit : Int] = [.mango : 3]
static let mangoKiwi: [Fruit : Int] = [.mango : 2, .kiwi : 1]

static func fetchJuiceRecipe(_ juice: Juice) -> [Fruit : Int] {
    switch juice {
    case .strawberry:
        return Recipe.strawberry
    case .banana:
        return Recipe.banana
    case .kiwi:
        return Recipe.kiwi
    case .pineapple:
        return Recipe.pineapple
    case .strawberryBanana:
        return Recipe.strawberryBanana
    case .mango:
        return Recipe.mango
    case .mangoKiwi:
        return Recipe.mangoKiwi
    }
}
```

2022-08-31 09:23 UTC, Monsteel requested changes
안녕하세요! 제이푸시, stone! :)
첫번째 스텝! 수고 많으셨습니다! 👍

PR내용에, 구조에 대한 설명과, 고민하신 부분을 잘 남겨주셔서 코드를 파악하고 여러분들의 생각의 흐름을 파악하는데에 큰 도움이 되었습니다 🙇🏻‍♂️ 감사합니다!

코드에 대한 코멘트는 아래 리뷰를 확인해주시구요! 이곳에는 남겨주신 "조언을 얻고 싶은 부분"에 대한 저의 생각을 남겨보도록 할게요!


### 1. 이미 유효성을 확인 한 후에 Dictionary의 값을 사용할 때
이 질문에 대해 고민해볼만한 포인트는 두가지 정도 있을것 같은데요, 

1. `useFruits(recipe: [Fruit : Int]) throws` 함수에 꼭 유효성이 검증된 값이 들어와야 하나요?
다르게 질문해보면,
유효성 검증을 하지 않고, `useFruits(recipe: [Fruit : Int]) throws` 메서드를 호출했을 때, 발생할 수 있는 오류가 있나요?

2. `useFruits(recipe: [Fruit : Int]) throws` 함수에 유효성이 검증된 값이 들어온다는 보장이 있나요?
다르게 질문해보면, 
`useFruits(recipe: [Fruit : Int]) throws` 함수가 호출되기 이전에 유효성 검증이 반드시 이루어진다는 보장이 있나요?

두가지 고민 포인트에 대해 우선 고민해보시면, 어떤 방향성을 가져가야할지 판단하시는데에 도움이 되실 것 같아요 🙌

### 2. 쥬스의 레시피를 가져올 때 고민했던 점
좋은 질문입니다!

우선 코멘트를 남기기 전에,
'현업에서는 이런 struct 데이터 모음을 잘 사용하는지' 라는 질문을 주셨는데,

**"현업에서 사용하는 방식 == 신뢰할 수 있는, 믿음직한 방식"** 이라고 생각하신다면,
그것은 사실이 아닌 미신이라고 생각합니다.

현업이라는 기준이 굉장히 광범위하고, 코드가 탄생한 장소가 다를 뿐, 현업에서 사용한다고 무조건
신뢰할 수 있는 믿음직한 방식은 아닙니다.

존재할 수 없는 방향을 따라가는것 보다, 
선택할 수 있는 여러 방식을 비교(사고)해보고, 스스로 선택하실 수 있는 개발자가 되셨으면 좋겠습니다 👍

--

1. 우선, `enum에서 원시값으로 딕셔너리를 주는 방법` 을 선호하시는 이유가 있나요?

아래의 코드리뷰에도 enum의 rawValue 사용에 대한 리뷰가 있어 간단하게 이야기를 해보자면,

저는 enum의 rawValue를 사용하는 방향보다는, enum value로 정의하는 방향을 더 선호합니다.
rawValue에 들어갈 내용을 enum의 구현을 보지 않아도 바로 확인할 수 있다는 장점이 있고,
rawValue의 값이 제목이면 제목, 수량이면 수량 등, 해당 값이 어떤 의미의 값인지 명확하게 표현할 수 있다는 것이 주된 이유입니다.

2. `결국은 enum의 값들과 중복되는 부분이 많아서 삭제` -> 좋습니다 👍

3.  struct를 통해서 현업에서는 이런 struct 데이터 모음을 잘 사용하는지 enum 타입으로 잘 사용하는지
상황에 따라 다를것 같아요. 

지금 코드에는 두가지 상황이 있어 보이는데,

a. enum의 case에 따라 달라지는 경우
b. '상수'의 nameSpace 정의에 사용되는 경우

두 상황 별도로 분리해서 판단하는것이 좋아보입니다 👍

이렇게 상황을 분리한 경우,
어떠한 방식이 각 상황에 더 적절할지 두분이서 우선 고민해주시면 좋을것 같습니다! 👍

궁금한점이나, 같이 논의하고 싶은 내용이 있으신 경우 언제든 해당 PR코멘트 / discord로 말씀해주세요 👍

수고하셨습니다!

2022-08-31 09:23 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private init() {
오 `private init()`을 사용하여 외부에서 `FruitStore`의 인스턴스가 생성되지 않도록 제한하신 방법 너무 멋지네요! ☀️

2022-08-31 09:23 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits: [Fruit : Int] = [:]
`dictionary`를 잘 활용하셨네요! 🙌
다만 해당 선언부를 보고, dictionary의 값이 수량(amount) 이라는 것을 파악하기 어려워 보입니다 😭

해당 값이 (fruit / amount) 로 구성되어 있다는 사실을 인지할 수 있도록 개선할 수 있을까요?

2022-08-31 09:23 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            print("\(juice.rawValue) 완성")
`Juice`의 이름을 해당 enum case의 rawvalue로 지정하여 사용하는것 보다, enum value를 사용하면 어떨까요?
"___ 완성" 에서, ___에 들어갈 내용을 enum의 구현을 보지 않아도 바로 확인할 수 있다는 장점이 있습니다. 👍

추가로, "Juice의 이름" 이 반드시 유니크한 값이 될것이라는 보장이 없기 때문에, 구조적으로 수정이 필요한 상황이 발생할 수 있습니다.

2022-08-31 09:23 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) {
`parameter label`을  underscore(_)로 정의해 주셨는데, 해당 개념을 적용한 메소드와 적용하지 않은 메소드가 있는것 같습니다!
사용하신 기준이 있나요? 🙋🏻‍♂️

2022-08-31 09:23 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +extension JuiceMakerError: LocalizedError{
컨벤션에 대한 리뷰입니다!

extension의 시그니쳐 뒤에 중괄호('{')가 띄워지지 않은 상태로 작성이 된 것 같아요!
모든 사용부에 ('{')를 띄우는 컨벤션으로 작성해주셨는데, 이부분만 띄워져있지 않네요 😇

해당 컨벤션이 기능에 직접적인 영향이나 가독에 영향을 미치지는 않지ㅁ..

![image](https://user-images.githubusercontent.com/52942409/187623882-637740da-78e4-4270-8a01-e12c2cf7e21a.png)

ㅎㅎ 참고 부탁드립니다. 😁

2022-08-31 09:23 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipe: [Fruit : Int] {
앗 이곳에는 `[Fruit : Int]`타입을 recipe를 표현하는 수단으로 사용하셨네요! 👀

`dictionary`의 value값이 어떤 수량을 나타내는지 명시적으로 구분이 필요해 보이는데, 좋은 방법이 있을까요? 🙋🏻‍♂️

2022-08-31 09:23 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let fruitAmount = fruits[fruit] else {
해당 로직이 중복으로 사용되네요! 👀
`func useFruits(recipe: [Fruit : Int]) throws` 메서드와, `func fetchFruitAmount(fruit: Fruit) throws -> Int` 메서드에서 동일한 로직이 사용되네요! 👀

하나로 통합해서, 관리포인트를 줄일 수 있을것 같아요.
관리포인트를 줄이는 행위는, 이후 유지보수의 피로도를 줄이는 등, 유지보수에 용이해진다는 장점이 있습니다.

2022-09-01 02:19 UTC, jjpush commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private init() {
감사합니다!!

2022-09-01 02:19 UTC, jjpush commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits: [Fruit : Int] = [:]
typealias를 이용해서 개선을 해보았습니다 😄

2022-09-01 02:20 UTC, lws2269 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let fruitAmount = fruits[fruit] else {
좋은 의견 감사합니다!! `useFruits`에서 사용되는 로직을 `fetchFruitAmount` 메서드를 호출하는 것으로 변경하였습니다.!!

2022-09-01 02:21 UTC, lws2269 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipe: [Fruit : Int] {
`typealias`를 활용하여 `Int` 타입을 `Amount`타입으로 치환하여 사용하는 방법을 채택해보았습니다!

2022-09-01 02:22 UTC, jjpush commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits: [Fruit : Int] = [:]
<img width="694" alt="스크린샷 2022-09-01 11 19 56" src="https://user-images.githubusercontent.com/82566116/187818357-89a1b8db-c42c-4fb8-bc4e-4991d6c24142.png">

저희가 고민을 하면서 장단점을 비교해보았는데 파일을 만들어서 typealias를 적어두는 방법을 선택했습니다.
각 타입들을 봤을 때 typealias가 어떻게 구현되어 있는지 들여다봐야하는 번거로움의 단점을 좀 더 크게 보고 사용하는 파일에 각각 명시를 해 주었습니다.

토니라면 어떤방식을 쓰셨을까요? 🤔 의견이 궁금합니다!

2022-09-01 02:24 UTC, lws2269 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) {
함수의 네이밍과 파라미터가 자연스럽게 읽힐 경우 `_`를 채택하였는데, 
말씀해주신대로 어느 곳에선 사용하고, 어느 곳에선 사용하지않고, 기준이 명확하지 않았던 것 같습니다!
좋은 의견 감사합니다!!

2022-09-01 02:28 UTC, jjpush commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            print("\(juice.rawValue) 완성")
생각하지 못했던 부분이었습니다! enum에 name 연산프로퍼티를 만들어서 구현부를 보지 않게 해두었습니다! 👍

2022-09-01 02:31 UTC, jjpush commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            print("\(juice.rawValue) 완성")
`추가로, "Juice의 이름" 이 반드시 유니크한 값이 될것이라는 보장이 없기 때문에, 구조적으로 수정이 필요한 상황이 발생할 수 있습니다.`
이부분이 잘 이해가 되지 않습니다!

2022-09-01 04:05 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruits: [Fruit : Int] = [:]
오호 typealias를 통해 접근하신 부분이 인상깊네요 👀 ✨

제시해 주신 방향에 대한 제 의견을 남겨보겠습니다!

1번 방법을 적용했을 때 발생하는 단점을 해소하기 위해서 2번과 같은 방향을 제시 해 주신것 같아 보이네요!
생각의 흐름을 파악할 수 있고, 방향을 결정하신 이유가 명확해서 좋은것 같아요.

다만, 파일의 내용이 길어지고 typealias 정의부를 한눈에 볼 수 없는 상황이 발생하면 해당 문제가 동일하게 발생할 수 있습니다.
typealias가 무슨 타입인지 일일이 확인이 필요한 이유는 파일이 분리되어 발생하는것이 아니라,
타입을 치환하여 사용해서 발생되는 단점은 아닐까요?

그리고, 두번째 방법에서 말씀주신 단점은
말씀주셨듯, Amount를 나타내는 타입이 변경되었을 경우, 수정해주어야 하는 관리포인트가 그만큼 늘어나게 불편함이 생기게 됩니다.

음.. struct를 활용해서 해소해볼 수 있을것 같은데, 
혹시 struct를 통해서 해당 타입을 정의하는 방향에 대해서는 검토해 보셨나요 ? 🙋🏻‍♂️

2022-09-01 04:17 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            print("\(juice.rawValue) 완성")
rawValue의 값은 unique한 값이 되어야 합니다.
하지만, 만약 아래의 경우처럼 rawValue의 값이 unique하지 못한 상태가 발생하게 되면 오류가 발생하게 되는 상황을 말씀드렸습니다!

```swift
case strawberryByjpush = "딸기쥬스"
case strawberryByTony = "딸기쥬스"
```

그렇게 되면, rawValue가 중복되는 문제가 발생하므로 구조적으로 수정이 필요한 상황이 발생하게 됩니다!

이런 상황을 말씀드렸는데, 혹시 이해에 도움이 되셨을까요 ~? 🙋🏻‍♂️

2022-09-01 09:41 UTC, Monsteel approved these changes
첫 스텝 수고하셨습니다 🙌🙌 앞으로도 잘 부탁드려요! ✨

2022-09-01 09:42 UTC, merged