쥬스 메이커 [Step1] Baem, Jeremy
yagom-academy/ios-juice-maker pull request #248
Opened 2022-08-30 06:24 UTC by yjjem

@hansangjin96  안녕하세요 havi !! 🪴
Step 1 PR 보내드립니다.
많이 혼내주세요. 매를 좋아합니다.
감사합니다.

## 고민한점 🤔
`FruitStore`에 각 `Fruit` 의 값을 저장할 방식을 고민했습니다.
처음에는 변수로 지정하여 사용했지만 기능들을 구현함에 있어 어려움이 많았습니다. 특히 재료 혼합 쥬스의 경우 여러 종류의 `Fruit` 가 들어가게 되면 코드가 복잡해지고 길어지는 문제가 있었습니다. 이는 값 저장 방식으로 딕셔너리를 채택하여 해결했습니다.

## 기능 ⚙️ 
- JuiceMaker
    - `makeJuice` : 주스 재고 확인 후 재고 변경해 주는 메서드
- FruitStore
    - `checkStockAvailability` : 재고가 충분한지 확인해주는 메서드
    - `manageStockOf` : 재고가 충분한지 확인 후, 재고 조정해주는 메서드
- StockError 
    - `outOfFruit` : 재고가 없음을 알리는 에러
    - `noEnoughFruit` : 재고가 충분하지 않음을 알리는 에러
- Fruit : 과일 종류 열거형
- Juice : 주스 종류 열거형

2022-08-30 08:46 UTC, hansangjin96 requested changes
수고하셨습니다 :)
궁금하신 점 있으시면 질문 주세요!

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    throws {
throws에서 개행이 들어갔는데, 제가 알기로 대중적인 코드 컨벤션에서는 throws를 붙여 쓰는거로 알고있어요 :)

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
해당 함수의 역할은 쥬스에 대한 잔고를 확인한 뒤 쥬스를 만들 수 있는지 없는지에 대한 체크를 하는 함수라고 이해했는데요,

abs()함수를 쓰셨는데 그럼 재고가 음수가 될 수도 있다는걸 의미하는 걸까요?
함수가 의미하는 바와 안에서 수행하는 역할을 다시 한 번 생각해보시면 좋을거 같아요 👍

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func manageStockOf(_ juice: Juice) {
위 함수에서는 `func checkStockAvailability(of juice: Juice)` 라고 작성해주셨는데요, 해당 함수에서는 external name이 없이 함수명에 Of가 있네요.
이렇게 작성해주신 이유가 있을까요?

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func manageStockOf(_ juice: Juice) {
`func manageStockOf(_ juice: Juice)`라고 함수 시그니쳐를 작성해주셨는데요,
해당 함수가 하는 역할은 쥬스를 만들고 난 뒤에 재고에 있는 과일의 수량을 쓴 큼 줄여주는거 같아요. 
근데 만약 요구사항을 모르는 이 프로젝트를 처음보는 사람이 이 함수를 본다면 해당 역할을 유추하기 힘들 수도 있다는 생각이 들어요.
이렇게 네이밍을 하신 이유가 있을까요?

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                stock += amount
해당 로직에서는 self가 가지고 있는 stock에서 재고를 꺼내서 지역변수로 만들고, 해당 지역변수를 amount로 처리해주고 있네요. 
그런데 이 로직대로라면 여기서 self가 가지고 있는 stock의 재고가 바뀔지 고민해보시면 좋을꺼 같아요 : )

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var name: [Fruit: Int] {
쥬스를 만들 때 쓰일 과일과, 해당 과일이 필요한 개수를 표현하는 프로퍼티라고 이해했습니다.
근데 `name`이라는 변수명이 해당 역할을 한다고 보기는 어려울거 같아요.
네이밍에 대한 고민을 조금 더 해보시면 좋을거 같습니다! 👍

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +            return [.strawBerry: -16]
요기서 두번째 Int의 값을 음수로 설정하신 이유가 있으실까요?

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var store = FruitStore()
`private` 키워드로 외부에서 접근하지 못하게 한 점 좋습니다 :)

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var store = FruitStore()
`JuiceMaker`가 가지고 있는 store가 변할 수 있는 프로퍼티일까요? let과 var중에 var를 사용하신 이유가 궁금합니다.

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
`func makeJuice(_ juice: Juice) throws`의 시그니쳐를 봤을 때 에러를 throw한다고 이해되는데요, 이 부분에서 에러를 do-catch로 핸들링 하면 해당 함수는 에러를 throw하지 않게 되는게 아닐까 싶어요.
에러를 어디에서 핸들링해야할 지 다시 한 번 고민해보시면 좋을거 같습니다 :)

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        store.manageStockOf(juice)
위에서 과일의 재고를 체크하는 로직이 있는데요,
재고를 체크해서 부족한지 아닌지와 관계없이 재고처리가 되고있는거 같아요.
요 부분도 위와 함께 고민해보시면 좋을거 같아요.

2022-08-30 08:46 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkStockAvailability(of juice: Juice)
함수 네이밍이 이해하기 좋네요 👍

2022-08-31 06:10 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    throws {
확인 후 대중적인 코드로 throws를 붙여 사용 하는것으로 통일했습니다
```swift 
func checkStockAvailability(of juice: Juice) throws {
```

2022-08-31 06:10 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        store.manageStockOf(juice)
위와 같이 `requestStockAvailability()` 함수를 분리하면서 Bool 값을 반환하도록 구현했습니다.
```swift
if requestStockAvailability(for: juice) {
    store.useStockForRecipe(of: juice)
}
```
if 문을 통과해야 재고처리가 되도록 변경했습니다. 감사합니다. 👍

2022-08-31 06:11 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
`makeJuice()`함수에서 에러 핸들링 기능을 분리한 `requestStockAvailability()`함수를 외부에 추가했습니다. 감사합니다. ☺️

2022-08-31 06:14 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
처음 `Fruit` 열거형에서 음수값을 적용하게 되어서 abs()를 사용했었습니다.
리뷰를 받고 나서 의미를 더 명확하게 하기 위해 abs대신 등호를 사용해서 다시 변경했습니다.
```swift
 stock > abs(amount) else 
```

아래와 같이 변경 했습니다.
```swift
stock < requiredamount else
```
감사합니다!

2022-08-31 06:16 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    private var store = FruitStore()
속직하게 답변드리자면 생각없이 변수로 지정해 사용했습니다. 고민해본 결과 `store` 값이 직접적으로 변하는 것이 아니라면 상수로 지정하는게 맞다고 판단되어 아래와 같이 변경했습니다. 감사합니다. 😬
```swift
private let store = FruitStore()
```

2022-08-31 06:17 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func manageStockOf(_ juice: Juice) {
다른 함수명을 생각하다가 미처 적용하지 못했던것 같습니다.

`useStockForRecipe(of: )`

로 변경 했습니다. 감사합니다!😀

2022-08-31 06:18 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func manageStockOf(_ juice: Juice) {
처음에 재고를 관리한다는 의미에서
`manageStockOf` 를 사용 했습니다.
정확하게 유추 할 수 있도록 네이밍을 아래 처럼 변경했습니다
`useStockForRecipe`

2022-08-31 06:22 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                stock += amount
지역변수로 만들어져서 적용이 된다는 사실을 인지하지 못하고 있었습니다.
아래와 같이 코드를 변경해서 딕셔너리 타입의 `stock`을 `updateValue`를 사용해서 값을 변경하도록 했습니다.

```swift
            if let stock = self.stock[fruitName] {
                self.stock.updateValue(stock + requiredamount, forKey: fruitName)
            }
```
감사합니다!! 😀

2022-08-31 06:27 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +            return [.strawBerry: -16]
초기에 구현을 하면서 "소모되는 갯수" 라고 기준을 잡았었습니다.  하지만 고민해본 결과 양수로 사용하고 필요시 `Substraction(-)` 이나 `비교 연산자` 를 사용하는게 옳다고 판단하여 아래와 같이 변경하였습니다. 🤔
```swift
var name: [Fruit: Int] {
    switch self {
    case .strawBerry:
        return [.strawBerry: 16]
```
양수를 사용하여 `stock - abs(amount)` 에서 아래와 같이 `<` 를 사용하여 비교하는 방식으로 수정했습니다.
```swift
guard let stock = self.stock[fruitName], stock < requiredamount else {
    throw StockError.notEnoughFruit
}
```

2022-08-31 06:31 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var name: [Fruit: Int] {
코멘트 감사합니다. `name` 에서 `recipe`로 변경하였습니다 ! ☺️ 😆
```swift
var recipe: [Fruit: Int] {
    switch self {
    case .strawBerry:
        return [.strawBerry: 16]
```

2022-08-31 15:22 UTC, hansangjin96 requested changes
리뷰 잘 반영해주셔서 감사합니다 ㅎㅎ
코멘트 달아주신 부분들 조금만 더 고민해보시면 더 좋은 코드가 될거 같아요 :)

2022-08-31 15:22 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//  Created by yagom.
여기만 야곰이 남아있는건 오타일까요? ㅎㅎ

2022-08-31 15:22 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        for (fruitName, requiredamount) in juice.recipe {
amount에서 a를 소문자로 작성하신 이유가 있으실까요??

2022-08-31 15:22 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                throw StockError.notEnoughFruit
0일 때 outOfFruit, 요구사항보다 적을 때 notEnoughFruit 에러를 떤지도록 작성해주셨는데,
각각의 에러에 따라 어떻게 에러핸들링을 할지 계획하고 StockError를 설계하셨을까요?
어떤 고민을 하셨는지 궁금합니다 :)

2022-08-31 15:22 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipe: [Fruit: Int] {
딕셔너리를 사용해서 recipe을 표현해주셨는데요,
recipe이 tuple, struct, class 등 다른 타입이었을 때에는 어떤 장단점이 있는지도 한 번 생각해보시면 좋을거 같아요 :)

2022-08-31 15:22 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
이 함수를 외부해서 호출했을 때, 항상 true를 반환할거 같네요.
어떤 경우에 이 함수를 사용할지, 이 함수의 기대값이 무엇일지 다시 한 번 고민해보시면 좋을거 같아요!

2022-09-01 07:52 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        for (fruitName, requiredamount) in juice.recipe {
이전 리뷰서 말씀해 주셨는데, 엑스코드 이슈가 생겼어서 확인하면서 놓친 것 같습니다
`requiredamount ` -> `requiredAmount `변경했습니다.
다음부터 하나하나 다시 확인해 보도록 하겠습니다. 🤙
감사합니다.

2022-09-01 08:22 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//  Created by yagom.
통일하여 변경했습니다.
감사합니다~!

2022-09-01 08:31 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
위의 함수가 항상 `true`를 반환하는것은 의도된 것이 아닙니다. 해당 문제를 해결하기 위해 아래 코드 예시와 같이 `try`후  `catch`되는 에러가 없다면 `true`를 반환하고, 에러가 `catch` 된다면 `false` 반환하도록 했습니다. 
```swift
try store.checkStockAvailability(of: juice)
// error를 catch 하면 지나가고 아니라면 true를 반환
return true
```
```swift
func requestStockAvailability(for juice: Juice) -> Bool {
        do {
            try store.checkStockAvailability(of: juice)
            return true
        } catch StockError.notEnoughFruit {
            print("재고 부족")
        } catch StockError.outOfFruit {
            print("재고 없음")
        } catch {
            print("Unknown Error")
        }
        return false
    }
}
```

이런식으로 `Bool` 값을 반환해주는 해당 함수는  `makeJuice()`함수 내부에서 재고를 소모하기전에 재고의 유무를 `Bool` 형태로 반환하여 재고가 있어야 재고가 소모될 수 있도록 해줍니다.
```swift
func makeJuice(_ juice: Juice) {
        if requestStockAvailability(for: juice) {
            store.useStockForRecipe(of: juice)
        }
    }
```

감사합니다 ☺️

2022-09-01 08:33 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                throw StockError.notEnoughFruit
프로젝트 요구사항에 `이 외에 더 필요한 기능, 특성, 타입이 있으면 자유롭게 추가해도 좋습니다.` 라는 문구가 있어 별다른 의미없이 "있으면 좋게다"라는 생각에 추가적으로 `outOfFruit`에러를 구현했습니다. 
논의간 그 기능은 재고가 없을 시 버튼 혹은 해당 과일 이미지가 `비활성화`되면 좋겠다는 의견이 있었습니다. 
`notEnoughFruit` 에러의 경우 `Alert` 창을 띄우는 식으로 알리면 좋겠다는 생각이 듭니다. 
감사합니다.  👍

2022-09-01 15:32 UTC, hansangjin96 approved these changes
수정하시느라 고생하셨습니다 👍  : )

2022-09-01 15:32 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(_ juice: Juice) {
사실 네이밍에 정답은 없긴 한데,
제가 알기로 애플에서는 함수명보다 argument를 쓰는것을 권장한다고 알고있어요.
`func make(juice: Juice)`와 같이 써도 괜찮을거 같네요 :)
네이밍이 이상하거나 틀렸다는 코멘트는 아닙니다!

2022-09-01 15:32 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        if requestStockAvailability(for: juice) {
if문으로 작성해주셨는데, if문과 guard문을 사용하는 기준에 대해서도 생각해보시면 좋을거 같아요!
마찬가지로 if문을 사용하는게 이상하거나 틀렸다는 코멘트는 아닙니다!

2022-09-02 10:17 UTC, merged