쥬스 메이커 [STEP 1] inho, 토털이
yagom-academy/ios-juice-maker pull request #249
Opened 2022-08-30 07:24 UTC by inho-98

안녕하세요, @hansangjin96 
토털이와 인호입니다.
부족하지만 코드를 열심히 짜봤습니다.
잘 부탁드립니다!🥰

# 목차
1. [제목](#제목)
2. [팀원](#팀원)
3. [고민했던 점](#고민했던점)
4. [궁금한 점](#궁금한점)

## 제목
 쥬스 메이커

## 팀원
- [토털이]()
- [inho]()

## 고민했던점
#### `JuiceMaker`타입의 `Menu`열거형
`JuiceMaker`타입 내에 `Nested Type`을 이용해 `Menu`열거형을 선언했습니다. 그리고 각 메뉴별로 필요한 재료와 수량을 나타내기 위해 `Menu` 내에 `Recipe`구조체를 선언하고 연산 프로퍼티를 이용하여 아래 코드와 같이 필요한 값을 얻어옵니다. 
```swift
enum Menu {
    case strawberryJuice...
    
    struct Recipe {
            let fruit: Fruit, amount: Int
        }
    var recipe: [Recipe] {
        switch self {
        case .strawberryJuice:
            return [Recipe(fruit: .strawberry, amount: 16)]
        ...
    }
}
```
#### `addStock`과 `useStock`메서드 분리
프로젝트의 요구사항에는 수량을 변경하는 메서드를 구현하도록 되어있었는데요,
하나의 메서드에서 수량을 늘이고 줄이는 역할을 모두 하려면 함수의 매개변수에 음수가 들어가야 했습니다.
하지만 해당 부분은 분리할 수 있는 부분이라고 생각하여 따로 구현하였습니다.
```swift
func addStock(of fruit: Fruit, amount: Int) 
func useStock(of fruit: Fruit, amount: Int)
```

## 궁금한점
1. 처음에는 `fruitStock` 변수에 각 `Fruit`케이스와 초기값을 일일이 작성하였습니다. 그런데 이런 방식은 확장성이 떨어진다고 생각해서 `Fruit`타입과 `forEach`메서드를 이용해서 초기화하도록 수정하였습니다. 코드의 이해나 가독성 부분에서는 첫번째 방법이 더 나을수도 있을지 고민되는데요, 이에 대한 하비의 의견이 궁금합니다!🤔

    - 코드 수정 전
    ```swift
    var fruitStock: [Fruit: Int] = [.strawberry: 10, .banana: 10, .pineapple: 10, .kiwi: 10, .mango: 10]
    ```
    - 코드 수정 후
    ```swift
    let initialStock = 10
    var fruitStock = [Fruit: Int]()

    init() {
        Fruit.allCases.forEach { fruit in
            fruitStock[fruit] = initialStock
        }
    }
    ```

2. 음료를 제조할때 두가지 이상의 재료가 이용되는 경우에, 각 재료들의 수량을 먼저 파악하기 위해 반복문이 한번, 또 제조가 가능한지 확인된 후에 음료를 만들기 위해 반복문 한번, 총 두번 등장해야 했습니다.
이 부분을 해결하기 위해 `JuiceMaker`타입 내의 `Menu`를 `FruitStore`의 `checkStock`메서드에 전달하여 재고를 판단하고 있는데요, 이 방법이 객체지향의 관점에서 문제가 없는지 궁금합니다!🤔

    ```swift
    //함수 호출 부분
    fruitStore.checkStock(for: juice)
    //함수 정의 부분
    func checkStock(for juice: JuiceMaker.Menu) throws { ... }
    ```

3. 전제적으로 네이밍과 컨벤션에 대한 조언이 궁금합니다.

4. 코드의 개선 방향 혹은 잘못된 지점이 궁금합니다.
---
혹시 직접 보여주고 싶거나 조언하고 싶으신게 있으시면 디스코드에서 만나서 이야기해보는 것도 저희는 항상 좋습니다! 감사합니다☺️

2022-08-30 08:45 UTC, hansangjin96 requested changes
수고하셨습니다 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    let initialStock = 10
initialStock이 FruitStore외부에서도 쓰일까요? private키워드가 붙으면 좋을거 같아요 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +
`궁금한점1`에서 말씀하주신 내용처럼 initialStock으로 과일의 재고들을 초기화 해주셨는데요,
만약 요구사항이 과일마다 다를 경우에는 어떻게 초기화해주는게 좋을지 고민해보시면 좋을거 같아요 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(of fruit: Fruit, amount: Int) {
해당 함수의 네이밍이 잘 이해가 되지 않는데요, of라는 전치사가 어색해보이네요 ㅎㅎ
해당 함수가 하는 역할에 따라 다시 한 번 고민해보시면 좋을거 같아요!

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func useStock(of fruit: Fruit, amount: Int) {
이 함수도 마찬가지로 `과일의 재고를 쓴다`가 음.. 과일이 가지고 있는 재고를 쓴다고 읽혀지네요 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            let totalStock = currentStock - amount
여기서 totalStock이 음수가 될 가능성은 없는지 고려해보셨을까요?

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
재고에 대한 확인 처리는 잘 읽히는거 같아요 💯

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let currentStock = fruitStock[recipe.fruit],
만약에 새로운 레시피가 추가되고, 가지고 있는 fruitStock에 레시피에 있는 과일이 없다면 어떻게 될지 생각해보시면 좋을거 같습니다! :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +             mangoKiwiJuice
보통 열거형의 경우 `,`로 구분하기 보다는
```
case strawberryJuice
case bananaJuice
```
와 같이 쓰는게 일반적인거 같아요 :)
열거형의 컨벤션도 고민해보시면 좋을거 같습니다.

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
이 부분도 위와 마찬가지로
```
let fruit: Fruit
let amount: Int
```
와 같이 표현되면 더 읽기 좋을거 같아요.

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        var recipe: [Recipe] {
Enum과 Struct 사이에 개행이 추가된다면 더 읽기 좋을거 같습니다 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        var recipe: [Recipe] {
쥬스에 따른 `Recipe`를 만들어 주신거 너무 좋습니다 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                        Recipe(fruit: .kiwi, amount: 1)]
딸기 바나나 쥬스를 시킬 경우 receipe에는 여러 개의 레시피가 있다고 착각할 수도 있을거 같은데요,
Recipe의 배열을 반환하는거 외에 다른 방법이 있을지 고민해보시면 좋을거 같아요 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var fruitStore = FruitStore()
해당 프로퍼티가 외부에서 쓰일 가능성이 있을지, 변경될 가능성이 있을지 고민해보시면 좋을거 같습니다 :)

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func produce(juice: Menu) {
만약 쥬스가 아닌 다른 매장을 파는 가게라면 juice의 타입에 대한 네이밍이 `Menu`로 읽히는게 맞을지 고민해보시면 좋을거 같아요.

2022-08-30 08:45 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
`JuiceMaker` 내부에서 에러를 핸들링하고 있는데 이 부분에서 에러를 핸들링해야겠다고 생각하신 이유가 있을까요??

2022-08-30 08:45 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(of fruit: Fruit, amount: Int) {
재고가 추가될 수도 있는 부분 염두해주신거 좋네요 💯

2022-09-01 01:32 UTC, tottalE commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    let initialStock = 10
네 바꿔 주었습니다 감사합니다 ^^~

2022-09-01 01:33 UTC, tottalE commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var fruitStore = FruitStore()
네 상수로 선언하고 private으로 바꾸어주었습니다 감사합니다~^^

2022-09-01 01:48 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +
한줄로 작성할 수 있는 코드를 고차함수를 이용하여 초기화 해주었는데요,
각 케이스의 초기값이 다른 경우에 대한 처리방법과 가독성, 확장성이 기존의 초기화 방법이 더 낫다고 판단해서 수정했습니다.

그런데 케이스가 더 많아질 경우에 대해서 어떤 방법이 좋을지 아직 잘 모르겠습니다. 🤔

2022-09-01 02:07 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(of fruit: Fruit, amount: Int) {
해당 메서드는 과일의 재고를 늘려주는 역할을 하고 있습니다.
그래서 `과일의 수량을 얼만큼 늘린다` 라는 의미로
`func add(_ fruit: Fruit, amountOf amount: Int)` 로 수정하였습니다!

2022-09-01 02:08 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func useStock(of fruit: Fruit, amount: Int) {
위 코멘트와 같은 내용입니다.
`func use(_ fruit: Fruit, amountOf amount: Int)`로 수정하였습니다.

2022-09-01 02:08 UTC, tottalE commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
감사합니다:)

2022-09-01 02:11 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            let totalStock = currentStock - amount
기존에는 해당 메서드 조건문에서 말씀해주신 음수가 되지 못하도록 확인하는 코드가 있었습니다. 
그런데 요구사항에 따라 수량이 줄어들기 전에 음료를 제조할 수 있는지(수량이 충분한지) 확인하는 메서드 내에서 음수가 될지 확인 하고 있어서, 

해당 메서드에서는 음수를 고려하는 부분은 삭제했습니다!

2022-09-01 02:20 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let currentStock = fruitStock[recipe.fruit],
해당 부분은 말씀해주신대로 과일이 없는 경우를 처리하기 위해 
```swift 
guard let currentStock = fruitStock[recipe.fruit] else {
    throw JuiceMakerError.invalidFruit
}
            
guard currentStock >= recipe.amount else {
    throw JuiceMakerError.outOfStock
}
```
위와 같이 로직을 분리하였습니다!

2022-09-01 02:21 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +             mangoKiwiJuice
말씀해주신대로 열거형에서 case를 나눠서 입력한다고 알게되었습니다!
감사합니다😁

2022-09-01 02:21 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
수정하였습니다! 👍

2022-09-01 02:42 UTC, tottalE commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(of fruit: Fruit, amount: Int) {
감사합니다!

2022-09-01 02:42 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                        Recipe(fruit: .kiwi, amount: 1)]
말씀해주신대로 기존 코드는 한 메뉴에 여러개의 레시피를 담고있는 것처럼 보였습니다! 그래서 하나의 레시피에 재료에 대한 정보를 담도록 코드를 수정했습니다!
```swift
struct Recipe {
   let ingredient: [Fruit: Int]
}

var recipe: Recipe {
    switch self {
    ...
    case .mangoJuice:
        return Recipe(ingredient: [.mango: 3])
    case .mangoKiwiJuice:
        return Recipe(ingredient: [.mango: 2, .kiwi: 1])
    }
}
```

2022-09-01 02:48 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func produce(juice: Menu) {
`Menu`라는 네이밍은 포괄적이라는 생각이 들어서, 직관적으로 `Juice`라는 네이밍으로 수정했습니다! 감사합니다😁

2022-09-01 02:58 UTC, tottalE commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
이게 더 자연스러운 흐름이라고 판단해서 코드를 작성했는데, checkStock에서 에러를 처리하는게 좋을지 produce에서 에러처리를 하는게 좋을지 판단이 정확히 서지 않습니다. 괜찮으시다면 하비의 의견이 궁금합니다!

2022-09-01 15:04 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +
음 제 생각에 코드에는 정답이 없다고 생각하는데요,
가독성과 확장성&기능 중에 고르라고 하면 기능에 대한이 더 중요하다고 고를 수 있을거 같아요 :)
다만 둘 다 챙기는게 베스트일거 같구요 ㅎㅎ
만약 저라면 깊게 생각해보지는 않았지만 `Fruit`안에 computed property로 각 과일마다의 initialStock을 가지고 있게하고,
FruitStore에서 변수 선언해줄 때 allCases를 돌면서 초기화시켜주지 않을까 싶네요 ㅎㅎ

2022-09-01 15:17 UTC, hansangjin96 approved these changes
열심히 고민하시는 모습이 보기 좋습니다 : )

2022-09-01 15:17 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitStock: [Fruit: Int] = [.strawberry: 10, .banana: 10, .pineapple: 10, .kiwi: 10, .mango: 10]
충분한 고민이 있으셨던거 같아서 보기 좋습니다 :)
이건 개인적인 취향인데 저라면 이렇게 여러개의 인자를 가진다면
```
[
  .strawberry: 10, 
  .banana: 10, 
  .pineapple: 10, 
  .kiwi: 10, .mango: 10
]
```
요런 식으로 띄워 쓰는거 같아요!

요건 취향이니 이렇게도 쓸 수 있구나만 알아두시면 좋을거 같아요 :)

2022-09-01 15:17 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func add(_ fruit: Fruit, amountOf amount: Int) {
수정해주신 것 좋습니다 👍 
개인적인 취향으로는 와일드카드 패턴을 쓰는걸 별로 안좋아해서 
저라면 이 함수의 파라미터를
`func add(fruit: Fruit, amount amount: Int)`
요렇게 작성했을거 같아요 ㅎㅎ

2022-09-01 15:17 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            let ingredient: [Fruit: Int]
ingredient라는 property가 추가되서 읽기 훨씬 좋아진거 같습니다 💯 
추가적으로 고민해보시려면 ingredient의 타입을 [Fruit: Int]로 선언해주셨는데,
딕셔너리, tuple, struct, class 등 다른 타입으로 선언하면 어떤 차이가 있을지도 고민해보시면 좋을거 같아요 : )

2022-09-02 10:17 UTC, merged