쥬스 메이커 [Step1] Kyo, 하모(태리)
yagom-academy/ios-juice-maker pull request #251
Opened 2022-08-30 08:02 UTC by lxodud

@Monsteel 
안녕하세요 토니! 하모와 Kyo가 열심히 Step1을 진행했습니다.
리뷰 잘 부탁드립니다👍👍👍

### 진행 단계 : Step1
## ⭐️ 구현한 기능
- `Fruit`, `Juice`, `JuiceMakerError`를 `enum`타입으로 정의하여 사용하였습니다.
- `FruitStore` 클래스
    - `fruitStock`: 현재 과일의 재고를 저장하는 프로퍼티(`Dictionary` 타입)
    - `init()`: 과일의 초기재고(`defaultStock`)를 설정해주는 이니셜라이저
    - `bringFruitStock()`: 현재 과일의 수량을 가져오는 메서드
    - `addFruits()`: 필요한 과일의 수량을 증가시키는 메서드
    - `substractFruits()`: 필요한 과일의 수량을 현재 재고에서 차감하는 메서드
    
- `JuiceMaker` 구조체
    - `manufactorJuice()`: 주스를 제조하는 메서드로 가정을 하고, 내부 구현에서 Juice 제조에 사용한 과일의 수량을 재고에서 차감시키는 메서드
    - `checkStock()`: 주문이 들어온 Juice 제조에 들어가는 과일의 수와 과일의 재고를 비교하는 메서드, 재고가 부족할 시 `outOfStock`이라는 품절처리 에러를 `throw`합니다.
    - `filterError()`: do-try-catch를 사용하여 위의 `checkStock()`메서드를 handling하는 메서드입니다. 에러가 발생하지 않을 경우 true를 반환합니다.

## ⭐️ 코드를 작성할 때 고민되었던 점
- `manufactorJuice()`에서 모든 Juice 케이스를 Switch문을 통해 선택할때 Switch 문이 커지는 점을 고민해봤습니다.
    - 한 가지 이상의 기능을 한다고 생각되어서 Juice를 선택하는 로직을 Juice 열거형 타입에 기능 분리 하였습니다.

- `manufactorJuice()`에서 에러를 핸들링하기 위해서 do-catch문을 사용하게 되었을 때 현재는 에러가 1개여서 짧지만 여러 케이스가 생겼을 때 catch문이 많아지게 되면 가독성이 떨어지는 점에 대해서 고민해봤습니다.
    - 에러를 캐치하는 메서드를 따로 기능분리하였습니다.
    - Result Type에 대한 고민을 하고 있습니다.

## ⭐️ 해결이 되지 않은 점
- 현재까지 해결이 되지않은점은 다행히 없는 것 같습니다!

## ⭐️ 조언을 얻고 싶은 부분 

- 매직리터럴,넘버등을 모아놓는 파일을 따로 만들어서 사용을 하고 싶은데 혹시 현업에서 이러한 파일들 명칭을 뭐라고하는지, 또한 이런 경우에는 어떠한 타입을 이용하는지 궁금합니다. (저희는 enum타입으로 예상하고 있습니다...) 
- 중첩타입을 사용을 해보고 싶어 Juice enum에서 구조체를 만들어 recipe내부를 구현을 했었습니다. 하지만 직접 Computed Property로 구현하는 것이 더 깔끔하고 가독성이 좋아보였습니다. 토니의 생각은 어떠신지 궁금합니다!

2022-08-31 12:38 UTC, Monsteel requested changes
안녕하세요! Kyo, 하모! :)
첫번째 스텝! 수고 많으셨습니다! 👍

++ 하모는 이름이 두개이신것 같네요 ㅋㅋㅋ  어떤 이름으로 부르는게 편하실까요 ~? ㅎㅎ

-- 

PR내용에, 구조에 대한 설명과, 고민하신 부분을 잘 남겨주셔서 코드를 파악하고 여러분들의 생각의 흐름을 파악하는데에 큰 도움이 되었습니다 🙇🏻‍♂️ 감사합니다!

코드에 대한 코멘트는 아래 리뷰를 확인해주시구요! 이곳에는 남겨주신 "조언을 얻고 싶은 부분"에 대한 저의 생각을 남겨보도록 할게요!

### 1. 매직리터럴,넘버등을 모아놓는 파일 명칭이 무엇인지, 선언 할 때에 어떠한 타입을 이용하는지 궁금합니다.
우선, 매직리터럴, 넘버를 모아놓고 관리포인트를 일원화 하시려는 방향성, 아주 멋집니다 ✨

코멘트를 남기기 전에,
'현업에서 이러한 파일들 명칭을 뭐라고하는지' 라는 질문을 주셨는데,

"현업에서 사용하는 방식 == 신뢰할 수 있는, 믿음직한 방식" 이라고 생각하신다면,
그것은 사실이 아닌 미신이라고 생각합니다.

현업이라는 기준이 굉장히 광범위하고, 코드가 탄생한 장소가 다를 뿐, 현업에서 사용한다고 무조건
신뢰할 수 있는 믿음직한 방식은 아닙니다.

존재할 수 없는 방향을 따라가는것 보다,
선택할 수 있는 여러 방식을 비교(사고)해보고, 스스로 선택하실 수 있는 개발자가 되셨으면 좋겠습니다 👍

===

혹시 enum 타입으로 예상하신 이유가 있나요 ?
저도 상수 선언 시, NameSpace로 활용하는 경우 enum 사용이 조금 더 적절하다는 생각을 가지고 있습니다.

두분이 enum타입으로 예상하신 이유가 궁금해지네요 :) 코멘트로 남겨주시면, enum을 사용하는 이유에 대해 이어서 이야기해보면 좋을것 같습니다.

* 이러한 파일들 명칭에 대해 질문을 주셨는데, 정답이 없는 문제이다 보니 해당 변수를 잘 나타낼 수 있는 예쁜 이름을 지어주시면 좋을것 같아요!

저는 개인적으로 "변하지 않는 값"을 의미하는 "상수"라는 개념을 사용하여, 이름을 지을때도 상수(constant)라는 개념을 포함시키려고 하는 편입니다.

### 2. Computed Property로 구현하는 것이 더 깔끔하고 가독성이 좋아보였습니다. 토니의 생각은 어떠신지 궁금합니다!

아주 좋습니다!
Computed Property를 사용했다는 사실이 좋은것이 아닙니다.

중첩타입을 사용을 해보고 싶다는 이유로
Juice enum에서 구조체를 만들어 recipe내부를 구현을 했지만, 가독성이 좋지 못하다는 이유로
Computed Property를 사용하는 방향으로 전환하신 이유있는 판단이 아주 좋다고, 아주 멋지다고 생각합니다! ✨

==

궁금한점이나, 같이 논의하고 싶은 내용이 있으신 경우 언제든 해당 PR코멘트 / discord로 말씀해주세요 👍

수고하셨습니다!

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitStock: [Fruit : Int] = [:]
dictionary를 잘 활용하셨네요! 🙌
dictionary의 value 가 fruit의 stcock이라는 사실을 인지할 수 있도록 이름을 붙여주셨네요! 멋집니다 👍

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipe: [(name: Fruit, count: Int)] {
recipe의 타입을 다루는 상황이 생기면,
tuple 타입 (name: Fruit, count: Int) 을 일일이 선언하고 사용해야 하는 번거로움(불편함)이 생기게 되는데, 이를 해결할 수 있는 방법이 없을까요 ?

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +enum Fruit: Int, CaseIterable {
`Int`구현을 따르도록 코드를 작성해 주신 이유가 있나요 ? 👀

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func filterError(juice: Juice) -> Bool {
`filterError`라는 네이밍을 통해 해당 함수가 하는 일을 파악하기 어려워 보입니다.

한 함수가 여러가지 역할을 수행하기 때문에 어려울수도 있고,
오류를 필터한다는 의미가 실제 오류를 처리하는 개념과 충돌하기 때문일수도 있을것 같아요.

해당 함수의 구현을 잘 파악할 수 있는 더 멋진 이름은 없을까요 ? 👀

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            return isNotSoldOut
bool 타입의 변수명에 `Not`이라는 부정이 들어가게 되니 해당 값의 정확한 의도를 바로 파악하기 어려워 보여요.
해당 값이 false인 경우 "부정의 부정" 과 같은 불필요한 사고의 흐름이 생겨서 그렇게 되는것 같습니다.

조금 더 한눈에 이해할 수 있는 멋진 이름은 없을까요? 👀

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            return false
이렇게 false를 return하게 되는 경우 해당 값이 어떤 값인지 파악하기 위에서는
해당 메소드 내의 다른 부분 (isNotSoldOut을 return하는 코드) 을 보지 못하면 파악하기가 어렵습니다.

해당 함수의 네이밍으로 잘 표현해볼 수 있을것 같기도 하구요!
해당 부분을 개선할 수 있는 방법을 고민해봐 주시면 좋을것 같아요 🙋🏻‍♂️

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard var fruitAmount = fruitStock[fruit] else {
해당 검증 로직(guard문)이 중복으로 사용되네요! 👀
addFruits(fruit: Fruit, amount: Int) 메서드와, substractFruits(juice: Juice) 메서드에서 동일한 로직이 사용되네요! 👀

하나로 통합해서, 관리포인트를 줄일 수 있을것 같아요.
관리포인트를 줄이는 행위는, 이후 유지보수의 피로도를 줄이는 등, 유지보수에 용이해진다는 장점이 있습니다.

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func checkStock(juice: Juice) throws -> Bool {
checkStock이 return하는 값이 정확이 어떤 의미를 가지는지 한눈에 파악하기 어렵습니다.
true인 경우는 어떤 상황인지, false인 경우는 어떤상황인지 빠르고 명확하게 확인할 수 있도록 개선할수는 없을까요 ? 👀

2022-08-31 12:38 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func manufactorJuice(menu: Juice) {
parameter label이라는 개념을 활용해서 menu == juice, 동일한 변수임을 명시하여, 
juice / menu가 혼동되어 사용하는 상황을 개선시킬 수 있을것 같아요 🙋🏻‍♂️

2022-08-31 12:38 UTC, Monsteel commented on README.md
> +# Juice Maker
ReadME! 야무지게 잘 적어주셨네요 ✨

2022-09-01 02:26 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitStock: [Fruit : Int] = [:]
감사합니다!👍

2022-09-01 02:28 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipe: [(name: Fruit, count: Int)] {
말씀하신대로 tuple을 일일이 선언해줘야하는 불편함이 있을 것 같아 
`typealias RecipeType = (name: Fruit, count: Int)` 로 수정하였습니다.
말씀하신 피드백 사항이 해당 부분으로 해결이 되었을까요??

2022-09-01 02:35 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +enum Fruit: Int, CaseIterable {
해당 `Int` 구현은 사용하지 않아 삭제 수정하였습니다..ㅎㅎ

2022-09-01 02:37 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func filterError(juice: Juice) -> Bool {
``` swift
func canManufactorJuice(juice: Juice) -> Bool { 
``` 
위에 함수명으로 수정하였습니다. 음료제조를 할 수 있는지 없는지를 판단할 수 있는 네이밍으로 고려하였습니다.

2022-09-01 02:39 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            return isNotSoldOut
```swift
 func canManufactorJuice(juice: Juice) -> Bool {
        var isEnoughStock: Bool = false
```
위와 같이 변수네이밍을 변경하였습니다. "충분한 재고여부가 있나"를 네이밍으로 선정하여 최대한 직관적으로 판단할 수 있게 고려하였습니다.

2022-09-01 02:42 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            return false
```swift
func canManufactorJuice(juice: Juice) -> Bool {
        var isEnoughStock: Bool = false
        
        do {
            isEnoughStock = try checkEnoughStock(juice: juice)
            return isEnoughStock
        } catch JuiceMakerError.outOfStock {
            print("과일 재고 품절입니다.")
            return isEnoughStock
        } catch {
            print("some error")
            return isEnoughStock
        }
    }
```

isEnoughStock를 지역변수 기본값 false를 가지게 하여 return되는 값이 어떠한 의미를 가지는 값인지 파악하기 쉽게 변경하였습니다.

2022-09-01 02:42 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitStock: [Fruit : Int] = [:]
감사합니다!👍👍👍

2022-09-01 02:43 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func checkStock(juice: Juice) throws -> Bool {
```swift
func checkEnoughStock(juice: Juice) throws -> Bool {
```
위와 같은 메서드 이름으로 변경을 하였습니다. 충분한 재고가 있는지를 체크하여 return값의 의미를 바로 알 수 있도록 고려해보았습니다.

2022-09-01 02:46 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func manufactorJuice(menu: Juice) {
```swift
func manufactorJuice(orderJuice: Juice) {
```
위와 같이 parameter자체 네이밍을 수정하였습니다. 피드백 주신대로 약간 모호함이 있어 변경을 하였지만, parameter네이밍을 수정한 것이 피드백내용에 부합하는지 궁금합니다.

2022-09-01 02:46 UTC, KyoPak commented on README.md
> +# Juice Maker
오.. 감사합니다 👍

2022-09-01 02:56 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard var fruitAmount = fruitStock[fruit] else {
```swift
func addFruits(fruit: Fruit, amount: Int) {
```
메서드는 과일의 수량을 더할때 사용하는 메서드로 구현을 하였습니다.

```swift
 func substractFruits(juice: Juice) {
```
메서드는 쥬스를 만들고 그 쥬스에 사용되는 과일의 갯수를 차감하는 메서드로 구현을 하였습니다.

저랑 하모랑 의논을 해본 결과
이번 step-1에서는 두가지 메서드를 합쳤을 때, 하나의 메서드에서 두가지 기능을 한다고 생각되어서 분리하게 되었습니다. 또한 그 메서드에서 추가인지 차감인지 Bool 타입으로 내부에서 받게 된다면 조건문을 통해 체크로직이 들어가야하는데 아직은 불필요하다고 느꼈습니다.!

추후 진행할 step의 재고수정 기능에서 +버튼, -버튼을 눌렀을때 addfruit()메서드와 별도로 재고수정을 차감하는 메서드를 만들어서 구별을 해야할 것 같습니다.

혹시 Tony의 생각은 어떠신가요..?
+ 관리포인트를 줄여나가야 한다는점 꾸르팁 감사합니다 👍

2022-09-01 03:03 UTC, KyoPak commented
추가로 NameSpace 파일을 별도로 생성해보았습니다!

저와 하모가 의논한 결과  구조체, 열거형으로 관리를 하는 방법이 있었는데, 구조체를 쓸 경우에는 초기화를 private로 해줘야했습니다. 열거형을 사용한다면 신경쓸 필요가 없다고 생각해서 열거형으로 구현하였습니다..! 
파일명은 `ConstantNameSpace` 로 해보았습니다! 

추가로 파일 내부로 들어가보시면 네이밍이 상당히.. 길어지는데 이러한 점들은 어떻게 관리를 해야할까요 ?
Tony의 의견을 기다립니다! 

Kyo,  하모

2022-09-01 04:27 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func filterError(juice: Juice) -> Bool {
@KyoPak 혹시 해당 네이밍이 어떤 의미일까요? Manu는 menu의 오타인걸까요?!

2022-09-01 04:30 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func manufactorJuice(menu: Juice) {
[Functions — The Swift Programming Language (Swift 5.7)](https://docs.swift.org/swift-book/LanguageGuide/Functions.html) 문서의 Argument Label이라는 개념을 활용해보면 좋을것 같아요 ✨

2022-09-01 04:34 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard var fruitAmount = fruitStock[fruit] else {
아하!

요 guard문의 중복사용에 대한 부분을 이야기드렸는데, 혹시 동일한 부분에 대해 이야기를 주신게 맞을까요?! 🙋🏻‍♂️
```swift
guard var fruitAmount = fruitStock[fruit] else {
  return
}
```

2022-09-01 04:40 UTC, Monsteel commented
> 

네임스페이스 정의에 있어서 struct에 비해 enum이 더 적절하다는 근거있는 판단 너무 좋습니다. 👍

이름이 길어지는 부분에 있어서는, enum에 정의되어 있는 상수들의 특성을 고려하여 enum의 이름을 결정하게 되면,
usage 같은 반복적으로 사용되는 네이밍을 사용하지 않아도 될 것 같다는 생각 듭니다 👍

2022-09-01 09:27 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func filterError(juice: Juice) -> Bool {
제조하다의 manufacture 이란 단어를 사용하였는데 오타여서.. 수정하였습니다.

2022-09-01 09:29 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func manufactorJuice(menu: Juice) {
``` swift
func manufactureJuice(menu juice: Juice) {
```
로 수정하였습니다! menu와 juice가 동일하다는 것을 명시하였습니다. !

2022-09-01 09:36 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard var fruitAmount = fruitStock[fruit] else {
해당 두 부분을 한 메서드에서 묶으려고 하였습니다. 하지만 옵셔널 값을 언래핑하는 과정에서 언래핑을 하지못했을 경우  return해야 하는 값을 정하지 못했습니다. 그래서 ConstantNameSpace를 모아둔 파일에
```swift 
static let invalidFruit: Int = -1
```
를 추가하였습니다. 그리고 코드 로직상으로는 발생하지 않을 에러인 "존재하지 않는 과일오류" 에 대해서도 에러case추가 하였습니다.
```swift
func bringValidFruitStock(_ fruit: Fruit) -> Int {
```
위 메서드에서 옵셔널언래핑 기능을 가지고 있는 `bringFruitStock()`을 `try`호출하고 존재하지 않을 경우 에러를 throw하였습니다.

저희가 너무 깊게 생각을 한건지.. 옵셔널 언래핑 실패할 경우 return  할 값들을 정하지 못하여 에러케이스까지 추가하게 되었습니다.
Tony라면 옵셔널 언래핑 실패할 경우 return 값을 정할 때 어떤 방식으로 처리를 하는지 궁금합니다!

저희가 처음 구현한 코드보다 다소 복잡해진것 같습니다 🤣
이 부분에 대해서도 어떻게 생각하시는지, 어떻게 저희가 처리해나갈 것을 기대하셨는지? 궁금합니다!!

2022-09-01 09:51 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard var fruitAmount = fruitStock[fruit] else {
멋진 생각의 흐름입니다. 👏

두분이 생각하신 생각의 흐름이, 실제로 `throw`라는 개념이 탄생하게 된 배경과 유사합니다!
`throw`라는 개념까지 생각하신 이 시점에서, 저의 기대를 말씀드리는건 큰 의미가 없어보이네요 :>

다소 복잡해 보일지는 몰라도,
throw라는 개념을 접하고 적용하고, 어떤 상황에 사용이 되는지에 대해 파악하신 점으로 큰 의미가 있다고 생각합니다.

이번에 throw를 한번 사용해 보셨으니, throw라는 개념과 친해지는 시간을 가져도 좋을것 같아요~ ✨

2022-09-01 12:43 UTC, Monsteel approved these changes
첫 스텝 수고하셨습니다 🙌🙌 앞으로도 잘 부탁드려요! ✨

2022-09-01 12:43 UTC, merged