쥬스 메이커 [STEP 1] LJ, som
yagom-academy/ios-juice-maker pull request #252
Opened 2022-08-30 08:05 UTC by jsa0224

안녕하세요, @junbangg !

아직 완벽하게 구현되지 않은 느낌이지만, 알라딘의 조언을 얻고자 PR을 보내봅니다!

# 고민되었던 점

- 두 가지 과일을 사용해서 만들어야하는 주스의 경우, 두 종류 모두 재고가 있는지 확인 후에 주스를 만들어야 했습니다. 수정 전에는 딸기바나나주스의 경우  딸기먼저 재료사용 후 바나나 재고없을시 제조불가, 불필요하게 딸기가 사용되는 논리적 오류가 발생하였습니다.
    
    ➡️  해결방법 : 열거형 안에 구조체를 선언하여 nested type을 이용하여 해결하였습니다. first, second 중 second를 옵셔널타입으로 선언하여 두가지종류가 필요한 과일주스만 두가지 모두 확인을 하도록 구현하였습니다.
    

# 해결이 안 되는 점
<img width="646" alt="스크린샷 2022-08-30 오후 5 03 52" src="https://user-images.githubusercontent.com/94514250/187383760-e0a8f6f5-dfdf-4451-9cfa-332c627cbca1.png">

- Xcode를 Run하면 이런 에러 메세지가 뜨는데, 해결방법을 모르겠습니다…🥺
- 과일을 2가지 쓰는 경우, 1개의 과일은 재고가 없고, 나머지 과일에 재고가 있을 경우, 나머지 과일은 차감되는 상황을 어떻게 해결해야할지 모르겠습니다.

# 조언을 얻고 싶은 부분

- 기존의 1-2주차 프로젝트는 콘솔창과 대화하는 형태의 프로그래밍이었는데, 이 프로젝트는 View Controller을 이용하여 익숙치 않은 느낌이 듭니다. 이런 부분에 대해 조언 얻고 싶습니다!

2022-08-30 16:25 UTC, junbangg requested changes
수고하셨습니다! 가독성에 대한 노력이 보이는 코드였습니다!
댓글 참고 해주세요!🙏

그리고 질문 주신 내용에 대한 답변을 해드리자면

## 해결이 안되는 점
이 부분은 댓글을 참고하시면 될것 같습니다..!
그래도 해결이 안된다거나 고민이 남아있으시다면 디스코드로 함께 이야기 나눠보면 좋을것 같아요:)

## 조언을 얻고싶은 점
콘솔 프로그램을 하시다가 갑자기 `ViewController` 가 나와버려서 조금은 어색하실 수 있을것 같은데
하다보면 재미도 있고 금방 적응하실거라 생각합니다 :) 

구체적으로 어떤 부분들에 대한 조언이 필요하신지 이것도 추가적인 질문을 해주시거나
디스코드로 한번 이야기 같이 나누면 좋을것 같아요!

수고하셨어요!

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  // 과일 저장소 타입
요 주석이 필요한 이유가 있을까요?!
코드에 주석이 필요한 경우는 어떤 경우라고 생각하시는지 궁금합니다!:)

(실수로 남겨 놓으셨더라도 이번 기회에!)

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit.allCases.forEach { stock[$0] = defaultStock }
질문 있습니다👋
`defaultStock` 는 생성자를 통해서 받고 
`stock` 라는 딕셔너리 타입은 클래스 내부에서 직접 생성해서 사용하고 있는 이유가 있을까요??
틀렸다는건 아닙니다!

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeFruitStock(fruit: Fruit, amount: Int) throws {
지금도 네이밍이 괜찮지만
파라미터 레이블을 잘 활용하면 조금 더 개선 될 수 있을것 같아요..!

힌트를 하나 드리자면 메서드명 + 레이블 + 파라미터 로 자연스러운 영어 문장을 구성할 수도 있을것 같아요👍

이건 어디까지나 제 개인적인 스타일 이긴 합니다:)

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let countFruit = stock[fruit] else {
흠 countFruit를 처음 봤을때 메서드명 처럼 느껴진 이유는 뭘까요🤔

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
여기 있는 들여쓰기 21, 25 번째 줄은 두분이서 사전에 동의한 컨벤션인걸까요???

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
👀 여기도 주석이 있네요..!

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
`FruitStore` 는 클래스로, `JuiceMaker` 는 구조체로 사용한 이유는 뭘까요?!
틀렸다는건 아닙니다 :)

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(of juice: Juice) {
메서드명에 대한 고민이 느껴지고 `of` 를 사용해서 가독성을 높이려고 한 노력 아주 좋아요!
근데 읽었을때 `make juice of juice` 라고 읽히는데 조금은 개선할 수 없을까요???

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipeOfJuice: Ingredient {
밑 댓글이랑 이어지는 이야기인데 요 연산 프로퍼티의 이름은 `recipeOfJuice` 인데 타입은 `Ingredient` 이네요!

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    }
요 타입의 네이밍과 역할이 조금 애매해보여요..!
`Ingredient` 라는 이름을 갖고있는데 역할은 `Recipe` 에 더 가까워 보이는것 같습니다 ..!

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    }
튜플을 이용한 시도는 좋았습니다! 
하지만 조금 더 생각해보면 지금은 요 타입이 두개의 재료로 구성되고 있는데(`first`, `second`)  
만약에 먼미래에 엄청 도전적인 쥬스메뉴가 요구사항에 추가되는 상황이 생기면 어떻게 될까요?? 
예를 들어서 `딸기바나나초코키위 쥬스` 가 생기는 상황? 

레시피의 형태를 조금 더 유연하게 가져갈 수는 없을까요??

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit.allCases.forEach { stock[$0] = defaultStock }
딕셔너리를 이용해서 과일마다 재고를 넣어준 아이디어 좋습니다! 👏👏👏
근데 실제 과일가게는 어떨지도 한번 생각해볼 필요가 있을것 같아요:)
지금은 과일가게의 모든 과일들을 `defaultStock` 만큼 재고를 동일하게 채우고 있는데
만약에 과일마다 재고를 다르게 채워야되는 상황이 생기면 어떨까요??🤔 

ex)
딸기: 3개, 바나나: 1개, 키위: 23개

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
재고가 떨어진 상황을 예외처리로 예리하게 잘 캐치 해주셨네요 👍

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = net.yagom.JuiceMake;
흠 이거 오타 난걸까요???

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeFruitStock(fruit: Fruit, amount: Int) throws {
한가지 더 짚고 넘어가고싶은 부분이 있는데 요 메서드가 지금 몇가지의 일을 하고 있을까요???

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
"해결하지 못한 점" 에서 말씀해주신 부분이 여기 같은데🤔
메서드가 조금 더 유연해진다면 해결이 될것 같아요..!

과일을 두개 쓰는 경우, 하나 쓰는 경우, 이런식으로 경우의 수를 딱 정하고 그거에 맞춰서 코딩을 하면서 발생한 문제로 판단됩니다.
조금 더 간단하게 생각해봐도 괜찮을것 같아요..!

질문 주신 문장을 한 번 볼게요!

"나머지 과일의 재고가 있을 경우, 나머지 과일은 차감되는 상황을 어떻게 해결해야할지 모르겠습니다."

여기서 우리가 필요로 하는 근본적인 메서드들을 뽑아볼 수 있을것 같아요.
**"~~나머지~~ 과일의 재고가 있을 경우"**
**"~~나머지~~ 과일은 차감되는 상황"**

이걸 메서드로 바꿔보면
`func 과일의_재고가_있나?() -> Bool {}`
`func 과일의_재고를_차감() {}`

이렇게 쪼개볼 수 있을것 같아요!

2022-08-30 16:25 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
윗 댓글이 이해 되셨다면(제가 글을 잘 못써서ㅋㅋ)
`changeFruitStock()`에 제가 달아놓은 댓글을 한 번 다시 봐주시면 감사하겠습니다 🙏

2022-08-31 01:20 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  // 과일 저장소 타입
주석이 필요한 경우는 저작권자 또는 작성자를 표시해야한다고 생각합니다.
수정하였습니다.😄

2022-08-31 01:34 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  // 과일 저장소 타입
앗코멘트 표기기 제대로 안돼서 헷갈리셨을 수도 있을것 같은데
9번째 줄에 대한 이야기였습니다!

2022-08-31 01:46 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit.allCases.forEach { stock[$0] = defaultStock }
- stock 라는 딕셔너리 타입은 클래스 내부에서 직접 생성해서 사용하고 있는 이유
`FruitStore` 객체가 과일들을 관리하는 역할을 수행해야하기 때문에, 여기서 직접 생성을 하고 있습니다.

- 과일마다 재고를 다르게 채워야되는 상황
```Swift
// FruitStore 메서드

func inputFruitNumber(
        strawberryNumber: Int?,
        bananaNumber: Int?,
        pineappleNumber: Int?,
        kiwiNumber: Int?,
        mangoNumber: Int?
    ) {
        guard strawberryNumber != nil else {
            return
        }
        guard bananaNumber != nil else {
            return
        }
        guard pineappleNumber != nil else {
            return
        }
        guard kiwiNumber != nil else {
            return
        }
        guard mangoNumber != nil else {
            return
        }
        stock[.strawberry] = strawberryNumber
        stock[.banana] = bananaNumber
        stock[.pineapple] = pineappleNumber
        stock[.kiwi] = kiwiNumber
        stock[.mango] = mangoNumber
    }
```
```Swift
// JuiceMaker 메서드

  func setFruitNumber() {
        fruitStorage.inputFruitNumber(strawberryNumber: 3, bananaNumber: 1, pineappleNumber: nil, kiwiNumber: 23, mangoNumber: nil)
    }
```
알라딘이 질문하신 내용을 저희가 코드로 구현해봤을 때는 이 코드가 간결성이 떨어져서 어떻게 구현해야할지 감이 오지 않습니다. 혹시 어떤 방식으로 구현해야할지 조언해주실 수 있으실까요?

2022-08-31 01:48 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeFruitStock(fruit: Fruit, amount: Int) throws {
네! 알라딘이 조언해주신 방법이 더 직관적일 거 같습니다👍 
그리고 기능 분리 부분도 수정하도록 하겠습니다!

2022-08-31 01:52 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeFruitStock(fruit: Fruit, amount: Int) throws {
넵 파라미터 레이블을 amountOfFruit 으로 개선하였습니다.
자연스러운 영어 문장으로 구성하는것이 코드읽힐 때도 좋을 것 같습니다.👍

2022-08-31 01:54 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let countFruit = stock[fruit] else {
아, count가 동사여서 메서드명처럼 느껴진 것 같습니다. 상수명을 amountOfFruit 으로 수정하였습니다.😄

2022-08-31 01:56 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
앗 놓친부분이 있었네요 무의미한 개행입니다. 수정하였습니다.😀

2022-08-31 02:02 UTC, jsa0224 commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = net.yagom.JuiceMake;
<img width="648" alt="스크린샷 2022-08-31 오전 11 01 36" src="https://user-images.githubusercontent.com/94514250/187576338-babcdb43-12ed-4bc8-a8f9-818cbe00bebe.png">
앞서 질문했던 이 문제를 해결하기 위해 다른 캠퍼분이 알려주신 방법대로 시도해본 결과물입니다...ㅎㅎ 아직 해결되지는 않았습니다ㅠㅠ

2022-08-31 02:12 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
FruitStore 클래스는 값(재고)가 계속 바뀌기 때문에 구조체처럼 복사해온 값이 아닌 참조하고있는 실제 메모리값을 변경해주어야 해서 클래스로 사용했다고 생각합니다.
JuiceMaker는 값이 바뀌지 않기 때문에 구조체로 사용했습니다.😄

2022-08-31 02:15 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(of juice: Juice) {
`makeJuice(of order: Juice)` 로 변경하여 `make juice of order`로 읽힐 수 있게 개선하였습니다.🤓

2022-08-31 02:19 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    }
recipe로 수정하였습니다.🤓  레시피형태는 좀 더 고민해보겠습니다!

2022-08-31 02:24 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
기능 분리를 해서 과일의 재고가 먼저 있는지 체크를 하고 차감되는 방식으로 진행하면 될 거 같습니다!
좋은 조언 감사드립니다, 알라딘!😄👍

2022-08-31 15:45 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        Fruit.allCases.forEach { stock[$0] = defaultStock }
넵 ! 이 부분도 시간 정해서 같이 이야기 해봐요~!

2022-09-05 17:00 UTC, junbangg approved these changes

2022-09-05 17:00 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                self.stock.updateValue(stock - amountOfFruit, forKey: fruit)
29번째 줄은 `self.stock` 을 해주셨는데 28번째 줄은 그냥 stock 이네요??! 
이건 스타일 차이라서 통일만 해주시면 좋을것 같습니다 👍

2022-09-05 17:03 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var recipeOfJuice: [Fruit: Int] {
딕셔너리로도 좋지만
`Ingredient` 타입을 활용한 배열로 표현해보는건 어떨까요?
```swift
struct Ingredient {
  let fruit: Fruit
  let amount: Int
}
```
요런식으로 `Ingredient` 를 나타낸다면 
`var recipe` 도 쉽게 표현이 가능할것 같아요!

더 나아가서 `Recipe` 라는 객체도 만들 수 있을것 같고요!

꼭 할 필요는 없지만 한 번 상의 해보시고 같이 이야기해보면 좋을것 같습니당

2022-09-05 17:05 UTC, merged

2022-09-05 17:08 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkStockBeUsed(in juice: Juice) throws {
요 메서드는 한번 셋이 같이 고민해보고 고쳐보면 좋을것 같아요 :)