쥬스메이커 [STEP 1] 미니, 애쉬
yagom-academy/ios-juice-maker pull request #256
Opened 2022-08-31 01:10 UTC by ash-youu

- 안녕하세요, James! (@inwoodev) 🤓
-  STEP 1까지 구현되어 첫 PR을 보내드립니다!

### 🤔 고민한 점
1. `Fruit Store` 에서 `increaseStock` 함수의 네이밍이 괜찮은지 조언이 필요합니다.
    ```swift
	func increaseStock(of fruits: [Fruit], by amounts: [Int]) {
        for (fruit, stock) in zip(fruits, amounts) {
            if let remainingStock = inventory[fruit] {
                inventory.updateValue(remainingStock + stock, forKey: fruit)
            }
        }
    }
    ```
    - 이 함수의 네이밍을 `changeStock`으로 하는 것과 `increaseStock`으로 하는 것에서 고민하였습니다.
    - 함수 내부 구현 상 `-` 기호가 없어서 `increase`라는 단어가 더 잘 함수를 표현한다고 생각하였습니다. 하지만, 함수의 기능으로 보았을 때에는`change` 라는 단어가 더 적절하다고 생각하였습니다.
    - 어떤 단어를 사용하는 것이 적절한지 궁금합니다.

2. 가변 매개변수를 활용하는 방법과 리스트를 반환하는 방법중에 어떤 것이 더 나은지 궁금합니다.
    ```swift
    // Before
    func makeJuice(juice: Juice) {
         switch juice {
            ...
         case .strawberrybananaJuice:
             if fruitStore.checkStock(fruit: .strawberry, stock: -10) &&
                 fruitStore.checkStock(fruit: .banana, stock: -1) {
                 fruitStore.changeStock(fruits: .strawberry, .banana, stocks: -10, -1)
             }
         case .mangokiwiJuice:
             if fruitStore.checkStock(fruit: .mango, stock: -2) &&
                 fruitStore.checkStock(fruit: .kiwi, stock: -1) {
                 fruitStore.changeStock(fruits: .mango, .kiwi, stocks: -2, -1)
             }
         }
     }
    ```
    ```swift
    // After
    func makeJuice(juice: Juice) {
        let juiceNeedFruits = juice.needFruits
        let juiceNeedStocks = juice.needStocks
        
        do {
		try fruitStore.haveStock(of: juiceNeedFruits, over: juiceNeedStocks)
		fruitStore.increaseStock(of: juiceNeedFruits, by: juiceNeedStocks)
        } catch StoreError.outOfStock {
            print("재고가 부족합니다.")
        } catch {
            print("알 수 없는 오류가 발생하였습니다.")
        }
    }
    ```
    - `juice`의 연관값과 가변 매개변수를 활용하여서 `haveStock(fruits:, stocks:)`와 `increaseStock(fruits:, amounts:)` 함수를 구성할 시, `makeJuice(juice:)` 함수에서 위의 함수를 호출하도록 구현했었습니다.
    - 하지만, 호출 시 juice의 각 케이스 별로 `haveStock`과 `increaseStock`을 각각 호출해줘야 하는 문제가 발생하였습니다.
    - 그래서 각 매개변수에 대한 리스트를 `juice` 타입이 반환할 수 있도록 구현했습니다.
    - 또한, 이에 대해서 Dictionary 타입을 반환하여서 `haveStock`과 `increaseStock`에서 불필요한 함수인 `zip`을 제거하는 방법을 활용하는 것이 적절한지 고민됩니다.
###
### 🤷‍♀️ 궁금한 점
1. 기능을 개발 시, 버그를 찾거나 버그를 사전에 방지할 수 있는 방법에는 어떤 방법이 있는지 궁금합니다.

2022-09-01 09:20 UTC, inwoodev commented
미니, 애쉬! 안녕하세요, 제임스입니다~ 여러분의 멋진 첫 번째 PR을 확인하게 되어서 기쁩니다. 제가 아는 선에서 최대한 제 생각을 풀어서 답변 드리도록 하겠습니다 :)

그 전에 먼저 **제가 드리는 조언은 절대 정답이 아니라는 점** 만 먼저 말씀 드리고 싶습니다. 저도 아직 부족한 점이 많은 개발자이기 때문에 적절하지 않은 답변을 드릴 수도  있습니다. 혹시나 잘못되었다 생각 되는 부분이 있다면 가감없이 얘기 해 주세요. 상호간의 피드백을 통해 같이 성장해 봅시다~~ 🥇 

> 1. Fruit Store 에서 increaseStock 함수의 네이밍이 괜찮은지 조언이 필요합니다.
``` swift
func increaseStock(of fruits: [Fruit], by amounts: [Int]) {
    for (fruit, stock) in zip(fruits, amounts) {
        if let remainingStock = inventory[fruit] {
            inventory.updateValue(remainingStock + stock, forKey: fruit)
        }
    }
}
```

>    이 함수의 네이밍을 changeStock으로 하는 것과 increaseStock으로 하는 것에서 고민하였습니다.
    함수 내부 구현 상 - 기호가 없어서 increase라는 단어가 더 잘 함수를 표현한다고 생각하였습니다. 하지만, 함수의 기능으로 보았을 때에는change 라는 단어가 더 적절하다고 생각하였습니다.
    어떤 단어를 사용하는 것이 적절한지 궁금합니다.

1. 일단 현재 구현된 부분에서는 제 생각에는 `increaseStock` 이 네이밍이 더 적절해 보입니다. 미니와 애쉬가 아닌 다른 사람이 해당 코드를 보았을 때 어떻게 작동하는지 더 직관적이게 이해할 수 있다고 생각했기 때문이죠 :) 그런데 만약 추후 더하는 기능 뿐 아니라 빼는 기능 또한 포함이 되어야할 경우 `changeStock` 메서드가 더 적절하다 판단될거 같네요 😁

---

> 가변 매개변수를 활용하는 방법과 리스트를 반환하는 방법중에 어떤 것이 더 나은지 궁금합니다.

``` swift
// Before
func makeJuice(juice: Juice) {
     switch juice {
        ...
     case .strawberrybananaJuice:
         if fruitStore.checkStock(fruit: .strawberry, stock: -10) &&
             fruitStore.checkStock(fruit: .banana, stock: -1) {
             fruitStore.changeStock(fruits: .strawberry, .banana, stocks: -10, -1)
         }
     case .mangokiwiJuice:
         if fruitStore.checkStock(fruit: .mango, stock: -2) &&
             fruitStore.checkStock(fruit: .kiwi, stock: -1) {
             fruitStore.changeStock(fruits: .mango, .kiwi, stocks: -2, -1)
         }
     }
 }

// After
func makeJuice(juice: Juice) {
    let juiceNeedFruits = juice.needFruits
    let juiceNeedStocks = juice.needStocks
    
    do {
	try fruitStore.haveStock(of: juiceNeedFruits, over: juiceNeedStocks)
	fruitStore.increaseStock(of: juiceNeedFruits, by: juiceNeedStocks)
    } catch StoreError.outOfStock {
        print("재고가 부족합니다.")
    } catch {
        print("알 수 없는 오류가 발생하였습니다.")
    }
}
```

>    juice의 연관값과 가변 매개변수를 활용하여서 haveStock(fruits:, stocks:)와 increaseStock(fruits:, amounts:) 함수를 구성할 시, makeJuice(juice:) 함수에서 위의 함수를 호출하도록 구현했었습니다.
    하지만, 호출 시 juice의 각 케이스 별로 haveStock과 increaseStock을 각각 호출해줘야 하는 문제가 발생하였습니다.
    그래서 각 매개변수에 대한 리스트를 juice 타입이 반환할 수 있도록 구현했습니다.
    또한, 이에 대해서 Dictionary 타입을 반환하여서 haveStock과 increaseStock에서 불필요한 함수인 zip을 제거하는 방법을 활용하는 것이 적절한지 고민됩니다.

저도 전자보다는 후자가 조금 더 나은 접근이라고 생각됩니다만 그 이유는 코드가 간결해지면서도 가독성을 그리 해치지 않는다고 생각하기 때문이죠:)
그럼에도 불구하고 현 상황에서 juiceMaker는 juice를 만드는 작업외에도 주입받은 juice 수량체크 후 수량을 조절까지 도맡는거 같습니다. JuiceMaker가 조금 과한 책임을 지게 된다고 생각이 드네요 :( 
그래서 드리는 질문입니다.`FruitStore`에서 재고 수량을 체크하는 로직을 외부(JuiceMaker)로 빼신 이유가 궁금합니다. FruitStore 또는 다른 객체에서 해당 기능이 포함이 되면 안될 이유가 있을까요?

수정된 코드를 보면...지적하신대로 `haveStock`과 `increaseStock`을 각각 순서대로 호출해야만 정상적으로 작동하게 되는데요. 이 때문에 해당 순서가 추후 모종의 이유로 바뀌게 된다면 추후 문제가 생길 수도 있겠다는 생각이 들었습니다. 이 문제를 해결하는 방향으로 비즈니스  로직을 수정하면 어떨까 조심스럽게 의견을 내봅니다. 🤔
---

> 🤷‍♀️ 궁금한 점

>   기능을 개발 시, 버그를 찾거나 버그를 사전에 방지할 수 있는 방법에는 어떤 방법이 있는지 궁금합니다.

현재로서 생각나는 **버그를 최대한 방지할 수 있는 방법**은 **암묵적 입력과 출력**을 최대한 자제하는 것입니다. 해당 부분은 저 보다는 다른 분들이 설명을 잘 해 놓으셨을것이라 생각하기 때문에 구글링을 해 보셔도 좋을거 같습니다~. input과 output이 명확해진다면 생각지 못했던 버그를 맞닥드릴 가능성이 적어진다고 생각해요 :)

저 같은 경우 발생한 버그의 원인을 찾기 위해서 lldb를 적극적으로 활용하며 에러가 나는 부분의 콜스텍을 최대한 자세히 확인하려 하고 있구요. 또한 버그가 발생할 수 있을거 같은 부분에 로그를 찍어놓는 편입니다 :) log를 찍는 객체를 하나 만들어서 활용하는 것도 좋은 방법인듯 합니다 :)

혹시나 더 궁금한 부분이 있으시다면 언제든지 discord로 연락 주세요. 최대한 빠르게 답변 드리도록 노력할게요. 
첫 번째 PR올리시느라 수고 많으셨습니다.

2022-09-01 09:22 UTC, inwoodev requested changes
미니, 애쉬! 안녕하세요, 제임스입니다~ 여러분의 멋진 첫 번째 PR을 확인하게 되어서 기쁩니다. 제가 아는 선에서 최대한 제 생각을 풀어서 답변 드리도록 하겠습니다 :)

그 전에 먼저 **제가 드리는 조언은 절대 정답이 아니라는 점** 만 먼저 말씀 드리고 싶습니다. 저도 아직 부족한 점이 많은 개발자이기 때문에 적절하지 않은 답변을 드릴 수도  있습니다. 혹시나 잘못되었다 생각 되는 부분이 있다면 가감없이 얘기 해 주세요. 상호간의 피드백을 통해 같이 성장해 봅시다~~ 🥇 

> 1. Fruit Store 에서 increaseStock 함수의 네이밍이 괜찮은지 조언이 필요합니다.
``` swift
func increaseStock(of fruits: [Fruit], by amounts: [Int]) {
    for (fruit, stock) in zip(fruits, amounts) {
        if let remainingStock = inventory[fruit] {
            inventory.updateValue(remainingStock + stock, forKey: fruit)
        }
    }
}
```

>    이 함수의 네이밍을 changeStock으로 하는 것과 increaseStock으로 하는 것에서 고민하였습니다.
    함수 내부 구현 상 - 기호가 없어서 increase라는 단어가 더 잘 함수를 표현한다고 생각하였습니다. 하지만, 함수의 기능으로 보았을 때에는change 라는 단어가 더 적절하다고 생각하였습니다.
    어떤 단어를 사용하는 것이 적절한지 궁금합니다.

1. 일단 현재 구현된 부분에서는 제 생각에는 `increaseStock` 이 네이밍이 더 적절해 보입니다. 미니와 애쉬가 아닌 다른 사람이 해당 코드를 보았을 때 어떻게 작동하는지 더 직관적이게 이해할 수 있다고 생각했기 때문이죠 :) 그런데 만약 추후 더하는 기능 뿐 아니라 빼는 기능 또한 포함이 되어야할 경우 `changeStock` 메서드가 더 적절하다 판단될거 같네요 😁

---

> 가변 매개변수를 활용하는 방법과 리스트를 반환하는 방법중에 어떤 것이 더 나은지 궁금합니다.

``` swift
// Before
func makeJuice(juice: Juice) {
     switch juice {
        ...
     case .strawberrybananaJuice:
         if fruitStore.checkStock(fruit: .strawberry, stock: -10) &&
             fruitStore.checkStock(fruit: .banana, stock: -1) {
             fruitStore.changeStock(fruits: .strawberry, .banana, stocks: -10, -1)
         }
     case .mangokiwiJuice:
         if fruitStore.checkStock(fruit: .mango, stock: -2) &&
             fruitStore.checkStock(fruit: .kiwi, stock: -1) {
             fruitStore.changeStock(fruits: .mango, .kiwi, stocks: -2, -1)
         }
     }
 }

// After
func makeJuice(juice: Juice) {
    let juiceNeedFruits = juice.needFruits
    let juiceNeedStocks = juice.needStocks
    
    do {
	try fruitStore.haveStock(of: juiceNeedFruits, over: juiceNeedStocks)
	fruitStore.increaseStock(of: juiceNeedFruits, by: juiceNeedStocks)
    } catch StoreError.outOfStock {
        print("재고가 부족합니다.")
    } catch {
        print("알 수 없는 오류가 발생하였습니다.")
    }
}
```

>    juice의 연관값과 가변 매개변수를 활용하여서 haveStock(fruits:, stocks:)와 increaseStock(fruits:, amounts:) 함수를 구성할 시, makeJuice(juice:) 함수에서 위의 함수를 호출하도록 구현했었습니다.
    하지만, 호출 시 juice의 각 케이스 별로 haveStock과 increaseStock을 각각 호출해줘야 하는 문제가 발생하였습니다.
    그래서 각 매개변수에 대한 리스트를 juice 타입이 반환할 수 있도록 구현했습니다.
    또한, 이에 대해서 Dictionary 타입을 반환하여서 haveStock과 increaseStock에서 불필요한 함수인 zip을 제거하는 방법을 활용하는 것이 적절한지 고민됩니다.

저도 전자보다는 후자가 조금 더 나은 접근이라고 생각됩니다만 그 이유는 코드가 간결해지면서도 가독성을 그리 해치지 않는다고 생각하기 때문이죠:)
그럼에도 불구하고 현 상황에서 juiceMaker는 juice를 만드는 작업외에도 주입받은 juice 수량체크 후 수량을 조절까지 도맡는거 같습니다. JuiceMaker가 조금 과한 책임을 지게 된다고 생각이 드네요 :( 
그래서 드리는 질문입니다.`FruitStore`에서 재고 수량을 체크하는 로직을 외부(JuiceMaker)로 빼신 이유가 궁금합니다. FruitStore 또는 다른 객체에서 해당 기능이 포함이 되면 안될 이유가 있을까요?

수정된 코드를 보면...지적하신대로 `haveStock`과 `increaseStock`을 각각 순서대로 호출해야만 정상적으로 작동하게 되는데요. 이 때문에 해당 순서가 추후 모종의 이유로 바뀌게 된다면 추후 문제가 생길 수도 있겠다는 생각이 들었습니다. 이 문제를 해결하는 방향으로 비즈니스  로직을 수정하면 어떨까 조심스럽게 의견을 내봅니다. 🤔
---

> 🤷‍♀️ 궁금한 점

>   기능을 개발 시, 버그를 찾거나 버그를 사전에 방지할 수 있는 방법에는 어떤 방법이 있는지 궁금합니다.

현재로서 생각나는 **버그를 최대한 방지할 수 있는 방법**은 **암묵적 입력과 출력**을 최대한 자제하는 것입니다. 해당 부분은 저 보다는 다른 분들이 설명을 잘 해 놓으셨을것이라 생각하기 때문에 구글링을 해 보셔도 좋을거 같습니다~. input과 output이 명확해진다면 생각지 못했던 버그를 맞닥드릴 가능성이 적어진다고 생각해요 :)

저 같은 경우 발생한 버그의 원인을 찾기 위해서 lldb를 적극적으로 활용하며 에러가 나는 부분의 콜스텍을 최대한 자세히 확인하려 하고 있구요. 또한 버그가 발생할 수 있을거 같은 부분에 로그를 찍어놓는 편입니다 :) log를 찍는 객체를 하나 만들어서 활용하는 것도 좋은 방법인듯 합니다 :)

혹시나 더 궁금한 부분이 있으시다면 언제든지 discord로 연락 주세요. 최대한 빠르게 답변 드리도록 노력할게요. 
첫 번째 PR올리시느라 수고 많으셨습니다.

2022-09-01 09:22 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +	}
`haveStock()` 메서드에서 throw로 예외처리를 하셨네요. 덕분에 오류를 즉각적으로 확인할 수 있어서 추후 디버깅 시 수월해질거 같아요 👍

2022-09-01 09:22 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -
현상황에서 불필요한 프레임워크를 제거하는건 개인적으로 좋다고 생각합니다 👍

2022-09-01 09:22 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +	case mangokiwiJuice
enum으로 주스 케이스에 제한을 준건 좋은 선택이라고 생각되는데요. 미니와 애쉬가 struct, class 대신 enum을 선택하신 이유가 궁금하네요~ 열거형으로 선언하여 얻는 이점과 단점이 있다면 어떤게 있을까요?

2022-09-01 09:22 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +				inventory.updateValue(remainingStock + stock, forKey: fruit)
zip연산자를 사용하셨네요😁 현재로서는 fruits 배열의 요소 갯수와 needStock 배열의 정수 갯수가 동일해서 문제 없이 사용할 수 있는데요. 음 만약에 juice열거형의 needFruits 배열의 element 갯수와 needStocks 배열이 리턴하는 요소의 갯수가 모종의 이유로 달라지면 문제가 생길 수도 있지 않을까요?

2022-09-01 09:22 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/StoreError.swift
> +}
커스텀 에러를 만드셨군요 👍👍👍

2022-09-01 09:22 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +			fruitStore.increaseStock(of: juiceNeedFruits, by: juiceNeedStocks)
comment확인 부탁드려요~

2022-09-01 13:33 UTC, leegyoungmin commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +	case mangokiwiJuice
struct로도 동일한 기능을 구현할 수 있지만, 열거형은 관련된 값들을 묶어주는 역할을 할 수 있습니다. 그래서 열거형을 활용하였을 때에는 이를 세분화하여서 새로운 그룹에 대해서 대응할 때, 상수를 사용하여서 접근할 수 있는 것이 용이합니다. 하지만, switch 구문이나 조건에 대해서 모두 구현 해주어야 한다는 것이 단점입니다. 예를 들어서, 연관값을 다르게 보내는 케이스들이 많은 경우, 저희가 전에 작성했던 코드 처럼 각각에 케이스에 대해서 대응하게 됩니다.

2022-09-01 13:35 UTC, leegyoungmin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +				inventory.updateValue(remainingStock + stock, forKey: fruit)
저희가 놓쳤던 부분인 것 같습니다.
그래서 배열을 활용하여서 zip 연산자를 활용하는 것 보다는 딕셔너리 타입으로 변경하여서 키-값의 형태로 함수를 호출하여서 위와 같은 문제를 해결하고자 하였습니다.

2022-09-01 13:38 UTC, leegyoungmin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +			fruitStore.increaseStock(of: juiceNeedFruits, by: juiceNeedStocks)
fruitStore의 haveStock을 외부에서 호출하였던 이유는 try를 통해서 함수가 throw를 하지 않는 경우에만 increaseStock을 수행할 수 있도록 하기 위해서 였습니다. 하지만, haveStock 내부에서 for 반복문이 종료되는 시점에 increaseStock을 하도록 하여서 juiceMaker의 역할을 줄이도록 하였습니다.

2022-09-02 02:30 UTC, inwoodev reviewed
고생하셨습니다. 추가적으로 몇 자 코멘트 남겼어요~ 참고해 주시고 준비되셨다 싶으실 때 메세지 주시면 머지하도록 할게요 :)

2022-09-02 02:30 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +		for (fruit, stock) in fruitAndStock {
`JuiceMaker`가 아닌 `FruitStore`에서 호출하여 `JuiceMaker`가 갖고 있던 짐이 좀 덜어졌군요 :) 그런데. `changeStock` 메서드가 내부에서만 호출되는 상황임에도 불구하고 FruitStore의 `changeStock` 메서드는 외부에서도 호출이 되는거 같네요? 개선 해 볼 수 있을까요?

2022-09-02 02:30 UTC, inwoodev commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +		let needFruitAndStock = juice.needFruitAndStock
여기에서도 전달인자 레이블을 활용하여 더 가독성 높은 메서드를 만들 수 있을거 같아요. 가령 for을 추가한다던지요..:)

2022-09-02 08:00 UTC, leegyoungmin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +		for (fruit, stock) in fruitAndStock {
외부에서도 함수를 호출할 수도 있다고 생각하여서 은닉화를 하지 않았는데, 은닉화 하는 것을 기본으로 작성할 수 있도록 하겠습니다. 추가 커밋에 수정하였습니다.

2022-09-02 08:00 UTC, leegyoungmin commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +		let needFruitAndStock = juice.needFruitAndStock
넵 함수의 의미를 더욱 잘 파악할 수 있도록 라벨을 작성해주었습니다.

2022-09-02 09:11 UTC, merged