쥬스 메이커 [STEP 1] 애종, zhilly, bella
yagom-academy/ios-juice-maker pull request #258
Opened 2022-08-31 07:25 UTC by jonghancha

# 쥬스 메이커 [STEP 1] p.r

@wonhee009
안녕하세요 라자냐! 쥬스메이커 한 팀이 된 애종,질리,벨라 입니다.
쥬스메이커 프로젝트 [STEP 1] 리뷰 잘 부탁드립니다! 🙂

## [구조]
```bash
.
├── Controller
│   ├── AppDelegate.swift
│   ├── JuiceMaker.swift
│   ├── SceneDelegate.swift
│   └── ViewController.swift
├── Model
│   ├── Fruit
│   │   ├── Fruit.swift
│   │   └── FruitStore.swift
│   ├── Juice
│   │   ├── Juice.swift
│   │   └── JuiceMaker.swift
│   └── JuiceRecipe.swift
├── Protocol
│   ├── FruitStoreProtocol.swift
│   └── JuiceMakerProtocol.swift
└── View
    ├── Assets.xcassets
    └── Base.lproj
        ├── LaunchScreen.storyboard
        └── Main.storyboard
```
 
## [고민되었던 점]
### ✏️ Class vs Struct
- enum으로 정의한 내용 외에, FruitStore는 class타입으로 JuiceMaker는 struct 타입으로 지정해주었습니다.
FruitStore의 경우 메서드가 있고 JuiceMaker안에서 참조타입으로 소통하고 있다고 생각되어 class를 사용해주었습니다. 
// 다른 이유 설명 필요
- 아직 class와 struct를 구분하는 기준을 프로퍼티의 변경여부 밖에 모르는 것 같습니다. 생성한 인스턴스를 다시 한번 할당해주고 (ex: var fruitStoreCopy = fruitStore = FruitStore()) 복사한 객체 내부에서 값을 바꿨을 때 참조 타입과 값 타입에 차이가 있다는 점은 알겠지만, 이러한 차이를 현실에서의 어떤 상황에 적용시켜야 할 지 잘 모르겠습니다. 우선 아래 문서를 읽어보려고 합니다! 혹시 이 문서 외에도 조언해주실게 있으면 해주시면 감사하겠습니다.
[참고문서 choosing-between-structures-and-classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)

### ✏️ Juice 타입
#### 레시피의 정의
- 레시피에 해당하는 과일과 개수를 딕셔너리로 넣어야 할지, Juice의 case의 rawValue로 넣어야 할지 고민되었습니다. 
enum의 rawValue는 추후 변경하기 어렵다는 생각이 들어 먼저 딕셔너리에 담긴 튜플의 형태로 시도해보다가, `Nested Types`을 이용한 방법이 가독성과 간결함이 더 좋다고 생각되었고 Juice 타입에 Recipe라는 이름의 구조체를 생성하였습니다. first, second의 변수 2개를 두다 보니 재고 체크, 재고 변경할 때 코드의 중복이 나타나기도 했습니다. 이런 불편한 점도 보여 레시피의 구현방식에 대해 중간중간 다시 생각해보기도 했습니다.

#### 복합쥬스의 정의와 인스턴스에 값 할당
- 복합과일쥬스의 경우를 고려하여, Recipe 구조체 안에 프로퍼티를 이용하여 복합과일중 첫번째 '과일&개수'와 두번째 '과일&개수'를 튜플타입으로 표현하였습니다. 
이때에 두번째 '과일&개수'는 복합쥬스가 아닌 경우에는 값이 없을 수도 있어서 옵셔널을 사용하였습니다. 
- Recipe 타입의 recipe 프로퍼티를 생성하고, switch 구문을 이용하여 쥬스에 값에 따른 Recipe 타입의 반환값을 지정해주었습니다. 

### ✏️ FruitStore 타입
- 재고의 경우 [Fruit: Int] 딕셔너리를 이용하였습니다. 재고수량이 Int타입의 10이 반복적으로 사용되는 매직넘버기에, 이를 줄여 표현하고자 `CaseIterable-allcases` 에 대해 고민하게 되었습니다. 
- 재고를 관리하는 함수인 updateFruitStore에서는 과일타입의 fruit key로 접근한 value를 옵셔널 바인딩 해주었으며, View에서 보여지는 버튼에 따라 User가 입력한 버튼이 "+"경우와 그렇지 않을 경우("-")를 나누어 조건을 설정해주었습니다.

### ✏️ JuiceMaker 타입
####  FruitStore타입의 인스턴스 생성
- 요구사항에 명시되어 있는 `JuiceMaker는 FruitStore를 소유하고 있습니다.` 라는 표현이 class를 이용한 상속인지에 대해 서로 의논하다가, JuiceMaker 내부에 인스턴스를 생성하여 프로퍼티와 메서드에 접근이 용이 할 수 있도록 하는 것으로 해석하여 코드를 구현하게 되었습니다. 
#### 주문받는 takeOrder함수 생성
- 주문을 받는 함수를 생성 시에, 복합쥬스의 경우를 생각하여 먼저 Juice타입 내에 recipe의 두번째 '과일&개수'의 값에 접근해 옵셔널 바인딩을 해주고 비교함수를 연달아 호출해주었으며, 그 이후에 첫번째 '과일&개수'도 비교하는 함수를 호출하였습니다.

#### 과일의 재고와 레피시의 재고 비교하는 checkRemainedStock 함수 생성
- (Fruit, Int)튜플 타입을 이용하여 Fruit타입의 과일 이름으로 딕셔너리에 있는 과일의 재고 Value를 옵셔널바인딩을 해주었으며, 옵셔널바인딩한 과일재고와 Recipe타입으로 받아오는 튜플 중 필요과일개수를 비교하는 함수를 구현하게 되었습니다. 

### ✏️ FruitStore와 JucieMaker에 프로토콜을 사용
```swift
protocol FruitStoreProtocol {
    func updateFruitStock(fruit: Fruit, plusOrMinus: String)
    func subtractFruitStock(fruit: Fruit, amount: Int)
    func isEnoughStock(juiceRecipe: (Fruit, Int)) -> Bool
}

let fruitStore: FruitStoreProtocol = FruitStore()

protocol JuiceMakerProtocol {
    func chooseJuice(juice: Juice)
}

let juiceMaker: JuiceMakerProtocol = JuiceMaker()
        juiceMaker.chooseJuice(juice: .mangoKiwiJuice)

```
(예시 코드 입니다!)

- 외부에서 사용할 함수들을 제외하고 접근제어자를 사용해 은닉화를 시켜주었습니다. 또한 `Protocol`을 사용해서 사용자가 사용할 수 있는 함수들을 `Extension`을 활용해 작성해봤습니다.
- `Protocol`과 `Extension`을 활용할 때 이런 식으로 사용하는게 맞는 방법일지! 라자냐의 의견이 궁금합니다~

---

## [해결이 되지 않은 점 && 조언이 필요한 점]
### ✏️ FruitStore 타입
#### FruitStore 요구사항
- `각 과일의 수량 n개를 변경하는 기능이 있습니다.` 라는 요구사항이 있는데, 혹시 "+","-"에 따라 1개씩 증감하는 것 외에도 1개 이상의 수량을 변경해야 하는 함수가 필요할까요? 
- FruitStore 타입의 `updateFruitStore` 함수 내에서 User가 입력하는 값이 "+", "-" 경우일 것이라고만 생각해서 로직을 구현하게 되었는데, String 타입으로 받을경우 그 외에 값도 받을 수 있긴 한 것이어서, 더 세분화된 코드 구현이 필요할지 궁금합니다. 

### ✏️ Error 표현 && 어디서 구현할지
- User가 선택한 쥬스 필요한 과일수량이 부족한 경우
- User가 과일재고가 0인 상황에서 "-"버튼을 누르는 경우
현재까지는 위와 같은 경우의 에러가 발생한다고 생각하였고, 해당 문구를 출력해주는 정도로 구현하였습니다.
추후 Error 표현을 따로 구현해야 한다면, 어떻게 어디서 구현해야 할지 고민이 됩니다..!!

2022-09-01 06:13 UTC, wonhee009 requested changes
step1 수고하셨습니다 🎉 
코멘트 남겨두었으니 확인 부탁드려요 🙏 

FruitStore 요구사항
1. 네 저는 기획서를 그렇게 이해했습니다. 스펙이 헷갈리거나 명확하지 않을때에는 기획자에게 문의하시면 좋습니다 :)
2. 해당 사항은 코멘트로 남겼습니다.

Error 표현 && 어디서 구현할지
1. 해당 사항은 코멘트로 남겼습니다.
2. 보통은 enum을 사용해서 error 타입을 정의하긴 합니다. [공식문서](https://developer.apple.com/documentation/swift/error) 확인해보시면 좋을거 같습니다 :)

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    func updateFruitStock(fruit: Fruit, plusOrMinus: String) {
`plusOrMinus`로 파라미터명을 정한 이유가 있을까요? 또한, String 타입으로 지정한 이유도 궁금합니다.
`updateFruitStock()`을 호출할 때마다 "+", "-"를 입력해주는게 번거롭고 휴먼 에러를 유발할 수 있지 않을까요?
과일 종류들 처럼 `add`, `decrease`같은 타입을 갖는 enum을 이용하면 어떨까요?
이렇게 사용한다면 `updateFruitStock()`을 호출할때 자동 완성 사용 가능 및 잘못 입력된 경우 컴파일 단계에서 확인할 수 있을거 같습니다 :)

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    }
이 메서드는 언제 사용하는건가요?
`updateFruitStock()`만으로도 대응 가능하지 않나요?

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +              fruitStock >= juiceRecipe.1
이후 레시피에서 과일명, 갯수 뿐만 아니라 다른 카테고리가 추가된다면 (예를 들어 얼음의 양이라던지....?) 비교할때 juiceRecipe.2 이렇게 사용해야할거 같습니다. 이후 더 많은 카테고리가 추가된다면 확인이 어려울거 같은데요. 어떻게 생각하실까요?-?

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/Juice.swift
> +    }
이후 딸기바나나망고 주스 타입이 추가된다면
```swift
struct Recipe {
   let first: ...
   let second: ...?
   let third: ...?
}
```
이렇게 될거 같습니다.
레시피가 추가될때마다 struct의 프로퍼티가 추가되는 방식이 아닌 다른 방식은 어떨까요?

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/JuiceRecipe.swift
> +}
Model 폴더에 Juice 파일과 동일한 코드 같은데요. 확인 부탁드립니다.

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +        }
재고가 충분하지 않을때 `fruitStore.isEnoughStock()` 메서드 내에서 "재고 부족으로 주스 제작에 실패했습니다."라고 알려주는데요.
해당 역할이 FruitStore보다는 JuiceMaker의 역할에 가깝지 않나 생각이 듭니다. 여러분들의 의견도 궁금합니다 😄

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +        }
```suggestion
        if let secondFruit = juice.recipe.second,
           fruitStore.isEnoughStock(juiceRecipe: secondFruit) {
              make(juice)
        }
```

2022-09-01 06:13 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        juiceMaker2.chooseJuice(juice: .pineappleJuice)
테스트용으로 추가하신걸까요?
`juiceMaker2`와 같은 네이밍은 지양해주세요 😢

2022-09-01 07:50 UTC, hyhy0429 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        juiceMaker2.chooseJuice(juice: .pineappleJuice)
앗 테스트용으로 적어보는 과정에서 잠깐 구현해보게되었는데, 미처 지우지 못했습니다! 유의하겠습니다. 🙂

2022-09-01 08:09 UTC, jonghancha commented on JuiceMaker/JuiceMaker/Model/JuiceRecipe.swift
> +}
아 네 폴더를 추가하는 과정에서 빠졌던 것 같습니다. 삭제했습니다!

2022-09-01 08:25 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    func updateFruitStock(fruit: Fruit, plusOrMinus: String) {
원래 String 타입으로 지정했던 이유는 ViewController에서 값이 +, -의 text로 넘어온다고 생각을 해서 String 타입으로 구현을 했었습니다! 생각해 보니 ViewController에서 메서드를 호출할 때 매개변수를 직접 정해주면 되어서 variation enum 파일을 생성해서 수정하였습니다!

2022-09-01 08:32 UTC, hyhy0429 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +        }
네! 저희도 재고부족문구 출력 위치를 JuiceMaker에서 알려주는 것이 맞는 것 같아 위치를 변경해주었습니다! 🙂

2022-09-01 09:52 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    }
`subtractFruitStock()` 함수는 주스를 만들 때 한 번에 과일 재고가 여러 개 차감되는 함수입니다!
또한 `updateFruitStock()` 을 사용하지 않은 이유는 `updateFruitStock()` 으로만 `FruitStock` 값을 수정할 수 있도록 제한 해둔 함수여서 `JuiceMaker`에서는 일부러 `FruitStock`에 `subtractFruitStock()` 함수를 만들어 사용하였습니다!

2022-09-01 09:55 UTC, jonghancha commented on JuiceMaker/JuiceMaker/Model/Juice/Juice.swift
> +    }
맞습니다. 저희도 이 부분에 대해서 고민을 많이 했는데요, 결론적으로 nested type의 Recipe 는 유지하고 연산프로퍼티의 타입을 [Recipe]로 바꿔주었습니다. 우선 프로퍼티마다 일일이 재고를 확인하고, 재고를 변경하는 작업이 반복된다고 느껴져서 이를 배열을 사용해 해결하고자 했습니다. 다음으로 배열 안에 tuple 형태로 (first, second, third) 처럼 할당할것인지, 아니면 [Recipe] 와 같이 배열 안에 구조체를 넣을지 고민했습니다. 

 고민한 결과, Recipe는 과일이름, 수량, (얼음의 양) 등의 속성을 가진 하나의 객체라고 판단했기에 tuple 보다는 struct의 형태를 선택했습니다.

2022-09-01 10:00 UTC, hyhy0429 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +              fruitStock >= juiceRecipe.1
이 부분은 밑에 애종의 답변과 연결되는 부분인데요, Recipe 구조체 안에 필요한 재료들을 프로퍼티로 지정해주고, Recipe 구조체가 담긴 배열을 사용하는 방법으로 구현하였습니다.
이 경우, 만약 추가 재료로 '얼음', '설탕' 등이 들어오게 된다면, 구조체 내부의 프로퍼티를 추가하여 문제를 해결 할 수 있을 것 같습니다! 🙂

2022-09-01 10:01 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +        }
저희도 고민을 했었는데요!
아래에 달아주신 문맥에서는 첫 번째 과일의 재고가 있어도 두 번째 과일의 재고가 없다면 make 함수가 실행되지 않는다고 판단해서 위에 문맥을 채택했었습니다. 하지만 지금은 사용했던 코드를 삭제하고 전반적으로 수정했습니다!
조언 감사해요 라자냐 :)

2022-09-01 10:06 UTC, zhilly11 commented
안녕하세요 라자냐! 디테일하고 정성스럽게 달아주신 코멘트 하나하나 잘 보았습니다 😀
저희가 고민했던 부분들에서 라자냐의 조언이 많은 도움이 된 것 같습니다 👍
저희가 수정한 부분들도 확인 부탁드리고 조언해 주실 부분 있으시면 코멘트 부탁드립니다 🔥

2022-09-02 01:39 UTC, wonhee009 requested changes

2022-09-02 01:39 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    }
> updateFruitStock() 을 사용하지 않은 이유는 updateFruitStock() 으로만 FruitStock 값을 안전하게 수정할 수 있도록 제한 해둔 함수

해당 코멘트가 이해가 되지 않는데요. `updateFruitStock()`, `subtractFruitStock()` 모두 FruitStock 값을 수정하고 있는데 "제한"했다고 볼 수 있을까요?

코드상으로 봤을때에는 `updateFruitStock()`은 무조건 1개의 value만을 더하거나 뺄 수 있고, `subtractFruitStock()`은 다수의 stock을 뺄 수 있는거로 이해했습니다.
하지만 두 메서드 모두 public하게 뚫려 있어 언제 `updateFruitStock()`을 호출해야하고 언제 `subtractFruitStock()`을 호출해야할지 사용처에서는 알 수 없을거 같습니다. 
또한, 
```swift 
updateFruitStock(fruit: .kiwi, variation: .minus)
subtractFruitStock(fuit: .kiwi, amount: 1)
```
위의 코드가 기능성 다른 점이 없기도 하고요.
이런 경우 어느 곳에서는 `updateFruitStock()`을 통해 1개의 stock을 빼고, 어느 곳에서는 `subtractFruitStock()`을 통해 1개의 stock을 빼는 경우가 생길텐데요.
여러분이 생각한 코드의 의도와 맡지 않는 경우도 생길거 같습니다.
또한, 현재 코드로는 "각 과일의 수량 n개를 변경하는 기능이 있습니다."의 스펙에 완벽하게 대응하지 못할거 같습니다.
(가령, 키위 10개 추가 이런 경우요)

2022-09-02 02:57 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Model/Fruit/FruitStore.swift
> +    }
> 해당 코멘트가 이해가 되지 않는데요. `updateFruitStock()`, `subtractFruitStock()` 모두 FruitStock 값을 수정하고 있는데 "제한"했다고 볼 수 있을까요?

-> 오타가 있었습니다! `updateFruitStock()`, `subtractFruitStock()` 모두 `updateStock()`이라는 함수를 통해서만 재고 수정을 할 수 있도록 구현 하는게 저희 생각이었습니다. 따라서 1. 재고 변경 화면에서 재고를 1개씩 증감하는 함수, 2. 주스를 만들 때 재고를 원하는 수량만큼 한 번에 차감하는 함수 이렇게 두 가지로 기능 분리를 하려는 목적으로 작성했었습니다만,

라자냐의 코멘트를 보고 저희가 STEP-1의 기능 요구사항을 완벽하게 구현하지 못했던 것 같아 요구사항에 조금 더 중점을 두고자
 `subtractFruitStock()` 함수를 삭제하고 `updateFruitStock()` 함수 내에 "각 과일의 수량 n개를 변경하는 기능이 있습니다." 기능을 완벽히 수행하도록 수정했습니다!

2022-09-02 04:12 UTC, wonhee009 approved these changes
수고하셨습니다 🎉

2022-09-02 04:21 UTC, merged