쥬스메이커 [STEP 2] 메네, 드래곤
yagom-academy/ios-juice-maker pull request #261
Opened 2022-09-06 04:33 UTC by FlameYG

@SungPyo
안녕하세요! `내일날씨맑음`

STEP 2 완료하고 PR 드립니다.

`메네`한정 ➡️ 코드 스타터부터 콘솔에서만 작업하다가 이번 프로젝트에 UIKit을 처음 접해봐서 각각의 컴포넌트와 기능에 대해 잘 알지못하는 부분이 많네요 😂 앞으로 코코아터치 프레임워크와 친해지도록 해보겠습니다. 🔥

![](https://i.imgur.com/5wZo8WP.png)
STEP 2 시작하면서 메네 Xcode에서 에러가 발생하여 빌드가 되지 않는 문제가 있어서 처음 3번의 커밋은 드래곤이 혼자 하였습니다. 이후에는 함수단위로 번갈아가며 커밋하였습니다. 

- STEP 1에서 확인하지 못했던 `JuiceMaker.swift`상의 logical error를 발견하여 수정하였습니다.

- `JuiceMaker.swift`파일의 `makeJuice` 함수가 Bool 타입을 반환하여 `HomeViewController`에서 얼럿생성시 사용하도록 변경하였습니다.

- Alert을 처음으로 구현해보면서 [HIG - Alert](https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts)을 먼저 읽고 협업을 시작하였습니다.

- 처음에는 컴포넌트 기능구현에 촛점을 맞추고 작동확인 이후에 함수분리를 위해 고민해 보았습니다.

- `재고수정` 버튼 클릭 시 화면이동 방법에 대해 고민해보았습니다.

## 고민했던 점
- `JuiceMaker.swift`파일의 `makeJuice` 함수에서 쥬스 레시피가 2개일 때, 첫번째 과일이 재고가 있고 2번째 과일의 재고가 부족한 케이스에서 `for`문 안에서 첫번째 과일 재고가 차감되고 그 후에 "재고가 부족합니다"가 뜨는 문제가 있었습니다.
    - 해결방안: for문을 2번 돌려 첫번째 for문에서 이상 있을 경우 false로 반환, 이상 없을 경우 다시 for문을 통해 inventory에 값을 적용시켜주는 방식으로 변경하였습니다.
    
- 요구사항에서 "재고가 없는 경우 `예` 선택시 재고수정화면으로 이동 / `아니오` 선택시 얼럿닫기"로 기술되어 있었는데 HIG에서 "you can use “OK” for acceptance, avoiding “Yes” and “No.” Always use “Cancel” to title a button that cancels the alert’s action."라는 부분을 확인하였습니다. 
    - 현업이었다면 기획자와 상의하고 요구사항을 수정하는 것이 맞겠지만 HIG를 따르는 것으로 드래곤과 결정하고 `예` / `아니오` 대신 `취소` / `재고수정` 으로 변경하여 구현하였습니다.
    
- 얼럿버튼의 순서를 고민해 보았습니다.
    - HIG를 적용하여 기대하는 작업(`재고수정`)을 제일 뒤에 배치하고, `Cancel`은 제일 처음에 배치하도록 구현하였습니다.
> Place buttons where people expect. In general, place the button people are most likely to choose on the trailing side in a row of buttons or at the top in a stack of buttons. Always place the default button on the trailing side of a row or at the top of a stack. Cancel buttons are typically on the leading side of a row or at the bottom of a stack.
    
- `재고수정` 버튼 클릭 시 화면이동 방법에 대해 고민해보았습니다.
    - 처음 받았던 프로젝트 파일에는 네비게이션 콘트롤러가 2개로 구현되어 있었는데 쥬스주문 화면에서 `재고수정`이라는 새로운 context를 만드는 것이라 생각하고 `Modal`을 사용하였습니다.
    - 이동한 재고수정 view에서 쥬스주문화면으로 돌아올 방법이 없어서 `Close`버튼을 구현하였습니다.

- Alert를 함수화 시키는 과정에서 `makeJuice` 로 부터 반환되는 Bool값에 따라 if&else로 나뉘게 되는 것을 통합하여 함수화하였습니다.
    - if와 else에 들어갈 코드를 각각 `showSuccessAlert`, `showFailAlert`으로 나눠 함수화 하는게 더 좋은 방법일지에 대해 고민은 해보았지만 Alert이라는 큰 기능으로 묶어 if&else를 통합하여 `showAlert`으로 함수화 시켰습니다.

- 각각의 쥬스 주문 버튼이 똑같이 `showAlert`함수와 `checkInventory`함수만을 호출하고 있어서 버튼을 `@IBOutlet`으로 선언하여 주고 매개변수 sender로 받을 때 버튼의 tag값을 rawValue로 받아 makeJuice를 할 수 있도록 구현하면 하나의 함수로 구현 가능하지 않을까?라는 생각을 해 보았습니다.
    - `showAlert` 함수가 얼럿만을 노출하는 것이 아니라 쥬스를 만들고 결과를 얼럿으로 뿌리는 것까지의 책임을 지고 있는것 같아 함수를 분리해야 하는 것이 맞는지 고민해 보았습니다.
    - 버튼의 tag는 Int값만 받을 수 있어서 Juice타입에 name 프로퍼티를 만들어서 쥬스 이름을 옮기고 Int 타입의 rawValue를 설정하여 버튼의 tag에 매칭하는 등의 리팩토링을 해야 할 것 같아 조금 더 고민해보겠습니다. 😄

## 해결이 되지 않은 점
- STEP 2의 요구사항은 일단 만족은 시킨 것 같습니다.

## 조언을 얻고 싶은 부분

- 프로그램 작성 시, 접근제어를 어떻게 해야 할지 머리속에서 잘 그려지지 않는데, 기본적으로 `private`으로 설정하고 구현하면서 호출이 안되는 경우에 접근수준을 고민하는 것이 좋을지, 대략적으로라도 먼저 고민하고 설정하는 것이 좋을지 조언을 얻고 싶습니다.

- HIG에서 "Enable alternative ways to cancel an alert when it makes sense."라는 부분이 있었는데요, iOS에서는 홈 화면으로 이동하거나 연결된 키보드의 esc키를 누르는 방법으로도 취소할 수 있어야 한다고 기술되어 있는데 현 상태로는 얼럿을 띄워놓고 홈화면으로 이동했다가 돌아가도 여전히 얼럿이 보여지고 있습니다.
    - 해결 방법을 찾아보니 NotificationCenter에서 obserber를 등록하여 앱이 active 상태인지 확인해서 얼럿을 dismiss하는 함수를 호출하는 방법이 있다는 블로그를 보고 적용해보려고 했지만 작동하지 않았습니다.
    - 다른 방법으로는 `App deligate`에 함수를 등록해서 할 수있다고 하는 것 같은데 사실 두 방법 다 정확하게 알고 있는 방법이 아니라서 이 부분 관련해서 공부해야 할 키워드 같은 것을 `웨더`가 알려주실 수 있을까요?

2022-09-07 10:28 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
코드가 중복인것 같아 보이는데, 이 중복된 코드를 어떻게 하면 줄일 수 있을지 생각해 보신적이 있으실까요? 
그랬다면 생각이 궁금합니다.

2022-09-07 10:29 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
guard let 을 사용하지 않고 옵셔널 값 그대로 사용하면 어떤 문제가 발생하나요?

2022-09-07 10:30 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
이 Button들이 각각의 Action으로 되어있는데, 하나로 만들어 보신적이 있을까요?

2022-09-07 10:33 UTC, SungPyo commented
> @SungPyo 안녕하세요! `내일날씨맑음`
> 
> STEP 2 완료하고 PR 드립니다.
> 
> `메네`한정 ➡️ 코드 스타터부터 콘솔에서만 작업하다가 이번 프로젝트에 UIKit을 처음 접해봐서 각각의 컴포넌트와 기능에 대해 잘 알지못하는 부분이 많네요 😂 앞으로 코코아터치 프레임워크와 친해지도록 해보겠습니다. 🔥
> 
> ![](https://camo.githubusercontent.com/b4b9c763f7318dc5040f4839e2bf71217ddde46c82d26cd87f4ccaef5e13a568/68747470733a2f2f692e696d6775722e636f6d2f35775a6f3857502e706e67) STEP 2 시작하면서 메네 Xcode에서 에러가 발생하여 빌드가 되지 않는 문제가 있어서 처음 3번의 커밋은 드래곤이 혼자 하였습니다. 이후에는 함수단위로 번갈아가며 커밋하였습니다.
> 
> * STEP 1에서 확인하지 못했던 `JuiceMaker.swift`상의 logical error를 발견하여 수정하였습니다.
> * `JuiceMaker.swift`파일의 `makeJuice` 함수가 Bool 타입을 반환하여 `HomeViewController`에서 얼럿생성시 사용하도록 변경하였습니다.
> * Alert을 처음으로 구현해보면서 [HIG - Alert](https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts)을 먼저 읽고 협업을 시작하였습니다.
> * 처음에는 컴포넌트 기능구현에 촛점을 맞추고 작동확인 이후에 함수분리를 위해 고민해 보았습니다.
> * `재고수정` 버튼 클릭 시 화면이동 방법에 대해 고민해보았습니다.
> 
> ## 고민했던 점
> * `JuiceMaker.swift`파일의 `makeJuice` 함수에서 쥬스 레시피가 2개일 때, 첫번째 과일이 재고가 있고 2번째 과일의 재고가 부족한 케이스에서 `for`문 안에서 첫번째 과일 재고가 차감되고 그 후에 "재고가 부족합니다"가 뜨는 문제가 있었습니다.
>   
>   * 해결방안: for문을 2번 돌려 첫번째 for문에서 이상 있을 경우 false로 반환, 이상 없을 경우 다시 for문을 통해 inventory에 값을 적용시켜주는 방식으로 변경하였습니다.
> * 요구사항에서 "재고가 없는 경우 `예` 선택시 재고수정화면으로 이동 / `아니오` 선택시 얼럿닫기"로 기술되어 있었는데 HIG에서 "you can use “OK” for acceptance, avoiding “Yes” and “No.” Always use “Cancel” to title a button that cancels the alert’s action."라는 부분을 확인하였습니다.
>   
>   * 현업이었다면 기획자와 상의하고 요구사항을 수정하는 것이 맞겠지만 HIG를 따르는 것으로 드래곤과 결정하고 `예` / `아니오` 대신 `취소` / `재고수정` 으로 변경하여 구현하였습니다.
> * 얼럿버튼의 순서를 고민해 보았습니다.
>   
>   * HIG를 적용하여 기대하는 작업(`재고수정`)을 제일 뒤에 배치하고, `Cancel`은 제일 처음에 배치하도록 구현하였습니다.
> 
> > Place buttons where people expect. In general, place the button people are most likely to choose on the trailing side in a row of buttons or at the top in a stack of buttons. Always place the default button on the trailing side of a row or at the top of a stack. Cancel buttons are typically on the leading side of a row or at the bottom of a stack.
> 
> * `재고수정` 버튼 클릭 시 화면이동 방법에 대해 고민해보았습니다.
>   
>   * 처음 받았던 프로젝트 파일에는 네비게이션 콘트롤러가 2개로 구현되어 있었는데 쥬스주문 화면에서 `재고수정`이라는 새로운 context를 만드는 것이라 생각하고 `Modal`을 사용하였습니다.
>   * 이동한 재고수정 view에서 쥬스주문화면으로 돌아올 방법이 없어서 `Close`버튼을 구현하였습니다.
> * Alert를 함수화 시키는 과정에서 `makeJuice` 로 부터 반환되는 Bool값에 따라 if&else로 나뉘게 되는 것을 통합하여 함수화하였습니다.
>   
>   * if와 else에 들어갈 코드를 각각 `showSuccessAlert`, `showFailAlert`으로 나눠 함수화 하는게 더 좋은 방법일지에 대해 고민은 해보았지만 Alert이라는 큰 기능으로 묶어 if&else를 통합하여 `showAlert`으로 함수화 시켰습니다.
> * 각각의 쥬스 주문 버튼이 똑같이 `showAlert`함수와 `checkInventory`함수만을 호출하고 있어서 버튼을 `@IBOutlet`으로 선언하여 주고 매개변수 sender로 받을 때 버튼의 tag값을 rawValue로 받아 makeJuice를 할 수 있도록 구현하면 하나의 함수로 구현 가능하지 않을까?라는 생각을 해 보았습니다.
>   
>   * `showAlert` 함수가 얼럿만을 노출하는 것이 아니라 쥬스를 만들고 결과를 얼럿으로 뿌리는 것까지의 책임을 지고 있는것 같아 함수를 분리해야 하는 것이 맞는지 고민해 보았습니다.
>   * 버튼의 tag는 Int값만 받을 수 있어서 Juice타입에 name 프로퍼티를 만들어서 쥬스 이름을 옮기고 Int 타입의 rawValue를 설정하여 버튼의 tag에 매칭하는 등의 리팩토링을 해야 할 것 같아 조금 더 고민해보겠습니다. 😄
> 
> ## 해결이 되지 않은 점
> * STEP 2의 요구사항은 일단 만족은 시킨 것 같습니다.
> 
> ## 조언을 얻고 싶은 부분
> * 프로그램 작성 시, 접근제어를 어떻게 해야 할지 머리속에서 잘 그려지지 않는데, 기본적으로 `private`으로 설정하고 구현하면서 호출이 안되는 경우에 접근수준을 고민하는 것이 좋을지, 대략적으로라도 먼저 고민하고 설정하는 것이 좋을지 조언을 얻고 싶습니다.
ㄴ `이건 정답이 없고 개발자 자신만의 코드 스타일이라고 생각됩니다. 저는 그냥 무의식적으로 private 사용합니다.`
> * HIG에서 "Enable alternative ways to cancel an alert when it makes sense."라는 부분이 있었는데요, iOS에서는 홈 화면으로 이동하거나 연결된 키보드의 esc키를 누르는 방법으로도 취소할 수 있어야 한다고 기술되어 있는데 현 상태로는 얼럿을 띄워놓고 홈화면으로 이동했다가 돌아가도 여전히 얼럿이 보여지고 있습니다.
>   
>   * 해결 방법을 찾아보니 NotificationCenter에서 obserber를 등록하여 앱이 active 상태인지 확인해서 얼럿을 dismiss하는 함수를 호출하는 방법이 있다는 블로그를 보고 적용해보려고 했지만 작동하지 않았습니다.
>   * 다른 방법으로는 `App deligate`에 함수를 등록해서 할 수있다고 하는 것 같은데 사실 두 방법 다 정확하게 알고 있는 방법이 아니라서 이 부분 관련해서 공부해야 할 키워드 같은 것을 `웨더`가 알려주실 수 있을까요?
ㄴ `기획적인 부분인데,  홈 화면으로 들어갈때 Alert을 내리고 싶다면 BackgroudEven나 화면이 사라질때 dismiss 시키는 방법도 있을 것 같아요 :)

2022-09-07 10:34 UTC, SungPyo requested changes
코멘트 부분 수정 & 댓글 작성 후에 PR을 다시 요청해봐 주세요 :)

2022-09-07 12:05 UTC, JaeKimdev commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
PR 메세지에서도 말씀드렸듯이, if와 else에 들어갈 코드를 각각 `showSuccessAlert`, `showFailAlert`으로 나눠 각각 호출하자는 의견이 있었지만 Alert이라는 하나의 큰 기능으로 묶어 showAlert으로 함수화 시켰습니다.
이 부분 드래곤과 다시 상의해보겠습니다.

2022-09-07 12:09 UTC, JaeKimdev commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
이것도 PR 메세지에 기록했었는데요, 

- 각각의 쥬스 주문 버튼이 똑같이 showAlert함수와 checkInventory함수만을 호출하고 있어서 버튼을 @IBOutlet으로 선언하여 주고 매개변수 sender로 받을 때 버튼의 tag값을 rawValue로 받아 makeJuice를 할 수 있도록 구현하면 하나의 함수로 구현 가능하지 않을까?라는 생각을 해 보았습니다.

    - showAlert 함수가 얼럿만을 노출하는 것이 아니라 쥬스를 만들고 결과를 얼럿으로 뿌리는 것까지의 책임을 지고 있는것 같아 함수를 분리해야 하는 것이 맞는지 고민해 보았습니다.
   -  버튼의 tag는 Int값만 받을 수 있어서 Juice타입에 name 프로퍼티를 만들어서 쥬스 이름을 옮기고 Int 타입의 rawValue를 설정하여 버튼의 tag에 매칭하는 등의 방법을 생각해 보았는데 이 부분도 리팩토링 하면서 드래곤과 다시 상의해보겠습니다.

2022-09-07 16:59 UTC, JaeKimdev commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
바인딩해주지 않아도 아무런 문제 없는 것 확인했습니다.
리팩토링 시에 드래곤과 반영해보겠습니다.

2022-09-08 04:00 UTC, FlameYG commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
guard let 사용하지 않고 직접적으로 값을 넣어줘도 특이사항 없는 것으로 확인하였습니다
그러하여, 아래와 같이 코드 수정하였습니다

```swift
strawberryStockLabel.text = juiceMaker.checkStock(of: .strawBerry)
bananaStockLabel.text = juiceMaker.checkStock(of: .banana)
pineappleStockLabel.text = juiceMaker.checkStock(of: .pineApple)
kiwiStockLabel.text = juiceMaker.checkStock(of: .kiwi)
mangoStockLabel.text = juiceMaker.checkStock(of: .mango)
```

2022-09-08 04:03 UTC, FlameYG commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
Alert을 생성하는 기능은 동일하지만 title, message, handler가 경우에 따라 다르게 입력되기 때문에
showSuccessAlert / shoeFailAlert 함수로 Alert을 나눠 아래 코드와 같이 Refactor하였습니다

```swift
private func showSuccessAlert(of juice: Juice) {
        let alert = UIAlertController(title: "제조 완료",
                                      message: "\(juice.rawValue)쥬스 나왔습니다! 맛있게 드세요!",
                                      preferredStyle: .alert)
        let ok = UIAlertAction(title: "확인",
                               style: .default,
                               handler: nil)
        
        alert.addAction(ok)
        present(alert, animated: true, completion: nil)
}
    
private func showFailAlert() {
        let alert = UIAlertController(title: "재고 부족",
                                      message: "재료가 모자라요. 재고를 수정할까요?",
                                      preferredStyle: .alert)
        let ok = UIAlertAction(title: "재고수정",
                               style: .default,
                               handler: {_ in
            self.presentChangeInventoryViewController()
        })
        let cancel = UIAlertAction(title: "취소",
                                   style: .default,
                                   handler: nil)
        
        alert.addAction(cancel)
        alert.addAction(ok)
        present(alert, animated: true, completion: nil)
}
```

2022-09-08 04:04 UTC, JaeKimdev commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
첫번째 생각한 방법은 `Juice.swift` enum의 rawValue를 Int로 변경하고 각각의 쥬스 주문 버튼에 tag를 설정하여 Juice(rawValue: sender.tag)로 쥬스타입을 불러와서 적용하는 방법이었습니다.

```swift
@IBAction private func orderFruitJuice(_ sender: UIButton) {
        guard let juice = Juice(rawValue: sender.tag) else { return }
         
        if juiceMaker.makeJuice(of: juice) {
            showSuccessAlert(of: juice)
            checkInventory()
        } else {
            showFailAlert()
        }
    }
```
이렇게 적용할 경우 버튼의 tag를 Int 타입으로만 설정할 수 있어 각각의 버튼의 몇번의 tag를 갖는지 직관적으로 알 수 없다는 단점이 있었습니다. 매직넘버가 되어 추후에 새로운 쥬스가 추가되거나 유지보수가 어려울 것 같아 다른 방법을 생각해 보았습니다. (enum의 rawValue가 Int로 변경됨에 따라 추가적으로 name이라는 저장프로퍼티도 생성해 줘야해서 불편했습니다.)

```swift
enum Juice: Int {
    case strawBerry = 1
    case banana = 2
    case pineApple = 3
    case kiwi = 4
    case mango = 5
    case strawBerryBanana = 6
    case mangoKiwi = 7
    
    var name: String {
        switch self {
        case .strawBerry:
            return "딸기"
        case .banana:
            return "바나나"
        case .pineApple:
            return "파인애플"
        case .kiwi:
            return "키위"
        case .mango:
            return "망고"
        case .strawBerryBanana:
            return "딸바"
        case .mangoKiwi:
            return "망고키위"
        }
    }
}
```
다시 생각해 본 방법은 sender로 받은 버튼을 juice 타입으로 변환해주는 `takeJuiceMenu`함수를 생성하여 `Juice` 타입으로 반환하고 그 값을 makeJuice함수의 파라미터로 사용하였습니다.

```swift
@IBAction private func orderFruitJuice(_ sender: UIButton) {
       guard let juice = takeJuiceMenu(of: sender) else { return }
        
        if juiceMaker.makeJuice(of: juice) {
            showSuccessAlert(of: juice)
            checkInventory()
        } else {
            showFailAlert()
        }
    }

 func takeJuiceMenu(of sender: UIButton) -> Juice? {
        switch sender {
        case strawberryBananaJuiceOrderButton:
            return .strawBerryBanana
        case mangoKiwiJuiceOrderButton:
            return .mangoKiwi
        case strawberryJuiceOrderButton:
            return .strawBerry
        case bananaJuiceOrderButton:
            return .banana
        case pineappleJuiceOrderButton:
            return .pineApple
        case kiwiJuiceJuiceOrderButton:
            return .kiwi
        case mangoJuiceOrderButton:
            return .mango
        default:
            return nil
        }
    }
```

2022-09-08 04:06 UTC, JaeKimdev commented
`웨더` 코멘트 달아주신 부분 확인하고 수정해보았습니다.
확인 부탁드려요! 감사합니다.

2022-09-13 12:20 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
음.. 하나의 함수로 파라미터를 받아 처리하는걸 생각했었지만 다른 방법이더라도 고민했다는거에 대해서 의미를 둘게요 :)

2022-09-13 12:20 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
👏

2022-09-13 12:22 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/HomeViewController.swift
> +    }
음.. 버튼을 배열로 만들거나, tag같은걸 사용해서 IBAction을 하나로 만드는걸 생각했었어요. 
많은 고민 하셨네요 👏

2022-09-13 12:22 UTC, SungPyo approved these changes
원하는 코멘트와 대답은 아니었지만 고생 많으셨어요 :)
다음 스탭에서 봬요

2022-09-13 12:23 UTC, merged