쥬스 메이커 [STEP 2] inho, 토털이
yagom-academy/ios-juice-maker pull request #264
Opened 2022-09-06 06:00 UTC by inho-98

안녕하세요, @hansangjin96 
토털이, 인호 입니다.

쥬스 메이커 프로그램 step 2 PR입니다!

## 고민했던 부분
### 뷰 컨트롤러에게 private 값 전달 방법
- 지난 스텝에서 `FruitStore`타입의 `fruitStock`프로퍼티와 `JuiceMaker`의 `fruitStore`프로퍼티에 `private` 접근 제어를 추가해 주었습니다.
- 그런데 이번 스텝의 뷰컨트롤러에서 과일 재고량(`fruitStock`)이 필요해서 위 두 타입에 `fetchStock(of fruit: Fruit)`메서드를 구현하여 특정 과일의 재고량을 전달합니다.
### 뷰 컨트롤러에서 과일 재고량을 각 레이블 업데이트
- 앱을 실행시키거나 과일 주문 버튼을 눌러 과일 수량이 변경되었을 때, 각 수량이 레이블에 반영되어야 합니다. 처음에 구현할 때는 과일 하나하나에 값을 업데이트 하는 메서드를 작성했습니다.
```swift
func updateStrawberryStockLabel() {
    let strawberryStock = try juiceMaker.fetchStock(of: .strawberry)
    strawberryStockLabel.text = String(strawberryStock)
}

func updateBananaStockLabel() {
    let bananaStock = try juiceMaker.fetchStock(of: .banana)
    bananaStockLabel.text = String(bananaStock)
}
...
```
- 그런데 위 코드의 반복되는 부분을 어떻게 줄일 지 고민후에 하나의 메서드와 스위치 문을 이용하여 해결하였습니다.
```swift

func updateStockLabel(of fruit: Fruit) {
    guard let fruitStock = try? juiceMaker.fetchStock(of: fruit) else { return }
        
    switch fruit {
    case .strawberry:
        strawberryStockLabel.text = String(fruitStock)
    case .banana:
        bananaStockLabel.text = String(fruitStock)
    ...
    }
}
```
- 그리고 모든 과일의 레이블을 업데이트하는 메서드를 만들고, 그 안에 `Fruit`타입과 `allCases`,`forEach`를 이용하여 업데이트 합니다.
```swift
func updateAllStockLabels() {
    Fruit.allCases.forEach({ fruit in
        updateStockLabel(of: fruit)
    })
}
```
### 과일 주문 버튼 처리하는 방법
- 앱을 실행시켜 보면 총 7개의 과일 주문버튼이 있습니다. 이때 각 버튼에 대한 액션을 일일이 만들어야 할까 고민하다가 버튼의 tag값을 지정해서 하나의 메서드 내에서 사용 가능하도록 구현했습니다. 
```swift
@IBAction func touchUpOrderButton(_ sender: UIButton) {
    if let orderedJuice = JuiceMaker.Juice(rawValue: sender.tag) {
        do {
            try juiceMaker.produce(juice: orderedJuice)
            showOrderedAlert(juice: orderedJuice)
        } catch JuiceMakerError.outOfStock {
            showOrderFailedAlert()
        }
        ...
    }
}
```
- `JuiceMaker.Juice`타입의 rawValue와 버튼의 tag값을 비교해서 주문을 받습니다.

### 화면 전환 방법
- 두번째 뷰 컨트롤러인 `StockEditViewController`로 화면이 전환되는 두가지 경우가 있는데, 
"재고수정"버튼과 주문 실패 시 재고수정 알럿의 "예" 버튼을 누를때 화면이 전환되어야 합니다.
- 그래서 모달로 화면을 보여주는 `presentStockEditViewController`메서드를 만들고 각 버튼을 눌렀을 때 해당 매서드가 호출됩니다.
- 화면 전환을 모달로 구현한 이유는 재고 수정 버튼을 누르는 것이 정보의 흐름과 이어진다기 보다 사용자에게 새로운 화면을 보여준다고 생각했기 때문입니다.

## 조언을 얻고싶은 부분
1. 이번 프로젝트에서 `navigation bar`를 두 화면에 모두 만들어 주기 위해 `navigation controller`를 두 개 사용하였습니다. 초기 프로젝트 파일부터 포함되어 있던 내용이라, 수정하지 않고 그대로 진행하였는데, 과연 이 방법이 맞는지 의문이 듭니다.
현재 앱에는 두개의 뷰가 있어서 하나의 네비게이션 컨트롤러만 있어도 된다고 생각합니다!

    그리고 한편으로는 위에서 작성한 대로 화면이 전환될 때, 정보의 흐름보다는 모달에 가까워서 네비게이션 컨트롤러가 없어도 되지 않을까 싶은 고민도 있었습니다. 
 하비는 어떻게 생각하시나요?

2. 두개의 `Navigation Controller`를 이어주기 위해서, present를 활용하였는데요. 그 과정에서 `StockEditViewController`가 아닌 두번째`Navigation Controller`를 `presentStockEditViewController()` 함수 내에서 연결해 주었습니다. navigation Bar를 유지해주기 위해서였는데, 이 방법이 맞는지 궁금합니다.

3. STEP3에서 `화면사이의 데이터 공유`가 핵심 경험으로 나와있습니다. 화면사이에 데이터를 전달하는 방법은 아주 많은데, 고민이 많습니다. 그 중 적절한 방법을 고르는 팁이 있을까요?

4. 컨트롤러를 작성하다 보면, 컨트롤러가 길어지는데 컨트롤러 속의 메서드들을 어떤 순서로 작성하는지 팁을 얻을 수 있을까요? 보기 좋은 코드로 만들고 싶은데 감이 잡히지 않아 여쭤봅니다!

2022-09-06 14:54 UTC, hansangjin96 requested changes
> 이번 프로젝트에서 navigation bar를 두 화면에 모두 만들어 주기 위해 navigation controller를 두 개 사용하였습니다. 초기 프로젝트 파일부터 포함되어 있던 내용이라, 수정하지 않고 그대로 진행하였는데, 과연 이 방법이 맞는지 의문이 듭니다.
> 현재 앱에는 두개의 뷰가 있어서 하나의 네비게이션 컨트롤러만 있어도 된다고 생각합니다!

> 
> 그리고 한편으로는 위에서 작성한 대로 화면이 전환될 때, 정보의 흐름보다는 모달에 가까워서 네비게이션 컨트롤러가 없어도 되지 않을까 싶은 고민도 있었습니다.
> 하비는 어떻게 생각하시나요?

1. 사실 뷰를 그리는건 개발자들마다 엄청 취향이 다르기 때문에 정답은 없는데요,
재고 추가 화면에서 어느 화면으로 push가 일어날 가능성이 있는 상황이라면 navigationContoller가 뷰컨마다 붙어있어도 이상하지는 않을거 같다고 생각해요 :)
만약 push가 절대 일어나지 않을거 같다고 판단 되신다면 `네비게이션 바 처럼 생긴 뷰`를 그려서 위에 올리는 방법도 생각해볼 수 있겠네요 ㅎㅎ
**추후에 기획이 어떻게 바뀔 수 있을까?** 를 고민해보시면 도움이 될 것 같습니다!

> 두개의 Navigation Controller를 이어주기 위해서, present를 활용하였는데요. 그 과정에서 StockEditViewController가 아닌 두번째Navigation Controller를 presentStockEditViewController() 함수 내에서 연결해 주었습니다. navigation Bar를 유지해주기 위해서였는데, 이 방법이 맞는지 궁금합니다.

2. 사실 저는 거의 코드베이스로만 2년 가까이 UI를 그려서 .. 
스토리보드를 많이 까먹은 상태에서 말씀드리자면
코드로 그릴때에는 `UINavigationController(rootViewController: 재고를_보여줄_뷰컨())`으로 초기화 한 뒤에 해당 네비를 present시키는데요, 
스토리보드 상의 sugar가 있는지는 모르겠지만 작성해주신 코드가 이상하게 보이진 않는거 같아요 👍 

> STEP3에서 화면사이의 데이터 공유가 핵심 경험으로 나와있습니다. 화면사이에 데이터를 전달하는 방법은 아주 많은데, 고민이 많습니다. 그 중 적절한 방법을 고르는 팁이 있을까요?

3. 화면 사이에 데이터를 전달하기 위해서 어떤 방법들을 찾아보셨는지, 그 방법들 중에 장점이 뭐고 단점이 뭔지 찾아보신 결과를 공유해주시면 답변드리기 더 좋을거 같습니다 : )

> 컨트롤러를 작성하다 보면, 컨트롤러가 길어지는데 컨트롤러 속의 메서드들을 어떤 순서로 작성하는지 팁을 얻을 수 있을까요? 보기 좋은 코드로 만들고 싶은데 감이 잡히지 않아 여쭤봅니다!

4. 보기 좋은 코드를 위해 고민하시는 모습 아주 좋습니다 :) 
사실 이 부분은 야곰 캠프 프로젝트를 계속 하게 되실 경우 자연스럽게 경험해나가실 거라고 생각되는데요,
결국엔 `뷰가 해야하는 역할은 뭘까?`, `뷰컨이 해야하는 역할은 뭘까?`,`그렇다면 뷰컨의 역할을 잘 설명하려면 어떤 순서로 코드가 작성되면 좋을까?` 까지 고민을 이어나가시면 좋을 거 같아요.
흔히 말하는 apple mvc의 한계와 mvvm 탄생 배경, 다른 아키텍쳐의 파생과정도 이에 해당하겠네요 :)

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    let juiceMaker: JuiceMaker = JuiceMaker()
접근 제어자는 고려해보셨을까요?

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateAllStockLabels() {
접근 제어자는 고려해보셨을까요?

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        if let orderedJuice = JuiceMaker.Juice(rawValue: sender.tag) {
버튼마다 각각 태그를 달아주셨는데요, 여기서 태그는 1, 2 등 리터럴한 숫자가 들어갈거에요.
그럼 만약 버튼이 15개가 된다면 12번 태그의 버튼이 어딨는지 찾기 힘들어질거 같아요 :)
혹시 버튼의 액션을 받을 수 있는 다른 방법들에 대해서는 고민해보신 부분이 있으실까요??

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func touchUpOrderButton(_ sender: UIButton) {
`touchUp`이라는 단어를 사용하셨는데 네이밍 관련해서 어떤 고민을 하셨는지 궁금합니다 👍

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func showOrderedAlert(juice: JuiceMaker.Juice) {
`주문된 경고를 보여주다`라고 해석되는데 혹시 네이밍 고민해보셨을까요?

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateAllStockLabels()
하나의 쥬스를 만들 때 마다 모든 재고를 업데이트 하는걸로 보이는데요,
딸바쥬스를 만든다면 딸기와 바나나의 재고외에 다른 과일의 재고가 업데이트 된다면 사이드 이펙트가 발생할 수도 있을 것 같아요!
어떻게 하면 해당 쥬스를 만든 재고들만 업데이트 할 수 있을지 고민해보시면 좋을 것 같습니다!

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
쥬스에 따라 얼럿 메시지가 분기처리 되는 부분은 좋습니다 :)
하지만 저는 개인적으로 이 부분은 뷰 컨트롤러의 역할보다는 `Juice`의 역할이라고 생각해요.
`Juice`가 computed property로 가지고 있을 경우 코드가 어떻게 바뀔지 한 번 생각해보시면 좋을거 같아요 👍

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func touchUpOrderButton(_ sender: UIButton) {
반복되는 로직을 최대한 줄이고자 하는 노력 아주 보기 좋습니다! 💯 💯

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        stockEditVC.modalPresentationStyle = .fullScreen
`modalPresentationStyle`을 `.fullScreen`으로 선택하신 이유가 궁금합니다 👍

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    enum Juice: Int {
위에 말씀드린 바와 마찬가지로 `Int`타입으로 쥬스를 만들 수 있다고 했을 때,
1로 바나나쥬스를 만들지, 키위쥬스를 만들지 헷갈릴거 같습니다 ㅎㅎ
고민한 부분이 보여서 멋있습니다 👍 👍

2022-09-06 14:54 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateStockLabel(of fruit: Fruit) {
접근 제어자는 고려해보셨을까요?

2022-09-06 14:54 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateAllStockLabels()
여러개의 비슷한 역할을 하는 label에 일괄적으로 값을 넣어주시 위해서 고민을 많이 하신 것 같아요 :)
하지만 **개인적인 생각** 으로는 버튼마다 하는 역할이 각각 다르고, 버튼마다 예외상황이 생길 수도 있을거 같아서 일괄적으로 처리하기 보다는 각각 초기화해주는게 더 확장성이 좋은거 같아요 ㅎㅎ
예를 들면 두가지 재료를 섞는 쥬스만 재고를 다르게 보여준다던가??
그래서 버튼이 여러개일 경우 코드가 더러워 보일 수 있긴 한데, extention이나 computed property 등을 활용하면 좀 더 깔끔하게 초기화할 수 있을거 같아요!

2022-09-08 01:45 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    let juiceMaker: JuiceMaker = JuiceMaker()
접근 제어자 추가했습니다!

2022-09-08 01:46 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateAllStockLabels() {
추가했습니다!

2022-09-08 01:46 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func updateStockLabel(of fruit: Fruit) {
추가했습니다!

2022-09-08 01:54 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func touchUpOrderButton(_ sender: UIButton) {
강의 들으면서 쓰인 이름을 참고해서 별생각없이 작성했었습니다🥲
`juiceOrderButtonPressed`라는 이름이 전달력이 더 좋은것 같아서 수정했습니다!

2022-09-08 02:03 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func showOrderedAlert(juice: JuiceMaker.Juice) {
`주문이 됐다는 경고를 보여주다`라는 의도로 작성했는데 의미가 명확하지 않은 것 같아서
`showOrderSucceedAlert`로 수정했습니다!

2022-09-08 02:28 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
말씀해주신 대로 해당 부분이 `Juice`의 역할인것 같습니다!ㅎㅎ
연산 프로퍼티로 가지고 있도록 수정했습니다!

2022-09-08 02:59 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateAllStockLabels()
말씀해주신 대로 쥬스가 주문될때마다 레이블 전부가 업데이트 되는건 문제가 될 수 있다고 생각했습니다!
그래서 주문 받은 쥬스 내의 프로퍼티를 이용해서 쥬스의 재료에 포함된 과일들의 레이블만 업데이트 되도록 수정했습니다!!
```swift
orderedJuice.recipe.ingredient.keys.forEach({ fruit in
    updateStockLabel(of: fruit)
})
```

2022-09-08 03:02 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        stockEditVC.modalPresentationStyle = .fullScreen
위 코드는 다른 뷰를 보여주는 방법을 찾다가 적용한 코드인데요,
`modalPresentationStyle`의 기본값이 `automatic`이고 `fullScreen`과 비교해서 가시적인 차이는 없었고
뷰컨트롤러의 라이프사이클이 달라진다는 정도까지만 이해됐습니다.

`modalPresentationStyle`이 기본값이 되어도 상관없다고 생각해서 위 코드는 삭제했습니다!

2022-09-08 07:38 UTC, tottalE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateAllStockLabels()
각각 초기화 할 수 있도록 작성해 주었습니다!

2022-09-08 07:40 UTC, tottalE commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        if let orderedJuice = JuiceMaker.Juice(rawValue: sender.tag) {
다른 방법들도 고민해 보았는데요. 그 결과 태그를 이용하는게 적절하다고 판단해서 지금은 그렇게 작성해두겠습니다!! 다음에 프로젝트할 때 말씀하신 부분 참고하겠습니다 :)

2022-09-08 07:57 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        if let orderedJuice = JuiceMaker.Juice(rawValue: sender.tag) {
버튼을 하나로 유지하기로 결정했습니다ㅎㅎ 말씀해주신 태그를 이용하는게 요소를 찾기 어렵다는 부분도 고민해 보았는데요, 
그래서 처음에 해결했던 방법은 버튼 타이틀과 `Juice`타입의 `rawValue`를 이용하는 것이었습니다. 

`딸바쥬스 주문`버튼을 sender로 받아서 타이틀을 `split`하여 쥬스의 `rawValue`와  비교하는 것이었는데요,
```swift
let juice = sender.titleLabel?.text?.split(separator: " ").first //"딸바쥬스 주문" 중 "딸바쥬스"
JuiceMaker.Juice(rawValue: juice) //rawValue와 비교하여 초기화
```
뷰 컨트롤러 내에서 `split`하여 값을 얻는 과정이 어색하고, 뷰의 텍스트 요소와 비교하는과정에서 예외 상황(오타)이 생길 수 있다고 느껴져서 tag를 이용!였습니다.
다만 아래 코멘트에 적어주신것처럼 `Juice`에 `Int`를 주는것 보다는 `String`을 주는게 더 자연스럽다고는 느껴지는데,
두 방법 간에 하비 의견도 궁금합니다..!🤔

2022-09-08 08:25 UTC, hansangjin96 requested changes
재고 업데이트 하는 부분 수정사항 확인해주시면 감사하겠습니다~!
수정하시느라 수고하셨구 추석 잘 보내세요 :)

2022-09-08 08:25 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
뷰컨의 이름도 고민해보시면 좋을거 같습니다 ㅎㅎ

2022-09-08 08:25 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateAllStockLabels()
음 수정사항에 해당 코드가 보이지 않는거 같아요!
뭔가 실수가 있으셨던걸까요?

2022-09-08 08:25 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        present(alert, animated: true)
어떤 재고가 얼만큼 부족한지도 보여줄 수 있으면 좋을거 같네요 : )

2022-09-09 06:56 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
두번째 뷰 컨트롤러 만들때 수정하려 했는데 간과했습니다..!
`JuiceMakerViewController`로 이름 변경했습니다~!

2022-09-09 06:57 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        updateAllStockLabels()
커밋한 내용이 푸쉬되지 않았었습니다..!!
수정했으니 다시 한번 확인 부탁드리겠습니다! 🙏

2022-09-09 07:40 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        present(alert, animated: true)
말씀해주신 내용이 구현되면 재밌겠다고 생각해서 반영해보려 했습니다!
어떤 음료의 재고가 부족한지 표시하는건 어렵지 않았는데,
**부족한 재고의 수량을 표현하는 과정**에서 문제가 있었습니다.

`FruitStore`타입의 `fruitStock`프로퍼티가 `private`이고 `dictionary`로 되어있어서
메서드를 이용하면서 옵셔널 바인딩, 에러 처리까지 추가해야합니다.
그리고 필요한 과일이 두개 이상일 때에는 어떤 과일이 몇개 부족한지 계산하는 과정이 있어서
코드가 복잡해지는 문제가 있었습니다. (do-catch문 안에 또 다른 do-catch문 호출)

그래서 현재는 부족한 음료의 종류만 표시되도록 구현하였습니다..!🥲

2022-09-09 08:24 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        if let orderedJuice = JuiceMaker.Juice(rawValue: sender.tag) {
rawValue를 이용해서 split하는 것은 tag보다 더 리터럴한 느낌이라 좋은 방법은 아닐거 같구요,
제 방법이 정답은 아니지만, 저라면 버튼마다 @IBAction 함수를 달아줄거 같네요 ㅎㅎ
고민하는 과정이 무의미 하지 않다고 생각해서 지금의 고민만으로도 좋은 경험이 되었을거라 생각됩니다 :)

2022-09-09 08:28 UTC, hansangjin96 approved these changes
두 분 모두 고민하시고 수정하시느라 고생하셨습니다~!
아무래도 처음 UIkit을 사용하시는거다보니 낯설 수 있을거 같은데,
다음 스탭, 다음 프로젝트로 가다보면 더 잘하실 것 같아요 :)

2022-09-09 08:28 UTC, hansangjin96 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
`"\(쥬스의 이름을 표현하는 프로퍼티) 나왔습니다! 맛있게 드세요!"`
`"\(쥬스의 이름을 표현하는 프로퍼티) 재료가 모자라요. 재고를 수정할까요?"`
와 같이 중복을 줄여줄 수 있을거 같네요~

2022-09-09 08:30 UTC, merged