쥬스 메이커 [STEP 2] 써니쿠키, 써머캣
yagom-academy/ios-juice-maker pull request #266
Opened 2022-09-06 11:14 UTC by sunny-maeng

@SungPyo
웨더 안녕하세요! 
STEP2 PR드립니다!
조금이라도 "왜 이렇게 썼지?" 라는 생각이 드시는 부분이 있다면 코멘트로 남겨주세요!
질책도 환영합니다 🙇🏻‍♀️🥊 

---

## 1. 프로젝트 구성

사용자가 쥬스를 주문하는 버튼을 누르면, `ViewController`의 `orderJuice` 메서드에서 `makeJuice`를 호출합니다. `makeJuice`가 반환한 결과값이 `.success`일 경우 성공 alert을 화면에 표시하고, `.failure`일 경우 오류 메시지를 출력합니다.
  - 이 과정에서 기존에 `JuiceMaker`에 구현한 `makeJuice`의 반환 타입을 `Void`에서 `Result<String, Error>`로 변경하고, `JuiceMakerError`의 `errorDescription`을 제조 실패 시 alert에 출력할 메시지로 변경하였습니다. `Result<String, Error>`로 변경한 이유는 `.success`에서 전달한 문자열을 그대로 성공 alert의 `message`로 전달해 사용하고, `.falure`일 경우 전달받은 `error`의 `errorDescription`을 실패 alert의 `message`로 전달해 사용하기 위해서 입니다.

```swift
func makeJuice(_ juice: Juice, total: Int) -> Result<String, Error> {
    do {
        try checkFruitStore(for: juice, total: total)
        useFruit(juice, total: total)
        return .success("\(juice.juiceName) 나왔습니다! 맛있게 드세요!")
    } catch let error as JuiceMakerError {
        return .failure(error)
    } catch {
        return .failure(error)
    }
}
```

```swift
extension JuiceMakerError {
    var errorDescription: String {
        switch self {
        case .stockShortage:
            return "재료가 모자라요. 재고를 수정할까요?"
        }
    }
}
```
쥬스를 성공적으로 제조한 경우, `viewDidLoad()` 메서드를 호출해 화면에 보이는 과일의 잔여 재고 수량을 갱신합니다. 쥬스 제조에 실패한 경우에는 갱신하지 않습니다.
```swift=
switch result {
    case .success(let message):
        showSuccessAlert(message: message)
        viewDidLoad()
    case .failure(let error):
        guard let juiceMakerError = error as? JuiceMakerError else {
            return showFailureAlert(message: error.localizedDescription)
        }
            
        showFailureAlert(message: juiceMakerError.errorDescription)
}
```

---

## 2. 실행 예시
<img width = 500, src = "https://i.imgur.com/Dn6hyiB.gif" >

사용자가 쥬스 주문 버튼을 탭 하면
- **쥬스 레시피별 과일 재고 있을 때** : 
제작 완료 alert을 띄운 후 사용량 만큼 과일의 재고 감소를 반영합니다.
- **쥬스 레시피별 과일 재고 부족할 때** : 
재료 부족 alert을 띄운 후 재고수정을 원하는지 물어봅니다. `아니오` 버튼을 탭하면 alert이 닫히고, `예` 버튼을 탭하면 재고수정 뷰로 이동합니다. 

<img width = 500, src = "https://i.imgur.com/yihXfid.gif" >

사용자가 재고수정 버튼을 탭하면 재고수정 뷰로 이동합니다.

---

## 3. 고민한 부분

### 3-1 `재고수정` 버튼을 통해 `재고 추가` 화면으로 이동할 때, 내비게이션 방식과 모달 방식 중 어느 것을 쓸 것인가?

`내비게이션 방식`은 현재 화면의 연장선상으로 세부사항을 열어보거나 다음 step으로 넘어갈 때 사용합니다.
`모달 방식`은 지금 화면에서 조금 벗어나 잠시 다른 일을 처리하거나, 연장선을 벗어나 새로운 갈래로 나갈 때 사용합니다.

쥬스를 주문하는 현재 화면에서 재고를 변경해주는 화면으로 이동할 때는 쥬스 주문과는 별개로 잠시 연장선상을 벗어나 다른 일을 처리한 후 돌아온다고 생각하여 화면 전환 방식으로 모달 방식을 채택했습니다. 

### 3-2 과일 재고의 개수를 메인 `ViewController`와 `FruitStockViewController`간에 공유하게 하는 방법

검색을 통해 프로퍼티로 직접 전달하는 방법, delegation을 이용하는 방법 등 다양한 방법이 있다는 것을 알게 되었지만, 활동학습 시간에 배운 Singleton Pattern을 이용하기로 했습니다.

그 이유는 이 프로젝트가 매우 단순한 구조의 프로젝트이기 때문이기도 하고, 현재 구조체로 정의되어 있는 `JuiceMaker`가 프로퍼티로 클래스 `FruitStore`의 인스턴스를 `private`으로 가지고 있었기 때문에, 클래스로 되어있는 `FruitStore`에 싱글톤 패턴을 적용하는 편이 낫다고 생각했습니다.
`FruitStore`에 싱글톤 패턴을 적용할 경우, `JuiceMaker`, `ViewController`, `FruitStockViewController`에서 모두 하나의 인스턴스에 접근이 가능하기 때문입니다.
(현재는 step2 요구사항에 `FruitStockViewController`에 재고 수량을 반영하는 부분이 기재되어 있지 않아 그 부분은 구현하지 않았습니다.)

### 3-3 `UILabel`과 `UIButton`을 다룰 때, 코드에서 중복되는 부분을 줄일 방법

처음에는 각 `label`과 `button`을 일일이 직접 매핑하거나 `switch case`로 구분하도록 작성했었습
니다. 하지만 두 가지 경우 모두 각 케이스마다 중복되는 코드가 많아 중복되는 코드를 줄일 방법을 고민(구글링)해 보았고, 아래의 글을 참고해 개선해 보았습니다.
(참고: https://stackoverflow.com/questions/52548196/shorten-long-switch-case)

`label`의 경우, `.text = String(FruitStore.sharedFruitStore.fetchStockOf(.strawberry))`부분이 `.strawberry`라는 과일 값만 빼고는 모두 똑같이 중복되고 있습니다.

```swift
// 최초에 작성한 코드 - label을 일일이 매핑
strawberryStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.strawberry))
        bananaStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.banana))
        pineappleStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.pineapple))
        kiwiStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.kiwi))
        mangoStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.mango))
```

아래와 같이 `[UILabel: Fruit]` 딕셔너리를 생성하고, `for-in`을 사용해 딕셔너리를 순회하면서 값을 `label`에 넣어주도록 수정해 보았습니다.

```swift
// 최종 수정한 코드
let fruitLabel: [UILabel: Fruit] = [
    strawberryStockLabel: .strawberry,
    bananaStockLabel: .banana,
    pineappleStockLabel: .pineapple,
    kiwiStockLabel: .kiwi,
    mangoStockLabel: .mango,
    ]
        
    for (label, fruit) in fruitLabel {
    label.text = String(FruitStore.sharedFruitStore.fetchStockOf(fruit))
    }
```

`button`을 식별해서 `switch case`를 이용해 `juiceMaker.makeJuice(Juice, total: Int)`에 넣어주는 부분 역시 `makeJuice` 메서드를 호출해서 `result`에 넣어주는 부분이 반복되고 있었습니다.

```swift
// 최초에 작성한 코드 - button을 switch case로 구분
 @IBAction func orderJuice(sender: UIButton) {
    switch sender {
        case strawberryBananaJuiceButton:
            result = juiceMaker.makeJuice(.strawberryBananaJuice, total: 1)
        case mangoKiwiJuiceButton:
            result = juiceMaker.makeJuice(.mangoKiwiJuice, total: 1)
        case strawberryJuiceButton:
            result = juiceMaker.makeJuice(.strawberryJuice, total: 1)
        case bananaJuiceButton:
            result = juiceMaker.makeJuice(.bananaJuice, total: 1)
        case pineappleJuiceButton:
            result = juiceMaker.makeJuice(.pineappleJuice, total: 1)
        case kiwiJuiceButton:
            result = juiceMaker.makeJuice(.kiwiJuice, total: 1)
        case mangoJuiceButton:
            result = juiceMaker.makeJuice(.mangoJuice, total: 1)
        default:
            return
        }
     ...
 }
```

이 부분도 아래와 같이 `[UIButton: Juice]` 딕셔너리를 생성하고, `juiceButton[sender]`의 값을 `juice`에 할당해 옵셔널 바인딩 해주니 `result`를 생성하는 `makeJuice()` 메서드를 한 번만 호출하도록 개선할 수 있었습니다.

```swift
 @IBAction func orderJuice(sender: UIButton) {
    let juiceButton: [UIButton: Juice] = [
        strawberryBananaJuiceButton: .strawberryBananaJuice,
        mangoKiwiJuiceButton: .mangoKiwiJuice,
        strawberryJuiceButton: .strawberryJuice,
        bananaJuiceButton: .bananaJuice,
        pineappleJuiceButton: .pineappleJuice,
        kiwiJuiceButton: .kiwiJuice,
        mangoJuiceButton: .mangoJuice,
        ]

    guard let juice = juiceButton[sender] else { return }

    let result = juiceMaker.makeJuice(juice, total: 1)
    ...
 }
```

---

## 4. 궁금한 점

### 4-1 ViewController의 함수에 접근제어를 설정

ViewController에 구현한 함수에도 접근제어를 설정해야 하는지 고민했습니다.

ViewController 파일에서 `showSuccessAlert(message:)`, `showFailureAlert(message:)`, `moveToFruitStockVC()` 와 같은 함수들과 화면과 연동되어있는 `@IBAction 함수`, `@IBOulet 프로퍼티` 도 `private`으로 처리를 해줘야 하는지 궁금합니다.

`private`으로 설정해도 시뮬레이션은 정상 작동됨을 확인했는데, 뷰 컨트롤러 내부의 요소들에 접근 제어를 설정하는 것이 불필요한 사항인지 필수사항인지 개념이 잡히지 않아 현재는 접근 제어를 설정하지 않고 PR드렸습니다..

### 4-2 화면 전환 방식 (함수가 구현되어있을 때 segue를 이용하는지)

화면을 전환하는 함수가 구현되어 있어도 segue를 이용하시는지 궁금합니다.

이번 step2에서는 모달 view로 넘어가는 경로가 두 개였습니다. 첫 번째는 `재고수정` 버튼을 눌렀을때이고 두 번째는 쥬스제조시 재고가 부족하다는 alert에서 `예`를 눌렀을 때입니다.

`예`를 눌렀을 경우를 위해 화면전환 함수를 코드로 구현했는데, 이럴 때 `재고수정` 버튼에도 같은 함수를 이용해 통일을 하는게 나을지 segue 방식을 사용해도 되는지 현업에서는 어떻게 하는지 궁금합니다.

2022-09-07 10:55 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
중복된 코드를 줄여볼 수 있을까요?

2022-09-07 10:56 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private init() {}
싱글톤 객체를 만들때 초기화 구문 앞에 private는 왜 붙이는지 알고 계시나요?

2022-09-07 11:17 UTC, SungPyo commented
> @SungPyo 웨더 안녕하세요! STEP2 PR드립니다! 조금이라도 "왜 이렇게 썼지?" 라는 생각이 드시는 부분이 있다면 코멘트로 남겨주세요! 질책도 환영합니다 🙇🏻‍♀️🥊
> 
> ## 1. 프로젝트 구성
> 사용자가 쥬스를 주문하는 버튼을 누르면, `ViewController`의 `orderJuice` 메서드에서 `makeJuice`를 호출합니다. `makeJuice`가 반환한 결과값이 `.success`일 경우 성공 alert을 화면에 표시하고, `.failure`일 경우 오류 메시지를 출력합니다.
> 
> * 이 과정에서 기존에 `JuiceMaker`에 구현한 `makeJuice`의 반환 타입을 `Void`에서 `Result<String, Error>`로 변경하고, `JuiceMakerError`의 `errorDescription`을 제조 실패 시 alert에 출력할 메시지로 변경하였습니다. `Result<String, Error>`로 변경한 이유는 `.success`에서 전달한 문자열을 그대로 성공 alert의 `message`로 전달해 사용하고, `.falure`일 경우 전달받은 `error`의 `errorDescription`을 실패 alert의 `message`로 전달해 사용하기 위해서 입니다.
> 
> ```swift
> func makeJuice(_ juice: Juice, total: Int) -> Result<String, Error> {
>     do {
>         try checkFruitStore(for: juice, total: total)
>         useFruit(juice, total: total)
>         return .success("\(juice.juiceName) 나왔습니다! 맛있게 드세요!")
>     } catch let error as JuiceMakerError {
>         return .failure(error)
>     } catch {
>         return .failure(error)
>     }
> }
> ```
> 
> ```swift
> extension JuiceMakerError {
>     var errorDescription: String {
>         switch self {
>         case .stockShortage:
>             return "재료가 모자라요. 재고를 수정할까요?"
>         }
>     }
> }
> ```
> 
> 쥬스를 성공적으로 제조한 경우, `viewDidLoad()` 메서드를 호출해 화면에 보이는 과일의 잔여 재고 수량을 갱신합니다. 쥬스 제조에 실패한 경우에는 갱신하지 않습니다.
> 
> ```
> switch result {
>     case .success(let message):
>         showSuccessAlert(message: message)
>         viewDidLoad()
>     case .failure(let error):
>         guard let juiceMakerError = error as? JuiceMakerError else {
>             return showFailureAlert(message: error.localizedDescription)
>         }
>             
>         showFailureAlert(message: juiceMakerError.errorDescription)
> }
> ```
> 
> ## 2. 실행 예시
> ![](https://camo.githubusercontent.com/644e8d46cb9e1a61b0b04ec0afa3ca8c83393e25414e5dbdcb1f65d1c4de66d0/68747470733a2f2f692e696d6775722e636f6d2f446e36687969422e676966) [ ![68747470733a2f2f692e696d6775722e636f6d2f446e36687969422e676966](https://camo.githubusercontent.com/644e8d46cb9e1a61b0b04ec0afa3ca8c83393e25414e5dbdcb1f65d1c4de66d0/68747470733a2f2f692e696d6775722e636f6d2f446e36687969422e676966) ](https://camo.githubusercontent.com/644e8d46cb9e1a61b0b04ec0afa3ca8c83393e25414e5dbdcb1f65d1c4de66d0/68747470733a2f2f692e696d6775722e636f6d2f446e36687969422e676966) [ ](https://camo.githubusercontent.com/644e8d46cb9e1a61b0b04ec0afa3ca8c83393e25414e5dbdcb1f65d1c4de66d0/68747470733a2f2f692e696d6775722e636f6d2f446e36687969422e676966)
> 
> 사용자가 쥬스 주문 버튼을 탭 하면
> 
> * **쥬스 레시피별 과일 재고 있을 때** :
>   제작 완료 alert을 띄운 후 사용량 만큼 과일의 재고 감소를 반영합니다.
> * **쥬스 레시피별 과일 재고 부족할 때** :
>   재료 부족 alert을 띄운 후 재고수정을 원하는지 물어봅니다. `아니오` 버튼을 탭하면 alert이 닫히고, `예` 버튼을 탭하면 재고수정 뷰로 이동합니다.
> 
> ![](https://camo.githubusercontent.com/4a852eb217c1a35e110ee08b5a6e329f3abeb48db8ea62e9da12239c33f37feb/68747470733a2f2f692e696d6775722e636f6d2f796968586669642e676966) [ ![68747470733a2f2f692e696d6775722e636f6d2f796968586669642e676966](https://camo.githubusercontent.com/4a852eb217c1a35e110ee08b5a6e329f3abeb48db8ea62e9da12239c33f37feb/68747470733a2f2f692e696d6775722e636f6d2f796968586669642e676966) ](https://camo.githubusercontent.com/4a852eb217c1a35e110ee08b5a6e329f3abeb48db8ea62e9da12239c33f37feb/68747470733a2f2f692e696d6775722e636f6d2f796968586669642e676966) [ ](https://camo.githubusercontent.com/4a852eb217c1a35e110ee08b5a6e329f3abeb48db8ea62e9da12239c33f37feb/68747470733a2f2f692e696d6775722e636f6d2f796968586669642e676966)
> 
> 사용자가 재고수정 버튼을 탭하면 재고수정 뷰로 이동합니다.
> 
> ## 3. 고민한 부분
> ### 3-1 `재고수정` 버튼을 통해 `재고 추가` 화면으로 이동할 때, 내비게이션 방식과 모달 방식 중 어느 것을 쓸 것인가?
> `내비게이션 방식`은 현재 화면의 연장선상으로 세부사항을 열어보거나 다음 step으로 넘어갈 때 사용합니다. `모달 방식`은 지금 화면에서 조금 벗어나 잠시 다른 일을 처리하거나, 연장선을 벗어나 새로운 갈래로 나갈 때 사용합니다.
> 
> 쥬스를 주문하는 현재 화면에서 재고를 변경해주는 화면으로 이동할 때는 쥬스 주문과는 별개로 잠시 연장선상을 벗어나 다른 일을 처리한 후 돌아온다고 생각하여 화면 전환 방식으로 모달 방식을 채택했습니다.
> 
> ### 3-2 과일 재고의 개수를 메인 `ViewController`와 `FruitStockViewController`간에 공유하게 하는 방법
> 검색을 통해 프로퍼티로 직접 전달하는 방법, delegation을 이용하는 방법 등 다양한 방법이 있다는 것을 알게 되었지만, 활동학습 시간에 배운 Singleton Pattern을 이용하기로 했습니다.
> 
> 그 이유는 이 프로젝트가 매우 단순한 구조의 프로젝트이기 때문이기도 하고, 현재 구조체로 정의되어 있는 `JuiceMaker`가 프로퍼티로 클래스 `FruitStore`의 인스턴스를 `private`으로 가지고 있었기 때문에, 클래스로 되어있는 `FruitStore`에 싱글톤 패턴을 적용하는 편이 낫다고 생각했습니다. `FruitStore`에 싱글톤 패턴을 적용할 경우, `JuiceMaker`, `ViewController`, `FruitStockViewController`에서 모두 하나의 인스턴스에 접근이 가능하기 때문입니다. (현재는 step2 요구사항에 `FruitStockViewController`에 재고 수량을 반영하는 부분이 기재되어 있지 않아 그 부분은 구현하지 않았습니다.)
> 
> ### 3-3 `UILabel`과 `UIButton`을 다룰 때, 코드에서 중복되는 부분을 줄일 방법
> 처음에는 각 `label`과 `button`을 일일이 직접 매핑하거나 `switch case`로 구분하도록 작성했었습 니다. 하지만 두 가지 경우 모두 각 케이스마다 중복되는 코드가 많아 중복되는 코드를 줄일 방법을 고민(구글링)해 보았고, 아래의 글을 참고해 개선해 보았습니다. (참고: https://stackoverflow.com/questions/52548196/shorten-long-switch-case)
> 
> `label`의 경우, `.text = String(FruitStore.sharedFruitStore.fetchStockOf(.strawberry))`부분이 `.strawberry`라는 과일 값만 빼고는 모두 똑같이 중복되고 있습니다.
> 
> ```swift
> // 최초에 작성한 코드 - label을 일일이 매핑
> strawberryStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.strawberry))
>         bananaStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.banana))
>         pineappleStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.pineapple))
>         kiwiStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.kiwi))
>         mangoStockLabel.text = String(FruitStore.sharedFruitStore.fetchStockOf(.mango))
> ```
> 
> 아래와 같이 `[UILabel: Fruit]` 딕셔너리를 생성하고, `for-in`을 사용해 딕셔너리를 순회하면서 값을 `label`에 넣어주도록 수정해 보았습니다.
> 
> ```swift
> // 최종 수정한 코드
> let fruitLabel: [UILabel: Fruit] = [
>     strawberryStockLabel: .strawberry,
>     bananaStockLabel: .banana,
>     pineappleStockLabel: .pineapple,
>     kiwiStockLabel: .kiwi,
>     mangoStockLabel: .mango,
>     ]
>         
>     for (label, fruit) in fruitLabel {
>     label.text = String(FruitStore.sharedFruitStore.fetchStockOf(fruit))
>     }
> ```
> 
> `button`을 식별해서 `switch case`를 이용해 `juiceMaker.makeJuice(Juice, total: Int)`에 넣어주는 부분 역시 `makeJuice` 메서드를 호출해서 `result`에 넣어주는 부분이 반복되고 있었습니다.
> 
> ```swift
> // 최초에 작성한 코드 - button을 switch case로 구분
>  @IBAction func orderJuice(sender: UIButton) {
>     switch sender {
>         case strawberryBananaJuiceButton:
>             result = juiceMaker.makeJuice(.strawberryBananaJuice, total: 1)
>         case mangoKiwiJuiceButton:
>             result = juiceMaker.makeJuice(.mangoKiwiJuice, total: 1)
>         case strawberryJuiceButton:
>             result = juiceMaker.makeJuice(.strawberryJuice, total: 1)
>         case bananaJuiceButton:
>             result = juiceMaker.makeJuice(.bananaJuice, total: 1)
>         case pineappleJuiceButton:
>             result = juiceMaker.makeJuice(.pineappleJuice, total: 1)
>         case kiwiJuiceButton:
>             result = juiceMaker.makeJuice(.kiwiJuice, total: 1)
>         case mangoJuiceButton:
>             result = juiceMaker.makeJuice(.mangoJuice, total: 1)
>         default:
>             return
>         }
>      ...
>  }
> ```
> 
> 이 부분도 아래와 같이 `[UIButton: Juice]` 딕셔너리를 생성하고, `juiceButton[sender]`의 값을 `juice`에 할당해 옵셔널 바인딩 해주니 `result`를 생성하는 `makeJuice()` 메서드를 한 번만 호출하도록 개선할 수 있었습니다.
> 
> ```swift
>  @IBAction func orderJuice(sender: UIButton) {
>     let juiceButton: [UIButton: Juice] = [
>         strawberryBananaJuiceButton: .strawberryBananaJuice,
>         mangoKiwiJuiceButton: .mangoKiwiJuice,
>         strawberryJuiceButton: .strawberryJuice,
>         bananaJuiceButton: .bananaJuice,
>         pineappleJuiceButton: .pineappleJuice,
>         kiwiJuiceButton: .kiwiJuice,
>         mangoJuiceButton: .mangoJuice,
>         ]
> 
>     guard let juice = juiceButton[sender] else { return }
> 
>     let result = juiceMaker.makeJuice(juice, total: 1)
>     ...
>  }
> ```
> 
> ## 4. 궁금한 점
> ### 4-1 ViewController의 함수에 접근제어를 설정
> ViewController에 구현한 함수에도 접근제어를 설정해야 하는지 고민했습니다.
> 
> ViewController 파일에서 `showSuccessAlert(message:)`, `showFailureAlert(message:)`, `moveToFruitStockVC()` 와 같은 함수들과 화면과 연동되어있는 `@IBAction 함수`, ` [...]

2022-09-07 11:18 UTC, SungPyo requested changes
코멘트 답변 or 코드 수정 후에 PR을 다시 요청해봐 주세요 :)

2022-09-08 02:55 UTC, sunny-maeng commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private init() {}
해당 class 외부에서 인스턴스를 생성하지 못하게 하기 위해서 private를 쓰는 것으로 알고있습니다.

2022-09-08 03:48 UTC, ttokin commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
alert를 사용자에게 보여주는 부분은 하나의 `showAlert` 메서드로 합치고, 대신 쥬스 주문 결과에 따른 alert를 생성해주는 `createAlert` 메서드를 새로 작성했습니다.

2022-09-08 03:57 UTC, sunny-maeng commented
@SungPyo 
웨더 안녕하세요!
커멘트 리댓 외 수정내용 및 궁금한점 작성했습니다!

---

이전 PR에서 쥬스제작 성공 후 stockLabel을 업데이트 해주기 위해서 viewDidLoad() 를 다시 호출하는 방식을 취했었습니다.
viewDidLoad() 함수의 역할에 맞지 않게 사용되었다고 생각했고, 모든 과일에 대해 업데이트를 하는 게 불필요하다 생각했습니다.
그래서 사용한 과일만 업데이트 해주는 updateFruitStockLabelUsedFor(_ juice: Juice) 메서드를 구현했습니다.

---

**궁금한점**

 updateFruitStockLabelUsedFor(_ juice: Juice) 메서드의 네이밍에서 매개변수로 받는 Juice와 연결시키기 위해 'UsedFor' 를 붙여줬습니다.  'UsedFor' 가 부자연스럽게 느껴지는데 혹시 리뷰어님이 보시기엔 어떤지 궁금합니다.

2022-09-13 12:24 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private init() {}
👏

2022-09-13 12:27 UTC, SungPyo commented
> @SungPyo 웨더 안녕하세요! 커멘트 리댓 외 수정내용 및 궁금한점 작성했습니다!
> 
> 이전 PR에서 쥬스제작 성공 후 stockLabel을 업데이트 해주기 위해서 viewDidLoad() 를 다시 호출하는 방식을 취했었습니다. viewDidLoad() 함수의 역할에 맞지 않게 사용되었다고 생각했고, 모든 과일에 대해 업데이트를 하는 게 불필요하다 생각했습니다. 그래서 사용한 과일만 업데이트 해주는 updateFruitStockLabelUsedFor(_ juice: Juice) 메서드를 구현했습니다.
> 
> **궁금한점**
> 
> updateFruitStockLabelUsedFor(_ juice: Juice) 메서드의 네이밍에서 매개변수로 받는 Juice와 연결시키기 위해 'UsedFor' 를 붙여줬습니다. 'UsedFor' 가 부자연스럽게 느껴지는데 혹시 리뷰어님이 보시기엔 어떤지 궁금합니다.

ㄴ`보는데 불편함은 없지만 굳이 붙이지 않아도 상관 없다고 느껴지네요 :)`

2022-09-13 12:28 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
👏

2022-09-13 12:28 UTC, SungPyo approved these changes
고생하셨습니다 다음 스탭에서 봬요

2022-09-13 12:28 UTC, merged