쥬스 메이커 [STEP 2] 애종, zhilly, bella
yagom-academy/ios-juice-maker pull request #267
Opened 2022-09-06 12:06 UTC by zhilly11

# 쥬스 메이커 [STEP 2] p.r

@wonhee009
안녕하세요 라자냐! 
쥬스메이커 프로젝트 [STEP 2] 리뷰 잘 부탁드립니다! 🙂 🙇🏻‍♀️🙇🏻‍♂️🙇🏻

---
## [고민되었던 점]
### 과일 재고 초기화

### Singleton 과 NotificationCenter 활용에 대한 고민
#### Singleton
- `fruitStore`에 `singleton`을 적용하게 될 경우에는, `singleton` 특성상, 참조하고자 하는 프로퍼티(`fruitStock`)가 오픈되어 있기에 다양한 곳에서 접근이 가능게 된다는 생각이 들었습니다. 
하지만 저희는 `fruitStock`에 접근제어를 설정하여, `fruitStore` 안에서만 수정이 가능하게 하고 싶었기에 저희의 의도와 맞지 않다고 생각하였습니다.
또한 model 단위안에 있는 class이기에, 다른 곳에서 접근이 가능할 경우에 의존성이 생겨 `singleton` 패턴의 단점인 `'개방-폐쇄 원칙 위배'`의 경우에 해당될 것이라고 생각했습니다. 

#### NotificationCenter
- `NotificationCenter`를 이용하여 알람을 `fruitStock` 조건에 따라 (성공/실패)로 나누었고, `viewDidLoader`에서 `addObserver` 를 통해 해당 알람을 받아 사용하고 싶었습니다. 그러다가, 알림에 따른 `observer`도 2개로 나누어져야 하는게 아닌가에 대한 고민이 있었습니다.
또한 저희가 구현한 조건이 현재로서는 간단하기에, `NotificationCenter`을 활용해 알림을 통한 처리를 해주어야 하는지에 대한 고민이 되었습니다.
- 컨트롤러에서 쥬스 만들기를 요청하고 모델에서 쥬스 제조를 위한 재고가 충분한지 확인이 이루어지는데, 그 결과를 어떻게 하면 다시 컨트롤러에 알려 `alert` 혹은 재고의 변화를 반영할지 고민했습니다. `userInfo`에 재고의 충분여부와 쥬스의 이름을 담아 post해주었고 컨트롤러에서 그 결과에 따라 alert를 띄우고 view의 재고현황을 update하도록 구현했습니다. 

### ViewController에서 JuiceMaker 할당

```swift
// 1번 방법 : viewDidLoad 밖에서 할당
class FruitJuiceStoreViewController: UIViewController {
    var juiceMaker: JuiceMakerProtocol = JuiceMaker()
    
    override func viewDidLoad() {
        
    }
}

// 2번 방법 : viewDidLoad 안에서 할당
class FruitJuiceStoreViewController: UIViewController {
    var juiceMaker: JuiceMakerProtocol?
    
    override func viewDidLoad() {
        juiceMaker = JuiceMaker()
    }
}

```
- 먼저 ViewController 안에서 할당할 수 있는 방법은 두 가지라고 생각했습니다. 
- viewDidLoad 밖에서 할당할 경우 -> ViewController가 할당될 때 juiceMaker가 할당 됨
- viewDidLoad 안에서 할당할 경우 -> ViewController 생애 한 번만 호출됨 
- 그래서 저희는 ViewController에서 다른 ViewController로 이동 되어도 그대로 juiceMaker가 있어야 해서 viewDidLoad 밖에서 할당하였습니다.

---
## [해결이 되지 않은 점 && 조언이 필요한 점]
### notificationCenter 
- notificationCenter에서 userInfo를 사용하는 경우는 보통 이 알림이 어떤 종류인지, 예를 들어 카카오톡 알림에서 일반 톡인지 선물하기인지를 구분하는 정도의 정보만을 담는다고 알고 있습니다. 이처럼 데이터 자체를 옮기는 역할이 아니라 notification을 구분하기 위한 용도라고 이해했습니다. 저희가 사용한 방법처럼 음료제조의 성공여부, 어떤 음료인지의 정보를 담는 것은 일반적인지 알고 싶습니다.

### ViewController에서 Class 할당
- 위에 간단하게 설명은 했지만 아직까지 어느게 맞는 것인지 헷갈립니다.. 어떤 키워드로 공부하면 좋을지 어떤 문서를 보면 도움이 될지 조언이 필요합니다...

2022-09-07 14:07 UTC, wonhee009 requested changes
스텝2 수고하셨습니다 🎉 
코멘트 남겨두었으니 확인 부탁드려요! 🙏 

- Notification: 일반적인 방법이라는 말이 애매한거 같습니다만 해당 방식처럼 사용해도 무방할거 같습니다.
- ViewController에서 JuiceMaker 할당: 1번과 2번의 차이는 뭘까요? init 시점과 viewDidLoad 호출 시점에 대해 알아보면 좋을거 같습니다. 또한 1번 방식은 `let`으로 선언해도 무방할거 같은데요. 이 부분도 같이 알아보면 좋을거 같아요~

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +    }
`sendFruitStockValue`라는 네이밍이 어색한거 같은데요.
`getFruitStock` 정도는 어떤가요?
Stock, Value의 의미가 크게 다르지 않은거 같고, 해당 메서드의 역할이 send보다는 값을 가져오다는 뜻으로 get이 더 맞지 않나 생각이 드는데요.
여러분 생각은 어떠신가요?

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +    func updateFruitAmountLabel(currentStockValue: [Fruit: Int]) {
[typealias](https://developer.apple.com/documentation/coreservices/typealias)도 한 번 봐보시면 좋을거 같습니다.

```swift
typealias FruitStock = [Fruit : Int]

func updateFruitAmountLabel(currentStock: FruitStock) { ... }
```
이렇게 좀 더 명확한 의미 전달이 가능할거 같습니다 :)

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +            }
이렇게 라벨 자체를 넘겨도 좋지만 저는 개인적으로 UI 요소를 파라미터로 넘기는걸 선호하지 않아서
```swift
for target in currentStock {
    updateLabel(amount: target.value, type: target.key)
}

func updateLabel(amount: Int, type: Fruit) {
    switch type {
        ...
        case .kiwi:
            kiwiAmountLabel.text = "\(amount)"
        ...
    }
}
```
이런식으로 사용하긴 합니다:)

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/FruitStockEditorViewController.swift
> +    @IBAction func touchUpDismissButton(_ sender: UIButton) {
```suggestion
    }
    
    @IBAction func touchUpDismissButton(_ sender: UIButton) {
```

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/Juice.swift
>          let name: Fruit
name 보다는 fruit이나 ingredient? 이런 네이밍은 어떤가요?

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
fruitStore나 JuiceMaker를 분리한 폴더를 'Model'이라고 하셨는데 현재 프로젝트에서 Model은 어떤 의미로 사용되고 있는걸까요?
제가 생각하는 Model은 비즈니스 로직을 처리하는 역할은 없다고 생각했는데요. 재고가 있는지 확인하는 부분은 비즈니스 로직이라고 생각이 들어 질문 드립니다.

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
네이밍에 `is`가 포함되어 있어 Bool 타입을 반환할거 같은데요.
반환 타입은 없고 throw만 있는거 같은데 error를 throw 해야하는 부분일까요?
`is`라는 네이밍을 사용한다면 아래와 같은 형태도 메서드의 의도가 분명해서 좋다고 생각합니다.
```swift
func isEnoughStock(...) -> Bool {
    if 가능하다면 return true
    if 불가능하다면 return false
}

private func takeOrder(juice: Juice) {
    if isEnoughStock() {
    } else { ... }
}
```

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +    func noticeResultOfJuiceMaking(isSuccess: Bool, juiceName: String) {
`noticeJuiceMakeResult`는 어떤가요?

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            name: Notification.Name("resultInmakingJuice"),
"resultInmakingJuice"는 post, observe 하는 여러 곳에서 사용될텐데요.
개발자의 오타로 휴먼에러 가능성이 있어보입니다.
(Notification 같은 경우는 name에서 오타나면 나중에 디버깅할때 고생할 수도...)
이런 name은 static하게 상수로 선언해주고 사용하는건 어떨까요?

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +        guard let juiceName: String = notice.userInfo?["juiceName"] as? String else { return }
```suggestion
        guard let isSuccess: Bool = notice.userInfo?["isMakingSuccess"] as? Bool,
                   let juiceName: String = notice.userInfo?["juiceName"] as? String else { return }
```

2022-09-07 14:07 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +            let succeedAlert = UIAlertController(
```suggestion
            let successAlert = UIAlertController(
```

2022-09-08 11:20 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +    }
`sendFruitStockValue` -> `getFruitStock` 변경했습니다! 
비슷한 의미로 FruitStore에 `sendFruitStockValue` -> `sendFruitStock` 로 변경했습니다.

2022-09-08 11:28 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +    func updateFruitAmountLabel(currentStockValue: [Fruit: Int]) {
조언 감사합니다! 반영해서 수정했습니다 :)

2022-09-08 11:42 UTC, jonghancha commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +            }
수정 후가 코드의 가독성이 좋게 느껴져서 수정하긴 했지만, 저희끼리 토의한 결과 UI 요소를 파라미터로 넘기면 안되는 이유는 찾기 어려웠습니다. 혹시 UI 요소를 파라미터로 넘기는걸 선호하지 않으시는 이유를 여쭤봐도 될까요? 궁금합니다!

2022-09-08 12:07 UTC, jonghancha commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +    func noticeResultOfJuiceMaking(isSuccess: Bool, juiceName: String) {
noticeJuiceMakeResult 보다는 noticeResultOfJuiceMaking이 문법적으로 좀 더 맞다고 판단해 바꾸지 않았습니다🥲

2022-09-08 13:08 UTC, hyhy0429 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
저희가 원래는 `isEnoughStock` 반환타입으로 Bool 타입을 사용했었는데요, 추후 `JuiceMakerError` 타입으로 반환타입을 변경하고 나서, 미처 함수 이름의 변경까지는 생각하지 못했습니다.
라자냐가 짚어주신대로, 함수명이 is로 시작될 경우 Bool 타입 반환이 자동적으로 예상될 수 있기에, 꼼꼼하고 명확한 네이밍을 하는 습관을 가져보도록 하겠습니다! 🙂

2022-09-08 13:11 UTC, jonghancha commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            name: Notification.Name("resultInmakingJuice"),
```swift
extension Notification.Name {
    static let resultInmakingJuice = Notification.Name("resultInmakingJuice")
}
```
말씀해주신대로 Notification.Name은 extension과 static을 통해 많이 사용한다는 것을 알았습니다! 우선 notification을 post하는 JuiceMaker파일 안에 extension을 추가했는데, 동시에 따로 extension을 위한 파일을 추가해 만들어줘야 하는건지 고민했습니다. 저희는 class의 extension인 경우 해당 class가 존재하는 파일에 extension을 추가했는데, Notification은 저희가 따로 선언해준 곳이 없어서 고민했던 것 같습니다. 이에 대한 조언을 해주실 수 있나요?

2022-09-08 13:27 UTC, jonghancha commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
>fruitStore나 JuiceMaker를 분리한 폴더를 'Model'이라고 하셨는데 현재 프로젝트에서 Model은 어떤 의미로 사용되고 있는걸까요?
제가 생각하는 Model은 비즈니스 로직을 처리하는 역할은 없다고 생각했는데요. 재고가 있는지 확인하는 부분은 비즈니스 로직이라고 생각이 들어 질문 드립니다.

 라자냐의 말씀을 듣고 순간 멍해졌었습니다. 생각해보니 Model에 대한 기준을 두지 않고 코드를 써내려갔던 것 같습니다. 이에 대해 팀원들과 얘기를 나눠봤지만 명확한 결론을 내리지 못해 각자 생각을 정리해서 코멘트로 남겨보기로 했습니다.

 제가 생각하는 모델은 데이터와 그 데이터를 다루는 기본적인 로직의 정의까지 포함한다고 생각합니다. 이번 프로젝트에서 다뤄지는 데이터란 fruitStock이고, 이를 'update하는 함수' '재고를 확인하는 함수'의 `정의`까지는 모델의 역할이라고 생각합니다. 결국 함수를 호출해 모델에게 명령을 내리는 건 컨트롤러의 역할이라고 생각했구요.

 때문에 JuiceMaker에서 재고가 있는지 확인하는 부분은 컨트롤러가 해야하는 역할이라고 생각했습니다. make(juice)함수 내부에서 재고를 수정하는 부분도 마찬가지일거라고 생각합니다. 그럼 결국 JuiceMaker는 Model을 벗어나 Controller폴더로 이동하는게 맞는 것일까요?

2022-09-09 08:48 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
애플의 [MVC 문서](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/MVC.html) 에 따르면

모델은 응용 프로그램의 고유한 데이터를 `**캡슐화하고 해당 데이터를 조작 및 처리하는 논리와 계산을 정의한다**.` 모델은 다른 모델과 1:1, 1:N 관계를 가질 수 있으며, 따라서 애플리케이션 모델 레이어는 효과적으로 하나 이상의 객체 그래프가 될 수 있습니다. `**앱의 지속상태에 속하는 데이터의 대부분은 데이터가 앱에 로드된 후 모델에 있어야 합니다**`.-모델은 데이터를 표시하고 사용자가 데이터를 편집할 수 있도록 하는 뷰에 명시적으로 접속하지 않는 것이 이상적입니다. 또한 사용자 인터페이스와 프레젠테이션의 문제는 관여하지 않는 것이 좋습니다.

라고 되어있는데요.

> 모델은 응용 프로그램의 고유한 데이터를 `캡슐화하고 해당 데이터를 조작 및 처리하는 논리와 계산을 정의한다`

이러한 이유에서 JuiceMaker 안에서 데이터를 조작 처리하는 부분들을 Model 폴더 안에 구분해 놓았습니다.


> 제가 생각하는 Model은 비즈니스 로직을 처리하는 역할은 없다고 생각했는데요. 재고가 있는지 확인하는 부분은 비즈니스 로직이라고 생각이 들어 질문 드립니다.

비즈니스 로직이라는 말의 의미가 `비즈니스 로직(Business logic)은 컴퓨터 프로그램에서 실세계의 규칙에 따라 데이터를 생성·표시·저장·변경하는 부분을 일컫는다. ` [(출처- 위키디피아](https://ko.wikipedia.org/wiki/%EB%B9%84%EC%A6%88%EB%8B%88%EC%8A%A4_%EB%A1%9C%EC%A7%81) 라고 되어있는데요! (Apple이나 iOS에서 비즈니스 로직의 의미는 찾지 못해서 위키디피아로 대체했습니다.) 라자냐가 말씀하시는 비즈니스 로직에는 어떠한 의미고 어떠한 기준으로 비즈니스 로직을 구분하시는지 조언을 얻을 수 있을까요?

2022-09-09 09:04 UTC, hyhy0429 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
`Model은 비즈니스 로직을 처리하는 역할은 없다` 고 생각한다고 하셨는데요, 이 말을 저희 프로젝트에서 보았을 때에 Juice 타입 내부에서는 해당 타입내부와 관련된 메서드만 있어야 하고, FruitStore 타입은 해당 타입과 관련된 메서드만 있어야 하며, 서로가 하는 일을 몰라야 한다라고 이해해도 괜찮은지 궁금합니다. 즉, 해당 타입 안에는 단순히 해당 타입안에서의 처리해야 하는 일만을 담은 메서드만 있어야 하고, 타입의 인스턴스를 생성하고 해당 메서드를 호출하는 것은 뷰컨 단위에서 해야하는 걸로 이해했는데 맞을까요?

2022-09-11 03:31 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            name: Notification.Name("resultInmakingJuice"),
현재처럼 JuiceMaker 파일 내에 extension을 추가해줘도 좋지만 Notification.Name을 사용할 수 있는 곳을 생각해보면 좋을거 같습니다.
Notification을 post하는 곳, observe하는 곳에서 해당 Name을 사용할 수 있을거 같은데요. 그렇다면 post하는 곳에 extension을 정의해야할까요, observe하는 곳에서 extension을 정의해야 할까요,  post 혹은 observe하는 곳은 다수로 존재할텐데 이럴 경우에는 어디에 정의해야할까요?
다수로 존재할때 다른 개발자가 중복으로 정의할 수도 있지 않을까요?
저는 그래서 이런 경우에는 extension 만을 정의하는 파일을 하나 만드는 편입니다 :)

2022-09-11 03:32 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Controller/FruitJuiceStoreViewController.swift
> +            }
앗 그냥 그 부분은 정말 저의 개인적인 취향입니다...ㅎㅎ

2022-09-11 07:25 UTC, wonhee009 requested changes

2022-09-11 07:25 UTC, wonhee009 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
남겨주신 코멘트들 확인해봤습니다:) 코멘트들 읽으면서 제가 질문을 애매하게 적은 부분이 있는거 같아 여러분들에게 살짝 혼란을 준거 같은데요.ㅠ_ㅠ
isEnoughStock() 메서드보다는 takeOrder에 대한 얘기가 맞을거 같습니다.

JuiceMaker.takeOrder()를 호출하면 아래와 같은 순서로 코드가 동작할텐데요.
1. fruitStore에서 해당 레시피의 재고가 충분한지 확인한다.
	1-1. 재고가 부족하면 false notification을 post하는 메서드를 호출한다.
	1-2. 재고부족 이외의 에러가 발생하면 그대로 메서드 종료한다.
2. 재고가 충분하므로 주스를 만드는 make 메서드를 호출한다.
	2-1. Make 메서드는 레시피를 돌면서 fruitStore의 재고를 수정한다.
3. true notification을 post하는 메서드를 호출한다.
저는 이런 흐름 자체를 비즈니스 로직이라고 보는 편입니다.

코멘트에 남겨주신 MVC에서의 Model의 역할이
- 데이터를 다루는 기본적인 로직의 정의
- 캡슐화하고 해당 데이터를 조작 및 처리하는 논리와 계산을 정의

였는데요. 해당 메서드 내에서 데이터를 다루는 로직 뿐 아니라 여러 역할(재고 확인, 재고 수정, notification post)를 하고 있어 해당 역할의 범주를 넘어서지 않았나 생각이 듭니다.

저는 takeOrder()이 아래와 같이 VC에 있어야한다고 생각하는데요.
```swift
class ViewController {
   func takeOrder(juice: _) {
      do {
         if try juiceMaker.canMakeJuice(juice.recipe) {
            juiceMaker.make(juice.recipe)
         } else {
            …
         }
      } catch juiceMakerError.notEnoughStock {
         …
      }
   }
}

class JuiceMaker {
   func canMakeJuice(recipe: _) throws -> Bool {
      return try fruitStore.isEnoughStock(recipe)
   }

   func make(recipe: _) {
      …
   }
}
```

- 과일의 재고가 부족하다면 주스를 생성하지 않고 alert을 띄워주는 A <- 현재 스펙
- 과일의 재고가 부족하다면 해당 과일에 재고 10씩을 추가한 뒤 주스를 만들어주는 B <- 추가된 스펙

추가된 스펙을 구현하기 위해서는 takeOrder이 VC에 있을 때와 Model에 있을 때 어떤 차이점이 있을까요?

#### VC에 있는 경우
```swift
func takeOrder(juice: _) {
   do {
      if try juiceMaker.canMakeJuice(juice.recipe) {
         juiceMaker.make(juice.recipe)
      } else {
         …
      }
   } catch juiceMakerError.notEnoughStock {
      juiceMaker.addFruit(_)
      juiceMaker.make(juice.recipe)
   }
}
```
이런식으로 수정할 수 있을텐데요.

그렇다면 Model에 있는 경우에는 어떻게 수정할 수 있을까요?
`takeOrder(juice: _, ifNotEnoughAddFruit: Bool)` 이런식으로 부족할 경우 재고를 자동으로 추가할지에 대한 파라미터를 추가하는 방식으로 수정할 수 있을거 같습니다.
그렇다면 주스를 만드는 메서드에 관련해서 새로운 스펙이 추가되면 무한정으로 파라미터가 추가될 수 있지 않을까요?

위의 코멘트들을 종합해보면 이러한 이후 추가되는 스펙등에 대응 및 유지보수를 위해서는 최대한 역할을 나누는 것이 좋으며 위의 예시처럼 비즈니스로직을 모델과 분리하는게 좋다입니다.

2022-09-13 02:50 UTC, jonghancha commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            name: Notification.Name("resultInmakingJuice"),
takeOrder()를 VC로 옮기며 결과에 대한 alert를 바로 나타나게 구현했습니다. 그로 인해 NotificationCenter는 불필요하다고 판단해 기능을 삭제했습니다. Notification을 사용하게 된다면 extension은 따로 파일로 만드는게 좋을것 같습니다!

2022-09-13 03:00 UTC, zhilly11 commented on JuiceMaker/JuiceMaker/Model/Juice/JuiceMaker.swift
> +            try fruitStore.isEnoughStock(juiceRecipe: juice.recipe)
라자냐 조언대로 비즈니스 로직이라고 생각되는 `takeOrder()` 메서드를 ViewController단위로 이동했습니다. 그리고 `canMakeJuice() throws`라는 `fruitStore`에 있는 `checkEnoughStock` 의 Error throws 를 그대로 받아 전달하는 메서드를 작성해 ViewController 단에서 사용했습니다.

따라서 추가된 스펙이나 요구사항이 생기면 ViewController단에서 유지보수 할 수 있게 된 것 같습니다.

2022-09-13 03:09 UTC, wonhee009 approved these changes
수고하셨습니다 👍

2022-09-13 03:09 UTC, merged