쥬스 메이커 [Step2] Baem, Jeremy
yagom-academy/ios-juice-maker pull request #270
Opened 2022-09-08 04:57 UTC by Dylan-yoon

@hansangjin96 
안녕하세요 하비! Step2 PR 올립니다.!

### ⭐️ 구현한 기능
- MainViewController -> 옵저버, fruitStock -> 옵저빙할 오브젝트. 데이터가 바뀔때 마다 label text를 update하는 KVO 구현
- Alert을 사용하여 alertOrderIsReady(), alertNotEnoughStock() 구현
- 코드를 사용하여 presentStockEditorViewController() 뷰 컨트롤러 전환 및 dismiss 구현

### 🤔 코드를 작성할 때 고민되었던 점

#### 1. IBAction의 네이밍.. -> 기존 함수와 같이 적용해야하는지? 처음 네이밍하는부분이라 어떻게 해야될지모르겠음
#### 2. 일단 modal 방식을 채택했지만, 세로모드에서는 modal 과 show 간의 큰 차이가 없는데 무엇을 기준으로 잡고 판단해야하는가.

#### 3. UIButton Identify 방식 그리고 재고 부족 Alert 구현 방식
저희가 생각하는 버튼의 identifying 방식에는 5가지가 있습니다:
- tag
- titleLable
- restorationIdentifyer
- accessabilityIdentifyer
- sender

```swift
@IBAction func orderJuice(_ sender: UIButton) {
    switch sender {
        case strawBerryButton:
        //딸기 쥬스 주문
        case bananaButton:
        //바나나 쥬스 주문
        ...
    }
}
```

초기에 `orderJuice()` 함수를 구현하면서 `sender`를 받아와 switch문 case별로 위의 예제와 같이 핸들링을 했었지만 비효율적이란느 생각이다 들어 `restorationIdentifier`을 사용을 했습니다. 
하지만 `restoration`과 `accessabilityIdentyfier` 모두 별도의 용도가 정해져 있어 . 그래서 선택한 것이 tag 보다 간편하고 간략한 각 버튼의 titleLabel별로 "**쥬스" 문자열만을 잘라와 case에 접근했습니다.

```swift
enum Juice: String {
    case strawBerry = "딸기쥬스"
    case banana = "바나나쥬스"
    ...
}

@IBAction func orderJuice(_ sender: UIButton) {
        if let sender = sender.titleLabel?.text?.replacingOccurrences(of: " 주문", with: ""),
            let juice = Juice(rawValue: sender) {
            if juiceMaker.requestStockAvailability(for: juice) {
                juiceMaker.store.useStockForRecipe(of: juice)
                present(alertOrderIsReady(juice), animated: true, completion: nil)
            } else {
                present(alertNotEnoughStock(), animated: true, completion: nil)
            }
        }
    }
```

위와 같이 JuiceMaker의 `makeJuice()` 함수에서 `requestStockAvailability(for: juice)`를 외부로 분리하여 재고 부족 Alert를 구현했습니다.

### 🙏🏻 조언을 얻고 싶은 부분

1. 스토리보드의 커밋 로그는 어떤 방식으로 남기는지 궁금합니다.
2. 개인적으로는 여러개의 NavigationController가 존재하는 이유는 Navigation Bar를 사용하기 위함이라는 추측을 하고있습니다. 여러개의 view stack이 아닌 단일 view를 보여주는 상황에서NavigationController가 꼭 필요한 것인지 궁금합니다.
3. ViewController파일 내에서의 함수 순서는 어떤식으로 구성하는게 더 일반적일지 조언 받고싶습니다.

2022-09-08 08:08 UTC, hansangjin96 requested changes
> 스토리보드의 커밋 로그는 어떤 방식으로 남기는지 궁금합니다.

이 질문은 제가 잘 이해를 못했는데요,
스토리보드를 수정한 뒤에 커밋했을 때 어떤 메시지를 남기시는지가 궁금하셨던걸까요?
제가 이해한 부분이 맞다면, 저의 개인적인 취향은 ... 스토리보드에 대한 커밋은 믿음의 어프루브... 같은 느낌이긴 합니다 ㅎㅎ 

> 개인적으로는 여러개의 NavigationController가 존재하는 이유는 Navigation Bar를 사용하기 위함이라는 추측을 하고있습니다. 여러개의 view stack이 아닌 단일 view를 보여주는 상황에서NavigationController가 꼭 필요한 것인지 궁금합니다.

말씀하신대로 단일 뷰만 나오는 경우가 무조건 보장된다면 NavigationController가 필요하지 않겠죠 ㅎㅎ
present했을 때 어딘가로 push가 일어난다거나, 동일한 UX의 네비게이션바를 보고싶다고 한다면 NavigationController를 추가해주는 것이 이상하지는 않다고 생각해요!

> ViewController파일 내에서의 함수 순서는 어떤식으로 구성하는게 더 일반적일지 조언 받고싶습니다.

이 부분은 뷰컨트롤러가 너무 많은 부분을 담당하고 있기 때문에 순서가 헷갈리실 수 있는데요,
야곰 아카데미에서 프로젝트를 계속 해나가다보면 점점 감이 잡히실거 같아요!
뷰컨트롤러가 하는 역할들이 정리가 되면, 뷰가 로드됐을 때 어떤 순서로 함수가 실행될 지가 정리되실거 같아요ㅎㅎ
순서에 정답은 없습니다!

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		C73DAF3A255D0CDD00020D38 /* MainViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = MainViewController.swift; sourceTree = "<group>"; };
`MainViewController`보다는 해당 뷰컨에서 하는 역할의 이름으로 네이밍 하는건 어떨까요?

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    private lazy var fruitStock = juiceMaker.store.stock
`lazy var`라는 의미는 해당 프로퍼티가 메모리에 로드될 수도 있고, 안될 수도 있다. 라고 오해할 여지가 있을거 같아요!
레이지 키워드 없이 초기화해줄 수 있는 방법은 고민해보셨을까요??

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
이렇게 하면 쥬스를 하나 시킬 때 마다 fruitStock 전체가 업데이트 될 거 같아요!!
하지만 딸기바나나 주스를 시켰는데 키위의 재고에 영향이 간다면, 사이드 이펙트가 발생할 가능성이 있을 것 같아요!
재고를 사용한 재료들만 업데이트되도록 해보는건 어떨까요??

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        })
KVO로 재고를 업데이트 하는 부분에서 많은 고민을 하셨을 것 같아요 멋집니다 👍 👍 
KVO말고 어떤 방식이 있고, 다른 방식들과의 장단점은 고민해보셨는지 궁금합니다 : )

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        if let sender = sender.titleLabel?.text?.replacingOccurrences(of: " 주문", with: ""),
중복된 코드를 없애기 위해 sender에 따라 분기처리 하려고 하신 모습 보기 좋습니다 💯 
하지만 저는 **개인적으로** 하나의 버튼은 하나의 역할만 해야한다고 생각해요!
이렇게 작성되면 버튼이 추가되고, 삭제되고 했을 때 예상하지 못한 동작이 생길수도 있구요 ㅎㅎ
하나의 버튼에 하나의 `@IBAction func`가 연결되어 있어도 좋겠다고 생각합니다 ㅎㅎ

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +                present(alertOrderIsReady(juice), animated: true, completion: nil)
`presentAlert(...)`와 같은 함수를 만들어보는건 어떨까요??

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            if juiceMaker.requestStockAvailability(for: juice) {
지금 로직에서는 에러 핸들링을 쥬스메이커 안에서 하고 있는데요,
쥬스메이커의 재고 상황을 체크해서 알럿을 띄워주는 에러 핸들링을 뷰컨에서 해보는건 어떨까요? :)

2022-09-08 08:08 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
어떤 재고가 몇 개 부족한 지 표시해주면 더 좋을거 같다는 생각이 드네요!

2022-09-08 12:12 UTC, yjjem commented on JuiceMaker/JuiceMaker.xcodeproj/project.pbxproj
> +		C73DAF3A255D0CDD00020D38 /* MainViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = MainViewController.swift; sourceTree = "<group>"; };
`JuiceMakerViewController`로 네이밍 수정했습니다. 감사합니다. 🙌

2022-09-08 13:59 UTC, yjjem commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
아래의 예제와 같이 변경사항만 업데이트 하도록 수정하였습니다. 🤓👍 

```swift
private func updateStock(to newValue: [String: Int], from oldValue: [String: Int]) {
    for fruit in newValue.keys {
        guard newValue[fruit] != oldValue[fruit],
                let newValue = newValue[fruit] else { continue }
        fruitStock.updateValue(newValue, forKey: fruit)
    }
}
```

2022-09-08 14:06 UTC, yjjem commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +                present(alertOrderIsReady(juice), animated: true, completion: nil)
별개의 함수를 만들지 않고 각 `Alert` 함수들의 return 값이 `present` 하도록 수정하였습니다. 
따라서 함수의 네이밍에 present를 추가하였습니다.

```swift
private func presentAlertOrderIsReady(_ juice: Juice) {
    let alert = UIAlertController(title: "완성!", message: "\(juice.rawValue) 나왔습니다! 맛있게 드세요!", preferredStyle: UIAlertController.Style.alert)
    let ok = UIAlertAction(title: "Ok", style: .default, handler: { _ in
        NSLog("The \"OK\" alert occured.")})
    alert.addAction(ok)
    
    return present(alert, animated: true, completion: nil)
}
    
private func presentAlertNotEnoughStock() {
    let alert = UIAlertController(title: "재고 부족!", message: "재료가 모자라요. 재고를 수정할까요?", preferredStyle: UIAlertController.Style.alert)
    let ok = UIAlertAction(title: "Ok", style: .default, handler: { _ in
        NSLog("The \"OK\" alert occured.")
        self.presentStockEditorViewController()
    })
    let cancle = UIAlertAction(title: "Cancle", style: .default, handler: { _ in
        NSLog("The \"Cancle\" alert occured.")})
    alert.addAction(cancle)
    alert.addAction(ok)
    
    
    return present(alert, animated: true, completion: nil)
}
```

2022-09-09 04:22 UTC, yjjem commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        })
저희가 알고있는 방식에는 KVO, NotificationCenter, PropertyObserver 가 있습니다.

사실대로 말씀드리면. 최근에 KVO와 NotificationCenter 개념을 접하게 되면서 프로젝트에 적용을 시켜보자는 취지였습니다. 그래서 Property Observer는 사용하지 않았습니다.

KVO를 사용해보기 위해 공부하는 과정이 생각보다 오래 걸려 NotificationCenter는 시도조차 못해봤습니다. 따라서 현제 step2에 KVO를 사용하고 있지만 현재 저희가 이해한 것을 말씀드리자면 KVO는 "산지직송" , NotificationCenter는 "옥천 HUB" . 
즉 KVO는 변동이 있을시 어느 곳도 거치치  않고 바로 observer에 알리고, NotificationCenter는 중계 지점을 거쳐 요청하는 observer들에게 알리는 것이라고 이해를 했습니다. 

NotificationCenter를 사용해보진 않았지만 하나의 Observer만을 사용하는 저희 프로젝트에서는 KVO가 더 어울린다고 생각을 했습니다.  
감사합니다.  😀

2022-09-11 08:06 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        if let sender = sender.titleLabel?.text?.replacingOccurrences(of: " 주문", with: ""),
최초에 중복코드를 없애기 위해 sender를 사용해 분기 처리했습니다.
가독성을 고려해서 한번에 처리하려고 했습니다.
다시 생각해보니 짧게 쓴다고 모든것이 좋은것이 아니라는것을 다시한번 느끼는 부분인것 같습니다.

하지만 하비가 말씀해주신 것 처럼 버튼은 하나의 역할을 해야 추후에 유지관리가 훨씬 수월 하겠네요!
🐤
그래서 아래와같이 변경했습니다!.
```swift
@IBAction func tapStrawBerryBananaButton(_ sender: UIButton) {
        orderJuice(juice: .strawBerryBanana)
    }
    
    @IBAction func tapMangoKiwiButton(_ sender: UIButton) {
        orderJuice(juice: .mangoKiwi)
    }
    
    @IBAction func tapStrawBerryButton(_ sender: UIButton) {
        orderJuice(juice: .strawBerry)
    }
    
    @IBAction func tapBananaButton(_ sender: UIButton) {
        orderJuice(juice: .banana)
    }
    
    @IBAction func tapPineAppleButton(_ sender: UIButton) {
        orderJuice(juice: .pineApple)
    }
    
    @IBAction func tapKiwiButton(_ sender: UIButton) {
        orderJuice(juice: .kiwi)
    }
    
    @IBAction func tapMangoButton(_ sender: UIButton) {
        orderJuice(juice: .mango)
    }
    
    func orderJuice(juice: Juice) {
        if juiceMaker.requestStockAvailability(for: juice) {
            juiceMaker.store.useStockForRecipe(of: juice)
            presentAlertOrderIsReady(juice)
        } else {
            presentAlertNotEnoughStock(data: juice.recipe)
        }
    }
```

2022-09-11 08:20 UTC, yjjem commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +    }
아래의 코드 예제와 같이 `presentAlertNotEnoughStock()` 메소드가 Juice.recipe 데이터를 받아와서 부족한 Fruit 종류와 갯수를 계산하는 함수  `getInsufficientFruitInformation(from data: [Fruit: Int]) -> String` 로 넘겨 표시할 String 값을 반환하도록 했습니다. 감사합니다  🙌

```swift
private func presentAlertNotEnoughStock(data: [Fruit: Int]) {
        let alert = UIAlertController(title: "재고 부족!", message: "재료가 모자라요.\n \(getInsufficientFruitInformation(from: data))\n재고를 수정할까요?", preferredStyle: UIAlertController.Style.alert)
    ....
    }
    
    private func getInsufficientFruitInformation(from data: [Fruit: Int]) -> String {
        var result: [String] = []
        for (fruit, count) in data {
            if count > juiceMaker.store.stock[fruit.rawValue]! {
                result.append("\(fruit.rawValue)가 \(count - juiceMaker.store.stock[fruit.rawValue]!)개")
            }
        }
        
        return result.joined(separator: "\n")
    }
```

2022-09-11 08:22 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +            if juiceMaker.requestStockAvailability(for: juice) {
JuiceMaker -> JuiceMakerViewController 에서 핸들링 하도록 변경했습니다!

2022-09-11 08:44 UTC, hansangjin96 approved these changes
수고하셨어요!

2022-09-11 08:44 UTC, merged