쥬스 메이커 [Step 2] LJ, som
yagom-academy/ios-juice-maker pull request #271
Opened 2022-09-10 13:11 UTC by jsa0224

안녕하세요, 프린스 @junbangg 🕌~
저희 Step2 PR 보냅니다..

# 고민했던 부분
- **얼럿 메서드 호출 위치**
처음에는 기존의 ViewController 객체에서 구현해야하나 고민을 많이 했습니다. 그래서 do-catch문을 ViewController 객체에서 구현을 해보았지만, 이미 JuiceMaker 객체에서 이미 do-catch문이 구현되어 있어 실행이 안 되는 문제가 생겼습니다. 그래서 JuiceMaker 객체의 makeJuice 메서드에서 ViewController를 파라미터로 받아 구현하는 방식으로 해결했습니다.

- **재고를 체크하는 메서드 기능 분리**
알라딘과 면담 후, FruitStore의 객체의 checkFruitStock 메서드의 기능을 분리하면서, 분리된 메서드들의 반환값을 do-catch문으로 걸러 changeFruitStock 메서드의 파라미터로 받아오려고 했습니다. 위의 고민과 똑같이 do-catch이 이미 makeJuice 메서드에서 구현되어, makeJuice의 메서드를 바꾸는 방향으로 해결했습니다.

# 해결되지 않은 부분
![](https://i.imgur.com/wz96mw4.gif)

딸기바나나 쥬스를 만들 경우, 딸기는 재고가 없지만 바나나가 있는 상태에서 쥬스 만들기를 시도하면 바나나만 차감되는 상황을 어떻게 해결하면 좋을까요?

# 조언을 얻고 싶은 부분
- **Recipe 구조체를 이용해서 recipeOfJuice 표현하는 부분**
분명 알라딘과 면담을 진행하고 이 방법에 대해 100% 이해하고 있다고 확신했는데... 까먹어버렸습니다🤣 그래서 일단 구조체로 Recipe 타입을 구현하고, recipeOfJuice에 적용해보았지만... 알라딘이 말씀하신 의도대로 구현했는지는 아직도 저희는 의문입니다😂 Step 1 코멘트로 남겨주신, 구조체 인스턴스를 이용해보라는 말씀에서 인스턴스는 어디에 구현을 해야할지도 막막해졌습니다.

- **som이 개인적으로 조언을 얻고 싶은 부분**
제가 너무 Step3까지 다 구현하고 머지받는 것에 계속 집착하게 되는 거 같습니다. 야곰 아카데미에서 제시하는 Step들을 다 구현하지 않아도 괜찮은 건가요?

2022-09-13 02:19 UTC, junbangg requested changes
수고하셨습니다 이번 스텝도!!
저희가 이야기했던 리팩토링을 열심히 진행해주셨네요 ㅎㅎ

질문 주신 내용 답변을 드리자면 

일단 해결하지못한점은..원인은 파악이 되신걸까요?? 이 얘기는 따로 나눠보시죠!

그리고 솜의 개인적인 질문은..음 이건 개인마다 생각이 다를 수 있겠지만! 
저는 개인적으로 전혀 중요하지 않다고 생각해요 ! 
끝낸다고 누가 상을 주지도 않고! 다음 프로젝트 시작하면 생각할 시간도 없을것 같아요. 
그것보다는 이 프로젝트에서 어떤걸 배웠고, 그걸 앞으로 써먹을 수 있는지가(기록) 훠어얼씬 중요하다고 생각합니다.

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet weak var mangoJuiceButton: UIButton!
Iboutlet도 접근제어 할 수 있을것 같아요!

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    let juiceMaker = JuiceMaker()
프로퍼티가 엉뚱한곳에 있어보입니다
이 친구도 위에 있는 프로퍼티들과 같이 있게 해주는건 어떨까요??
그리고 얘도 은닉화가 가능할것 같아요!

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        imageView.image = UIImage(named: "위대한 개츠비")
오 이 친구는 어떤거죠???

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        let emptyStockAlert = UIAlertController(title: "알 수 없는 오류입니다.",
UIAlertController 가 여러번 생성되고 있는거 같아요🤔
쫌더 재사용할 수 있는 방법은 없을까요???

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +
불필요한 줄바꿈이 있어보여요!

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            NotificationCenter.default.post(name: NSNotification.Name("stockChanged"),
여기서 notification을 뿌리게한 이유가 있을까요??

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> -    private let fruitStorage = FruitStore()
이친구 밖에서 접근하게 둘 필요가 있을까요?
아마 접근하려면 . 이 두번 쓰여야될것 같은데
은닉화를 시키고 메서드를 통해서 필요한 작업들을 해주는건 어떨까요??

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/Recipe.swift
> +    let ingredient: [Fruit: Int]
요기서 쪼금만 더 생각해보시면 될것 같아요
Recipe 는 Ingredient 들의 모임이잖아요??
그럼 우리가 의도한걸 구현하려면 하나의 타입이 더 필요해보여요! Ingredient!
그럼
'''
let ingredients: [Ingredient]
'''
요런 느낌으로 바뀔것 같네요

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: Int {
오 왜 INT 타입으로 바뀌었나요???

2022-09-13 02:19 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                view.showSuccessAlert(to: order) // 최종 목적지
주석이 남아있네요!

2022-09-13 08:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet weak var mangoJuiceButton: UIButton!
네! 접근제어 해보도록 하겠습니다!

2022-09-13 08:23 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    let juiceMaker = JuiceMaker()
앗 그렇네요! 다른 프로퍼티들과 같은 위치에 두도록 하겠습니다!

2022-09-13 08:24 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        imageView.image = UIImage(named: "위대한 개츠비")
나중에 같이 토의할 때 알려드리도록 하겠습니다^^!

2022-09-13 08:37 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        let emptyStockAlert = UIAlertController(title: "알 수 없는 오류입니다.",
이 부분도 저희 얘기 나눌 때, 같이 토의해보았으면 좋겠습니다!

2022-09-13 08:38 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +
넵 수정하겠습니다 😀

2022-09-13 08:49 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            NotificationCenter.default.post(name: NSNotification.Name("stockChanged"),
KVO는 값을 계속 지켜보다가 변경되면 알려주는 것이라 값을 계속 지켜보는것보다 NotificationCenter를 이용하는것이 좀 더 효율적인 방법이라 생각했습니다.
FruitStore 과일저장소에서 stock재고값이 변경될 때마다 알려야 해서 위 코드 위치에서 notification을 뿌렸습니다. :)

2022-09-13 08:56 UTC, lj-7-77 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> -    private let fruitStorage = FruitStore()
JuiceMaker쥬스메이커가 FruitStore과일저장소를 소유해야한다는 요구사항을 보고 뷰컨트롤러가 아닌 쥬스메이커파일에서 접근하게 해두었습니다. 메서드를 통해서 작업하는것이 쥬스메이커에서 메소드를 만들어 접근하는것이라고 이해하면 될까요? 이따 질문하겠습니다😭

2022-09-13 09:20 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: Int {
<img width="593" alt="스크린샷 2022-09-13 오후 6 18 41" src="https://user-images.githubusercontent.com/94514250/189863390-3609f4a8-75e2-4626-8317-ead62f6d7157.png">

`sender.tag`의 타입이 Int 타입이기 때문에, Juice의 `rawValue` 값을 활용하기 위해 Int 타입으로 바꿨습니다.

2022-09-13 09:20 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                view.showSuccessAlert(to: order) // 최종 목적지
수정하겠습니다!

2022-09-15 13:49 UTC, junbangg approved these changes
두 분 고생많으셨습니다~~
코드 다시 살펴보면서 눈에 들어왔던 부분들에 대해 간단하게 코멘트 남겼어요~
일단 참고만 해주시고 스텝 3 화이팅 해봅시다 :)

2022-09-15 13:49 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    let juiceMaker = JuiceMaker()
뒤늦게 발견했지만 요친구도 은닉화가 가능할것 같네요 :)

2022-09-15 13:49 UTC, junbangg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    func designateFruitStock() {
요메서드는 은닉화가 가능할것 같아요!
그리고 지금 메서드가 하는 일은 `과일 label` 들의 UI를 업데이트 하는거니까
그런걸 조금 더 표현한 메서드명은 어떻겠습니까??
`updateFruitStockLabels()` 요런 느낌스?

2022-09-15 13:49 UTC, junbangg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkStockAmount(to stock: Int, with amountOfFruit: Int) throws {
아규먼트 레이블은 적절히 사용하면 가독성을 높이지만 무조건 쓸 필요는 없습니다!!
지금 메서드명 자체에도 `stock` , `amount` 가 들어가있는데 아규먼트로도 들어가있어서! 여기서는 빼버리는것도 나쁘지않을것 같아요~

2022-09-15 13:49 UTC, merged