쥬스 메이커 [Step3] Kyo, 하모(태리)
yagom-academy/ios-juice-maker pull request #272
Opened 2022-09-12 04:00 UTC by lxodud

@Monsteel 
안녕하세요 토니! Kyo와 하모가 열심히 최종 Step3를 진행했습니다..!
리뷰 잘 부탁드립니다👍👍👍

### 진행 단계 : Step3
## ⭐️ 구현한 기능

- ViewController
    - `fruitLabel`: Dictionary타입으로 key값은 Fruit타입, value에는 각각 과일에 매칭되는 UILable인 Property
    - `setNotification()`: ViewController의 observer를 추가하는 메서드
    - `@objc updateStockLabel()`: notification이 왔을 때 실행고 재고가 변경된 과일의 label을 수정해주는 메서드
- ModifyStockViewController
    - `fruitUIAttribute`: Dictionary타입으로 key값은 Fruit타입, value에는 각각 과일에 매칭되는 UILable, UIStepper, 재고변경여부를 확인하기 위한 isChange를 추가한 Property.
    - `stepperTapped()`: 각각 과일에 매칭되는 Stepper의 +,- 클릭 시 Label에 변경을 주었고, 변경여부를 바꿔주는 메서드
    - `saveButtonTapped()`: NotificationCenterf를 통해서 변경된 재고를 post 시켜주는 메서드
    - `setNavigationBar()`: 네비게이션 타이틀을 기입하고 색상을 변경
    - `setFruitStockLabel()`: fruitLabel들을 `fruitUIAttribute`에 맞게 셋팅해주는 메서드
    - `setStepperValue()`: Stepper의 기본 value를 셋팅해주는 메서드
    - `saveButtonTapped()`: 저장버튼을 누르면 전체과일의 재고가 아닌 변경된 과일들의 재고만이 post되는 메서드
- FruitStore 클래스
    - `updateFruits()`: 수정된 재고를 Dictionary 타입으로 받아서 fruitStock을 업데이트하는 메서드
- JuiceMaker 구조체
    - `addNotficationObserver()`: ModifyStockViewController에서 post한 notificaiotn을 감지하기 위한 observer를 추가하는 메서드 (클로저 이용)

## ⭐️ 코드를 작성할 때 고민되었던 점
- Singleton패턴 사용에 대한 고민
    - 솔직히 Singleton패턴을 사용해서 구현을 해보았을 때 굉장히 편했습니다. 하지만 Singleton을 사용하면 여러 군데에서 접근이 가능해져 의존성에 문제가 있을 수 있다는 것을 느꼈습니다. 어디서나 Singleton에 접근할 수 있었기 때문에 조금이라도 의존성을 줄이고 필요한곳에서만 데이터에 대한 접근이 가능하도록 Notification을 사용하게 되었습니다.

- 요구사항조건에는 없었지만 재고수정 모달에 닫기 버튼을 추가로 생성한 것에 대한 고민
    - 요구사항에는 네비게이션바에 버튼이 닫기 버튼만 존재하였는데 WWDC2022 영상을 공부하였을 때 정보의 변경이 모달 view에서 생기게 되면 닫기와 저장 두가지 버튼을 제공하는 것을 권장하였습니다. 그리고 닫기 버튼만 있는 경우는 단순히 정보를 보여주기만 하는 상황에서 권장하였습니다. 따라서 두가지 버튼을 구현하였습니다.
    
- Notification을 통해서 데이터를 전달할 때 어떤 객체에 전달할지에 대한 3가지 고민
    - 1. `ViewController`에만 전달하여 ViewController의 Label변경하고, FruitStore의 재고를 변경하기위해 변경된 값을 JuiecMaker에 전달하는 방법.
    - 2. `JuiceMaker`에만 전달하여 FruitStore의 재고를 변경하고 ViewController에 변경된 재고를 전달하는 방법 
    - 3. `ViewController`와 `JuiceMaker` 모두에 전달하여 변경된 값으로 ViewController의 Label, JuiceMaker의 FruitStore에 대한 데이터 변경을 하는 방법
    - 최종적으로 3번의 방법을 채택하였습니다. 이유는 Notification의 특징이 다수의 객체들에게 동시에 이벤트의 발생을 알려준다는 점인데 이러한 점을 직접 구현해보며 느껴보고 싶었고, 의존성에 대한 부분은 1번,2번,3번 모두 동일한 영향을 가질 것이라고 생각했습니다.

- Outlet으로 연결된 요소들의 값 설정에 대한 고민
    - 직접 설정해주면 코드의 가독성이 떨어지고 불필요하게 중복코드가 많아져서 Dictionary로 묶어서 해결하였습니다. 코드를 처음보는 사람이 가독성이 떨어질 것 같긴하지만 코드의 중복성을 상당히 줄일 수 있었습니다. 또한 이러한 아이디어를 통해서 전체 재고의 update가아닌 바뀐 재고만을 update하는 방식도 구현가능하였습니다.
## ⭐️ 해결이 되지 않은 점
아쉽게도 없습니다..!

## ⭐️ 조언을 얻고 싶은 부분 
- 모달창에 네비게이션바를 사용하기 위해 네비게이션 컨트롤러를 사용해야하는지에 대한 고민 
    - Hamo: 모달로 화면전환을 하였을 때 네비게이션 바를 구현하기 위해서 직접적으로 버튼과 레이블을 넣는 방법 / 그리고 UINavigationController의 rootViewController로 해당 viewController 지정해 주는 방법이 있었습니다. UINavigationController를 사용했을 때 장점은 자동으로 상단의 Bar가 embed된다는 점, 자동으로 위치를 설정 해준다는 점이라고 생각됩니다. 근데 굳이 사용할 필요성이 있는지는 잘모르겠습니다. 토니의 생각은 어떤가요 조언받고 싶습니다!!

- Notification에 대한 고민
    - Kyo: 위에 고민되었던 점에서 Notification에 대한 방법을 많이 고민을 했는데 저희가 채택한 방법이 큰프로젝트라고 가정했을 경우 한군데에서만 observer를 사용했을 때보다 어떻게 보면 2군데에서 받기 때문에 추적이 까다로울것같다는 생각을 했습니다..저희가 생각한 방향성이 맞는지, 보완점은 없는지, 더 고민해봐야하는가에 대해서 조언을 받고 싶습니다.

- 가독성에 대한 고민
    - Hamo, Kyo : 위에 Outlet으로 연결된 요소들의 값 설정에 대해서 Dictionary로 묶었을 때 가독성이 조금 떨어지는 경향이 있었습니다. Tony라면 가독성이 우선인지..갓 Tony의 의견이 궁금합니다..

2022-09-13 07:55 UTC, Monsteel requested changes
안녕하세요 Kyo, 하모~! 이번 step3도 수고많으셨습니다 👍

### ⭐️ 조언을 얻고 싶은 부분

> * 모달창에 네비게이션바를 사용하기 위해 네비게이션 컨트롤러를 사용해야하는지에 대한 고민
>    * Hamo: 모달로 화면전환을 하였을 때 네비게이션 바를 구현하기 위해서 직접적으로 버튼과 레이블을 넣는 방법 / 그리고 UINavigationController의 rootViewController로 해당 viewController 지정해 주는 방법이 있었습니다. UINavigationController를 사용했을 때 장점은 자동으로 상단의 Bar가 embed된다는 점, 자동으로 위치를 설정 해준다는 점이라고 생각됩니다. 근데 굳이 사용할 필요성이 있는지는 잘모르겠습니다. 토니의 생각은 어떤가요 조언받고 싶습니다!!

사실에 기반한 이유있는 판단이라면 무엇이든 좋습니다. 👍
굳이 사용할 필요성이 없다면 사용하지 않아도 될 것 같아요!

> * Notification에 대한 고민
>    * Kyo: 위에 고민되었던 점에서 Notification에 대한 방법을 많이 고민을 했는데 저희가 채택한 방법이 큰프로젝트라고 가정했을 경우 한군데에서만 observer를 사용했을 때보다 어떻게 보면 2군데에서 받기 때문에 추적이 까다로울것같다는 생각을 했습니다..저희가 생각한 방향성이 맞는지, 보완점은 없는지, 더 고민해봐야하는가에 대해서 조언을 받고 싶습니다.

Notification에 대한 우려스러운 점은 아래 코드리뷰에 함께 남겼습니다. 참고해 주세요!


참고로, 남겨주신 `Singleton패턴 사용에 대한 고민` 에 대한 부분을 이곳에 적어보자면,

`여러 군데에서 접근이 가능해져 의존성에 문제 ...(중략)`가 notification 을 사용해서 개선이 되었나요?
제 생각에는 Notification이라는 전역적인 singleton 객체로 감쌌을 뿐, 의존성에 대한 문제는 여전히 남아있다고 봅니다.

의존성에 대한 문제를 해결할 수 있는 다른 좋은 방법은 없을까요?
`delegate`라는 키워드에 대해 한번 학습해보시면 도움이 될 것 같아요.


> * 가독성에 대한 고민
> Hamo, Kyo : 위에 Outlet으로 연결된 요소들의 값 설정에 대해서 Dictionary로 묶었을 때 가독성이 조금 떨어지는 경향이 있었습니다. Tony라면 가독성이 우선인지..갓 Tony의 의견이 궁금합니다..

1인 개발이 아닌 여러명과 함께 개발하는 환경에서 가독성은 서로간의 배려이고,
그 배려는 더 나은 생산성을 만들어 냅니다. 중요한 요소이지요.

Dictionary라는 좋은 아이디어를 가져가면서, 가독성을 챙길 수 있는 방법에 대해 고민해보시면 좋을것 같아요 👍 줄바꿈을 하는 등, 같은 코드여도 가독성을 지킬 수 있는 방법들이 있습니다. 한계가 있을 수 있지만요. 😞

이번 step3도 수고 많으셨습니다 :)

2022-09-13 07:55 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +    lazy var fruitUIAttribute: [Fruit : (label: UILabel, stepper: UIStepper, isChange: Bool)] =
굉장히 신선한 접근방식이네요! ✨ 좋습니다.

이곳에서 lazy를 붙여주신 이유가 `@IBOutlet` 값들이 초기화 된 이후에 초기화 되도록 하시려고, (초기화 시점을 제어하기 위해) 작성하신걸로 추측됩니다! 혹시 맞을까요?

만약 맞으시다면, 해당 방법은 조금 위험해 보입니다.
해당 값이 `@IBOutlet` 초기화 이전에 사용되게 된다면 오류가 발생하게 될거에요.

`@IBOutlet`값 초기화가 된 이후에 `fruitUIAttribute`값이 초기화 될 수 있도록 안전하게 처리할 수 있는 방법은 없을까요?


* 제가 사용한 "초기화" 라는 단어의 의미는, 값이 init, 값이 변수에 할당되는 시점을 의미하고 사용했습니다!

2022-09-13 07:55 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        setNavigationBar()
`set~()`함수는 내부에서만 호출되는 함수이니  Access modifier를 활용해 접근할 수 있는 범위를 한정지으면 좋을것 같아요 👍
혹시 이 외에도 내부에서만 사용이 되어야 하는, 사용이 되는 함수나 변수가 있다면  Access modifier를 활용해 접근을 제어해주세요!

2022-09-13 07:55 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>          orderedJuice = orderedJuice.replacingOccurrences(of: " 주문", with: "")
이전 리뷰에서 제가 캐치하지 못한 부분이네요.

해당 처리 방식은 위험해 보입니다. 만약 "주문" 이라는 키워드가 지워진다면,
이곳에도 그 반영이 필수적으로 이루어져야 할텐데, 실수로 누락하게되면 juce를 찾을 수 없는 상황이 발생합니다.

human error를 방지할 수 있는, 더 안전한 처리방법은 없을까요?

2022-09-13 07:55 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +        guard let changeFruit = Fruit(rawValue: sender.tag) else {
`rawValue`의 값이 `sender.tag`과 치환이 되는 개념인지 코드단에서 확인하기 어렵습니다.
명확하게 `rawValue` == `sender.tag` 임을 인지할 수 있도록 표현할 방법은 없을까요?

2022-09-13 07:55 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func setFruitStockLabel() {
👍

2022-09-13 07:55 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateStockLabel), name: Notification.Name.stock, object: nil)
세번째 고민사항과 연관되어 있는 리뷰인데요, 

같은 label을 수정하는 주체가 두곳이네요. 여러곳에서 하나의 label을 제어하다 보면 시점에 차이나, human error로 인해
실제 데이터와는 다르게 표시될 위험이 있습니다. 데이터의 무결성을 보호하는 차원에서 한곳으로 일원화하는 방법은 없을까요?

2022-09-13 12:32 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +    lazy var fruitUIAttribute: [Fruit : (label: UILabel, stepper: UIStepper, isChange: Bool)] =
해당 부분 Tony가 말한 이유 맞습니다!
나중에 접근시 초기화 시키려고 `viewController`와 `ModifyStockViewController`에서 lazy키워드를 사용했었습니다.
수정 내용은 아래와 같습니다.
먼저 해당 배열을 빈 배열로 선언을 하였습니다.
`setFruitLable()`, `setFruitUIAttribute()`메서드를 구현해서 그 안에서 값을 할당해주었습니다. 그리고 그 메서드를 `viewDidLoad()` 에서 호출을 하였고, 그 이유는 
`@IBOutlet`이 모두 `viewDidLoad()`에서 먼저 초기화가 되었기 때문에 안전하다고 생각을 했습니다. 

초기화 이전에 사용될 시나리오가 없을 것같다고 생각을 했었는데 혹시모를 오류에 대비해서 말씀을 해주신건지
아니면 오류가 발생할 수 있는 케이스가 있어서 말씀을 해주신건지 궁금합니다!

2022-09-13 12:32 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        setNavigationBar()
해당부분은 `private` 키워드를 사용해서 수정완료했습니다! 앞으로는 접근제어도 생각을 해보겠습니다 ㅎㅎ

2022-09-13 12:35 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>          orderedJuice = orderedJuice.replacingOccurrences(of: " 주문", with: "")
해당부분을 각각  쥬스주문 버튼마다 tag를 지정하는 방법을 사용하여 수정하였습니다. 
그리고 `Juice` 열거형에서 타입메서드 `findJuiceButtonLocation()`를 생성하여 버튼의 tag에 따라 `Juice`타입을 리턴하도록 하였습니다.

2022-09-13 12:37 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +        guard let changeFruit = Fruit(rawValue: sender.tag) else {
해당부분은 저 부분이 포함된 액션 메서드에서 아래와 같은 코드를 삽입하여 가독성을 높혀보았습니다.
Tony가 조언한 내용과 수정내용이 부합하는지 궁금합니다..!
```swift
let buttonLocation = sender.tag
```

2022-09-13 12:47 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateStockLabel), name: Notification.Name.stock, object: nil)
이 부분은 고민을 해본 결과 Notification을 사용했을 경우 일원화 시키기가 까다롭다고 생각하였습니다. 그 이유는 하나의 메서드에서는  notification의 userInfo를 가지고 Label을 변경해주는 것이었고, 하나는 fruitStore에서 데이터를 가지고 왔었기 때문입니다.  추가로 처음에 두개로 분리를 애초에 한 이유는 변경된 Label들만 가져오고 싶어서 분리를 했었습니다. 혹시 이 부분에 대해서 Tony는 어떻게 생각하시나요??



결과적으로 저랑 하모가 긴~ 토론을 한 결과, Notification은 post되는 Broradcast 를 받을 Observer들이 많고, 그 이후에 이벤트를  처리 해줘야할 때 사용해야한다고 생각이 바뀌었습니다. 또한 Notification, KVO, Delegate를 사용을 할 때 의존성에 초점을 두고 선택하는 것이 아닌 더 상황에 알맞은 방법을 선택하는것이 좋다고 생각하게 되었는데 Tony의 생각은 어떠신가요..?



Kyo - 추가로 Notification을 사용해도 의존성이 남아있다는 것을 알게 되었고, Delegate패턴을 사용하기로 하고 수정 완료하였습니다..! 조언 감사드립니다~!

2022-09-14 09:33 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +    lazy var fruitUIAttribute: [Fruit : (label: UILabel, stepper: UIStepper, isChange: Bool)] =
@KyoPak 일반적인 상황에서는, 초기화 이전에 사용되지 않을거에요.

하지만, 초기화 시점을 분명히 하는것은 중요해요.

(실제로 이런 상황이 발생하는지는 잘 모르겠습니다만, 예시를 들자면)
예기치 못한 오류로 `@IBOutlet`이 초기화되지 않은 상황(VC의 View가 메모리에 로드되지 않은 상황) 에서 lazy value가 초기화가 이루어 지게 된다면 강제 언래핑으로 인해 앱이 종료될거에요.

하지만,  `@IBOutlet`이 초기화된 후에(VC의 View가 메모리에 로드된 후에) 호출되는 `viewDidLoad()`에서 `setFruitUIAttribute`를 진행해 준다면, 강제 언래핑으로 인해 앱이 종료되는 상황으로부터 보다 안전한 처리가 가능하게 되겠지요.

viewLifecycle을 활용해서 조금 더 fit 하게 초기화 시점을 설정하고, 사용해주시길 하는 의도로 리뷰 남겼습니다 👍

2022-09-14 09:33 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +        guard let changeFruit = Fruit(rawValue: sender.tag) else {
제가 말씀드린 내용과는 조금 거리가 있는데요!

조금 자세한 상황을 예시로 들어보면, 
enum Fruit의 구현부를 보고 각 case의 rawValue 값이 어떤 값을 의미하는지 파악하기가 어렵습니다.
해당 rawValue가 어떤 값인지 파악하기 위해서는 init해주는 부분을 보아야 파악할 수 있게 되어요.

제 의도는 이런 포인트를 해결할 수 있는 방법에 대해 여쭈어 보았어요! : )

2022-09-14 09:39 UTC, Monsteel commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateStockLabel), name: Notification.Name.stock, object: nil)
많은 고민을 하신것 같아요. 좋습니다 👍
우선 전체적으로 두분의 의견에 동의해요.

한가지 의견이 있는데,
> Notification, KVO, Delegate를 사용을 할 때 의존성에 초점을 두고 선택하는 것이 아닌 더 상황에 알맞은 방법을 선택하는것이 좋다고 생각하게 되었는데 Tony의 생각은 어떠신가요..?

라고 말씀주신 부분에서, 
1. 상황을 어떻게 정의하냐에 따라서 다르겠지만, `상황에 알맞은 방법` 내에 `의존성에 대한 고려`도 내포되어 있다고 생각해요.

2. 앞으로 여러분들이 판단해야할 상황들에서, 판단 기준이 의존성이냐 상황이냐 처럼, 두가지 상황만 존재하지는 않을거에요, 가지고 계신 지식과 경험을 통해 여러 방면에 대한 고려가 복합적으로 이루어지면 좋을것 같다는 생각이 들고, 자연스럽게 고민하시게 될 거라 생각합니다 👍

2022-09-15 01:41 UTC, KyoPak commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +    lazy var fruitUIAttribute: [Fruit : (label: UILabel, stepper: UIStepper, isChange: Bool)] =
감사합니다! 신경쓰도록 하겠습니다 :)

2022-09-15 04:13 UTC, lxodud commented on JuiceMaker/JuiceMaker/Controller/ModifyStockViewController.swift
> +        guard let changeFruit = Fruit(rawValue: sender.tag) else {
저희가 생각을 잘못했네요!
enum Fruit에 case들의 rawValue가 어떤 역할을 하는지 파악하기 어렵다는 부분을 확인하고 타입 메서드로 어떤 역할을 하는지 명확하게 보여주었습니다!!

2022-09-15 15:48 UTC, Monsteel approved these changes
Kyo, 하모 ~!
리뷰로 남긴 부분들을 코드에 잘 반영해 주셨네요! ✨
모두 수고 많으셨습니다~! 🙌🙌

2022-09-15 15:48 UTC, merged