쥬스메이커 [STEP 3] 메네, 드래곤
yagom-academy/ios-juice-maker pull request #273
Opened 2022-09-12 07:48 UTC by FlameYG

@SungPyo
안녕하세요! `내일날씨맑음`

STEP 3 완료하고 PR 드립니다.

- 뷰 컨트롤러 사이에 과일 재고 데이터를 전달하는 방식에 대해 고민해 보았습니다.

- 스테퍼의 초기값 설정 방법에 대해 고민해 보았습니다.

- STEP 2에서 뷰컨트롤러 상에 구현해 놓았던 Close버튼을 요구사항에 따라 네비게이션 콘트롤러를 사용하여 `닫기` 버튼으로 변경하였습니다.

- 기기 크기에 따라 화면을 보여줄 수 있도록 Auto Layout 적용을 위해 고민하였습니다.

## 고민했던 점
- 뷰 컨트롤러 사이에서 과일 재고 데이터를 전달하는 방식에 대해 여러 방법을 생각해 보았지만, juiceMaker 파일의 store를 static으로 설정하여 사용하였습니다.

- `HomeViewController`에서 인벤토리에 있는 값을 매번 어떻게 가져올지 고민하다가, ViewWillAppear함수를 사용하여 매번 뷰가 올라올때마다 데이터를 가져오는 방식으로 구현하였습니다.
    - ViewWillAppear함수 활용을 위해 presentChangeInventoryViewController함수에서 changeInventoryVC.modalPresentationStyle = .fullScreen로 설정해주었습니다.

- `ChangeInventoryViewController`에서 Stepper의 Value값을 Stepper를 누를때마다 인벤토리에서 값을 읽어오도록 구현하고 싶었으나 누를때마다 값을 읽어오니 값이 고정되어 값이 변화하지 않아, ViewDidLoad함수에서 최초로딩할 때 전체 Stepper의 Value값을 가져오는 방식으로 구현하였습니다.

- `HomeViewController` 화면에서 기기 사이즈가 작은 경우 버튼의 텍스트가 `파인..주문`으로 노출되는 문제를 해결하기 위해 화면크기에 따라 폰트사이즈가 조절되도록 구현할 수 있도록 고민해 보았습니다.
    - 처음 생각한 방법: 버튼의 텍스트를 2줄로 줄바꿈하여 보여주면 ...으로 생략되지 않을 것 같아 버튼 title을 `Plain`에서 `Attributed`로 변경하고 줄바꿈해 보았지만 버튼 상에 첫번째 줄만 노출되는 문제가 있었습니다
    - 해결방안: 폰트에서 Body로 Compact & Regular 각각의 사이즈를 주어 작은 화면에서도 폰트가 ...으로 생략되지 않도록 구현하였습니다.
    
- `ChangeInventoryViewController` 화면에서 오토레이아웃을 적용하기 위해 고민해 보았습니다.
    - 각각의 요소에 뷰 컨트롤러를 적용하기는 어려울 것 같아서 `Vertical Stack View`를 사용하여 과일/갯수 레이블 / 스태퍼를 묶어주고, 5개의 과일 묶음을 `Horizontal Stack View`를 이용하여 다시 묶어주었습니다.
 
## 해결이 되지 않은 점
- STEP 3의 요구사항은 일단 만족은 시킨 것 같습니다.

## 조언을 얻고 싶은 부분
- checkInventory함수와 checkStepperValue함수를 현재 하나씩 초기값을 넣어주는 방식이 아닌 반복문을 돌려 많은 값을 넣어줘야하는 상황에서도 편리하게 초기값 셋팅을 하고자 하였으나, 개선하지 못하고 하나씩 초기값을 넣는 식으로 구현하였습니다...
    - 혹시, 위 2가지 함수를 어떻게 개선하면 좋을지 의견 주시면 감사하겠습니다!

- ChangeInventoryViewController에서 ViewDidLoad함수안에 checkInventory를 통해 Label의 초기값을 셋팅해주고, checkStepperValue를 통해 Stepper의 초기값을 셋팅해두었습니다.
    - 혹시, 각각의 초기값을 따로 설정해주는게 좋은 접근인지, 아니면 초기값은 하나의 함수에 묶어서 처리해주는게 좋은 접근인지 의견 주시면 감사하겠습니다!

- 현재 Stepper를 누를때마다 값을 +, -하고 Label에 값을 바꿔준 뒤 인벤토리에 값을 바로 업데이트 해주는 방식입니다.
    - 혹시, 업데이트를 자주하는 방식이 아닌 Label 값만을 바꿔주다가 Dismiss될 때 최종값을 인벤토리에 업데이트 해주는게 좋은 접근인지 의견 주시면 감사하겠습니다!

- STEP 3 요구사항에 `ChangeInventoryViewController`에 네비게이션 컨트롤러를 사용하여 타이틀을 추가하고 버튼을 적용하도록 되어 있어서 사용하긴 했는데, 직접 뷰 컨트롤러에 Label과 버튼을 사용하는 방식대비 어떤점이 좋은지 잘 모르겠습니다. 이전 STEP을 진행하면서 화면전환 방식에 대해 고민했을 때에도 `재고수정`이라는 새로운 context를 만드는 것이라 생각하고 모달로 구현을 했는데 네비게이션 바를 사용하는 것에 대한 이점이 있을까요?

2022-09-13 13:02 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ChangeInventoryViewController.swift
> +    @IBOutlet weak private var mangoStepper: UIStepper!
왜 weak를 써야하는지
weak를 안쓰면 안되는지
에 대해서 알고 계신가요?

2022-09-13 13:08 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ChangeInventoryViewController.swift
> +            return nil
`tag` 라는걸 이용하면 IBOutlet도 좀 정리할 수 있고 Stepper 자체를 비교하지 않아도 될 것 같은데 한번 알아보시겠어요?

2022-09-13 13:12 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    static let store = FruitStore(initialFruitAmount: 10)
음.. 이걸 static으로 바꾸게 된 결정적인 이유는 뭐에요?

2022-09-13 13:29 UTC, SungPyo commented
> @SungPyo 안녕하세요! `내일날씨맑음`
> 
> STEP 3 완료하고 PR 드립니다.
> 
> * 뷰 컨트롤러 사이에 과일 재고 데이터를 전달하는 방식에 대해 고민해 보았습니다.
> * 스테퍼의 초기값 설정 방법에 대해 고민해 보았습니다.
> * STEP 2에서 뷰컨트롤러 상에 구현해 놓았던 Close버튼을 요구사항에 따라 네비게이션 콘트롤러를 사용하여 `닫기` 버튼으로 변경하였습니다.
> * 기기 크기에 따라 화면을 보여줄 수 있도록 Auto Layout 적용을 위해 고민하였습니다.
> 
> ## 고민했던 점
> * 뷰 컨트롤러 사이에서 과일 재고 데이터를 전달하는 방식에 대해 여러 방법을 생각해 보았지만, juiceMaker 파일의 store를 static으로 설정하여 사용하였습니다.
> * `HomeViewController`에서 인벤토리에 있는 값을 매번 어떻게 가져올지 고민하다가, ViewWillAppear함수를 사용하여 매번 뷰가 올라올때마다 데이터를 가져오는 방식으로 구현하였습니다.
>   
>   * ViewWillAppear함수 활용을 위해 presentChangeInventoryViewController함수에서 changeInventoryVC.modalPresentationStyle = .fullScreen로 설정해주었습니다.
> * `ChangeInventoryViewController`에서 Stepper의 Value값을 Stepper를 누를때마다 인벤토리에서 값을 읽어오도록 구현하고 싶었으나 누를때마다 값을 읽어오니 값이 고정되어 값이 변화하지 않아, ViewDidLoad함수에서 최초로딩할 때 전체 Stepper의 Value값을 가져오는 방식으로 구현하였습니다.
> * `HomeViewController` 화면에서 기기 사이즈가 작은 경우 버튼의 텍스트가 `파인..주문`으로 노출되는 문제를 해결하기 위해 화면크기에 따라 폰트사이즈가 조절되도록 구현할 수 있도록 고민해 보았습니다.
>   
>   * 처음 생각한 방법: 버튼의 텍스트를 2줄로 줄바꿈하여 보여주면 ...으로 생략되지 않을 것 같아 버튼 title을 `Plain`에서 `Attributed`로 변경하고 줄바꿈해 보았지만 버튼 상에 첫번째 줄만 노출되는 문제가 있었습니다
>   * 해결방안: 폰트에서 Body로 Compact & Regular 각각의 사이즈를 주어 작은 화면에서도 폰트가 ...으로 생략되지 않도록 구현하였습니다.
> * `ChangeInventoryViewController` 화면에서 오토레이아웃을 적용하기 위해 고민해 보았습니다.
>   
>   * 각각의 요소에 뷰 컨트롤러를 적용하기는 어려울 것 같아서 `Vertical Stack View`를 사용하여 과일/갯수 레이블 / 스태퍼를 묶어주고, 5개의 과일 묶음을 `Horizontal Stack View`를 이용하여 다시 묶어주었습니다.
> 
> ## 해결이 되지 않은 점
> * STEP 3의 요구사항은 일단 만족은 시킨 것 같습니다.
> 
> ## 조언을 얻고 싶은 부분
> * checkInventory함수와 checkStepperValue함수를 현재 하나씩 초기값을 넣어주는 방식이 아닌 반복문을 돌려 많은 값을 넣어줘야하는 상황에서도 편리하게 초기값 셋팅을 하고자 하였으나, 개선하지 못하고 하나씩 초기값을 넣는 식으로 구현하였습니다...
>   
>   * 혹시, 위 2가지 함수를 어떻게 개선하면 좋을지 의견 주시면 감사하겠습니다!
ㄴ `개선 하라고 하긴 좀 그렇고 for문으로 개선하려면 IBOutlet 부터 수정사항이 좀 많아질텐데 괜찮을까요? 코멘트 달아논 부분을 생각해 보시면 이 코드도 자연스레 바뀌지 않을까 싶습니다.`
> * ChangeInventoryViewController에서 ViewDidLoad함수안에 checkInventory를 통해 Label의 초기값을 셋팅해주고, checkStepperValue를 통해 Stepper의 초기값을 셋팅해두었습니다.
>   
>   * 혹시, 각각의 초기값을 따로 설정해주는게 좋은 접근인지, 아니면 초기값은 하나의 함수에 묶어서 처리해주는게 좋은 접근인지 의견 주시면 감사하겠습니다!
ㄴ `이래나 저래나 상관없다. 취향이다. 라고 말씀드리고 싶어요.`
> * 현재 Stepper를 누를때마다 값을 +, -하고 Label에 값을 바꿔준 뒤 인벤토리에 값을 바로 업데이트 해주는 방식입니다.
>   
>   * 혹시, 업데이트를 자주하는 방식이 아닌 Label 값만을 바꿔주다가 Dismiss될 때 최종값을 인벤토리에 업데이트 해주는게 좋은 접근인지 의견 주시면 감사하겠습니다!
ㄴ `동작에 문제 없다면 상관없을수도 있을 것 같아요.`

> * STEP 3 요구사항에 `ChangeInventoryViewController`에 네비게이션 컨트롤러를 사용하여 타이틀을 추가하고 버튼을 적용하도록 되어 있어서 사용하긴 했는데, 직접 뷰 컨트롤러에 Label과 버튼을 사용하는 방식대비 어떤점이 좋은지 잘 모르겠습니다. 이전 STEP을 진행하면서 화면전환 방식에 대해 고민했을 때에도 `재고수정`이라는 새로운 context를 만드는 것이라 생각하고 모달로 구현을 했는데 네비게이션 바를 사용하는 것에 대한 이점이 있을까요?
ㄴ `방식의 차이 or 기획의 차이 라고 말씀드리고 싶네요. 물론 어떨때 모달을, 어떨때 네비게이션을 쓰는지는 나뉘어져 있지만 이 프로젝트에서는 단순히 이점때문에 그렇게 구현하라고 나온건 아닌것 같아요 :) 지금은 무조건 이점이다 라고 할만한것도 없거나 별 차이 안나보여요.`

2022-09-13 13:30 UTC, SungPyo requested changes
컨플릭 해결 후 다시 PR주세요.
고생하셨어요.

2022-09-14 13:33 UTC, JaeKimdev commented on JuiceMaker/JuiceMaker/Controller/ChangeInventoryViewController.swift
> +    @IBOutlet weak private var mangoStepper: UIStepper!
ARC(Auto Reference Counter)에서 `weak`로 선언된 아울렛 변수는 참조해도 카운트가 증가하지 않고, 상호 (강한)참조를 통해 발생하는 retain cycle을 방지 할 수 있습니다.

약한 참조는 delegate, 상위 뷰컨트롤러에 대한 참조를 포함하는 하위 뷰, retain cycle을 방지하기 위해 사용됩니다.

애플의 [WWDC2015 - Implementing UI Designs in Interface Builder](https://developer.apple.com/videos/play/wwdc2015/407/) 영상에서는 “ In general you should make your outlet strong, especially if you are connecting an outlet to a sub view or to a constraint that's not always going to be retained by the view hierarchy. The only time you really need to make an outlet weak is if you have a custom view that references something back up the view hierarchy and in general that's not recommended. So I'm going to choose strong and I will click connect which will generate my outlet.” 일반적으로 `strong`을 사용하고 뷰 계층에서 뷰를 참조하는 경우에만 사용하라고 설명하고 있고, 

[Should Outlets Be Weak or Strong
](https://cocoacasts.com/should-outlets-be-weak-or-strong) 페이지에서도 애플에서는 `strong`을 권장하고 있다고 기술되어 있는데 관련한 애플의 문서는 찾지 못했습니다.

뷰 컨트롤러가 메모리에 올라가있는 동안 뷰 요소들도 모두 메모리에 올라가 있도록 강한 참조를 사용해야 합니다. `weak`인 경우 레이블의 텍스트를 변경하거나 버튼으로 사용자 상호작용을 하는 도중 nil 포인터 에러가 발생할 수 있다고 이해했는데요

제가 알아본 것처럼 기본으로 `strong`을 사용하고 필요한 경우 `weak`로 설정해주는 것이 좋을까요?
많은 웹 페이지들이 상반된 이야기를 하고 있어서 혹시 이부분 `웨더`가 조언해주실 부분이 있을지 문의드려요.

2022-09-14 13:37 UTC, FlameYG commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    static let store = FruitStore(initialFruitAmount: 10)
JuiceMaker에서 한번만 store로  FruitStore(initialFruitAmount: 10)을 가져와서 뷰컨트롤러에서 사용하면 좋을 것 같다라는 생각에 구현한 코드입니다...

그런데 스터디하다보니 싱글턴 디자인패턴을 알게 되어 아래와 같이 싱글턴 디자인패턴으로 변경하였습니다.
```swift
class FruitStore {
static let shared = FruitStore.init(initialFruitAmount: 10)
  
  var inventory: [Fruit: Int] = [:]
  private init(initialFruitAmount: Int) {
      Fruit.allCases.forEach { inventory[$0] = initialFruitAmount }
}
```

2022-09-14 13:44 UTC, FlameYG commented on JuiceMaker/JuiceMaker/Controller/ChangeInventoryViewController.swift
> +            return nil
`tag`를 사용하여 아래와 같이 코드 리팩토링해보았습니다.
추가로, 리팩토링해본 결과 전체적으로 태그를 사용하여 코드를 짰을 경우 코드의 직관성이 많이 떨어진다라고 생각이 되었습니다.
그러하여  태그를 사용하면 좋은 경우가 정확하게 언제인지 모르겠어서... 웨더에게 조언 좀 여쭙고자 합니다!

```swift
@IBAction private func setFruitStock(_ sender: UIStepper) {
      switch sender.tag {
      case 1:
          strawberryStockLabel.text = Int(sender.value).description
          juiceMaker.store.inventory[.strawberry] = Int(sender.value)
      case 2:
          bananaStockLabel.text = Int(sender.value).description
          juiceMaker.store.inventory[.banana] = Int(sender.value)
      case 3:
          pineappleStockLabel.text = Int(sender.value).description
          juiceMaker.store.inventory[.pineapple] = Int(sender.value)
      case 4:
          kiwiStockLabel.text = Int(sender.value).description
          juiceMaker.store.inventory[.kiwi] = Int(sender.value)
      case 5:
          mangoStockLabel.text = Int(sender.value).description
          juiceMaker.store.inventory[.mango] = Int(sender.value)
      default:
          break
      }
}
  
private func setFruitStepper(number stepper: Int) -> Array<UIStepper> {
      var fruitStepperArray:Array<UIStepper> = []
      
      for tagNumber in 1...stepper {
          guard let fruitStepper = self.view.viewWithTag(tagNumber) as? UIStepper
          else { break }
          fruitStepperArray.append(fruitStepper)
      }
      
      return fruitStepperArray
}
  
private func checkStepperValue() {
      var fruitStepper:Array<UIStepper> = setFruitStepper(number: 5)
      
      for fruit in Fruit.allCases {
          let stepper = fruitStepper.removeFirst()
          stepper.value = Double(juiceMaker.store.inventory[fruit] ?? 0)
      }
}
```

2022-09-14 13:52 UTC, JaeKimdev commented
안녕하세요~ 댓글 주신 내용 확인하고 드래곤과 함께 리팩토링 하였습니다.

수정사항으로는
- STEP 2에서 댓글 주셨던 얼럿 함수 `showSuccessAlert`, `showFailAlert`을 title과 messgage, 성공여부를 파라미터로 받아서 얼럿을 노출하는 하나의 `makeAlret`함수로 변경하였습니다.
- 전역으로 사용했었던 JuiceMaker의 `store`를 싱글톤 패턴을 적용하여 사용하도록 변경하였습니다.
- `ChangeInventoryViewController`에서 UIStepper @IBOutlet을 삭제하고 `tag`를 사용하도록 수정하였습니다.

먼저 달아주신 댓글에 `tag`와 `weak/strong 참조`관련하여 공부하고 이야기 해본 내용과 궁금한 내용 작성하였는데, 한번 읽어보시고 의견 주시면 감사하겠습니다.

2022-09-15 03:04 UTC, JaeKimdev commented on JuiceMaker/JuiceMaker/Controller/ChangeInventoryViewController.swift
> +    @IBOutlet weak private var mangoStepper: UIStepper!
추가적으로 찾아보고 참고한 문서입니다.
https://stackoverflow.com/questions/29421614/should-iboutlet-be-weak-or-strong-var

https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Outlets/Outlets.html

https://developer.apple.com/library/archive/documentation/General/Conceptual/Devpedia-CocoaApp/Outlet.html

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/MemoryMgmt.html#//apple_ref/doc/uid/10000011i

2022-09-16 18:10 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    static let store = FruitStore(initialFruitAmount: 10)
고생하셨습니다

2022-09-16 18:14 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ChangeInventoryViewController.swift
> +    @IBOutlet weak private var mangoStepper: UIStepper!
많이 찾아보셨군요.
이정도 공부했으면 다 하신거네요 :)
개인적인 의견을 좀 더하자면 IBOutlet의 경우는 strong이나 weak에 대해 이런저런 논의를 많이 했었습니다.
제 말이 무조건 맞다 할 수 없지만 저는 기본적으로 weak를 사용하고 많은 링크 올려주신것 처럼 
뷰를 삭제해야 하거나 하는 경우가 생기는 연결의 경우 weak를 제거합니다.
그 외에 weak를 사용할 수 없는 IBOutlet도 있는데 한번 알아보세요.

고생하셨습니다 .

2022-09-16 18:15 UTC, SungPyo approved these changes

2022-09-16 18:15 UTC, SungPyo approved these changes

2022-09-16 18:15 UTC, SungPyo approved these changes

2022-09-16 18:15 UTC, merged