쥬스 메이커 [STEP 3] inho, 토털이
yagom-academy/ios-juice-maker pull request #276
Opened 2022-09-13 03:04 UTC by inho-98

안녕하세요, @havi
토털이, 인호 입니다.

쥬스 메이커 프로그램 step 3 PR입니다!

## 고민했던 부분
#### 뷰컨트롤러 간에 데이터를 전달하는 방법
- `JuiceMakerVC`에서 `StockEditVC`로 넘어갈때는 두번째 뷰컨의 `fruitStock`프로퍼티에 접근하여 값을 전달합니다.
```swift
class StockEditViewController: UIViewController {
    var fruitStock = [Fruit: Int]()
    ...
}
    
class JuiceMakerViewController: UIViewController {
    ...
    Fruit.allCases.forEach({ fruit in
        guard let fruitStock = try? juiceMaker.fetchStock(of: fruit) else { return }
            
        stockEditVC.fruitStock[fruit] = fruitStock
    })
}
```
- `StockEditVC`에서 재고 수정을 마친 데이터를 `JuiceMakerVC`로 보낼때는 `delegate`을 이용합니다. 
```swift
protocol StockEditDelegate {
    func didEndStockEditing(fruitStock: [Fruit: Int])
}

class StockEditViewController: UIViewController {   
    var delegate: StockEditDelegate?
    ...
    @IBAction func dismissButtonPressed(_ sender: UIBarButtonItem) {
        delegate?.didEndStockEditing(fruitStock: fruitStock)
        dismiss(animated: true)
    }
    ...
}

extension JuiceMakerViewController: StockEditDelegate {
    func didEndStockEditing(fruitStock: [Fruit: Int]) {
        juiceMaker.updateAllStock(using: fruitStock)
        updateAllStockLabels()
    }
}
```
- `StockEditVC`에서 닫기 버튼이 눌렸을때 `delegate`의 메서드를 호출합니다. 
- `didEndStockEditing`의 메서드 내에서는 전달받은 데이터를 가지고 `fruitStock`과 과일 재고에 맞게 레이블을 업데이트 하는 메서드를 호출합니다.
- 위 두가지 방식을 이용한 이유는 아래 조언을 얻고싶은 부분에 같이 남겨두었습니다!
#### `StockEditVC` 내에서 정보 업데이트 방법(label, stepper)
- `JuiceMakerVC`에서 여러 버튼을 하나의 메서드에서 `tag`를 이용했던 방법과 달리 각 스테퍼에 메서드를 연결했습니다. 메서드 내에서는 스테퍼의 바뀌는 `value` 값을 `fruitStock`프로퍼티와 `fruitStockLable`에 바로 전달해줍니다.
```swift
@IBAction func strawberryStepperPressed(_ sender: UIStepper) {
    fruitStock[.strawberry] = Int(sender.value)
    strawberryStockLabel.text = Int(sender.value).description
}
```
#### 오토레이아웃 적용
- `StockEditVC`에서 오토레이아웃을 정할때, 각 과일의 이미지, 레이블, 스테퍼를 하나의 수직`stackView`로 만들고, 그렇게 만들어진 5개의 `stackView`를 하나의 수평`stackView`에 담습니다.
- `Ipod touch`기기에서 `stepper`의 요소가 잘리는 문제가 있었는데, 이를 해결하기 위해서
가장 포괄적인 수평`stackView`의 `width`를 safe Area 너비의 80% 이상으로 지정해서 
작은 화면에서도 요소가 잘리지 않도록 했습니다.

## 조언을 얻고싶은 부분
- Delgate를 공부하고 사용하다가 순환 참조 문제가 발생할 수 있다는걸 알게됐습니다. 어떤 상황에 순환참조가 일어나는지 알아보고 저희 코드와 비교해 보니, 저희 코드에서는 순환 참조가 일어나지 않는것 같습니다. 
Delegate을 사용했을때 순환 참조가 일어나는 경우는 두 뷰컨트롤러 내에서 서로를 프로퍼티로 참조하고 있을때 발생한다고 이해했는데, 저희 코드처럼 스토리 보드 ID로 접근하는게 아닌 직접 다음 뷰컨트롤러의 인스턴스를 프로퍼티로 받아오는 경우가 많은지 궁금합니다..!

- 위에서 고민한 내용대로, `JuiceMakerVC`에서 `StockEditVC`로 넘어갈때는 두번째 뷰컨의 `fruitStock`프로퍼티에 접근하고 `StockEditVC`에서 `JuiceMakerVC`로 데이터를 전달할 때는 `delegate`을 이용합니다.
처음에는 첫번째뷰에서 두번째로 넘어갈때에 `delegate`을 이용하려 했는데 실패한 이유가
두번째 뷰컨에서 첫번째 뷰의 `delegate`프로퍼티를 self로 받아야 하는 과정이 있는데, 두번째 뷰컨은 첫번째 뷰컨에서 `present`할때 메모리에 올라가서 `delegate`지정이 안되어 데이터를 전달할 수 없다고 이해했고, 현재 코드대로 프로퍼티를 이용했습니다.
그리고 검색했을때, 주로 두번째 뷰컨에서 첫번째 뷰컨으로 넘어올때 `delegate`을 이용한다는 내용도 있었는데 아마 위의 이유 때문이지 않을까 싶었습니다.
`delegate`를 이용한 해결 방법이 있는지, 아니면 지금 이해한 내용이 맞는지 궁금합니다..!!🤔

2022-09-14 12:52 UTC, havilog requested changes
조언을 얻고 싶으신 부분 설명드리자면,
어떠한 객체를 메모리에 올린 뒤에, 해당객체.delegate = self 로 지정하는 것은 일반적인 방법입니다!
그리고 첫번째 고민은.. 메모리 누수가 날 것 같은데 안나는건 잘 이해가 안되는 부분이네요 ㅠㅠ
확인 방법 공유해주시면 감사하겠습니다!

delegate와 메모리 누수에 관련한 내용을 리뷰에서 전체적으로 설명드리긴 힘들것 같고,
swift 공식문서에 strong reference관련된 자료가 있으니 한 번 찾아보시고 다시 얘기해보아요 ㅎㅎ

이 두 개념은 정말정말 중요한 개념이니 확실하게 이해하고 넘어가셨으면 좋겠습니다!

2022-09-14 12:52 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        })
제 생각에는 요 아이들은 `presentStockEditViewController`함수의 역할에 벗어나는 것 같아요!
`stockEditVC`의 프로퍼티에 직접 외부에서 접근하는 방식 보다는 stockEditVC을 생성하는 시점에 fruitStock자체를 넘겨주도록 해보는건 어떨까요?

2022-09-14 12:52 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
지금 구현에서는 문제가 없을것 처럼 보이는데요,
이렇게 작성하고 로직이 복잡해질 경우 JuiceMakerViewController과 stockEditVC의 재고가 달라질 수도 있을것 같아요 !
두 뷰컨이 같은 재고를 바라보고 있게 하는 방법도 생각해보시면 좋을 것 같아요 ㅎㅎ 
방법이 틀렸다는 이야기는 아닙니다!

2022-09-14 12:52 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/StockEditViewController.swift
> +    var delegate: StockEditDelegate?
음 제가 봤을 때는 메모리 누수가 생길것 같은데 .. 안생기나요?
조언받고 싶은 부분에서 이해하신대로 두 strong reference가 서로 참조하고 있을 경우 메모리 누수가 발생하는데, 이 부분은 스토리보드랑은 상관 없을 것 같아요.
어떻게 메모리 누수를 체크해보셨을까요?

2022-09-14 12:52 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/StockEditViewController.swift
> +    internal var fruitStock = [Fruit: Int]()
위에서 언급한 대로 fruitStock은 외부에서 접근하면 위험할거 같아요.
외부에서 의도치 않게 이 프로퍼티의 값을 바꿀수도 있을 거 같아서요!

2022-09-14 12:52 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +              let stockEditVC = stockEditNavigationController.topViewController as? StockEditViewController else {
저도 옛날에는 굳이 ViewController를 길게 안쓰고 줄여서 VC라고 썼었는데요 ㅎㅎ..
함수명이나 변수명은 길더라도 줄임말을 지양하고 최대한 명확하게 전달해주는게 좋을거 같아요!
요건 취향입니다 :)

2022-09-19 09:42 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        })
대화로 애기해주신 대로 `stockEditViewController`의 인스턴스를 만드는 시점에서 초기화 함수를 이용하였습니다!

다만, 뷰컨트롤러를 `init`을 사용하는 과정에서 에러가 많이 떠서 구글링을 참고하고 해결했는데,
코드가 무슨 의미인지 이해하지 못하고 사용한 부분이 있습니다..!🥲 (coder 과 requred init()부분입니다.)
```swift
init?(fruitStore: FruitStore, coder: NSCoder) {
    self.fruitStore = fruitStore
    super.init(coder: coder)
}

@available(*, unavailable, renamed: "init(fruitStore:coder:)")
required init?(coder: NSCoder) {
    fatalError("Invalid way of decoding this class")
}
```

2022-09-19 09:43 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
두 뷰컨이 같은 재고를 바라보도록 수정했습니다!

2022-09-19 09:43 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/StockEditViewController.swift
> +    internal var fruitStock = [Fruit: Int]()
`private`을 이용하고, 초기화 함수를 이용해서 값을 초기화하도록 수정했습니다!

2022-09-19 09:43 UTC, inho-98 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +              let stockEditVC = stockEditNavigationController.topViewController as? StockEditViewController else {
수정하였습니다!ㅎㅎ

2022-09-19 12:21 UTC, havilog approved these changes
두 분 모두 수고하셨습니다~!

2022-09-19 12:40 UTC, merged