쥬스 메이커 [Step3] Baem, Jeremy
yagom-academy/ios-juice-maker pull request #281
Opened 2022-09-14 13:38 UTC by yjjem

안녕하세요 @havilog !! 🥳
Step 3 완료하여 PR 보내드립니다. 이번 리뷰도 잘 부탁드리겠습니다 . 🙌
# 🤔 궁금한 점

### 1. 싱글톤과 KVO
KVO와 Singleton이 함께 쓰이는 경우도 있는지 궁금합니다.
재고추가 화면을 구현하면서 JuiceMaker내부에 FruitStore 인스턴스를 싱글톤으로 만들어 사용했습니다.
이 경우 "KVO가 무슨 소용인가?"라는 생각이 들었습니다. 
```swift
struct JuiceMaker {
    static let sharedStore = FruitStore()
   ...
 }  
```

### 2. subclass에서 superclass의 self
Alert의 재사용성을 위해 클래스 구현을 하던중에 UIAlertAction의 handler 설정시 ViewController 인스턴스를 직접 파라매터로 받아오지 않고 구현하기 위해서 무엇을 공부해야 하는지 궁금합니다.

### 3. 매개변수 활용
이 부분에서 저번 라이브리뷰 해주실때 매개변수로 넣어서 쓰면 좋을것 같다 하셔서 구현해 보았는데,
이렇게 쓰는게 방향성이 맞는지 궁금합니다.
```swift
func manageValue(of fruit: String, and label: UILabel, with sender: UIStepper) {
        label.text = Int(sender.value).description
        myStock.stock.updateValue(Int(sender.value), forKey: fruit)
}
```

2022-09-14 14:12 UTC, havilog requested changes
수고하셨습니다 ㅎㅎ
사실 이번 스탭에서 제가 제일 중요하다고 생각하는 부분은 화면간의 데이터 전달인데요,
데이터는 전달하는 방법에는 어떤 방법들이 있고, 어떤 경우에 사용하는지,
싱글톤으로 객체를 관리할 경우 장단점, delegate패턴은 어떻게 동작하고 왜 사용하는지, 객체간에 서로 강하게 참조하면 메모리누수가 일어나는데 이를 어떻게 해결할 수 있을지 등에 대한 충분한 고민이 있으면 좋을거 같습니다!
KVO, 싱글톤을 같이 사용하는 부분만 수정해주시면 감사하겠습니다 👍

2022-09-14 14:12 UTC, havilog commented on JuiceMaker/JuiceMaker/Model/Alerter.swift
> +            alertController.addAction(UIAlertAction(title: "Cancel", style: .default))
title과 message를 매개변수로 받아오는데, title에 값이 하드코딩 되어있네요?!

2022-09-14 14:12 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/StockEditorViewController.swift
> +    var myStock = JuiceMaker.sharedStore
KVO와 싱글톤을 같이 쓰시는지 질문 주셨는데, 싱글톤이란 앱에 하나의 객체만 두고 그 객체의 상태를 변경하는 패턴을 얘기해요. 그렇다면 싱글톤에 접근하는 모든 객체들은 같은 데이터를 공유하기 때문에 KVO가 필요 없겠죠?

2022-09-14 14:12 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        return present(alert, animated: true)
재사용을 위해 Alerter를 만드려고 도전하신 부분 좋습니다 💯 
하지만 제가 얘기드린 부분이랑 이해하신부분이 조금 다른거 같아요 ㅎㅎ
`func presentAlert(title: String, message: String, action: 액션들, on: 띄워줄 뷰컨)` 요런 식으로 함수를 정의한 뒤,
해당 함수 안에서 alert를 만드는 부분을 정의하실수도 있을거 같아요 ㅎㅎ
외부에서는 알러트에 대한 내용을 주입해주고,
알러트를 띄우는 함수, 알러트를 만드는 함수 이런 식으로의 분리를 말씀드린거였습니다!
지금도 충분히 잘하신거 같아요 ㅎㅎ

2022-09-14 14:12 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        mangoLabel.text = JuiceMaker.sharedStore.stock[Fruit.mango.rawValue]?.description
스트링 하드코딩 없애려고 노력하신 부분 좋습니다 💯 
다만 이렇게 될 경우 코드가 길어지는 문제가 있는데,
이 부분은 stock의 타입이 [String: Int]이기 때문에 나타나는것 같아요!
저번에 말씀드렸던 stock을 어떤 타입으로 정의할 것인가에 대한 해답이 나오면 코드가 개선 될 여지가 있을 것 같습니다 ㅎㅎ
지금도 충분합니다!!

2022-09-14 14:12 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/StockEditorViewController.swift
> +    func manageValue(of fruit: String, and label: UILabel, with sender: UIStepper) {
접근 제어자의 경우 그냥 default로 함수 정의하실 때 private func 로 정의하시고 외부에서 접근하실 일 있을 때만 접근제어자 변경하시는게 좋을 것 같아요!

2022-09-14 14:12 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/StockEditorViewController.swift
> +    func manageValue(of fruit: String, and label: UILabel, with sender: UIStepper) {
parameter의 이름이 fruit인데 String을 받고있네요 ㅎㅎ
`manageValue(of: .mango, label: mangoLabel, sender: sender)` 요런 식으로 쓸 수도 있을 것 같아요.
그리고 사실 label을 매개변수로 넘기는건 흔하지 않은 패턴인데요,
음 manageValue함수 안에서 받은 fruit에 따라 switch문으로 변경시켜줄 수도 있을거 같네요!

2022-09-15 09:05 UTC, yjjem commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        return present(alert, animated: true)
감사합니다 !! 😆

2022-09-16 02:55 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        mangoLabel.text = JuiceMaker.sharedStore.stock[Fruit.mango.rawValue]?.description
네 감사합니다!

2022-09-16 03:08 UTC, yjjem commented on JuiceMaker/JuiceMaker/Controller/StockEditorViewController.swift
> +    func manageValue(of fruit: String, and label: UILabel, with sender: UIStepper) {
아래와 같이 수정하였습니다 감사합니다 ! 👍
```swift
private func manageValue()
```

2022-09-16 03:11 UTC, yjjem commented on JuiceMaker/JuiceMaker/Model/Alerter.swift
> +            alertController.addAction(UIAlertAction(title: "Cancel", style: .default))
아래와 같이 Alerter 클래스 내부에 Ok 와 Cancel String 을 가지는 상수들을 정의하여 사용하도록 했습니다. 감사합니다 😆
```swift
            alertController.addAction(UIAlertAction(title: cancelButtonTitle, style: .default))
            alertController.addAction(UIAlertAction(title: okButtonTitle, style: .default)
```

2022-09-16 03:12 UTC, yjjem commented on JuiceMaker/JuiceMaker/Controller/StockEditorViewController.swift
> +    var myStock = JuiceMaker.sharedStore
KVO를 삭제하고 Singleton과 Delegate를 사용하도록 수정했습니다. 감사합니다 😊

2022-09-16 03:20 UTC, Dylan-yoon commented on JuiceMaker/JuiceMaker/Controller/StockEditorViewController.swift
> +    func manageValue(of fruit: String, and label: UILabel, with sender: UIStepper) {
그렇군요, label을 매개변수로 받는다는게 흔치않은 패턴인지는 처음알았습니다.
확인 후 변경했습니다.
또한 fruit 타입을 String -> Fruit 로 변경해 주면서
switch로 label값을 지정해 주었습니다. 
감사합니다!

2022-09-19 12:18 UTC, havilog approved these changes
두 분 모두 수고하셨습니다!
이번 프로젝트에서 delegate 패턴의 장단점과 singleton 패턴의 장단점만이라도 완벽하게 이해하셨길 바라며 어푸 드립니다~!

2022-09-19 12:18 UTC, havilog commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        StockEditorViewController.delegate = self
delegate의 경우 보통 static으로 들고있기 보다는 JuiceMakerViewController의 instance를 프로퍼티로 들고있는게 더 자연스러울 거 같아요!

2022-09-19 12:25 UTC, merged