쥬스메이커 [STEP 3] mangdi, rhovin
yagom-academy/ios-juice-maker pull request #283
Opened 2022-09-15 04:16 UTC by yuvinrho

@lina0322 

안녕하세요 엘림! 로빈, 망디 입니다. 😄
이번 스텝에서는 step2에서 개선한부분이 많습니다 이부분 감안해서 봐주시면 감사합니다😹
이번에도 아낌없는 조언 부탁드립니다!!🙏 

# 진행 단계 : Step 3
step2 코멘트 달아주신 내용도 포함하여 작성하였습니다.

## 🤔 코드를 작성할 때 고민되었던 점
- FruitJuice파일에서 각 주스가 재료를 딕셔너리 타입으로 갖게 수정하였습니다. 이렇게하면서 ingredientCount 프로퍼티를 삭제하였고, JuiceMaker에서 makeFruitJuice메소드를 아래와 같이 수정하였습니다.
```swift
var ingredients: [Fruits: Int] {
    switch self {
    case .strawberryJuice:
        return [.strawberry: 16]
    case .bananaJuice:
        return [.banana: 2]
    case .kiwiJuice:
        return [.kiwi: 3]
    case .pineappleJuice:
        return [.pineapple: 2]
    case .mangoJuice:
        return [.mango: 2]
    case .strawberryBananaJuice:
        return [.strawberry: 10, .banana: 1]
    case .mangoKiwiJuice:
        return [.mango: 2, .kiwi: 1]
    }
}
```

```swift
func makeFruitJuice(of fruitJuice: FruitJuice) throws {
        if !fruitStore.isFruitListStock(fruitJuice.ingredients) {
            throw JuiceMakerError.underFlowOfAmount
        }
        
        for (fruit, count) in fruitJuice.ingredients {
            try fruitStore.use(fruit, of: count)
        }
    }
```

- 화면을 전환할때 과일의 개수를 동일하게 띄울수 있는 방법을 고민했습니다. Notification을 이용해서 쥬스를만드는화면, 재고수정화면을 동일하게 과일수를 보일수있게 구현했습니다
- 아래 코드에서 fruitList값이 변경되면 알림을 보낼 수 있게 didSet에 설정하였습니다.
```swift 
struct FruitStore {
    private(set) var fruitList: [Fruits: Int] = [:] {
        didSet {
            NotificationCenter.default.post(
                name: Notification.Name("showFruitCount"),
                object: fruitList,
                userInfo: nil)
    }
}
```

- JuiceMakerViewController는 알림을 수신하면 현재 주스주문 화면의 과일개수들과 변경된 FruitList를 비교하여 어떤 과일이 변경됐는지 확인하고, 해당 과일에 맞는 개수레이블을 변경해주도록 하였습니다.

```swift
@objc func updateFruitCount(_ notification: Notification) {
        let currentFruitList: [Fruits: String?] = [
            .strawberry: strawberryCountLabel.text,
            .banana: bananaCountLabel.text,
            .pineapple: pineappleCountLabel.text,
            .kiwi: kiwiCountLabel.text,
            .mango: mangoCountLabel.text
        ]
        
        guard let changedFruitList = notification.object as? [Fruits: Int] else { return }
        
        for (fruit, count) in changedFruitList {
            if currentFruitList[fruit] != String(count) {
                updateCountLabel(fruit: fruit, count: count)
            }
        }
    }
```

## 🆘 조언을 얻고 싶은 부분 등 상세하게 작성
- 재고수정화면에서 과일, 개수레이블, 스탭퍼의 너비를 같게 설정하고 싶어서 스택뷰로 묶은다음에 스택뷰 alignment를 fill로 설정하였습니다.
- 화면을 이동해서 값을 전달하는방법으로 2가지를 떠올렸습니다. 
 첫번째로 세그를 이용하는방법을 썼습니다.
 prepare와 performSegue로 쥬스메이커화면에서 재고수정으로 넘어갈때 과일개수를 전해주고, 
 재고수정화면에서 닫기버튼을 누르고 돌아올때 delegate를 이용해서 수정된 개수를 다시 전달해주는 방법과,
 Notification으로 FruitStore의 fruitList에다가 센터를 달아놓고 값이 변경될때마다 쥬스메이커화면에 반영되게하는 방법중 어느방법이 더 좋을까 고민하다가 
 쉽게 구현할수있고, 단순한 방식인 Notification을 사용하게 되었습니다. 
 다만 Notification은 사용할수록 결합도가 높아지게 되는데 앞에 prepare와 performSegue,delagate를 사용하는방법보다 코드가 훨씬 간결하다는 이점이 있습니다. 
 저흰 아직 경험이 많지 않아서 어떤것을 쓰는게 전체적으로 이점이 좋은지 잘 모르겠습니다. 
 앞으로 데이터를 가지고 화면을 이동할때 어떤식으로 코드를 짜는것이 좋은지 엘림의 의견이 궁금합니다.

2022-09-16 12:34 UTC, lina0322 requested changes

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            object: nil)
```suggestion
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(updateFruitCount),
            name: Notification.Name("showFruitCount"),
            object: nil
        )
```
일단 이렇게 줄바꿈하는게 더 좋을거같고요!
이 부분 따로 함수로 주는건 어떨까요?

NotificationCenter으로 작업하신 것에 대한 의견은 아래쪽코멘트에 작성하였습니다!

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @objc func updateFruitCount(_ notification: Notification) {
접근제어자 붙일 수 있을 것 같아요.
항상 기본적으로 붙인다고 생각하시고 작업하시는걸 추천드려요!

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        ]
조금 더 디벨롭 해봅시다! 이 아이디어도 좋지만,
Fruit에서 label의 indentifier를 저장할수도있고, 
label을 배열로 연결하고 Fruit에 과일 번호를 저장해서 label에 순서대로 그 번호를 넣어준 다음 체크하는 것도 방법이겠어요.
언제 어디서든 과일에 관련된건 과일이 들고있고
과일 쥬스에 관련된건 과일 쥬스가 들고있는다고 생각해봅시다!

+ 추가로 아래 쪽 코멘트도 한번 확인해주세요!

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      }
```suggestion
         for (fruit, count) in changedFruitList where currentFruitList[fruit] != String(count) {
            updateCountLabel(fruit: fruit, count: count)
        }
```

함수 내 깊이를 줄이는 것 항상 고민해주세요!

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func updateCountLabel(fruit: Fruits, count: Int) {
updateFruitCount에서는 왜 이 함수를 활용하지 않았나요?？

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>          handleAlert(fruitJuice: fruitJuice)
주문을 하면 알람을 컨트롤하나요? 함수 명이 애매해진거같습니다.

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/ModifyFruitsStockViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
접근제어자 전체적으로 한번 체크해봅시다!

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/CustomStepper.swift
> +}
이건 뭘까요~?
커밋, PR 전후로 코드 확인 꼭 해주세요!

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                userInfo: nil)
버튼을 누를때마다 post를 보내면 다소 과하지 않을까요? 그리고 지금 로직상 하나의 과일 개수를 조정하거나 사용할때도 전체 데이터를 다 넘겨주고 있어서 다소 과해보여요. 이대로 유지한다면 과일 1~2개만 넘겨주는게 맞을 것 같고요.

지금 여러분이 `JuiceMaker.shared.fruitList`이렇게 싱글턴에 접근을 해서 사용하고 있거든요.
그럼 지금 사실상 첫 화면이랑 두번째 화면이 모두 싱글턴에 접근하고있고, 그러면 모두가 같은 값을 바라보고는 있는거네요!

음, 그래서 개인적으로는 이미 싱글턴에 접근하고 있기때문에 화면만 갱신하면 될거같은데 굳이 노티를 써야할까? 생각이 드네요!
noti는 1:1이 아니라 1:n으로 퍼지는건데, 지금은 화면이 2개라서 상관없지만 10개~20개가 있는 상황에서 그 모든 화면과 모델들에게 다 post가 갈거라서 다소 어색헤보이긴 했어요!
다만 여러분이 화면이 2개고 두 개 화면에 모두 접근하기위해서 선택한거라고 하신다면 틀리다고는 할 수 없겠네요.

관련해서 두분이 다시 한번 생각해보시고 의견 내주시면 더 좋겠어요!!

(사실상 모든 화면에서 값은 변해있어요. 화면에만 표시가 안되고 있는데 이걸 어떻게 할지 고민해보시면 좋을거같아요!)

2022-09-16 12:34 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                userInfo: nil)
이해가 안가실까봐 하나 더 남기자면, 싱글턴을 사용하고 계신 현재 상황에서는
세그나 딜리게이트로 서로 값을 넘겨줄 필요가 없다는 뜻이에요!!
싱글톤을 사용하신 이유가 분명히 있으셨을겁니다!🥲

만약에 세그나 딜리게이트(현재는 딜리게이트가 필요해보이지 않으나 작성하셨길래..)로 정보를 전달한다고 한다면
싱글턴을 사용하지 않는 쪽으로 해보세요~

2022-09-17 04:32 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            object: nil)
확인했습니다!

2022-09-17 04:33 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @objc func updateFruitCount(_ notification: Notification) {
넵 명심하겠습니다!

2022-09-17 07:58 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        ]
감사합니다 엘림!
Fruits에서 아래와 같이 `tagNumber` 를 지정하여 label을 배열로 연결하였습니다~
```swift
enum Fruits: CaseIterable {
    case strawberry
    case banana
    case pineapple
    case kiwi
    case mango
    
    var tagNumber: Int {
        switch self {
        case .strawberry:
            return 1
        case .banana:
            return 2
``` 
```swift
private func setFruitsCountLabelsTag() {
    for (index, label) in fruitCountLabels.enumerated() {
        label.tag = index + 1
    }
}
    
private func updateFruitCountLabel(by fruit: Fruits) {
    guard let label = view.viewWithTag(fruit.tagNumber) as? UILabel else { return }
    guard let fruitCount = JuiceMaker.shared.fruitList[fruit] else { return }
    label.text = String(fruitCount)
}
```

2022-09-17 07:59 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      }
😮for in에 where를 붙여서 저런식으로 써줄수있군요! 하나 알아갑니다 ㅎㅎ

2022-09-17 08:02 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>          handleAlert(fruitJuice: fruitJuice)
아래와 같이 handleAlert()를 order()로 수정하였습니다~

```swift
private func order(fruitJuice: FruitJuice) {
    let alert = UIAlertController(title: nil,
                                  message: nil,
                                  preferredStyle: .alert)
    
    do {
        try JuiceMaker.shared.makeFruitJuice(of: fruitJuice)
        updateFruitCountLabel(by: fruitJuice)
        showJuiceComeOutAlert(alert, fruitJuice: fruitJuice)
    } catch JuiceMakerError.underFlowOfAmount {
        showFruitsOutOfStockAlert(alert)
    } catch {
        debugPrint(error)
    }
}

```

2022-09-17 08:13 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Controller/ModifyFruitsStockViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
앗😂 접근제어자 항상 의식하며 코드 작성하겠습니다!

2022-09-17 08:21 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/CustomStepper.swift
> +}
저희가 스텝퍼 커스터마이즈를 위해 테스트로 파일을 만들었는데 지운다는 것을 잊어버렸습니다..😅 PR올리기 전 다시한번 확인하겠습니다. 감사합니다!

2022-09-17 08:23 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func updateCountLabel(fruit: Fruits, count: Int) {
위에 코멘트주신 내용들로 수정을 진행하다가 해당 함수는 지워버려서 어떤기능을 했었는가 까먹어버렸습니다..
해당 부분의 코드를 찾으려고 보는데 전체적으로 보이지않아서 확인하기가 어려웠습니다. 
혹시 해당 코드를 전체적으로 다시 볼수있는 그런 방법이 있을까요?

2022-09-17 08:41 UTC, yuvinrho commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                userInfo: nil)
다시 생각해보니깐 엘림 말씀대로 싱글톤을 사용하기 때문에 구지 노티픽케이션을 쓰지 않아도 된다는 것을 알았습니다.
이번 기회에 싱글톤의 사용에 대해서 다시한번 공부해 보았습니다. 감사합니다~~
최종적으로 노티피케이션을 삭제하고 싱글톤을 사용하여 레이블을 변경해주었습니다!

2022-09-17 09:00 UTC, MangDi-L commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                userInfo: nil)
아하 싱글턴을 사용하면 노티피케이션,세그,델리게이트 이런것을 쓸 필요가 없군요
반대로 싱글턴을 안쓴다면 세그,델리게이트로 구현이 가능하고 
세그랑 델리게이트만으로 구현이 가능하다는것을 알겠습니다! 
각자 장단점을 알게되어서  어떤식으로 사용해야하는지 잘 알게되는 계기가 되었습니다! 감사합니다 엘림

2022-09-20 12:07 UTC, lina0322 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
>      private func updateCountLabel(fruit: Fruits, count: Int) {
이전 커밋을 살펴보면 남아 있을겁니다! 혹은 엑스코드 내에서 지난 커밋과 비교할 수 있는데 방법 한 번 찾아보시고, 못찾으시면 말씀해주세요~!

2022-09-20 12:07 UTC, merged