쥬스메이커 [STEP01] 송준, Rowan
yagom-academy/ios-juice-maker pull request #285
Opened 2023-01-03 03:21 UTC by Kyeongjun2

@wongbingg
웡빙 안녕하세요!! 
4-1조 송준, Rowan JuiceMaker 첫 PR 보내드립니다 🙌
피드백 잘 부탁드립니다 🙏

### 고민한 점
#### Nested Type 사용

#### 재고 표현 방법
* class Fruit 
과일 인스턴스를 FruitStore에 생성 -> ```JuiceMaker.make```메서드에서 과일 프로퍼티에 접근하는 방법이 번거로웠습니다. 각각의 과일 프로퍼티에 접근할 때 배열을 사용해야하는 불편함이 있었습니다.
```swift=
class FruitStore {
    class Fruit {
        let name: String
        let stock = 10
        
        init(name: String) {
            self.name = name
        }
    }

    let strawberry = Fruit(name: "딸기")
    let banana = Fruit(name: "바나나")
    let kiwi = Fruit(name: "키위")
    let pineapple = Fruit(name: "파인애플")
    let mango = Fruit(name: "망고")

    func makeFruitsList() -> [Fruit] {
        let fruitsList = [self.strawberry, self.banana, self.kiwi, self.pineapple, self.mango]
        return fruitsList
    }

    func findFruit(fruitName: String) -> Fruit? {
        for i in 0..<makeFruitsList().count {
            if makeFruitsList()[i].name == fruitName {
                return makeFruitsList()[i]
            }
        }
    }
}
```
* dictionary
클래스를 사용하는 방법 외에 딕셔너리를 사용하는 방법을 고민해봤습니다. 그 결과로 가독성이 좋아졌습니다. 추가적으로 딕셔너리를 생성함으로써 만약 외부에서 새로운 품목을 추가할 때 위의 클래스 방식보다 수월할 것이라 생각됩니다.
또한, JuiceMaker ```make```메서드에서 ```Recipe``` 열거형 ingredients 연산 프로퍼티를 통해 ```subtractInventory```메서드의 parameter 전달이 수월해졌습니다.
```swift=
class FruitStore {
    var fruitsStock = ["딸기":10, "망고":10, "바나나":10, "키위":10, "파인애플":10]

    func subtractInventory(fruit: String, number: Int) throws {
        guard let selectedStock = self.fruitsStock[fruit],
              selectedStock - number >= 0 else {
            throw StockError.outOfStock
        }
        
        fruitsStock[fruit] = selectedStock - number
    }
    
    func addInventory(fruit: String, number: Int) {
        if let selectedStock = self.fruitsStock[fruit] {
            fruitsStock[fruit] = selectedStock + number
        }
    }
    
    func checkStock(fruit: String) {
            let resultMessage = "\(fruit)의 재고는 \(fruitsStock[fruit])개입니다."
}
```

### 조언을 얻고 싶은 부분
#### 이 코드에서 더 효율성을 낼 수 있는 방법이 궁금합니다!!
#### Magic Literal/Number 사용
```Dictionary``` key, value에서 (과일명, stock초기값)을 magic literal/number로 표현했습니다.
magic literal/number의 사용을 지양하라는 피드백이 자주 보여서 고민해봤는데 dictionary 또는 enum에 값을 할당할 때도 적용해주는게 좋을까요?
 
- *magic literal/number*
```swift=
var fruitsStock = ["딸기":10, "망고":10, "바나나":10, "키위":10, "파인애플":10]
```
- *열거체*
```swift=
enum fruit {
    static let strawberry = "딸기"
    static let mango = "망고"
    static let banana = "바나나"
    static let kiwi = "키위"
    static let pineappe = "파인애플"
}

```

2023-01-03 10:10 UTC, wongbingg commented
안녕하세요 송준, Rowan 쥬스메이커 프로젝트 step1 고생하셨습니다 ☺️

>저의 리뷰는 여러분과 함께 고민하는 과정입니다. 제가 드리는 피드백이 정답은 아니며, 여러분의 선택이 정답이 됩니다. 더 넓게 생각하는 자세를 가지고 제 피드백을 봐주셨으면 좋겠습니다 ☺️

### 고민한 점에 대하여

잘 수정해주신 것 같네요 ~! 과일 각각을 객체로 만들기 보단, 딕셔너리로 관리하는 것이 훨씬 간편하고 코드도 줄어서 가독성이 말씀대로 올라갔어요 👍

### 조언을 얻고싶은 부분에 대하여

현재 `fruitStock`의 타입은 `Dictionary<String, Int>` 가 되는데, 여기서 `Fruit` 열거형을 사용하게 되면 타입이 `Dictionary<Fruit, Int>` 가 되겠네요! (enum 타입의 이름도 대문자 카멜케이스로 작성합니다🧐) 저는 후자가 더 가독성 뿐만 아니라, 딕셔너리의 키값에 들어가게 되는 타입이 열거형으로 한정되어있어 `String` 이라는 넓은 범위보다 사용하기, 명시하기에 좋을 것 같다고 생각해요! 추가적으로 여유가 된다면 swift 에서 `String` 타입이 어떤 특성을 지니고 있는지, 성능에 어떤 영향을 미치는지 한번 찾아보시면 좋을 것 같아요

2023-01-03 10:36 UTC, wongbingg requested changes

2023-01-03 10:36 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  }
- ViewController에 코드를 작성 해주셨네요 ~! 어떤 ViewController인지 이름을 지어주면 좋을 것 같아요. 예를들어 홈화면을 담당한다면 HomeViewController 이런 식이에요!
- ViewController 안의 juiceMaker는 외부에서 접근 가능한 상태인데요, 외부에서 접근할 상황이 있을까요 ?
- 이 클래스가 상속될 가능성이 있을까요? 만약 그렇지 않다면 어떤 키워드로 이를 표현해줄 수 있을까요 ?

2023-01-03 10:36 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/Error.swift
> +}
에러타입 열거형을 잘 작성 해주셨네요 👍

2023-01-03 10:36 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
메서드명을 동사형으로 잘 작성해주셨네요 👍 다만, 네이밍의 의미가 인벤토리를 뺀다 라는 뜻으로 보여져서 조금 아쉬운 것 같아요 실제로는 과일을 빼주는 것이니 의미를 잘 전달할 수 있도록 네이밍을 수정해 볼까요 ? (이미 FruitStore라는 타입에서 인벤토리 라는 것은 확인할 수 있을 것 같아요!)

2023-01-03 10:36 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
이 부분에서는 전치사를 활용해서 argument label을 지정해주면 더 자연스러울 것 같아요.

2023-01-03 10:36 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
- 계산프로퍼티를 활용해서 음료 별 재료를 딕셔너리로 출력하도록 만드셨군요 ! 👍
- 해당 열거형에 들어있는 case들은 음료의 종류를 나타내는 것 같아요 ! `Recipe` 라는 네이밍이 적절한지 다시한번 생각해볼까요 ?

2023-01-03 10:36 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let songroFruit = FruitStore()
인스턴스화한 객체의 네이밍을 보면 어떤 종류의 과일을 나타내는 것 같아요~! 과일 창고라는 의미가 들어갈 수 있도록 네이밍을 해주면 좋을 것 같습니다 ☺️

2023-01-03 10:36 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitsStock = ["딸기":10, "망고":10, "바나나":10, "키위":10, "파인애플":10]
`FruitStore` 를 Class 로 , `JuiceMaker`를 Struct 로 만드셨는데 그 이유가 있을까요 ~?

2023-01-04 03:05 UTC, kimseongj commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  }
- 아직 어떤 화면을 담당할지 모르겠습니다 하하 만약에 홈화면을 담당한다면 HomeViewController가 되겠지만, 스토리보드에 ViewController가 있어서 일단 보류하겠습니다. 아직 뷰 구현을 하지 않았기 때문에 추후 고민해서 이름을 붙여보겠습니다!
- 쥬스메이커는 외부 접근이 필요없어 보입니다. 고로 private을 사용하여 외부 접근을 차단했습니다.
- ViewController는 저희가 생각했을 때 어플리케이션에서 하나의 화면을 담당하게 될텐데, 어플리케이션에 비슷한 화면이 현재는 필요하지 않을거라 생각되서 final키워드를 사용했습니다.

2023-01-04 03:06 UTC, Kyeongjun2 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
메서드 네이밍이 영문법적으로 이해되도록 메서드 이름과 parameter lable을 아래와 같이 수정해봤습니다!
```swift
func subtractStock(of fruit: Fruits, count number: Int) throws {
        guard let selectedStock = self.fruitsStock[fruit],
              selectedStock - number >= 0 else {
            throw StockError.outOfStock
        }
        
        fruitsStock[fruit] = selectedStock - number
    }
    
    func addStock(of fruit: Fruits, count number: Int) {
        if let selectedStock = self.fruitsStock[fruit] {
            fruitsStock[fruit] = selectedStock + number
        }
    }
```

2023-01-04 03:11 UTC, Kyeongjun2 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
전치사 of를 argument lable로 사용해서 메서드 의미를 자연스럽게 알 수 있도록 수정했습니다!
```swift
func checkStock(of fruit: Fruits) {
        if let stock = fruitsStock[fruit] {
            let resultMessage = "\(fruit)의 재고는 \(stock)개입니다."
            print(resultMessage)
        }
    }
```

2023-01-04 03:12 UTC, Kyeongjun2 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let songroFruit = FruitStore()
인스턴스 이름을 fruitStorage로 수정했습니다 👍

2023-01-04 03:14 UTC, Kyeongjun2 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
case에 음료 종류가 있다는 것을 나타낼 수 있도록 Recipe를 Juice로 수정하였습니다👍

2023-01-04 03:23 UTC, kimseongj commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitsStock = ["딸기":10, "망고":10, "바나나":10, "키위":10, "파인애플":10]
- ```FruitStore```클래스에 있는 ```fruitStock```프로퍼티가 ```FruitStore```내에 있는 메서드들에 의해 변경이 빈번합니다.  따라서 프로퍼티값을 수월하게 변경할 수 있는 클래스를 사용했습니다.
- ```JuiceMaker```구조체같은 경우는 ```FruitStore``` 인스턴스를 소유하고,  ```JuiceMaker``` 자체 프로퍼티는 사용하지 않기 때문에 구조체로 만들었습니다.

2023-01-05 05:34 UTC, wongbingg commented
코멘트에 대한 반영이 잘 되었네요 고생하셨습니다 송준, Rowan ☺️
이번스텝은 머지하도록 할게요! 다음 step 도 화이팅 입니다 👍

2023-01-05 05:34 UTC, merged