쥬스 메이커 [STEP 1] Harry, kokkilE
yagom-academy/ios-juice-maker pull request #286
Opened 2023-01-03 04:48 UTC by kokkilE

안녕하세요! @Judy-999
2-1조 쥬스 메이커 프로젝트의 Step 1 첫 PR을 보냅니다.
잘 부탁드립니다! 😃 

## 고민했던 점
### 싱글톤 (singleton)
- Step 1의 요구사항에 따라 JuiceMaker Class가 FruitStore Class의 인스턴스를 소유하도록 구현했습니다.
- FruitStore는 프로그램 내 하나만 존재해야 하고 실수로라도 여러 인스턴스가 생성될 경우 재고가 꼬일 수 있다고 생각하여 싱글톤을 적용하여 하나의 인스턴스만 존재하도록 했습니다.

### 파일 분리
- 열거형을 정의해 놓은 파일들을 어떻게 적절하게 나눌지 고민했습니다.
- 과일의 종류를 나타내는 타입
    - enum Fruit -> Fruit.swift에 작성
- 레시피 목록을 가지고 있는 타입
    - enum Recipe -> Recipe.swift에 작성
    - Recipe 타입은 각각의 주스 제조법 프로퍼티마다 [Fruit: Int] 딕셔너리를 가지고 있습니다.
- 에러 타입
    - JuiceMakerError, FruitStoreError -> JuiceMakerError.swift에 작성

### fruitStock 변수의 데이터 타입
fruitStock 변수가 과일의 종류와 (Fruit 타입) 재고 수량 정보 (Int 타입) 두 가지 정보를 저장하도록 정의하고자 했습니다.
- 딕셔너리 타입 사용 [Fruit: Int]
    - 데이터에 접근할 때 옵셔널 체크가 필요하다는 단점이 있습니다.

- 튜플의 배열 사용 [(Fruit, Int)]
    - 데이터에 접근할 때 숫자로 된 인덱스를 사용해야 한다는 단점이 있습니다.

- 튜플의 튜플 사용 ((Fruit, Int), (Fruit, Int), (Fruit, Int), (Fruit, Int), (Fruit, Int))
    - 데이터의 추가가 불가능하다는 단점이 있습니다.

딕셔너리 타입은 옵셔널 체크가 필요하다는 단점이 있지만, Fruit 타입을 키값으로 사용해서 직관적인 접근이 가능하다는 점에서 딕셔너리 타입을 채택했습니다.

## 조언을 얻고싶은 부분

### 에러처리 (옵셔널 바인딩)
```swift
func addStock(fruit: Fruit, quantity: Int) throws {
        guard let selectedFruitStock = fruitStock[fruit] else {
            throw FruitStoreError.invalidFruitInput
        }
        
        fruitStock.updateValue(selectedFruitStock + quantity, forKey: fruit)
    }
```
- 위 메서드를 예시로 `fruitStock[fruit]` 딕셔너리 값을 가져올때, 옵셔널 바인딩이 필요했습니다.
- 저 부분에서 `fruitStock`에서 인덱스로 `Fruit` 타입을 받고, 후에 버튼 입력으로 해당 메서드를 기능하게 한다고 가정했을때 저 부분에서 옵셔널 바인딩이 되지않아 에러를 던져주는 경우는 없을거라 생각이 됩니다.
- 따라서 guard let 을 통해 옵셔널 바인딩이 되지않을 경우 return 을 해주어 그냥 함수를 종료시키는 것이 맞을지, 아니면 저런식으로 일어날 가능성이 없는 에러를 던져주는 것이 맞는지 고민을 했습니다.
- 결론적으로 에러를 던져주는 식으로 처리를 했고 더 좋은 방법이 생각나지 않아 조언을 받고 싶습니다!

2023-01-03 12:24 UTC, Judy-999 requested changes
해리, 코낄이 수고하셨습니다 👏👏

콘솔 앱을 지나 UI를 가진 iOS 개발을 시작하신걸 축하드려요 🎉
고민한 점을 보니 해당 방식을 사용하는 이유를 생각하고 장단점 비교해서 선택하신게 보여서 아주 좋습니다 👍

리뷰 전 몇 가지 당부의 말씀을 드릴게요!
제가 질문드리는 점은 반드시 고쳐야 한다고 둘러서 말하는게 아니라 정말 궁금하거나 의견을 묻는 경우도 있으니 잘못된 점이라고 생각하시지 않으면 좋겠네요 🙂

저는 여러분의 코드를 평가하거나 잘못된 점을 지적하는 사람이 아닙니다! 같이 코드를 고민하는 역할로 더 좋은, 여러분의 이유가 있는 코드를 완성하는 데에 도움이 되면 좋겠습니다 🙌
<br>

## 조언을 얻고싶은 부분
### 에러처리 (옵셔널 바인딩)

> - 위 메서드를 예시로 fruitStock[fruit] 딕셔너리 값을 가져올때, 옵셔널 바인딩이 필요했습니다.
> - 저 부분에서 fruitStock에서 인덱스로 Fruit 타입을 받고, 후에 버튼 입력으로 해당 메서드를 기능하게 한다고 가정했을때 저 부분에서 옵셔널 바인딩이 되지않아 에러를 던져주는 경우는 없을거라 생각이 됩니다.
> - 따라서 guard let 을 통해 옵셔널 바인딩이 되지않을 경우 return 을 해주어 그냥 함수를 종료시키는 것이 맞을지, 아니면 저런식으로 일어날 가능성이 없는 에러를 던져주는 것이 맞는지 고민을 했습니다.
> - 결론적으로 에러를 던져주는 식으로 처리를 했고 더 좋은 방법이 생각나지 않아 조언을 받고 싶습니다!

만약에 새로운 과일을 추가하게 되면 어떨까요? 버튼과는 잘 연결했지만 `fruitStock`에 추가하는 과정을 까먹은 경우 단순히 `return`을 해버린다면 어떤 문제인지 파악하기 어려울 수 있습니다. 요구사항과 코드는 언제든 변경될 수 있기 때문에 ``"반드시 그럴 경우는 없다"`` 하고 단정지을 순 없습니다.

물론 위는 예시일 뿐이고 현재 프로젝트에서는 해리와, 코낄이의 생각대로 에러를 던지는 경우는 발생하지 않는다고 볼 수 있겠네요. 그렇다해도 에러를 던져서 `"이 흐름은 내가 의도한 방향이 아니다, 올바른 흐름이 아니다"`라고 표시하는 것이 협업하는 팀원과 미래의 내가 봤을 때 명확할 것 같네요 🙂

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  //
주석을 변경하셨네요! 꼼꼼하십니다 👍

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +}
과일 열거형 깔끔하고 좋네요 🍓

다만 주석과 코드가 너무 딱 붙어 있는 것 같은데 한 줄씩 개행해주면 좋지 않을까요 👀 
(Recipe, JuiceMakerError도 마찬가지입니다!)

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
`import Foundation`을 해두셨네요. 혹시 어떤 의미인지, 어떤 기능을 하는지 알고 계실까요?

열거형을 가진 파일들에서는 없는데 남겨두신 이유가 있으신지 질문드려요!
(JuiceMaker도 마찬가지입니다!)

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
메서드와 매개변수 이름으로 해석하면 `레시피가 저장되어(준비되어) 있다`로 해석될 것 같아요.
레시피가 저장되어 있다는 말은 좀 모호하게 느껴지는데 `레시피를 위한 ~`이 되도록 Argument Label을 추가해보시는건 어떤가요?

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
`fruitStore` 밖에서 접근이 필요할까요? 그렇지 않다면 접근보호를 하는게 좋아보이네요.

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +}
결국 주스를 만드는 과정에서 발생하는 에러들일텐데 굳이 나눠야할 이유가 있을까요? 🤔

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(recipe: [Fruit: Int]) throws {
`makeJuice`라는 네이밍이면 매개변수로 어떤 주스인지 와야할 것 같아요. 
아니면 마찬가지로 `"레시피로, 레시피를 이용해"`라고 해석할 수 있게 Argument Label를 활용해보세요!

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`isStocked`의 `currentStock < ingredient.value`와 `subtractStock`의 `selectedFruitStock >= quantity`가 같은 의미를 가지는 것으로 보이네요 👀

어차피 `subtractStock`를 수행하는 과정에서 과일이 적게 남았으면 에러를 보낼 텐데 `isStocked`를 따로 가져야하는 이유가 있을까요?

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
에러가 발생했을 때 단순히 어떤 에러인지 출력하기 보다는 어떤 상황인지 알려주는게 좋을 것 같아요.
각 에러에 따른 설명 값이 있으면 편리하게 출력할 수 있겠네요!

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Recipe.swift
> +}
case의 이름들로 봐서는 타입 이름은 **Juice**가 어울리지 않나 생각이 드네요. 고민해보세요~!

2023-01-03 12:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Recipe.swift
> +}
`static let`으로 각 주스들을 나타내셨네요. 
`case`를 사용하는 것과 어떤 차이가 있고, `static let`을 선택하신 이유는 무엇인가요?

2023-01-04 01:35 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +}
(+ 추가 코멘트)

`invalidFruitInput`이 어떤 의미인지는 알겠지만 너무 개발자 측면의 이름이 아닌가 싶네요. 결국 딕셔너리(과일 종류)에 없는 과일을 요청한 경우이니 `존재하지 않는 과일, 종류(재고)를 벗어난 과일, 잘못된 요청(주문)` 이런 이름은 어떤가요~?

2023-01-04 09:04 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +}
의견 반영하여 한 줄 개행하였습니다. 😄

2023-01-04 13:21 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
의견 반영하여 자연스럽게 읽히도록 전달인자 레이블을 추가하였습니다. 😄

2023-01-04 13:24 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
의견주신대로 Foundation이 필요없어서 삭제를 했습니다 !

2023-01-04 13:24 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +}
- 에러가 던져지는 파일 단위로 에러를 구분했었는데, 불필요한 구분이라고 생각하여 에러 타입을 하나로 통합하였습니다.
- `invalidFruitInput` 는 `nonExistentFruit` 로 변경하여 존재하지 않는 과일의 의미를 나타내도록 했습니다. 😄

2023-01-04 13:25 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
넵! 이부분도 저희가 생각하지 못한 부분인것 같습니다!
private 접근 제한자로 블록안에서만 접근 할 수 있도록 수정했습니다!

2023-01-04 13:28 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(recipe: [Fruit: Int]) throws {
Recipe 열거형 이름을 Juice로 변경했고,

전달인자 레이블을 통해 `어떤` 주스로 만드는 것이다 라는 것을 알 수 있게 수정하였습니다!
의견 감사합니다!!

2023-01-04 13:30 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`isStocked`의 `currentStock < ingredient.value` 는 주스를 만들 때 재고를 체크하고자 하는 의도이고,
`subtractStock`의 `selectedFruitStock >= quantity` 는 주스를 만드는 상황이 아닌, 다른 상황에서 재고의 변경이 있을 경우를 가정한 에러 처리였습니다.

그러나 현재 코드에서 재고의 감소는 오직 `makeJuice` 함수를 통해서 `isStocked`으로 재고 체크 후 발생하기 때문에, 
`selectedFruitStock >= quantity`는 불필요한 에러처리라고 판단되어 삭제했습니다.

2023-01-04 13:30 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
에러 출력에서 무슨 상황인지 알기 쉽도록 변경을 했고
그리고 이부분은 아까 라이브로 피드백주신것처럼 나중에 앱을 만들었을때 활용도가 높을 수 있도록
문자열을 리턴해주는 프로퍼티를 활용했습니다 !

2023-01-04 13:35 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Model/Recipe.swift
> +}
`static let` 을 사용하면 해당 타입 프로퍼티에 접근할 때 메모리에 생성되기 때문에 메모리 상 이점이 있고, 인스턴스를 생성하지 않고 접근이 가능하다는 장점이 있다고 알고 있습니다.

하지만 `static let`을 사용하여 각각의 프로퍼티를 딕셔너리로 정의하는 것 보단, `case`로 각각의 쥬스에 대하여 연산 프로퍼티로 처리하는게 가독성 측면에서 낫다고 생각하여 case로 변경하였습니다.

2023-01-04 23:29 UTC, Judy-999 approved these changes
잘 반영하셨네요! 다음 스텝도 화이팅입니다 🙌

2023-01-04 23:29 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMakerError.swift
> +    }
연산 프로퍼티로 하셨네요! 좋습니다 👍

2023-01-04 23:29 UTC, merged