쥬스메이커🧃 [STEP 1] 무리, 릴라, 세홍
yagom-academy/ios-juice-maker pull request #288
Opened 2023-01-03 07:12 UTC by juun97

# Juice Maker🧃 [STEP1] 무리, 릴라, 세홍
@llingo

안녕하세요 링고! 무릴라홍입니다! 
새해 첫 STEP1 PR보냅니다.
앞으로 3주간 잘부탁드립니다 :blush:~

## 고민했던 점 🤯
### 1️⃣ Fruits의 Initialize
```swift=
// 초반 작성 코드
class FruitStore {
    private var strawberry: Int = 10 
    private var banana: Int = 10
    private var pineapple: Int = 10
    private var kiwi: Int = 10
    private var mango: Int = 10    
}
```
- 처음 작성한 방향에서는 과일들을 각각의 프로퍼티로 `FruitStore` 에 생성하였으나 `JuiceMaker` 와 데이터를 주고 받는 과정에서 계속해서 switch문으로 어떤 과일인지 식별해줘야 하는 큰 번거로움이 있었습니다. 
- 이를 개선하기 위해 `Dictionary` 사용을 결정했습니다. 저희 조는 `Magic Number` 사용을 지양하기 위해 처음 Dictionary 각각의 Key(String)값의 Value(Int) 를 init()에 Value를 프로퍼티로 할당을 하려했으나 프로퍼티들이 `initialize` 되기전에는 할당을 할 수 없다는 에러가 발생해 다른 방법을 고민했습니다.

```swift=
 private(set) var fruits: [Fruit : Int] = [:]

 private init() {
        initializeDefaultStock()
    }
    
    private func initializeDefaultStock() {
        let defaultStock = 10
        for fruit in Fruit.allCases {
            fruits[fruit] = defaultStock
        }
    }
```
- 기존 `FruitStore`에 존재하던 프로퍼티들은 `Enum` 타입으로 새로 정의하고 `FruitStore` 내에서는 `Dictionary[Fruit : Int]`만을 프로퍼티로 갖게 수정했습니다. 또한 `initialize` 될 때 각각의 과일 일때의 `Value` 값에 접근하여 `default` 값인 10을 할당 해주었습니다.

### 2️⃣ 각 주스별 recipe
```swift=
// 초반 recipe 구현부분
enum Recipe {
        static let usingStrawberry = 16
        static let usingBanana = 2
// ...
        static let usingMixMango = 2
        static let usingMixKiwi = 1
    }

```
```swift=
// Nested 타입을 사용한 Juice타입 내 구현 부분
    var recipe: [Fruit : Int] {
        switch self {
        case .strawberryJuice:
            return [.strawberry : 16]
        case .bananaJuice:
            return [.banana : 2]
// ...
        case .strawberryBananaJuice:
            return [.strawberry : 10, .banana : 1]
        case .mangoKiwiJuice:
            return [.mango : 2, .kiwi : 1]
        }
    }
```
- 초반 **Nested Type**에 대해 알지 못하여 `Recipe`타입을 따로 정의하여 진행했습니다. 해당 과일쥬스에 `Int`값으로 소모되는 과일의 갯수는 할당해주었지만 **어떠한 과일인지** `Fruit`타입은 사용할 수 없었습니다.
- **Nested Type**과 딕셔너리를 사용하여 `recipe`마다 `Fruit`타입의 과일이 몇개 소모되는지를 구현할 수 있었습니다.

### 3️⃣ Singleton
- `class FruitStore` 같은 경우 처음 인스턴스화 되고 나서 그 인스턴스가 다른 인스턴스로 변경되는일이 있어서는 안된다고 생각했습니다. 재고를 관리하는 역할이었기 때문에 실수로 라도 새로운 인스턴스가 생성되어 값이 수정되어서는 안되기 때문에 단 하나의 인스턴스만을 보장하는 `Singleton` 패턴을 사용하게 되었습니다.

### 4️⃣ 오류처리
- 캠핑사이트에서 필요시 오류처리에 대한 부분을 throw, try-catch로 구현해보라고 안내되고 있습니다. 하지만 팀원 중 과반수 이상이 `Result`로 오류처리하는 방식을 써보지 않았고, 가독성이 좋다고 생각하여 `Result`로 사용해보았습니다!
- 오류를 던지는 부분과 받는 부분이 어느곳에 위치해야 하는가에 대한 고민을 해보았습니다. 팀원들과의 의견을 나눈 결과로 실제 과일의 재고를 체크하는 `FruitStore` 에서 오류를 던지고 Fruit 재고를 확인하는 함수를 사용하는 `JuiceMaker` 에서 오류를 받아내는 방향으로 코드를 작성 했습니다.

### 5️⃣ 은닉화
- 먼저 STEP1의 기능을 모두 구현한 후 접근 제어에 대해 고민을 해보게 되었습니다.
- `class FruitStore`의 `Dictionary fruits`의 경우 `private(set)`을 사용하여 외부에서는 읽기만 가능하도록했습니다.
- 또 `FruitStore`의 메서드 중 외부에서 접근할 필요가 없는 메서드는 `private`을 사용하여 은닉화하였습니다.

### 6️⃣ final class
- `class FruitStore`의 경우 상속을 받거나 상속을 하지 않기때문에 `final` 키워드를 사용해주었습니다.

---
## 조언을 얻고 싶은 부분 🙇🏻‍♂️
### 로직의 최적화
- 현재 저희 코드에서는 Dictionary로 어떤 과일인지와 얼마나 필요한지를 주고받고 있습니다. 이 과정에서 과일을 식별하는 과정이 필요했고 이 과정을 요구하는 모든 로직은 for 문과 옵셔널 바인딩을 통해 진행하였습니다. 혹시 더 간결한 로직이 있을지 다른 방향으로 생각할 수도 있는지 조언이 필요합니다.

2023-01-03 15:52 UTC, llingo requested changes
안녕하세요 무리, 릴라, 세홍
쥬스메이커 프로젝트 STEP 1 수고하셨습니다 :)

---

앞으로의 원활한 리뷰 진행을 위해 몇 가지 안내사항을 드리겠습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

---

**Q1. 로직의 최적화**
> 현재 저희 코드에서는 Dictionary로 어떤 과일인지와 얼마나 필요한지를 주고받고 있습니다. 이 과정에서 과일을 식별하는 과정이 필요했고 이 과정을 요구하는 모든 로직은 for 문과 옵셔널 바인딩을 통해 진행하였습니다. 혹시 더 간결한 로직이 있을지 다른 방향으로 생각할 수도 있는지 조언이 필요합니다.

A1. [Dictionary](https://developer.apple.com/documentation/swift/dictionary)에는 merging과 merge라는 메서드가 존재합니다. 이를 잘 활용하면 로직을 단순화할 수 있을 것 같아요. 필요 시 filter, map 같은 고차함수도 사용하면 최적화가 가능할 것 같아요.

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//  Created by 릴라, 세홍, 무리
주석을 변경하셨군요 좋습니다 👍

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private(set) var fruits: [Fruit : Int] = [:]
[P2] 딕셔너리 타입은 `[Fruit: Int]`이 더 좋을 것 같아요

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
싱글톤으로 FruitStore를 작성해주셨네요. 싱글톤으로 작성해주신 이유가 있을까요? 싱글톤을 사용 시의 장단점과 주의해야할 점에 대해 고민해보시는 것이 좋을 것 같습니다.

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func isStocked(recipe: [Fruit : Int]) -> Result<Bool, JuiceMakeError> {
Result 타입을 사용하셔서 값과 에러를 처리해주셨네요.

[P1] isStocked(recipe:)는 `recipe가 저장되어있나요?` 라는 뜻으로 읽히는 것 같습니다. Argument Label 사용하거나 네이밍을 변경해보면 좋을 것 같습니다  :)

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func useFruit(recipe: [Fruit : Int]) {
[P1] 위의 코멘트와 동일합니다. 
Argument Label을 사용하여 네이밍을 변경해보면 좋을 것 같습니다 :)

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +        }
[P1] 현재는 `[키 : 값]`으로 되어 있는데 `[키: 값]`의 형태가 되는 것이 좋을 것 같아요.

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var menu: String {
[P2] 현재 menu 프로퍼티는 Juice의 이름을 전달하는 역할을 하고 있는 프로퍼티인 것 같아요. 
네이밍은 외부에서 사용했을 때 이름만으로 해당 기능의 결과를 예상할 수 있어야합니다.

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMakeError.swift
> +    }
[P3] LocalizedError에 대해 알아보시면 좋을 것 같아요 :)

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore.shared
[P3] FruitStore는 클래스, JuiceMaker는 구조체로 작성해주셨는 데 이렇게 구현하시게된 이유가 있을까요?
클래스와 구조체는 면접 단골 질문이기 때문에 클래스와 구조체의 차이에 대해 한번 공부해보시면 좋을 것 같아요 :)

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) {
[P2] 현재는 네이밍이 `makeJuice(juice:)` 읽히는 것 같아요. 
Argement Label와 Swift Guidelines를 참고하셔서 네이밍을 변경해보면 좋을 것 같습니다

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
[P1] 실패보다는 성공했을 때가 위에 오는 것이 좋을 것 같아요. Result의 결과로 .success(let result)로 result 이름이 중복되는 것보단 다른 네이밍으로 작성하는 것은 어떨까요? 또한, case 사이에는 한칸 띄워주는 것이 가독성 측면에서도 더 좋습니다 :)

```swift
case .success(let result):
    return result

case .failure(let error):
    print(error.errorMessage)
    return false
```

2023-01-03 15:52 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func completeOrder(menu: String) {
[P1] `completeOrder(menu:)` 라는 이름과 실제 동작하는 것이 다른 것 같습니다. 
실제 동작은 출력하는 기능을 하는 것 같네요. 🤔

2023-01-03 15:52 UTC, seu0313 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +            return [.mango : 2, .kiwi : 1]
딕셔너리를 사용해서 레시피를 관리하는 방법 아주 좋네요 :)

2023-01-03 15:59 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore.shared
[P2] fruitStore를 외부에서 열람할 수 있는 것 같아요.

2023-01-04 10:00 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private(set) var fruits: [Fruit : Int] = [:]
피드백 받고 딕셔너리의 컨벤션을 다 수정 했습니다!

2023-01-04 11:02 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
`FruitStore` 클래스 같은 경우 재고 관리라는 명백한 목적이 있습니다. 만약 인스턴스가 새로 생성되어 교체되는 일이 생긴다면
이니셜라이저를 통해 재고들이 default 값으로 변경되는 일이 생길 수도 있습니다. 이를 방지하기 위해 단하나의 인스턴스를 보장해주는
`Singleton` 타입을 사용했습니다.

`Singleton`을 사용하게 되면 단하나의 인스턴스만을 생성하기 때문에 메모리를 아낄 수 있고` Singleton` 으로 만들어진 클래스의 인스턴스는 전역 인스턴스이기 때문에  외부에서도 쉽게 데이터를 공유할 수 있습니다.

하지만 쉬운 접근때문에 다른 클래스에서 무분별하게 접근을 하게되면 클래스의 인스턴스간 `의존성`이 높아질 수 있습니다.
또 찾아보니` 멀티 스레드` 환경에서 객체가 1개이상 생성되어 오류가 발생할 여지가 있을수도 있다고 합니다!

2023-01-04 11:04 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func isStocked(recipe: [Fruit : Int]) -> Result<Bool, JuiceMakeError> {
argument label 로 juiceIngredients 을 사용해 쥬스의 재료에 대한 재고가 저장되있는가 라는 뜻을 의도해 보았습니다!

2023-01-04 11:04 UTC, sehoong0429 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore.shared
fruitStore는 Class `Reference Type`입니다.
해당 클래스 내에서는 인스턴스가 변경되는 일이 있어선 안되기 때문에 let 으로 선언을 했습니다. let으로 선언이 되었기에 만약 struct 로 구현을 하게 된다면 과일재고 collection 인 fruits 의 내부 값 변경을 할 수가 없습니다. 그렇기 때문에 Class 로 구현을 했습니다.

Struct는 `Value Type` 이기 때문에 프로퍼티나 인스턴스 둘 중에 하나라도 let 으로 설정을 하게되면 프로퍼티의 값을 변경할 수 없습니다. 따라서 내부의 프로퍼티의 값을 변경할 일이 없는 JuiceMaker를 struct로 구현했습니다.

2023-01-04 11:05 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func useFruit(recipe: [Fruit : Int]) {
똑같이 juiceIngredients label을 사용했습니다!

2023-01-04 11:05 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +        }
수정했습니다 :) !!

2023-01-04 11:05 UTC, sehoong0429 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func completeOrder(menu: String) {
말씀해주신 부분대로 출력하는 의미를 담은 printCompleteMessage 로 변경하였습니다.

2023-01-04 11:06 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var menu: String {
두가지의 항목에서 고민을 많이 했습니다 returnJuiceName 과 name 인데 전자의 경우 메서드의 느낌이 나는거 같아 후자를 채택해 수정했습니다 링고의 생각은 어떠신가요??

2023-01-04 11:07 UTC, sehoong0429 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
성공케이스 실패케이스 순서를 바꿔서 진행했고, result -> verifiedValue 로 확인 된 값이라는 의미로 수정 해보았습니다!

2023-01-04 11:07 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/JuiceMakeError.swift
> +    }
팀원과 같이 스터디 진행 후 다음스텝에서 수정해보겠습니다 !

2023-01-04 11:07 UTC, sehoong0429 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) {
ordered 라는 전달인자 레이블을 추가하였습니다!

2023-01-04 11:08 UTC, sehoong0429 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore.shared
접근 제어자 private 을 사용하여 외부에서 열람할 수 없도록 수정하였습니다!

2023-01-04 13:57 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let shared = FruitStore()
좋습니다 👍

2023-01-04 14:16 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) {
[P2] `func makeJuice(_ juice: Juice)`는 어떠신가요? 현재는 `makeJuice(ordered:)`인 것 같아요

2023-01-04 14:20 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    var menu: String {
returnJuiceName보다는 name이 좋다고 생각합니다. 저도 전자의 경우 메서드 느낌의 네이밍인 것 같아요.

2023-01-04 14:31 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
juiceIngredients 는 너무 길다고 생각이 되네요 
```swift
func isStocked(juiceIngredients recipe: [Fruit: Int])
func useFruit(juiceIngredients recipe: [Fruit: Int])
```

아래와 같은 형태로 Argument Label을 사용하면 좋을 것 같아요 😄
```swift
func checkStock(forRecipe recipe: [Fruit: Int])
func useFruit(forRecipe recipe: [Fruit: Int])
```

2023-01-04 14:35 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(ordered juice: Juice) {
[P2] 위의 코멘트와 동일합니다!

2023-01-04 14:37 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let checkedStock = fruitStore.isStocked(juiceIngredients: juice.recipe)
isStocked 라는 네임이 ArgumentLabel를 추가하기 어렵게 만드는 부분이 아닌가 생각이 됩니다.
isStocked(juiceIngredients:)의 결과로 checkedStock가 나오는 것을 명확히 하기 위해
`func checkStock(forRecipe recipe: [Fruit: Int]` 는 어떤신가요? 😎

2023-01-05 04:08 UTC, sehoong0429 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
감사합니다! 말씀해주신 부분 참고하여 앞으로 적당한 길이의 네이밍을 할 수 있도록 해보겠습니다!

2023-01-05 04:09 UTC, sehoong0429 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let checkedStock = fruitStore.isStocked(juiceIngredients: juice.recipe)
감사합니다! 코멘트 해주신 부분 수정완료했습니다!

2023-01-05 04:18 UTC, llingo approved these changes
수고하셨습니다 :) 잘 수정해주셨습니다.
몇 가지 추가 피드백의 경우 다음 스탭에서 수정하셔도 될 것 같아요.
다음 스탭 PR 전에 코멘트 확인 부탁드립니다. :)

다음 스탭도 화이팅입니다. 🎉

2023-01-05 04:18 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +          print("주문하신 \(menu) 나왔습니다.")
한칸씩 줄이 밀린 것 같아요 다음 스탭에서 수정하면 될 것 같아요

2023-01-05 04:19 UTC, merged