쥬스메이커 [STEP 1] Goat, Broady
yagom-academy/ios-juice-maker pull request #289
Opened 2023-01-03 07:18 UTC by Goatt8

### 고민했던 점
* switch - case 구문을 통해 과일(fruit)과 차감하고싶거나 검증하고싶은 갯수(count)를 일일히 받아오는 과정이 필요했는데, 이를 딕셔너리 구조로 변경하므로써 불필요한 코드를 많이 줄였습니다.
* 영어 구문의 흐름대로 네이밍을 하는게 어려웠습니다. of 아규먼트 레이블을 사용하거나 _(언더스코어)를 이용해서 코드의 가독성을 높였습니다.

2023-01-03 10:43 UTC, wongbingg commented
안녕하세요 Goat, Broady 쥬스메이커 프로젝트 step1 고생하셨습니다 ☺️

>저의 리뷰는 여러분과 함께 고민하는 과정입니다. 제가 드리는 피드백이 정답은 아니며, 여러분의 선택이 정답이 됩니다. 더 넓게 생각하는 자세를 가지고 제 피드백을 봐주셨으면 좋겠습니다 ☺️

### 고민했던 점에 대하여

- 딕셔너리를 활용하여 코드 가독성을 높이고 불필요한 코드를 줄여주셨네요 👍
- 과일재고 1개를 감소시키는 메서드와 여러개를 감소시키는 메서드가 분리되어야 하는 이유가 있을까요 ?
- 나머지 부분에 대해서는 코멘트를 남겨두도록 하겠습니다 ☺️

2023-01-03 11:11 UTC, wongbingg requested changes

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
- ViewController 의 이름을 지어줘볼까요~? 어떤 역할을 하는지 현재는 알 수 없는 것 같아요 🧐
- 해당 class 가 상속될 가능성이 있을까요? 상속될 가능성이 없을 때 어떤 키워드 처리를 해줄 수 있을까요?

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
fruitBasket 에 접근제어자를 통해 외부에서 접근하지 못하도록 만드셨네요 👍

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
이니셜라이저에서 각 과일의 초기 재고값을 업데이트 해주는 로직이 들어가있네요! 👍 
파라미터 number라는 값이 어떤 값인지 아직은 명확히 알 수 없는 것 같아요. 구체적인 네이밍으로 수정해볼까요 ?

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
메서드의 네이밍을 잘 지어주셨네요 👍

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/Type.swift
> +    case mangoKiwiJuice
enum 타입을 잘 활용하셨네요 👍

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/Type.swift
> +    }
계산 프로퍼티를 이용하여 각 쥬스의 재료 딕셔너리를 반환하도록 구현하셨군요 👍
다만, 재료가 요구사항과 다르게 들어가있는 곳이 있어요! 확인 후 수정 해볼까요 ?

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
argument label을 잘 활용해서 네이밍을 해주셨네요 👍

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        reducedList.forEach{ fruitStore.reduceStock(of: $0.key, count: $0.value) }
```suggestion
        reducedList.forEach { fruitStore.reduceStock(of: $0.key, count: $0.value) }
```
중괄호의 시작 전, space를 해주는 컨벤션을 많이 따릅니다☺️ 공식문서의 여러 코드를 보시면 확인하실 수 있을거에요!

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
- `reduceOne(of fruit: Fruit)` 메서드와 `reduceStock(of fruit: Fruit, count: Int)` 메서드를 구분지어주는 이유가 있으실까요 ? 얼핏 봐서는 `reduceOne(of: Fruit)`와  `reduceStock(of: Fruit, count: 1)` 과 기능이 다르지 않아 보입니다 🥲
- `checkFruit(name: Fruit, count: Int) -> Bool` 메서드를 통해 현재 과일이 충분히 남아있나 확인해주는 것이군요 👍

2023-01-03 11:11 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore(number: 10)
JuiceMaker 를 구조체로, FruitStore를 클래스로 구현하신 이유가 있을까요 ~?

2023-01-04 01:16 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Model/Type.swift
> +    }
수정했습니다!

2023-01-04 01:18 UTC, Goatt8 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
* 현재는 주스를 만드는데 초점이 있는 뷰컨트롤러인거같아 JuiceMakeViewController 라는 이름으로 변경해봤습니다!
* 현재 step1까지 봤을때 class의 상속은 불필요해보입니다(?). 따라서 클래스앞에 final키워드로 상속될 가능성을 없앨 수 있을거 같습니다!

2023-01-04 01:29 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        reducedList.forEach{ fruitStore.reduceStock(of: $0.key, count: $0.value) }
수정했습니다!

2023-01-04 01:29 UTC, Goatt8 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
init 파라미터 네임은 -> initialStockNumber 로 과일재고들의 초기값을 나타낸다고 직관적으로 변경해봤습니다

2023-01-04 01:42 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
```swift
 func reduceOne(of fruit: Fruit) {
        guard let currentFruitCount = fruitsBasket[fruit],
              currentFruitCount >= 0 else {
            return
        }
        let reducedFruitCount = currentFruitCount - 1
        fruitsBasket[fruit] = reducedFruitCount
    }

func reduceStock(of fruit: Fruit, count: Int) {
        if let currentFruitCount = fruitsBasket[fruit] {
            let reducedCount = (currentFruitCount - count)
            fruitsBasket[fruit] = reducedCount
        }
    }
```
- reduceOne은 재고관리에서 (-)버튼을 통해 하나의 수량만 감소시키는 메서드이고, reduceStock은 주스를 만들때 이미 주스수량이 있는 것을 체크하고 count만큼 감소하는 함수입니다. 
- 두 개의 메서드가 reduce한다는 의미는 공통점이지만 호출되는 상황이 다르다고 생각했기 때문에 분리를 시켜줬습니다.

2023-01-04 01:47 UTC, Goatt8 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore(number: 10)
처음에 파일을 받을때 그렇게 구조가 짜여져있어서 일단 진행했는데..ㅎ 다음 스텝에서 class의 특징인 상속을 이용할 일이 생긴다면, 다시고려해보겠습니다!

2023-01-04 04:18 UTC, wongbingg commented
고생하셨습니다 ☺️ 이번 스텝에서 드린 코멘트에 대한 답변은 모두 받은 것 같네요 🧐
이번 PR 머지할게요 ~! 다음 스텝도 화이팅입니다 👍👍

2023-01-04 05:08 UTC, wongbingg commented
Goat, Broady 수정사항 모두 확인 했습니다 ! 고생하셨습니다. ☺️
재고를 하나씩만 추가/제거 하는 메서드를 따로 둔 이유가 있으셨군요 👍
이번 스텝 고생 많으셨습니다 다음 스텝도 화이팅 입니다 💪

2023-01-04 05:08 UTC, merged