쥬스메이커 [STEP1] 리지, kaki
yagom-academy/ios-juice-maker pull request #292
Opened 2023-01-04 01:29 UTC by kak1x

## STEP1 PR
@Judy-999
안녕하세요 주디! 첫 번째 PR 잘 부탁드리겠습니다🙂

### 고민했던 부분
- 지난 프로젝트에서는 첫 시작과 끝의 흐름을 다 알 수 있었는데, 이번 프로젝트는 전체적인 내용을 알 수 없어서 처음에 어떻게 시작해야 할지 고민이 많았습니다.
- 딕셔너리를 다루는 것에 익숙치 않아 관련 함수 부분 작성 시 어떻게 처리를 해주면 좋은지에 대해 많은 고민을 했습니다.
- 이번 미션에서 접근제어 학습내용이 있어 이를 적용해보고자 고민했습니다.

### 해결방법
- 흐름대로 연결하는것이 아니라 개념을 분리해서 생각해보았습니다. 예를 들어 FruitStore는 과일재고관리만 담당하고, JuiceMaker에서는 쥬스를 만드는 것만 담당하며 재고 관련해선 FruitStore의 기능을 사용하는 방식으로 분리하였습니다.
- collect type 공식문서에서 딕셔너리 부분을 공부하면서 코드에 적용해보았습니다. 
   - 쥬스 레시피 타입을 ```[Fruits: Int]```의 딕셔너리 타입으로 구현해서 [과일: 수량] 이런식으로 표현해보았습니다.
   - 과일의 재고를 표현하는 것도 마찬가지로 딕셔너리 타입으로 구현하여 빈 배열을 만들어 주었고 메서드를 통해 수량이 변경되도록 구현했습니다.
   - for문을 이용하여 딕셔너리에 접근하는것도 구현해보았습니다.
- 클래스 내부에서만 이용되는 저장 속성들에 private 키워드를 이용하여 은닉화를 진행해주었습니다
```swift
 private var fruitStocks: [Fruits: Int] = [:]
 private let initialStock = 10
```

2023-01-04 11:38 UTC, Judy-999 requested changes
## 리지, 카키 

리지, kaki 수고하셨습니다 👏👏

콘솔 앱을 지나 UI를 가진 iOS 개발을 시작하신걸 축하드려요 🎉

`FruitStore`와 `JuiceMaker` 각각의 역할을 고민하고 기능을 잘 분리하셨네요! 딕셔너리와 접근 제어도 신경쓰신게 보여 아주 좋습니다 👍

리뷰 전 몇 가지 당부의 말씀을 드릴게요!

제가 드린 코멘트에 댓글로 어떻게 반영하셨는지 또는 의견을 달아주시면 제가 수정사항을 파악하기 용이합니다. 만약 큰 의미가 없는 코멘트라면 이모지만 달아주셔도 됩니다! 만약 제가 드린 코멘트가 잘 이해가 안가신다면 언제든 DM 주세요~
그리고 PR과 마찬가지로 모든 수정을 마친 후 DM을 주시면 빠르게 확인하겠습니다.

제가 질문드리는 점은 반드시 고쳐야 한다고 둘러서 말하는게 아니라 정말 궁금하거나 의견을 묻는 경우도 있으니 잘못된 점이라고 생각하시지 않으면 좋겠네요 🙂 꼭 제가 추천드리는 방향으로 진행하지 않으셔도 되니 이유만 확실하게 알려주세요!

저는 여러분의 코드를 평가하거나 잘못된 점을 지적하는 사람이 아닙니다! 같이 코드를 고민하는 역할로 더 좋은, 여러분의 이유가 있는 코드를 완성하는 데에 도움이 되면 좋겠습니다 🙌

--- 

현재 `main` 브랜치에서 작업하시고 그대로 PR을 보내주셨는데 어렵지 않으시다면 스텝 별로 브랜치를 생성한 후 작업해보시기를 추천드려요~!

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +//  Created by riji, kaki.
주석을 변경하셨네요! 꼼꼼한 센스 😄

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  // 과일 저장소 타입
이미 작성되어 있는 주석이었겠지만 큰 의미 없는 주석은 남기지 않는게 좋습니다!

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private let initialStock = 10
```suggestion
class FruitStore {
    private var fruitStocks: [Fruits: Int] = [:]
    private let initialStock = 10
```

원래 한 줄 개행이 컨벤션인 걸까요~? 아니라면 맞춰주세요!

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
나중에 초기 개수를 변경하게 될 가능성을 생각하면 초기화할 때 개수를 넘겨받는 방법도 있겠네요.

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
단순히 `return`으로 처리하면 왜 `addStock`이 진행되지 않았는지 알기 어렵지 않을까요?
(`printStock`도 마찬가지입니다!)

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
메서드 이름으로 `print`는 어울리지 않는 것 같아요 👀
`재고 확인하기`와 같은 의미는 어떨까요?

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Fruits.swift
> +}
`CaseIterable`를 채택하신 이유는 무엇인가요?

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
메서드와 파라미터명을 잘 지었는지 확인하려면 메서드와 매개변수를 한 문장으로 읽었을 때 자연스러운지 생각해보면 됩니다!

그런 측면에서 `select`라는 레이블은 어색하게 느껴질 것 같아요. 이미 `makeJuice`라는 메서드명에서 `주스를 만든다`라는 의미가 전달되니 `makeJuice(.strawberryJuice)` 이렇게 되도록 생략하는 것도 좋아보이네요 🙂

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                try fruitStore.subtractStock(fruit: fruit, amount: stock)
`subtractStock(fruit: fruit, amount: stock)`
매개변수명과 전달하는 값의 이름이 `fruit`으로 반복되네요. 중복을 줄이고 의미를 확실하게 하도록 `~의`라는 Argument Label을 추가해도 좋겠네요~

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
해당 에러에 따른 설명을 바로 가져올 수 있으면 좋을 것 같아요!

2023-01-04 11:38 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMenu.swift
> +}
열거형과 연산 프로퍼티 모두 깔끔하고 좋네요 👍

2023-01-05 05:33 UTC, kak1x commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private let initialStock = 10
개행 수정하였습니다!

2023-01-05 05:33 UTC, yijiye commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
"알수 없는 오류" 와 같은 방법으로 처리하였습니다!

2023-01-05 05:33 UTC, yijiye commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                try fruitStore.subtractStock(fruit: fruit, amount: stock)
Argument Label 로 of 를 사용해보았습니다

2023-01-05 05:33 UTC, kak1x commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
코멘트를 참고하여 이니셜라이저에 파라미터로 initialStock을 받고, 파라미터의 기본값을 10으로 설정해주는 방식으로 변경하였습니다.

2023-01-05 05:35 UTC, yijiye commented on JuiceMaker/JuiceMaker/Model/Fruits.swift
> +}
enum 타입으로 정의한 과일의 종류를 배열처럼 활용하여 딕셔너리의 key 값으로 넣어주기 위해서 CaseIterable을 사용했습니다.

2023-01-05 05:36 UTC, yijiye commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
checkoutStock으로 수정하였습니다!

2023-01-05 05:37 UTC, kak1x commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
두 함수 모두 새로운 에러를 정의하여 에러를 던질 수 있는 함수로 변경하였습니다.
변경 중에 의문이 생겨 질문드립니다.
fruit는 Enum을 받는 파라미터여서 함수 사용 시  파라미터가 잘못되면 컴파일 에러가 발생할 것이고, 사용중에 에러를 던질 일은 없다고 생각되어 그냥 return 처리해주어도 문제가 없다고 생각되는데, 주디의 조언을 받고 싶습니다!

2023-01-05 05:39 UTC, yijiye commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
@Judy-999 
에러처리를 추가하는 과정에서 addStock과 subtractStock 메서드에서 try 구문을 사용하게 되었는데, 이렇게 표현하면 함수가 두가지 일을 하게 되는것 같습니다. 그런데 코드상에 봤을 때는 복잡하지 않아 이렇게 처리를 하였는데, do catch 구문을 두개로 표현하는게 더 좋은 표현방법일까요?

2023-01-05 06:22 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
`do catch 구문을 두개로 표현`하는 방법은 `makeJuice`에서 do catch를 두 번 하신다는 걸까요? 만약 ` checkOutStock`를 `makeJuice`에서 실행하시는건 좋지만 do catch는 한 번에 해도 될 것 같은데 고민해보시고 진행해보세요!
`
물론 함수는 하나의 기능만 하는게 좋습니다. 다만 이 경우는 아래와 같이 A, B 작업을 하던 코드를 B 작업을 다른 함수로 분리한 경우인데 그래도 역시 두 가지 작업을 하는건지 보는 관점에 따라 다를 것 같네요. 저는 개인적으로 괜찮다고 생각합니다.

```swift
func 함수() {
    // A 작업
    // B 작업
}

--> 기능 분리

func 함수() {
    // A 작업
    B함수()
}

func B함수() {
    // B 작업
}
```

무엇보다 궁극적으로 `checkOutStock`에 `fruit`과 같이 `fruitStock`도 함께 전달하면 에러가 발생할 일이 없겠네요 🙂

2023-01-05 06:24 UTC, Judy-999 approved these changes

2023-01-05 06:24 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Fruits.swift
> +}
지금보니 열거형 타입 이름이 `Fruits`였네요
타입 이름으론 복수형을 사용하지 않습니다! 다음 스텝에서 같이 수정해주세요~

2023-01-05 06:36 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
현재 코드에서는 `Fruits.allCases`를 이용해 모든 과일을 넣어주시고 계시니 해당 구문이 실행되진 않겠네요. 굳이 생각해보자면 요구사항이 수정되어 재고가 0이된 과일은 재고 목록에서 빼는 걸로 한다면 해당 에러가 발생할 수 있겠죠?! 요구사항과 코드는 언제든 변경될 수 있는거니까요! 예방해서 나쁠건 없죠 🙂

하지만 현재 코드에서 발생하지 않음을 확실히 알고 있거나, 해당 구문이 실행되도 별다른 조치를 취하지 않을 예정이라면 카키와 리지 생각대로 `return` 처리해주셔도 됩니다! 해당 부분을 인지하고 있고 `return`을 하는 이유만 확실하게 있으면 됩니다 👍

2023-01-05 06:36 UTC, merged

2023-01-05 07:08 UTC, kak1x commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
- 원래 코드에서 만약 substrachStock과 checkOutStock 두 함수의 기능을 분리했다면 makeJuice에서 try 를 두 번 사용해야해서 do-catch 구문을 두번 사용해야하는 것 같아서 드렸던 질문이었습니다! 혹시 이렇게 두 함수에서 에러를 던지는 경우에도 한 가지의 do-catch 구문에서 처리가 가능한가요??
- 마지막 부분이 잘 이해가 가지 않습니다 ㅠㅠ.. checkOutStock 메서드에 파라미터로 fruit과 같이 fruitStock도 함께 전달하면 에러를 발생시키지 않을 수 있다는 말씀이 맞으실까요??

2023-01-05 07:09 UTC, yijiye commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
```swift
 func makeJuice(_ juiceMenu: JuiceMenu) {
        let receipe = juiceMenu.receipe
        
        do {
            for (fruit, stock) in receipe {
                try fruitStore.subtractStock(of: fruit, amount: stock)
                try fruitStore.checkOutStock(of: fruit)
            }
        } catch JuiceMakerError.outOfStock {
            print("재고가 부족합니다.")
        } catch JuiceMakerError.fruitError {
            print("과일 선택 오류입니다.")
        } catch {
            print("알 수 없는 오류가 발생했습니다.")
        }
    }
```
질문에 대한 예시입니다!

2023-01-05 07:35 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
- 마지막 부분 말이 좀 모호했네요 😅

```swift
func addStock(of fruit: Fruits, amount: Int) throws {
        guard let fruitStock = fruitStocks[fruit] else {
            throw JuiceMakerError.fruitError
        }
    ....
}
```

이미 여기서 `guard let`으로 개수를 가져왔으니 해당 `fruitStock`를 같이 보내주면 또 다시 `checkOutStock`에서 `guard let`을 할 필요가 없을 것 같아서 드린 말이었습니다!

---

- do 안에서 여러 번의 try 던져서 에러 처리하는 방법 가능합니다!