쥬스메이커 [STEP2] 리지, kaki
yagom-academy/ios-juice-maker pull request #296
Opened 2023-01-09 08:45 UTC by kak1x

## STEP2 PR
@Judy-999 
안녕하세요 주디! 두 번째 PR 리뷰도 잘 부탁드리겠습니다~😄

### 고민했던 부분
- 화면 전환을 어떤 방식으로 진행해줘야 하는지 고민했습니다.
- 화면 전환 시 ViewController에 Segue를 연결해주면 Navigation Item을 사용할 수 없었기에 이 부분을 어떻게 해결해야 하는지 고민했습니다.

### 해결방법
- Segue를 설정한 뒤 segueIdentifier를 이용한 performSegue와 dismiss 메서드를 활용하여 화면 전환을 구현해주었습니다.
- Segue를 ViewController가 아닌 NavigationController로 설정해주어 문제를 해결하였습니다.

### 새로 알게된 내용

- ```singleton```을 사용하여 화면간 데이터를 공유하였습니다. 이때 저희가 만든 ```singleton``` 은```struct JuiceMake```로 정의를 하였는데, class가 아닌 struct에서 ```singleton``` 사용시 주의해야 되는 부분을 새로 알게되었습니다. 

```swift
struct JuiceMaker {
    static let sharedJuiceMaker = JuiceMaker()
    
    private init() {}
    
    private let fruitStore = FruitStore()
```
- 위와 같이 싱글톤을 정의해 주었고 이를 view controller에서 가져와 과일재고의 업데이트를 확인해주도록 구현했습니다.

```swift=
class ViewController: UIViewController {
    
    //var juiceMaker = JuiceMaker.sharedJuiceMaker
    func updateStockLabel() {
        strawberryStockLabel.text = JuiceMaker.sharedJuiceMaker.currentFruitStock(of: .strawberry)
   
    }
```
- 주석처리된 juiceMaker를 변수로 생성하면 JuiceMaker의 경우 struct이기 때문에 Copy On Write 방식에 의해 속성의 값이 변경될 경우 새로운 인스턴스의 주소값이 복사됩니다.
- 현재 코드에서는 struct JuiceMaker에 값이 변화하는 부분이 없어서 문제가 생기지는 않지만 만약 mutating 등으로 프로퍼티나 메서드가 변화하는 부분이 생기다면 이는 새로운 값이 복사되어 또 다른 인스턴스가 생성되는 문제가 발생할 수 있습니다.
- 이를 방지하고자 변수로 선언하는 부분을 만들지 않고 코드를 작성하였습니다.

2023-01-09 11:34 UTC, Judy-999 requested changes
리지, kaki 수고하셨어요 👏👏

이전과 다르게 UI 작업이 필요헤서 쉽지 않으셨을 텐데 잘하셨네요 👍
다만 코드 전반적으로 접근 보호도 잊지 말고 챙겨주세요 🙌

---

## 고민했던 부분 & 해결방법
> - 화면 전환을 어떤 방식으로 진행해줘야 하는지 고민했습니다.
> - Segue를 설정한 뒤 segueIdentifier를 이용한 performSegue와 dismiss 메서드를 활용하여 화면 전환을 구현해주었습니다.

고민하신 방법 중 다른 방법에는 어떤게 있었을까요? 어떤 이유에서 `performSegue` 방식을 선택하셨는지 궁금하네요!

## 새로 알게된 내용
> - 주석처리된 juiceMaker를 변수로 생성하면 JuiceMaker의 경우 struct이기 때문에 Copy On Write 방식에 의해 속성의 값이 변경될 경우 새로운 인스턴스의 주소값이 복사됩니다.
> - 현재 코드에서는 struct JuiceMaker에 값이 변화하는 부분이 없어서 문제가 생기지는 않지만 만약 mutating 등으로 프로퍼티나 메서드가 변화하는 부분이 생기다면 이는 새로운 값이 복사되어 또 다른 인스턴스가 생성되는 문제가 발생할 수 있습니다.

이런 문제가 있으면 사실 `Struct`로 **Singleton**을 구현하는게 맞을지 고민해보시면 좋겠어요. 
더불어 하나로 유지되어야 할 대상이 무엇인지도 같이 고민해보시면 좋겠네요 🙂
(왜 `JuiceMaker`는 Class고 `FruitStore`는 Struct로 구현됐는지 의미와 역할을 생각해보세요!)

그리고 화면 전환 시 데이터를 넘겨주는 다른 방법도 알아보시면 좋겠습니다 👍

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +
두 번째 뷰컨트롤러 보다는 해당 화면이 어떤 역할을 하는 화면인지 표현하는 이름이면 좋겠어요~!

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -
역시 `ViewController` 보단 의미있는 이름으로 변경하는게 좋겠네요 👀

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +    @IBAction func barButtonTapped(_ sender: UIBarButtonItem) {
어떤 barButton인지 이름에서 알 수 있음 좋겠네요!

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +    }
해당 메서드들은 외부에서 사용하나요!?

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`ddalbaJuiceButtonTapped` ~ `mankiJuiceButtonTapped`는 모두 주스만 다를 뿐 같은 동작을 하고 있네요. 
하나의 메서드로 합쳐보는건 어떤가요?

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func barButtonTapped(_ sender: UIBarButtonItem) {
역시 어떤 `barButton`인지 명시해주세요!

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +    }
\+ 이 메서드들 외에 모든 메서드들에 대해 외부에서 참조하는지 확인해보세요!

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let ok = UIAlertAction(title: "예", style: .default, handler: { action in self.performSegue(withIdentifier: "toSecondVC", sender: nil) })
```suggestion
        let ok = UIAlertAction(title: "예", style: .default, handler: { action in 
            self.performSegue(withIdentifier: "toSecondVC", sender: nil) 
        })
```

코드 한 줄이 너무 긴 느낌이 있는데 개행을 넣어도 좋을 것 같아요~

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let alert = UIAlertController(title: "\(name) 나왔습니다! 맛있게 드세요!",message: nil, preferredStyle: UIAlertController.Style.alert)
```suggestion
        let alert = UIAlertController(title: "\(name) 나왔습니다! 맛있게 드세요!",message: nil, preferredStyle: .alert)
```

참고로 타입이 명확하기 때문에 위처럼 타입명은 생략하고 사용가능합니다!

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitStocks: [Fruit: Int] = [:]
`final`을 사용하셨네요! 어떤 의미이고 왜 붙여주셨나요?

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitStocks: [Fruit: Int] = [:]
다른 클래스 중에도 붙여줄 곳이 없는지 생각해보시면 좋겠네요 👍

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
에러처리 위치를 고민해보시면 좋겠네요.
`makeJuice` 내부보다는 `makeJuice`를 시킨쪽에서 에러를 받는건 어떨까요 👀 고민해보세요!

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMenu.swift
> +    }
이름을 반환해주는 연산 프로퍼티 좋네요 👍
다만 사용할 때 `~~Juice.juiceName`이 되는데 **Juice**가 반복되네요 🤔

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>          }
에러 타입에도 연산 프로퍼티를 사용해서 각 에러마다 에러 설명을 반환하도록 하면 어떨까요~?

2023-01-09 11:34 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
주스를 만들면서 재고에서 `subtractStock`를 진행하면서 재고가 없을 때는 에러를 보내줄 텐데 따로 체크해주는 이유가 있을까요?

2023-01-10 01:47 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +
수정하였습니다!

2023-01-10 01:47 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> -
이 부분도 이름 수정하였습니다~

2023-01-10 01:48 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +    @IBAction func barButtonTapped(_ sender: UIBarButtonItem) {
manageStockBarButtonTapped 로 변경해주었습니다

2023-01-10 01:49 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +    @IBAction func barButtonTapped(_ sender: UIBarButtonItem) {
closeViewBarButtonTapped 로 변경해주었습니다

2023-01-10 01:49 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +    }
외부에서 참조하지 않는 메서드 및 프로퍼티를 확인하고 접근 제어 수정해주었습니다

2023-01-10 01:50 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
동일한 동작을 하나의 메서드(showsAlert)로 묶어주었습니다

2023-01-10 01:51 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func barButtonTapped(_ sender: UIBarButtonItem) {
manageStockBarButtonTapped 로 변경해주었습니다

2023-01-10 01:51 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let ok = UIAlertAction(title: "예", style: .default, handler: { action in self.performSegue(withIdentifier: "toSecondVC", sender: nil) })
네! 코드에 반영했습니다

2023-01-10 01:57 UTC, kak1x commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitStocks: [Fruit: Int] = [:]
더이상 상속을 하지 않는 class에 붙여주는 것으로 알고 있습니다.
ViewController 클래스들도 상속이 없다고 생각되어 final 키워드를 붙여주었습니다.

2023-01-10 01:58 UTC, kak1x commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>      }
makeJuice 내부가 아닌 makeJuice 메서드를 실행하는 쪽에서 에러를 처리하도록 수정하였습니다.

2023-01-10 02:01 UTC, kak1x commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
subtratStock만 사용할 경우 2가지 이상의 과일의 재고를 검사해야할때 문제가 발생하였습니다. 딕셔너리는 매번 랜덤하게 순서가 바뀌고 이 랜덤한 순서에 따라 재고가 부족한 과일을 먼저 검사하며 에러를 발생하고 종료가 되거나, 재고가 충분한 과일에서 먼저 재고를 감소시킨 이후 재고가 부족하다는 에러가 발생하게 되었습니다. 이에 대한 문제를 해결하기 위해 미리 재고를 검사하는 과정을 추가했습니다.

2023-01-10 02:03 UTC, yijiye commented
@Judy-999 
1. 고민하신 방법 중 다른 방법에는 어떤게 있었을까요? 어떤 이유에서 performSegue 방식을 선택하셨는지 궁금하네요!

- 스토리보드에 navigation controller가 하나 더 있어서 이 부분을 활용하려고 고민을 했었습니다. 그래서 첫번째 화면에서 다음 navigation controller로 연결하여 두번째 화면으로 이동하게 했고 이과정에서  스토리보드에서 활용하기 쉬운 Segue 방식을 선택했습니다. 
- 한가지 확실하지 않은 부분은 저희는 navigation controller 가 하나 더 있어서 연결을 시켜 뒤로가기 버튼을 navigation item으로 구현을 했는데 사실 버튼으로 해주어도 기능적으로는 다른 부분이 없다고 생각이 들었습니다. 그래서 이 navigation controller가 왜 굳이 두개가 있어야 하는지 정확한 의미를 파악하지는 못한것 같습니다. 🥲

2. 이런 문제가 있으면 사실 Struct로 Singleton을 구현하는게 맞을지 고민해보시면 좋겠어요.

- 한가지로 남아있어야 하는 부분은 과일재고라고 생각했습니다. 그래서 과일재고를 담고 있는 ```fruitStore```를 ```singleton``` 으로 구현하는게 맞다는 생각을 했습니다. 그런데, 만약 ```fruitStore```를 ```singleton```으로 구현한다고 하면 미션 1에서 요구하는 ```juiceMaker```가 ```fruitStore```를 가지고 있어야 한다는 요구사항에 어긋나는 거 같아서 바꿔도 되는건지 잘 모르겠습니다...!
- 다른 방법을 생각해보라는 말씀을 듣고 notification 을 사용해야하나 생각을 했는데 이 부분에 대한 주디의 의견을 듣고싶습니다!

2023-01-10 04:41 UTC, Judy-999 approved these changes
꼼꼼한 접근제어자 좋네요 👏👏

바로 머지 가능한 상태이지만 추가 코멘트 확인하시고 변경하고 싶으신 사항있으면 반영 후 알려주세요 😊

2023-01-10 04:41 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    }
공통적인 코드를 메서드로 분리한 점 좋습니다 👍

혹시 하나의 `@IBAction`에 여러 UIButton을 연결할 수 있다는 점을 아실까요?
동일한 로직이니 하나의 `@IBAction`로 처리하는 방법도 고민해보세요 🙂

2023-01-10 04:41 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    }
이 메서드는 `showsAlert`보다는 주스를 만드는게 주요 역할인 것 같아요 👀

2023-01-10 06:45 UTC, yijiye commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    }
[ac1d586](https://github.com/yagom-academy/ios-juice-maker/pull/296/commits/ac1d5864cdeab29c55a3d1a2bba394d9991d71f0)
네이밍 수정하였습니다!

2023-01-10 06:45 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    }
하나의 @IBAction으로 묶어서 처리해주었습니다!

2023-01-10 06:50 UTC, yijiye commented
[bd6699b](https://github.com/yagom-academy/ios-juice-maker/pull/296/commits/bd6699b6544e75c0bba5c3cb5532f2e12586f593)
singleton을 fruitStore로 변경하고 juiceMaker가 fruitStrore.shared를 갖도록 코드를 작성하였습니다. 이렇게 바꾸면 struct 인 juiceMaker를 새로운 인스턴스로 만들어도 재고에 접근하는 것은 heap영역에 있는 fruitStore로 접근하게 되니 값이 바뀔때의 위험성을 줄일 수 있다고 생각했습니다.
한가지 궁금한 사항은 주소값에 접근하기위해 singleton을 만들었는데 거기에 접근하려면 juiceMaker를 인스턴스로 만들어서 접근해야하니까 결국 juiceMaker의 값을 복사하는게 여러번이 생기는 것 같습니다. stack에 쌓이는 것은 앱이 종료되면 사라지니까 괜찮다고 생각하고 넘어가도 될까요...?🤔

2023-01-10 07:08 UTC, Judy-999 commented
> 한가지 궁금한 사항은 주소값에 접근하기위해 singleton을 만들었는데 거기에 접근하려면 juiceMaker를 인스턴스로 만들어서 접근해야하니까 결국 juiceMaker의 값을 복사하는게 여러번이 생기는 것 같습니다. stack에 쌓이는 것은 앱이 종료되면 사라지니까 괜찮다고 생각하고 넘어가도 될까요...?🤔

JuiceMaker의 인스터스를 한 번 생성해서 사용하는 것일 텐데 값을 복사하는게 여러 번 반복된다고 생각하시는 이유는 무엇일까요?

JuiceMaker의 인스턴스를 계속 생성하는게 걱정이시라면 한 번 생성한 후 화면 이동 시 계속 전달하거나 재고만 관련된 코드라면 바로 FruitStore의 shared로 접근하는 방식으로하면 될 것 같네요!

우선 이번 스텝은 머지하고 해당 사항은 고민해 보시고 정리하신 내용을 다음 PR에 같이 넣어주세요 🙌
수고하셨어요 👏👏

2023-01-10 07:08 UTC, merged