쥬스메이커 [Step2] Harry, kokkilE
yagom-academy/ios-juice-maker pull request #297
Opened 2023-01-09 08:49 UTC by HarryHyeon

@Judy-999
안녕하세요 주디!!
이번 리뷰도 잘 부탁드립니다 😄 

# 고민했던 점 & 조언을 얻고싶은 부분

## UI가 쥬스나 과일에 대한 정보를 가지게 할 수는 없을까?

### 1. 과일의 재고를 나타내는 레이블이 과일에 대한 정보를 가지지 않을때 있었던 문제
#### 변경전 코드
``` swift
func configureFruitCountLabels() {
        guard let strawberryCount = fruitStore.fruitStock[Fruit.strawberry],
              let bananaCount = fruitStore.fruitStock[Fruit.banana],
              let kiwiCount = fruitStore.fruitStock[Fruit.kiwi],
              let pineappleCount = fruitStore.fruitStock[Fruit.pineapple],
              let mangoCount = fruitStore.fruitStock[Fruit.mango] else {
            return
        }
        strawberryCountLabel.text = String(strawberryCount)
        bananaCountLabel.text = String(bananaCount)
        kiwiCountLabel.text = String(kiwiCount)
        pineappleCountLabel.text = String(pineappleCount)
        mangoCountLabel.text = String(mangoCount)
    }
```
- 과일 재고의 변경이 어떤 label에 연결되는지 코드상에서 알 수 없으므로 일괄적으로 모든 label들의 데이터가 다시 할당되어야 했습니다.

#### 변경 후 코드
``` swift
...
    fruitLabelsDictionary = [
                .strawberry: strawberryCountLabel,
                .banana: bananaCountLabel,
                .kiwi: kiwiCountLabel,
                .pineapple: pineappleCountLabel,
                .mango: mangoCountLabel
            ]
...

func configureFruitCountLabels() {
        for fruit in Fruit.allCases {
            fruitLabelsDictionary[fruit]?.text = fruitStore.getStockCountToString(of: fruit)
        }
}

func updateFruitCountLabels(juice: Juice) {
        for fruit in juice.recipe.keys {
            fruitLabelsDictionary[fruit]?.text = fruitStore.getStockCountToString(of: fruit)
        }
}
```
- 해결책으로 `[Fruit: UILabel]` 타입의 딕셔너리를 정의해서, 모든 레이블의 업데이트가 필요할 때는 `configureFruitCountLabels`을 호출하고, 쥬스를 만들어서 일부 과일의 재고가 변경되었을 때는 `updateFruitCountLabels` 을 호출하여 재고가 변경된 과일에 해당하는 label만 변경되도록 구현하였습니다.
<br>

---

<br>

### 2. 쥬스를 주문하는 버튼이 어떤 쥬스인지에 대한 정보를 가지지 않을때 있었던 문제

#### 변경전 코드
``` swift
func decideJuice(by sender: UIButton) -> Juice? {
        switch sender {
        case strawberryJuiceButton:
            return .strawberryJuice
        case bananaJuiceButton:
            return .bananaJuice
        case kiwiJuiceButton:
            return .kiwiJuice
        case pineappleJuiceButton:
            return .pineappleJuice
        case strawberryBananaJuiceButton:
            return .strawberryBananaJuice
        case mangoJuiceButton:
            return .mangoJuice
        case mangoKiwiJuiceButton:
            return .mangoKiwiJuice
        default:
            return nil
        }
    
    @IBAction func touchUpJuiceOrderButton(_ sender: UIButton) {
        guard let juice = decideJuice(by: sender) else { return }

        do {
            try juiceMaker.makeJuice(for: juice)
        } catch {
            presentOrderFailureAlert()
            return
        }
        presentOrderSuccessAlert(juice: juice)

        print(fruitStore.fruitStock)
    }
```

- 쥬스를 제조하는 7가지 버튼의 동작을 하나의 액션함수로 지정하다보니, 버튼마다 어떤 쥬스를 만들어야할지를 검사해 주는 로직이 항상 필요했습니다.
- 그래서 버튼이 버튼 나 자신이 어떤 쥬스를 만드는 버튼인지에 대한 정보를 모르기 때문에 어떤 쥬스를 만들어야할지 검사하는 부분이 매번 수행된 후에 쥬스 제조를 할 수가 있었습니다.
- 해결책으로는 UIButton을 상속받는 Custom Class를 만들어 저장 프로퍼티에 쥬스의 정보를 저장하는 방법을 고려했지만, 클래스를 정의하고 또 다시 해당 프로퍼티에 초기화를 해주는 작업이 **번거롭게 느껴졌습니다.**
<br>

#### 변경 후 코드
``` swift
func defineDictionary() {
        juiceButtonsDictionary = [
            strawberryJuiceButton: .strawberryJuice,
            bananaJuiceButton: .bananaJuice,
            kiwiJuiceButton: .kiwiJuice,
            pineappleJuiceButton: .pineappleJuice,
            mangoKiwiJuiceButton: .mangoKiwiJuice,
            mangoJuiceButton: .mangoJuice,
            strawberryBananaJuiceButton: .strawberryBananaJuice
        ]
    }
@IBAction func touchUpJuiceOrderButton(_ sender: UIButton) {
        guard let juice = juiceButtonsDictionary[sender] else { return }
        
        do {
            try juiceMaker.makeJuice(for: juice)
        } catch {
            presentOrderFailureAlert()
            return
        }
        presentOrderSuccessAlert(juice: juice)
        updateFruitCountLabels(juice: juice)
```
- 변경 후 바뀐 코드로 인해 매번 어떤 쥬스를 만들지 검사하던 `decideJuice()` 메서드가 사라지고,
딕셔너리로 바로 value 값을 받아 주문받은 쥬스를 제조하는 방식으로 변경되었습니다.
- 이렇게 처리하는 방법에서 더 좋은 방법이 있는지 잘 떠오르지 않아 주디의 생각은 어떨지 궁금합니다!

2023-01-09 14:04 UTC, Judy-999 requested changes
해리, 코낄이 수고하셨어요 👏👏

이전과 다르게 UI 작업이 필요헤서 쉽지 않으셨을 텐데 깔끔하게 잘하셨네요 🙌
다만 전반적으로 접근 제어 처리가 되어 있지 않아 고민해보시고 신경써주세요!

---

## 고민했던 점 & 조언을 얻고싶은 부분
### 1. 과일의 재고를 나타내는 레이블이 과일에 대한 정보를 가지지 않을때 있었던 문제
`Fruit`의 `allCases`와 재고 개수를 받아오는 메서드를 잘 활용하셨네요 👍

### 2. 쥬스를 주문하는 버튼이 어떤 쥬스인지에 대한 정보를 가지지 않을때 있었던 문제
버튼과 주스 간의 관계가 필요한데 딕셔너리를 활용하신건 좋은 방법 같습니다! 

이전의 `decideJuice`라는 메서드로 Switch 분기 처리하신 코드도 나빠보이진 않네요~
떠오르는 다른 방법은 Button에 tag라는 **Int** 값을 가지는 속성이 있는데 `IBAction` 메서드에서 `sender.tag`로 접근할 수 있어 `Fruit`이 **Int** `rawValue`를 가지면 바로 가져올 수 있겠네요! 하지만 버튼에 숫자를 지정하는 방식이라 숫자와 버튼의 연관이 없어 현재 방식이 좋아 보이네요 🙂

추가적으로 알려드리자면 IBOutlet들을 outlet collection으로 묶어서 사용할 수 있습니다. IBOutlet들을 Array 형식으로 관리하는게 편리한 코드라면 알아보신 후 사용해보세요!

2023-01-09 14:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
딕셔너리 정의 부분을 따로 메서드로 만드신 이유가 있을까요?

2023-01-09 14:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
같은 `present` 를 호출하셨는데 `self`를 붙이신건 다르네요! 통일해주시면 좋겠네요!

2023-01-09 14:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        present(alert, animated: true, completion: nil)
참고로 `completion`으로 처리할 코드가 없다면 아래처럼 생략 가능합니다~
```suggestion
        present(alert, animated: true)
```

2023-01-09 14:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +enum Fruit: CaseIterable {
`CaseIterable`는 어떤 이유에서 채택하셨을까요?

2023-01-09 14:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    var fruitLabelsDictionary: [Fruit: UILabel] = [:]
외부에서 사용될 일이 있을까요~?

2023-01-09 14:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    var fruitLabelsDictionary: [Fruit: UILabel] = [:]
이외에도 전반적으로 다른 프로퍼티와 메서드의 접근성을 살펴보시면 좋겠네요 🙂

2023-01-09 14:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        updateFruitCountLabels(juice: juice)
이렇게도 가능합니다 👍
```suggestion
        do {
            try juiceMaker.makeJuice(for: juice)
            presentOrderSuccessAlert(juice: juice)
            updateFruitCountLabels(juice: juice)
        } catch {
            presentOrderFailureAlert()
        }

```

2023-01-09 14:06 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
상속될 여지가 있는 클래스일까요? 
아니라면 상속되지 않음을 표시하는 키워드가 있으니 찾아보신 후 적용해보세요!

2023-01-09 14:10 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
storyboard에서 `withIdentifier`로 `UINavigationController`의 인스턴스를 가져오셨네요 👍

`UIViewController`가 아닌 `UINavigationController`를 가져오신 이유가 있으실까요?

2023-01-09 14:12 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
이외에 알고계신 화면 전환하는 다른 방법이 있다면 설명 부탁드려요 🙂
또한 다른 방법이 있다면 이 방법을 선택하신 이유도 같이 설명해주세요!

2023-01-10 01:34 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
의견 반영하여 통일했습니다. 😃

2023-01-10 01:35 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
viewDidLoad에  많은 양의 코드가 있으면 코드 읽기가 힘들거 같아 따로 메서드로 만들어 호출 해주었습니다 !

2023-01-10 01:36 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        present(alert, animated: true, completion: nil)
넵 사용하지 않는 컴플리션은 제거했습니다!

2023-01-10 01:36 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +enum Fruit: CaseIterable {
`Fruit` 타입 내의 모든 `case`를 for문으로 순회하기 위해 `CaseIterable`을 채택했습니다!
``` swift
private func configureFruitCountLabels() {
        for fruit in Fruit.allCases {
            fruitLabelsDictionary[fruit]?.text = fruitStore.getStockCountToString(of: fruit)
        }
}
```

2023-01-10 01:37 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    var fruitLabelsDictionary: [Fruit: UILabel] = [:]
코드 전체적으로 불필요한 접근을 하지 않도록 수정했습니다!

2023-01-10 01:38 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        updateFruitCountLabels(juice: juice)
의견 반영하여 수정하였습니다. 😃
`try` 구문에서 에러가 던져졌을 때와 그렇지 않을 때의 실행 구문이 더 가시적으로 구분된 것 같아요!

2023-01-10 01:38 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
뷰컨트롤러도 그렇고 FruitStore도 상속될 가능성이 없어서 final 키워드를 활용해보았습니다 !

2023-01-10 02:07 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
### 네비게이션 컨트롤러 인스턴스를 가져온 이유
- 일단 초기 프로젝트 구성에서 두 개의 뷰컨트롤러에 각각 네비게이션 컨트롤러가 달려있는 현재와 같은 형태였습니다.
- 2번째 화면 이후에 또 추가적인 화면이 다음 스텝에 있을 수도 있다고 생각하였습니다.
- 재고수정 화면은 첫번째 화면인 쥬스 주문하기 화면의 상세화면이 아니라고 생각하여 present 방식을 사용하게 되었습니다.  


### 화면 전환의 방법
- present : modality; 현재 화면에서 새로운 화면을 덮어씌움
- push : 내비게이션 컨트롤러에 뷰 스택을 쌓는 형태로 화면 전환
- segue
    - action segue : 스토리보드에서 지정하여 특정 action에 따라 세그가 실행되도록 화면전환 구현
    - manual segue(performSegue) : 세그에 Identifier를 부여하고 코드상에서 Identifier를 사용하여 메서드를 사용하여 화면전환 구현

2023-01-10 02:57 UTC, Judy-999 requested changes
모두 잘 수정해주셔서 바로 머지 가능하지만
이전에 놓친 코멘트들과 댓글에 대한 코멘트가 있어서 간단하게 수정하시고 답글 달아주세요 🙂

2023-01-10 02:57 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private let fruitStore = FruitStore.shared
`JuiceMaker `가 `fruitStore`를 들고있지 않나요?
따로 정의해서 사용할 필요는 없어보이네요!

2023-01-10 02:57 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/#naming)에 따르면 **"명료성이 간결함보다 더 중요하다."** 라고 합니다.

즉 `NC`와 같은 축약형은 지양해주시고 풀네임으로 사용해주세요!

2023-01-10 02:57 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
final을 붙이면 어떤 장점이 있을지도 나중에 같이 고민해보세요 👍

2023-01-10 02:57 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
앗 왜 아래와 같이 선언하시면서 바로 할당하지 않았는지 질문이었습니다!
그럼 값이 변경되지 않아 `let`으로 선언할 수 있을텐데요.

```swift
let juiceButtonsDictionary: [UIButton: Juice] = [
        strawberryJuiceButton: .strawberryJuice,
        bananaJuiceButton: .bananaJuice,
        kiwiJuiceButton: .kiwiJuice,
        pineappleJuiceButton: .pineappleJuice,
        mangoKiwiJuiceButton: .mangoKiwiJuice,
        mangoJuiceButton: .mangoJuice,
        strawberryBananaJuiceButton: .strawberryBananaJuice
    ]
```

> 힌트를 미리 드리면 위와 같은 코드는 불가합니다. 직접 해보시고 왜 그런지, 해결하려면 어떤 방법이 있을지도 알아보시면 좋겠네요 🙂

2023-01-10 03:02 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
앗 왜 아래와 같이 선언하시면서 바로 할당하지 않았는지 질문이었습니다!
그럼 값이 변경되지 않아 let으로 선언할 수 있을텐데요.

```swift
let juiceButtonsDictionary: [UIButton: Juice] = [
        strawberryJuiceButton: .strawberryJuice,
        bananaJuiceButton: .bananaJuice,
        kiwiJuiceButton: .kiwiJuice,
        pineappleJuiceButton: .pineappleJuice,
        mangoKiwiJuiceButton: .mangoKiwiJuice,
        mangoJuiceButton: .mangoJuice,
        strawberryBananaJuiceButton: .strawberryBananaJuice
    ]
```

> 힌트를 미리 드리면 위와 같은 코드는 불가합니다. 직접 해보시고 왜 그런지, 해결하려면 어떤 방법이 있을지도 알아보시면 좋겠네요 🙂

2023-01-10 03:02 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
final을 붙이면 어떤 장점이 있을지도 나중에 같이 고민해보세요 👍

2023-01-10 03:09 UTC, HarryHyeon commented
> Button에 tag라는 Int 값을 가지는 속성이 있는데 IBAction 메서드에서 sender.tag로 접근할 수 있어 Fruit이 Int rawValue를 가지면 바로 가져올 수 있겠네요! 하지만 버튼에 숫자를 지정하는 방식이라 숫자와 버튼의 연관이 없어 현재 방식이 좋아 보이네요 .
> 추가적으로 알려드리자면 IBOutlet들을 outlet collection으로 묶어서 사용할 수 있습니다. IBOutlet들을 Array 형식으로 관리하는게 편리 한 코드라면 알아보신 후 사용해보세요!

의견 감사드립니다 주디 ! 저희도 두가지 방법 다 생각해보았는데요 버튼에 직접 숫자를 부여하는 것이 뭔가 어색해보여서 딕셔너리로 버튼의 속성을 주는방법을 택했습니다.

2023-01-10 03:12 UTC, kokkilE commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    private let fruitStore = FruitStore.shared
`fruitStore` 는 싱글톤 패턴을 적용하여 어떤 방식으로 사용해도 동일한 인스턴스를 참조하기 때문에 상관이 없다고 생각했고,
`juiceMaker.fruitStore.` 로 접근하는것보다 `fruitStore.` 로 접근하는것이 편하다고 생각하여 따로 정의하였습니다.

2023-01-10 05:01 UTC, HarryHyeon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
넵 의견 반영하여서 수정했습니다 ~

2023-01-10 05:15 UTC, Judy-999 commented
수고하셨어요 👏👏 다음 스텝도 화이팅입니다 😊

2023-01-10 05:15 UTC, merged