쥬스메이커🧃 [STEP 2] 무리, 릴라, 세홍
yagom-academy/ios-juice-maker pull request #301
Opened 2023-01-10 00:58 UTC by juun97

@llingo 링고 무릴홍 스텝2 PR 올립니다 🙇🏻‍♀️🙇🏻‍♂️🙇🏻‍♀️
이번에는 활동학습때 새로배운걸 적용해보는 쪽에 시간을 많이 써봤습니다!

## 고민했던 점❓

### 1️⃣ 화면전환의 오류
- 쥬스 만드는 화면에서 재고수정 버튼을 누르면 아래와 같은 오류가 떴습니다.
- >Thread 1: "Storyboard (<UIStoryboard: 0x60000232ea00>) doesn't contain a view controller with identifier
- 스토리보드에서 연결을 시켜주었다고 생각했는데 오류를 보니 뷰컨트롤러의 identifier가 설정되어있지 않아서 발생하는 오류였습니다. 스토리보드에서 `Storyboard ID`를 설정해주니 오류가 사라지고 정상적으로 작동하는 모습을 볼 수 있었습니다.

### 2️⃣ 버튼 액션함수의 재활용
- 쥬스를 만드는 버튼이 쥬스의 종류만큼 있었기에 기존대로 하려면 7개 각각에 해당하는 액션을 다 작성해야 했습니다. 하지만 코드를 작성하던 중 쥬스를 만드는 기능은 다 똑같고 쥬스의 종류만 달라지는건데 액션하나를 공유해서 같이 쓰는 방법은 없을까 고민을 해봤습니다.

<img width="400" alt="image" src=https://i.imgur.com/yCm4ttE.png> 

</br>
</br>

- 각 버튼의 `Restoration ID` 를 해당 쥬스의 이름으로 설정해 액션함수의 매개변수인 sender로 접근해 해당 이벤트를 보낸 인터페이스 객체가 무엇인지 식별한 뒤 각각의 쥬스에 맞는 함수를 불러와 작동했습니다.

```swift
@IBAction func makeJuiceTapped(_ sender: UIButton) {
        let juiceMaker = JuiceMaker()
        
        guard let senderID = sender.restorationIdentifier else { return }
        switch senderID {
        case "OrderStrawberryBanana":
            juiceMaker.makeJuice(.strawberryBananaJuice)
        // ....
        case "OrderMangoKiwi":
            juiceMaker.makeJuice(.mangoKiwiJuice)
        default:
            return
        }
    }
```

## 조언을 얻고싶은 부분

### 1️⃣ 코드의 정리
- 함수의 갯수가 점점 많아지면서 코드의 가독성이 떨어지는 걸 느꼈습니다. 기능에 따라 함수의 정의 위치를 조정을 해보고자 했습니다. 서로 영향을 미쳐 연관이 있는 함수끼리 일단 붙여봤는데, 적절하게 코드의 위치를 관리하는 방법의 조언이 필요합니다!

### 2️⃣ NotificationCenter Observer를 등록하는 위치
- 팀프로젝트 시작 전에 구현해야할 기능과 네이밍에 대한 고민을 잠깐 하는 시간이 있었는데 Observer를 두는 위치에 대해 팀원들의 의견이 달랐습니다. Model에 가까이 두고싶다는 의견과 View Controller에 두는게 맞지 않을까하는 의견이 둘 다 나왔습니다.
- Model에 두고싶다는 의견은 Model은 데이터의 관련된 작업만 해야한다고 생각했고, View의 영역( ex. 인터페이스를 건드리는)은 건드리면 안된다고 생각했습니다.
- View Controller에 두고싶다는 의견은 "`Observer`에 의해 바뀌는 값이 표시되는건 View에서 표시되기때문에 View Controller에 두어도 상관이 없을것같다" 였습니다.
- Observer의 위치에 대해서 링고는 어떻게 생각하시나요?

### 3️⃣ Restoration vs Accessibility

<img width="300" alt="image" src=https://i.imgur.com/f6kP15A.png> 

- sender의 프로퍼티에서 식별자를 접근하던 중 두가지 항목이 있었던걸 발견했습니다
`Restoration ID` 와 `Accessibility Identifier` 가 있었는데, 이 두가지의 사용하는 곳이 다른걸 까요? 어떨때 어떤 것을 사용해야하는 건지 조언이 필요합니다!

2023-01-10 11:56 UTC, llingo requested changes
안녕하세요 무리, 릴라, 세홍
쥬스메이커 프로젝트 STEP 2 수고하셨습니다 :)

---

> 안내사항은 참고용으로 남겨두었습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

---

**Q1. 코드의 정리**

> 함수의 갯수가 점점 많아지면서 코드의 가독성이 떨어지는 걸 느꼈습니다. 기능에 따라 함수의 정의 위치를 조정을 해보고자 했습니다. 서로 영향을 미쳐 연관이 있는 함수끼리 일단 붙여봤는데, 적절하게 코드의 위치를 관리하는 방법의 조언이 필요합니다!

A1. 서로 연관있는 함수끼리 붙여주셨습니다. 
1. 주석을 통해 구분해주는 방법
2. Extension을 통해 관련 함수끼리 묶어서 분리해주는 방법
3. 기능이 많이 추가되는 경우 파일을 분리하여 2번을 사용하는 방법

현재 프로젝트 단계에서는 주석을 활용해서 구분해주는 것이 좋을 것 같네요.

```swift
// 주석
// MARK: 마크 주석
// MARK: - 마크 주석 + 구분선
```


**Q2. NotificationCenter Observer를 등록하는 위치**

> Observer의 위치에 대해서 링고는 어떻게 생각하시나요?

A2. NotificationCenter로부터 오는 이벤트를 받고 처리하는 곳의 생성자 쪽에서 등록해야한다고 생각합니다.


**Q3. Restoration vs Accessibility**

> Restoration ID 와 Accessibility Identifier 가 있었는데, 이 두가지의 사용하는 곳이 다른걸 까요? 어떨때 어떤 것을 사용해야하는 건지 조언이 필요합니다!

A3. Restoration ID의 경우 앱이 Crash 같은 문제로 종료되고 열려있던 뷰를 복원시킬 때 사용하며 Accessibility Identifier는 손쉬운 사용에서 접근성 관련 설정과 관련있는 부분입니다. 현재 프로젝트에서는 사용하지 않아도 될 것 같습니다.

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +
[P1] EditStockViewController을 상속해서 사용하는 타입이 없다면 final 키워드를 붙여주는 것이 좋아요. 
성능상의 이점과 상속을 하지 못하도록 강제하는 장점이 있습니다.

> final 키워드에 대해서는 추후 학습하실 내용입니다. 평소 final 키워드를 붙여주는 습관을 들여두시는 것을 추천드립니다.

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var mangoLabel: UILabel!
[P1] ViewController의 UI 요소들을 외부에서 접근할 수 있을 것 같습니다.
접근제어자를 추가하면 좋을 것 같네요 :)

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +                                       object: nil)
화면 간의 데이터 전달 방법을 NotificationCenter로 선택하신 이유가 있을까요? 
화면 간 데이터 전달 방법에는 추가적으로 어떤 방법들이 있나요?

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +                                                                                "EditStockViewController") else { return }
[P3] 현재는 identifier를 수동으로 입력하도록 되어있는데 만약 철자가 잘못되면 관련된 곳에서 모두 수정해야하는 문제가 있을 것 같아요. EditStockViewController의 identifier를 EditStockViewController에서 작성할 수 있도록하면 좋을 것 같아요.

```swift
guard let editStockViewController = self.storyboard?.instantiateViewController(
    withIdentifier: EditStockViewController.identifier) else { ... }
```

---

더 좋은 방법은 `self.storyboard.instantiateViewController(withIdentifier:)`을 간단하게 처리할 수 있는 Sugar를 만드는 방법도 있을 것 같아요.

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
[P1] 중복으로 사용되는 코드가 많은 것 같아요. 간단하게 줄일 수 있는 방법에 대해 고민해보면 좋을 것 같아요.
또한, Restoration ID의 경우 앱이 Crash 같은 문제로 종료되고 열려있던 뷰를 복원시킬 때 사용하기 때문에 여기서 사용하는 것은 좋지 않는 것 같습니다.

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func makeJuiceTapped(_ sender: UIButton) {
[P2] 버튼 탭 메서드의 경우 아래와 같이 보통 많이 쓰는 것 같아요.

```swift
func xxxButtonDidTap(_ sender: UIButton) { ... }
func didTapXxxButton(_ sender: UIButton) { ... }
```

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func successAlert(_ juiceName: String) {
[P2] successAlert는 "성공 알림"의 명사형 네이밍인 것 같아요
present 하는 의미를 더 담아서 `presentSuccessAlert`는 어떠신가요?

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func failureAlert(at fruitName: String, count: Int) {
[P2] 위의 successAlert 코멘트와 동일합니다. 동사 + 명사형으로 네이밍이 좋을 것 같아요.

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                notificationCenter.post(name: .failureUseFruit, object: nil, userInfo: ["fruitName": fruit.rawValue, "count": ingredient - stock])
NotificationCenter는 기본적으로 1:N 구조의 BroadCast 방식이기 때문에 필요없는 뷰에도 이벤트가 전달되는 문제가 있습니다. 다른 방법을 고민해보면 좋을 것 같아요 :)

2023-01-10 11:56 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let fruits = fruitStore.fruits.mapValues{ String($0) }
mapValues(_:)는 어떤 기능을 하는 메서드인가요?

2023-01-11 11:37 UTC, parkmuri commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +
링고 코멘트 참고하여 `final`키워드 추가하였습니다 :)
4992f2b793ba581fb042ad1b9461d018f90af0d4

2023-01-11 11:38 UTC, juun97 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        let fruits = fruitStore.fruits.mapValues{ String($0) }
Label의 텍스트의 경우 String 타입을 줘야했습니다! 하지만 저희의 가 출력하고싶은 재고의 갯수는 Int 의  형태였기에 고차함수를 통해 값들을 다 String로 변환 시켜줬습니다!

2023-01-11 11:38 UTC, juun97 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func successAlert(_ juiceName: String) {
조언에 맞춰 수정했습니다!

2023-01-11 11:38 UTC, juun97 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    func failureAlert(at fruitName: String, count: Int) {
위 코멘트와 같이 맞춰 수정했습니다!

2023-01-11 11:38 UTC, parkmuri commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var mangoLabel: UILabel!
외부에서 접근이 불가능해야할것같은 메서드/프로퍼티에 접근제어자 `private`선언해주었습니다!
4992f2b793ba581fb042ad1b9461d018f90af0d4
33b85abd115e740074beb8a640258d07458cac8f

2023-01-11 11:38 UTC, juun97 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func makeJuiceTapped(_ sender: UIButton) {
`makeJuiceButtonDidTap` 으로 네이밍을 바꿔주었습니다!

2023-01-11 11:40 UTC, juun97 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
```swift
 @IBAction func makeJuiceButtonDidTap(_ sender: UIButton) {
        let juiceMaker = JuiceMaker()
        
        for juice in Juice.allCases {
            guard sender.tag == juice.rawValue else { continue }
            juiceMaker.makeJuice(juice)
        }
    }
첫 실행시 Juice 타입의 원시값과 버튼들의 태그값들을 동일하게 맞춰준 뒤 Juice 타입을 for 문으로 돌아 확인하는 로직으로 수정해보았습니다 !
```

2023-01-11 13:44 UTC, juun97 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +                notificationCenter.post(name: .failureUseFruit, object: nil, userInfo: ["fruitName": fruit.rawValue, "count": ingredient - stock])
Singleton 으로 선언된 FruitStore 인스턴스를  활용하는걸로 변경했습니다!

2023-01-11 13:55 UTC, juun97 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +                                                                                "EditStockViewController") else { return }
5da353d7632d7fbf695a94757505a5897dfa005b
0d197210826b1e11ac1cd0cfa070065b807b1398
(커밋 실수로 2개로 나눠졌습니다 ㅜㅜㅜㅜ)

EditStockViewController 에서 static 으로 Identifier 을 설정한 뒤 그 값을 이용해서 화면전환을 했습니다!

2023-01-11 13:56 UTC, parkmuri commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +                                       object: nil)
학습활동시간에 배운것을 사용해보고자 선택한것이 가장 큰 이유였습니다.
다른 화면 간 데이터 전달 방법에는
1. 프로퍼티로 직접 접근해서 데이터 넘기는 방식
2. segue를 이용해서 전달하는 방식
3. delegate 패턴을 이용한 방식
4. closure를 이용한 방식
5. notification center

- `notification center`는 broadcast에서 많이 사용한다고 하여 다른 방법을 사용해보기로 했습니다. `KVO` 적용 시 이미 `ViewController`가 `UIViewController`상속을 받고있기 때문에 적용이 어려워 다른 방법을 찾아보았습니다.
- `delegate`를 사용하려고 적용했을 시, `delegate`의 인스턴스가 생성되는 시점이 `ViewController`의 `viewDidLoad()`보다 앞선 시점이라 해결이 어려웠습니다. 또 질문을 통해 이렇게되면 Singleton, (성공/실패 알람을 위한)notification에 delegate까지 사용하게되어 비효율적이라는 말을들었습니다.
- 따라서 선언해놓은 Singleton을 최대한 이용하는 방향으로 진행하게 되었습니다.

2023-01-11 16:27 UTC, llingo approved these changes
수고하셨습니다 무리, 릴라, 세홍 :) 
주석 관련 추가 피드백의 경우 다음 스탭에서 수정하셔도 될 것 같아요. 코멘트 확인 부탁드립니다. 
다음 스탭도 화이팅입니다 🎉

2023-01-11 16:27 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/EditStockViewController.swift
> +    static let identifier = "EditStockViewController"
좋습니다 👍

2023-01-11 16:27 UTC, llingo commented on JuiceMaker/JuiceMaker/Controller/NotificationName.swift
> +//}
[P2] 사용하지 않게된 코드는 주석으로 처리하는 것보다 제거하는 편이 좋습니다 :)

2023-01-11 16:27 UTC, llingo commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: Int, CaseIterable {
CaseIterable을 사용해주셨군요 좋습니다 👍

2023-01-11 16:28 UTC, merged