쥬스메이커 [STEP3] 리지, kaki
yagom-academy/ios-juice-maker pull request #302
Opened 2023-01-12 06:25 UTC by kak1x

## STEP3 PR
@Judy-999 
안녕하세요 주디! 마지막 세 번째 PR리뷰도 잘 부탁드릴게요😊

### 고민했던 부분
1. 원래는 버튼에 tag를 이용하여 버튼 액션을 구현해줬는데, tag의 Int 값과 버튼은 아무런 연관성이 없다고 생각되었습니다.
2. 스토리보드에서 Navigation Item 글자의 크기를 키우면 글자가 상단으로 커져서 center 정렬이 풀리는 현상이 발생했습니다.
3. stepper를 적용할때도 하나의 ```@IBAction```으로 묶어서 처리할 방법을 생각했습니다. 그런데 stepper를 누르면 과일의 종류도 확인이 되어야하고 그 과일의 재고가 보여지는 label도 확인이 되어야해서 어떻게 접근하는게 좋을지에 대한 고민을 했습니다.
4. modal 형태로 화면을 띄워주면 .fullScreen으로 설정해주지 않는 이상 ```viewWillAppear```를 사용할 수 없었습니다.

#### 1. 해결방법
```swift
private func setButton(_ sender: UIButton) -> JuiceMenu? {
        guard let buttonTitle = sender.titleLabel?.text else {
            return nil
        }
        
        switch buttonTitle {
        case "딸기쥬스 주문":
            return JuiceMenu.strawberryJuice
        case "딸바쥬스 주문":
            return JuiceMenu.strawberryBananaJuice
        case "바나나쥬스 주문":
            return JuiceMenu.bananaJuice
        case "파인애플쥬스 주문":
            return JuiceMenu.pineappleJuice
        case "키위쥬스 주문":
            return JuiceMenu.kiwiJuice
        case "망고쥬스 주문":
            return JuiceMenu.mangoJuice
        case "망키쥬스 주문":
            return JuiceMenu.mangoKiwiJuice
        default:
            return nil
        }
    }

@IBAction private func orderButtonTapped(_ sender: UIButton) {
        guard let orderedJuice = setButton(sender) else {
            return
        }
        completeOrder(of: orderedJuice)
    }
```
- 주문하는 버튼에 적혀있는 buttonTitle 로 접근하여 쥬스의 종류를 확인하도록 구현했습니다. 그리고 ```orderButtonTapped``` 하나로 묶어서 버튼을 눌렀을 때, 쥬스의 종류를 확인하여 주문하도록 변경하여 코드의 길이를 줄일 수 있었습니다.
 
 
 #### 2. 해결방법
 ```swift
private func initTitle() {
        let navigationTitle = UILabel(frame: CGRect(x: 0, y: 0, width: 200, height: 40))
        navigationTitle.numberOfLines = 1
        navigationTitle.textAlignment = .center
        navigationTitle.font = UIFont.systemFont(ofSize: 30)
        navigationTitle.text = "재고 추가"
        self.navigationItem.titleView = navigationTitle
    }
```
 - Navigation controller의 title을 코드로 구현하여 storyboard 에서 다루기 어려웠던 부분을 해결할 수 있었습니다.

#### 3. 해결방법
```swift
private func setStepper() {
        let stepperList: [UIStepper] = [strawberryStepper, bananaStepper, pineappleStepper, kiwiStepper, mangoStepper]
        
        for stepper in stepperList {
            guard let fruit = matchStepperAndFruit(stepper).fruit else { return }
            stepper.value = Double(juiceMaker.currentFruitStock(of: fruit))
        }
        
        stepperList.forEach {
            $0.autorepeat = true
            $0.maximumValue = 150
        }
    } 

private func matchStepperAndFruit(_ stepper: UIStepper) -> (fruit: Fruit?, label: UILabel?) {
        switch stepper {
        case strawberryStepper:
            return (.strawberry, strawberryStockLabel)
        case bananaStepper:
            return (.banana, bananaStockLabel)
        case pineappleStepper:
            return (.pineapple, pineappleStockLabel)
        case kiwiStepper:
            return (.kiwi, kiwiStockLabel)
        case mangoStepper:
            return (.mango, mangoStockLabel)
        default:
            return (nil, nil)
        }
    }

@IBAction private func stepperTapped(_ sender: UIStepper) {
        guard let fruit = matchStepperAndFruit(sender).fruit,
        let label = matchStepperAndFruit(sender).label else { return }
        label.text = Int(sender.value).description
        FruitStore.sharedFruitStore.fruitStocks[fruit] = Int(sender.value)
    }
```
- ```setStepper```를 이용하여 stepper와 현재 재고량을 설정해주었고, 이후 ```matchStepperAndFruit```을 이용하여 각 stepper가 눌렸을때 그에 해당하는 Fruit과 UILabel을 튜플타입으로 반환하여 하나의 메서드로 2개의 값에 접근할 수 있도록 연결해주었습니다.

#### 4. 해결방법
```swift
// ManageStockViewController.swift
override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    NotificationCenter.default.post(name: NSNotification.Name("dismiss"), object: nil)
}

// OrderJuiceViewController.swift
override func viewDidLoad() {
    super.viewDidLoad()
    
    NotificationCenter.default.addObserver(self, selector: #selector(self.didDismissManageStockView(_:)), name: NSNotification.Name("dismiss"), object: nil)
}

@objc func didDismissManageStockView(_ notification: Notification) {
    self.updateStockLabel()
}
```
- modal 방식을 .fullScreen으로 수정해주면 간단하게 해결이 되겠지만 활동학습에서 배웠던 Notification을 사용해서 해결해보았습니다.
- ```viewDidDisapper```로 처음에 구현을 했는데, 화면이 닫히고 값이 변경되어 첫번째 화면으로 돌아왔을 때 딜레이가 생겼습니다. 그래서 닫히면서 값이 변경되는 ```viewWillDisappear``` 로 구현하였습니다.

### 추가적으로 학습할 내용
- 싱글톤이 아닌 델리게이트 패턴을 이용하여 데이터 관리하는 법을 학습할 계획입니다.

### 인스턴스 관련 정리 내용
- struct의 인스턴스는 Stack 영역에 올라갔다가 사용이 종료되면 자동으로 지워지므로 여러개의 인스턴스를 생성하는것이 현재 프로젝트엔 크게 문제가 없다고 생각됩니다.

2023-01-15 08:53 UTC, Judy-999 requested changes
kaki, 리지 마지막 스텝도 잘 수행하셨네요 👏👏

오토레이아웃이 쉽지 않은 개념이지만 앞으로도 UI 배치를 위해 반드시 사용하게 될 기능이니 잘 익혀두시면 좋겠습니다.

## 고민한 부분

1. 원래는 버튼에 tag를 이용하여 버튼 액션을 구현해줬는데, tag의 Int 값과 버튼은 아무런 연관성이 없다고 생각되었습니다.

> **Int** 값과 버튼이 연관이 없는 것처럼 버튼의 text인 **String**으로 비교하는 것도 명확하진 않을 것 같아요. 어떤 버튼인지 버튼 자체로 비교하는 방법은 어떨까 싶네요 👀

<br>

2. 스토리보드에서 Navigation Item 글자의 크기를 키우면 글자가 상단으로 커져서 center 정렬이 풀리는 현상이 발생했습니다.

> Lable을 직접 넣어줘서 해결하셨네요 👍 
> 해당 코드와 관련된 리뷰는 코멘트로 남기겠습니다~

<br>

3. stepper를 적용할때도 하나의 @IBAction으로 묶어서 처리할 방법을 생각했습니다. 그런데 stepper를 누르면 과일의 종류도 확인이 되어야하고 그 과일의 재고가 보여지는 label도 확인이 되어야해서 어떻게 접근하는게 좋을지에 대한 고민을 했습니다.

> 연관된 두 개의 값이 필요해서 튜플을 사용하셨네요! 튜플에 lable로 각 인덱스를 구분할 수 있게 한 점도 좋습니다 👏

<br>

4. modal 형태로 화면을 띄워주면 .fullScreen으로 설정해주지 않는 이상 viewWillAppear를 사용할 수 없었습니다.

> 왜 `.fullScreen`이 아니면 `viewWillAppear`를 사용할 수 없는걸까요? 이유를 고민해보시고 알려주세요~!

<br>

---

## 오토레이아웃
실행 후 재고 수정 화면으로 가면 콘솔 창에 이미지와 같은 오류 사항이 뜹니다 😅 오토레이아웃에 문제가 있는 듯하니 해결해주세요!

<img width="565" alt="스크린샷 2023-01-15 오후 5 50 28" src="https://user-images.githubusercontent.com/102353787/212531771-84334f54-cec8-43ec-8bfc-60f440d43e84.png">

(참고로 [wtfautolayout](https://www.wtfautolayout.com/) 이 사이트에 위 에러 문구 중 `"<NSLayoutConstraint ~ `로 시작하는 부분 전체를 복사해서 넣으면 어떤 문제인지 보기 편하게 알려줍니다~)

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
외부에서 접근할 일이 있을까요~?

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
단순히 `Title`이라고 하면 모호하게 느껴질 수 있어 보여요. 메서드명에서도 Navigation의 Title이라고 명시해주면 좋겠네요!

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
`UILabel`에 `CGRect`로 크기를 지정해주고 있는데 어떤 수치인가요?
해당 수치가 실제로 영향을 주고 있는지 확인해보시면 좋겠네요!

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
[numberOfLines](https://developer.apple.com/documentation/uikit/uilabel/1620539-numberoflines)의 공식문서를 보면 default 값이 1로 되어있네요! 굳이 명시해주지 않아도 될 것 같습니다.

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
`UIFont.systemFont(ofSize: 30)` 여기서 30이란 수치도 직접 설정하신 값이라 가늠되지 않을 수 있습니다.

[HIG - Typography](https://developer.apple.com/design/human-interface-guidelines/foundations/typography#specifications) 문서를 참고해서 지정되어 있는 font 중 하나를 적용해보세요 🙂

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
`set`이란 단어는 많은 의미를 가지고 있어 모호합니다. 설정이란 의미를 명확하게 나타내는 표현을 사용하시면 좋겠네요.
개인적으로는 `setup`을 사용하는 편입니다~

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
`stepperList`로 stepper 배열을 선언해서 사용하고 계시네요.

`IBOutlet`들을 `Outlet Collection`으로 선언하면  Array 형식으로 사용할 수 있습니다. 참고해보세요 🙂

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
`override func`이니 `viewDidLoad` 쪽에 위치하는게 좋겠네요!

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(self.didDismissManageStockView(_:)), name: NSNotification.Name("dismiss"), object: nil)
한 줄의 코드라도 `viewDidLoad`에 직접 작성하는 것 보단 메서드로 분리해서 어떤 작업인지 명시하는게 좋을 것 같아요 🙂

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
>      }
`private` 잊지 말아주세요 🙌

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
>      }
해당 메서드의 역할이 버튼을 `set`하는걸까요~?

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
>      private func successAlert(name: String) {
`successAlert`은 명사처럼 느껴지네요 🤔 `보여준다, 나타낸다`와 같은 의미를 명시해주면 좋겠네요!
(`failAlert`도 동일합니다)

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        return fruitStock
반환타입을 `Int`로 변경해서 활용성을 높여주셨네요 👍

2023-01-15 08:53 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      }
`init`을 `private`하게 하면서 초기값을 지정할 수 있게 되었네요 😊

2023-01-16 05:22 UTC, yijiye commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet weak var mangoStepper: UIStepper!
private으로 접근제어 걸었습니다!

2023-01-16 05:22 UTC, yijiye commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
네이밍 수정하였습니다 :)

2023-01-16 05:23 UTC, yijiye commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
아 네! 위치 수정하였습니다

2023-01-16 05:24 UTC, yijiye commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
>      }
버튼을 누르면 주스가 반환되는 역할을 하니 주문을 받는다는 뜻으로 takeOrders 로 네이밍 변경하였습니다

2023-01-16 05:25 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    }
initNavigationTitle로 메서드명을 바꿔주었으며, Label에는 CGRect 적용이 불가하여 UILabel()로 변경하였습니다.
numberOfLines는 지워서 default 값을 이용하게 해주었으며 Font는 .largeTitle로 설정해주었습니다!

2023-01-16 05:30 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(self.didDismissManageStockView(_:)), name: NSNotification.Name("dismiss"), object: nil)
setUpNotificationObserver 메서드로 정의해주었습니다!

2023-01-16 05:32 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
>      private func successAlert(name: String) {
showSuccessAlert / showFailAlert 로 변경해주었습니다

2023-01-16 05:35 UTC, yijiye commented
> 왜 .fullScreen이 아니면 viewWillAppear를 사용할 수 없는걸까요? 이유를 고민해보시고 알려주세요~!
- fullScreen이 아니면 그 전의 화면이 완전히 덮히지 않아서 disappear 되지 않고 계속 스택에 남아있게 됩니다. 그래서 viewWillAppear를 사용할 수 없었습니다.

2023-01-16 11:04 UTC, Judy-999 requested changes
잘 반영하셨네요! 좋습니다 👍👍
잘해주셔서 생각해보면 좋은 질문들과 오토레이아웃 부분만 추가 코멘트 드려요 😊

---

## 오토레이아웃
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-16 at 19 54 37](https://user-images.githubusercontent.com/102353787/212662526-ff03ba5d-ce99-42d4-89e5-4cd743b3e7a0.png)

묘하게 `과일 이미지~주문버튼`들이 전체적으로 위쪽으로 치우친 것 같아요. 
화면 중앙에 있도록 정렬하시면 좋겠네요!
<br>

<img width="451" alt="스크린샷 2023-01-16 오후 7 56 37" src="https://user-images.githubusercontent.com/102353787/212662722-c611ecc9-8195-4010-9df0-917ec1140330.png">

- 과일 이미지들의 height를 102.33으로 지정하신 걸까요? 애매한 숫자 같은데 높이를 정해주고 싶다면 비율로 고정하는게 좋을 것 같습니다.
- 넣어주지 않아도 되는 제약들이 있는 것 같아요. StackView의 설정들을 생각해보시고 필요한 제약들만 남겨주세요! 하나씩 지워보면서 확인하셔도 좋습니다 🙂

2023-01-16 11:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        }
두 구문 모두 `stepperList` 반복하고 있네요! 하나로 합치는건 어떨까요?

2023-01-16 11:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        }
`for`와 `forEach`는 어떤 차이가 있을까요?

2023-01-16 11:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        let label = matchStepperAndFruit(sender).label else { return }
```suggestion
        guard let fruit = matchStepperAndFruit(sender).fruit,
              let label = matchStepperAndFruit(sender).label else { return }
```
사소하지만 이렇게 여백이 들어가는게 맞을 것 같네요!
필요한 구문을 드래그한 후 `control + i`를 누르시면 자동으로 고쳐줍니다 👍

2023-01-16 11:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
>      }
```suggestion
    private func setUpNotificationObserver() {
        NotificationCenter.default.addObserver(self, 
        selector: #selector(self.didDismissManageStockView(_:)),
        name: NSNotification.Name("dismiss"), 
        object: nil)
    }
```

코드 한 줄이 길다면 이렇게 매개변수를 기준으로 개행을 넣어주기도 합니다 🙂
(위 코드에는 여백이 표현되진 않았지만 매개변수가 같은 열에 있도록 정렬될 겁니다!)

2023-01-16 11:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet private var stepperList: [UIStepper]!
`stepperList`에는 `weak` 키워드가 붙지 않았네요 🤔
`weak`는 어떤 역할을 하고, 왜 사용되는 걸까요?

2023-01-16 11:04 UTC, Judy-999 commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet private var stepperList: [UIStepper]!
`@ IBOutlet`들에 왜 `!`를 해주고 있을까요? 

`?`로 변경하면 어떤 점이 달라질까요?

2023-01-17 04:44 UTC, kak1x commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +        }
```forEach```는 반복문이 아니기 때문에 요소만 반복이 가능하며 ```break```, ```continue``` 같은 키워드의 사용이 불가능합니다.

2023-01-17 05:59 UTC, yijiye commented on JuiceMaker/JuiceMaker/Controller/ManageStockViewController.swift
> +    @IBOutlet private var stepperList: [UIStepper]!
### @IBOutlet에 weak 선언된 이유
- 앱을 사용하다가 메모리가 부족해지면 ViewController는 "didReceiveMemoryWarning()"라는 인스턴스 메서드를 호출하여 View를 nil 처리해주는데, 이때 만약 subView들이 Strong으로 선언되어 RC가 올라가있다면 View가 nil이 되더라도 ViewController로부터 RC가 올라가있는 상태라 메모리에서 내려가지 않게 됩니다. 즉, View가 메모리에 존재하지 않는데 보이지도 않는 subView가 메모리에 계속 존재하는 메모리 누수 현상이 일어날 수 있습니다. 이런 현상을 방지하게 위해 weak 키워드가 디폴트로 선언됩니다.

### @IBOutlet Collection에 weak가 선언되지 않는 이유
- Collection(Array)은 Struct 타입이기 때문에 참조가 불가능하여 weak 키워드를 붙여줄 수 없습니다.

### 강제언래핑을 사용하는 이유? 
- @IBOutlet은 스토리보드와 interface builder를 연결해주는 역할을 하는데 스토리보드에 존재하는 것을 연결해주었기 때문에 무조건 존재할 수 밖에 없기에 불필요한 언래핑 과정을 생략해주기 위해 강제 언래핑(!)이 사용됩니다.

2023-01-17 06:32 UTC, Judy-999 approved these changes
모두 완벽하게 수정하시고 추가 질문도 잘 알아보신 것 같아 좋습니다 👍👍
두 분 다 잘하셔서 프로젝트가 일찍 마무리되었네요😁

여유가 있으시면 화면 전환 시 데이터를 전달하는 다른 방법도 공부하고 적용해보시는 연습을 해도 좋을 것 같네요. 수고하셨어요 🙌

2023-01-17 06:32 UTC, merged