쥬스메이커 [STEP 3] Goat, Brody
yagom-academy/ios-juice-maker pull request #303
Opened 2023-01-12 07:57 UTC by Goatt8

@wongbingg
웡빙 안녕하세요!
Goat, Broady Step3 PR 보냅니다
이번리뷰도 잘부탁드릴게요! 🔥

<br/>

## 고민했던 점 & 조언을 얻고싶은 점 :smile:

### 1. 오토 레이아웃을 코드로 적용할지 StoryBoard에서 적용할 지에 대한 부분을 고민했습니다.
- 메인 스토리뷰에서 뷰를 만들어 놨기 때문에 스토리보드에서 오토 레이아웃을 적용했습니다. 하지만 만약 복잡한 뷰가 생성되고 재사용되어야 한다면 코드로 오토레이아웃 제약을 설정하는 것이 좋다고 생각이 들었습니다.

### 2. 스토리보드의 Identifier 매직리터럴을 보관하는 방법에 대해 고민했습니다.
- 모달 방식으로 스토리보드에 있는 네비게이션 컨트롤러를 삽입하기 위해서는 코드에서 identifier를 가져와야 했습니다. 긴 문자열이기 때문에 어떤 특정한 타입에 저장하면 좋지 않을까 생각이 들었고 결과적으로 Identifier라는 열거형 타입을 만들었습니다.
```swift
// 정의
enum Identifier: String {
    case fruitStoreNavigationController = "fruitStoreNavigationController"
}
// 사용
guard let fruitStoreVC = self.storyboard?.instantiateViewController(
    withIdentifier: Identifier.fruitStoreNavigationController.rawValue
) as? UINavigationController else {
    return
}
```
- 혹시 위처럼 Identifier를 정의하는 방법보다 더 많이 사용하는 방법이 있을까요?

### 3. SizeToFit
- 오토 레이아웃을 사용하기 전에는 Stepper를 통해 수량 레이블을 변화시킬 때 레이블의 텍스트크기에 맞게 레이블의 뷰를 넓혀주기 위해 sizeToFit()메서드를 사용했습니다. 하지만 **auto layout의 스택뷰를 적용한 이후 sizeToFit()을 사용하지 않아도 자동으로 텍스트 크기에 맞게 레이블 뷰의 크기를 넓히는 것**을 볼 수 있었습니다. 
- 이에 대해 스택뷰는 묶여진 뷰들 중에 큰 뷰에 맞게 width를 설정해서 레이블도 그 width까지만 늘어나고 이후로는 글자가 짤리는 것을 가정했습니다. 하지만 label에 1000000이라는 스택뷰의 너비를 넘어서는 값을 주었더니 텍스트크기에 맞게 레이블 뷰가 넓혀지는 것을 볼 수 있었습니다. 그래서 오토레이아웃의 스택뷰에서 레이블을 처리하는 방법에 대해 궁금증이 남아있지만 해결하지 못했습니다. 혹시 오토레이아웃의 제약사항을 설정하는 것이 레이블의 sizeToFit설정을 해주는 것과 어떤 관련이 있을까요?

### 4. FruitStoreVC(secondVC)에서 navigationItem.BarButtonItem 이 연결되지 않던 문제를 고민헀습니다.
* navigationItem.BarButtonItem을 정상적으로 만들었음에도 불구하고FruitStoreVC화면에 띄워지지 않아 문제를 찾아봤는데, **FruitStoreVC가 모달방식으로 present된 화면**이어서 네비게이션을 정상적으로 불러오지못하는 상황이었습니다. 네비게이션은 뷰들간의 화면의 흐름을 연결시켜주는 기능인데, 모달방식이라 이를 적용하지 못하는 것 같았습니다.
    * 따라서 JuicMakerVC에서 화면이동을 할때 FruitStoreVC를 불러오는게 아니라 FruitStoreVC에 세팅되있는 **FruitStoreNavigationVC를 붙러오는 방식**으로 해결했습니다.
```swift
func presentFruitStoreVC() {
guard let fruitStoreVC = self.storyboard?.instantiateViewController(withIdentifier: 
     Identifier.fruitStoreNavigationController.rawValue) as? UINavigationController
    else {
     return
}
```

2023-01-12 08:06 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +        }
재고가 부족한 부분에 대한 실패alert과 알 수 없는 이유에 대한 실패alert두개를 하나의 함수 안에 정의했습니다. 
이 부분엔 2개의 케이스만 있어서 괜찮은데요, 만약 여러 개의 에러 모달을 띄워줘야 할 때는 하나의 showFailureAlert가 아닌 특정 에러케이스에 해당하는 alert함수들을 각각 만드는 것이 나을까요?

2023-01-12 08:06 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +        fruitStoreVC.modalPresentationStyle = .fullScreen
주문화면으로 돌아올 때 재고수정에서 변경된 값이 반영되어야 하기 때문에 present방식을 fullScreen방식으로 만들어 viewWillAppear메소드를 호출할 수 있게끔 만들었습니다. 
이 부분은 델리게이트 패턴을 통해 리팩토링 할 수 있을 것 같은데 수정을 하는 것이 좋을지 아니면 fullScreen방식으로 해도 괜찮은지 궁금합니다!

2023-01-13 05:26 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +        fruitStoreVC.modalPresentationStyle = .fullScreen
두 방법 다 좋은 방법인 것 같아요. 다만 viewWillAppear 라는 메서드를 취하기 위해 화면전환 스타일을 바꾸기 보다는 실제 어떤 화면전환이 어울리는지에 대한 고민이 우선시 되어야할 것 같아요! 두 방법(delegate, viewWillAppear)다 사용 가능한 부분이니 화면전환 스타일로 어떤 것을 가져갈지 사용자경험 또는 HIG를 참고하여 결정해볼 수 있겠죠?!

2023-01-13 05:52 UTC, wongbingg commented
안녕하세요 Goat, Broady ☺️ Step3 고생하셨습니다. 이번 PR에 많은 내용이 담겨있군요 👍 
빠짐없이 보고 답글을 달아두겠습니다 🧐

## ✅ 고민했던 점 & 조언을 얻고싶은 점


### ☑️ 1. 오토 레이아웃을 코드로 적용할지 StoryBoard에서 적용할 지에 대한 부분을 고민했습니다.
>- 메인 스토리뷰에서 뷰를 만들어 놨기 때문에 스토리보드에서 오토 레이아웃을 적용했습니다. 하지만 만약 복잡한 뷰가 생성되고 재사용되어야 한다면 코드로 오토레이아웃 제약을 설정하는 것이 좋다고 생각이 들었습니다.

좋은 고민을 해주셨네요.👍
- **코드로 적용**을 한다면 UI 요소들에 더 깊게 접근할 수 있는 장점이 있을 것 같아요. 스토리 보드의 Inspector 창에서 설정해줄 수 있는 것들을 코드로 작성하니 어떤 UI에 어떤 적용을 해주었는지도 한눈에 알아보기가 좋다는 장점도 있어요.
- **스토리보드**를 사용했을 때는 코드로 제약을 작성하는 것보다 눈으로 확인하며 제약을 빠르게 줄 수 있다는 장점이 있어요. 또한 제약 오류사항도 바로 확인할 수 있고 심지어 자동으로 오류를 수정해주는 기능까지 있어요(이 기능은 비추천🥲) 

저는 둘다 사용해보고 어떤 것이 나은 방법이었는지 판단해 보는 방법도 좋다고 생각해요! 시간이 남는다면 프로젝트를 리팩토링 하며 각각의 방법을 다 사용 해보셨으면 좋겠네요 ☺️

### ☑️ 2. 스토리보드의 Identifier 매직리터럴을 보관하는 방법에 대해 고민했습니다.
>- 모달 방식으로 스토리보드에 있는 네비게이션 컨트롤러를 삽입하기 위해서는 코드에서 identifier를 가져와야 했습니다. 긴 문자열이기 때문에 어떤 특정한 타입에 저장하면 좋지 않을까 생각이 들었고 결과적으로 Identifier라는 열거형 타입을 만들었습니다.
>-- 코드 --
>- 혹시 위처럼 Identifier를 정의하는 방법보다 더 많이 사용하는 방법이 있을까요?

저는 지금도 충분히 좋은 방법이라 생각됩니다 👍 
- 매직 리터럴들을 enum 타입으로 분리를 하려고 생각하신 이유가 있을까요? 
- enum으로 분리하지 않았을 때 겪을 수 있는 비용에는 어떤 것이 있을까요?

### ☑️ 3. SizeToFit
>- 오토 레이아웃을 사용하기 전에는 Stepper를 통해 수량 레이블을 변화시킬 때 레이블의 텍스트크기에 맞게 레이블의 뷰를 넓혀주기 위해 sizeToFit()메서드를 사용했습니다. 하지만 **auto layout의 스택뷰를 적용한 이후 sizeToFit()을 사용하지 않아도 자동으로 텍스트 크기에 맞게 레이블 뷰의 크기를 넓히는 것**을 볼 수 있었습니다. 
>- 이에 대해 스택뷰는 묶여진 뷰들 중에 큰 뷰에 맞게 width를 설정해서 레이블도 그 width까지만 늘어나고 이후로는 글자가 짤리는 것을 가정했습니다. 하지만 label에 1000000이라는 스택뷰의 너비를 넘어서는 값을 주었더니 텍스트크기에 맞게 레이블 뷰가 넓혀지는 것을 볼 수 있었습니다. 그래서 오토레이아웃의 스택뷰에서 레이블을 처리하는 방법에 대해 궁금증이 남아있지만 해결하지 못했습니다. 혹시 오토레이아웃의 제약사항을 설정하는 것이 레이블의 sizeToFit설정을 해주는 것과 어떤 관련이 있을까요?

- sizeToFit() 메서드는 UILabel 이 자신이 가진 subview(text)를 감쌀 수 있도록 크기를 변경시키는 기능으로 알고 있어요. 오토레이아웃 제약설정을 통해 UILabel의 크기를 지정 해준다면 sizeToFit() 메서드가 의미가 없어질 것 같아요. 이 반대 순서도 마찬가지 일 것 같아요. 두 기능 다 뷰의 크기조절 관련 메서드라 둘중 하나만 사용해도 좋을 것 같다는 생각이 드네요 !
- 현재 100000 이라는 값을 주었을 때 텍스트크기에 맞게 레이블 뷰가 넒혀졌던 이유는 스택뷰의 alignment 설정에 따라 달라질 것 같아요. center 와 fill일 때 어떤 차이가 있을까요?

### ☑️ 4. FruitStoreVC(secondVC)에서 navigationItem.BarButtonItem 이 연결되지 않던 문제를 고민헀습니다.
>* navigationItem.BarButtonItem을 정상적으로 만들었음에도 불구하고FruitStoreVC화면에 띄워지지 않아 문제를 찾아봤는데, **FruitStoreVC가 모달방식으로 present된 화면**이어서 네비게이션을 정상적으로 불러오지못하는 상황이었습니다. 네비게이션은 뷰들간의 화면의 흐름을 연결시켜주는 기능인데, 모달방식이라 이를 적용하지 못하는 것 같았습니다.
    * 따라서 JuicMakerVC에서 화면이동을 할때 FruitStoreVC를 불러오는게 아니라 FruitStoreVC에 세팅되있는 **FruitStoreNavigationVC를 붙러오는 방식**으로 해결했습니다.
```swift
func presentFruitStoreVC() {
guard let fruitStoreVC = self.storyboard?.instantiateViewController(withIdentifier: 
     Identifier.fruitStoreNavigationController.rawValue) as? UINavigationController
    else {
     return
}
```

- 현재 JuiceMakerVC 에 네비게이션 컨트롤러를 가지고있다면, navigationController.pushViewController() 메서드를 통해 화면전환을 시켜줄 수 있을 것 같아요. 현재 코드에서는present를 통해 모달방식으로 다음뷰를 띄워주고 있네요. 이렇게 되면 다음 뷰가 navigationController를 가지지 않게 되어 바버튼아이템 등록도 되지 않았던 것 같아요. 중요한 부분이니 고민해보시면 좋을 것 같아요!

2023-01-13 05:59 UTC, wongbingg requested changes

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/Type.swift
> +    case unknownError
에러타입을 잘 정의해주셨네요 👍

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +        }
에러타입이 많다면 그렇게 처리해주는 것이 좋겠어요! 하나의 메서드는 하나의 기능만 하도록 만드는 것이 좋은 방향이라고 생각해요. 
또한 alert생성에 대한 코드가 많은데, 이를 빌더패턴을 이용해서 alert를 생성해주는 방법도 많이 사용 한답니다 관심있으시면 builder 디자인패턴에 대해 찾아보셔도 좋을 것 같아요 ☺️

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    }
이 두개의 프로퍼티 다 외부에서 접근할 가능성이 있나요 ?

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    @IBOutlet weak var pineappleStepper: UIStepper!
@IBOutlet 프로퍼티는 왜 weak 키워드와 암시적 언래핑 방법이 자동완성 될까요 ? 고민해보시면 좋을 것 같아요

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        setUpStepper()
뷰 라이프사이클 메서드 내부를 깔끔하게 정리 해두셨군요 👍

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    }
```suggestion
    func setUpNavigationItem() {
        self.title = "재고 추가"
        let rightButton = UIBarButtonItem(
            title: "닫기",
            style: .plain, 
            target: self, 
            action: #selector(goBackJuiceMakeView)
        )
        self.navigationItem.rightBarButtonItem = rightButton
    }
```

이런식으로 개행을 주어도 좋을 것 같아요 ☺️

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        Int(sender.value) > fruitCount ? fruitStore.addOne(of: targetFruit) : fruitStore.reduceOne(of: targetFruit)
3항 연산자를 잘 활용 해주셨네요 👍

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +            self.present(failureAlert, animated: true)
Alert를 생성하는 부분을 메서드로 분리해주어도 좋을 것 같네요 🧐

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> -            print("알 수 없는 에러가 발생했습니다")
알 수 없는 에러에 대한 처리도 잘 해주셨네요 👍

2023-01-13 05:59 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
의도된 개행인가요 ?

2023-01-16 06:38 UTC, Goatt8 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    }
접근가능성이 없어보여서 private 키워드를 넣어주었습니다!ㅎ

2023-01-16 06:48 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    }
감사합니다!

2023-01-16 06:50 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
개행을 못했네요..ㅎ 수정했습니다!

2023-01-16 06:50 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +            self.present(failureAlert, animated: true)
빌더패턴을 이용해서 분리했습니다😄

2023-01-16 06:51 UTC, seunghyunCheon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +        }
빌더패턴 적용해서 문제를 해결했습니다!

2023-01-16 06:53 UTC, Goatt8 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakeViewController.swift
> +        fruitStoreVC.modalPresentationStyle = .fullScreen
모달방식을 사용하기위해 present를 사용했고, 그에따라서 viewWillAppear를 사용하는게 적절해보입니다!

2023-01-16 10:07 UTC, wongbingg commented
코멘트에 대한 수정사항이 잘 적용되었네요. 빌더패턴도 바로 적용을 하시다니 대단합니다👍 
고생 많으셨습니다 ☺️ 이번 스텝 머지할게요~! 다음 프로젝트도 화이팅 입니다 💪

2023-01-16 10:07 UTC, merged