쥬스 메이커 [STEP03] 송준, Rowan
yagom-academy/ios-juice-maker pull request #307
Opened 2023-01-13 06:52 UTC by kimseongj

@wonbingg
웡빙! 드디어 Step3 PR입니다! 웡빙의 날카로운 리뷰를 볼 때마다 무릎을 탁 친답니다ㅎ
이번 리뷰도 잘부탁드리겠습니다!😎

## 고민했던 점 
### 1. ```stepper```의 초기화 위치
stepper의 값을 현재 과일 재고 수량으로 초기화하기 위해 ```@IBAction func pushStepper(_ sender: UIStepper)```에서 ```stepper.value```값을 변경해주었습니다. 하지만```@IBAction func pushStepper(_ sender: UIStepper)```로 초기화할 경우 ```stepper```를 누를 때마다 초기화되는 문제점이 발견되었습니다. 이를 해결하기 위해 ViewController가 초기화될 때, 즉 viewDidLoad에 ```stepper.value```를 함께 초기화해주었습니다.
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    displayStock()
    initializeSteppers()
    setUpNavigationItem()
}
```

### 2. IBOutlet Collection
Stepper의 초기화를 한 번에 구현하기 위해 ```initializeSteppers()```메서드에서 모든 Stepper에 접근할 수 있도록 IBOutlet Collection에 담아주었습니다.

```swift
@IBOutlet var steppers: [UIStepper]!

func initializeSteppers() {
    for stepper in steppers {
        if let selectedFruit = identifyRelatedFruit(of: stepper),
           let initialValue = fruitsStock[selectedFruit] {
                stepper.transform = stepper.transform.scaledBy(x: 1.0, y: 1.0)
                stepper.value = Double(initialValue)
        }
    }
}
```

### 3. Navigation Bar 
요구사항 화면에는 NavigationBar의 크기가 저희가 사용하는 NavigationBar보다 컸습니다. 처음에는 요구사항에 맞춰서 NavigationBar대신 View를 이용해서 만들었습니다. 하지만 근본적인 원인을 해결한거 같지 않아서 NavigationBar를 사용하여 height 값을 높여주려 했습니다. height값을 올려주기 위해 조사해본 결과 iOS11 이상부터는 높이 커스터마이징을 할 수 없다라는 결론이 나와 height값을 올려주지 못했습니다.

### 4. Notification
```ChangeStockViewController```에서 ```MainViewController```으로 화면전환 시 변경된 사항을 전달하기 위해 ViewWillAppear를 사용하려 했습니다. 하지만 Modal의 경우 Full-Screen Modal이 아닐 경우 이전 화면으로 돌아갈 때, 이전 화면이 새로 표현되는 것이 아니기 때문에 ViewWillAppear, ViewDidAppear 등의 메서드를 오버라이딩할 수 없었습니다. 이를 해결하기 위해 Notification을 활용하여 ```ChangeStockViewController```의 변경사항이 있을 시 과일의 재고를 갱신했습니다. <br/> <br/> 변경사항의 ```post``` 시점은 재고 변경사항을 한 번에 전달할 수 있도록 ```viewWillDisappear```메서드를 override하여 정해주었습니다.

### 5. name space (alert message)
Alert에서 각각의 ```String```을 직접 넣는 방식보다 열거형을 통해 NameSpace를 선언하여, 가져오는 방식을 채택했습니다.  
```swift
private enum AlertMessege {
        static let confirm = "확인"
        static let yes = "예"
        static let no = "아니오"
        static let madeJuice = "가 나왔습니다. 맛있게 드세요!"
        static let lackOfStock = "재료가 모자라요. 재고를 수정할까요?"
        static let success = "성공"
        static let failure = "실패"
    }
```
### 6. 재고변경 뷰컨에서 레이블을 각각 초기화 or 모두 초기화
```displayStock()```메서드를 통해 모든 Label을 초기화 할 수 있지만 하나의 Stepper의 IBAction으로 재고의 변경이 있을 때, 전체를 초기화하기 보다는 해당하는 과일의 재고만 업데이트 할 수 있도록 ```pushStepper(_:)```메서드에서 해당 Label을 업데이트 해주었습니다. 
```swift
@IBAction func pushStepper(_ sender: UIStepper) {
        guard let fruitsLabel = identifyRelatedLabel(of: sender),
              let fruit = identifyRelatedFruit(of: sender) else { return }
        
        FruitStore.shared.fruitsStock[fruit] = Int(sender.value)
        fruitsLabel.text = Int(sender.value).description
    }
```

2023-01-15 11:43 UTC, wongbingg commented
안녕하세요 로웬, 송준 Step3 고생 많으셨습니다 ☺️

## ✅ 고민했던 점 

### ☑️ 4. Notification
>```ChangeStockViewController```에서 ```MainViewController```으로 화면전환 시 변경된 사항을 전달하기 위해 ViewWillAppear를 사용하려 했습니다. 하지만 Modal의 경우 Full-Screen Modal이 아닐 경우 이전 화면으로 돌아갈 때, 이전 화면이 새로 표현되는 것이 아니기 때문에 ViewWillAppear, ViewDidAppear 등의 메서드를 오버라이딩할 수 없었습니다. 이를 해결하기 위해 Notification을 활용하여 ```ChangeStockViewController```의 변경사항이 있을 시 과일의 재고를 갱신했습니다. <br/> <br/> 변경사항의 ```post``` 시점은 재고 변경사항을 한 번에 전달할 수 있도록 ```viewWillDisappear```메서드를 override하여 정해주었습니다.

뷰 컨트롤러간 데이터 전달에 대해 고민 해주셨네요 👍 앞으로 하게될 프로젝트들에서도 자주 고민하게될 부분일거에요. 화면간 데이터 전달 방법에는 NotificationCenter 말고도 또 어떤 방법들이 있고 각각의 특성과 장단점은 어떤지 알아보면 좋을 것 같아요!

나머지 부분들은 코드를 보고 코멘트 남겨두었습니다 ☺️

2023-01-15 11:44 UTC, wongbingg requested changes

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        setUpNavigationItem()
뷰 라이프사이클 함수 내부에 깔끔하게 작성을 해주셨네요👍 가장 초반에 보는 부분이므로 메서드분리를 지금처럼 해주면 전반적인 흐름파악에 도움이 될 것 같아요 ☺️

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +
파일들을 위에서부터 보면 메서드와 프로퍼티의 순서가 섞여있어 파악하기 조금 어려운 점이 있을 것 같아요. 위에서 부터 1.프로퍼티(IBOutlet 포함) 를 쭉 나열하고 (2.이니셜라이저, 3.뷰라이프사이클 함수)그 다음에 4.메서드들(IBAction포함)을 위치시켜 주고, 같은 속성을 가진것 끼리 묶어주면  좀 더 깔끔하지 않을까 생각되네요 🧐

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
>      }
⚠️ 모든 함수에 적용됩니다

외부에서 접근 가능한 메서드 인가요? 그렇지 않다면 접근제어자를 활용해주면 좋을 것 같아요 🧐

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
>      }
내부에서 사용되는 private enum 같은 경우 개인적으로는 최 상단(프로퍼티 보다 위)에 위치시키는 것이 깔끔한 것 같아요.

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.present(nextVC, animated: true)
pushViewController 메서드와 present 메서드는 어떤 차이가 있을까요 ?

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/NotificationCenter.swift
> +
center 프로퍼티가 사용되는 두개의 ViewController파일 내에서는 이 center가 무엇을 의미하는지 파악하기 어려울 것 같아요. 차라리 싱글톤 패턴의 특성을 이용해 NotificationCenter.default 로 접근해주는 것이 더 명확한 의미를 전달할 수 있다고 생각됩니다

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> -
불필요한 개행을 제거하는 습관 좋습니다 👍👍

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Model/NotificationCenter.swift
> +
의도된 두번의 개행인가요 !?

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        navigationBar.rightBarButtonItem = dismissButton
네비게이션 아이템 뿐만 아니라 title 까지 지정해주고 있으므로 setUpNavigationBar 이런 식의 네이밍도 좋을 것 같아요.

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        }
stepper.transform 에는 어떤 설정을 해주고 있는 걸까요? 적용을 해주었을 때와 아닐 때의 차이점은 무엇인가요 ? 🧐

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        }
```suggestion
    func identifyRelatedFruit(of stepper: UIStepper) -> Fruits? {
        switch stepper {
        case strawberryStepper:
            return .strawberry
        case bananaStepper:
            return .banana
        case pineappleStepper:
            return .pineapple
        case kiwiStepper:
            return .kiwi
        case mangoStepper:
            return .mango
        default:
            return nil
        }
```

개인취향 차이가 있을 수 있겠지만 공식문서 상 사용된 예시코드에서는 이런 식의 개행을 적용 해주었답니다☺️

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +
IBOutlet Collection 을 잘 활용 해주셨군요 👍

2023-01-15 11:44 UTC, wongbingg commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
>      }
stepper에 해당하는 타겟만 업데이트될 수 있도록 잘 처리 해주셨네요 👍

2023-01-16 04:39 UTC, kimseongj commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        }
transform을 사용했던 이유가 stepper가 작게 느껴져서 비율을 확대할려고 했던거 같습니다. 리팩토링 중 확대할 필요가 없어서 각각의 값을 1.0, 1.0으로 두었습니다. 
1.0, 1.0은 default 크기와 같기 때문에 필요 없는 코드일거 같군요! 수정하겠습니다 ㅎ

2023-01-16 04:41 UTC, kimseongj commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        }
가독성 측면에서 한줄로 case를 작성하는게 좋다고 생각했는데, 공식문서가 그랬었군요!

2023-01-16 05:37 UTC, Kyeongjun2 commented on JuiceMaker/JuiceMaker/Model/NotificationCenter.swift
> +
필요없는 개행 삭제했습니다~~

2023-01-16 05:40 UTC, Kyeongjun2 commented on JuiceMaker/JuiceMaker/Controller/MainViewController.swift
> +        self.navigationController?.present(nextVC, animated: true)
```pushViewController```메서드는 네비게이션 방식의 화면전환 메서드이고 ```present```메서드는 모달 방식의 화면전환 메서드입니다. 네비게이션 방식을 사용할 경우 다음 화면에 자동으로 뒤로가기 버튼이 생성되고 모달의 경우 따로 뒤로가기 버튼을 만들어야 했습니다.

저희는 쥬스를 주문하는 MainViewController화면과 재고를 수정하는 ChangeStockViewController화면은 User의 작업의 context가 다르다고 생각하여 모달 화면전환 방식 ```present```를 사용하였습니다.

2023-01-16 09:55 UTC, wongbingg commented
코멘트에 남겨둔 부분에 대한 수정이 잘 이루어졌네요 👍 고생하셨습니다 ☺️
마지막 스텝이 일찍 끝났으니 화면간 데이터 전달에서 `delegate 패턴`을 도전 해보시면 좋을 것 같아요 ~! 
이번 스텝은 머지하겠습니다 😊

2023-01-16 09:55 UTC, merged