쥬스 메이커 [STEP1] jusbug, Erick
yagom-academy/ios-juice-maker pull request #310
Opened 2023-05-08 09:58 UTC by JusBug

@jsa0224 
안녕하세요 Som!! Step1 PR 보내드립니다. 확인 부탁드립니다😀

### 고민한 점🧐
***Fruit***
과일과 재고를 어떤 타입에 받아 둘지 고민했습니다. 처음에는 과일 종류별로 Dictionary안에 과일과 재고 수량을 정의 해주었으나 이후 makeJuice() 혹은 changeNumber() 함수에서 재고가 변경 될 때마다 해당 타입 데이터 접근이 번거로워서 사용자 정의 타입을 생성하였습니다.
```swift
fileprivate struct Fruit {
    var name: String
    var stock: Int
}
```

***InputError***
에러처리를 하기 위해 InputError라는 Error타입을 정의해주었습니다.
```swift
enum InputError: Error {
    case nameError
    case stockError
}
```

### 해결이 안된 점🥲
없습니다.

### 조언을 얻고 싶은 점💡
1. Do-catch 구문을 어디서 사용해야 할지 헷갈립니다. 지금처럼 printError()라는 함수를 만들어 내부에서 에러메세지를 출력해주는게 괜찮은 사용일까요?

2. makeJuice() 함수 내에 switch case구문에서 각 과일주스 별로 조건을 걸어서 재고를 연산 처리했는데 보다시피 코드가 길어져서 효율이 조금 떨어질 수도 있다고 생각하는데 이런 구조 말고도 더 좋은 아이디어가 있는지 궁금합니다.

2023-05-09 05:49 UTC, jsa0224 requested changes
안녕하세요! 저스버그, 에릭!
코드 잘 보았습니다.
3주동안 잘 부탁드립니다😊

## 고민하신 부분에 대한 답변
> Fruit
과일과 재고를 어떤 타입에 받아 둘지 고민했습니다. 처음에는 과일 종류별로 Dictionary안에 과일과 재고 수량을 정의 해주었으나 이후 makeJuice() 혹은 changeNumber() 함수에서 재고가 변경 될 때마다 해당 타입 데이터 접근이 번거로워서 사용자 정의 타입을 생성하였습니다.

해당 타입 데이터 접근이 번거로운 코드의 기준이 무엇인가요? 
접근이 번거로운 코드는 쓰지 않는다는 생각이 옳을까요? 
이 부분에서 저는 갸우뚱하게 되네요. 

## 조언을 얻고 싶은 부분에 대한 답변
> Do-catch 구문을 어디서 사용해야 할지 헷갈립니다. 지금처럼 printError()라는 함수를 만들어 내부에서 에러메세지를 출력해주는게 괜찮은 사용일까요?

이 부분은 아래 코멘트에서 답변 드리겠습니다.

> makeJuice() 함수 내에 switch case구문에서 각 과일주스 별로 조건을 걸어서 재고를 연산 처리했는데 보다시피 코드가 길어져서 효율이 조금 떨어질 수도 있다고 생각하는데 이런 구조 말고도 더 좋은 아이디어가 있는지 궁금합니다.

효율보다는 제가 아래 코멘트에서 여러번 언급한 유지보수와 확장성을 고려하지 않는 구조 같아요. 
이 부분은 제가 코멘트에서 자세하게 언급했으니, 한 번 고민해보시고 함께 리팩토링해보셨으면 좋겠습니다.

## 조언드리고 싶은 부분
- 은닉화/캡슐화가 적용되지 않았네요.
- 함수의 기능 분리가 필요해보여요.
- 유지보수, 확장성을 고려해보셨으면 좋겠어요.
    - 프로젝트에 기능이나 요소가 추가될 경우에 코드를 어느 정도 추가 및 수정을 하는 정도에 따라 유지보수와 확장성을 판단하게 됩니다. 
해당 코드는 과일 종류와 주스 종류가 추가될 경우, 모든 객체를 다 수정해야하기 때문에 유지보수와 확장성에 좋은 코드는 아닌 거 같습니다.

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +}
- `fileprivate`을 사용하신 이유가 무엇인가요?
- `Fruit`이라는 사용자 정의 타입이 `stock`, 즉 스스로의 재고수량을 프로퍼티로 지정되어 있는 것이 객체지향 관점에서는 어색합니다. 재고 수량은 `FruitStore`에서 관리해야할 거 같습니다.

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
- class를 사용하신 이유가 있으신가요?
- final 키워드가 없네요. 만약 final 키워드에 대해서 모르신다면, [Increasing Performance by Reducing Dynamic Dispatch](https://developer.apple.com/swift/blog/?id=27) 문서를 읽어보세요!

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var mango = Fruit(name: "망고", stock: 10)
- 딸기, 바나나, 파인애플, 키워, 망고 외에 다른 과일이 추가된다면 어떻게 관리하실 건가요?
- 저라면 주스메뉴(딸기주스, 바나나주스, 등등..)에 대한 객체와 과일(딸기, 바나나, 키위, 등등..)에 대한 객체를 열거형으로 만들고 관리할 거 같습니다. 
- 이 부분은 위에서 코멘트 드린 확장성, 유지보수 관리에 대한 고민을 충분히 하시고 리펙토링하셨으면 좋겠습니다.

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
- 고민하신 부분에서 딕셔너리를 사용하셨다가 접근이 불편해서 이렇게 바꾸신 거 같네요. 하지만 딕셔너리를 활용하면 확장성, 유지보수에도 좋고, 코드도 줄일 수 있습니다. `stock` 프로퍼티를 딕셔너리 타입으로 바꿔보시는 걸 추천드립니다!

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeStock(_ fruit: String, to number: Int) throws {
- `changeStock()`은 과일 개수를 바꿔주는 기능으로 보이는데, 과일을 사용하는 기능(빼는 기능)과 과일을 추가하는 기능의 분리가 필요해보입니다.
- 매개변수는 `number` 대신 개수를 표현하는 네이밍이 적절해보입니다.

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        case "망코":
오타! ㅎㅎ

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/InputError.swift
> +//  Created by 표현수 on 2023/05/08.
팀원 이름이 들어갔으면 좋겠습니다~

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/InputError.swift
> +}
- 전체적으로 타입명부터 case명까지 무슨 에러를 뜻하는지 전혀 감이 오지 않습니다.
- `nameError`는 `name`이 `nil`인 상태인 에러인지, 다른 이름이 들어왔다는 에러인지 / `stockError`는 `stock`이 `nil`인 상태인 에러인지, `stock` 개수가 마이너스 상태인 에러인지 등등... 네이밍만 보고 감이 오지 않네요. 구체적인 네이밍이 필요해보입니다.

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
`struct`를 사용하신 이유가 있나요?

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
불필요한 여백이 보이네요~

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            throw InputError.nameError
- JuiceMaker 타입이 쥬스를 만드는 기능에서 과일 재고를 체크하고, 과일을 차감하는 기능은 불필요해보이네요. 이 기능은 FruitStore가 해야할 기능으로 보입니다. 
- 이 경우에도 다른 주스가 추가될 경우, case가 계속 생겨 자원 낭비가 우려되는 코드네요.

2023-05-09 05:49 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
- `do-catch문`을 따로 빼두셨군요. 에러를 구현해야 하는 이유는 무엇일까요?
- 저는 어떠한 기능을 구현할 때, 그 기능에 문제가 생길 시, 사용자에게 알려주기 위해 구현해야 한다고 생각합니다. 그래서 이런 식으로 따로 뺄 것이 아니라, 위의 `makeJuice()`에서 구현해야 한다고 생각이 들어요. 주스를 만들 때 일어나는 오류기 때문이죠!

2023-05-11 02:08 UTC, JusBug commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +}
동일한 소스파일에서만 해당 인스턴스에 접근 가능하도록 하기 위해 사용했습니다.

2023-05-11 02:14 UTC, JusBug commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
FruitStore의 인스턴스가 여러개라도 과일의 재고가 항상 동일해야 한다고 생각하여 참조타입인 class를 사용하였습니다. final 키워드는 아직 필요하지 않아서 이후 과정에서 참고하겠습니다.

2023-05-11 02:17 UTC, JusBug commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
JuiceMaker는 상속이 필요가 없고, FruitStore 처럼 값을 참조할 필요도 없다고 생각하여 struct를 사용하였습니다.

2023-05-11 02:17 UTC, JusBug commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
수정했습니다.

2023-05-11 02:18 UTC, JusBug commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
예기치 못한 다양한 오류로 인해 프로그램이 강제로 종료되는 것을 막고 사용자와의 상호작용을 통해 오류를 해결하고 제어할 수 있도록 만들기 위해서 사용합니다.

2023-05-11 03:44 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var mango = Fruit(name: "망고", stock: 10)
Fruit를 열거형으로 바꾸고 과일을 케이스 별로 선언하였습니다. (과일이 추가될거라는 생각은 못 했던 것 같습니다. )
유지보수를 쉽게 하기 위해서, fruitStock라는 딕셔너리를 만들 때 Fruit.allCases로 열거형을 배열로 사용하고, 딕셔너리의 uniqueKeysWithValues를 사용하여 배열의 요소를 키로, Int 10을 값으로 주어, 새로운 과일을 추가할 때 Fruit의 새로운 케이스만 추가하여도 fruitStock에 과일이 추가되도록 수정하였습니다.

2023-05-11 03:44 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
Fruit를 열거형으로 선언하고, stock을 딕셔너리로 하니 코드가 많이 줄었습니다.

2023-05-11 03:46 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeStock(_ fruit: String, to number: Int) throws {
과일을 추가하는 addFruits()와 과일을 사용하는 useFruits()로 기능을 분리하였습니다.
number대신 addStock과 useStock으로 리네임하였습니다.

2023-05-11 03:58 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/InputError.swift
> +}
Error타입의 이름을 JuiceMaker를 사용할 때 발생하는 에러라고 하여 JuiceMakerError로 리네임하였고, Fruit에 없는 과일 경우에 발생하는 nonExistentFruitError, 재고가 부족하다는 outOfStockError, Juice에 없는 쥬스일 경우 발생하는 nonExistentJuiceError 케이스를 추가하였습니다.

2023-05-11 04:00 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            throw InputError.nameError
9. juiceRecipe라는 Juice타입을 키로, [Fruit: Int]를 값으로 가지는 딕셔너리를 만들어 재료를 선언하고 쥬스에 맞는 재료를 가져와 FruitStore의 useFruits함수를 사용하여 쥬스를 만드는 방식으로 수정하였습니다.

2023-05-11 08:56 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
나중에 `ARC` 개념 공부해보시면서 추후 프로젝트에서 고민해보세요!

2023-05-11 08:57 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var mango = Fruit(name: "망고", stock: 10)
allCases를 사용하신 점 너무 좋습니다!

2023-05-11 09:01 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/InputError.swift
> +}
case 네이밍 마다 끝에 Error가 붙고 있습니다. 이미 Error 타입인데 중복되는 네이밍을 적용해야할 이유가 있을까요?

2023-05-11 09:11 UTC, jsa0224 approved these changes
수정해주신 부분 잘 보았습니다! 저스버그, 에릭!
몇 가지 아쉬운 부분들이 있어 코멘트 남겼습니다!
확인해보시고, 어려우신 부분 있으시면 언제든 디엠 남겨주세요!

2023-05-11 09:11 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    ]
`딕셔너리`를 중첩되게 구현하셔서 더 값을 접근하는 게 어려워보입니다.
이 부분을 `Juice` 타입에서 `연산 프로퍼티`로 리팩토링 해보시면 값 접근 방식이 쉬워지실 거 같네요!

2023-05-11 09:11 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        guard let ingredient = juiceRecipe[juice] else { throw JuiceMakerError.nonExistentJuiceError }
```suggestion
    private func getIngredient(_ juice: Juice) throws -> [Fruit: Int] {
        guard let ingredient = juiceRecipe[juice] else { throw JuiceMakerError.nonExistentJuiceError }
```

띄어쓰기가 적용되지 않았어요!

2023-05-11 09:11 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +refact: (addStock, useStock) -> amount /(addFruit, useFruit)-> fruit 네이밍 수정
이 부분은 커밋 메세지인가요? 잘못 들어간 텍스트 같습니다.

2023-05-11 09:46 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +refact: (addStock, useStock) -> amount /(addFruit, useFruit)-> fruit 네이밍 수정
넵! 수정하였습니다!

2023-05-11 09:46 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        guard let ingredient = juiceRecipe[juice] else { throw JuiceMakerError.nonExistentJuiceError }
수정하였습니다!

2023-05-11 11:11 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    ]
Juice 타입에 ingredients 프로퍼티를 추가하여 케이스 별로 재료를 반환해주었습니다.

2023-05-12 03:07 UTC, jsa0224 commented
수고 많으셨습니다, 저스버그, 에릭!
이번 스탭은 여기서 마무리 지으셔도 될 거 같습니다👍
다음 스탭도 화이팅입니다!

2023-05-12 03:07 UTC, merged