쥬스 메이커 [Step1] EtialMoon, 비모
yagom-academy/ios-juice-maker pull request #320
Opened 2023-05-11 01:41 UTC by bubblecocoa

@jsa0224 
안녕하세요 솜!
쥬스 메이커 프로젝트 Step1 PR 요청드립니다.
3주간 잘 부탁드립니다 🙇

---

### 고민했던 점
#### `FruitStore`에 `과일 저장소 타입` 이라는 주석
코드를 받아서 처음 열어본 순간부터 해당 주석이 있었습니다.
처음에는 저장소 타입이라고 생각하여 하나의 과일과 수량을 담당하고 해당 타입을 계속 생성하여 사용하면 된다고 생각했습니다.
나중에는 Store 라는 단어에 집중하여 여러가지 과일을 관리할 수 있도록 저장 프로퍼티에 딕셔너리 타입으로 과일과 수량 형태를 가지도록 변경하였습니다.

#### `enum`내의 연산 프로퍼티
쥬스 제작을 위한 과일 종류와 필요 수량을 저장할 수 있도록 `JuiceRecipe`라는 타입을 생성하였습니다.
하지만 쥬스 제작에 필요한 레시피가 불변인 점과, 해당 타입을 선언하게 되면 `JuiceMaker`타입 내에 코드량이 방대해지고, 한 번 수정을 위해서는 여러곳의 코드가 변경되어야 한다는 점을 인지하여 해당 타입은 다시 제거했습니다.
이후 `JuiceMenu` 타입 내에 연산 프로퍼티로 `recipe`를 추가했습니다.

---

### 조언을 얻고싶은 부분
#### error파일 위치를 어디로 할까요?
프로젝트를 받았을때 3개의 그룹(`Controller`, `Model`, `View`)으로 구분되어 있는데, 이번 프로젝트 진행 중 작성하게 된 에러 파일을 어디에 위치시켜야 하는지 고민이 되었습니다.
`Model`간의 연산 중에 생긴 에러라 해당 그룹 내에 위치시켜야 하나 라는 고민을 하였으나 '에러도 모델인가?' 라는 생각에 일단은 `Error`라는 그룹을 따로 생성하여 위치시켰습니다.
이러한 상황에서 Error파일은 어디에 위치시키는게 좋을까요?

#### catch switch error {}
에러를 받을 때 `catch` 안에서 `switch error {}`로 받게 됩니다. 그런데 `switch` 뒤에 `error`라는 이름이 고정적으로 사용되는 것같은데 왜 그렇게 사용하는지에 대한 정보를 어디서 구할 수 있는지 모르겠습니다.

2023-05-11 08:12 UTC, jsa0224 requested changes
안녕하세요! 비모, 문!
프로젝트 잘 보았습니다.
3주동안 잘 부탁드립니다😊

## 고민했던 부분에 대한 답변
이번 프로젝트는 효율성의 측면도 중요하지만 확장성과 유지보수 관점을 익혀가는 것이 중요하다고 생각이 듭니다. 비모와 문이 고민하셨던 부분들이 해당 부분과 일치하고 중요한 고민들을 생각하시면서 프로젝트를 진행하셨네요👍

## 조언을 얻고 싶은 부분에 대한 답변
> **error파일 위치를 어디로 할까요?**
프로젝트를 받았을때 3개의 그룹(Controller, Model, View)으로 구분되어 있는데, 이번 프로젝트 진행 중 작성하게 된 에러 파일을 어디에 위치시켜야 하는지 고민이 되었습니다.
Model간의 연산 중에 생긴 에러라 해당 그룹 내에 위치시켜야 하나 라는 고민을 하였으나 '에러도 모델인가?' 라는 생각에 일단은 Error라는 그룹을 따로 생성하여 위치시켰습니다.
이러한 상황에서 Error파일은 어디에 위치시키는게 좋을까요?

이 부분은 아래 코멘트에 답변을 남겼지만, 모호한 답변이 될 수 있어 통화로 이야기 나눠보는 것이 좋을 거 같습니다.

> **catch switch error {}**
에러를 받을 때 catch 안에서 switch error {}로 받게 됩니다. 그런데 switch 뒤에 error라는 이름이 고정적으로 사용되는 것같은데 왜 그렇게 사용하는지에 대한 정보를 어디서 구할 수 있는지 모르겠습니다.

`switch문`으로 에러 처리를 할 때, `사용자 정의 유형`을 포함하여 `모든 오류 준수 유형`을 적용할 수 있습니다. 
![스크린샷 2023-05-11 오후 5 08 25](https://github.com/yagom-academy/ios-juice-maker/assets/94514250/eee36bf0-b89d-457c-bc20-ee3e3c9a9464)

그래서 모든 오류 준수 유형을 적용해야 하기에 error로 표기되는 걸로 알고 있습니다.
[Error Pattern Matching in Swift](https://www.vadimbulavin.com/swift-error-pattern-matching/https://www.vadimbulavin.com/swift-error-pattern-matching/) 문서가 도움이 될 거 같습니다.

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +}
과일이라는 공통점으로 열거형을 구현한 점 좋습니다👍

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -import Foundation
불필요한 프레임워크 삭제도 좋네요👍

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
재고 개수가 10개가 아닌 다른 개수일 경우도 고려해보셨군요👍

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
- 메서드 네이밍이 계산기의 기능처럼 보입니다🤔 
과일 저장소 입장에서는 과일이 더하고 빼는 개념보다는 증가하고 감소되는 물질이 아닐까요?
- 두 메서드 모두 같은 기능의 `guard문`을 사용하고 있네요. 기능 분리를 해서 하나의 메서드로 활용해보는 건 어떠신가요?

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
- class로 구현하신 이유가 있으실까요?
- final 키워드가 없네요. 만약 final 키워드에 대해서 모르신다면, [Increasing Performance by Reducing Dynamic Dispatch](https://developer.apple.com/swift/blog/?id=27) 문서를 읽어보세요!

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
`struct`로 구현하신 이유가 있으실까요?

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
아직은 MVC 아키텍처보다 전에 하셨던 커멘트툴 프로젝트가 익숙하셔서 `do-catch문`을 여기서 구현해주신 거 같네요! 
해당 오류문을 사용자에게 보여주어야 할 때 어떻게 설계하셔야할지, Step 2에서 고민해보셨으면 좋겠습니다.

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
이 부분은 `JuiceMaker`에서 해야할 기능으로 적절하지 않은 거 같습니다.
객체지향적 관점으로 `JuiceMaker`가 쥬스 가게라고 가정했을 때, 과일 저장소에서 필요한 과일만큼 사용하면서 동시에 과일이 부족한 지 체크할 필요는 없다고 생각이 드네요. 
이 기능은 `FruitStore`에서 해야할 기능이라고 생각이 듭니다.

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMenu.swift
> +    }
enum에서 `연산 프로퍼티`를 활용해보셨군요!
확장성과 유지보수를 고민한 흔적이 보이는 코드입니다👍

2023-05-11 08:12 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Error/JuiceError.swift
> +}
- 이 객체 위치가 고민 되셨군요! 보통은 해당 객체에서만 사용되는 오류문이라면 그 객체 위에 구현하는 편입니다. (텍스트로 설명하려니 어렵네요. 나중에 시간 되실 때 통화로 설명드리겠습니다.) 지금 상태로는 `JuiceMaker` 파일 안에 구현해도 좋을 거 같습니다.
- `no`, `not` 보다는 `empty`, `out of~` 와 같은 네이밍이 적절해보입니다.

2023-05-11 10:35 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
MVC 아키텍처로 프로젝트가 제공되긴 했지만, Step 1의 경우 커맨드툴 프로젝트에 유사한듯 하여 이렇게 작성했습니다!
Step 2 작업시 해당 리뷰 충분히 고민해보도록 하겠습니다.

2023-05-11 11:37 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Error/JuiceError.swift
> +}
noFruitInFruitStore -> nonexistentFruit
notEnoughFruitStock -> shortageFruitStock
로 변경하였습니다!

2023-05-11 11:39 UTC, hojun-jo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
add -> addStock
subtract -> useStock
메서드 네이밍은 각각 위와 같이 변경하였습니다.
`guard문`은 receiveStock이라는 메서드로 분리했습니다.

2023-05-11 12:24 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
쥬스를 만들기 전 과일 재고 확인,
과일을 사용시 과일 재고 확인
이 두가지 케이스 모두에 대해 처리했습니다.

2023-05-11 12:33 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
저장 프로퍼티 `fruits` 내의 값이 빈번하게 수정 될 수 있어 `class`를 선택했습니다.
해당 클래스는 상속을 받을 필요가 없어 코멘트 주신 내용 참고하여 `final`처리 했습니다.

2023-05-11 12:35 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
내부 값이 변경 될 일이 없고, 정해진 역할만 수행하기 때문에 `struct`를 선택했습니다.
저장 프로퍼티인 `fruitStore`의 경우 `class`타입이기 때문에 내용 변경에 문제가 없었습니다.

2023-05-11 12:39 UTC, bubblecocoa commented
@jsa0224 
코멘트 주신 부분 모두 확인하였습니다!
수정된 부분 확인 부탁드립니다! 감사합니다.

2023-05-12 06:35 UTC, jsa0224 commented
수고하셨습니다! 비모, 문~
이번 스탭 진행하시면서 객체지향, 확장성, 유지보수 관점을 많이 활용해보신 거 같습니다.
다음 스탭도 화이팅입니다!

2023-05-12 06:35 UTC, merged