쥬스 메이커 [STEP2] jusbug, Erick
yagom-academy/ios-juice-maker pull request #322
Opened 2023-05-15 03:10 UTC by JusBug

@jsa0224 
안녕하세요 Som!! 
Step2 PR 보내드립니다. 
이번에도 좋은 리뷰 부탁드립니다😀

### 고민한 점
***ViewController 화면전환***
- 처음에 Navigation push, Segue, present 등 여러 방식을 고민했습니다.
- 처음에는 기본적인 present 방식으로 구현하려고 했으나, back button을 따로 생성해야만 했습니다. 반면 Navigation push의 경우, 스토리보드에 이미 Embed In되어 있고 back button을 따로 설정해주지 않아도 자동으로 활성화되기 때문에 Navigation push 방식을 사용하였습니다.
```swift
func pushFixStockViewController() {
    guard let pushViewController = self.storyboard?.instantiateViewController(withIdentifier: "StockCorrectionViewController") else { fatalError("해당 뷰컨트롤러ID를 가진 뷰컨트롤러가 스토리보드에 없습니다.") }
    self.navigationController?.pushViewController(pushViewController, animated: true)
}
```

***currentTitle***
- 처음에는 버튼 하나하나에 따로 @IBAction 함수를 만들어 액션을 처리했지만 코드가 너무 길어지고 새로운 버튼이 생긴다면 새로운 함수를 만들어줘야 했기에 button의 .currentTitle 프로퍼티를 사용하여 버튼의 title을 받아와 switch문으로 분기처리 해주었습니다.

```swift
@IBAction func orderJuiceButton(_ sender: UIButton) {
        guard let title = sender.currentTitle else { fatalError("버튼이 설정되지 않았습니다.") }
        
        switch title {
        case "딸기쥬스 주문":
            orderJuice(.strawberryJuice)
        case "바나나쥬스 주문":
            orderJuice(.bananaJuice)
        case "파인애플쥬스 주문":
            orderJuice(.pineappleJuice)
        case "키위쥬스 주문":
            orderJuice(.kiwiJuice)
        case "망고쥬스 주문":
            orderJuice(.mangoJuice)
        case "딸바쥬스 주문":
            orderJuice(.strawberryBananaJuice)
        case "망키쥬스 주문":
            orderJuice(.mangoKiwiJuice)
        default:
            break
        }
    }
```
***

### 해결이 안된 점
추후 수정 예정

### 조언을 얻고 싶은 점
***화면이동***
Navigation push, Segue, present 등 여러 화면전환 방식이 있는데 각자의 장단점이 무엇인지 정확하게 파악하기 어려워서 앞으로도 버튼 액션을 생성할 때 무엇을 우선으로 사용해야 하는지 고민이 됩니다. Som은 화면이동 버튼을 생성할 때 주로 어떤 방식을 이용하고 그 이유가 있다면 무엇인지 궁금합니다.

***에러처리***
사용자에게 보여지는 에러는 outOfStock만 있다고 생각되어 나머지 에러 케이스는 삭제하였습니다.
나머지 guard문에서 발생하는 예외 케이스 에러들은 사용자가 앱을 사용 중에 발생하는 것이 아닌, 개발자의 설정에 의해 나오는 에러임으로 개발자가 알아야 한다고 생각되어 에러 처리를 하는 것이 아닌 fatalError를 사용하여 프로그램을 정지하고 메세지를 주는 형식으로 변경하였는데 이런식의 에러처리도 괜찮을지 조언을 얻고 싶습니다.

2023-05-15 13:58 UTC, jsa0224 requested changes
안녕하세요! 저스버그, 에릭!
프로젝트 잘 보았습니다. 수고 많으셨어요!

## 고민하신 부분에 대한 답변
> ***ViewController 화면전환***

그렇죠! 이미 스토리보드에서 `navigation` 방식으로 구현이 되어 있으니, 이 부분은 `push` 방식이 적절한 거 같습니다.

> ***currentTitle***

이 부분 너무 좋았습니다! 
`tag`는 버튼에 `Int` 값을 주어, 각각 추적하는 방식도 있습니다. 하지만 휴먼에러가 발생할 수 있는 여지도 많아 저는 위험한 방법이라고 생각이 들어서, 이 부분을 어떻게 조언을 드릴까 많이 고민했는데 잘 구현하신 거 같아요!

한 가지 조언을 드리자면, 저는 `Juice` 타입에서 버튼 타이틀 관련한 연산 프로퍼티를 만든 후, 비교해서 해당 주스를 주문하도록 구현할 거 같아요 ㅎㅎ!

## 조언을 얻고 싶은 부분에 대한 답변
> ***화면이동***
Navigation push, Segue, present 등 여러 화면전환 방식이 있는데 각자의 장단점이 무엇인지 정확하게 파악하기 어려워서 앞으로도 버튼 액션을 생성할 때 무엇을 우선으로 사용해야 하는지 고민이 됩니다. Som은 화면이동 버튼을 생성할 때 주로 어떤 방식을 이용하고 그 이유가 있다면 무엇인지 궁금합니다.

이 부분은 활동학습에서도 배우는 걸로 알고 있습니다. 
저는 주로 수정이나 추가가되는 화면은 `modal`, 뎁스를 타고 들어가서 해당 정보를 보여주는 화면은 `navigation`으로 구현하고 있습니다. 
[Modality](https://developer.apple.com/design/human-interface-guidelines/modality) vs [Navigation](https://codershigh.github.io/guidelines/ios/human-interface-guidelines/interaction/navigation/index.html) 언제 사용해야할지 한 번 읽어보시는 걸 추천드려요! 

> ***에러처리***
사용자에게 보여지는 에러는 outOfStock만 있다고 생각되어 나머지 에러 케이스는 삭제하였습니다.
나머지 guard문에서 발생하는 예외 케이스 에러들은 사용자가 앱을 사용 중에 발생하는 것이 아닌, 개발자의 설정에 의해 나오는 에러임으로 개발자가 알아야 한다고 생각되어 에러 처리를 하는 것이 아닌 fatalError를 사용하여 프로그램을 정지하고 메세지를 주는 형식으로 변경하였는데 이런식의 에러처리도 괜찮을지 조언을 얻고 싶습니다.

이 부분은 아래 코멘트에 남기기도 했지만, 사용자로부터 앱 강제 종료는 좋은 이벤트라고 생각이 들지 않습니다.
여러분이 구현하신 `Alert`은 무슨 기능을 할까요? `Alert`은 언제 쓰면 좋을까요? 
[Alerts](https://developer.apple.com/design/human-interface-guidelines/alerts)에 대한 HIG 문서도 한 번 읽어보세요! 
UI 작업을 하면서 HIG 많이 접하시게 되실 거예요!

## 조언드리고 싶은 부분
![스크린샷 2023-05-15 오후 10 12 24](https://github.com/yagom-academy/ios-juice-maker/assets/94514250/89ec218f-7f09-40cf-a68c-917c967755a0)

여러분의 프로젝트를 사용하면서, 재고가 부족할 경우 재고 추가 화면을 넘겼을 때 이런 에러가 발생하더라고요. 
아래에서도 이 에러에 대한 언급을 하긴 했지만, 에러가 나는 프로젝트를 PR로 제출하시는 건 좋지 않다고 생각이 듭니다.
여러분도 테스트하시면서 이 에러는 만나보셨을 거라고 추측이 됩니다. 
팀 스스로 해결하시는 게 가장 좋은 방법이지만, 해결이 안 되실 경우 저에게 디엠을 주셨으면 좋을 거 같습니다. 

ps. 저스버그 이모지 프사 너무 귀엽네요😆

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var mangoStockLabel: UILabel!
- 해당 부분 은닉화가 되지 않았네요!
- `@IBOutlet`의 형태가 왜 `weak var`이며, 타입 뒤에 `!`를 왜 붙이는 지 공부해보셨으면 좋겠네요.

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
무슨 ViewController인지 명확한 네이밍이 필요해보여요!

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
- 보통 `Button Action` 관련 메서드는 `누른다`의 의미를 많이 씁니다 ㅎㅎ
- 은닉화가 되지 않았네요!
- `currentTitle()` 메서드 활용 너무 좋네요! 저도 모르는 기능이었는데, 덕분에 알아갑니다👍

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
이 부분도 네이밍! 위와 동일한 이유입니다.

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`showStock()`은 사용자 측면으로 생각하신 네이밍인 거 같아요! 하지만 행하는 주체가 `ViewController`이기 때문에, `ViewController` 측면에서는 `text`를 구성해주는 기능이 아닐까 싶습니다! 한 번 생각해보시고, 반영해주셨으면 좋겠습니다!

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
에러 처리 Good👍

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
- `fix`는 고치다 라는 의미가 강해서 재고가 마치 기계 부품 같다는 생각이 많이 드네요! `바꾸다`라는 의미를 가진 네이밍으로 수정해보셨으면 좋겠습니다!
- `fatalError`에 대해서 공부해보셨나요? `fatalError`는 바로 앱이 강제 종료가 되는 오류문인데, 사용자 입장에서 그 방법이 좋을까요? 고민해보셨으면 좋겠습니다.
- 스토리보드로 추적해서 푸시되는 방식인가요? 이건 저도 처음 보는 방식이네요! 실행해보니, `withIdentifier`를 찾을 수 없다는 오류가 나옵니다. 아마도 이 화면에 대한 `ViewController`를 생성하지 않으셔서 나는 오류 같습니다. 객체를 생성해보세요!

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>      }
- 얼럿 창을 띄우는 기능인데, `order`이라는 네이밍이 적절한 지 모르겠습니다. 
- `UIAlertController` 및 다른 기능들이 여러 번 사용되고 있는데, 재활용성을 고려해서 구현해보셔도 좋을 거 같아요!

2023-05-15 13:58 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func getStock(_ fruit: Fruit) -> Int {
`get`은 다른 프로그래밍 언어에서 다른 의미로 쓰이는 경우들이 많아 잘 활용되지 않는 네이밍입니다. 다른 네이밍을 고민해보셨으면 좋겠습니다!

2023-05-16 02:50 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var mangoStockLabel: UILabel!
- @IBOutlet private weak var 형식으로 은닉화 하였습니다.
- `weak`를 사용하는 이유는 VC가 View를 강함참조하고, View는 View 객체를 강한 참조하니 VC가 View 객체를 강한참조한다면 강한참조순환으로 메모리 누수가 발생할 수 있기 때문에 VC는 View 객체를 약한 참조 해야하여 `weak`를 사용해야 합니다.
- IBoutlet var 타입은 nil이 존재할 수 없습니다. 즉, 이니셜라이져를 주어져야 하기 때문에 ViewController에서는 옵셔널로 타입을 꼭 명시해줘야합니다. 그리고 암시적인 옵셔널 프로퍼티들은 init이 진행된 이후에 nil이 될 수도 있습니다만 Storyboard에 해당 값들이 먼저 assign 되어야만 합니다.
- 뷰객체가 unwrapping 되어 있음을 암시적으로 알려줘야 하기 때문에 !를 사용해야 합니다. 옵셔널 타입으로 지정하기 위해서 ?도 사용해도 됩니다.

2023-05-16 02:51 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet weak var mangoStockLabel: UILabel!
<참고 링크>
https://co-dong.tistory.com/60
https://www.quora.com/What-is-the-point-of-using-weak-variables-in-IBOutlets

2023-05-16 02:55 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
JuiceMakerViewController으로 수정했습니다.

2023-05-16 03:00 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
- orderJuiceButtonTapped으로 수정했습니다.
- 은닉화 했습니다.

2023-05-16 03:00 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
fixStockButtonTapped으로 수정했습니다.

2023-05-16 03:02 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`updateStock'으로 수정했습니다.

2023-05-16 03:08 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
- `pushChangeStockViewController`로 리네임하였습니다.
- fatalError를 사용한 이유는 위와 같은 에러는 스토리보드 ID의 오류이기 때문에 사용자가 아닌 개발자가 알아야하는 에러라고 생각되어 fatalError로 앱을 강제 종료하여 잘못된 것을 바로 알 수 있도록 fatalError를 사용하였습니다. 
- 스토리보드 ID를 추적하여 푸시하는 방식입니다. 오류는 스토리보드ID가 달라서 발생한 것 같습니다.
- 스토리보드 ID를 수정하여 오류를 해결했습니다.

2023-05-16 03:19 UTC, h-suo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func getStock(_ fruit: Fruit) -> Int {
- `get`을 뺴고 `stock`으로 리네임하였습니다.
참고링크: https://soojin.ro/blog/english-for-developers-swift

2023-05-16 03:22 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>      }
- popUpSuccessMessage, popUpFailMessage 으로 수정했습니다.

2023-05-16 06:10 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>      }
- 추후에 Step3에서 자주 반복되는 기능은 얼렛 함수를 따로 생성하여 코드를 수정하겠습니다.

2023-05-16 07:42 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
Tapped라는 네이밍은 쥬스를 주문하는 버튼이 눌러진 상태, 즉 과거에 눌러진 걸 나타내는 네이밍으로도 해석이 될 여지가 있어보입니다! 
`didTap`, `tap`과 같은 의미가 주 기능이니, 네이밍 중 앞쪽에 배치되어야 할 거 같습니다.

2023-05-16 07:44 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
이 부분도 아래 코멘트에 따라 `fix`라는 네이밍 대신 다른 네이밍으로 수정해보셨으면 좋겠습니다!

2023-05-16 08:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
업데이트 된다는 의미로 보기에는 모호한 거 같습니다.
위의 메서드는 `ViewController`가 `text`를 구성해주는 기능을 하고 있는 거 같습니다.

2023-05-16 08:33 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
fatalError에 대한 제 생각은 다릅니다!
AppStore 리젝사유 중 가장 중요한 부분은 앱이 중간에 비정상적으로 튕기거나 꺼지는 경우입니다. 
fatalError는 이 부분에 대한 위험성이 있을 에러 처리 방법이라고 생각이 드네요!
자세한 사항은 [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/#introduction:~:text=a%20living%2C%20too.-,Before%20You%20Submit,-To%20help%20your) 문서를 읽어보세요!

2023-05-18 02:05 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`orderJuiceButtonTap`으로 리네임하였습니다!

2023-05-18 02:06 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`changeStockButtonTap`으로 리네임하였습니다!

2023-05-18 02:06 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
텍스트를 구성해주다라는 의미인 `composeText`로 리네임하였습니다!

2023-05-18 02:18 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
넵! `fatalError`를 모두 삭제하고 return으로 처리했습니다!
그리고 return으로 함수를 종료시키기 이전에 print로 경고 메세지만 출력해주는 코드로 수정하였습니다!

2023-05-18 08:36 UTC, jsa0224 commented
수고하셨습니다👏
다음 스텝 진행하시면 됩니다!

2023-05-18 08:36 UTC, merged