쥬스 메이커 [Step2] EtialMoon, 비모
yagom-academy/ios-juice-maker pull request #327
Opened 2023-05-16 11:06 UTC by bubblecocoa

@jsa0224 
안녕하세요 Som!
EtialMoon & 비모입니다.
Step2 PR 보내드립니다.
잘 부탁드립니다. 🙇

---

### 고민했던 점
#### 7개의 쥬스 버튼
처음에는 모든 쥬스 버튼에 대해 각각의 `@IBAction` 메서드를 만들었습니다. 하지만 쥬스 종류만 다를 뿐 모든 동작이 동일했고, `do-catch`문을 작성하는 과정에서 코드가 너무 길어지는것을 인지했습니다. 그러던 중 `storyboard`의 `Attributes inspector`에 있는 `tag`라는 요소를 알게 되었습니다. 이것에 부여된 값은 `ViewController`에서 `sender.tag`로 사용할 수 있었기때문에 `JuiceMenu` 열거형의 타입을 `Int`로 지정하여 `rawValue`로 메뉴를 식별하여 처리할 수 있도록 했습니다.
```swift
// 개선 전 코드
@IBAction func orderStrawberryJuice(_ sender: UIButton) {
    if juiceMaker.make(juice: .strawberryJuice) {
        setFruitStockLabel()
        present(alertJuiceReady(menu: .strawberryJuice), animated: true)
    } else {
        present(alertShortageStock(), animated: true)
    }
}

@IBAction func orderBananaJuice(_ sender: UIButton) {
    if juiceMaker.make(juice: .bananaJuice) {
        setFruitStockLabel()
        present(alertJuiceReady(menu: .bananaJuice), animated: true)
    } else {
        present(alertShortageStock(), animated: true)
    }
}
...
```
```swift
// 개선 후 코드 
@IBAction func orderJuice(_ sender: UIButton) {
    guard let menu = JuiceMenu(rawValue: sender.tag) else {
        return
    }

    if juiceMaker.make(juice: menu) {
        setFruitStockLabel()
        present(alertJuiceReady(menu: menu), animated: true)
    } else {
        present(alertShortageStock(), animated: true)
    }
}
```
결과적으로 7개의 메서드가 1개로 줄어드는 개선이 있었습니다.

#### enum의 연산프로퍼티
쥬스 제작후 `strawberry 쥬스 나왔습니다!` 얼럿이 출력됩니다. 처음에는 뷰컨트롤러 안에 `switch`문을 작성해서 전환해주는 작업을 할까 했으나 step1에서 `recipe`에 대한 연산 프로퍼티를 `JuiceMenu`안에 작성했던것이 기억났습니다.
```swift
// JuiceMenu에 연산 프로퍼티 추가 작성
var name: String {
    switch self {
    case .strawberryJuice:
        return "딸기쥬스"
    case .bananaJuice:
        return "바나나쥬스"
    case .kiwiJuice:
        return "키위쥬스"
    case .pineappleJuice:
        return "파인애플쥬스"
    case .strawberryBananaJuice:
        return "딸바쥬스"
    case .mangoJuice:
        return "망고쥬스"
    case .mangoKiwiJuice:
        return "망키쥬스"
    }
}
```
```swift
// 기존 코드
let juiceAlert = UIAlertController(title: "제조 완료", message: "\(menu) 쥬스 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)

// 변경 코드
let juiceAlert = UIAlertController(title: "제조 완료", message: "\(menu.name) 나왔습니다! 맛있게 드세요!", preferredStyle: .alert)
```
이렇게 변경함에 따라 `딸기쥬스 나왔습니다!`가 출력되는 결과를 얻을 수 있었습니다.

#### 얼럿에서 화면 전환
화면 전환하는 방법을 스토리보드에서 세그를 이용해 전환하는 방법만 알고 있었습니다. 하지만 얼럿에서 화면 전환을 하기 위해서는 이 방법으로 불가능하기 때문에 다른 방법을 찾아 보았습니다. `FruitStoreViewController` 파일을 만든 후 스토리보드에서 과일 재고를 수정하는 화면의 `Identity inspector`에서 클래스를 `FruitStoreViewController`로 설정했습니다. 그리고 지정된 식별자에 해당하는 뷰 컨트롤러를 리턴하는 `instantiateViewController`를 이용해 새 화면을 보여줄 수 있도록 하였습니다.
```swift
private func moveToFruitStoreViewController() {
    guard let fruitStoreViewController = self.storyboard?.instantiateViewController(withIdentifier: "FruitStoreViewController") as? FruitStoreViewController else {
        return
    }

    fruitStoreViewController.modalTransitionStyle = .coverVertical

    self.present(fruitStoreViewController, animated: true)
}
```
이렇게 작업했을 때 `FruitStoreViewController`를 찾을 수 없다는 에러가 출력되었는데, 스토리보드에서 해당 뷰컨트롤러에 연결되어있는 `Scene`의 `Identity inspector`에서 `Storyboard ID`항목에 `FruitStoreViewController`를 추가해주어 에러를 해결했습니다.
이로 인해 `withIdentifier: "FruitStoreViewController"` 코드가 `Storyboard ID`를 찾는다는 것을 알 수 있었습니다.

---

### 조언을 얻고싶은 부분
#### 네이밍
그동안 커맨드라인 프로젝트로 진행하며 나름 이름 짓는것에 익숙해졌다고 생각했습니다. 하지만 PR을 보낸 시점에서 저희 조가 느끼기엔 뭔가 네이밍이 어색하다는 느낌을 받고 있습니다. 나름 고민해서 지은 이름들인데 `ViewController`의 역할에 익숙하지 않아 이런 상태가 된 것 같습니다. 적절한 이름에 대해 힌트가 필요한 시점인 것 같습니다 😅😅😅

#### 컨트롤러?
얼럿 표시나 레이블에 값을 세팅하는 일 모두 컨트롤러에서 하는 일은 맞는 것같은데 프로젝트가 조금만 더 복잡해져도 컨트롤러의 크기가 너무 커질 것같습니다. 계속 이렇게 진행하는게 맞을까요? 아니면 코드를 별도로 분리할 방법이 있을까요?

2023-05-17 06:16 UTC, jsa0224 requested changes
안녕하세요! 비모, 문!
프로젝트 잘 보았습니다.

## 고민하신 부분에 대한 답변

코드를 효율적으로 개선하려고 노력하신 점이 돋보입니다👍
하지만 코드를 줄이는 것과 동시에, JuiceMenu가 Int 타입의 rawVaule를 갖는 것이 적절한지에 대한 고민을 해보셨으면 좋겠습니다. 
해보셨다면, 해당 코멘트에 답변을 남겨주셨으면 좋겠습니다!

## 조언을 얻고 싶은 부분에 대한 답변
> **네이밍**

이 부분은 아래 코멘트로 답변 드리겠습니다. 

> **컨트롤러?**

오, 이 부분에 대한 고민을 하셨군요!
그래서 MVC 패턴은 개발자들이 MassiveViewController 라고도 하죠!
ViewController가 하는 일이 너무 많은 경우가 대다수고, 그 영향으로 코드 양이 많아지기 때문이죠🥲
이러한 단점이 매우 크기 때문에, MVVM이나 Clean Architecture 등을 아키텍처 패턴으로 사용되는 경우가 많습니다. 
지금은 MVC 아키텍처를 배우고 계시기 때문에, 이런 고민을 꾸준히 하시되 애플은 왜 MVC 패턴을 고수했을까? 생각해보시는 것도 도움이 되실 거 같습니다.

## 조언을 드리고 싶은 부분
- 에러처리
에러 처리를 하는 이유는 무엇인가요? 모든 개발 환경에 따라 답이 달라지겠지만, iOS는 mobile app이기 때문에, 앱을 사용하면서 일어날 수 있는 변수들을 사용자들에게 알려주기 위함이라고 저는 생각합니다.
그래서 저는 최대한 [Alert](https://developer.apple.com/design/human-interface-guidelines/alerts)을 필요한 경우 활용해보셨으면 좋겠습니다.

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet private weak var mangoStockLabel: UILabel!
`@IBOutlet`의 형태가 왜 `weak var`이며, 타입 뒤에 `!`를 왜 붙이는 지 공부해보셨으면 좋겠네요.

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
`final` 키워드 빠졌네요!

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
`override` 키워드는 해당 메서드에서 왜 필요할까요?🤔

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            }
이 부분은 코드를 줄여보려는 노력을 하신 거 같네요👍
- `tag`는 `Int 값`으로 `JuiceMenu`의 `rawValue`를 `Int`로 설정해서 비교해주셨는데, 이러면 `JuiceMenu`와 `Int` 타입이 무슨 연관성이 있는 지 잘 모르겠네요.

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            }
사용자는 해당 오류에 대해 알 필요가 없는 걸까요?

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBAction private func orderJuice(_ sender: UIButton) {
보통 `Button Action` 관련 메서드는 `누른다`의 의미를 많이 씁니다 ㅎㅎ

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
이 부분은 의견이 갈릴 수도 있는 부분으로 보이네요!
사용자가 `nil`이라는 개념을 알까요? 해당 오류문은 해당 과일이 `nil`일 경우에 나오는 에러문 같습니다. 
그렇다면 이 `label`은 과일 재고가 `nil`일 경우, 아무런 텍스트가 나오지 않나요? 그게 사용자 입장에서 좋은 경험일까요?
저라면 오류 처리보다는 병합연산자를 활용하여 `nil`일 경우, `0`이라는 텍스트로 표현할 거 같습니다.
이 부분에 대해 한 번 고민해보셨으면 좋겠습니다.

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
- 얼럿을 띄우는 기능인데, 해당 메서드 네이밍은 적절하지 않은 거 같습니다. 
`ViewController`에서 메서드 네이밍에 대한 tip을 드리자면, 사용자 입장이 아닌 `ViewController` 입장에서 해당 이벤트를 어떤 방식으로 제공하는 지, 고려해보시면 좀 더 쉬워집니다!
- 해당 부분에서 `UIAlertController`, `addAction`, `present` 가 연속적으로 쓰이고 있습니다. 
재사용성을 고려해서 통합해보셨으면 좋겠습니다.

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
화면 전환을 하는 기능이라, `moveTo` 보다 더 좋은 네이밍이 있을 거 같습니다!

2023-05-17 06:16 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/JuiceMenu.swift
> +enum JuiceMenu: Int {
위의 코멘트에도 남겼지만, `JuiceMenu`와 `Int` 타입이 무슨 연관성이 있나요?

2023-05-17 07:48 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet private weak var mangoStockLabel: UILabel!
간단하게 정리해보았습니다!

IBOutlet에서
- weak 키워드를 사용하는 이유 : 간단히 말하자면 메모리 해제가 되지않아 메모리 누수가 발생하는 케이스를 막기 위해
- !를 사용하는 이유 : 불필요하거나 오류의 여지가 있는 경우에 대한 선언을 오류를 띄워 방지하기 위해

2023-05-17 08:04 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
JuiceMakerViewController, FruitStoreViewController가 상속받고 있는 UIViewController에 이미 viewDidLoad 메서드가 선언되어있고, 슈퍼클래스와 같은 이름의 메서드를 덮어쓰기 위해 override 키워드가 필요합니다.

2023-05-17 08:05 UTC, hojun-jo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
`viewDidLoad`가 뷰가 실행될 때 1번 호출되는 메서드이기 때문에 뷰 실행 후 저희가 원하는 기능을 실행하기 위해 `viewDidLoad`를 `override`하여 사용했습니다.

2023-05-18 01:19 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
`movetTo`에서 `show`로 변경했습니다!

2023-05-18 01:23 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBAction private func orderJuice(_ sender: UIButton) {
앞에 `tap`을 추가했습니다!

2023-05-18 12:09 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
기존 코드에서 만약 파인애플 이라는 과일이  없다면 파인애플, 키위, 망고가 모두 0으로 노출되는 현상을 확인했습니다.
파인애플에서 `throw`처리 되었기 때문에 뒷부분이 처리되지 않아서 그런것으로 확인됩니다.
사용자 입장에서는 과일이 없는것과 수량이 0인것의 차이가 없기 때문에 추천해주신 병합연산자를 이용하여 `0`으로 처리했습니다.

2023-05-18 12:11 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
`JuiceMakerViewController`뿐만 아니라 `FruitStoreViewController`에도 추가해주었습니다.

2023-05-18 12:12 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            }
해당 내용과 동일한 부분은 아래에 함께 코멘트 남기겠습니다!

2023-05-18 12:12 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Model/JuiceMenu.swift
> +enum JuiceMenu: Int {
해당 내용과 동일한 부분은 아래에 함께 코멘트 남기겠습니다!

2023-05-18 12:45 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
다양한 `alert`메서드를 하나로 통일하였고, 메서드 명은 `showAlert`이 되었습니다!

2023-05-18 12:48 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            }
모든 에러 상태에 대해서 사용자에게 쥬스를 제공하지 못함은 동일합니다.
`shortageFruitStock`의 경우에는 요구사항대로 진행했고,
나머지는 "쥬스를 만들 수 없습니다"라는 얼럿을 제공하기로 하였습니다.

2023-05-18 12:55 UTC, bubblecocoa commented
스토리보드의 `UIButton tag`와 `JuiceMenu` 열거형의 `rawValue`를 연관지어 사용하는 것은 `tag`가 수정되거나, 열거형의 순서가 바뀔 경우 서로에게 수정사항을 발생시킨다는 것을 깨달았습니다.
때문에 `tag`를 통해 `JuiceMenu`를 찾는 것은 해당 스토리보드와 연결된 `ViewController`에게 책임을 부여했습니다.
이렇게 변경하고 나니 `JuiceMenu`의 `rawValue`가 필요없어져 `Int`타입 할당을 제거했습니다.

2023-05-19 02:05 UTC, jsa0224 reviewed
수고하셨습니다, 비모, 문!
남긴 코멘트를 잘 읽어보시고 빠르게 반영해주셔서 감사합니다!

추가적으로 코멘트 남겼습니다. 
이와 관련하여 좋은 고민해보셨으면 좋겠습니다.

+ 저라면 `tapOrderJuice()` 의 얼럿의 기능들을 따로 메서드로 분리할 거 같습니다.
코멘트로 남기지 않은 이유는 버튼을 눌렀을 때의 액션이 저 기능이라고 판단하시면 그대로 두셔도 괜찮다는 생각도 들기 때문입니다.

2023-05-19 02:05 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    }
LGTM👍
고민 많이 해보신 게 느껴지네요!

2023-05-19 02:05 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
앞선 코멘트에 이야기 드렸듯이, `tag` 자체는 휴먼에러가 발생할 수 있는데
`tag`를 사용하시는 이유가 있으실까요?

2023-05-19 05:20 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        }
모든 버튼에 대해 동일한 `IBAction Method`를 사용하려다보니 각 버튼의 식별자가 필요했습니다.
이 과정에서 버튼을 어떻게 식별할까 생각하던 중 두가지 방안이 떠올랐습니다.
1.  버튼의 `label`이 `JuiceMenu.name`을 포함하는가?
2. `UIButton`의 요소 중 식별자로 사용 가능한 `tag`
둘 중 1번의 경우로 코드를 작성한다면 `UIButton의 label`이 바뀌거나, `JuiceMenu.name`의 값이 바뀔때 에러가 발생할 수 있었습니다.
하지만 `tag`를 이용하는 경우 작업자가 새로운 버튼을 추가하게 되면 같은 `tapOrderJuice` 메서드에 액션을 연결 할 것이고, `menu`는 `tag`를 이용하여 찾을 수 있다는 것을 알 수 있을 것입니다.
두 방안 모두 휴먼에러를 가지고 있는 코드이지만, 2번의 경우가 좀 더 변경사항에 대하여 코드 수정을 덜 해도 된다고 판단했습니다.

결론적으로 질문주신 `tag`는 누른 버튼을 식별하기 위한 용도로 사용했습니다.
혹시 `tag`이외에 휴먼에러를 피할 수 있는 식별자가 있을까요?

2023-05-19 11:55 UTC, jsa0224 commented
수고하셨습니다! 
다음 스텝도 화이팅입니다!👍

2023-05-19 11:55 UTC, merged