쥬스 메이커 [STEP 2] redmango, hoon
yagom-academy/ios-juice-maker pull request #330
Opened 2023-05-17 08:22 UTC by redmango1447

@jsa0224  5m앞에 서 계신 솜에게

## 고민되었던 점

### 여러 `UIButton`들을 하나의 `@IBAction`으로 묶기
- 쥬스를 주문하는 버튼이 각각의 쥬스 종류만큼 개별적으로 존재했습니다. 모든 주문 버튼에 관련하여 각각 `@IBAction`을 생성하는 경우 아래와 같이 중복되는 코드의 양이 무척 많았습니다.

    ```swift
    @IBAction func touchUpStrawberryJuiceOrderButton(_ sender: UIButton) { ... }
    @IBAction func touchUpBananaJuiceOrderButton(_ sender: UIButton) { ... }
    @IBAction func touchUpPineappleJuiceOrderButton(_ sender: UIButton) { ... }
    @IBAction func touchUpKiwiJuiceOrderButton(_ sender: UIButton) { ... }
    @IBAction func touchUpMangoJuiceOrderButton(_ sender: UIButton) { ... }
    @IBAction func touchUpStrawberryBananaJuiceOrderButton(_ sender: UIButton) { ... }
    @IBAction func touchUpMangoKiwiJuiceOrderButton(_ sender: UIButton) { ... }
    ```
    
    이러한 부분을 수정하기 위해 하나의 `@IBAction`에서 버튼을 구분 지어 각각의 버튼에 맞는 동작을 수행하도록 수정하였습니다.
    
    ```swift
    @IBAction func touchUpOrderButton(_ sender: UIButton) { ... }
    ```
    위와 같이 하나의 `@IBAction`에서 각각의 버튼을 구분하기 위해서는 이를 구분하기 위한 식별자가 필요했습니다. `UIButton`의 `tag`와 `title` 프로퍼티를 사용하여 식별자 역할을 할 수 있었습니다. 두 방법에 대해 다음과 같이 코드로 표현하였습니다.
    - `tag` 사용

        ```swift
        @IBAction func touchUpOrderButton(_ sender: UIButton) {
            try juiceMaker.makeOrder(sender.tag)    
        }
        ```
        
        `tag`를 사용하여 해결을 한 경우 각각의 버튼에서 가지고 있는 프로퍼티의 `tag`값을 모두 개별적으로 지정해 주어야 한다는 점에서 코드의 수정이 필요했습니다. 또한 `tag`는 기본값으로 0을 가지고 있기 때문에 새로운 버튼을 추가하고 개발자가 `tag`를 수정하지 않을 시 같은 `tag` 값을 갖는 문제가 발생하였습니다.
        
    - `title` 사용
    
        ```swift
        @IBAction func touchUpOrderButton(_ sender: UIButton) {
            guard let title = sender.titleLabel?.text,
                  let juice = Juice(rawValue: title)
            else {
                return
            }

            try juiceMaker.makeOrder(juice)
        }
        ```
        
        `title` 사용 시 버튼에 대한 기본 네이밍의 양식이 같다면 추가 수정 없이 Juice의 원시 값을 수정하여 매칭을 시킬 수 있었습니다. 이렇게 된다면 버튼이 추가될 때 `Juice`의 원시 값만 추가하여 해당 버튼의 `title`과 같은 값으로 맞춰주면 되었습니다.
        
        위의 두 경우를 비교하여 생각하였을 때 `title`을 사용하는 방식이 `tag`를 활용하는 방법보다 새로운 버튼이 추가되었을 때 더 적은 수정을 필요로 하고 혹시 모를 에러(ex: 버튼 추가 후 `tag`미 수정 등)를 미연에 방지하기 때문에 최종적으로 `title`을 활용하기로 결정하여 문제를 해결하였습니다.

### `UIOutlet Collection` 활용
- `UILable`에 재고 값을 하나하나 넣는 것보단 반복문 등을 통해 한 번에 넣는 게 더 좋다고 판단했습니다. 아래와 같이 `UIOutlet Collection`을 활용해 `UILable`을 하나로 묶어 배열처럼 사용하였습니다.

    ```swift
        private func changeStockLabel() {
            for (fruitStockLabel, fruit) in zip(fruitStockLabels, Fruit.allCases) {
                fruitStockLabel.text = juiceMaker.showRemainStock(of: fruit)
            }
        }
    ```

### `AlertAction handler` 화면 전환 방법
- `재고 수정`을 누를 경우 `Segue`를 사용해`Present Modally` 방식으로 재고 수정 `viewController`와 연결해 줬습니다. `Alert`창에서 "예"를 누를 경우에도 `AlertAction handler`를 활용해 같은 재고 수정 `viewController`로 화면전환을 해줘야 하기에 처음엔 아래와 같이 `viewController`의 `identifierID`를 활용해 인스턴스화하여 `present` 해주는 방식으로 화면 전환을 하였습니다.

    ```swift
    guard let nextView = self.storyboard?.instantiateViewController(identifier: "identifierID") else { return }
    self.present(nextView, animated: true)
    ```

    하지만 기존의 `Segue`를 어떻게 활용할 방법이 없을까 하고 고민이 들었고 결국 아래와 같이 `performSegue`을 활용해 아래와 같이 해결했습니다.
    
    ```swift
    let confirmAction = UIAlertAction(title: "예", style: .default) { _ in
        self.performSegue(withIdentifier: "goToStockViewController", sender: nil)
    }
    ```

## 조언을 얻고 싶은 부분

### 특정 `label`에 값을 받아오는 방법과 `stockList`의 딕셔너리 사용시 관찰의 어려움
- 현재 작성한 코드에서는 쥬스를 만들고 쥬스를 만들기 위해 사용한 과일의 수만큼을 해당 재고에서 감소시킨 후 그 전체 값을 다시 받아와서 `UILabel`에 새로 입력을 해줍니다.
    
    ```swift
    private func changeStockLabel() {
            for (fruitStockLabel, fruit) in zip(fruitStockLabelCollection, Fruit.allCases) {
                fruitStockLabel.text = juiceMaker.showRemainStock(of: fruit)
            }
        }
    ```
    
    위처럼 실제로 사용한 과일뿐만 아니라 전체 과일에 대해 순환을 하면서 변경되지 않은 과일의 재고도 다시 `UILabel`에 새로 할당합니다.
    
    이런 방식이 아닌 실제 사용된 과일을 특정하여 그 재고 값만을 다시 `UILabel`에 할당하는 방식을 위해서 생각한 내용이 `Observer` 방식을 활용하는 것이었습니다. 여기서 생긴 문제점은 기존에 선언한 `stockList`가 `dictionary`타입이라 하나의 프로퍼티가 모든 과일에 대한 값을 담고 있다는 것이었습니다. 이렇게 되면 관찰할 대상은 개별 과일과 수량이 아닌 전체 과일이 되기 때문에 여기서 특정 과일을 지칭하기가 어려웠습니다. 이러한 경우에 각각의 과일을 구조체와 같은 타입으로 변경하여 각각 관찰할 수 있는 인스턴스로 만드는 것이 괜찮은 방법일까요?

### `enum` 타입에서 `rawValue`의 사용과 `switch`문을 사용한 해결
- `enum`의 `case`에 따라 각각 다른 동작을 수행합니다. `enum`의 `case`에 따라 구분하기 위해서 `switch`문을 사용하여 각각의 `case`에 대한 처리를 진행하였습니다.

    ```swift
    switch juice {        
    case .strawberryJuice:
        <#code#>
    case .bananaJuice:
        <#code#>
    case .pineappleJuice:
        <#code#>
    case .kiwiJuice:
        <#code#>
    case .mangoJuice:
        <#code#>
    case .strawberryBananaJuice:
        <#code#>
    case .mangoKiwiJuice:
        <#code#>
    }
    ```

    `switch`문을 사용하는 경우 `enum`의 `case`가 추가될 시 `switch`문에서도 수정을 해야 한다는 부분에서 확장성이 떨어져 보인다고 생각하였습니다. 실례로 개방-폐쇄 원칙(OCP)을 지키기 위한 하나의 방법이 무분별한 `switch`문의 사용을 지양하는 것이라는 내용을 보았습니다. 

    이러한 생각을 가지고 개별 동작을 구분하기 위한 방법으로 `rawValue`를 활용하는 방안을 생각해 보았습니다.
    ```swift
    Juice(rawValue: title)
    ```
    위와 같이 `Juice`의 어떤 특정 `case`에 대해 `rawValue`를 사용하여 값을 초기화하는 방법을 사용하였습니다. 여기서 든 궁금점은 `enum`에서 `rawValue`의 사용은 사용자 입장에서 어떠한 타입이 사용되는지에 대한 예측이 불가능하단 점에서 지양하는 방식이라고 들었습니다. 여기서는 어떤 값에 접근하기 위해 `enumCase.rawValue`처럼 사용하는 것이 아니어서 괜찮다고 생각하였습니다.
    
    두 경우 모두 각각의 장단점들이 있었고 어떤 방법이 여기서 더 어울릴지와 이 외에 다른 생각지 못한 방법이 있을지 궁금합니다.

2023-05-18 07:41 UTC, jsa0224 requested changes
안녕하세요! 훈, 레드망고!
프로젝트 잘 보았습니다.
(이제는 멀어졌네요...🤣)

## 고민하신 부분에 대한 답변
> ### 여러 `UIButton`들을 하나의 `@IBAction`으로 묶기

`tag`와 `title` 중 어느 것으로 구현할지 고민이 많이 되셨던 거 같아요. 저도 훈맹구팀과 마찬가지로 `tag`는 휴먼에러가 발생할 여지가 높기 때문에, `title`로 구현하신 점에 동의합니다👍

> ### `UIOutlet Collection` 활용

- `Fruit`라는 열거형으로 이루어져 있는 특성을 잘 활용하신 거 같습니다. 
- 재고 수가 바뀔 때마다 `label`도 바뀌기 때문에 `change`라는 네이밍을 사용하신 거 같습니다. 
저도 이 부분이 애매해서 코멘트로 따로 남겨드리진 않았지만, `ViewController`의 입장에서 `label`을 바꾸는 것이 아닌 구성한다는 점에서 네이밍을 한 번 고민해보셨으면 좋겠습니다.

> ### `AlertAction handler` 화면 전환 방법

`segue`를 활용해보셨군요👍
`segue`는 어떤 개념인지 한 번 공부해보는 것도 추천드려요.

## 조언을 얻고 싶은 부분에 대한 답변
> ### 특정 `label`에 값을 받아오는 방법과 `stockList`의 딕셔너리 사용시 관찰의 어려움

이 부분은 그때 제가 잠깐 설명드린 부분을 포함해서 추가로 남기겠습니다.
그때 훈맹구팀이 저에게 물어보신 질문이, `ViewController`가 `Fruit`을 알아도 되는 지에 대한 거였죠.
제가 그때, 필요할 경우 알아도 된다고 했었던 거 같은데, 최대한 `FruitStore`를 활용해보라는 말씀을 드렸던 거 같습니다.
`FruitStore`은 딕셔너리 `key` 형태로 `Fruit`을 소유하고 있기 때문에 연산 프로퍼티나 메서드로 충분히 전달이 가능하기 때문이죠.
이 부분을 토대로 한 번 고민해보시고 수정해보셨으면 좋겠습니다!

> ### `enum` 타입에서 `rawValue`의 사용과 `switch문`을 사용한 해결

글쎄요... `개방-패쇄 원칙`을 위배한다고 해서 `Juice`가 `rawValue` `String` 형태로 주문 버튼을 소유하고 있는 것도 좋은 방법은 아닌 거 같습니다. 
`Juice`에서 연산 프로퍼티로 구현하는 것(`switch문`)의 사용을 지양하라는 말은 전 와닿지 않는 거 같습니다.
보통 네트워크 작업을 할 때, 해당 `URL`의 `Endpoint`를 관리할 때도 `enum`의 `연산 프로퍼티`를 많이 활용합니다.
이 부분은 케이스에 따라 수정될 여지가 많은데도, 사용한 거면 `개방-패쇄 원칙`을 어긴 걸까요?
이렇게 생각하신 계기가 궁금해지네요 ㅎㅎ

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +class StockViewController: UIViewController {
- final 키워드가 빠졌네요!
- 재고추가화면인데, 추가의 의미가 네이밍이 내포되지 않은 거 같습니다.

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
- 여기도 final 키워드!
- 여기는 `ViewController`의 이름을 정해주지 않으셨네요.

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet var fruitStockLabelCollection: [UILabel]!
- `Label`을 배열로 지정해주셨군요.
- `weak` 키워드가 빠진 이유는 무엇인가요?
-  `@IBOutlet`의 경우 타입 뒤에 왜 `!`로 강제 언래핑을 할까요?

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
- 코드를 줄이기 위해 노력하신 부분이네요👍
- 하지만 `Juice`의 `rawVaule`가 `titleLabel`가 무슨 연관성이 있는 지 잘 모르겠습니다.

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
사용자에게 오류를 적절하게 알려주시려는 시도가 좋습니다👍

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`UIAlertController`가 2번이나 같은 방식으로 쓰이는데, 하나로 통합해보시면 좋을 거 같아요!

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
이 부분은 저희가 따로 이야기 했던 부분이라 자세한 코멘트는 남기지 않겠습니다!

2023-05-18 07:41 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    case mangoKiwiJuice = "망키쥬스 주문"
위에 남겼던 `Juice` `rawValue`에 관한 코멘트 부분입니다.

2023-05-19 06:03 UTC, redmango1447 commented on JuiceMaker/JuiceMaker/Controller/StockViewController.swift
> +class StockViewController: UIViewController {
`view`에 만들어져 있는 버튼이 `Stepper`이기에 재고를 추가할수도, 뺄수도 있다는걸 생각해 `StockManagementViewController`라는 이름으로 바꿨습니다!

2023-05-19 06:05 UTC, redmango1447 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
쥬스를 주문하는 뷰이기에 `JuiceOrderViewController`라는 이름으로 바꿨습니다!

2023-05-19 06:09 UTC, redmango1447 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
`UIButton`을 상속받은 `CustomButton`을 만들고 `customIdentifier`라는 `Juice`타입의 프로퍼티를 만들어 활용해봤습니다

2023-05-19 06:10 UTC, redmango1447 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`AlertType`이라는 `Enum`을 만들고 이것을 활용해 하나로 통합했습니다!

2023-05-19 06:31 UTC, Hoon94 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBOutlet var fruitStockLabelCollection: [UILabel]!
### `weak` 키워드 생략
- `IBOutlet Collection`은 `Array` 타입으로 구조체인 값 타입의 변수입니다. `weak` 키워드는 클래스 타입인 경우에 참조할 때 `reference count`를 증가시키지 않기 위해 사용합니다. `weak` 키워드를 `IBOutlet Collection`에서 사용하려고 하면 다음과 같은 에러 메시지를 출력합니다.

    ```
    'weak' may only be applied to class and class-bound protocol types, not '[UITextField]'
    ```

### `@IBOutlet` 타입 뒤에 `!` 사용
- `@IBOutlet`의 경우 `Implicitly Unwrapped Optionals(IUO)` 방법을 통해 옵셔널을 사용하며 이를 사용하면 변수에 값을 `lazy`하게 초기화 시킬 수 있습니다. View Controller에서 View를 사용하기 위해 연결하는 `IBOutlet` 변수는 View가 메모리에 할당된 이후에 이를 가지고 초기화를 진행하며 `IUO`가 아닌 `Optionals(?)`를 사용할 수도 있지만 기본적으로 지원하는 `IUO` 방식을 사용하였습니다. 확실한 안정성을 위해서라면 `Optionals`를 사용하는 것이 좋겠지만 `@IBOutlet attribute keyword` 자체에서 Interface Builder에 있는 View와 연관하여 사용하는 변수라는 것을 컴파일러에게 사전에 알려줬기에 만약 사용하지 않을 View 또는 변수였다면 처음부터 선언할 필요가 없었다는 점에서 `viewDidLoad` 메서드가 호출된 이후라면 `IUO` 방식을 통해 간편하게 사용할 수 있다고 생각하였습니다.

2023-05-22 11:44 UTC, jsa0224 commented
수고하셨습니다, 훈맹구팀!
다음 스탭도 파이팅입니다!

2023-05-22 11:44 UTC, merged