쥬스 메이커 [STEP 2] dasanKim, kyungmin
yagom-academy/ios-juice-maker pull request #331
Opened 2023-05-17 08:43 UTC by YaRkyungmin

원비(@wonbi92) 안녕하세요🥰
다산,경민 입니다🐤🐤
바쁘신 와중에도 리뷰해주셔서 감사합니다
잘 부탁드려요😽👏

-------
## 🔍 고민되었던 점

### 1. ‘재고수정’ 버튼을 터치하였을 때 ‘재고 추가’ 화면으로 이동 시 적절한 방식은?
- storyboard에서 객체 Segue 사용하여 Present Modally를 선택하였습니다.
- 일반적으로 Present Modally 방식은 기존의 뷰 컨트롤러에서 **일시적으로** 새로운 화면을 보여줄 때 사용됩니다. 
- 예를 들어, 정보를 입력하는 화면이나, 설정을 변경하는 화면 등이 Present Modally 방식으로 보여진다고 합니다.
- 아래와 같은 이유로 Present Modally를 선택하였습니다.
    - 재고 수정만하고 다시 주문하는 기존 화면으로 돌아와야 했습니다
    - 사용자가 보고 있던 화면 위에 다른 화면을 띄워 **시선을 끌면서** 기존 화면에서 **잠시** `재고 추가 화면`을 보여주기 위하여 선택하였습니다

### 2. Bool Type init()의 기본값
- 기존 기본 타입들을 초기화할 때 각 타입의 `init()`을 활용하여 초기화를 하였었습니다. 그러던 중 `requsetFruitStock` 함수에 로직적 오류를 발견하였습니다.
- **오류 발견**: `recipe`에 2가지 이상 과일이 필요할 때, 마지막 과일 재고만 있어도 `true`리턴하게 되므로 로직 오류
    ```swift
    var isEnoughStock: Bool = Bool
    fruitJuice.recipe.forEach {
        isEnoughStock = fruitStore.hasEnoughStock(fruit: $0.key, amount: $0.value)
    }
    ```
- 아래와 같이 로직으로 바꾸기 위하여서는 선언된 `isEnoughStock`에 `false`가 들어가있는지, `true`가 들어가있는지 알아야했습니다.
    ```swift
    fruitJuice.recipe.forEach {
        isEnoughStock = fruitStore.hasEnoughStock(fruit: $0.key, amount: $0.value) 
                        && isEnoughStock
    ```
- 당연히 true가 들어가있을 거라 생각하며 간단하게 테스트를 해보았더니
    ```swift 
    var isEnoughStock: Bool = Bool()
    print(isEnoughStock) // false
    ```
- `false` 이었습니다. 따라서 init()으로 초기화하였던 것을 true로 초기화 해주었습니다.

### 3. enumberated()의 index 대신 다른 것 사용할 수 없을까?
- `enumberated()`의 index 자체는 **가독성이 떨어질 수 있어** 다른 방법이 없을까 고민해보았습니다.
- Label의 `tag`값들은 Fruit 타입의 `inventoryIndex`값과 같도록 설정해놓았던 터라 fruitInventory배열을 enumberated()의 index로 접근하는 대신 **fruitStockLabel의 tag**값을 활용해보았습니다.

- Before
``` swift 
func updateFruitStockLabel() {
   for (index, fruitStockLabel) in fruitStockLabels.enumberated() {
       //print("tag: \(fruitStockLabel.tag) , index: \(index)")
       fruitStockLabel.text = String(juiceMaker.fruitStore.fruitInventory[index])
   }
}
```

- After
``` swift
func updateFruitStockLabel() {
   for fruitStockLabel in fruitStockLabels {
       fruitStockLabel.text = String(juiceMaker.fruitStore.fruitInventory[fruitStockLabel.tag])
   }
}
```
<br>

## 📌 해결하지 못한 점 
### 1. weak은 왜 쓰이는 것인지 의문이 생겼습니다.
```swift!
    @IBOutlet weak var testLabes: UILabel!
    @IBOutlet weak var fruitStockLabels: [UILabel]! //error
```
- 'weak'키워드는 메모리 관리를 위해 사용 됩니다. 클래스 인스턴스에 대한 약한 참조를 나타냅니다.
- 약한 참조는 참조 카운트에 영향을 주지 않으며, 참조 대상이 메모리에서 해제될 수 있는 상황을 허용합니다.
- 참조 순환(Strong Reference Cycle)을 방지하고 메모리 누수를 방지하는 데에 사용됩니다.
- 위와 같은 이유로 weak 키워드를 배열에서 사용하려고 하였더니 에러가 발생했습니다.
- 배열이 구조체로 정의 되어있기 때문에 weak를 사용할 수 없다고 이해했습니다.

### 2. ViewController는 인스턴스화 하지 않아도되는데 ModifyStockViewController는 왜 인스턴스화 해줘야되는지 고민했습니다
- Storybord Entry Point가 포함된 Navigation Controller Scene에서 segue를 통한 root view controler로 처음 화면인 ViewController를 연결하면 ViewController를 인스턴스화 해준다고 생각 했습니다. 저희가 이해한게 맞을까요?

<br>

## 🙏 조언을 얻고 싶은 부분
- 뷰 들 간의 데이터 전달에 있어 KVO, NotificationCenter, Delegate, Singleton Pattern 등 여러가지 방법이 있는데요. 다음 스텝 진행에 있어 배웠던 내용을 바탕으로 KVO나 NotificationCenter를 활용해야 할지, 아니면 Delegate를 적용해야할 지 의문이 듭니다.

<br>

## 📚 참고 링크
- [🍎Apple Docs: Modality](https://developer.apple.com/design/human-interface-guidelines/modality)
- [🍎Apple Docs: Array](https://developer.apple.com/documentation/swift/array)
- [🍎Apple Docs: InstantiateViewController](https://developer.apple.com/documentation/uikit/uistoryboard/1616214-instantiateviewcontroller)
- [🍎Apple Docs: Alert](https://developer.apple.com/documentation/swiftui/alert)

2023-05-18 04:13 UTC, wonbi92 requested changes
@DasanKim @YaRkyungmin
안녕하세요 다산! 경민! 😎
Step2 진행하시느라 고생하셨습니다!
PR코맨트와 코드에서 여러가지 방법 중에서 하나를 선택하고 그 이유를 찾는 과정이 보여서 좋았습니다! 👍

약간의 수정사항과 참고하실만한 부분들을 코맨트 드렸으니 쭉 읽어보시고 궁금하신 점 있으시면 말씀해주세요~ 💪
코맨트로도 말씀 드렸지만, 약간의 버그가 있습니다! 코맨트 확인해보시고 수정해주세요~

아래는 질문주시고 고민하신 부분에 대한 제 생각입니다! 😁

> 1. weak은 왜 쓰이는 것인지 의문이 생겼습니다.
- weak키워드에 대해 알아보셨군요! 그리고 아울렛 컬랙션에 weak를 붙이면 에러가 나는 이유를 잘 고민해보신거 같아요! 
- 그렇다면,  아울랫 변수에 weak를 붙이는 이유는 무엇일까요? 

> ViewController는 인스턴스화 하지 않아도되는데 ModifyStockViewController는 왜 인스턴스화 해줘야되는지 고민했습니다
- 일단 왜 `ViewController`는 인스턴스화 하지 않아도 된다고 생각하셨을까요? 
- 만약 코드상에서 인스턴스화 하지 않아서 이렇게 생각하셨다면, 고민하신 내용이 정확하진 않지만 방향성은 맞다고 말씀드릴 수 있을거 같아요!
- 화면에 뷰를 띄우는 방법은 여러가지가 있죠! 스토리보드에서 세그를 이용한 방법과 코드로 인스턴스화 해서 present혹은 push하는 방법이 있을거같아요! 그럼 앱이 처음 실행될 때는 어떨까요? 앱이 처음 실행될 때 내부적으로 어떻게 동작하는지 좀 더 공부해보세요~!

> 뷰 들 간의 데이터 전달에 있어 KVO, NotificationCenter, Delegate, Singleton Pattern 등 여러가지 방법이 있는데요. 다음 스텝 진행에 있어 배웠던 내용을 바탕으로 KVO나 NotificationCenter를 활용해야 할지, 아니면 Delegate를 적용해야할 지 의문이 듭니다.
- 여러 방법이 있고, 각 방법마다 장단점과 제약들이 존재하겠죠? 말씀드렸었지만 각각의 방법에 대한 사용법과 장단점을 공부해보시고, 어떤 방법이 우리 프로젝트에 맞는지 선택하시고 그 이유를 설명해주세요! 
- 추가적으로 제가 이 프로젝트를 진행할 당시에는 각각의 방법들을 브랜치 별로 나눠서 한번씩 다 적용시켜보고 각각의 장단점을 파악했었습니다. 이런 방법도 있으니 참고해보세요~ 😁

2023-05-18 04:13 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
UIView의 프로퍼티인 tag를 활용해서 어떤 쥬스 주문했는지 구별하는 로직이군요! 태그는 어떨 떄 사용하는 프로퍼티일까요?

또한, 태그는 Int타입입니다. 따라서 스위치 문의 각 케이스인 1~7 숫자들이 상황에 따라서는 어떤걸 의미하는지 정확하게 모를 수 있을거 같습니다. 한번 매직넘버를 지워볼까요?

태그를 사용하면 코드를 작성하기 매우 쉬워지고 코드도 깔끔해지지만, 각 객체의 태그를 하나하나 지정해줘야하고, 버튼의 위치가 변경되거나, 새로운 버튼이 생길경우 이에대한 대응이 힘들어질 수 있습니다. 시간이 허락하신다면 이부분도 한번 고려해보세요~!

2023-05-18 04:13 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
`enumberated()`의 가독성이 떨어져서 로직을 수정하신거 같은데 현재 코드에서 적용이 안된거 같아요! 한번 확인해보세요~ 😅

2023-05-18 04:13 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>      }
스토리보드를 가져와 그 내부에있는 `ModifyStockViewController`를 인스턴스화 해서 `present`를 하고 있네요! 그런데 이 얼럿 컨트롤러를 통해 접근한 뷰에서 이전뷰로 돌아갈 방법이 없는거 같아요..! 
정확하게 말씀드리자면, 앱을 실행한 후, 재고수정 버튼을 누르지 않은 상태에서 재고가 모자라다는 얼럿을 통해 다음뷰에 접근하게 되면 이전뷰로 돌아갈 방법이 없군요..!
게다가, 화면을 띄우는 애니메이션도 다르네요! 이부분 확인한번 해보세요!

추가적으로, 네비게이션 컨트롤러는 어떤 역할을 할까요? 또한 현재 스토리보드상 네비게이션 컨트롤러가 각각의 뷰 컨트롤러마다 하나씩 존재하는데 이는 어떤의미일까요?

2023-05-18 04:13 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +enum Juice: CustomStringConvertible {
`CustomStringConvertible`프로토콜! 👍👍

2023-05-18 04:13 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>          }
로직에 오류를 발견하셔서 수정하셨군요! 간혹 이러한 예상못하는 오류가 발생할 수 있습니다. 이제라도 알아서 다행이군요! 😅

이러한 로직상의 오류가 났을 때는 왜 이 오류가 나타났는지 체크해볼 필요가 있습니다. 지금 수정해주신 로직으로 동작은 하지만, 코드의 가독성이 너무 안좋아진거 같아요.
현재 이 메서드의 목적은 "재고가 매개변수로 받아온 쥬스를 만들 수 있을만큼 충분한지 체크"하는게 목적이겠네요!
다르게 말한다면 "쥬스의 레시피 목록 중 하나라도 재고가 부족하면 실패"네요..!
이를 활용한다면 좀 더 가독성이 좋고, 로직적으로 허점을 줄일 수 있는 코드를 작성할 수 있을거 같아요!
저였다면 이런식으로 로직을 구성했을거 같습니다.
```swift
    private func requestFruitStock(menu fruitJuice: Juice) throws {
        for ingredient in fruitJuice.recipe {
            if !fruitStore.hasEnoughStock(fruit: ingredient.key, amount: ingredient.value) {
                throw JuiceMakerError.outOfFruitStock
            }
        }
    }
```
어떤가요? 좀 더 읽기 편해보이지 않나요? 게다가 레시피를 순회하는 동안에 한번이라도 재고가 부족하다면 바로 throw를 해버리기 때문에 더 순회를 돌 필요가 없어져서 성능적인 비용절감이 가능해졌고, 발견하신 오류가 나타날 가능성도 사라져버렸네요!

말씀드리는 김에 한가지 더 말씀드리자면, 저는 recipe를 딕셔너리가 아닌 튜플을 담은 배열로 처리할 것 같습니다. 다음과 같이요!
```swift
    var recipe: [(name: Fruit, amount: Int)] {
        switch self {
        case .strawberryJuice:
            return [(.strawberry, 16)]
        case .bananaJuice:
            return [(.banana, 2)]
        case .kiwiJuice:
            return [(.kiwi, 3)]
        case .pineappleJuice:
            return [(.pineapple, 2)]
        case .strawberryBananaJuice:
            return [(.strawberry, 10), (.banana, 1)]
        case .mangoJuice:
            return [(.mango, 3)]
        case .mangoKiwiJuice:
            return [(.mango, 2),(.kiwi, 1)]
        }
    }
```
이렇게 한다면 사용하는 쪽에서는 다음과 같이 사용할 수 있겠네요!
```swift
    private func requestFruitStock(menu fruitJuice: Juice) throws {
        for ingredient in fruitJuice.recipe {
            if !fruitStore.hasEnoughStock(fruit: ingredient.name, amount: ingredient.amount) {
                throw JuiceMakerError.outOfFruitStock
            }
        }
    }
```
어떤가요? key value로 접근하는 것보다 훨씬 더 좋은 가독성이지 않나요? 😁
딕셔너리를 사용하는 이유와 딕셔너리만의 장점을 한번 알아봅시다! 사실 현재 사용하신 로직에서는 딕셔너리의 장점을 잘 이용하고 있다는 생각이 안드네요! 한번 고민해보세요~!!

2023-05-18 04:13 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
이 뷰컨트롤러는 다른 객체가 상속받을 일이 있을까요? 더이상 상속할 객체가 없는 클래스는 어떻게 하면 좋을까요?

추가적으로 이 뷰컨트롤러는 어떤 뷰를 컨트롤하는 컨트롤러일까요? 🤔 이름만 봐서는 어떤 뷰인지 모르겠어요! 적절한 이름을 지어줘봅시다!

2023-05-18 11:53 UTC, DasanKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    }
맞습니다ㅠㅠ 다음엔 수정사항이 현재 코드에 반영되었는지 다시 한번 확인해보겠습니다😹

2023-05-18 12:19 UTC, YaRkyungmin commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
```swift
@IBAction func touchUpOrderButton(_ sender: UIButton) {
        if let buttonIndex = orderButtons.firstIndex(of: sender){
            order(juice: Juice.allCases[buttonIndex])
        }
        
        updateFruitStockLabel()
    }
```

여러개의 Label들을 배열에 담아 접근했던 방법을 인용하여, UIButton도 같은 방식으로 구현해봤습니다. 객체의 태그를 하나씩 지정해줘야하고, 새로운 버튼이 생길경우에 대한 단점은 보완한 것 같은데 버튼의 위치가 변경되는 경우는 이해하지 못했습니다.

2023-05-18 12:29 UTC, DasanKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
> 이 뷰컨트롤러는 다른 객체가 상속받을 일이 있을까요? 더이상 상속할 객체가 없는 클래스는 어떻게 하면 좋을까요?

- 메인 ViewController는  `navigationViewController`의 `root view` 이므로 다른 객체가 상속받을 일이 없다고 생각합니다. 
- 더 이상 상속할 객체가 없는 클래스는 혹시 모를 상속을 막기 위하여 `final`이라는 키워드를 붙여줍니다.
- 본래 `final` 키워드는 **`Overrides`를 막기 위한 키워드**입니다. 메소드나 속성 키워드 앞에 final 키워드를 붙여주면 해당 메소드나 속성의 재정의를 막을 수 있습니다. 더 나아가 class 키워드 앞에 final를 작성하면 해당 클래스의 하위 클래스를 만드려는 어떤 시도도 compile-time error라고 보고하므로, 혹시 모를 상속을 막을 수 있습니다.

> 추가적으로 이 뷰컨트롤러는 어떤 뷰를 컨트롤하는 컨트롤러일까요? 🤔 이름만 봐서는 어떤 뷰인지 모르겠어요! 적절한 이름을 지어줘봅시다!
- 위 뷰 컨트롤러는 쥬스 주문을 받아 쥬스를 만들어 주는 View를 담당하고 있으므로, `JucieMakerViewController` 라고 이름을 지어주었습니다:)

2023-05-18 12:30 UTC, YaRkyungmin commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>          }
코드를 살펴보니 해시테이블로 구현된 딕셔너리의 장점은 key값을 이용해 빠르게 Value값을 찾을수 있는 것인데 recipe 프로퍼티에 접근할때 key값으로 접근하고 있지 않고 있음에도 불구하고 딕셔너리를 사용했다는 것을 깨달았습니다. 조언 해주신 tuple을 이용해 구현해봤습니다.

2023-05-22 02:22 UTC, YaRkyungmin commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>      }
닫기 버튼을 dismiss로 구현해봤습니다.

present방식도 segue로 통합했습니다:)

네비게이션 컨트롤러는 각 뷰컨트롤러 인스턴스를 Stack에 push pop을 통하여 관리합니다. 각각의 뷰가 네비게이션 컨트롤러마다 존재할 필요가 없다고 생각하여 재고수정 view의 네비게이션 컨트롤러는 없애줬습니다.

또한 저희는 ["이전 컨텍스트를 잃지 않고 명확하고 좁은 범위의 작업을 수행할 수 있도록 지원"](https://developer.apple.com/design/human-interface-guidelines/modality) 할때 사용 한다는 것에 초점을 두어 네비게이션컨트롤러 대신 재고수정 view를 modal방식으로 구현했습니다.🤔

그리고 네비게이션컨트롤러의 기능을 사용하는부분이 naviagation bar 부분의 버튼만을 사용하고 있지만, 네비게이션 컨트롤러를 남겨놓은 이유는 추후의 과일 재조를 하면서 추가기능을 넣어 주는 다음 view를 만들어 이동할때는 push를 해줘야 할 것 이라고 생각해서 남겨놨습니다.🤔

2023-05-22 03:00 UTC, YaRkyungmin commented
- 아울랫 변수에 weak를 붙이는 이유는 무엇일까요?
  - 뷰 컨트롤러가 메모리에서 해제될 때, 아울랫변수가 weak로 선언되어 있다면 해당 변수는 자동으로 nil로 설정됩니다. 따라서 뷰 컨트롤러가 메모리에서 해제될 때 아울랫변수도 같이 해제되므로 해당 뷰에 대한 참조를 방지할 수 있습니다
- ViewController는 인스턴스화 하지 않아도 된다고 생각하셨을까요?, 앱이 처음 실행될 때 내부적으로 어떻게 동작하는지?
  - Instantiation: 앱이 처음 시작할 때, 혹은 다른 ViewController에서 Storyboard를 통해 새로운 ViewController를 로드할 때 발생합니다
  - Initialization: ViewController의 인스턴스화 후에, ViewController의 초기화 메서드인 init?(coder:) 또는 init(nibName:bundle:) 이 호출 됩니다
  - View Loading: ViewController는 처음으로 뷰가 필요할 때 loadView() 메서드를 호출하여 뷰 계층을 로드하고, 그 후에는 viewDidLoad() 메서드를 호출합니다

2023-05-22 03:15 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
버튼의 위치변경은 실제 뷰에서 위치가 바뀌는 경우를 말하는거였어요! ㅎㅎ 버튼의 위치가 바뀌면 태그 숫자가 뒤죽박죽이 되면서 뷰와 코드를 같이 봐야할 때 좀 복잡해질 수도 있겠죠? 태그의 숫자는 버튼상에서 나타나지 않으니까요~!

2023-05-22 03:25 UTC, wonbi92 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
완벽합니다! 👍👍👍

2023-05-22 03:27 UTC, wonbi92 commented
@DasanKim @YaRkyungmin
안녕하세요 다산! 경민! 😎
먼 태국 땅에서 여러분의 코드를 보고있으니 느낌이 새롭고 좋네요! ㅎㅎ 
잘 수정해주셨고, 잘 설명해주셨어요! 근거도 너무 좋았고 깊게 고민하셨던 흔적이 보여서 정말 좋습니다!

머지해드릴게요! 다음 스탭 진행해주세요~

2023-05-22 03:28 UTC, merged