쥬스 메이커 [STEP3] jusbug, Erick
yagom-academy/ios-juice-maker pull request #333
Opened 2023-05-19 07:21 UTC by JusBug

@jsa0224
안녕하세요 Som!!
항상 좋은 리뷰 감사합니다!
마지막 Step3 PR 보내드립니다.
이번에도 좋은 리뷰 부탁드립니다😀

### 고민한 점
***Singleton***
- 처음에는 `FruitStore`를 singleton 패턴으로 작성하였습니다.
- `JuiceMakerViewController`와 `ChangeStockViewController`가 같은 데이터 영역의 `FruitStore`를 가르키고 있도록 하여 view 간의 데이터 전달이 없더라도 데이터 참조가 가능하도록 했습니다.
- 하지만 singleton 패턴이 대표적인 안티패턴이기도 하고, 변경이 자주 일어날 수 있는 Model부분을 singleton 패턴으로 작성하면 추후 코드가 바뀌었을 때 Model을 가지고 있는 다른 객체들도 다 변경되어야 하는 단점이 있어 사용하지 않았습니다.

***Delegate***
- 위에 언급된 singleton 패턴을 사용하지 않고 뷰 간의 데이터를 전달하기 위해 사용한 것이 delegate 패턴입니다.
- NotificationCenter의 사용도 고민했으나 서로 연결되어 있지 않은 완전히 독립된 객체 간의 통신이나 데이터 전달을 할 때 NotificationCenter를 사용하는게 좋다고 생각하여 delegate 패턴을 사용했습니다.

</br>

- 수정한 재고를 보내주기 위해 `ChangeStockProtocol` 프로토콜을 만들고 `delegate` 프로퍼티를 이용해 fruitStore를 보내는 모습입니다.

```swift
protocol ChangeStockProtocol {
    func changeStock(fruitStore: FruitStore)
}

class ChangeStockViewController: UIViewController {
    // ...
    var delegate: ChangeStockProtocol?
 
    // ...
    @IBAction private func closeButtonTap(_ sender: UIBarButtonItem) {
        self.delegate?.changeStock(fruitStore: fruitStore)
        self.navigationController?.popViewController(animated: true)
    }
    
    // ...
}
```

- 수정된 재고를 받는 `JuiceMakerViewController`에서는 `ChangeStockProtocol` 프로토콜을 채택하고 델리게이트를 self로 설정해주어 `changeStock()`를 통해 `fruitStore`를 받아오고 있습니다.

```swift
class JuiceMakerViewController: UIViewController, ChangeStockProtocol {
 
    // ...
    func changeStock(fruitStore: FruitStore) {
        self.juiceMaker.fruitStore = fruitStore
        composeText()
    }
    
    private func pushChangeStockViewController() {
        // ...
        // 뷰를 push할 때 프로퍼티 할당으로 데이터 전달
        pushViewController.fruitStore = juiceMaker.fruitStore
        // 델리게이트 self로 설정
        pushViewController.delegate = self
        self.navigationController?.pushViewController(pushViewController, animated: true)
    }
    
    // ...
}
```

***Stepper***
- 처음에 Stepper 액션을 처리할 때 재고를 변경해주는 addStock()과 useStock()을 이용하는 방법을 구상했으나 따로 연산 처리를 해줄 필요도 없이sender.value로 변경된 값을 amount로 바로 가져와 changeStock()을 호출하여 변경된 값을 fruitStock에 업데이트하고 composeText()로 재고를 구성해주도록 구현했습니다.
### 조언을 얻고 싶은 점
***storyboard와 code***
- 현재 프로젝트는 view를 storyboard를 사용하여 만드는 프로젝트인데
- stepper의 tag나 minimumValue와 같은 프로퍼티는 storyboard와 코드에서 둘 다 수정할 수 있습니다.
- 과연 두 가지 방법은 각각 어떠한 상황에서 쓰이면 좋을지 궁금합니다.

2023-05-22 00:22 UTC, jsa0224 requested changes
안녕하세요! 저스버그, 에릭!
프로젝트 잘 보았습니다. 수고 많으셨어요!
이제 마지막 스텝이네요..🥲
이번 프로젝트로 얻어가신 부분들이 많으셨음 좋겠네요😊

## 고민하신 부분에 대한 답변
> ***Singleton*** & ***Delegate***

그 때 이야기하셨던 부분들에 대한 고민들을 잘 정리해주셨네요!
`delegate`에 대한 개념과 `protocol` 활용이 어려우실 수도 있는데, 잘 구현하셨군요👍
`JuiceMakerViewController` 입장에서는 수정된 과일 재고만 알면 되기 때문에, 좋은 구현 방식인 거 같습니다.

## 조언을 얻고 싶은 부분에 대한 답변
> ***storyboard와 code***
> - 현재 프로젝트는 view를 storyboard를 사용하여 만드는 프로젝트인데
> - stepper의 tag나 minimumValue와 같은 프로퍼티는 storyboard와 코드에서 둘 다 수정할 수 있습니다.
> - 과연 두 가지 방법은 각각 어떠한 상황에서 쓰이면 좋을지 궁금합니다.

나중에 뷰가 많아지게 된다면 `InterFace Builder`로 일일이 설정을 확인하는 것이 번거로워, 코드로 구현하는 게 좋다는 생각이 듭니다.

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +}
- `delegate` 역할을 하는 타입명에 `Protocol`라는 네이밍은 적절하지 않아 보여요. `delegate`가 포함되는 네이밍이었으면 좋겠습니다. 
- 따로 파일을 나눠주셨으면 좋겠어요!

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    var delegate: ChangeStockProtocol?
- `은닉화`가 안 되어 있네요! 
- 둘 다 `var`인 이유가 있나요?

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    }
물론 `닫힌다` 라는 기능으로서 `close`가 적절할 수 있겠지만, 버튼을 눌렀을 때가 먼저 선행되어야 하기에, `tap`이 앞으로 오는 게 적절해보입니다.

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        guard let fruit = Fruit(rawValue: sender.tag) else { return }
이렇게 되면 `Fruit`의 `rawValue`가 `Int` 타입이 되는데, `Fruit`이 `Int` 타입과 무슨 연관이 있나요?

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        mangoStockStepper.value = Double(fruitStore.bringStock(.mango))
두 메서드 모두 `구성한다`라는 의미로, `compose`와 `set`을 사용하셨는데, 통일성을 위해서 둘 중 하나로 통일해주셨으면 좋겠습니다.

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        mangoStockStepper.minimumValue = -1
- `changeStockStepper()` 메서드 내부 구현이 `value`가 `0` 이하로 내려갈 경우 `value`를 `0`으로 설정해주시는데, 왜 `minimumValue`은 `-1`로 설정해주셨는지 궁금합니다.

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    private func popUpNonChangeableMessage() {
얼럿을 띄워준다는 의미의 네이밍이 적절해보입니다!

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController, ChangeStockProtocol {
보통은 가독성의 문제로 extension으로 확장해서 구현해주기도 합니다!

```suggestion
class JuiceMakerViewController: UIViewController { }

extension JuiceMakerViewController: ChangeStockProtocol { }
```

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +              let juice = Juice(rawValue: title) else {
위와 연관되는 코멘트를 남기자면, `Juice`는 `String` 타입과 무슨 연관이 있나요?

2023-05-22 00:22 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/UIViewController+Extensions.swift
> +}
LGTM👍
UIAlertController의 재사용성이 좋아졌네요👍
`title`이나 `message`가 `nil`일 가능성도 있으니, 파라미터 타입 선언을 옵셔널로 해줘도 좋을 거 같습니다!

2023-05-22 02:09 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +}
따로 프로토콜 파일을 생성하여 ChangeStockDelegate로 네이밍 수정했습니다.

2023-05-22 02:14 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    var delegate: ChangeStockProtocol?
- `JuiceMakerViewController`에서 `ChangeViewController`의 `fruitStore`와 `delegate`에 접근해야하기 때문에 은닉화를 하지 않았습니다.
- 구조체 인스턴스를 변경하기 위해서는 var로 선언해주어야 합니다.
- `delegate`도 옵셔널 `ChangeStockDelegate`타입으로 지정되어 있어 나중에 값이 바뀌거나 할당되기 위해 var로 설정해주어야 합니다.

2023-05-22 02:29 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    }
Tap을 앞으로 빼서 네이밍 수정했습니다.

2023-05-22 02:43 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        mangoStockStepper.minimumValue = -1
Stepper은 minimumValue의 디폴트 값이 0으로 설정되어 있는데 만약 따로 -1로 설정해주지 않은 상태로 재고가 0인 상태에서 -를 클릭할 경우 alert를 띄울 수 없기 때문에 따로 값을 -1로 설정해주었습니다.

2023-05-22 02:47 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        mangoStockStepper.value = Double(fruitStore.bringStock(.mango))
setText, setStepperValue로 통일했습니다.

2023-05-22 02:48 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +    private func popUpNonChangeableMessage() {
Message를 Alert로 모두 수정했습니다.

2023-05-22 02:51 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController, ChangeStockProtocol {
extension으로 확장해서 구현해주었습니다!

2023-05-22 02:59 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/UIViewController+Extensions.swift
> +}
`title`과 `message`의 파라미터 타입을 옵셔널로 바꾸고 `nil`일 때는 빈문자열을 디폴트값으로 주도록 설정했습니다.

2023-05-22 03:07 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        guard let fruit = Fruit(rawValue: sender.tag) else { return }
- stepper로 `Fruit`의 재고를 변경하게 되는데 이때 하나의 함수로 여러개의 stepper를 처리하기 위해서 tag를 사용했습니다.
- `ViewController`에서 분기처리를 하지 않고 모델에서 tag에 맞는 과일을 가져오기 위한 목적으로 Int를 원시값으로 설정했습니다.

2023-05-22 03:14 UTC, JusBug commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +              let juice = Juice(rawValue: title) else {
Juice에서 열거했던 각 과일들의 원시값을 이용하여 Button currentTitle 개체 값을 String으로 비교하기 위해서 사용했습니다.

2023-05-22 15:04 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        guard let fruit = Fruit(rawValue: sender.tag) else { return }
주신 답변에 대한 저의 생각은 간편한 구현을 위해 원시값을 `Int`로 설정해주신 거 같아요.
하지만 객체지향관점에서 생각해본다면, `Fruit`과 `Int`는 무슨 연관성이 있을까요?

[Implicitly Assigned Raw Values](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations#Implicitly-Assigned-Raw-Values)에서 `enum`에 `Int 원시값`을 사용하는 예시로 소개되는 `Planet` 타입의 경우 'n번째 행성'이라는 연관성이 있을 것 같습니다.

이러한 연관성이 `Fruit`에도 있을까요?

2023-05-22 15:25 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        mangoStockStepper.minimumValue = -1
![스크린샷 2023-05-23 오전 12 13 36](https://github.com/yagom-academy/ios-juice-maker/assets/94514250/9028a4a3-f1ea-468b-b58b-4e57ac7fa0b2)
잘 보이실지 모르겠네요!
해당 코드를 주석 처리하고 프로그램을 실행해보면, 딸기 재고가 0이 되었을 때, `stepper`의 `-` 부분이 비활성화되는 게 보이시나요?
옆의 바나나 `stepper`의 `-` 부분과 비교해보시면 차이를 느끼실 겁니다!

- 따로 `minimumValue`을 설정해주지 않으면 `default`로 0으로 설정됩니다.
- `Alert`은 언제 사용되는 게 좋을까요? 제가 이전 PR에서 `Alert` 관련 `HIG 문서`를 보내드렸던 걸로 기억해요.
물론 `Alert`이, 사용자에게 `정보 제공 기능`도 할 수 있겠지만, 이 케이스는 `경고`에 가까운 거 같습니다.
위의 내용처럼 앞서 `stepper`의 `-` 부분이 비활성화 되어 사용자는 더 차감이 안 된다는 경험을 얻을텐데, `Alert`으로 경고를 줄 필요성이 있을까요?

2023-05-23 02:01 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        mangoStockStepper.minimumValue = -1
- `Alert`를 재사용해보기 위해서 그리고 0 미만의 값으로는 재고 변경이 안된다는 정보를 주기 위해 사용했습니다!
- som 말대로 정보를 주기보단 경고에 가까웠던 것 같네요! 이미 stepper에서 최솟값이 0일 때는 버튼이 비활성화되니 경고를 줄 필요성은 없을 것 같습니다.

2023-05-23 02:04 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        guard let fruit = Fruit(rawValue: sender.tag) else { return }
- Fruit과 Int의 연관성을 찾자면 ‘n번쨰로 화면에 보이는 과일’이라고 할 수 있겠네요.. Model로서의 Fruit을 생각했을 때는 연관성이 없는 것 같습니다.

2023-05-23 02:27 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +              let juice = Juice(rawValue: title) else {
위에 달았던 제 답변 보시고, 이 부분도 고민해주세요!

2023-05-23 04:16 UTC, h-suo commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +              let juice = Juice(rawValue: title) else {
넵! `Juice`도 `Fruit`과 같이 원시값으로 처리하지 않고 `JuiceMakerViewController`내부에서 `currentTitle`로 분기처리하여 구현하였습니다.

2023-05-23 06:30 UTC, jsa0224 commented
수고하셨습니다! 에릭, 저스버그👍
머지 진행하면서 한 가지 추가로 더 고민해보셨으면 좋겠습니다.
현재 `JuiceMaker`의 프로퍼티인 `fruitStore`이 은닉화되지 않은 상태로, `ViewController`에서 활용되고 있습니다.
이 부분이 `의존도`가 높아지고 있는 거 같은데, 어떻게 해결할 수 있을 지 고민해보시면 좋을 거 같아요😊

2023-05-23 06:30 UTC, merged