쥬스 메이커 [Step3] EtialMoon, 비모
yagom-academy/ios-juice-maker pull request #335
Opened 2023-05-22 12:51 UTC by bubblecocoa

@jsa0224 
안녕하세요 Som!
EtialMoon & 비모입니다.
Step3 PR 보내드립니다.
잘 부탁드립니다. 🙇

---

### 고민했던 점
#### 중복되는 showAlert 메서드
`FruitStoreViewController`에서 에러 발생 시 얼럿을 보여주기 위해 `JuiceMakerViewController`의 `showAlert` 메서드를 그대로 가져왔습니다.
두 뷰컨트롤러 사이에 중복되는 코드를 어떻게 줄일까 하다가 `Alert`이라는 클래스를 싱글톤으로 만들었습니다.
결과적으로 두 뷰컨트롤러에서 중복된 메서드를 제거하고, 얼럿 발생 코드를 깔끔하게 작성할 수 있게 되었습니다.

#### 불필요한 메서드 제거
재고 수정 뷰에서 과일 수량의 감소, 증가에 대한 모든 변화를 한 번에 적용하도록 `changeStock`메서드를 만들었습니다.
과일 쥬스를 만들때는 `useStock` 메서드를 사용하지만, 과일 추가를 한다고 `addStock`을 사용하고 있진 않습니다.
코드 전체적으로 아무곳에서도 `addStock`를 활용하고 있지 않기때문에 해당 메서드는 제거했습니다.

---

### 조언을 얻고싶은 부분
#### JuiceMakerViewController에서 juiceMaker.fruitStore.{something}
이렇게 타고 타고 들어가는 것을 뭐라고 불러야 할지 모르겠습니다.
`JuiceMakerViewController`가 `JuiceMaker`를 가지고 있고 `JuiceMaker`가 `FruitStore`를 가지고 있는 상태입니다.
이렇게 접근하게 되면 결국 `JuiceMakerViewController`가 `FruitStore`에 직접 접근하게 되는 것이 아닌가요? 이렇게 되는 상태를  서로 의존도가 높아지는 것이라고 할 수 있을까요?

2023-05-23 06:06 UTC, jsa0224 requested changes
안녕하세요! 비모, 문!
프로젝트 잘 보았습니다.
이제 마지막 스탭이네요🥲
이번 프로젝트에서 얻어가신 부분들이 많으셨으면 좋겠습니다😊

## 고민하신 부분에 대한 답변

> **중복되는 showAlert 메서드**

- 이 부분에 대한 구현은 너무 잘해주셨고, 보통 `AlertManager` 혹은 `AlertBuilder`라는 객체로 구현이 됩니다. 
- 하지만 코멘트에서도 남겼다시피, `alert`을 띄워주는 기능을 이 객체에서 하는 것이 적절한 지 의문이 듭니다. 

> **불필요한 메서드 제거**

이 부분도 정답은 없습니다.
제 스타일은 `add` / `use` 기능을 각각 구현해서 활용하는 편이고, 비모와 문처럼 `change`라는 메서드에 변경된 값만 넣어서 구현할 수도 있죠!

## 조언을 얻고 싶은 부분에 대한 답변
> **JuiceMakerViewController에서 juiceMaker.fruitStore.{something}**

그렇죠. 의존성이 높아지는 부분이라고 저도 생각이 드네요.
- `JuiceMaker`에서 `FruitStore`에 관련한 기능을 메서드로 구현하여 의존성을 낮추는 방법도 있을 거 같습니다.
- 한편으로는 고민되시는 부분이 바뀐 재고를 두번째 `ViewController`에 전달하는 부분인데, 그 역할을 `JuiceMaker`에서 하는 게 적절한가? 라는 생각도 드네요. 
`JuiceMaker`는 쥬스를 만들어주는 역할, `FruitStore`는 과일 재고를 관리하는 역할이죠. 
그래서 과일 재고를 전달하는 역할도 `FruitStore`이 하는 게 적절하다고 저는 판단되네요. 
한 번 고민해보세요!

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/Alert.swift
> +    static let `default` = Alert()
싱글톤으로 구현하신 이유가 있나요?

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +}
- 메서드의 파라미터명이 `fruits`인 게 적절해보이지는 않습니다. 
재고인 `stock`이 적절한 네이밍 아닐까요?
- 이 부분 따로 파일로 분리해주세요~

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
>  final class FruitStoreViewController: UIViewController {
과일 재고를 추가하는 `ViewController`인데, 과일 저장소라는 네이밍은 어색해보입니다.

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var fruits: [Fruit : Int]?
- 해당 프로퍼티는 왜 옵셔널로 지정해주셨나요?
- 위와 마찬가지로 재고를 뜻하는 네이밍이 적절해보입니다.

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            Alert.default.showAlert(self, title: title, message: message, actions: actions)
따로 title 변수를 nil로 설정해주지 않아도, showAlert 메서드의 파라미터 값을 nil로 지정하면 되지 않을까요?

ex)
```swift
Alert.default.showAlert(self, title: nil, message: message, actions: actions)
```

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/Alert.swift
> +        viewController.present(alert, animated: true)
해당 객체는 뷰인가요? 왜 띄워주는 역할을 수행하고 있나요?

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        }
`tag` 값은 `인터페이스 빌더`에서 설정해주셨나요?
코드로 `tag` 값을 설정하는 방법도 있는데, 저는 코드로 설정하는 것이 `휴먼에러`를 훨씬 줄일 수 있을 거 같습니다.

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +final class JuiceMakerViewController: UIViewController, FruitStoreDelegate {
주로 가독성을 위해 extension으로 확장하여 프로토콜을 채택해주기도 합니다.
```suggestion
final class JuiceMakerViewController: UIViewController { }

extension JuiceMakerViewController: FruitStoreDelegate { }
```

2023-05-23 06:06 UTC, jsa0224 commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +            Alert.default.showAlert(self, title: title, message: message, actions: actions)
이 부분도 위와 같은 부분이 있는데, 고민해보세요!

2023-05-24 00:48 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
>  final class FruitStoreViewController: UIViewController {
`FruitStoreViewController`에서 `FruitStockViewController`로 변경했습니다.

2023-05-24 07:06 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +final class JuiceMakerViewController: UIViewController, FruitStoreDelegate {
`FruitStoreDelegate` 채택을 `extension`으로 옮기고, 명세 메서드도 해당 클로저 안으로 이동했습니다.

2023-05-24 07:08 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +        }
`tag` 값을 사용하는 뷰컨트롤러 모두 코드로 설정하는 방식으로 변경 적용하였습니다.

2023-05-24 07:12 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/Alert.swift
> +        viewController.present(alert, animated: true)
저희가 했던 고민인 '중복되는 showAlert 메서드' 에 관해 `present` 코드까지 줄여보고자 해당 코드를 작성했던 것인데,
현재는 빌더패턴으로 변경하며 해당 객체의 역할에서 벗어난다고 생각하여 제거되었습니다.

또한, 변경 전 객체도 ViewController의 기능 중 Controller의 역할만 하고 있음을 인지하게 되었습니다. 🙇

2023-05-24 07:14 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var fruits: [Fruit : Int]?
코드 전체적으로 사용된 `fruits` 라는 네이밍을 확인해보니 용도에 적합하지 않아보여 `fruitStock`으로 변경했습니다.

해당 프로퍼티가 빈 값일수도 있다고 생각했는데, 오히려 그 때문에 불필요한 옵셔널 바인딩 코드가 늘어나는 것을 확인했습니다.
현재는 기본값 `[]`으로 변경했습니다.

2023-05-24 07:15 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
>  final class FruitStoreViewController: UIViewController {
추가 하는 기능 뿐만 아니라 재고 자체를 관리할 수 있는 기능이기 때문에 `FruitStockViewController`로 변경 했습니다.

2023-05-24 07:16 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +}
해당 부분 `Controller`내에 `Delegate` 그룹을 만들어 분리했습니다.

`fruits`는 `fruitStock`으로 변경했습니다.

2023-05-24 07:18 UTC, bubblecocoa commented on JuiceMaker/JuiceMaker/Controller/Alert.swift
> +    static let `default` = Alert()
중복되는 메서드 `showAlert`을 한 곳에서 전역적으로 사용한다고 생각하다보니 싱글톤이 되었던 것 같습니다.
하지만 위에서 주신 네이밍 힌트에 영감을 받아 팩토리 패턴, 빌더 패턴을 학습 후 빌더 패턴이 더 적합하다고 판단해 빌더패턴으로 변경했습니다.

2023-05-24 07:44 UTC, bubblecocoa commented
@jsa0224 
위에 코멘트 주신 부분 모두 확인했습니다!

> - JuiceMaker에서 FruitStore에 관련한 기능을 메서드로 구현하여 의존성을 낮추는 방법도 있을 거 같습니다.
> - 한편으로는 고민되시는 부분이 바뀐 재고를 두번째 ViewController에 전달하는 부분인데, 그 역할을 JuiceMaker에서 하는 게 적절한가? 라는 생각도 드네요.
>    JuiceMaker는 쥬스를 만들어주는 역할, FruitStore는 과일 재고를 관리하는 역할이죠.
>    그래서 과일 재고를 전달하는 역할도 FruitStore이 하는 게 적절하다고 저는 판단되네요.
>    한 번 고민해보세요!

생각을 공유한 결과 쥬스를 만드는 역할 <-> 과일 재고를 관리하는 역할을 담당하기 위해서는 별도의 객체가 필요하다고 생각했습니다. e.g. `FruitManager`
하지만 그렇게 될 경우 `FruitStore`가 너무 수동적인 존재가 되고, 프로젝트 전체적인 복잡도가 높아질 것 같았습니다.
`FruitStore`는 단어상으로는 무생물이지만, 능동적으로 재고 관리와 재고 전달 등의 역할을 수행할 수 있어야 한다고 생각했습니다.
결론적으로는 솜이 주신 의견과 같은 결론이 나왔습니다 🙌
때문에 추가 객체 생성이나, 메서드 작성 없이 현행 코드를 유지하기로 했습니다.

2023-05-25 01:28 UTC, bubblecocoa commented
이전 코멘트의 번복입니다. 😅

별도 타입은 추가하지 않고 `JuiceMaker`에 추가 메서드를 작성했습니다.
해당 메서드를 활용해 `JuiceMaker`의 `FruitStore`에 대한 의존성을 제거했습니다.

+ 오탈자 수정, 컨벤션 정리 등 추가 작업 진행했습니다!

2023-05-26 05:27 UTC, jsa0224 commented
수고하셨습니다! 비모, 문👍
시간이 남으신다면, 이번 프로젝트의 핵심 개념들! 다시 한 번 복습해봐도 좋을 거 같아요!

2023-05-26 05:27 UTC, merged