쥬스 메이커 [Step1] 미르, 찰스
yagom-academy/ios-juice-maker pull request #344
Opened 2023-09-12 06:59 UTC by Charl-es

@lxodud
안녕하세요 하모! 
Step 1 제출합니다!

---

### 고민했던 점
- 과일의 재고를 어떻게 처리해야할 지를 고민했습니다.
   - 해당하는 과일과 재고를 연관지어 정보를 담을 수 있는 `Dictionary`를 사용하여 해결했습니다.
- 각 과일의 수량 n개를 변경하는 기능을 어떻게 구현할 지 고민했었습니다.
   - 재고를 증가하는 함수와 감소하는 함수를 각각 구현을 해주었고 이를 딕셔너리 메소드 중 `updateValue` 를 사용하여 값을 변경시켰습니다.
 - 쥬스 종류마다 소모되는 재료를 어떻게 해결할 지 고민했습니다.
    - `Juice` 열거형에서 계산속성을 사용하여 쥬스 종류마다 분기처리를 하여 소모되는 재료를 반환시키도록 하였습니다.
- 재고가 부족할 때 어떻게 처리하면 좋을 지 고민했습니다.
   - 오류처리를 하여 재고가 부족하다는 것을 `CustomStringConvertible`프로토콜을 채택하여 해당 오류를 실행할 때 적절한 문자열을 반환하도록 하였습니다.

---

### 조언을 얻고 싶은 점
- `JuiceMaker`에서 `makeJuice` 함수를 실행할 때 분기처리마다 `do-catch`문을 사용하여 오류처리를 해주었는데, 이 부분에 대하여 어떻게 좀 더 가독성이 좋도록 처리할 수 있을 지에 대한 조언을 얻고 싶습니다.

2023-09-12 16:14 UTC, lxodud commented
안녕하세요 미르, 찰스!!
고생 하셨습니다 😃

## 조언을 얻고 싶은 점

> `JuiceMaker`에서 `makeJuice` 함수를 실행할 때 분기처리마다 `do-catch`문을 사용하여 오류처리를 해주었는데, 이 부분에 대하여 어떻게 좀 더 가독성이 좋도록 처리할 수 있을 지에 대한 조언을 얻고 싶습니다.

아래 코멘트에 답변 남겨뒀습니다!!

이해가 안되거나 질문이 있다면 언제든지 연락주세요!!

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> -import Foundation
불필요한 프레임워크 import 제거 좋습니다 👍👍👍

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
class를 사용하신 이유가 있나요??

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitStock: [Fruit: Int]
외부에서 접근해야 하는 프로퍼티인가요??

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addFruitStock(fruitName: Fruit, count: Int) {
fruit라는 정보가 중복되고 있기 때문에 생략하는게 좋을 것 같습니다.
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)에 Naming 파트를 참고해봅시다!!

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func subtractFruitStock(fruitName: Fruit, count: Int) throws {
위 코멘트와 같습니다.

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
```swift
guard let currentStock = fruitStock[fruitName],
      currentStock - count >= 0
else {
    throw FruitStoreError.outOfStock
}
```
저는 개행하는 것을 선호합니다 😎

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStoreError.swift
> +enum FruitStoreError: Error, CustomStringConvertible {
CustomStringConvertible을 사용하신 점 좋습니다 👍👍👍
추가적으로 LocalizedError에 대해서 공부해보셔도 좋을 것 같습니다!!

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
struct를 사용하신 이유가 있나요??

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore(fruitStock: [.strawbery: 10, .banana: 10, .pineapple: 10, .kiwi: 10, .mango: 10])
외부에서 접근할 필요가 있는 프로퍼티인가요??

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func subtractFruitStock(juice: Juice) throws {
외부에서 JuiceMaker 인스턴스에게 주스를 만드는 작업 이외에 재고를 줄이는 작업을 시킬 일이 있나요??
없다면 은닉화하는게 좋을 것 같습니다.

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) throws {
- make로 시작하는 네이밍은 사용처가 분명하기 때문에 개인적으로 지양하는 편입니다.
  - [API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)를 참고해봅시다.
- 내부에서 모든 error를 다 처리하고 있는데 throws 명시해줄 필요가 있을까요??

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
- 분기처리가 필요하다는 것은 각 케이스 별로 다른 로직이 필요하다는 것인데 해당 코드는 각 케이스별로 같은 동작을 수행하고 있습니다. 즉, 분기처리가 필요없는 코드라고 생각합니다.
- 만약 분기처리가 필요하다고 했을 때 각 케이스별로 do-catch 문을 작성하고 있는데 아래 코드처럼 한번만 사용해도 동일한 동작을 할 수 있다고 생각합니다.
```swift
do {
    switch juice {
    case .strawberyJuice:
        try subtractFruitStock(juice: .strawberyJuice)
    case .bananaJuice:
        try subtractFruitStock(juice: .bananaJuice)
    case .kiwiJuice:
        try  subtractFruitStock(juice: .kiwiJuice)
    case .pineappleJuice:
        try subtractFruitStock(juice: .pineappleJuice)
    case .strawberyBananaJuice:
        try  subtractFruitStock(juice: .strawberyBananaJuice)
    case .mangoJuice:
        try  subtractFruitStock(juice: .mangoJuice)
    case .mangoKiwiJuice:
        try subtractFruitStock(juice: .mangoKiwiJuice)
    }
} catch {
    ...
}
```

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    case strawberyJuice
```suggestion
    case strawberryJuice
```
🤩🤩🤩

2023-09-12 16:14 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    }
LGTM 👍

2023-09-12 16:15 UTC, lxodud requested changes

2023-09-12 16:15 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/Fruit.swift
> +}
아

2023-09-13 02:28 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
참고 문서
- [클래스와 구조체](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures/)
- [클래스와 구조체 사이의 선택](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)

위 두 문서를 읽어보았지만, 클래스와 구조체의 메모리적 부분에 대한 이해는 어느정도 되었으나, 애플에서는 구조체를 권장한다는 문구가 있었기는 하지만  아직까지는 명확하게 언제 구조체를 사용해야하고 클래스를 사용해야 할 지에 대한 부분은 애매모호합니다.

이 부분에 대해 프로젝트를 구현할 때 클래스와 구조체를 구분지어 사용하시는 명확한 기준점이 있으실까요?🤔

2023-09-13 02:28 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    var fruitStock: [Fruit: Int]
이 부분에 대해서는 수정하였습니다!

2023-09-13 02:29 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addFruitStock(fruitName: Fruit, count: Int) {
중복되는 것 같아 `fruitName`에서 `name`으로 수정하였습니다.

2023-09-13 02:29 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func subtractFruitStock(fruitName: Fruit, count: Int) throws {
해당 부분도 수정하였습니다.

2023-09-13 02:33 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
팀원과는 서로 기존 스타일을 선호하는 것을 확인하여 수정하지는 않았습니다만, 

혹시 어떤 컨벤션을 많이 선호하시는 지에 대해 궁금합니다!

2023-09-13 02:34 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
위의 코멘트 주신 부분과 같은 답변입니다!

2023-09-13 02:34 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let fruitStore = FruitStore(fruitStock: [.strawbery: 10, .banana: 10, .pineapple: 10, .kiwi: 10, .mango: 10])
은닉화하여 수정하였습니다!

2023-09-13 02:35 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(juice: Juice) throws {
수정하였습니다!

2023-09-13 02:36 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
피드백 주신 부분에 대해 고민을 해보았는데 말씀대로 명확히 분기처리를 한 이유가 없는 코드였던 것 같아 수정하였습니다!

2023-09-13 05:29 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
컨벤션에 정답은 없습니다. 
전체적으로 통일하는게 중요하다고 생각합니다.
저는 너무 길어진다 싶으면 개행하는 것을 선호합니다.

2023-09-13 05:37 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
클래스와 구조체의 차이점을 기반으로 상황에 따라 판단하는게 중요하다고 생각합니다.
참고하신 [https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes](https://github.com/yagom-academy/ios-juice-maker/pull/344) 문서에서 `Choose Structures by Default`이외에도 어느정도 명확한 기준점을 얘기하고 있습니다. 
이 부분을 자세하게 살펴보시면 좋을 것 같습니다.

2023-09-13 05:40 UTC, lxodud commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private func addFruitStock(name: Fruit, count: Int) {
- addFruitStock의 접근 수준이 private인 이유가 궁금합니다 🤔
- 은닉화를 하는 이유가 궁금합니다 🤔

2023-09-13 06:51 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
알겠습니다. 감사합니다!

2023-09-13 06:59 UTC, Charl-es commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private func addFruitStock(name: Fruit, count: Int) {
외부에서 접근하여 값을 변경시키지 못하게 접근을 막는 것이 은닉화인데, 
단순히 당장 step1에서는 사용되지 않아 착각하여 은닉화를 했었습니다.

2023-09-13 09:37 UTC, lxodud commented
고생하셨습니다 👏🏻👏🏻👏🏻
추가적으로 제가 남기는 코멘트가 전부 정답은 아닙니다.
다른 의견이 있다면 언제든지 말씀해주셔도 괜찮습니다 😃

2023-09-13 09:39 UTC, merged