쥬스 메이커 [Step1] Morgan, Hisop
yagom-academy/ios-juice-maker pull request #346
Opened 2023-09-12 07:53 UTC by devjoon

@Rhode-park
안녕하세요 로데 이번에 쥬스메이커를 제작하게 된 Hisop, Morgan 입니다.
3주동안 잘 부탁드리겠습니다 🙇‍♂️

### 조언을 얻고싶었던 점
---
- FruotStore의 changeQuantity를 +,- 메서드로 각각 분리해서 처리할지 고민되었습니다.

- 네이밍과 코딩컨밴션이 적절한지 고민되었습니다.

- FruitStore의 fruitList를 딕셔너리로 한 것이 적절한지 고민되었습니다.

- 요구사항중 "JuiceMaker는 FruitStore를 소유하고 있습니다" 라는 요구사항을 정확하게 이해한게 맞는건지 고민되었습니다.
(저희는 프루트스토어를 구조체로 만들어서 쥬스메이커에 인스턴스의 형태로 제공하였습니다.)

2023-09-13 06:07 UTC, Rhode-park requested changes
3주간 잘 부탁드립니다.
프로젝트 하시다가 궁금한 점이나 해결하기 어려운 점들이 있으면 주저하지 말고 DM부탁드립니다.


## ✅ 조언을 얻고싶었던 점
> * FruotStore의 changeQuantity를 +,- 메서드로 각각 분리해서 처리할지 고민되었습니다.
> * 네이밍과 코딩컨밴션이 적절한지 고민되었습니다.
> * FruitStore의 fruitList를 딕셔너리로 한 것이 적절한지 고민되었습니다.
> * 요구사항중 "JuiceMaker는 FruitStore를 소유하고 있습니다" 라는 요구사항을 정확하게 이해한게 맞는건지 고민되었습니다.
(저희는 프루트스토어를 구조체로 만들어서 쥬스메이커에 인스턴스의 형태로 제공하였습니다.)

* 현재 더해주고 빼주는 메서드가 필요하지 않다면, 빼주는 메서드만 있어도 될 것 같습니다. 그런데, 빼주는 메서드만 있는 것이라면, 재고를 소비하기만 하는 것인데.. 네이밍이 적절한지에 대해서는 의문이 듭니다.
* 네이밍에 대해서는 코멘트 드렸습니다.
* 딕셔너리로 만들어주셨군요. 멋집니다! 혹시 다른 고민되는 방법이 있으셨을까요? 딕셔너리가 아니라면 어떤 방법으로 fruitList를 만들고자 하셨는지 궁금합니다.
* `JuiceMaker`가 `FruitStore`를 소유하고 있는 것 같습니다. 그런데, 쥬스메이커가 프루트스토어의 재고를 주입해줘야 할 필요가 있는지는 의문이 듭니다.

## ✅ 드리고 싶은 말씀
### 1️⃣ 요구사항에 맞춰 프로젝트 작성하기
전체적으로 요구사항에 맞춰 프로젝트를 잘 작성해주셨습니다.
그렇지만, 실질적으로 build하려면 문제가 되는 부분들이 조금 있는 것 같습니다.
코멘트 남겨드렸으니, 확인 부탁드립니다.

### 2️⃣ 해당 브랜치에 PR보내기
본인의 해당 브랜치가 아닌 main브랜치에 PR을 보내주셨습니다. 멋집니다!

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/EnumType.swift
> +//  Error.swift
파일명이 EnumType인 것이 적절하지 않아보입니다.
Enum이 이미 Type이기 때문입니다.
파일명을 네이밍하기 어렵다면, Fruit / Menu / OrderFail 등과 같이 enum별로 파일을 분리하는 방법도 있을 것 같습니다.
그리고, 파일명은 EnumType인데, 여기에는 Error.swift라고 되어있네요?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/EnumType.swift
> +enum Menu: String {
Menu안에서 연산프로퍼티를 통해 recipe를 관리하는 방법에 대해서도 고민해보셨을까요?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +struct FruitStore {
어떤 이유로 struct를 사용하고 계신가요?
struct를 사용하신 구체적인 이유가 있으실텐데, 그 이유가 궁금합니다.
class로 바꾸라는 말은 아닙니다.
struct를 사용하게 된 논리가 궁금합니다.
설명 부탁드립니다.

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitList: [Fruit: Int] = [:]
private을 잘 활용해주셨습니다.
다른 접근 제어 키워드는 무엇이 있고, 각각의 키워드는 어떤 접근 제어 레벨을 가지고 있을까요?
또한, swift의 기본 접근 제어 레벨은 무엇인가요

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitList: [Fruit: Int] = [:]
**(참고)** 전반적으로 타입 명시를 해주지 않는 것이 컨벤션입니다.
다음과 같이 쓰면, 타입 명시를 해주지 않을 수 있겠습니다:
```swift
private var fruitList = [Fruit: Int]()

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    mutating func changeQuantity(fruit: Fruit, quantity: Int) {
`changeQuantity`라고 메서드명을 정해주셨습니다.
그런데, 메서드의 기능은 퀀티티를 바꾸는 것보다는 재고를 소모하는 쪽에 더 가깝지 않나 생각이 듭니다.
그 기능을 충분히 나타낼 수 있도록 네이밍해볼까요?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let unwrappedfruit = fruitList[fruit] else {
`unwrappedfruit`라는 네이밍이 적절하지 않아보입니다.

첫째로, 과연 `unwrapped~`라는 표현이 꼭 필요한 표현이었을까 싶습니다.
앞으로 옵셔널을 많이 사용하게 될 것인데, 그 때마다 바인딩 된 변수나 상수를 `unwrapped~`라고 이름 지으실건가요?
[Swift/API Design Guidelines/Naming/Omit needless words](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage)를 참고해보시길 바랍니다.

둘째로, `unwrappedfruit`가 그 자신을 충분히 설명하는 네이밍이 아닌 것 같습니다.
타입이 Int입니다.
그리고 코드의 흐름을 보았을 때, 과일 종류에 따른 재고를 나타내는 상수인 것 같습니다.
그러면, 과일 재고와 관련한 네이밍으로 작성해야겠죠?
변수명, 상수명, 메서드명은 그 각자의 기능 및 역할을 충분히 나타내야합니다.

더불어, Swift는 카멜케이스로 코드를 작성합니다.
이에 따르면 `unwrappedfruit`가 아닌 `unwrappedFruit`이 되어야하는 것이 맞겠죠?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkIngredient(recipe: [Fruit: Int]) -> Bool {
`ingredient`의 뜻은 무엇인가요?
재료라는 뜻입니다.
`checkIngredient()`라는 네이밍을 볼 때는, `Ingredient`자체에 대한 확인을 하고 있는 것처럼 보입니다.
그런데, 이 메서드는 `ingredient`가 존재하는지보다는 `ingredient`의 재고가 얼마나 있는지에 대한 기능에 방점이 찍혀있는 것 같습니다.
`checkIngredientStock()`등의 표현을 사용해보면 어떨까요?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        for (fruit, quantity) in recipe {
딕셔너리에서 `for (key, value) in dictionary`와 같은 방법으로 key와 value를 가지고 iterate할 수 있다는 점을 알고 계십니다. 멋집니다!

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let ingredientQuantity = fruitList[fruit] else {
마찬가지로, `ingredientQuantity`보다는 stock이라는 단어를 사용하는 것이 조금 더 소통하기 좋을 것 같습니다.

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init(ingredientQuantity: Int) {
`init`을 통해서 외부에서 재고를 주입받아야할 이유가 있나요?
`fruitList`를 private로 접근 제어를 해주셨음에도 불구하고, 과일의 개수를 외부에서 알아야 하는 이유가 궁금합니다.

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
마찬가지입니다.
어떤 이유로 struct를 사용하고 계신가요?
struct를 사용하신 구체적인 이유가 있으실텐데, 그 이유가 궁금합니다.

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func takeOrder(order: Menu) throws {
`takeOrder()`메서드를 호출하면 어떤 일이 벌어질까요?
```text
Cannot use mutating member on immutable value: function call returns immutable value
```
이런 에러가 뜨며 build가 되지 않을 것 같습니다.
왜 이런 에러가 뜨게 될까요?
코드의 어떤 부분이 이런 에러를 뜨게 만드는 것일까요?
해당 에러에 대해서 공부를 해보시고, 다음 질문에 대하여 설명 부탁드립니다:
* 왜 이런 에러가 발생하는 것인가요?
* 이런 에러를 피하기 위해서는 어떻게 코드를 작성해야할까요?
* 어떻게 리팩토링을 하셨나요?
* 리팩토링의 근거는 무엇인가요?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func takeOrder(order: Menu) throws {
`mutating`은 어떤 코드인가요?
어떨 때 사용하는 것이며, 왜 사용하셨나요?
설명 부탁드립니다.

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func takeOrder(order: Menu) throws {
throws를 통해서 에러를 던져주고 계십니다. 멋집니다!
그런데, 에러핸들링은 어디서 하고 있나요?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        guard let unwrapRecipe = recipe[order] else {
마찬가지입니다.
더 적절한 네이밍이 있을 것 같습니다.

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        print("\(recipe.keys)가 제작되었습니다.")
정상적으로 build가 된다면, 다음과 같은 결과가 나올 것 같습니다.
```text
[JuiceMaker.Fruit.banana]가 제작되었습니다.
```
의도하신 결과일까요?
제작되는 것은 쥬스가 아닌 과일이네요?
게다가, String으로 표시되지 않고 있네요?
의도하신 바가 아니라면, 어떻게 하면 좋을까요?

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
`init`을 통해서 `recipe`를 관리하고 있는 이유가 있나요?
그 이유가 궁금합니다.

2023-09-13 06:07 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/EnumType.swift
> +enum Menu: String {
enum을 통해서 과일쥬스를 관리하고 계십니다. 멋집니다!
String을 사용해서 rawValue도 주셨군요.
String이라고만 썼을 때, 각각의 rawValue는 어떻게 될까요?
답변 부탁드립니다.

2023-09-13 10:51 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +struct FruitStore {
https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes 를 참조했습니다. 기본적으로 struct 사용을 권장하며, 상속을 사용할때 class를 사용합니다.

저희는 step1에선 상속이 사용되지 않아도 된다고 판단하여 struct를 선택했습니다.

2023-09-13 11:19 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitList: [Fruit: Int] = [:]
Swift의 기본 접근 제어 레벨은 internal 입니다.
> 아래로 갈수록 더 강한 접근제어

- Open , Public : 모듈의 모든 소스파일을 다른 모듈에서도 사용할 수 있는 접근 수준을 부여합니다.
- Internal :  다른 모듈에서는 접근할 수 없는 수준을 부여합니다.
- File-private :  해당 소스파일에서만 접근할 수 있는 수준을 부여합니다.
- Private :  기능을 정의한 내부에서만 접근할 수 있는 수준을 부여합니다.

[Swift 공식문서 접근제어 ](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol/)

2023-09-13 11:32 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    init(ingredientQuantity: Int) {
가게를 만들기 위해선 누군가 초기 재고를 설정해주어야한다고 생각했습니다. 그래서 쥬스메이커가 가게를 생성할 때 초기 재고를 얼마나 채워넣을지 결정하도록 만들어주었습니다.

fruitList 딕셔너리에 값을 하나하나 채워넣어준다고 가정했을때 초기 재고의 양이 변경된다면 하나하나 변경해주어야하는 불편함이 생길것이라 예상했습니다.

2023-09-13 11:33 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
>  struct JuiceMaker {
FruitStore와 동일한 이유로 상속이 사용되지 않아도 된다고 판단하여 struct를 사용했습니다.

2023-09-13 11:48 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/EnumType.swift
> +//  Error.swift
Fruit / Menu / OrderFail 로 파일분리하여 처리하였습니다.
주석부분 수정 완료하였습니다.

2023-09-13 12:07 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var fruitList: [Fruit: Int] = [:]
``` swift
private var fruitList : [Fruit: Int] = [:]
-> private var fruitList = [Fruit: Int]()
```
컨벤션 수정 완료하였습니다.

2023-09-13 12:16 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    mutating func changeQuantity(fruit: Fruit, quantity: Int) {
```changeQuantity``` -> ```reduceStock``` 으로 네이밍 변경했습니다.

2023-09-13 12:20 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        guard let unwrappedfruit = fruitList[fruit] else {
```unwrappedfruit``` -> ```stock``` 으로 네이밍 변경했습니다.

2023-09-13 12:22 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func checkIngredient(recipe: [Fruit: Int]) -> Bool {
```checkIngredient()``` -> ```checkIngredientStock()``` 으로 네이밍 변경했습니다.

2023-09-13 12:24 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard let ingredientQuantity = fruitList[fruit] else {
```ingredientQuantity``` ->  ```stock``` 으로 네이밍 변경하였습니다.

2023-09-13 12:27 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func takeOrder(order: Menu) throws {
- Struct에서 프로퍼티 값을 변경하기 위해서 사용해야합니다.
[Swift 공식문서 메소드](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/methods/)

2023-09-13 12:29 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func takeOrder(order: Menu) throws {
에러 핸들링을 해주려고 했으나 이부분은 나중에 컨트롤러에서 처리하는것으로 판단하여 따로 처리해주지 않았습니다.

2023-09-13 12:37 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        guard let unwrapRecipe = recipe[order] else {
```unwrapRecipe```  -> ```needFruit``` 로 네이밍 변경하였습니다.

2023-09-13 13:20 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        guard let unwrapRecipe = recipe[order] else {
recipe를 recipes로 변경, unwrapRecipe는 recipe로 변경했습니다.

2023-09-13 17:18 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    mutating func takeOrder(order: Menu) throws {
mutating으로 처리해도 당장 문제가 생기진 않았으나 class로 변경해주었습니다.

2023-09-13 17:18 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        print("\(recipe.keys)가 제작되었습니다.")
전달받은 order.rawValue를 출력하도록 변경했습니다.

2023-09-13 17:19 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
사용자가 레시피에 접근하면 안된다는 의도로 구현했던 코드입니다.
현재는 fetchRecipe라는 이름의 private 메서드를 구현하여 변경해주었습니다.

2023-09-13 17:20 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Model/EnumType.swift
> +enum Menu: String {
자동으로 case의 이름과 같이 설정됩니다.

2023-09-14 02:33 UTC, devjoon commented on JuiceMaker/JuiceMaker/Model/EnumType.swift
> +enum Menu: String {
recipe는 fetchRecipe 함수로 접근하는 방식으로 변경하였습니다.

2023-09-14 07:57 UTC, Rhode-park requested changes
코멘트 두 개만 더 달았습니다. 확인 후 반영 해주시면 바로 merge해드리겠습니다.

2023-09-14 07:57 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            guard stock > quantity else {
stock과 quantity가 같을 때는 쥬스를 만들 수 없겠네요?

2023-09-14 07:57 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        }
```suggestion
        catch {
            print(error)
        }
```

이렇게 해주면 어떤 에러로 인해서 쥬스를 만들 수 없는지 나타낼 수 있을 것 같습니다.

2023-09-14 08:11 UTC, merged