Feat: 과일 재고 확인 기능, 과일 쥬스 제조 기능, 과일 제조 기능 추가
yagom-academy/ios-juice-maker pull request #35
Opened 2021-03-08 11:36 UTC by CJMIN

담당 리뷰어 태그 : ex) @yagom 

1번째 STEP

# 📌 코드를 작성할 때 고민되었던 점 :

- 함수를 나누는 일반적인 기준(그냥 궁금한 점)에 대해서 고민하였습니다.
- if guard를 언제 사용할지에 대한 일반적인 기준(그냥 궁금한 점)에 대해서 고민하였습니다.
- switch를 사용할지 if else를 사용할지 고민하였습니다.
- 명세에 없는 것을 switch문의 default에 작성해도 되는지 작성하는 것이 안된다면 어떤 것을 default에 작성해야하는지 고민하였습니다.
- 연산 프로퍼티에서 반환되는 타입을 어떻게 명시할지 고민하였습니다.

# 📌 해결이 되지 않은 점:

- 함수를 나누는 일반적인 기준(그냥 궁금한 점)
- if guard를 언제 사용할지에 대한 일반적인 기준(그냥 궁금한 점)
- switch를 사용할지 if else를 사용할지에 대한 기준
- 명세에 없는 것을 switch문의 default에 작성해도 되는지 작성하는 것이 안된다면 어떤 것을 default에 작성해야하는지

# 📌 조언을 얻고 싶은 부분 :

- 함수를 나누는 일반적인 기준(그냥 궁금한 점)
- if guard를 언제 사용할지에 대한 일반적인 기준(그냥 궁금한 점)
- switch를 사용할지 if else를 사용할지에 대한 기준
- 명세에 없는 것을 switch문의 default에 작성해도 되는지 작성하는 것이 안된다면 어떤 것을 default에 작성해야하는지

2021-03-08 13:23 UTC, yagom requested changes
빠른 커밋을 줬네요.
전반적으로 띄어쓰기와 줄바꿈이 잘 되어있는점 좋네요.

JM의 풀리지 않은 의문점에 대해 답변하기 전에 저도 몇가지 질문을 하고싶어요.

- Git은 왜 사용하는걸까요?
- Git에서 commit은 어떤 의미를 갖나요?
- Git의 commit은 어떤 단위로 나누는 것이 좋을까요?

다른 질문은 코드에 직접 코멘트 남겨두었습니다 :)

JM의 의문점들에 대한 답변입니다.

아래 기준은 제 개인적인 사견이므로 원칙은 아닙니다. 프로그래머마다 다를 수 있기 때문에 참고만 하면 좋겠습니다.
- 제가 메서드를 나누는 기준은 '한 가지 동사로 이름을 나타낼 수 있는가'입니다.
- guard는 이곳을 지나가는 필수조건인 경우에 사용합니다. 반대로 if는 부가적으로 조건을 따져 수행할 일에 대해 사용합니다.
- switch는 좋은점도 있지만 단점도 많습니다. default도 그 질문의 연장선인 것 같아요. 본인이 작성한 코드만으로 결론이 잘 나지 않는다면 검색해보면 더 좋은 글들을 많이 마주해 볼 수 있을것 같아요.

또 궁금한 점이 있으면 이야기 나눠보아요~

2021-03-08 13:23 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
프로퍼티인데 이름은 메서드인 동사형을 띄는군요!
이름은 check인데 반환하는 값은 과일의 정보입니다.
이름을 좀 더 개선해 볼 수 있을것 같아요.

또, `fruitState`를 인스턴스 외부에서 직접 접근하고 수정할 수 있는데, 굳이 `checkFruitInventory` 라는 프로퍼티가 필요한 이유는 무엇일까요?

2021-03-08 13:23 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeFruitJuice(juiceName: String){
`makeFruitJuice`와 `juiceName`에 중복된 이름이 들어가네요.
중복된 단어가 들어갈 필요가 없고, 중복된 단어 때문에 더 혼동이 올 여지가 있습니다.
이름을 개선해보면 좋겠어요.

2021-03-08 13:23 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        case "딸기 쥬스":
혹시나 나중에 이 문자열 "딸기 쥬스"를 실수로 "달기 쥬스"로 변경했을 때, 눈치채기 쉬울까요?
문자열 상수를 로직 코드에서 사용하지 않을 수 있는 좋은 방법은 없을까요?
저 아래 메서드의 switch 구문에서도 마찬가지에요.

2021-03-08 13:23 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            if fruitState.strawberry >= 16 {
16이라는 수가 의미하는바는 무엇인가요?
코드만 보고는 이해하기가 어렵군요.

2021-03-08 13:23 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            if fruitState.strawberry >= 16 {
또, switch라는 조건구문 안에 또다른 조건구문인 if가 위치하지 않도록 개선해볼 수 있을것 같아요.
가독성에도 좋지 않고, 중복될 수 있는 조건이 생길 여지가 크거든요.

2021-03-08 13:23 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
이니셜라이저를 정말 적절히 활용했어요. 좋습니다. 의존성 문제에서 자유로울 수 있겠어요. 👍

2021-03-08 13:23 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addFruit(fruitName: String , numberOfFruit: Int){
이 메서드에서도 fruit라는 단어가 세 번 중복되어 있는데, 더 개선해 볼 수 있겠습니다.

2021-03-08 22:16 UTC, CJMIN commented
@yagom 

리뷰 감사합니다.

Git은 왜 사용하는걸까요? 
-> 버전관리를 위해서 라고 생각합니다.
Git에서 commit은 어떤 의미를 갖나요? 
-> 돌아갈 수 있는 세이브포인트와 같은 의미를 갖는다고 생각합니다.
Git의 commit은 어떤 단위로 나누는 것이 좋을까요? 
-> 언어로 무언가가 바뀌었다고 표현할 수 있을때마다? 
즉, 세이브 포인트 느낌이므로 혼동만 없다면 자주할 수록 좋다고 생각합니다.

2021-03-08 22:23 UTC, CJMIN commented
담당 리뷰어 태그 : ex) @yagom

1번째 STEP

📌 코드를 작성할 때 고민되었던 점 :
switch 문에 있는 if문을 어떻게 하면 없앨 수 있을까?
네이밍 관련된 고민
쥬스를 만들때 차감되는 수를 어떻게 표현하면 좋을지?

📌 해결이 되지 않은 점:
쥬스를 만들때 차감되는 수를 어떻게 표현하면 좋을지?

📌 조언을 얻고 싶은 부분 :
쥬스를 만들때 차감되는 수를 어떻게 표현하면 좋을지?

2021-03-08 22:26 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
아래와 같이 변경하였습니다.

(1) checkFruitInventory -> fruitInventory 

(2) private var fruitStock : FruitInfo

2021-03-08 22:26 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeFruitJuice(juiceName: String){
(1) juiceName -> name

2021-03-08 22:27 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        case "딸기 쥬스":
문자열 상수를 로직 코드에서 사용하지 않기 위해 아래와 같은 열거형을 선언하였습니다.

enum Juice: String {

    case strawberry = "딸기 쥬스"

    case banana = "바나나 쥬스"

    case pineapple = "파인애플 쥬스"

    case kiwi = "키위 쥬스"

    case mango = "망고 쥬스"

    case strawberryBanana = "딸바 쥬스"

    case mangoKiwi = "망고키위 쥬스"

}



enum Fruit: String {

    case strawberry = "strawberry"

    case banana = "banana"

    case pineapple = "pineapple"

    case kiwi = "kiwi"

    case mango = "mango"

}

2021-03-08 22:30 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            if fruitState.strawberry >= 16 {
16을 표현하는 다른 방법으로 쥬스를 만들기 위해 필요한 최소한의 과일의 수를 모두 상수로 선언해볼까 고민했습니다.
작은 표현 때문에 코드가 너무 길어지고 네이밍도 복잡해질 것 같다고 생각하여 좀 더 고민해 보기로 했습니다.

2021-03-08 22:34 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            if fruitState.strawberry >= 16 {
switch문 안의 조건문을 없애기 위해 switch문 아래에 guard를 이용하여 한번 거르고

switch문을 하나 더 추가하였습니다.

개인적으로는 이렇게 구현했을 시에 코드가 너무 길어지는 것 같다는 생각이 들었습니다.

가독성을 높이기 위해서라면 코드의 길이는 충분히 길어져도 되는 건지 여쭙고 싶습니다.

2021-03-08 22:34 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addFruit(fruitName: String , numberOfFruit: Int){
(1) fruitName -> name

(2) numberOfFruit -> number

2021-03-10 04:02 UTC, yagom requested changes
이번 PR엔 커밋을 몇 단계로 나누어 보냈네요 :) 좋은 생각이에요.

> Q.
커밋은 돌아갈 수 있는 세이브 포인트와 유사하다고 생각한다고 이야기 했는데, 지금의 커밋단위는 되돌아가기 적절한 만큼의 단위일까요?
ac8f9dc 커밋은 커밋 메시지와 다른 내용의 변경사항도 포함이 되어있는데, 동료가 커밋 메시지만 보고 되돌리기를 한다면 어떤 일이 발생할까요?

STEP1에는 UI 요구사항이 없는데, STEP1의 commit에 UI 사항(이미지 등)이 포함된 이유는 무엇일까요?


제 개인적인 기준은 이 변경사항을 날려도 아쉽지 않은 만큼(즉, 실행취소 한다고 생각해도 허탈하지 않을 정도) or 한 문장으로 변경사항을 명확히 나타낼 수 있는만큼을 커밋단위로 생각해요.

> Q.
버튼의 배경색은 코드로 구현할 수 없는 건가요?

> Q.
`JuiceMaker` 타입은 클래스로, `FruitInfo` 타입은 구조체로 구현한 이유가 궁금합니다.

> 쥬스를 만들때 차감되는 수를 어떻게 표현하면 좋을지?
의 뜻을 잘 이해하지 못했습니다. 조금 더 설명해주면 좋을것 같아요.
혹시 `makeFruitJuice` 메서드 내부에서 차감되는 수를 말하는걸까요?
딕셔너리, 튜플, 구조체, 열거형 등등 다양한 방식이 있죠. 제 의견으로는 배열 두개를 사용하는 것은 부적절한 선택이었던 것 같아요.

현재의 요구사항과 다른 내용이 PR에 포함되어 있어 머지하기 어렵겠습니다.
STEP 1에 해당하는 사항만 보내주세요 :)

2021-03-10 04:02 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
index는 무엇을 의미하나요?

2021-03-10 04:02 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addFruit(name: String , number: Int){
name의 타입을 String 대신 Fruit를 사용하지 않을 이유가 있나요?

2021-03-10 04:04 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            if fruitState.strawberry >= 16 {
코드의 길이가 길어졌을 때 발생하는 문제점은 무엇이 있을까요?

2021-03-10 04:05 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addFruit(fruitName: String , numberOfFruit: Int){
좋은 변화네요 :)
그런데 number라는 이름은 좀 모호하지 않을까요? 과일의 번호인지 과일의 갯수인지, 모호한 표현일 것 같아요.

2021-03-10 17:22 UTC, CJMIN commented
리뷰어 태그 : @yagom 

1. 커밋은 돌아갈 수 있는 세이브 포인트와 유사하다고 생각한다고 이야기 했는데,
지금의 커밋단위는 되돌아가기 적절한 만큼의 단위일까요?

-> 단위에 대해서 고민 중이 었는데 야곰의 기준을 일단 모방하고
나중에는 협업자들과 커밋단위에 대한 규칙을 세워야 될 것 같다는 생각이 듭니다.
야곰의 커밋 단위 기준을 알려주셔서 감사합니다!


2. ac8f9dc 커밋은 커밋 메시지와 다른 내용의 변경사항도 포함이 되어있는데,
동료가 커밋 메시지만 보고 되돌리기를 한다면 어떤 일이 발생할까요?

-> 동료의 생각과 다른 방향으로 코드가 나타나질 것 같습니다.

커밋 메세지와 변경되 코드가 일치해야 현업에서의 마찰을 줄일 수 있을 것 같다는 생각이 듭니다!



3. STEP1에는 UI 요구사항이 없는데, STEP1의 commit에 UI 사항(이미지 등)이 포함된 이유는 무엇일까요?

-> JuiceMaker.swift 파일만 커밋하려고 했는데 같이 커밋 된 것 같습니다. step1 이외의 내용은 삭제했습니다!

2021-03-10 17:24 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addFruit(fruitName: String , numberOfFruit: Int){
number -> count 로 변경했습니다.

2021-03-10 17:27 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeFruitJuice(name: String) {
enum Juice에 fruitCount라는 연산 프로퍼티와

deductInventory라는 함수 그리고 makeFruitJuice 함수로 나누었습니다.

2021-03-10 17:29 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
enum DeductionCount을 이용하여 로직코드에서 상수를 배제하였습니다.
로직코드에서 상수가 있으면 오류가 날 가능성이 높고 유지보수에 어려움을 겪을 수 있기 때문이라고 생각합니다.

2021-03-10 17:29 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
index는 배열의 원소인 과일을 의미했습니다.
현재 이 코드는 지웠습니다.

2021-03-10 17:30 UTC, CJMIN commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addFruit(name: String , number: Int){
name 타입을 String 대신에 Fruit으로 변경하였습니다.

2021-03-10 17:36 UTC, CJMIN commented
Q.

버튼의 배경색은 코드로 구현할 수 없는 건가요?

구현할 수 있습니다. 협업을 하려면 코드로 구현하는 것이 더 좋을 것 같습니다!

Q.

JuiceMaker 타입은 클래스로, FruitInfo 타입은 구조체로 구현한 이유가 궁금합니다.

c언어나 java에서 사용하는 것처럼 사용했던 것 같습니다.
swift에서의 class와 struct의 사용 기준을 세워봐야겠습니다.

2021-03-13 06:09 UTC, yagom reviewed
리뷰가 늦어져서 미안합니다.
코드를 많이 수정했네요!

새로운 커밋으로 코드를 삭제하기 보다는 revert 등을 시도해봤으면 더 좋았을것 같아요. 다만, revert 했다면 다른 변경사항도 같이 지워졌을테니, 이게 최선이었을지도 몰라요. 그래서 커밋 단위를 잘 나누는 것도 중요합니다.

deduct, make, add 등 여러 메서드를 외부에서 호출할 필요가 있을지 고민해보는 것도 좋을것 같아요. 외부에 드러나야함을 고민해야하는 것은 프로퍼티 뿐만 아니라 메서드도 마찬가지지요. 이니셜라이저도 그렇구요.

딕셔너리일수록 강제 언래핑은 더더욱 지양하는것이 좋습니다.

저는 상속이 꼭 필요하거나 값을 참조 방식으로 접근해야 할 때만 클래스를 선택합니다.
스위프트에선 꼭 상속으로만 타입의 확장이 가능한 것은 아니기 때문에 훨씬 상속에서 자유롭습니다.

다른 개인일정 때문에 아직 프로젝트에 대해 많이 고민하지 못하고 있는것 같아요. 
이 프로젝트는 꼭 숙성시켜 두었다가 두달 뒤 다시 돌아와서 꼭 보면 좋겠습니다.
그 때도 개선의 방향이 보이지 않는다면, 실력이 발전하지 않았다는 뜻으로 생각해도 좋아요.

스텝1 머지합니다.
스텝 2에서 더 개선해볼만한 포인트에 대해 코멘트 남겨두었어요.

고생 많았습니다.

2021-03-13 06:09 UTC, yagom commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func deductFruit(name: Fruit, count: Int){
인스턴스 외부에서 바라볼 때 deductFruit와 deductInventory의 차이는 무엇일까요?

2021-03-13 06:09 UTC, merged