쥬스 메이커 [Step3] Morgan, Hisop
yagom-academy/ios-juice-maker pull request #355
Opened 2023-09-26 12:25 UTC by devjoon

@Rhode-park
안녕하세요 로데 스텝3 PR보냅니다
잘 부탁드립니다

## 고민되었던 점 🧐
- 기존 딕셔너리 구조를 통해 outlet 변수들을 관리했으나 컬렉션을 통해 관리하도록 변경
- delegate 패턴을 통해 juicemaker VC가 fruitStore VC에게 위임받아 재고 갱신을 동작하도록 함
- 재고관리 화면을 present할 때 VC의 프로퍼티에 직접 접근하여 현재 재고를 전달하도록 함
-  FruitStoreViewController  28~33, 51~56 코드에 겹치는 부분이 존재 이부분을 줄일 수 있는 방법에 대한 고민 

## 조언을 얻고 싶었던 점 🥲
- 현재 노티피케이션으로 처리하고 있는 부분을 델리게이트 패턴으로 대체가 가능해보입니다. 변경하는게 적절할까요?

2023-09-27 17:06 UTC, Rhode-park requested changes
## 고민되었던 점 🧐
> * 기존 딕셔너리 구조를 통해 outlet 변수들을 관리했으나 컬렉션을 통해 관리하도록 변경
> * delegate 패턴을 통해 juicemaker VC가 fruitStore VC에게 위임받아 재고 갱신을 동작하도록 함
> * 재고관리 화면을 present할 때 VC의 프로퍼티에 직접 접근하여 현재 재고를 전달하도록 함
> * FruitStoreViewController 2833, 5156 코드에 겹치는 부분이 존재 이부분을 줄일 수 있는 방법에 대한 고민

outlet collection을 사용해주신 점이 정말 멋집니다!
겹치는 코드에 대해서는 코멘트 남겨드렸으니 확인 부탁드립니다.

## 조언을 얻고 싶었던 점 🥲
> * 현재 노티피케이션으로 처리하고 있는 부분을 델리게이트 패턴으로 대체가 가능해보입니다. 변경하는게 적절할까요?

노티피케이션으로 처리할 때와 델리게이트 패턴으로 대체할 때 각각 어떤 식으로 전개가 가능한가요?
각각의 장단점은 어떻게 되는지 역시 알고 싶습니다.
가능하다면, 브랜치를 더 파서, 두 가지 방법을 다 시도해보시고, 어떤 방법이 더 적절할지 생각해보시고 답변 부탁드립니다.

2023-09-27 17:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    @IBOutlet var fruitCountLabels: [UILabel]!
`Outlet Collections`를 사용해주셨습니다. 멋집니다!
이렇게하면, 코드가 좀 더 짧아짐과 동시에 outlet들을 관리할 수도 있겠네요?

2023-09-27 17:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    func updateStock(fruitList: [Fruit: Int]) {
override method보다 아래에 위치하는 것이 좋을 것 같습니다.

2023-09-27 17:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        fruitCountLabels.sort(by: {$0.tag < $1.tag})
`sort`와 `sorted`의 차이점은 무엇일까요?

2023-09-27 17:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        fruitCountLabels.sort(by: {$0.tag < $1.tag})
`FruitStoreViewController`에서는 따로 메서드를 분리해줬는데, 여기에서는 바로 `viewDidLoad`에 넣어주셨네요?

2023-09-27 17:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        NotificationCenter.default.post(name: Notification.Name(OccurNotification.refreshStock.rawValue), object: nil)
`configureNotificationCentre`등의 이름으로 메서드를 만들고 `ViewDidLoad`에서 호출해봄은 어떨까요?

2023-09-27 17:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var fruitList: [Fruit: Int] = [:]
타입 어노테이션과 타입 추론 중 무엇이 이 팀의 컨벤션인가요?
다음과 같이 작성하면 더 좋을 것 같습니다.
```swift
var fruitList = [Fruit: Int]()
```

2023-09-27 17:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            }
이 부분을 별도의 메서드로 분리하면, 중복되는 코드를 막을 수 있을 것 같습니다.

2023-09-28 10:05 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +    func updateStock(fruitList: [Fruit: Int]) {
프로토콜에 해당하는 메서드라 생각하여 제일 위에 둔 것 같습니다. 아래쪽으로 위치 변경 완료했습니다.

2023-09-28 10:09 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        fruitCountLabels.sort(by: {$0.tag < $1.tag})
sort는 원본을 수정하며, sorted는 정렬된 값을 반환합니다.

2023-09-28 10:18 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        fruitCountLabels.sort(by: {$0.tag < $1.tag})
JuiceMakerViewController엔 따로 init을 담당하는 메서드를 만들지 않아서 viewDidLoad에 포함시켰습니다.
여러번 호출 될 가능성이 있는 refrash메서드에 넣어주는 것은 낭비라고 생각했고, 단순히 sort하는 코드 한 줄을 메서드로 분리하는 것은 원치 않아 이렇게 썼습니다.
메서드를 분리하는 것이 더 깔끔할까요?

2023-09-28 10:21 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        NotificationCenter.default.post(name: Notification.Name(OccurNotification.refreshStock.rawValue), object: nil)
configureNotificationCenter 메서드를 만들어 호출하도록 변경했습니다.

2023-09-28 10:21 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +    var fruitList: [Fruit: Int] = [:]
변경했습니다!

2023-09-28 10:53 UTC, Hi-sop commented on JuiceMaker/JuiceMaker/Controller/FruitStoreViewController.swift
> +            }
메서드로 분리하여 호출하도록 변경해주었습니다.

2023-09-28 12:32 UTC, Hi-sop commented
노티피케이션은 클래스 구분 없이 post를 보내고 옵저버를 통해 메서드를 실행하는 식으로 구현되었고,
델리게이트 패턴은 위임받는 쪽의 클래스를 위임하는 쪽이 실행하는 식으로 구현됐습니다.

사용해보면서 델리게이트 패턴은 처리자가 명확히 선언된다는 점, 값의 전달이 노티피케이션의 userInfo에 비해 편하다는 점이 기억에 남고
노티피케이션은 post를 기준으로 실행되므로 옵저빙하는 곳이 여러곳일 경우 더 유용하게 사용할 수 있었겠다. 라는 생각을 했습니다.

사실 이번 프로젝트에서는 어느쪽을 사용하던지 상관 없다는 생각이 들었습니다. 단순히 메서드를 실행하기만 하면 되는 로직을 가지고있어서
명확한 장단점을 찾아내기엔 적절한 예시가 되지 않았던 것 같습니다.

델리게이트로 패턴을 사용해 변경한 브랜치 명은 delegate_test입니다.

2023-09-28 15:06 UTC, Rhode-park commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        fruitCountLabels.sort(by: {$0.tag < $1.tag})
뭐가 되었든 컨벤션에서의 통일성을 가지고 있는게 좋을 것 같다고 생각합니다.

2023-09-29 05:25 UTC, devjoon commented on JuiceMaker/JuiceMaker/Controller/JuiceMakerViewController.swift
> +        fruitCountLabels.sort(by: {$0.tag < $1.tag})
넵 수정 완료했습니다

2023-09-29 06:02 UTC, merged