[Step1] Neph, Ian
yagom-academy/ios-juice-maker pull request #37
Opened 2021-03-09 01:52 UTC by Neph3779

@AppleCEO 

안녕하세요 도미닉! 쥬스 메이커 프로젝트 1차 PR을 보냅니다!
아래에 저희가 고려한 부분과 해결한 내용들을 적어봤어요!
잘못된 점이나 고쳐볼만한 것들에 대해 알려주시면 감사하겠습니다! 😁

### 유지보수 측면에서 고려해본 사항들

1. 과일의 종류가 추가될 수 있다.

2. 쥬스의 요구사항(필요 재료량)이 바뀔 수 있다. 

3. 쥬스의 종류가 추가될 수 있다.

4. 과일 class, 쥬스 class의 사이즈가 커질 수 있다. 

5. 과일과 쥬스의 종류가 매우 많아질 수 있다.

### 해결 방법 

우선 한 파일에 모든 것을 모아놓으면 과일 class, 쥬스 class의 기능들이 많아져 사이즈가 커지거나 과일, 쥬스의 종류가 많아지면 이를 관리하기 어려울 것이라 생각하여 별개의 파일로 관리하고자 했습니다. enum을 사용하자니 enum의 제약사항(rawValue로 Hashable한 값만 채택할 수 있는 부분)이 해결되지 않아서 RawRepresentable 프로토콜을 채용한 구조체를 사용하여 FruitType과 JuiceType을 묶어 관리했습니다.

2021-03-09 07:27 UTC, AppleCEO requested changes
Neph & Ian 고생하셨습니다.
typealias 등 고급스러운 문법들이 많이 보여서 재미있게 봤습니다.
몇가지 체크하고 넘어가고 싶어서 이번에는 변경 요청을 드립니다.
그러면 화이팅입니다!

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    }
재고를 사용한다는 메소드명은 조금 어색한 부분이 있는 것 같습니다.
addStock 메소드의 반대 역할을 하는 것이니 조금 더 좋은 메소드 이름으로 개선해 볼 수 있을까요?

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    }
메소드명이 깔끔하고 좋습니다! 👍

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Juice.swift
> +    }
이 부분은 연산 프로퍼티를 활용할 수 있을 것 같네요.
메소드라기 보다는 상태값 같이 느껴져서요.

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Juice.swift
> +    static let strawberryJuice: Juice = Juice(require: Requirements.strawberryRequirement)
아래 줄들과 같은 역할을 하는 코드로 보이는데요.
이 코드만 Juice 타입을 명시해준 이유가 있을까요?

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        if juice.canMake() {
조건문의 조건에서 메소드를 실행시키는 부분은 좀 어색해보입니다.
조금 복잡하기도 하고요 ㅎㅎ 어떻게 개선할 수 있을까요?

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Juice.swift
> +    var requirements: [fruitAndNeedAmount]
과일마다 필요한 양은 한번 정해지면 고정일 것 같은데요.
고정인 값을 저장하려면 어디에 저장하는게 좋을까요?

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    private(set) var stock: Int = 10
readOnly 로 작성한 것 아주 좋습니다. 💯

2021-03-09 07:27 UTC, AppleCEO commented on JuiceMaker/JuiceMaker/Juice.swift
> +typealias fruitAndNeedAmount = (Fruit: Fruit, needAmount: Int)
typealias 를 사용해보셨군요. 🥇 
typealias를 사용했을 때 장점은 무엇일까요? 혹시 단점도 있을까요?

2021-03-09 07:34 UTC, Neph3779 commented on JuiceMaker/JuiceMaker/Juice.swift
> +    static let strawberryJuice: Juice = Juice(require: Requirements.strawberryRequirement)
문맥상 타입을 명시해주지 않아도 Juice의 instance인 것이 명확한 것 같습니다
가독성을 위해 지우는 것이 좋을 것 같아서 지우도록 하겠습니다 😂

2021-03-09 07:55 UTC, Neph3779 commented on JuiceMaker/JuiceMaker/Juice.swift
> +typealias fruitAndNeedAmount = (Fruit: Fruit, needAmount: Int)
Typealias를 사용하면 임의로 만든 튜플 타입도 이름을 부여한채로 쓸 수도 있고 다른 경우에는 문맥상 더 어울리는 단어로 바꾸어서 쓸수도 있다 생각합니다. 
하지만 코드를 처음 접하는 사람 입장에서 헷갈릴 우려가 있고 적응하는데 시간이 걸릴 수 있다는 단점이 있을 것 같습니다.

2021-03-09 07:58 UTC, Neph3779 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        if juice.canMake() {
canMake 메서드를 연산 프로퍼티로 변경하는 방법으로 해결했습니다!
isEmpty 프로퍼티처럼 자연스럽게 쓸 수 있을 것이라 생각했습니다.

2021-03-09 08:19 UTC, Neph3779 commented
@AppleCEO 
안녕하세요 도미닉! 빠르게 피드백 주셔서 너무 감사합니다! 이렇게 빠르게 피드백이 도착할거라 생각하지 못해서 공부하다 새롭게 든 의문점을 PR요청 글에 적어서 수정하고 있었는데 그 사이 피드백이 도착했어요😂 그래서 이 글의 하단부에 다시 궁금한 점을 질문드립니다!

### 반영한 피드백
1. useStock()의 메서드명을 subtractStock으로 변경하여 더 명확한 의미 전달이 되도록 했습니다.
2. canMake() 메서드를 연산 프로퍼티로 변경했습니다.
이유 : 상태를 확인하는 차원에서 역할이 끝나기 때문에 메서드를 통해 구현할 필요가 없었고 JuiceMaker class의 메서드인 makeJuice내의 조건문 사용도 훨씬 명료해졌습니다.
3. 불필요한 타입 명시를 제거했습니다.
4. 쥬스마다 필요한 과일의 양은 고정적이라 생각하여 Juice의 프로퍼티인 requirements를 상수로 변경하였습니다.
5. typealias를 사용하여 type명을 만들어주었던 fruitAndNeedAmount의 type명을 Upper Camel Casing을 적용하여 FruitAndNeedAmount로 변경하였습니다.

### 궁금한 점
Class의 instance 생성시에 
`let`으로 선언하는 것과 `var`로 선언하는 것이 무슨 차이를 가져오는지 잘 모르겠습니다.
`let`으로 선언한 상수 구조체와 달리 클래스는 두 경우 모두 variable property를 variable로 쓸 수 있는데 왜 둘이 구분되어 있는걸까요? 구글링을 통해 해결하지 못한 부분이라 질문드립니다!

고생해주셔서 감사합니다 😁

2021-03-09 12:28 UTC, merged

2021-03-09 12:29 UTC, AppleCEO commented
reference type 과 value type 에 대해서 찾아보시면 도움이 될 것 같습니다.
variable propery가 value type을 말씀하시는 것일까요?

2021-03-10 03:24 UTC, yagom commented
@AppleCEO 

> reference type 과 value type 에 대해서 찾아보시면 도움이 될 것 같습니다.
> variable propery가 value type을 말씀하시는 것일까요?

클래스의 인스턴스는 `var`로 선언하든 `let`으로 선언하든 프로퍼티의 값을 변경할 수 있죠.
변수(`var`)로 선언한 구조체에서는 프로퍼티의 값을 변경할 수 있는데, 상수(`let`)으로 선언한 구조체에서는 내부 프로퍼티를 변경할 수 없는 것에 대한 질문인듯 합니다.

2021-03-10 03:32 UTC, Neph3779 commented
@yagom 
안녕하세요 야곰!
캠퍼들이 받은 피드백을 하나하나 읽어보시는군요.. 너무 감사합니다!

저 질문에 대해서는 어제 도미닉께 질문을 DM으로 드려 해결했습니다
[어제자 TIL](https://neph3779.github.io/til/2021.03.09-TIL/)에 정리하여 업로드를 마쳤어요!
class의 instance를 let으로 선언하면 참조값을 변경할 수 없다는 차이가 있더군요
struct를 let으로 선언한 경우에 대해서도 var로 선언한 경우와 어떤 차이가 있는지 알아보았습니다.

신경써주셔서 감사합니다!