[STEP 1] Fezz, SooKim
yagom-academy/ios-juice-maker pull request #38
Opened 2021-03-09 02:35 UTC by Fezravien

## [STEP 1] 쥬스 메이커 🧃
@delmaSong 
안녕하세요! `delma`! 

`sookim` 과 쥬스 메이커 step1을 고민해봤어요 🤔

### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ⁉️

- enum, struct, class 구조를 저희 처럼 설계하는 것이 적절할까요?
- 코드의 네이밍 - `whatFruit`, `thisFruit` 
- 가독성을 위해 `switch - case` 를 지양하기 위해 `딕셔너리`를 사용하는 것이 더 좋은 방법일까요? 
- test 입출력의 모호함 ? (어떤 이벤트가 발생하고 어떻게 처리해야 할지의 모호함)
- `딸기` - (딸기 16) / `딸바` -(딸기 10, 바나나 1) 처럼 다른 타입 처리 😱
- guard let만 사용했었는데 guard var는 다른 의미가 있을까요? (검색해보니 사용자 재량(?)이라고 봤어요) 🙃
- 구조체의 값을 변경하기 위해 `mutating` 과 `class`의 참조에 의한 값 변경의 차이점

---

### 조언을 얻고 싶은 부분 👂

- 앱의 이벤트를 처리함에 있어서 저희 설계가 맞는 방향성을 가지는지 궁금합니다. 
  - 과일 저장소 부분이 `class`에 속해야 하는지 따로 `struct`를 만들어야 되는지

2021-03-09 15:07 UTC, delmaSong requested changes
안녕하세요! fezz와 sookim! 작업하신 것 잘 보았습니다 ㅎㅎ
커밋 메시지도 정성스럽게 작성해주셔서 보기 좋았답니다!
JuiceMaker라는 파일에 모든 타입들을 한꺼번에 작성하기보단 각 기능에 맞게 파일도 분리해보면 어떨까요?

### 고민하신 점
> enum, struct, class 구조를 저희 처럼 설계하는 것이 적절할까요?
> - 앱의 이벤트를 처리함에 있어서 저희 설계가 맞는 방향성을 가지는지 궁금합니다.
>  - 과일 저장소 부분이 class에 속해야 하는지 따로 struct를 만들어야 되는지

코멘트에도 남겨놓았는데 enum, struct, class 각각의 타입이 어떤 특징을 가지고 있는지 설명해주실 수 있을까요? 과일 저장소가 클래스여야 하는지 구조체여야 하는지는 각각의 특징과 용도에 따라 알맞게 선택해서 구현할 수 있을 것 같네요

> 가독성을 위해 switch - case 를 지양하기 위해 딕셔너리를 사용하는 것이 더 좋은 방법일까요?

지금 딕셔너리와 switch문을 함께 사용하고 있지 않은가요? 구체적인 사례를 들어서 설명해주실 수 있을까요?

> test 입출력의 모호함 ? (어떤 이벤트가 발생하고 어떻게 처리해야 할지의 모호함)

테스트 케이스를 작성하려고 하시는건가요? 전 보통 메서드나 어떤 기능을 하는 객체를 만들고, 그것이 의도대로 잘 동작하는지를 테스트하고 있습니다.!

> guard let만 사용했었는데 guard var는 다른 의미가 있을까요? (검색해보니 사용자 재량(?)이라고 봤어요) 🙃

먼저 let과 var의 차이가 무엇인지 살펴보시면 도움이 될 것 같습니다

2021-03-10 00:51 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
요구사항에 `읽기전용`으로 과일 재고를 확인이 있어서 읽기 전용으로 과일 저장소를 만들기 위한 프로토콜이에요 

```swift
private(set) fruitStorage: [Fruits : Fruit]
```

프로토콜로 사용하지 않고 class 직접적으로 사용하는게 맞을까요?

2021-03-10 01:24 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
🙆‍♂️

2021-03-10 05:04 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func isCheckedStock(needFruitAmount: Int) -> Bool {
`delma`의 피드백을 생각해보고 파일을 나누고 동작에 대해서 다시한번 생각해보면서 `step 1` 을 재구성 했어요 🙆‍♂️
 - 과일은 움직이는 친구가 아니기 때문에 동작관련된 것들은 잘못된 것 같다고 생각했어요

2021-03-10 05:05 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
`StockError`
- 재고에 대한 에러 이름으로 변경했어요 🙃

2021-03-10 05:17 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +struct Fruit {
> struct와 class는 각각 어떤 특징을 가지고 있고, 어떨 때 무엇을 사용하나요?
- struct 는 값 복사에 의한 전달, class 참조에 의한 전달 
- 구조체와 클래스의 선택 (조건 중 1개 이상을 만족하면 구조체를 사용하는 것을 고려)
  - 구조체의 주 목적이 관계된 `간단한 값을 캡슐화(encapsulate)` 하기 위한 것인 경우
  - 구조체의 인스턴스가 참조되기 보다 `복사`되기를 기대하는 경우
  - 구조체에 의해 저장된 어떠한 프로퍼티가 참조되기 보다 `복사`되기를 기대하는 경우
  - 구조체가 프로퍼티나 메소드 등을 `상속`할 필요가 없는 경우

---
> Fruit을 구조체로 만든 이유가 무엇인가요?

`Fruit` 구조체는 `상속`이라는 부분에 초점이 몰렸던 것 같아요 😧
이번 수정에서는 과일 저장소를 class로 바꾸고 싱글톤으로 사용해봤어요 
- 외부에서 프로퍼티 번경이 있다.

2021-03-10 05:20 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
> Fruit이 이렇게 생겼으면 Fruits의 종류가 하나씩 늘어갈때마다 Fruit의 인스턴스도 매번 동일하게 하나씩 늘어야겠군요? 
- 과일 저장소를 싱글톤으로 만들어봤어요 😀

> 프로퍼티는 private으로 작성해 동작(메서드)만 드러나도록 객체지향적으로 코드를 작성해주세요
- 준수하도록 노력할게요 👍

2021-03-10 05:20 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +enum Furits {
😧

2021-03-10 05:30 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
사용가능한 과일의 양 -> 쥬스를 만들기 필요한 과일 `needFruitsForJuice` 로 변경했어요 

- -999999 처럼 음수로 넘어가는 것을 방지하기 위한 코드
```swift
guard let stock = fruitStorage.fruits[whatFruit], needFruitsForJuice > 0, stock - needFruitsForJuice >= 0 else {
     throw StockError.lackStock
}
```

2021-03-10 05:31 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func fruitStock(fruit: Furits) throws -> Int {
네 🥳

2021-03-10 05:33 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
- 오류처리 부분을 다시 신경써서 해볼게요 ! 🙌

2021-03-10 05:34 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
- 알럿으로 조건에 만족하지 않았을때(재고 부족) 사용자에게 알려주는 방법이 있을 것 같아요 🤔

2021-03-10 05:35 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        case .strawberryJuice:
🤩

2021-03-10 06:26 UTC, Fezravien commented
## [STEP 1] 쥬스 메이커 🧃- 2

@delmaSong 
안녕하세요! `delma`! 

피드백 주신 부분을 적극적으로 생각하고 전체적인 로직을 수정하고, 기능에 따른 파일을 분류해봤어요 🥳

> enum, struct, class 각각의 타입이 어떤 특징을 가지고 있는지 설명해주실 수 있을까요?

- enum
  - 관련된 값의 그룸에 `공통 타입`을 정의하여 이 값들을 코드에서 `안전한-타입` 방식으로 작업할 수 있게 해준다.
- struct, class
  - 구조체와 글래스는 프로그램 코드의 `건축 자재` 역할을 하는 범용적이고, 유연한 `구조물` 이다.
  - struct 는 값 복사에 의한 전달, class 참조에 의한 전달이다.
  - 구조체와 클래스의 선택 (조건 중 1개 이상을 만족하면 구조체를 사용하는 것을 고려한다.)
    - 구조체의 주 목적이 관계된 `간단한 값을 캡슐화(encapsulate)` 하기 위한 것인 경우
    - 구조체의 인스턴스가 참조되기 보다 `복사`되기를 기대하는 경우
    - 구조체에 의해 저장된 어떠한 프로퍼티가 참조되기 보다 `복사`되기를 기대하는 경우
    - 구조체가 프로퍼티나 메소드 등을 `상속`할 필요가 없는 경우

저희는 이렇게 찾아보았어요 🤔 (아직 명확하게 구조체!! 클래스!! 와닿지는 않는거 같아요 😢 )

> 지금 딕셔너리와 switch문을 함께 사용하고 있지 않은가요? 구체적인 사례를 들어서 설명해주실 수 있을까요?

```swift
switch juice {
        case .strawberryJuice:
            guard strawberry - 16 < 0 else {
                return false
            }
            strawberry -= 16
            return true
        case .bananaJuice:
            guard banana - 2 < 0 else {
                return false
            }
            banana -= 2
            return true
        case .kiwiJuice:
            kiwi -= 3
        case .pineappleJuice:
            guard pineapple - 2 < 0 else {
                return false
            }
            pineapple -= 2
            return true
        case .mangoJuice:
            guard mango - 3 < 0 else {
                return false
            }
            mango -= 3
            return true
        case .strawBa:
            guard strawberry - 10 < 0 || banana - 1 < 0 else {
                return false
            }
            strawberry -= 10
            banana -= 1
            return true
        case .mangoKiwi:
            guard mango - 2 < 0 || kiwi - 1 < 0 else {
                return false
            }
            mango -= 2
            kiwi -= 1
            return true
        }
        return false
```

- 초기에 위와 같은 스위치로 하나하나 비교 했었는데 이 부분에 대해서 물어봤었어요. 지금 이 부분은 딕셔너리를 통해 해결을 했어요 🙂



> 먼저 let과 var의 차이가 무엇인지 살펴보시면 도움이 될 것 같습니다 (guard let, guard var)

- 옵셔널을 처리하면서 guard let만 사용해보았는데 혹시 guard var는 `상수`, `변수` 의 의미말고 다른 숨겨진 의미가 있지 않을까 해서 물어봤어요 🙃





### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ⁉️

- Model ,View ,Controller (MVC) 패턴을 사용할때 `Model`에 맞춰서 기능을 구현하는지, `Controller`를 구현하고 `Model`을 맞추는지 
- 저희 설계의 의도는 모델(JuiceMakerModel), 비지니스 로직(JuiceMaker), 컨트롤러, 뷰 이렇게 구성하려는 방향을 가지고 있는데 옳은 뱡향으로 가고 있을까요?
- 과일 저장소는 이 앱의 전체에서 사용한다고 생각하고 싱글톤 패턴을 사용하면 좋을 것 같아서 사용했는데 적절한 선택인가요?
  - 싱글톤 ?
    - 특정 용도로 객체를 하나만 생성하여, 공용으로 사용하고 싶을 때 사용하는 디자인 유형


    | 장점     | \- 한 번의 Instance만 생성하므로 메모리 낭비를 방지할 수 있음<br/>\- Singleton Instance는 전역 Instance로 다른 클래스들과 자원 공유가 쉬움<br/> |
    | -------- | ------------------------------------------------------------ |
    | **단점** | **- Singleton Instance가 너무 많은 일을 하거나, 많은 데이터를 공유시킬 경우 다른 클래스의 Instance들 간 결합도가 높아져 "개방=폐쇄" 원칙을 위배함 (객체 지향 설계 원칙 어긋남)<br/>- 따라서 수정과 테스트가 어려워짐** |

2021-03-10 14:36 UTC, delmaSong requested changes
수고하셨습니다! 파일을 나누니 전보다 한결 보기 편해졌어요 ㅎㅎ 
네이밍에 많이 신경쓰신 흔적이 보였는데 😂 중복을 덜하고 좀 더 구체적이고 명확한 이름이면 좋겠습니다!

- 아직 명확하게 구조체냐 클래스냐 잘 와닿지 않지만 지금처럼 어떤 명확한 기준을 가지려고 하다보면 지날 수록 어디에 무엇을 써야할 지가 뚜렷해질 것 같아요! 지금 잘 써주셨어요 ㅎㅎ
- guard let과 guard var에는 let과 var만큼의 차이만 있고 별다른 차이점은 없는 걸로 알고있습니다!

`미해결 부분`
> Model ,View ,Controller (MVC) 패턴을 사용할때 Model에 맞춰서 기능을 구현하는지, Controller를 구현하고 Model을 맞추는지 | 저희 설계의 의도는 모델(JuiceMakerModel), 비지니스 로직(JuiceMaker), 컨트롤러, 뷰 이렇게 구성하려는 방향을 가지고 있는데 옳은 뱡향으로 가고 있을까요?

저는 요구사항에 따른 모델의 명세는 어느정도 정해져있다고 생각해요. 그리고 결과적으로 얻길 원하는 값들이 있을텐데 이것들을 구하기 위해 어떤 역할로 나눌 것인가, 그 역할들이 어떤 책임을 지게 할 것인가, 또한 각각의 역할들이 어떻게 협력하도록 할 것인가에 초점을 맞춰서 작업하시면 보다 객체지향적으로 코드를 작성하시는 데 도움이 되리라 생각합니다.

>과일 저장소는 이 앱의 전체에서 사용한다고 생각하고 싱글톤 패턴을 사용하면 좋을 것 같아서 사용했는데 적절한 선택인가요?

FruitStock은 현재 앱 내에서 딱 한 인스턴스만 필요한 것 같아 싱글턴을 이용한 것은 좋은 선택이라고 생각합니다 ㅎㅎ 다만 아래에 남긴 코멘트 확인해주세요~

2021-03-10 14:36 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        for (whatFruit, needFruitsForJuice) in juice.juiceRecipe {
`needFruitsForJuice` 라고 하면 `쥬스를 위해 필요한 과일들`.. 이어서 `갯수나 양` 이라는 의미가 담긴 이름이면 더 좋겠어요

2021-03-10 14:36 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                // 알럿 처리 부분
// TODO: - 
처럼 마크업 주석을 이용하면 에디터 상단 코드 네비게이터에 표시된답니다!

2021-03-10 14:36 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func consumeFruit(fruit whatFruit: Fruits, amount needFruitsForJuice: Int) {
여기 이름도 중복이 덜하게끔 변경할 수 있을 것 같아요!

2021-03-10 14:36 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
위에선 주석표시가 있어서 추후 구현 예정이란 것은 알겠는데.. 이부분은 그냥 리턴인가요? 🤔

2021-03-10 14:36 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerModel.swift
> +    }
fileManager가 재고를 더하고 빼는 두가지 작업을 하고있는데 이걸 나눠봐도 좋을 것 같아요~!

2021-03-11 03:01 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMakerModel.swift
> +}
저희도 에러는 다른 파일에 작성하는게 맞다 생각해요 👍 `JuiceMakerError`로 분리했어요!

2021-03-11 03:01 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMakerModel.swift
> +enum Juices {
🙆‍♂️

2021-03-11 03:09 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMakerModel.swift
> +    func fruitManager(fruit Whatfruit: Fruits, amount thisFruitAmount: Int) throws {
``` swift
func manageStorage(fruit kind: Fruits, amount: Int)
```
수정했어요 🙃

2021-03-11 03:20 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMakerModel.swift
> +        }
`싱글톤`을 사용하면서 그 부분은 고려하지 못했던 것 같아요 😢
`private`로 `init`을 하면서 그 안에서 기본 수량을 설정하는 메소드를 호출했어요 😀

2021-03-11 03:20 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMakerModel.swift
> +        switch self {
🙆‍♂️

2021-03-11 03:43 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
> 할당한 변수 stock에 대한 쓰임이 guard문 이후에 없네요..
어떤 기준으로 if와 guard를 사용하시는지 듣고싶습니다.

재고가 없는데 쥬스 주문이 들어오게 되면 `Error`을 던지기 위해서 `guard` 를 사용했어요 
그리고 재고가 존재하면 함수가 끝나게 되고 정상적인 로직으로 돌아가게 했어요 🤔

> needFruitsForJuice의 타입을 UInt로 사용하면 어떨까요? 🤔

저희도 음수값을 처리하기 위해 `UInt`를 생각해봤었는데 Manage 메소드는 과일의 `+, -` 를 관리하는 것으로 생각하고 음수와 양수를 모두 받아서 처리할 수 있게 하기 위해서 `int`로 작성하게 되었어요 

> chcekFruitStock 라는 이름이 조금 모호한 것 같습니다. 앞으로도 되도록 check- 보다는 좀 더 구체적인 표현을 사용해주세요!

`hasFruitStock`

2021-03-11 03:44 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
`step 3` 를 보면 전체 과일의 재고를 보고 추가 구매를 한다고 생각했어요 그래서 전체 재고가 필요하다고 느꼈어요 🤔

2021-03-11 03:50 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeJuice(juice: Juices) {
`func make(order: Juices)` 수정했어요 🙆‍♂️

2021-03-11 04:03 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMakerModel.swift
> +    }
`UInt` 를 사용하지 않은 이유가 이 부분에서 음수와 양수를 모두 받을 수 있게 하여 한번에 처리하기 위해 구성했어요 
혹시 `UInt`를 사용하고 더하고 빼는 부분은 나누는 것이 더 좋을까요? 🤔

2021-03-11 04:30 UTC, Fezravien commented
## [STEP 1] 쥬스 메이커 🧃- 3
@delmaSong 
안녕하세요! `delma`! 

`delma`가 피드백 주신 중복과 모호한 표현이 많았던 `네이밍` 부분을 개선했고, 오류 열거형 부분을 새로운 파일로 분류 했어요 😁



### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ⁉️

- 피드백 주신 부분에 `UInt` 부분에 대해 궁금한 점이 있어요 
  - 저희는 `manageStorage` 에서 음수와 양수를 모두 받을 수 있게 하기 위해 `Int` 를 사용해서 재고를 더하거나 쥬스를 만들어서 재고가 빠지는 경우를 하나의 함수에서 제어 할 수 있게 했어요. 이 부분에서 더하기, 빼기를 따로 만드는 방법에 대해서 말씀해주셨는데 한번에 제어하는 방법이 별로일까요? 
-  `fruitStorage.manageStorage(fruit: kind, amount: -amount)`
  - 메소드의 매개변수와 동일한 네이밍을 사용해도 될까요 ?
- 메소드 자체의 이름에 매개변수 이름을 메소드의 이름이 포함된다고 생각하고 지어도 될까요?
  - 메소드 - addFruit
  - 매개변수 - (Fruit)kind 

- guard 부분에 할당한 변수를 사용하지 않는 경우

  ```swift
  func hasFruitStock(fruit kind: Fruits, amount: Int) throws {
          guard let stock = fruitStorage.fruits[kind], amount > 0, stock - amount >= 0 else {
              throw StockError.lackStock
          }
      }
  ```

  `stock`을 상수에 할당하고 `guard`가 끝나고 사용하지 않는지에 대한 피드백에서 저희는 딕셔너리 옵셔널을 바인딩하고 재고의 상태를 확인하기 위해 `guard`를 사용했고, 에러 상황이 아닐때 `콜백`해서 정상적인 흐름으로 가도록 했어요 

   **다른 방법이 있을까요?** 🤔

2021-03-11 13:02 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
음 결국 사용하는 쪽에서는 과일 전체 재고를 통째로 받은 다음 개별 과일이 몇개 있는지 거기서 헤아리게 되지 않을까요? 이 부분이 과일을 입력받고 거기에 해당하는 과일 갯수를 리턴하는 메소드여도 괜찮을 것 같아요 !
일단은 그대로 가보죠 ㅎㅎ

2021-03-11 13:20 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        do {
`consume(fruit kind: Fruits, amount: Int)` 혹은
`consumeFruit(_ kind: Fruits, amount: In)` 여도 괜찮을듯..?🤔

2021-03-11 13:20 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
> 재고가 없는데 쥬스 주문이 들어오게 되면 Error을 던지기 위해서 guard 를 사용했어요
그리고 재고가 존재하면 함수가 끝나게 되고 정상적인 로직으로 돌아가게 했어요 🤔

그 부분은 if 문으로도 가능할텐데 어떤 기준으로 guard와 if를 선택하시나요? 🤔

2021-03-11 13:20 UTC, delmaSong approved these changes
👏🏼👏🏼👏🏼👏🏼👏🏼
수고 많으셨어요! 피드백을 성실히 반영하려고 하신 점이 눈에 띄었어요😉
스텝2에서 뵈어요! 

`고민하신 점`
>저희는 manageStorage 에서 음수와 양수를 모두 받을 수 있게 하기 위해 Int 를 사용해서 재고를 더하거나 쥬스를 만들어서 재고가 빠지는 경우를 하나의 함수에서 제어 할 수 있게 했어요. 이 부분에서 더하기, 빼기를 따로 만드는 방법에 대해서 말씀해주셨는데 한번에 제어하는 방법이 별로일까요?

별로라기 보다는 현재 consumeFruit(fruit:amount:)이나 addFruitStock(fruit:amount:) 내에서 재고 추가냐 소비냐에 따라 - 붙여주는 것만 다르고 같은 메소드를 호출하고 있어서, 상위에서 기능을 분리한 것처럼 하위에서도 같은 결로 분리하면 어떨까 싶어서 드린 말씀이었습니다. 꼭 별로다, 낫다는 아니어서 일단 이대로 가보죠 ㅎㅎ

> 메소드의 매개변수와 동일한 네이밍을 사용해도 될까요 ?

이부분 메소드의 매개변수와 `argument label`에 동일한 네이밍을 사용해도 되냐는 말씀이실까요? 

> 메소드 자체의 이름에 매개변수 이름을 메소드의 이름이 포함된다고 생각하고 지어도 될까요?

그럼요! 메소드 이름은 argument label까지 포함한답니다.
`walk(at:)`과 `walk(with:)`은 다른 메소드에요!

> guard 부분에 할당한 변수를 사용하지 않는 경우

음 이 부분은 해당 코멘트의 타래로 더 얘기해보죠 ㅎㅎ

2021-03-11 13:22 UTC, merged

2021-03-11 14:51 UTC, Fezravien commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        do {
다음 step2 에서 반영할게요 🙆‍♂️