[STEP 1] - Wody, Alan
yagom-academy/ios-juice-maker pull request #39
Opened 2021-03-09 04:01 UTC by Wody95

@corykim0829 

### 안녕하세요 Cory! 저희 첫번째 PR입니다. 😊

#### 코드를 작성할 때 고민 & 조언을 얻고 싶은 부분
- 과일(재고)과 쥬스(레시피) 데이터를 어떤 방법으로 관리할지 고민되었습니다. 처음에는 확장을 고려하여 배열로 관리할까 고민했었으나 코드가 복잡해지면서 어려움을 느껴 전부 갈아 엎어 간단한 구조로 다시 만들었습니다. '쥬스 메이커'와 같은 프로그램을 만들 때 상용화를 고려한다면 어떤 데이터 구조로 만드는게 좋을까요?
- 유지 보수 측면에서 딕셔너리 구조를 사용하는게 최선일까요?

2021-03-09 05:28 UTC, corykim0829 requested changes
수고하셨습니다! 😃

이번 리뷰에서는 전체적인 로직보다는 함수명이나 변수와 같은 부분을 리뷰해드렸습니다! 이 부분 먼저 반영하시고 로직을 수정하면 좋을 것 같아요!

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func readFruitStock(fruit: Fruit) -> Int {
이 함수명만 보면 `FruitStock`을 Input으로 받아서 처리할 것 같습니다! Int를 반환하면 명사형 함수명도 고려해보는건 어떨까요?

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        let result: Int = fruit.stock
타입이 명확하면 타입을 명시하지 않아도 됩니다!

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                print("\(fruit)의 재고량 부족")
iOS 개발 미션이 시작되었으니 print함수는 최종 코드에는 사용하지 않는게 좋습니다!

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeFruitJuice(juice: Juice) {
함수명 끝에 Juice와 파라미터 juice가 중복되네요! [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/)를 참고해서 수정해보면 좋을 것 같아요 😀

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func plusFruitStock(fruit: Fruit, addStock: Int) {
함수명만 보면 `FruitStock`을 더하는 함수같네요! 또 `addStock` 파라미터가 Int를 의미한다고 생각하기 어려울 것 같아요! 아래 minus 함수도 같이 고민해보세요!

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Type/Fruit.swift
> +    var stock: Int = 10
stock은 10개가 고정인가요?
프로퍼티는 객체지향적으로 코드를 작성하기 위해 접근제한자를 우선적으로 private으로 고려해주세요!

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +//        print("현재 바나나 재고량 : \(testJuiceMaker.readFruitStock(fruit: banana))")
이런 주석 처리는 같이 올리지 않는게 좋습니다! 주석처리한 이유까지 같이 주석을 하는게 좋을 것 같아요!

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Type/Juice.swift
> +    var recipe: [(Fruit, Int)]
`recipe`이 튜플의 배열로 선언되어있는데, 그러면 하나의 `Juice` 클래스는 여러 `recipe`을 가져도 되나요?

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Type/Juice.swift
> +    init(require: [(Fruit, Int)]) {
require 파라미터명이 부자연스러운 것 같아요! 한번 더 고민해보면 좋을 것 같아요 ㅎ

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Type/Fruit.swift
> +var mango = Fruit()
Fruit 인스턴스로 Juice recipe을 구성하셨는데, 이렇게 되면 인스턴스에 의존하게 됩니다! 타입 자체로 처리하는 방법을 고민해보세요! 😀

2021-03-09 05:28 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
plus와 minus모두 하위 객체가 일을 처리하도록 잘 구현하셨네요!

2021-03-09 05:33 UTC, corykim0829 commented
Woody, Alan 수고 많으셨습니다! 정말 빠르게 하셨네요👀 

> * 과일(재고)과 쥬스(레시피) 데이터를 어떤 방법으로 관리할지 고민되었습니다. 처음에는 확장을 고려하여 배열로 관리할까 고민했었으나 코드가 복잡해지면서 어려움을 느껴 전부 갈아 엎어 간단한 구조로 다시 만들었습니다. '쥬스 메이커'와 같은 프로그램을 만들 때 상용화를 고려한다면 어떤 데이터 구조로 만드는게 좋을까요?

제가 생각했을 때에는 step2를 보면 어떤 쥬스 구매버튼을 눌렀을 때 로직을 고민해서 데이터를 선택하면 좋을 것 같습니다! 조금 더 힌트를 드리자면 결국에는 JuiceMaker에서 재고를 모두 관리해야하는 점입니다! JuiceMaker안에서 모두 관리가 되면 좋겠네요 😊

> * 유지 보수 측면에서 딕셔너리 구조를 사용하는게 최선일까요?

모든 데이터는 장단점이 있죠! 각 데이터의 장단점을 정리해보는건 어떨까요? 😀

2021-03-10 03:18 UTC, DragonTigerXYZ commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func readFruitStock(fruit: Fruit) -> Int {
Step1에 "읽기전용"조건에 너무 집중한 나머지, 포커스를 잃어버렸네요.😅😅😅

함수명을 returnFruitStock으로 수정했습니다!

2021-03-10 03:19 UTC, DragonTigerXYZ commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        let result: Int = fruit.stock
주석제거 (remove comments) 처리 했습니다!☺️

2021-03-10 03:32 UTC, DragonTigerXYZ commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeFruitJuice(juice: Juice) {
파라미터의 이름을 함수명과 의미상 중복을 피하면서
또한 보다 명확하게 juice에서 object로 수정해보았습니다!^^😌

2021-03-10 03:39 UTC, DragonTigerXYZ commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func plusFruitStock(fruit: Fruit, addStock: Int) {
addstock, revertstock의 파라미터 naming이 Int를 의미한다기엔 좀 모호함이 있는거 같네요!
파라미터 자료형의 특성을 보다 잘 나타낼 수 있게끔 파라미터명을 number로 수정하였습니다.
또한 함수명도 plusNumberToStock / minusNumberToStock으로 바꾸어 보았습니다🙃

2021-03-10 03:42 UTC, DragonTigerXYZ commented on JuiceMaker/JuiceMaker/Type/Fruit.swift
> +    var stock: Int = 10
private(set)으로 수정하였습니다.

2021-03-10 03:42 UTC, DragonTigerXYZ commented on JuiceMaker/JuiceMaker/ViewController.swift
> +//        print("현재 바나나 재고량 : \(testJuiceMaker.readFruitStock(fruit: banana))")
주석제거 하였습니다.😅😅😅

2021-03-10 03:53 UTC, DragonTigerXYZ commented on JuiceMaker/JuiceMaker/Type/Juice.swift
> +    init(require: [(Fruit, Int)]) {
쥬스 레시피를 초기 설정하는 의미에서
require -> setRecipe 로 파라미터명을 수정해보았습니다!🙃

2021-03-10 18:32 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func readFruitStock(fruit: Fruit) -> Int {
!! return, get 같은 반환을 의미하는 단어를 넣기 보다는 명사형 함수로 바꿔보는건 어떨까요? return은 피하는게 좋습니다 😭

2021-03-10 18:33 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                print("\(fruit)의 재고량 부족")
message 변수라는 것을 여기서 반환해주는게 적절할까요? 이 메세지도 어디선가 관리하는게 좋지 않을까요?

2021-03-10 18:34 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeFruitJuice(juice: Juice) {
object는 juice를 추상적으로 의미하는 것 같아서 아쉽네요! 함수, 파라미터명을 작성하고 실제 사용할 때 어떻게 읽히는지 고려해보면 조금 더 좋은 네이밍을 할 수 있습니다!
파라미터 생략할 수 있는 방법도 힌트입니다 😎

2021-03-10 18:49 UTC, corykim0829 requested changes
수고하셨습니다!!

이전 리뷰를 컨벤션 위주로 했었는데, 이번에도 컨벤션 관련 리뷰가 많네요 😅
여러분이 작성한 코드에 대해서 바로바로 리뷰를 해드리지만, 꼭 바로 수정할 필요는 없습니다. 이렇게 말씀 드린 이유는 전체적인 로직이 수정되면 리뷰해드린 코드가 사라지거나 바뀔 수 있기 때문에 그렇습니다!
처음부터 완벽할 수 없으니 로직이 계속 바뀌어지는건 당연하다고 생각이 듭니다! 그러니 코드가 바뀌는 거에 두려워하지 않으셨으면 합니다 👀

힌트를 좀 드리자면, 타입으로 정할 것은 확실하게 타입으로 구현하여 사용하고 로직으로 처리할 부분은 로직으로 처리하는 것입니다. 이건 SOLID에 S와 관련이 있는데, 어렵지 않으니 한번 읽어보시면 좋을 것 같습니다.

객체(Struct, Class)의 역할들이 모호해지지 않고 자기 일만 하도록 구현하라는 의미입니다!

2021-03-10 18:49 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                messege = "\(object) 쥬스 나왔습니다! 맛있게 드세요!"
여기에서 object로 전달되면 정상적으로 출력이 되나요?

2021-03-10 18:49 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeFruitJuice(object: Juice) -> String {
함수명만 보면 쥬스를 만드는 것 같은데 String인 메세지를 반환하는게 부자연스럽네요!
전체적인 플로우를 한번 더 고려해보면서 수정해보세요!

2021-03-12 03:51 UTC, DragonTigerXYZ commented
@corykim0829

안녕하세요 Cory! Step1 리뷰 이후 설계를 다시 진행하여, 작성해보았습니다.🙃

### 코드를 작성할 때 고민 & 조언을 얻고 싶은 부분
- 에러메시지를 enum으로 선언할지, 각각의 메서드에서 생성할지 고민이 되었습니다. step1에서는 사용빈도가 적어서 삭제후 메서드별로 작성하는게 좋을거같은데, Step2~3를 고려하면 현재의 코드를 유지하는게 좋을 거같은데, Cory의 의견을 받고싶습니다.
- 불필요한 Fruit 종류 열거형 선언 대신, 배열에 해당하는 인덱스별 과일종류를 주석으로 남겼습니다. 
- 프로그램 실행 순서에 따라 메서드의 순서를 재배치 해보았습니다.
- Naming의 경우 명사형 단어조합을 하되, 메서드명과 매개변수명 사이의 중복을 피하고, 명확함을 표현할수 있는 기준으로 작성하였습니다.
- 메서드의 매개변수에 와일드카드를 사용함으로써, 중복되는 매개변수명을 피해보았는데, Cory의 의견을 받고싶습니다😊

2021-03-15 05:48 UTC, corykim0829 requested changes
정말 수고 많으셨습니다!!

현재 과일들을 `Int` 배열로 관리하고 있는데, 이렇게 되면 index로 밖에 구분을 하지 못해서 따로 문서나 주석이 없으면 코드를 이해하는 것이 많이 어렵습니다 🥲

과일 객체를 만들어서 관리해보세요! 저의 힌트입니다 😃

`JuiceMaker` 객체가 전체 로직을 담당하고 있는 부분은 잘 구현하셨습니다!! 👏👏👏
과일 객체 관리 -> 재고 관리 -> 쥬스 생성 흐름을 잘 유지하면서 발전시켜보면 좋을 것 같아요!

2021-03-15 05:48 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +enum printMessege: String {
enum으로 에러 메세지를 잘 정리하셨군요!
에러를 처리할 때 Error 프로토콜을 사용하면 편리합니다!
에러 메세지는 CustomStringConvertible 프로토콜을 알아보면 좋을 것 같아요!

2021-03-15 05:48 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        var recipe: [Int: Int] = [:]
여기 recipe dictionary를 보면 key, value가 무엇을 뜻하는지 모르겠네요. 👀

2021-03-15 05:48 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    private var stocks: [Int] = [10, 10, 10, 10, 10]
인덱스로 처리하게 되면, 계속해서 여기 주석을 봐야하는 불편함이 있습니다. 코드만 보고 어떤 재료인지 판단할 수 있는 로직으로 바꾸면 좋을 것 같아요!

2021-03-15 05:48 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    case unknownError = "알 수 없는 에러입니다."
알수 없는 에러는 없어도 될 것 같네요. 에러는 발생할 때만 처리하는 흐름으로 가면 좋을 것 같네요!

2021-03-15 05:48 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func isCheckStock(_ juiceName: Juice) -> Bool {
is + Check 동사가 중복되어서 어색하네요!

2021-03-15 05:48 UTC, corykim0829 commented on README.md
> +<<<<<<< HEAD
머지 하면서 이슈가 있었나 보네요 README도 한번 정리하면 깔끔할 것 같아요 ㅎ

2021-03-15 15:46 UTC, corykim0829 commented
> 메서드의 매개변수에 와일드카드를 사용함으로써, 중복되는 매개변수명을 피해보았는데, Cory의 의견을 받고싶습니다😊
와일드카드가 어떤 걸 의미하는건가요? 👀

2021-03-16 06:29 UTC, DragonTigerXYZ commented
@corykim0829 
## 안녕하세요 Cory! Step1 리뷰 이후 설계를 다시 진행하여, 작성해보았습니다.🙃
코드를 작성할 때 고민 & 조언을 얻고 싶은 부분

- enum의 에러메시지는  완성, 에러, 재고수정을 모두 통칭 할수 있는 "StatusMessage"로 네이밍 변경 하였습니다.

- class Fruit를 분리시켰고, class FruitStok는 Fruit를 통해 각 과일별 재고를 관리하는 타입으로 정의했습니다.

- class Juice 타입에서, 쥬스레시피 타입을 정의해주었습니다. typealias(별칭)을 NeedStock으로 지정해주었고, 배열의 튜플을 사용함으로써, 이전 코드의 recipe dictionary의 (key,value)가 의미하는 바를 보다 명확하게 표현해보았습니다.

- class JuiceRecipe 타입은 Juice타입으로부터 각각의 쥬스의 인스턴스를 생성해보았습니다.

- class JuiceMaker 타입은 싱글톤패턴의 FruitStock과 JuiceRecipe을 통해 재고를 관리하고, 레시피와 실재 재고량의 상태에 따라 쥬스를 만드는 역할을 합니다. 또한 여러개의 과일을 사용하는 레시피의 경우 각 과일 별 재고 상태에 따라 레시피 조건 충족 유무가 달라져서 때문에 전체 레시피의 조건을 검사하는 메소드를 만들었습니다. 마지막으로 쥬스를 만들고 난 뒤 결과에 따른 Step2, 3 얼럿 표시와 화면 이동을 위해 enum 타입의 StatusMessage가 결과값으로 반환되게 처리하였습니다.

- 추가로 메서드, 프로퍼티의 네이밍은 각각의 타입을 고려하여, 고심하여 지었지만, 매번 Naming과정은 너무 힘듭니다. 😂😂😂 코멘트를 통해 깨닫기보다 관련된 내용의 책 혹은 자료를 한번 보고싶은데, 추천해주실 만한게 있을까요?

2021-03-17 07:03 UTC, corykim0829 approved these changes
수고 정말정말 많으셨습니다!! 
👏👏👏👏👏

해드린 피드백은 step2 진행하면서 반영해보세요!!

2021-03-17 07:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func orderMakeJuice(targetJuice: ObjectIdentifier) -> ErrorMessage {
`func make(juice: ~)` 이런식으로 바꾸면 깔끔할 것 같아요!

2021-03-17 07:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeJuice(_ targetJuice: ObjectIdentifier) {
makeJuice 안에 또 makeJuice가 실행되는게 어색하네요 이 함수명은 그냥 재고를 줄인다는 의미로 표현해보는건 어떨까요?

2021-03-17 07:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        if juiceRecipes.canMake(targetJuice, fruitStocks) {
함수명이 의미전달이 잘돼서 좋네요! 👍

2021-03-17 07:03 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        return resultMessage
if else 에서 각각 return 처리해주면 더 깔끔할 것 같아요 👀

2021-03-17 07:04 UTC, merged