[STEP1] Bobby, SJ
yagom-academy/ios-juice-maker pull request #41
Opened 2021-03-09 09:28 UTC by SoKoooool

@corykim0829 

### 고민했던 점, 조언을 얻고 싶은 점
STEP1의 기능설명서를 참고하여 코딩을 하려고 했는데
STEP2로 넘어가면 코드의 내용들을 많이 수정해야할것 같았습니다
STEP의 범위가 혼동되어 코드가 지저분해진것 같습니다😭

- 과일 재고를 담을 타입을 클래스로 할지, 열거형으로 할지 아니면 더 좋은 방법이 있는지,
- 그리고 과일과 같은 데이터를 정의할때 어떠한 방법으로 선언하면 좋을지 조언 부탁드립니다
- 이외에도 다른 부족한점 있으면 리뷰 부탁드려요

2021-03-09 10:07 UTC, corykim0829 requested changes
👏 수고 많으셨습니다!! 깔끔하게 구현 잘하셨습니다.

⚡️ 일단은 함수 네이밍, 접근제어자 중심으로 리뷰를 해드렸습니다! 이 부분 먼저 수정하고 로직을 수정하면 좋을 것 같아요!

🦄 git 관련하여 리뷰를 해드리자면, 현재 커밋을 보면 어떤 작업을 했는지 명확하게 판단하기가 힘드네요 🥲
커밋 컨벤션을 만들어서 이에 맞게 커밋해주시고, 더 잘게! 커밋을 해주시면 좋을 것 같네요!

🚗 로직에 관한 리뷰를 해드리자면, 다음 step들도 읽어보시고 코드를 작성하는게 좋을 것 같습니다!
현재 step1만 보면 잘 구현하셨지만, 이제 iOS 앱 프로젝트이니 조금 더 고려할 부분이 있을거에요. 
버튼을 눌렀을 때 어떻게 처리할 것인가, 재고가 부족하면 어떻게 처리할 것인가 등 많은 경우에 수를 생각하면서 로직을 짜면 좋을 것 같아요!

2021-03-09 10:10 UTC, corykim0829 commented
커밋 분리

> @corykim0829
> 
> ### 고민했던 점, 조언을 얻고 싶은 점
> STEP1의 기능설명서를 참고하여 코딩을 하려고 했는데
> STEP2로 넘어가면 코드의 내용들을 많이 수정해야할것 같았습니다
> STEP의 범위가 혼동되어 코드가 지저분해진것 같습니다😭

커멘트에도 해드렸는데 다음 스텝까지 고려해서 코드를 작성하세요! 너무 하나의 step만 충족하려고 하면 매 스텝마다 수정하는 부분이 많아져서 비용이 클 것 같아요!

> 
> * 과일 재고를 담을 타입을 클래스로 할지, 열거형으로 할지 아니면 더 좋은 방법이 있는지

➡️ 과일 타입을 더 탄탄하게 구현하면 좋을 것 같아요! 과일 재고 관리는 결국에는 컬렉션으로 하면 되니까요
추상화도 고려해보면 좋을 것 같네요!

> * 그리고 과일과 같은 데이터를 정의할때 어떠한 방법으로 선언하면 좋을지 조언 부탁드립니다

➡️ class, struct에서 고민해보시고, 처리하기 쉬운 방법을 고려하면 좋습니다. 과일 같은 데이터는 정말 데이터만 저장하도록 구현하고, 로직은 다른 객체가 처리하게 하도록 하는게 좋아요!

2021-03-11 14:49 UTC, Babywalnut commented
## step1-2
@corykim0829 

* 기본적으로 타입내에 정의된 프로퍼티들은 선언된 범위밖에서 접근하기에 private(set)을 통하여 읽기 전용으로 선언하였습니다.

* Fruit class는 아래의 typealias ingredient 가 immutable이므로 fruit을 struct로 선언했을때 해당 메서드는 mutating을 선언해줘야합니다. 하지만 ingredint 에서 mutating 메서드를 호출하려하면 에러가 발생하여 class로 선언해주었습니다.

* 과일들의 데이터를 어디에 담지 않고 파일 내부에 그냥 선언해주었는데 리뷰부탁드립니다.

2021-03-11 16:39 UTC, corykim0829 requested changes
수고 많으셨습니다! 👏👏👏👏

변수, 함수 네이밍은 연습이 많이 필요한 부분이니 너무 지치지 마시고 계속 수정해보시면 좋을 것 같습니다! 💪

지금 하나의 파일안에 모든 코드를 구현하셨는데, 객체마다 파일을 ✌️분리✌️하여 구현해주세요! 왜 분리하여서 구현하는지 답변으로 말해주세요 ☺️

⚡️⚡️이 부분 꼭 읽어주세요!⚡️⚡️
지금 너무 JuiceMaker를 만드는 것에 집중해서 로직이 어색한 것 같아요. 제가 이번에 해드린 리뷰는 나중에 반영해도 좋으니 우선적으로 다음을 고려해서 고쳐보세요!

0️⃣ 파일 분리! (위에서 언급한 내용이에요!)
1️⃣ Fruit 데이터를 어떻게 생성해서 어떻게 저장할 것인가? -> 현재는 Fruit 클래스의 인스턴스가 모든 과일을 다 처리하고 있어요. `var strawberry = Fruit(name: "딸기", amount: 10)` 이 친구요! `strawberry` 인스턴스가 개수까지 다 처리하니까 이 친구는 딸기를 나타내는 인스턴스라기 보다는 딸기 개수까지 관리하는 객체네요. 이 객체의 역할이 모호해요.
2️⃣ 과일쥬스를 주문하는 입장에서 로직을 작성해봅시다! 지금은 생성하는데 집중되어있는데, 결국에는 주문하기 버튼을 눌러야 작동이 되는 로직이 필요하기 때문이죠!
3️⃣ 마지막으로 enum 지양하기입니다. enum이 많아지면 유지보수에 어려움이 큽니다. 사용하지 않으려고 노력해보세요! (이전 묵찌빠는 3개로 정해져있어서 사용하기 적합했어요!)

이것들을 고려해서 먼저 로직을 개선해보고 그 후에 제가 해드린 리뷰들을 반영해보세요 😀

조금만 더 힘내봅시다! 💪

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    private(set) var fruitAmount: Int
fruit 객체안에 fruitName, fruitAmount 프로퍼티 이름에 중복되는 건 제거해도 될 것 같습니다!

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    init(name: String,amount: Int) {
```suggestion
    init(name: String, amount: Int) {
```
띄어쓰기 주의!

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addfruit() {
camel case 지켜주세요! 🐫

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        self.fruitAmount += 1
아래 함수에서는 여러 과일을 줄일 수 있는데, 여기에서는 하나씩만 추가할 수 밖에 없나요?

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func addfruit() {
여기도 위에 변수처럼 fruit이 중복되네요 👀

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +typealias ingredient = (fruit: Fruit, amount: Int)
typealias를 잘 사용하셨네요!
튜플을 사용한 이유가 있을까요?

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
indent가 어긋나네요 👀

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +let failureMessage: String = "재고가 부족합니다."
상수화로 잘 처리하셨네요!
타입이 확실하면 명시하지 않으셔도 됩니다 😀

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    private(set) var Ingredients: [ingredient]
변수가 대문자로 시작하네요..! 🙊

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func madeFruitsJuice(name: FruitsJuice) -> String {
함수명을 보면 FruitsJuice를 반환할 것 같은데, String을 반환하네요? 👀
함수에 사용되는 동사는 현재시제로 사용하는게 자연스럽습니다!

2021-03-11 16:39 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            if checkFruitStock(of: .strawberryJuice) {
모든 케이스에서 인자에 들어가는 값만 다른데, 추상화하여 처리할 수는 없을까요?

2021-03-11 16:41 UTC, corykim0829 requested changes

2021-03-11 16:41 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    private(set) var fruitAmount: Int
private(set) 잘 사용하셨습니다 👍

2021-03-11 16:47 UTC, corykim0829 commented
> * Fruit class는 아래의 typealias ingredient 가 immutable이므로 fruit을 struct로 선언했을때 해당 메서드는 mutating을 선언해줘야합니다. 하지만 ingredint 에서 mutating 메서드를 호출하려하면 에러가 발생하여 class로 선언해주었습니다.

➡️ mutating의 의미가 무엇인가요? 👀
➡️ mutating과 관련하여 class와 struct의 특성 차이를 알아보면 좋을 것 같아요.

> * 과일들의 데이터를 어디에 담지 않고 파일 내부에 그냥 선언해주었는데 리뷰부탁드립니다.

➡️ 전역변수로 취급되기 때문에 좋지 않습니다. 🥲 하나의 객체가 이를 관리하면 좋을 것 같아요!

제가 리뷰 해드린 곳에 커멘트를 남겨서 대화를 이어나가는 것도 좋을 것 같아요 🙌

2021-03-13 13:57 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    private(set) var fruitAmount: Int
넵 name과 amount로 수정하겠습니다!

2021-03-13 14:01 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        self.fruitAmount += 1
기능 명세서를 보고 개수를 내리는 reduceFruit함수의 경우는 재고에서 1씩 내리는 경우와 쥬스 생성시 소진할 때 모두 사용할 수 있도록 감소시킬 개수를 파라미터로 받게 해놨습니다. 개수를 올릴 경우의 수는 1개씩 올리는 경우밖에 없어서 1로 지정해놨습니다! 다른 기능을 추가를 고려한다면 재고 추가 또한 똑같이 파라미터로 개수를 전달받는것이 좋을까요?

2021-03-13 14:06 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +typealias ingredient = (fruit: Fruit, amount: Int)
쥬스의 레피시를 ingredient로 정의해주기위하여 fruit(재료) 와 amount(해당 과일의 소모 개수)를 사용할 수 있도록 튜플을 사용하였습니다. 딕셔너리를 사용하면 그 의미를 파악하기 쉬울거라 생각했지만 ingredint의 fruit인스턴스 프로퍼티 amount(현재 제고)와 ingredient의 amount(제조시 과일의 소요개수)를 직접적인 비교하여 쥬스제조가능여부를 파악하고자 튜플을 사용했습니다.

2021-03-13 14:07 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
수정하겠습니다!

2021-03-17 08:30 UTC, Babywalnut commented
## Step1-3
@corykim0829 

* 코드를 Fruit, FruitStorage, Juice, JuiceMaker로 각각의 타입의 상속관계, 역할을 고려하여 나눴습니다.

* ObjectIdentifier로 Fruit타입을 상속받은 각각의 과일을 식별하였고 , 쥬스도 마찬가지로 구현하였습니다.

* 소모된 개수가 반영되지 않는 오류를 Optional binding 후 개수를 수정 후 다시 원래의 Dictionary Value에 값을 수정된 복사해줌으로써 해결하였습니다.

* JuiceRecipe 타입의 역할이 애매하고 어색하다하여 Juice타입을 상속받은 각각의 쥬스와 요구 레시피를 typealias를 통해 새로운 Dictionary로 생성해서 한번에 관리해주었습니다.

리뷰 부탁드립니다🙈🙏

2021-03-17 09:43 UTC, corykim0829 approved these changes
수고 정말 많으셨습니다👏👏👏👏👏

step2 바로 진행하시구요! 리뷰해드린 내용은 step2 하면서 반영하시면 좋을 것 같습니다.
step2 하면서 로직도 유연하게 변경하셔도 됩니다 ⚡️

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +    func addFruit(fruit: ObjectIdentifier, amount: Int) {
fruit이 중복되네요!
addFruit(_ fruit: ObjectIdentifier, amount: Int) 로 바꾸면 좋을 것 같아요

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +                                                , ObjectIdentifier(Mango.self): 10]
이 부분 엔터를 사용하여 정리하면 좋을 것 같습니다!

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +    func addFruit(fruit: ObjectIdentifier, amount: Int) {
fruit 파라미터에 다른 ObjectIdentifier가 들어와도 괜찮나요?

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +        if var fruitAvailable = self.fruitsStock[fruit] {
fruitAvailable 변수명이 어색하네요.. 현재 사용가능한 과일을 뜻하는건가요?

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +            fruitAvailable += amount
이 부분 때문에 if let이 아닌 if var를 사용하신 것 같은데, if let을 사용하여 두 값을 더하여 처리하는건 어떤가요?

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +            self.fruitsStock[fruit] = self.fruitsStock[fruit]
이 부분은 의미가 없는 코드 같네요 👀

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Juice.swift
> +typealias Recipe = (stock: ObjectIdentifier , requiredAmount : Int)
띄어쓰기 컨벤션을 맞춰주세요! 👀

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Juice.swift
> +    var recipe: [Recipe]
이 프로퍼티는 값이 변경되나요? 접근제한자도 고려해주세요!

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeJuice(juice: ObjectIdentifier) {
- 함수명과 파라미터에서 juice가 겹치네요!
- 여기도 다른 ObjectIdentifier가 들어와도 괜찮나요??

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        if let juiceRequirements = recipes[juice] {
juiceRequirements 의미가 잘 와닿지 않네요 재료들이라고 표현해도 괜찮지 않을까요?

2021-03-17 09:43 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    private func checkFruitStock(juice: ObjectIdentifier) -> Bool {
checkFruitStock 라고 하면 반환값이 없을 것 같아요
has ~~ can~~ 이런 조동사를 이용한 네이밍도 있어요! 참고하세요 ㅎ

2021-03-17 09:45 UTC, merged

2021-03-17 14:57 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +    func addFruit(fruit: ObjectIdentifier, amount: Int) {
> fruit 파라미터에 다른 ObjectIdentifier가 들어와도 괜찮나요?

혹시 다른 ObjectIdentifier가 들어와도 괜찮냐고 물어보신 리뷰는
파리미터명을 변경해보라는 말씀이신지 아니면 ObjectIdentifier도 식별할 수 있는게 있는지 궁금합니다

2021-03-17 14:59 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +                                                , ObjectIdentifier(Mango.self): 10]
넵 private(set)을 늦게 추가하다가 어긋난거 같습니다 수정하겠습니다!

2021-03-17 15:01 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +    func addFruit(fruit: ObjectIdentifier, amount: Int) {
파라미터는 타입으로 받고 그 타입으로 ObjectIdentifier를 만들어서 처리하는 게 좋을 것 같아서요!
파라미터를 제한할 수 있어서 더 좋을 것 같습니다 ㅎ

2021-03-17 15:17 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +            fruitAvailable += amount
> 이 부분 때문에 if let이 아닌 if var를 사용하신 것 같은데, if let을 사용하여 두 값을 더하여 처리하는건 어떤가요?

        if let fruitAvailable = self.fruitsStock[fruit] {
            self.fruitsStock[fruit] = fruitAvailable + amount
        } 
와 같은 형식으로 수정하겠습니다!

2021-03-17 15:20 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +        if var fruitAvailable = self.fruitsStock[fruit] {
창고에남아있는과일이라고 명확하게 나타낼 수 있도록 수정하겠습니다.

2021-03-17 15:52 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +    func addFruit(fruit: ObjectIdentifier, amount: Int) {
> 파라미터는 타입으로 받고 그 타입으로 ObjectIdentifier를 만들어서 처리하는 게 좋을 것 같아서요!
> 파라미터를 제한할 수 있어서 더 좋을 것 같습니다 ㅎ

func addFruit(_ fruit: stock.Key, amount: Int) {
와 같이 수정하겠습니다

2021-03-17 15:53 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/Juice.swift
> +    var recipe: [Recipe]
let으로 수정하고 private으로 접근제한자를 주겠습니다!

2021-03-17 16:01 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    private func checkFruitStock(juice: ObjectIdentifier) -> Bool {
hasEnoughFruitStock으로 수정해보겠습니다