[Step1] CODA, Summer
yagom-academy/ios-juice-maker pull request #42
Opened 2021-03-10 02:27 UTC by dacodaco

### 코드를 작성할 때 고민했던 점 
1. Enum 선언 어떻게 해줄지 고민하였음 
2. 읽기 전용으로 접근제어자를 어떻게 선언해야하는지 고민하였음
3. 별도의 변수 없이 inout parameter를 활용해 함수 내에서 변경된 값을 전달하는 방법을 고민하였음
4. 재고체크 활용 방법에 대해서 고민하였음. (아직도 고민 중)

### 해결되지 않은 점 / 조언 얻고 싶은 점
1. 재고를 체크하고, 주스를 제조하는 과정을 조금 더 깔끔하게 구현하고 싶었는데, manufactureJuice 메서드를 보시면 아시겠지만, switch의 case마다 if 문을 주렁주렁 달아놓아서 CODA와 Summer 둘 다 굉장히 열받은 상태입니다. 문제는 어떻게 해결해야될지에 대해서 감을 잡지 못하고 있습니다....
이게 하나의 주스가 하나의 과일만 사용한다면 어떻게 할 수 있을 것 같은데;;;; 딸바랑 망키(ㅋㅋ)가 자꾸 머리를 괴롭힙니다. 살려주세요..🔥🤷‍♀️🔥🌋🔥🤯🔥🤯🔥🤯🔥🤯🔥

🔥구원자 소환🔥
@O-O-wl

2021-03-11 00:48 UTC, O-O-wl requested changes
고생하셧어요 
Coda Summer
다양한 문법을 공부해보시고 적용하시는 중이신 것 같아요 
더 불어 이 문법들은 어떤 상황에 사용되어야 할까도 같이 고민되면 좋을 것 같아서 코멘트 남겨두었습니다 
이모지 원래 많이 쓰는데 맥북이 이상해서 잘 안되네요 ... :(

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +class JuiceMaker: FruitStock {
혹시 상속으로 구현하신 이유가 있을까요?

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +let currentFruitStock = FruitStock()
이 인스턴스는 어디서 사용되나요?

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +    fileprivate(set) var mango: Int = 10
접근제한자에 대해공부해보신 흔적이 있는 것 같아요
readOnly인 접근제한자는 private(set)으로 해도될 것 같아요 혹시 fileprivate(set) 으로 구현하신 이유가 있을까요
- private 
- private(set)
- fileprivate
- fileprivate(set)
- internal
- public
- open
앞으로 자주 접하게될 접근제한자들인테 한번 공부해보고 정리해봐도 좋을 것 같아요
[Swift Docs Access Control](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html)

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +    func addAmount(of: inout Int, as much: Int) {
메소드 레이블링도 가능하답니다

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +    func addAmount(of: inout Int, as much: Int) {
inout 키워드를 사용하신 이유가 궁금해요
밖에서 넣은 값에 더하는 건가요?
`+` 연산자와 어떤 게 다른 걸까요?
JuiceMaker 라는 클래스가 숫자를 더해서 반환해주는 메소드를 구현해야하나요?

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +            subtractAmount(of: &pineapple, as: 2)
과일들은 내부 프로퍼티로 지니고 있는 것들인데
그걸 다시 메소드에 넣어야하나요?

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +            if canMakeJuice(amount: strawberry, subtract: 16) == true {
if (condition) condition 이 true 라면 아래의 스코프가 실행될 거에요
== true 는 생략가능할 것 같습니다

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +            if canMakeJuice(amount: strawberry, subtract: 16) == true {
혹시나 해서 `case .strawberryJuice   where canMakeJuice...`와 같은 문법도 있답니다

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +                return
return은 명시해주시지 않아도 되요

2021-03-11 00:48 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +        checkFruitStock()
이 3개의 메소드가 외부가 아닌 내부에서만 호출되는 메소드로 보여요
private 접근제한자로 개선할 수 있는 여지가 있는 것 같아요

2021-03-15 05:08 UTC, dacodaco commented on JuiceMaker/JuiceMaker/main.swift
> +class JuiceMaker: FruitStock {
처음에는 단순히 과일 재고를 별개의 클래스에서 받아오기보단,
하나의 클래스의 부모 클래스로 두고, 상속을 받아오면 편리하게 사용할 수 있겠다는 생각에서 상속을 했어요.

그런데 생각해보니 클래스 간의 간섭을 최소화 하기 위해서라도 분리하는 것이 좋다고 생각하였고, 분리해보고 있는 중입니다 :)

2021-03-15 06:02 UTC, dacodaco commented on JuiceMaker/JuiceMaker/main.swift
> +    func addAmount(of: inout Int, as much: Int) {
저희는 메서드 바깥에 있는 과일의 재고를 변경하려고 해서, 파라미터 값으로 불러오는 값을 변경해 다시 재고 값으로 돌려주기 위해 inout 파라미터를 활용해 보았어요. 
+ 연산자를 활용하는 것보다 inout 파라미터를 활용하는 것이 ‘어떤 과일’에 ‘얼마만큼’추가할 것인지를 범용적으로 사용할 수 있을 것이라고 판단했습니다! 혹시 inout 키워드를 사용했을 때 어떤 불리한 점이 있을까요?!!

2021-03-15 06:06 UTC, dacodaco commented on JuiceMaker/JuiceMaker/main.swift
> +            subtractAmount(of: &pineapple, as: 2)
(지금은 별도의 타입으로 만들어주었지만) 혹시 내부 프로퍼티로 지니고 있는 값을 메소드로 넣으면 안되는 이유가 무엇인지 알 수 있을까요..? ㅜㅜ 붱이님이 생각하시기에 위의 경우 메소드에 넣지 않고서 어떻게 subtract를 구현하는게 좋을지 궁금합니다..!! 가능하다면 디스코드로 설명을 들어보고 싶은데 가능할까요?!!

2021-03-15 07:06 UTC, dacodaco commented on JuiceMaker/JuiceMaker/main.swift
> +let currentFruitStock = FruitStock()
사용을 하지 않고 있는 인스턴스였어요. 처음에 코드 작성시 활용해야겠다고 생각하고 진행했는데 미처 지우지 못했어요.. ㅜㅜ

2021-03-15 09:03 UTC, dacodaco commented on JuiceMaker/JuiceMaker/main.swift
> +    func addAmount(of: inout Int, as much: Int) {
메소드 레이블링이 argument label을 설정하는 것을 의미하는 것일까요...?
method labeling 이라고 검색해도 안나오는데 혹시 알려주실 수 있나요?!

2021-03-15 09:06 UTC, dacodaco commented on JuiceMaker/JuiceMaker/main.swift
> +            if canMakeJuice(amount: strawberry, subtract: 16) == true {
와우!!! 바로 적용해서 코드 작성해 보았습니다 :):) 코드가 한결 단순해진 것 같아서 기분이 좋아요:)
where를 통해서 특정한 조건을 추가해줄 수 있다는 점을 확실하게 알았습니다!!

2021-03-15 09:12 UTC, dacodaco commented on JuiceMaker/JuiceMaker/main.swift
> +        checkFruitStock()
궁금한 점이 하나 있어요! 
외부가 아닌 내부에서만 호출되는 메소드의 경우 private 접근 제한자를 해주는 것이 좋은 이유는 무엇인가요?

2021-03-15 13:34 UTC, summer0817 commented on JuiceMaker/JuiceMaker/main.swift
> +        checkFruitStock()
3개의 메소드가 내부에서만 호출되는 메소드이므로 각각의 메소드를 찾아 메소드명 앞에 private접근제한자를 붙여 수정하였습니다.
private checkFruitStock()
private manufactureJuice()
저도 외부가 아닌 내부에서만 호출되는 메소드의 경우 private 접근 제한자를 해주는 것이 좋은 이유가 궁금합니다. 🤔

2021-03-15 13:47 UTC, summer0817 commented
@O-O-wl 
리뷰 확인 후 코드 수정하였습니다. 확인 부탁드립니다!🙏

2021-03-17 00:31 UTC, O-O-wl approved these changes

2021-03-17 00:31 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +    private func manufactureJuice(of: FruitJuice) {
manufacture '제조하다'라는 뜻은 보통 기계를 통해서 제조하는 걸 의미할 것 같아요

2021-03-17 00:31 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +            subtractAmount(&fruitStock.kiwi, as: 1)
레이블 아규먼트가 있으니 
recipeOf(juice: ~) 로 해도 되지 않을까요?

2021-03-17 00:31 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
>      func recipeOfJuice(juice: FruitJuice) {
외부에서 알아야할 메소드는 start() 하나이고 그러면 JuiceMaker가 로직들을 수행하는 것 같아요 
이 메소드도 private이 될 수 있지 않을까요

2021-03-17 00:31 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
>          }
이 메소드를` return amount >= subtract ` 한줄로도 처리 가능할 수 있겠네요

2021-03-17 00:33 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +    fileprivate(set) var mango: Int = 10
JuiceMaker.swift 파일을 만들어두셨던데 
파일을 나누어보는 것 도 좋을 것 같아요

2021-03-17 00:35 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +        checkFruitStock()
캡슐화를 해두었다면 
외부에서 알아야할 최소한의 인터페이스만 열어두는 게, 관심사의 분리가 이루어지는 것 같아요
여러분이 사용하는 아이폰이나 등 기기들이 사용자가 접근할 수 있는 몇몇가지들로 제한을 해둘 거에요, 그 복잡한 기기를 단순하게 사용할 수 있을것이구요

오히려 반대로 외부에서 사용되지 않는 메소드를 열어두어야할 이유가 있을까요?

2021-03-17 00:36 UTC, O-O-wl commented
코멘트 몇개 남겨두었습니다~ STEP2 진행하시면서 
한번 더 이야기해보아요 ㅎ ㅡㅎ 
머지하겠습니다!

2021-03-17 00:37 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +class JuiceMaker: FruitStock {
만약 이전의 상속이었다면 extension과 유사하게 사용하신 것 아닐까요?

2021-03-17 00:39 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +    func addAmount(of: inout Int, as much: Int) {
input과 output의 명확함이 있으면 테스트하기도 좋을 것 같아요
현재는 input으로 넣은 기존 값의 변화를 체크해야할거에요. 
input을 통해서 output을 얻어오는 방법을 통해서 구현한다면 어떤 값이 집중해야하는 지 인지할 수 있지 않을까요?

2021-03-17 00:41 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/main.swift
> +            subtractAmount(of: &pineapple, as: 2)
넣으면 안되는 건 아니에요 
의도가 궁금했습니다.
내부 프로퍼티로 객체의 state 를 표현하고, 메소드를 통해서 객체의 behavior를 표현하셨을 것 같아요
내부에서 접근가능한 state를 다시 인자로 전달하는 방식을 넣는 선택을 하신 이유가 궁금했어요

2021-03-17 00:41 UTC, merged

2021-03-17 03:28 UTC, dacodaco commented on JuiceMaker/MyPlayground.playground/Contents.swift
> +}
아! 프로토타이핑을 좀 해보려고 플레이그라운드 파일을 만들어두었어요..!!
이건 inout 파라미터를 활용해보려고 연습한 코드였는데, 미처 못지우고 함께 PR을 보냈어요.. ㅜㅜ