[STEP1] - Hailey, Kio
yagom-academy/ios-juice-maker pull request #43
Opened 2021-03-11 07:31 UTC by Kioding

@delmaSong 
안녕하세요! Hailey, Kio입니다.
delma 잘 부탁드립니다 ☺️

## 코드를 작성할 때 고민했던 점
- Type을 어떤 걸로 해야할지 고민
- 팀 프로젝트를 어떻게 하면 효율적으로 할 수 있을지 😭
- 재고관리를 어떻게 해줘야 할지

## 해결되지 않은 점 / 조언 얻고 싶은 점
**JuiceMaker.swift()** 
- JuiceMaker Type을 다른 타입으로부터 상속받거나 자신을 상속할 필요가 없다고 생각해서 구조체를 사용해봤는데 적절하게 잘 사용한건지 궁금해요!
- Struct JuiceMaker의 fruits 변수명을 적절하게 지은건지 궁금합니다.
- 19~26 line에서 If let 옵셔널 바인딩 할때 꼭 else문이 있는 게 좋을지 궁금합니다.

**Git**
- git pull을 했는데 새로 추가한 file이 터미널에는 있지만 Xcode상에 보이지 않고 추가하려고 하면 이미 존재하는 파일이라고 나옵니다. 임시방편으로 다른 이름의 file을 생성하여 복사하였는데 Xcode의 문제일지 궁금합니다 😭
- 저희가 코드를 짤때 타입을 하나씩 완벽히 짜지 못하고 계속 오류가 나서 커밋을 중간중간 하지 못했는데 이럴때 다 짜지 못했더라도 커밋을 하는게 나은건 지 궁금합니다! 그리고 지금은 코드를 다 짜고나서야 커밋을 나눠서 하게 되었는데 이때도 커밋을 함수나 파일 별로 나눠서 하는게 나은지 아님 그냥 다 짠 코드를 한번에 올리는게 나은건 지 궁금해요!

2021-03-11 15:01 UTC, delmaSong requested changes
Hailey, Kio 안녕하세요 😃 uml부터 고민하시더니 꽤 역할이 잘 나뉘어진 것 같습니다 👏🏼
수고하셨습니다 ㅎㅎㅎ

`조언을 얻고 싶다고 하신 점`
> JuiceMaker Type을 다른 타입으로부터 상속받거나 자신을 상속할 필요가 없다고 생각해서 구조체를 사용해봤는데 적절하게 잘 사용한건지 궁금해요!

공부하셨겠지만 복습할 겸 구조체와 클래스의 차이점에 대해 설명해주실 수 있을까요😀? 

> Struct JuiceMaker의 fruits 변수명을 적절하게 지은건지 궁금합니다.

변수명에 대한 코멘트는 아래를 확인해주세요!

> 19~26 line에서 If let 옵셔널 바인딩 할때 꼭 else문이 있는 게 좋을지 궁금합니다.

옵셔널 바인딩이 제대로 안 되어있는 경우에 어떤 처리를 해주기 위해서는 else문이 있어야 하지 않을까요? 옵셔널 해제가 제대로 되지 않아도 상관이 없는 값이라면 스킵 할 수 있을 것 같은데, 그런 경우가 아니라면 있어야 할 것 같습니다

> git pull을 했는데 새로 추가한 file이 터미널에는 있지만 Xcode상에 보이지 않고 추가하려고 하면 이미 존재하는 파일이라고 나옵니다. 임시방편으로 다른 이름의 file을 생성하여 복사하였는데 Xcode의 문제일지 궁금합니다 😭

아 이게 간혹 remote와 local의 파일 hierarchy가 다르면 이런 일이 생기는 것 같더라고요. 그게 아니면 이미 동일한 이름으로 파일을 로컬에 생성했다가 지우고 나서 git pull로 땡겨올 때 이런일이 있었던 것 같아요..! 그래서 저는 아예 다른 이름으로 변경해서 싱크를 맞춰줬었다는...😂

> 저희가 코드를 짤때 타입을 하나씩 완벽히 짜지 못하고 계속 오류가 나서 커밋을 중간중간 하지 못했는데 이럴때 다 짜지 못했더라도 커밋을 하는게 나은건 지 궁금합니다! 그리고 지금은 코드를 다 짜고나서야 커밋을 나눠서 하게 되었는데 이때도 커밋을 함수나 파일 별로 나눠서 하는게 나은지 아님 그냥 다 짠 코드를 한번에 올리는게 나은건 지 궁금해요!

예를들어 1부터 10까지 짠 코드를 한번에 커밋했을 때, 문제가 생겨서 7까지만 되돌리고 싶으면 어떻게 해야할까요? 0으로 되돌아가서 8부터 10을 걷어내고 1부터 7을 살려야겠죠?.. 그런데 각각이 커밋이 되어있다면 한번에 7로 돌아가면 되니까 훨씬 편할 것 같아요 ㅎㅎ 그래서 되도록 작은 단위로 커밋을 쪼개는 것이 좋답니다
또한 커밋은 작동 가능한 경우 && 작은 기능이더라도 이름 붙일 수 있을 정도일 때 하는게 좋을 것 같습니다!
그리고 중간중간 커밋을 하지 못하고 다 작업을 한 다음 한번에 커밋을 하게 되었을 때도 가능한 의미있는 기능별로 나눠서 커밋하는 것이 위에 말한 이유때문에 좋을 것 같아요!

2021-03-12 01:18 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    }
과일을 관리할 수 있는 클래스 이름을 FruitManager로 바꿔봤습니다!😃

2021-03-12 01:32 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    }
재고가 존재한다는 뜻으로 처음에는 checkExistanceOfStock 이렇게 생각해봤는데 너무 긴 것 같아서 haveStock로 바꿨습니다!
함수명을 지을 때 간단하고 짧게 짓는게 나은지 정확한 표현을 위해 길게 지어도 괜찮은지 궁금해요!

2021-03-12 01:37 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeJuice(juice: JuiceTypes) {
makeJuice(orderedMenu: JuiceTypes)로 변경했습니다!
혹시 이미 JuiceMaker라는 구조체 안에 있는데 메서드명을 make() 이렇게만 써도 괜찮을까요?

2021-03-12 01:58 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                }
콤마를 사용하여 하나로 줄여봤습니다😆

2021-03-12 02:00 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
사용자에게 alert으로 안내해줄 수 있을 것 같아요!

2021-03-12 02:13 UTC, Kioding commented on JuiceMaker/JuiceMaker/Juice.swift
> +    func recipe() -> [FruitTypes:Int] {
앗... 확인했습니다!

2021-03-12 02:30 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        .strawberry: Fruit(.strawberry),
fruitInformation으로 바꿔보았어요🙃

2021-03-12 02:40 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        print("\(juice.name()) 나왔습니다! 맛있게 드세요!")
Bool 타입으로 반환타입을 설정해줬는데 그럼 메서드명도 수정해야될까요?😭

2021-03-12 03:13 UTC, eunseo5355 commented
@delmaSong 

delma 안녕하세요😃
코멘트 감사합니다!🙇‍♀️
조언해주신 것을 바탕으로 코드 수정해봤어요!

> 공부하셨겠지만 복습할 겸 구조체와 클래스의 차이점에 대해 설명해주실 수 있을까요😀? 

질문해주신 구조체와 클래스의 차이점을 설명해봤어요!

```
구조체는 클래스와 다르게 상속할 수 없다.
구조체는 값 타입이고, 클래스는 참조 타입이다.
여기서 값 타입은 값이 복사되어 전달되고 참조 타입은 참조(주소)가 전달된다.
따라서 인스턴스를 만들어주고 타입 밖에서 프로퍼티 값을 변경해준다면 
구조체는 구조체 안에 있는 프로퍼티 값에 변동이 없지만 클래스는 안에 프로퍼티 값이 변경된다. 
```


Step2할 때는 커밋을 되도록 작은 단위로 쪼개서 해보겠습니다!😁

2021-03-12 04:39 UTC, delmaSong approved these changes
굿굿 수고하셨습니다!🤓
구조체와 클래스를 사용하는 데에 있어서는 각각의 특징에 맞게 자신만의 기준을 세우고 사용하시면 좋을 것 같습니다! 
머지할테니 아래 사항은 스텝2에서 반영해주세요 
👏🏻👏🏻👏🏻

2021-03-12 04:39 UTC, delmaSong commented on JuiceMaker/JuiceMaker/FruitManager.swift
> +        self.stock = 10
생성시에 값을 입력받도록 하고 기본값을 10으로 하면 좀 더 유연해질 것 같아요 !

2021-03-12 04:39 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        for (fruitType, requiredAmount) in orderedMenu.recipe() {
리턴값이 Bool이려면 메소드 이름이 `음료 만들기에 성공했는가` 를 표현하는게 더 적절할 것 같아요!

2021-03-12 04:39 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    var fruitInformation: [FruitTypes: FruitManager] = [
쥬스 메이커가 과일 정보를 들고있는데
그 과일 정보에는 각각의 과일매니저가 있다..?
과일 매니저보다 다른 이름은 어떨까요? 🤔

2021-03-12 04:39 UTC, merged

2021-03-12 04:41 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    }
너무 긴 것만 아니라면 좀 길더라도 의미가 명확한 게 더 좋은 것 같아요! 잘 읽힐 수 있다면 훨씬 좋구요 ㅎㅎ
isStockExist 같은 이름을 쓸 수도 있겠네요 ㅎㅎ