[Step1] 강경, Ryan
yagom-academy/ios-juice-maker pull request #44
Opened 2021-03-11 08:40 UTC by KangKyung

@Limwin94 
Lin~~! 드디어 첫 PR을 보내게 되었습니다!!
코드 작성하면서 많은 고민을 하였어요🤔
Lin의 멋진👍🏻 생각을 듣고싶어요~~
(혹시 더 추가적인 설명이 필요하시면 DM보내주세요!)

## 고민한 점
- JuiceMaker타입을 설계할 때, struct 와 class중 어떤게 더 적합할까요?
저희는 ‘상속’을 이용하지 않는 한, struct를 사용하는게 맞다고 생각하여 타입을 struct로 만들었습니다.
리뷰어분께서 보시기에도 struct를 쓰는게 더 적합하다고 생각하시는지, 혹시 저희생각했던거 외에 이번 프로젝트에서 struct를 사용하는게 더 좋은 이유같은게 있을지 궁금하여 질문드립니다..!
(원래는 Maker라는 상위클래스를 만들어, JuiceMaker타입이 상속받아 사용할 수 있도록 만드려고 했는데, 향후 상속할 소지가 없는 JuiceMaker라는 특정한 타입을 만들면 되어서 struct로 진행하게 되었습니다.)

## 해결이 되지않은 점 & 조언을 얻고싶은 부분
- 저희는 json을 이용하여 JucieRecipe내용을 받아왔는데, 이걸 String, Int와 같이 Swift에서 기본으로 제공하는 타입이 아니라, 사용자정의타입으로 받아올 수 있는 방법이 있을까요?
- 저희는 Juice타입에서 이름을 출력하는 과정에서 이름을 name이라는 프로퍼티로 정의하여 반환하도록 하였는데, rawValue의 이름을 직접 지정해서 받아올 수 있는 방법도 있을거 같습니다. 어떤 방식이 현업에서 더 선호될지 궁금합니다..!

2021-03-12 03:02 UTC, Limwin94 requested changes
안녕하세요 강경, Ryan Step1 쉽지 않으셨을텐데 진행하시느라 고생 많으셨습니다 👍🏻 

> ## 고민한 점
> - JuiceMaker타입을 설계할 때, struct 와 class중 어떤게 더 적합할까요?
저희는 ‘상속’을 이용하지 않는 한, struct를 사용하는게 맞다고 생각하여 타입을 struct로 만들었습니다.
리뷰어분께서 보시기에도 struct를 쓰는게 더 적합하다고 생각하시는지, 혹시 저희생각했던거 외에 이번 프로젝트에서 struct를 사용하는게 더 좋은 이유같은게 있을지 궁금하여 질문드립니다..!
(원래는 Maker라는 상위클래스를 만들어, JuiceMaker타입이 상속받아 사용할 수 있도록 만드려고 했는데, 향후 상속할 소지가 없는 JuiceMaker라는 특정한 타입을 만들면 되어서 struct로 진행하게 되었습니다.)

Swift에서 Class와 Struct를 선택하는 기준에 대해서 4가지를 보고 결정하라고 권장하고 있습니다.

1. 기본적으로 **Struct**를 사용
2. Obj-c 상호 운영성이 필요한 경우 **Class**를 사용
3. 모델링하는 데이터의 identity를 제어해야 할 경우 **Class**를 사용
4. **Struct**에 프로토콜을 채택해 구현부를 공유할 수 있음.

Struct는 값 타입이므로 일반적으로 불변성을 위해서 '모델'에 해당하는 경우 많이 사용하고 있습니다.(3번 항목)
현재 JuiceMaker, Stock 같은 경우 내부 값을 바꾸기 위해서 mutating을 사용하고 있는데요, 이럴 경우 Class로 만들어 내부 값을 변경하는 것과는 어떤 차이가 있을까요?  <br> 이곳을 참고해보면 더욱 좋을것 같습니다. [링크](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)

> ## 해결이 되지않은 점 & 조언을 얻고싶은 부분
> - 저희는 json을 이용하여 JucieRecipe내용을 받아왔는데, 이걸 String, Int와 같이 Swift에서 기본으로 제공하는 타입이 아니라, 사용자정의타입으로 받아올 수 있는 방법이 있을까요?
저희는 Juice타입에서 이름을 출력하는 과정에서 이름을 name이라는 프로퍼티로 정의하여 반환하도록 하였는데, rawValue의 이름을 직접 지정해서 받아올 수 있는 방법도 있을거 같습니다. 어떤 방식이 현업에서 더 선호될지 궁금합니다..!

첫번째 질문의 경우 코드에서 코멘트로 남겼습니다 확인 해주세요 :)
저는 단순히 rawValue를 사용하는 것 보다 좋은 선택이라고 생각합니다. 해당 값이 무엇을 나타내는지 명시해놓음으로 인해서 가독성이 좋아진다고 생각합니다. (의견에 있어서 개인차는 분명 있다고 생각합니다..!)

추가로 현재 구조에 대해서 어떤 타입이 어떤 역할과 특성을 가지고 있는 지 한번 텍스트로 작성해주실수 있나요?
예를들어 JuiceMaker는 무엇을 하는 타입인지, JuiceMaker에서 requiredFruits라는 메소드는 어떤 역할을 담당하는지..와 같이 작성해보셨으면 합니다.

작성함으로 인해서 각각의 역할이 너무 많은것을 하고 있는것이 아닌지, 현재 구조가 잘 작성되어 있는지, 혹은 더 좋은 구조를 나타낼 수 도 있을 발판이 될거라 생각됩니다.
다른 코멘트들도 남겨보았으니 확인 부탁드려요! 감사합니다 :)

2021-03-13 10:04 UTC, ryan-son commented on JuiceMaker/JuiceMaker/EnumTypes.swift
> +  internal var name: String {
기본 적용되는 접근 수준이 internal인 것을 어제 알았습니다..! 코드를 PR하기 전에 삭제하려 했는데 꼼꼼히 확인을 하지 않았네요 🥲. 수정하여 internal 접근수준을 가지는 프로퍼티나 메서드는 internal 키워드를 삭제했습니다.

2021-03-13 10:06 UTC, ryan-son commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +struct Recipe: Codable {
구조체를 중첩 타입으로 정의하지 않고 별도로 정의하는 방법을 고려하여 적용해보았습니다. 이전보다 가독성이 향상 되었네요.
구조체를 정의할 때 중첩하여 사용해서 중복된 네이밍이라는 것을 인지하지 못했습니다. JuiceType 으로 수정해서 적용해두었습니다.

2021-03-13 10:06 UTC, ryan-son commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +    struct Ingredient: Codable {
JSON 디코딩을 위한 방법을 찾던 중 가장 먼저 Codable 프로토콜을 접해서 적용했는데, 해당 프로젝트에서는 Encoding할 필요가 없으므로 Decodable 프로토콜로 변경하였습니다.

2021-03-13 10:06 UTC, ryan-son commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +private let jsonString = """
json파일로 따로 빼두기 전이라면 파일 분리도 의미가 있을 것 같습니다. 파일 분리하여 다시 push 했습니다! 확실히 용도 별로 파일을 분리하니 더 깔끔하네요.

2021-03-13 10:11 UTC, ryan-son commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +      switch error {
- 호출하는 메서드에서 do-catch구문을 공통적으로 사용하기보다 make에서 받은 모든 에러는 switch 구문을 통해 처리되게끔 handleErrorForMake() 메서드로 분리하여 에러를 처리해보았습니다. 어떤 메서드에서 에러가 발생하는지 파악하기 위해 에러를 던진 함수명을 파악할 수 있게끔 Error.swift에 informErrorLocation(functionName:) 전역함수를 추가했어요.
-  현업에서는 이런 경우에 호출하는 함수마다 에러처리를 해주는 것과 저희처럼 마지막 실행 메서드에서 모든 에러를 처리하되 별도 메서드로 분리하는 것 중 어느 것이 일반적인 방식인지 궁금합니다..!

2021-03-13 10:23 UTC, ryan-son commented on JuiceMaker/JuiceMaker/EnumTypes.swift
> +  case strawberry, banana, pineapple, kiwi, mango
Ingredient 타입(JuiceRecipe.swift)의 fruitName 프로퍼티의 타입을 JSON 내용으로부터 사용자 정의 타입인 Fruit 타입으로 받기 위해 아래와 같이 CodingKeys와 init(from decoder: Decoder) 이니셜라이저를 작성하였어요. 디코딩 과정 중 실패 가능성이 있어 fruitName과 quantity 프로퍼티를 옵셔널 타입으로 적용하였습니다.
```swift
struct Ingredient: Decodable {
  var fruitName: Fruit?
  var quantity: Int?
  
  private enum CodingKeys: String, CodingKey {
    case fruitName
    case quantity
  }
  
  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.fruitName = try? container.decode(Fruit.self, forKey: .fruitName)
    self.quantity = try? container.decode(Int.self, forKey: .quantity)
  }
}
```

2021-03-13 10:24 UTC, ryan-son commented on JuiceMaker/JuiceMaker/EnumTypes.swift
> +  case strawberry, banana, pineapple, kiwi, mango
디코딩은 성공적으로 된 것 같은데, `fruitName`의 출력되는 방식에 의문이 있어 추가 질문 드려요. 아래 사진에서 `fruitName`이 `Fruit(stringValue: "Pineapple", intValue: nil)`이라고 출력되는데 `intValue`의 의미와 `nil`이 나오는 이유를 모르겠습니다.. 어떻게 알아봐야 할까요?
![image](https://user-images.githubusercontent.com/69730931/111027035-0bbafd80-8431-11eb-8f36-56faffc2261c.png)

2021-03-13 10:25 UTC, ryan-son commented on JuiceMaker/JuiceMaker/EnumTypes.swift
> +  case strawberry, banana, pineapple, kiwi, mango
출력문구는 CustomStringConvertible을 통해 해결해보았습니다..!

2021-03-13 10:27 UTC, ryan-son commented on JuiceMaker/JuiceMaker/Error.swift
> +enum FruitError: Error {
`CustomStringConvertible` 프로토콜을 활용해서 에러별로 지정된 에러 문구를 출력하도록 적용해보았습니다.

2021-03-13 10:36 UTC, ryan-son commented
타입별로 담당하는 기능을 아래와 같이 정리해보았습니다.

```swift
쥬스메이커 타입 {
- Stock 클래스 인스턴스
- 쥬스만들기(make(of:))
- 쥬스를 만들기 위해 필요한 과일의 종류와 개수를 가져오기 (checkRequiredFruits(for:))
- 필요한 과일의 종류와 양을 재고와 비교하여 재료 충분 여부를 반환하기 (hasEnoughFruits(of:))
- 재료 사용하기 (consumeStockedFruits(for:))
- 쥬스 완성 문구 출력 (printOrderCompleted(for:))
- make 메서드에서 발생한 에러 처리하기 (handleErrorForMake(_:))
}

과일재고 타입 (Stock) {
- 딕셔너리 형식 과일 재고 저장 프로퍼티 (stock = [Fruit: Int])
- 과일 초기 재고 지정 이니셜라이저
- 지정한 과일의 재고 체크하기 (checkStock(for:))
- 유효하지 않은 과일 에러 구문 출력하기 (printInvalidFruitError())
- 지정한 과일의 재고 반환하기 (count(for:))
- 지정한 과일의 재고를 지정량만큼 빼기, 지정량 없을 경우 하나 빼기 (subtract(for:amount:))
- 지정한 과일의 재고 하나 더하기
}

쥬스 레시피 타입 (JuiceRecipe) {
- JSON에서 옵셔널 Recipe로 디코딩된 저장 프로퍼티 (wrappedRecipeBook)
- JSON 데이터 디코딩 이니셜라이저
- 지정된 쥬스 레시피를 반환하기 (find(for:))
}

// JSON 파일 디코딩을 위한 타입
레시피 타입 (Recipe) { 
- 모든 쥬스 레시피 모음 저장 프로퍼티 (juiceRecipes: [JuiceType])
}

// JSON 파일 디코딩을 위한 타입
쥬스 타입 (JuiceType) {
- 레시피 내 쥬스 이름 (name: String)
- 쥬스 재료 (ingredient: [Ingredient])
}

// JSON 파일 디코딩을 위한 타입
재료 타입 (Ingredient) {
- 과일 이름 (fruitName: Fruit?)
- 필요 개수 (quantity: Int?)
- 디코딩 시 받을 프로퍼티의 이름과 JSON 내 해당 자료 이름 매칭을 위한 CodingKeys 열거형 (Decodable 프로토콜 준수)
- JSON 디코딩 시 파싱된 내용을 프로퍼티에 사용자 지정 타입으로 받기 위한 이니셜라이저(init(from decoder: Decoder))
}

과일 에러 타입 (FruitError) {
- 에러 발생 메서드명 출력 전역함수 (informErrorLocation(functionName:))
- 유효하지 않은 과일 입력 케이스
- 에러 발생 시 반환할 사용자 지정 문구 연산 프로퍼티 (CustomStringConvertible 프로토콜)
}

쥬스 에러 타입 (JuiceError) {
- 유효하지 않은 쥬스 입력 케이스
- 에러 발생 시 반환할 사용자 지정 문구 연산 프로퍼티 (CustomStringConvertible 프로토콜)
}

레시피 에러 타입 (JuiceError) {
- 유효하지 않은 레시피 입력 케이스
- 에러 발생 시 반환할 사용자 지정 문구 연산 프로퍼티 (CustomStringConvertible 프로토콜)
}

과일 타입 (Fruit) {
- 딸기, 바나나, 파인애플, 키위, 망고 케이스
- 각 케이스별로 반환할 사용자 지정 문구 연산 프로퍼티 (CustomStringConvertible)
} 

쥬스 타입 (Juice) {
- 딸기쥬스, 바나나쥬스, 키위쥬스, 파인애플쥬스, 딸바쥬스, 망고쥬스, 망고키위쥬스 케이스
- 각 케이스별 이름을 반환하기 위한 연산 프로퍼티 (name: String)
}
```

2021-03-13 11:07 UTC, ryan-son commented
@Limwin94 

Lin!
Lin이 피드백 주신 부분들을 많이 고민해서 코드를 수정해보았어요. 😄
위 코멘트와 같이 타입별로 수행하는 기능들을 정리해보았고, 코드를 다시 읽으며 이해가 어려울 수 있는 부분들도 리팩터링을 통해 개선했습니다.
궁금한 점 있으시면 DM으로 문의해주세요~!

## 개선한 점 🚀
- JuiceMaker 타입의 메서드들이 수행하는 기능을 전체적으로 조정하여 메서드 네이밍에 맞는 기능을 수행하도록 변경하였습니다.
- JSON에서 사용자 정의 타입으로 받을 수 있도록 `init(from decoder: Decoder)` 이니셜라이저를 작성하였습니다.
- Stock 타입에서 `subtract(for:)`, `add(for:)` 메서드가 `stock: [Fruit: Int]`의 값을 업데이트 하고 있지 않던 문제를 수정하였습니다.
- 각 열거타입에 `CustomStringConvertible` 프로토콜을 채택하여 사용자 지정 문구를 반환하도록 하였습니다.
- 에러 발생 위치 출력 함수(`informErrorLocation(functionName:)`)를 추가하여 디버깅을 용이하게 할 수 있게끔 하였습니다.

## 고민한 점 / 조언을 얻고 싶은 부분 🧐
- 내부 identity의 변경이 있을 경우 `class` 사용이 권장되는 것으로 파악하였는데, identity가 프로퍼티를 이야기하는 것인가요?
  - 저희는 identity가 프로퍼티를 의미한다고 생각하여 프로퍼티 수정 메서드가 있는 타입을 모두 `class`로 변경하였습니다.
- `struct`는 `mutating` 메서드에 의해 프로퍼티 변동이 생기면 새로운 값을 생성하는 방식으로 작동된다고 공부하였는데 맞는 내용인가요?
- Step 2에서 UI 구현을 할 때 각 과일의 재고를 보여주기 위한 메서드를 현재는 `JuiceMaker` 내에서 생성된 `stock` 인스턴스의 메서드를 통해 출력이 가능합니다. 저희는 `JuiceMaker`에서 하는게 맞다고 판단되는데, Lin의 생각은 어떠신가요?

2021-03-13 15:30 UTC, KangKyung commented
위의 "**고민한 점 / 조언을 얻고 싶은 부분**"에서
> Step 2에서 UI 구현을 할 때 각 과일의 재고를 보여주기 위한 메서드를 현재는 `JuiceMaker` 내에서 생성된 `stock` 인스턴스의 메서드를 통해 출력이 가능합니다. 저희는 `JuiceMaker`에서 하는게 맞다고 판단되는데, Lin의 생각은 어떠신가요?

이 질문에 좀 더 덧붙여서 질문드립니다..!

은닉화 측면에서, 
```swift
class MakeJuice {
  let stock = Stock()
}

MakeJuice.stock.add()
```
이런 식의 호출을 진행해도 되는건지, 아니면 
```swift
class MakeJuice {
  private let stock = Stock()

  stockAdd() {
    stock.add()
  }
}

MakeJuice.stockAdd()
```
이런 식으로 감싸서, 밖에서는 stock.add()에 직접적으로 접근할 수 없게 만들어야하는지 궁금합니다🤔

2021-03-15 16:41 UTC, Limwin94 reviewed
강경, Ryan 꼼꼼하게 코멘트를 남겨주어 감사합니다. 진행하시느라 고생하셨어요. 💯 

마지막에 강경이 남겨주신 질문은 리뷰하면서 해당 부분에 코멘트로 달아놓았습니다. 이부분 확인 부탁드릴게요 :)

---

## 고민한 점 / 조언을 얻고 싶은 부분

> - 내부 identity의 변경이 있을 경우 class 사용이 권장되는 것으로 파악하였는데, identity가 프로퍼티를 이야기하는 것인가요?
저희는 identity가 프로퍼티를 의미한다고 생각하여 프로퍼티 수정 메서드가 있는 타입을 모두 class로 변경하였습니다.

네 맞습니다 :) 

> - struct는 mutating 메서드에 의해 프로퍼티 변동이 생기면 새로운 값을 생성하는 방식으로 작동된다고 공부하였는데 맞는 내용인가요?

새로운 인스턴스가 할당된다는 내용이라면 아닌것 같습니다. mutating 메서드 사용시 Struct 자체에 대한 메모리 주소는 변경되지 않는 것으로 보아 단순히 내부 값만 바뀌는것 같은데, 혹시 어떤 레퍼런스를 참고 했는지 공유가능할까요?

> - Step 2에서 UI 구현을 할 때 각 과일의 재고를 보여주기 위한 메서드를 현재는 JuiceMaker 내에서 생성된 stock 인스턴스의 메서드를 통해 출력이 가능합니다. 저희는 JuiceMaker에서 하는게 맞다고 판단되는데, Lin의 생각은 어떠신가요?

JuiceMaker에서 재고 관리를 위해 Stock을 가지고 있고 사용되고 있다면 좋은 생각인 것 같습니다.
대신에 강경처럼 직접 Stock으로 접근할 건지, 아닌지에 대한 고민이 필요하겠네요

> - Stock 타입의 subtract(for:), add(for:) 메서드와 같이 guard문의 else에서 에러가 일어난 곳을 프린트하고 return으로 종료하는 방식

개인에 따라 다르다고 생각합니다. 다만, 기준을 세워 통일성을 유지해야 된다고 생각합니다.
두번째 항목에 대해선 코멘트로 남겼습니다.
`Result` 또한 가독성 향상이나 에러처리시 도움이 많이 될 것 같습니다 👍🏻 

---

이번에도 코멘트가 많은데요 😅 천천히 고민해보시고 궁금하신 사항 있으시면 언제든 DM 부탁드립니다.
화이팅입니다!

2021-03-15 16:41 UTC, Limwin94 commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +      throw RecipeError.invalidRecipe
에러를 더욱 세분화 해보는건 어떨까요? 세분화 되는 만큼 `informErrorLocation()`이 쓰이지 않아도 될 것 같습니다.

2021-03-15 16:41 UTC, Limwin94 commented on JuiceMaker/JuiceMaker/Error.swift
> +enum JuiceError: Error, CustomStringConvertible {
현재 `JuiceError`가 사용되고 있는 곳이 있나요?

2021-03-15 16:41 UTC, Limwin94 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        throw FruitError.invalidFruit
에러내용을 세분화 하였으면 좋겠습니다. 
해당 메소드의 경우 "과일에 대한 입력"이 되는 부분이 없다고 생각되는데 어떻게 표시해줘야 할까요?

2021-03-16 11:56 UTC, KangKyung commented on JuiceMaker/JuiceMaker/EnumTypes.swift
> +
Model폴더 안에 EnumTypes, StructTypesForDecoding폴더를 생성하여, 각 파일들이 하는 역할에 따라 분리시켰습니다👍🏻

2021-03-16 12:03 UTC, KangKyung commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +  var stock = Stock()
열심히 고민한 끝에..!
Step2와 Step3에서 사용자가 `Stock`클래스에 직접 접근해야하기 때문에,
`Stock`클래스의 인스턴스를 `static` 타입 프로퍼티로 구현하여 (싱글턴 패턴)
`JuiceMaker`타입과 관계없이 독립적으로 사용할 수 있게 만들었습니다😁

2021-03-16 12:13 UTC, KangKyung commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +  private func hasEnoughFruits(of requiredFruits: [Fruit: Int]) throws -> Bool {
훌륭한 말씀이십니다..🤩🤩
Lin이 아래에 코멘트에 남겨준 것과 연계해서,
`Stock.count`메서드와 같이 에러가 발생했을 때, 치명적이지 않은경우(ex 해당 과일에 대한 재고가 nil일 경우)에 대해 에러를 발생시키지 않고,
0이라는 값을 반환함으로서, `hasEnoughFruits`메서드에서 에러처리를 하지 않도록 했습니다.
(`hasEnoughFruits`메서드는 바로 아래의 코멘트에서 언급하신 `count`메서드를 호출하기 때문에, 에러처리가 필요했습니다.)

2021-03-16 12:40 UTC, KangKyung commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +  private func hasEnoughFruits(of requiredFruits: [Fruit: Int]) throws -> Bool {
throw를 사용하는 이유는, `hasEnoughFruits`메서드에서 `count`메서드를 호출하기 때문이었습니다.
아래 코멘트에서 자세히 말씀드리겠지만, 저희는 이 프로그램이 사용자 입력이 아닌 버튼 입력방식이기 때문에,
`count`메서드에 입력되는 파라미터가 유효하지 않은 경우, 
0이라는 값을 반환하게 되면 사용자 입장에서는 버튼을 눌러도 동작하지 않기 때문에, 어떤 문제가 일어났는지 알 수 없게됩니다.
그렇기 때문에, 프로그램에 어떤 문제가 일어났는지 명확히 보이기 위해서는 에러처리를 하는것이 맞다고 생각합니다.
추후 step2에서는 이러한 문제가 일어났을 때 `alert`형식으로 오류를 처리할 예정입니다..!

2021-03-16 12:42 UTC, KangKyung commented on JuiceMaker/JuiceMaker/Stock.swift
> +    guard let fruitNumberInStock = stock[fruit] else {
위의 코멘트에서 언급한 바와 같이, 사용자 입장을 고려하여 처리해 보았습니다.. 어떻게 생각하시나요?😅

2021-03-16 12:44 UTC, KangKyung commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +}
훌륭한 말씀이십니다..🤩🤩
Lin의 첫번째 코멘트의 `EnumTypes`를 나누는 과정에서 관련있는 모델끼리 분리하였습니다!!

2021-03-16 12:49 UTC, KangKyung commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +      throw RecipeError.invalidRecipe
에러를 던지는 메서드 마다 각각 하나의 case를 할당하였습니다.
그러면서 `informErrorLocation()`이 쓰이지 않게되어 삭제하였습니다🧹

2021-03-16 12:51 UTC, KangKyung commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        throw FruitError.invalidFruit
메서드의 파라미터가 `Juice` 타입인데, `Fruite`에러를 던지고 있었군요..😅
`Juice`에러로 변경하였습니다..!

2021-03-16 12:53 UTC, KangKyung commented on JuiceMaker/JuiceMaker/Error.swift
> +enum JuiceError: Error, CustomStringConvertible {
`checkRequiredFruits`에서 사용해야 했는데🤦🏻‍♂️
아래 코멘트를 참고해주세요..!

2021-03-16 13:07 UTC, KangKyung commented
@Limwin94 

Lin!
적어주신 코멘트를 꼼꼼히 읽으면서 치열하게🔥 고민해 보았습니다..!
이번에도 궁금한 점은 DM💌부탁드려요!

## 개선한 점 🚀
- 각 구조에 맞게 `EnumTypes`와 Decode를 위한 구조체파일을 분리하였습니다!
- `Stock`타입에 Singleton pattern적용을 도전해 보았습니다👍🏻
- 에러처리를 좀 더 세분화시켜, 에러 발생 위치를 알려주는, 불필요한 메서드를 삭제하였습니다🧹

## 고민한 점 / 조언을 얻고 싶은 부분 🧐
- 에러 처리에 대한 나름의 결론을 내렸지만, 아직 확신이 들지 않습니다.
위에서는 throw를 통한 에러처리를 진행했지만,
`Stock.count`메서드와 같이 에러가 발생했을 때, 치명적이지 않은경우(ex 해당 과일에 대한 재고가 nil일 경우)에 대해 에러를 발생시키지 않고,
0이라는 값을 반환함으로서, `hasEnoughFruits`메서드에서 에러처리를 할 수 있다고 생각합니다.
Lin의 피드백 덕분에, 이 부분에 대해 깊이 생각해볼 수 있어서 좋았어요!
하지만, 분명 저희가 놓친 부분이 있는 것 같습니다..!
Lin은 이 부분에 대해 어떤생각을 가지고있는지 궁금합니다🤔

2021-03-17 16:09 UTC, Limwin94 approved these changes
강경, Ryan 진행하시느라 고생많으셨습니다.

말씀해주신 고민한 점 / 조언을 얻고 싶은 부분에 대해서 코멘트는 밑에 남겨두었습니다.
이 외의 부분은 Step2를 진행하면서 같이 고민해보아요.

고생하셨습니다 💯

2021-03-17 16:09 UTC, Limwin94 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +  private func hasEnoughFruits(of requiredFruits: [Fruit: Int]) throws -> Bool {
재고가 0일 경우 `if stockedQuantity < requiredQuantity`에서 걸러질 것 같습니다.
또한 `count`메서드에 입력되는 `Fruit` 타입이 잘못 들어올 여지가 있을까요?

앱의 안정성을 위해 유효성 검사를 하는 것은 분명 좋은 일이지만 현재의 경우 `hasEnoughFruits`은 굳이 에러를 던지지 않아도 호출하는 쪽에서 값이 false면 과일이 충분치 않다는 것을 사용자에게 알려주는 메서드라고 생각하게 될 것 같습니다.
써야한다면 throws 혹은 Bool값 둘 중 하나만 써야할 것 같네요.

오히려 `make`의 경우 throws를 사용해야 할 것 같습니다.
상위객체에서 `make`를 호출해서 사용할 경우 에러가 일어난 사실을 알 수 있을까요?

2021-03-18 15:13 UTC, merged