[Step1] Sunny, Steven
yagom-academy/ios-juice-maker pull request #47
Opened 2021-03-12 07:23 UTC by stevenkim18

@seizze 

하이디 안녕하세요!! step1 PR 보냅니다 :)

## 고민한 점
### 과일(Fruit)을 어떤 타입으로 정해 줄지
- 과일을 어떤 타입으로 할지 고민하다가 결국에는 enum을 선택했습니다. 
- 프로젝트 요구 사항에 새로운 **종류**의 과일이 추가 되는 것이 없어서 enum으로 하는 것이 좋다고 판단했습니다.
- 그러면 문제점이 저번주 처럼 `가위바위보` 타입과 같이 과일 타입에서도 `rawValue` 를 사용하고 싶은 경우가 생깁니다 (지난주 하이디의 리뷰 https://github.com/yagom-academy/ios-rock-paper-scissors/pull/33#discussion_r587533327)
- `JuiceMaker`의 프로터피로 `fruitStocks` 라는 과일의 수량을 배열을 선언헀는데 `rawValue`를 사용해서 인덱스로 접근해주려고 했습니다.
- 그래서 지난주 똑같이 과일 타입 안에 `index` 를 선언해서 `rawValue` 를 리턴하게 해주었습니다.(코드 9-15줄 참고)
- 도저히 고민해도 더 좋은 방법을 모르겠어요 ㅜㅜ 하이디라면 어떻게 구현했을거 같나요?

## 해결이 되지 않은 점

## 조언을 얻고 싶은 부분
### flowchart, class diagram
- https://github.com/stevenkim18/ios-juice-maker-fork/blob/main/README.md
- 위 링크에 가시면 저희가 작성 플로우 차트와 클래스 다이어 그램을 볼 수 있어요 
- 현업에서 사용하는 클래스 다이어그램 툴들이 있나요?
- 보통은 자바를 기반으로 프로그램이 제작 되어있어서 enum이나 접근제어자등을 제대로 표현 할 수 없는데 swift용 프로그램이 있을까요? 없다면 간단하게 설계 할 때 하이디는 어떻게 하시나요?

2021-03-13 11:49 UTC, seizze requested changes
안녕하세요 스티븐, 써니~ 수고 많으셨어요 ☺️

PR 코멘트에 써주신 과일 타입과 Flow chart에 대한 의견은 모두 코드에 남겼습니다 ㅎㅎ

그런데... Sunny의 커밋이 하나도 보이지 않네요 뭔가 어려움이 있나요?

2021-03-13 11:49 UTC, seizze commented on README.md
> +![classDiagram](https://user-images.githubusercontent.com/35272802/110903528-f075c280-834a-11eb-9851-03067d4ddea6.jpeg)
플로우 차트와 클래스 다이어그램 잘 그리셨네요! 👍 
현업에서 특별히 사용하는 툴은 없고, 제가 아주 가끔 사용하는 툴을 공유해드리자면 [UMLet](https://www.umlet.com)이 있습니다 ㅎㅎ 팀에서 발표할 땐 저는 보통 그냥 키노트를 사용합니다.

스위프트용 프로그램이 따로 있는지는 잘 모르겠네요 ㅎㅎ 보통 enum이나 접근제어자들을 정확하게 표시하는게 목적이 아니라 저는 큰 구조를 그려서 이해를 전달할 때 사용하고 있었기 때문에 스위프트용 툴이 필요하다고 느낀 적은 별로 없는것 같아요.. ☺️

저는 플로우 차트나 클래스 다이어그램은 개발할 때마다 매번 그리는 건 아니고, 간단하게 설계 정리가 필요할 땐 그냥 빠르게 손그림으로 그리고 공유가 필요할 때 작업해서 설명하는 편입니다.

2021-03-13 11:49 UTC, seizze commented on README.md
> +![classDiagram](https://user-images.githubusercontent.com/35272802/110903528-f075c280-834a-11eb-9851-03067d4ddea6.jpeg)
그리고 클래스 다이어그램 관련해서,
프로퍼티나 메서드도 중요하지만 타입들의 관계(참조, 상속, 구현 등)을 표현하는 것도 중요합니다. 아래는 제가 옛날에 그린건데 타입들 간 관계 표현 참고용으로 보세요!

![image](https://user-images.githubusercontent.com/49332230/111028449-09a96c80-843a-11eb-868b-6579c6c715d9.png)

2021-03-13 11:49 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
메서드는 호출하는 쪽 기준으로 어떻게 사용되는지도 고려해서 이름을 지으면 좋아요~
예를 들어 이 메서드는 `juiceMaker.checkStock(of: Kiwi.self)` 이런 식으로 호출되면 더 자연스러워 보이지 않을까요?

2021-03-13 11:49 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
이 메서드도 호출하는 쪽 기준으로 생각해 보면 Juice라는 단어가 두 번 반복되네요! 스위프트에서는 argument label도 함수 이름에 포함된다는 걸 고려해서 작성하면 좋을것 같아요~ argument label을 쓰지 않는게 적합하다고 생각한다면 `_`를 사용해서 생략할 수도 있습니다.

2021-03-13 17:11 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
너무 도전적인 과제를 제안한 것 같아서.. 다시 돌아와서 코멘트 남깁니다..
너무 어려우면 Fruit이 rawValue로 Int를 사용하지 않도록만 개선해봐도 좋을것 같아요. 이렇게 하기 위해선 fruitStock을 숫자로 표현하지 않고 `[Fruit: Int]` 타입으로 들고 있도록 해야합니다.

2021-03-15 11:23 UTC, unme88 commented
> 안녕하세요 스티븐, 써니~ 수고 많으셨어요 ☺️
> 
> PR 코멘트에 써주신 과일 타입과 Flow chart에 대한 의견은 모두 코드에 남겼습니다 ㅎㅎ
> 
> 그런데... Sunny의 커밋이 하나도 보이지 않네요 뭔가 어려움이 있나요?

브랜치를 합치는 과정에서 저의 커밋이 반영이 안됐습니다 ^.^;;
처음에는 저의 브랜치에서 같이 페어프로그래밍을 하다가
마지막에는 스티븐의 브런치에서 작성한 코드를 메인으로 푸쉬하면서 저의 커밋이 누락됐습니다ㅎㅎ
다음에 주의해서 작업하도록 할게요! 감사해요!

2021-03-15 11:27 UTC, unme88 commented on README.md
> +![classDiagram](https://user-images.githubusercontent.com/35272802/110903528-f075c280-834a-11eb-9851-03067d4ddea6.jpeg)
공유해주셔서 감사합니다! 다음번 프로젝트 할 때 참고할게요 :)

2021-03-15 11:58 UTC, unme88 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
하이디의 의견을 반영해서 `juiceMaker.checkStock(of: .kiwi)`으로 수정했습니다 ^.^ 감사해요~!!

2021-03-15 14:12 UTC, seizze commented
> > 안녕하세요 스티븐, 써니~ 수고 많으셨어요 ☺️
> > PR 코멘트에 써주신 과일 타입과 Flow chart에 대한 의견은 모두 코드에 남겼습니다 ㅎㅎ
> > 그런데... Sunny의 커밋이 하나도 보이지 않네요 뭔가 어려움이 있나요?
> 
> 브랜치를 합치는 과정에서 저의 커밋이 반영이 안됐습니다 ^.^;;
> 처음에는 저의 브랜치에서 같이 페어프로그래밍을 하다가
> 마지막에는 스티븐의 브런치에서 작성한 코드를 메인으로 푸쉬하면서 저의 커밋이 누락됐습니다ㅎㅎ
> 다음에 주의해서 작업하도록 할게요! 감사해요!

엇.. 지금은 보이네요.. 제가 잘못 봤나봐요 😅 머지 커밋에 섞여있었나봐요

2021-03-15 14:18 UTC, seizze commented
그런데.. 커밋 6481f85 에서 수정을 하셨는데 머지 커밋인 127d389 에서 원래 코드로 원복됐네요 ㅠㅠ 충돌 해결이나 merge할 때 문제가 생긴거 같아요

페어 프로그래밍을 할때 merge 작업 없이 하려면,
- 작업하던 컴퓨터에서 push
- 상대방 컴퓨터에서  fetch & 해당 브랜치로 checkout 

한 다음에 그 상태에서 바로 커밋할 수도 있어요~!

2021-03-16 02:10 UTC, unme88 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
하이디의 조언을 참고해서 배열을 딕셔너리로 바꿔봤어요 🙂

2021-03-16 02:11 UTC, unme88 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
_로 바꿔줘서 Juice라는 단어를 반복하지 않게 해줬어요. 다음 번에도 주의할게요! 감사합니다 ^.^

2021-03-16 13:03 UTC, seizze commented
수정 다 하신걸까요? 다 하셨으면 코멘트 주세요~ ㅎㅎ

2021-03-16 13:16 UTC, seizze approved these changes
수고하셨습니다~!
수정은 다 하신것 같아서 머지하겠습니다 😎
추가 의견 남겼으니 다음 단계 진행하면서 확인부탁드릴게요! :)

2021-03-16 13:16 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
옵셔널 강제 추출을 해버렸네요. 이러면 과일 재고가 없거나 했을 때 그냥 앱이 꺼져버립니다. 어떻게 하면 안전하게 처리할 수 있을까요?

2021-03-16 13:16 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    var fruitStocks: [Fruit: Int] = [:]
fruit stock 자체로 과일들의 저장소를 의미하니 복수형이 아니어도 되지 않을까요?

2021-03-16 13:16 UTC, merged

2021-03-18 00:05 UTC, unme88 commented
> 수고하셨습니다~!
> 수정은 다 하신것 같아서 머지하겠습니다 😎
> 추가 의견 남겼으니 다음 단계 진행하면서 확인부탁드릴게요! :)

감사합니다 ^.^
추가 의견 남겨주신거 스티븐이랑 같이 있다 얘기해볼게요! :)