2 jay
yagom-academy/ios-juice-maker pull request #48
Opened 2021-03-12 12:38 UTC by helloworldjay

reviewer: @seizze 

## 코드를 작성할 때 고민되었던 점 :

```
- 과일 재고를 어떤 자료형으로 처리할지(enum vs dictionary vs struct vs class)
```

## 조언을 얻고 싶은 부분 :

README에 거의 모든 부분을 만들 때 고민한 것을 정리해보았습니다. 혹시 잘못된 생각이나 더 나은 방향이 있다면 말씀 부탁드립니다!

리뷰 감사합니다! :)

2021-03-13 16:51 UTC, seizze requested changes
Jay, 요시킴 수고 많으셨습니다! 전체적으로 고민한 부분이 많이 보이네요 ㅎㅎ

README에서 의도를 잘 이해할 수 있어서 더 관련있는 내용을 말씀드릴 수 있었던 것 같아요 💯 
고민한 내용과 그 답을 정리한 내용, 특히 트러블슈팅한 내용은 채용 담당자분들도 유심히 본답니다 ㅎㅎ

코드 관련해서는, 외부에서 접근할 메서드와 내부에서만 사용할 메서드를 의도를 갖고 구분하신 점이 인상깊었습니다. 타입 및 파일들을 적절히 분리하신 점도 아주 적절했습니다. 👍👍  옵셔널 처리도 모두 깔끔하게 잘 해주셨어요~

다만 커밋은 작업 단위를 잘 나눠서 구분해 보면 좋을 것 같아요. 그래야 나중에 부분적으로 되돌리거나 할 수 있고, 나중에 다른 사람이 그 코드를 볼 때 line 단위로 히스토리를 확인할 수 있게 됩니다.

마지막으로, 객체지향적으로 개선하는 것 관련해서 코멘트를 여러개 남겼습니다. 목적과 역할에 맞게 타입들을 잘 분리하셨으니, 이제 타입이 능동적으로 동작하도록 개선하는 데에 중점을 두면 좋을 것 같아요!

2021-03-13 16:52 UTC, seizze commented on README.md
> +- 스토리보드보다 코드 베이스로 코딩하기
(이번 프로젝트에서 무조건 스토리보드를 사용해야 한다는 의미는 아닙니다 ㅎㅎ)

2021-03-14 10:56 UTC, helloworldjay commented on README.md
> +- 스토리보드보다 코드 베이스로 코딩하기
네 감사합니다! :) 지난번 iOS 개발자 클럽하우스 대화에서 현업에서는 스토리보드보다 코드베이스로 작업한다는 말씀을 듣고 이번 프로젝트에 적용해보려고 했습니다! 스토리보드를 통해 작업하는 방법도 고민해보겠습니다 :)

2021-03-14 10:57 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    let fruitStockManager = FruitStockManager.shared
여기서는 은닉화를 생각하지 못했었습니다! 말씀해주신대로 두 변수 모두 private으로 변경했습니다 :)

2021-03-14 11:04 UTC, helloworldjay commented on README.md
> +     - why Singleton?: 과일의 재고를 하나의 객체로 생성해서 공유하며 여러 View나 다른 객체에서 사용해도 그 데이터는 하나의 개념으로 공유되므로 Singleton으로 관리될 수 있다.
재고 매니저의 코드가 변경되어야 할 경우, 재고 매니저의 코드만 변경하면 이 클래스를 사용하는 다른 클래스들에서는 자동적으로 그 변경사항이 반영되어 작동되는 것으로 이해하고있는데 제가 혹시 잘못 이해하고 있는 부분이 있을까요? 싱글톤에 대한 이해가 부족해서 아래 상황들에 발생할 문제점이 아직은 그려지지 않습니다 ㅠ 조금 더 공부해보고 주신 상황들을 이해할 수 있도록 해보겠습니다!

2021-03-14 11:12 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/FruitStockManager.swift
> +    }
아 작동하지 않겠네요.. ㅠ optional을 처리할 생각만 하다보니 생각을 잘못했습니다! 다시 생각해서 바꿔보았는데 혹시 더 좋은 방법이 있다면 다시 한번 피드백 부탁드립니다 :)

2021-03-14 11:12 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/FruitStockManager.swift
> +    }
넵 변경했습니다! :)

2021-03-14 11:20 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +    }
오 네! 훨씬 좋은 방법 같습니다! 그런데 코드 작성과정에서 if let으로 처리하면 FruitTypeAndAmount로 리턴(레시피 결과)로 나오게 되는데 문제는 if 문 바깥에 return값이 없어서 오류가 발생합니다! dummy 값을 넣는 것은 안좋은 코딩같아서 방법을 찾아보고 있는데 혹시 작업하실 때 이런 경우 선호하시는 방식이나 추천해주실 수 있는 방식을 들을 수 있을까요? :)

2021-03-14 11:21 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
네! 기능요구서 STEP2에서 해당 내용이 있어서 STEP2 에서 구현하려고 했는데 1에서 하는게 더 좋을까요?

2021-03-14 11:25 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        guard let juiceIngredients: FruitTypeAndAmount = juiceRecipe[juiceName] else { return }
흠 제가 이해하기로는 JuiceRecipe에서 해당 Recipe를 찾아 직접 그 레시피를 반환하게 해주는 위의 피드백을 적용하면 조금 더 능동적인 동작이라고 생각되는데 그렇게 이해하면 될까요? 여기서 직접 레시피 북을 찾아보는게 아니라 레시피북에서 검색 결과를 반환하는 코드로 여기서는 결과만 가지고 작동하게 변경해보겠습니다! 혹시 이해가 잘못 되었다면 말씀 부탁드립니다!

2021-03-15 03:35 UTC, seizze commented on JuiceMaker/JuiceMaker/FruitStockManager.swift
> +    }
잘 바꾸셨네요! 👍

2021-03-15 03:40 UTC, seizze commented on README.md
> +     - why Singleton?: 과일의 재고를 하나의 객체로 생성해서 공유하며 여러 View나 다른 객체에서 사용해도 그 데이터는 하나의 개념으로 공유되므로 Singleton으로 관리될 수 있다.
아, 재고 매니저의 내부 구현 변경이 아니라 인터페이스의 변경을 말씀드린거였습니다 :) 외부에서 접근 가능한 메서드에 매개변수가 추가되거나, 변경되거나, 새 메서드가 생긴다거나 하는거요~

싱글톤을 사용할 때의 문제점을 말씀드린 이유는, 싱글톤이 편하긴 하지만 편한 만큼 수반되는 문제점들이 많으니 그것들을 고민해 보고, 이런 문제들을 감수하고 대처할 정도로 싱글톤이 꼭 필요한지, 정말 앱의 모든곳에서 접근해야 할 만큼 공통되는 컴포넌트인지를 다시 생각해 봤으면 좋겠다는 의미였습니다 😎

2021-03-15 03:58 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +        "mangoKiwiJuice":[("mango", 2), ("kiwi", 1)]]
여기에 다소 복잡한 자료구조가 표현되어 있는데, 이렇게 개선해보면 어떨까요?

- 추상적인 쥬스 레시피 타입을 만들고, 구체적인 딸기쥬스 레시피, 바나나쥬스 레시피 등의 타입을 구현
- 각 구체 타입들에서 구체적인 레시피(딸기 16개)를 표현
- 여기 구조체에서는 추상적인 쥬스 레시피 타입들의 배열로 정보를 갖고 있음
- 외부에서 쥬스 레시피를 물어보면 구체 타입 리턴

이해가 안간다거나 설명이 더 필요하다면 질문 주세요~!

2021-03-15 03:59 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        }
아 네 그럼 스텝2에서 구현하시죠 ㅎㅎ

2021-03-15 04:22 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    let fruitStockManager = FruitStockManager.shared
아하.. FruitStockManager가 싱글톤임을 알기 전 코멘트여서 이렇게 남겼네요~

만약 싱글톤을 사용하실거라면, 싱글톤을 사용하는 객체에서 이렇게 프로퍼티로 참조를 저장해 놓는게 어색하게 느껴지긴 합니다. 보통 사용하는 부분에서 바로 FruitStockManager.shared로 접근해서 사용하거나, 코드가 너무 길어진다면 로컬 변수 정도로 선언해서 사용하는 것 같네요 ㅎㅎ

> 상수를 한번만 생성해서 사용하는 것인지, 아니면 저 shared를 통해 다른 곳에서 선언해도 하나의 클래스에서 동작하므로 공유되는 개념인지 궁금합니다!

```swift
let a = FruitStockManager.shared
let b = FruitStockManager.shared
let c = FruitStockManager.shared
```

이런 식으로 여러 군데서 여러 번 상수를 선언해도 하나의 인스턴스를 공유하는것인지 질문하신거면, 일단은 그게 맞습니다. 싱글톤 인스턴스가 언제 생성되는지 공부해보면 좋을거 같아요 ☺️

싱글톤 관련해서는 아래 더 의견 남겼으니 확인부탁드릴게요 :)

2021-03-15 04:26 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +    }
여기선 옵셔널을 그대로 리턴하고, 외부에서 처리하게 하는 것도 하나의 방법일 것 같네요 😎

2021-03-15 04:31 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        guard let juiceIngredients: FruitTypeAndAmount = juiceRecipe[juiceName] else { return }
네 맞아요 위쪽 피드백이랑 연관된 코멘트였습니다 ㅎㅎ 이것 관련하여 아래에 추가 의견 남겼으니 확인 부탁드려요~

2021-03-15 05:17 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +    }
옵셔널로 반환하는 것을 생각하지 못했습니다! 옵셔널로 반환해서 사용하는데에서 guard let 하는 것으로 처리했습니다 :)

2021-03-15 05:19 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        guard let juiceIngredients: FruitTypeAndAmount = juiceRecipe[juiceName] else { return }
넵 감사합니다!

2021-03-15 05:35 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    let fruitStockManager = FruitStockManager.shared
네 감사합니다! :) 
1. 보통 사용하는 부분에서 바로 사용한다는 말씀이 위의 코드에서 fruitStockManager로 선언하는게 아니라 아래 사용할 때 FruitStockManager.shared.decreaseStockAmount(of: fruitType, by: fruitNumber)로 사용한다는 말씀으로 이해해도 괜찮을까요? 
2. 로컬 변수라고 하시면 위의 fruitStockManager처럼 클래스 안에서가 아니라 함수 내의 선언으로 이해해도 괜찮을까요?

2021-03-15 05:55 UTC, helloworldjay commented on README.md
> +     - why Singleton?: 과일의 재고를 하나의 객체로 생성해서 공유하며 여러 View나 다른 객체에서 사용해도 그 데이터는 하나의 개념으로 공유되므로 Singleton으로 관리될 수 있다.
네! 사용시에는 싱글톤의 장점 위주로 찾아보다보니 적용부터 했는데 말씀을 듣고 단점을 찾아보니 본 프로젝트에서는 전역적으로 선언될 만큼 모든 곳에서 해당 클래스를 사용하는게 아니라서 싱글톤일 필요가 없을 것 같습니다! 싱글톤이 아닌 구현을 진행했습니다 :) 감사합니다!

2021-03-15 07:08 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    let fruitStockManager = FruitStockManager.shared
1, 2 둘다 맞습니다 :D

2021-03-16 13:01 UTC, seizze commented
수정 다 하신건가요? 머지해도 될까요? 😎

2021-03-16 14:25 UTC, helloworldjay commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +        "mangoKiwiJuice":[("mango", 2), ("kiwi", 1)]]
개선 완료했습니다 :)

2021-03-16 14:26 UTC, helloworldjay commented
네! 말씀 주신 부분들 모두 수정하여 적용했습니다 :) 피드백 감사합니다!

2021-03-16 16:33 UTC, seizze approved these changes
수고하셨습니다~!
머지할테니 추가 피드백은 다음 단계 진행하면서 확인부탁드릴게요 ☺️

2021-03-16 16:33 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceRecipe.swift
> +}
키위쥬스 말고 다른 쥬스들은 레시피를 안바꿨네요~

2021-03-16 16:33 UTC, seizze commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        let fruitStockManager = FruitStockManager()
메서드를 호출할 때마다 새 인스턴스를 생성하고 있네요! 의도된건가요?

2021-03-16 16:33 UTC, merged