[STEP 2] Fezz, Sookim
yagom-academy/ios-juice-maker pull request #49
Opened 2021-03-12 16:18 UTC by Sookim18

## [STEP 2] 쥬스 메이커  🧃- 1

@delmaSong 

안녕하세요!  `delma`!

`step1`을 진행 한 후 보완할 부분들을 포함해서 `step2`를 진행해봤어요 !😄

### 고민되었던 점, 해결되지 않은 점, 궁금한 점  ⁉️

1. 싱글톤 패턴을 `fruitStock`에서 적용해야 되는 걸로 생각했었는데 프로젝트를 진행해보다가 `JuiceMaker`에 적용하는 것이 더 적합하다고 판단해서 변경해봤어요 
	*	그렇게 생각한 이유❓ 는 과일재고자체가 행동을 하는 것이 아닌 쥬스메이커가 재고관리를 해주기 때문에 여기에 적용하는 것이 더 적합하다고 생각했어요 ! 

2. `step2`에서 예를들어 딸기 주스 버튼을 눌렀을 때 버튼의 속성값을 받아서 처리를 각각의 버튼마다 `tag`값을 지정해주어서 처리해보았는데 다른 좋은 방법이 있을까요?🤔

3. 저희가 `MVC패턴`을 염두해서 작성하고 있는데 올바른 방향으로 가고 있을까요?

### Auto Layout 적용 

<img width="300" alt="1" src="https://user-images.githubusercontent.com/55218398/110967149-6dc82400-8399-11eb-8d8f-521292ebcb5d.png">

<img width="300" alt="2" src="https://user-images.githubusercontent.com/55218398/110967297-90f2d380-8399-11eb-9c2a-6a4ecfdb1601.png">

<img width="300" alt="3" src="https://user-images.githubusercontent.com/55218398/110967388-a7009400-8399-11eb-9d2c-276ce0f7a8ee.png">

---
* iPhone se
<img width="300" alt="4" src="https://user-images.githubusercontent.com/55218398/110967486-c0a1db80-8399-11eb-9992-d7b4c30b3ad6.png">

2021-03-14 09:23 UTC, delmaSong reviewed
수고하셨습니다! 👏🏼👏🏼👏🏼👏🏼👏🏼
오토레이아웃도 잘 구현하셨네요! 다만 현재 iPhone SE에서 상단 부분이 좀 어긋나는데 이쪽만 확인해주세요!


`고민하신 점`
1. 아래 코멘트에도 남겨놓았듯이 버튼의 태그와 쥬스들의 rawValue에 어떤 연관관계가 없어서 태그로 접근하는 방법보다는 다른 방법이 더 좋을 것 같아요. 그리고 지금도 똑같은 버튼들, 라벨들이 반복해서 사용되는데 커스텀 버튼으로 만들어보는 건 어떨까요?
2. MVC 패턴을 지향한다고 하셨는데 각각이 무엇인지 설명해주실 수 있을까요? 구현하신 Juices와 FruitStock 는 MVC중 어디에 속하나요?

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    var juiceMaker = JuiceMaker.shared
juiceMaker가 외부에 공개되어야 할 이유가 있을까요?

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    @IBOutlet weak var kiwiLabel: UILabel!
IBOutlet도 접근제어자를 지정해줄 수 있답니다

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    }
메소드를 정의하는 순서가 무엇인지 궁금합니다
`touchUpjuiceOrderButton(_:)`이 `viewDidLoad`보다 먼저 와있네요

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    }
카멜케이스를 지켜서 이름을 작성해주세요

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    func lakeStockAlert() {
어떤 기준으로 extension을 사용하신건가요?

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        kiwiLabel.text = String(stock[.kiwi]!)
지금처럼 모든 과일의 라벨을 일괄적으로 업데이트 하는 것이 아니라 재고에 변화가 생긴 과일만 업데이트 하는게 어떨까요?

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        strawberyBananaButton.layer.borderWidth = 1.2
각 값들을 변수로 할당해서 쓰는 게 좀 더 편하지 않을까요?

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    func updataStock() {
메소드도 외부에 노출될 일이 없다면 접근제어자를 지정해주세요

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
메소드에서 에러가 발생한 경우 throws로 던지고 있는데
막상 내부에서는 do catch문으로 잡고있네요
꼭 여기서 에러를 캐치해야 하는 이유가 있는게 아니라면 에러 처리를 한곳에서 할 수 있도록 변경해보면 어떨까요?

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +
final 키워드에 대해 알아보셔요

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        let selectedFruit = Juices(rawValue: orderButton.tag)!
UI에서 버튼의 배치가 달라진다면 쥬스의 rawValue도 전부 변경되어야 하지 않을까요?

2021-03-14 09:23 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        strawberryButton.layer.cornerRadius = 15
`decorateButtons`가 더 맞지 않을까요?

2021-03-14 09:24 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        strawberyBananaButton.layer.borderWidth = 1.2
UIStackView에 대해 알아보셔도 좋을 것 같아요

2021-03-15 06:33 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +    case mangoKiwiJuice = 7
각각의 태그 값을 이용해서 주스주문을 판단하기 위해서 사용했어요 😃

2021-03-15 06:33 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
바로 수정했습니다 ㅎㅎ

2021-03-15 06:37 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    var juiceMaker = JuiceMaker.shared
juiceMaker가 juiceMakerViewController안에서만 작동하기 때문에 외부에 공개될 필요가 없을 것 같습니다 ❗️

2021-03-15 06:40 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    @IBOutlet weak var kiwiLabel: UILabel!
Lable은 @IBOutlet private weak var strawberryLabel: UILabel!로 변경하였고 버튼은 커스텀버튼을 사용할 수 있기 때문에 따로 지정해주지 않았어요

2021-03-15 06:46 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    }
touchUpjuiceOrderButton 이 touchUpJuiceOrderButton 로 카멜케이스로 적용해보았습니다. 메소드를 정의하는  순서도 변경했습니다.

2021-03-15 06:49 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    func lakeStockAlert() {
부가적인 로직(Alert)을 나누기 위해서 사용하였는데 `수정`했습니다.

2021-03-15 11:19 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        kiwiLabel.text = String(stock[.kiwi]!)
`notification center`를 이용해서 주스를 만든 후 과일저장소가 변화되면 즉시 Label에 각각 반영이 되게 수정했어요 🍓🥝🥭🍋

2021-03-15 11:20 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        strawberyBananaButton.layer.borderWidth = 1.2
custom button과 custom Label을 모두 작성을 했어요 !!

2021-03-15 11:21 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    func updataStock() {
viewController 안에서만 사용하기 때문에 외부에 노출될 필요가 없는 메소드 모두를 접근제어자를 지정해줬어요

2021-03-15 15:02 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
* manageStorage 에서 딕셔너리 옵셔널 확인과 과일의 품목이 알수없는 품목이 들어올 때 inValidStock에러처리를 하려고 사용했습니다.

* addFruitStock(step3를 위한 메소드) 재고개수를 추가하고 허용되지 않는 값(음수)이 들어올 때   inValidStock에러처리

* consume 사용하는 개수가 허용되지 않는 값(현재 재고보다 적은 값)이 들어올 때   inValidStock에러처리

각각의 경우에서 예상치 못한 에러를 처리하기 위해 에러처리를 나누려고 했어요. 아직, 이 코드의 오류처리에 대해서 정확히 이해가 되지않는 거 같아요 😔

2021-03-15 15:09 UTC, Sookim18 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +
> final 개념 
 
메소드, 속성, 또는 첨자 연산은 최종 (final) 이라고 표시함으로써 ‘재정의’ 되는 것을 막을 수 있습니다. 이렇게 하려면 (final var, final func, final class func, 및 final subscript 처럼) 메소드, 속성, 또는 첨자 연산의 ‘도입자 (introducer)’ 키워드 앞에 ‘final 수정자 (modifier)’ 를 작성하면 됩니다.
‘최종’ 메소드, 속성, 또는 첨자 연산을 재정의하려는 어떤 시도도 컴파일-시간 에러라고 보고합니다. 클래스의 ‘익스텐션 (extension)’ 에서 추가한 메소드, 속성, 또는 첨자 연산도 ‘익스텐션 (extension)’ 정의 내에서 ‘최종’ 이라고 표시할 수 있습니다.
 
클래스 정의에 있는 class 키워드 앞에 ‘final 수정자’ 를 (final class 처럼) 작성함으로써 전체 클래스를 ‘최종’ 이라고 표시할 수 있습니다. ‘최종 클래스’ 로 ‘하위 클래스’ 를 만들려는 어떤 시도도 컴파일-시간 에러라고 보고합니다.

---

final 키워드를 사용하면 상속을 제한시켜서 다이나믹함(간접접근 ,간접호출)을 제거함으로써 컴파일 속도가 빨라지게 되더라구요👍

2021-03-16 11:05 UTC, Fezravien commented
## [STEP 2] 쥬스 메이커 🧃- 2

[@delmaSong](https://github.com/delmaSong)

안녕하세요 `delma`! 
Step 2 피드백 주신 부분에 대해서 고민해보고 수정했어요 👨‍💻

---

> 아래 코멘트에도 남겨놓았듯이 버튼의 태그와 쥬스들의 rawValue에 어떤 연관관계가 없어서 태그로 접근하는 방법보다는 다른 방법이 더 좋을 것 같아요. 그리고 지금도 똑같은 버튼들, 라벨들이 반복해서 사용되는데 커스텀 버튼으로 만들어보는 건 어떨까요?

- `태그`를 사용하는 방식에서 버튼의 속성값을 이용하기 위해 `currentTitle`로 수정해봤어요 
- 버튼을 꾸미는(?) decorate 메소드를 `커스텀 버튼 클래스`로 만들어서 일괄 처리했어요 
- 혹시 `커스텀 버튼 클래스`로 각각의 주문 버튼을 판단할 수 있을까요? 

> MVC 패턴을 지향한다고 하셨는데 각각이 무엇인지 설명해주실 수 있을까요? 구현하신 Juices와 FruitStock 는 MVC중 어디에 속하나요?

- Model : JuiceData, FruitStorage, JuiceMaker
- View, Controller : JuiceMakerViewController 
- 폴더를 만들어서 정리해봤어요 🤔

---


### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ⁉️

- 7개의 주문 버튼에 이벤트가 발생했을 때 하나의 액션으로 받으면 7개의 버튼을 다르게 판단할 수 있는 방법이 있을까요? 
  - 저희는 tag 방식에서 currentTitle 방식으로 수정했어요 🙂
  - 하지만 `delma`가 말씀해주시는 다른 방법이 이것이 아닌거 같아요 😓
  - 커스텀 버튼 클래스로 버튼을 일괄적 처리를 해줬는데 이 부분에서 활용할 수 있는 방법이 있을까요? 



- 에러 처리 방식 (do try catch - throw) 

  - 저희의 생각은 안쪽(?) 부터 오류가 발생하면 throw 로 던지고 catch로 받아서 또 다시 throw로 던지고 결국에 뷰 컨트롤러 까지 던진 에러가 가게되면 그곳에서 알럿처리를 할 수 있지 않을까 생각했어요
    1. 딕셔너리 옵셔널 오류발생 -> throw inValidError 
    2. consume 에서 catch  -> throw inValidError   
    3. try make에서 catch -> 알럿으로 오류 띄우기 (제고 부족, 접근 오류)
  - 한 곳에서 오류처리를 하게 해달라고 말씀해주셨는데 ... 저희가 이 오류처리 부분에서 이해가 잘 가지 않아요 😱

  

- 노티피케이션 센터 생성과 소멸 

  - 각각의 과일의 수량의 변화가 생길 시 컨트롤러에게 알려서 과일 별로 업데이트를 할 수 있도록 노티피케이션 센터를 활용했어요 
    - 생성 : viewWillAppear
    - 소멸 : viewWillDisappear
      - 초기값을 viewDidLoad에서 업데이트를 해주니 메모리를 생각해서 옵져버를 viewWillAppear에 설치 했어요. viewWillAppear는 화면 전환시 호출 되므로 소멸은  viewWillDisappear에서 하도록 했어요 (화면이 전환된 상태에서 지속적인 라벨 업데이트 막기)
      - 화면이 변환될 때 마다 노티피케이션 옵져버를 생성하고 소멸하는 방식이 괜찮을까요? 🤔

2021-03-17 13:44 UTC, delmaSong requested changes
안녕하세요 fezz, sookim!
수고 많으셨습니다 ㅎㅎㅎ

태그를 제거하셨군요 💯 편한 방법이긴 하지만 각 UI가 보여주는 값들과 전혀 연관성이 없어서 나중에 알아보기 어렵다는 단점이 있지요.. 잘하셨습니다! `커스텀 버튼 클래스`로 각각의 주문 버튼을 판단하는 방법에 대해서는 아래 코멘트로 남겨놓았으니 확인해주세요 ㅎㅎ

몽땅 한 파일에 들어있던 Juice, JuiceMaker, FruitStorage 등을 개별 파일로 나누고 폴더로 정리하니 훨씬 좋네요! 논리적인 의미에 맞게 물리적으로도 잘 분리가 된 것 같습니다 👍🏼

----

> 에러 처리 방식

메서드의 반환값으로 충분히 핸들링 가능한 부분을 전부 에러로만 던지는 것 같아서 드린 말씀이었어요.
```
딕셔너리 옵셔널 오류발생 -> throw inValidError
consume 에서 catch -> throw inValidError
``` 
라고 하셨는데 정작 코드에선 invalidError(invalidStock)이 사용되는 곳이 아무곳도 없네요.. ㅎㅎ 
에러로 던지는 부분을 가능하다면 메서드의 리턴값으로 돌려줄 수 있는지 고민해보고 그게 정 안될 때 사용자에게 에러 알럿을 띄워주는 방향으로 가봅시다. 자세한 사항은 아래 코멘트를 확인해주세요

> 노티피케이션

노티피케이션에 관한 코멘트는 아래를 확인해주세요

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/FruitStorage.swift
> +    public private(set) var initValue = 0
public private(set)과 private(set)의 차이점이 무엇인가요?

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/FruitStorage.swift
> +    public private(set) var initValue = 0
initValue가 외부로 노출되어야 하는 이유가 무엇인가요?

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/FruitStorage.swift
> +        fruits.updateValue(fruits[kind]! + amount, forKey: kind)
옵셔널 강제 해제 연산자는 되도록 사용하지 않는 습관을 들이는게 좋습니다. ! 는 앱이 크래시될 수 있는 가능성을 내포하고 있어요.

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +class JuiceMaker {
상속할 여지가 있는 것이 아니라면 final 키워드를 붙여주세요!

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
여기서 에러를 던지는 것 보다 Bool 타입의 반환값을 던지도록 하는 건 어떨까요? 이 메서드를 사용하는 쪽에서도 동일한 에러를 던지고 있는데 중복을 줄일 수 있을 것 같아요

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
이 메서드가 사용되는 곳은 어디인가요?

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
`FruitStorage`에서는 재고를 더하고 빼는 작업을 `manageStorage(fruit:amount:)`라는 한 곳에서 하고
`JuiceMaker`에서는 동일한 작업을 `consume(fruit:amount:)`과 `addFruitStock(fruit:amount:)`에서 각각 나눠서 하고있어요.
이렇게 나눈 기준이 무엇인가요?

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
쥬스를 만들기를 실패했을 때 에러를 던지기보다는 쥬스를 만들었는지의 성공 / 실패 여부를 반환값으로 전달하는 건 어떨까요?

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        return String(fruitStorage.fruits[fruit]!)
`!` 사용을 지양해주세요

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +    }
[애플 개발자 문서](https://developer.apple.com/documentation/foundation/notificationcenter/1413994-removeobserver)에 따르면 iOS 9.0 이상부터는 별도로 `removeObserver(_:)` 를 호출해주지 않아도 된다고 하네요

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +        orderSuccessAlert(selectedFruit!)
몇 줄 안되는 코드에 옵셔널 강제 언래핑 연산자가 4개나 사용됐네요..😨
if let과 guard let 사용하는 걸 귀찮아 하지 마세요

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +    }
메모리를 생각해서 viewWillAppear에 노티를 등록했다고 하셨는데, 
viewDidLoad에서는 로드된 시점 한번에만 등록되는데 화면이 보여질 때마다 매번 노티피케이션을 등록하는 게 더 비효율적이지 않을까요?

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +    }
updateLabel이나 initLabel 내부 동작은 결국 똑같은 것 같은데 줄일 수는 없을까요?

2021-03-17 13:44 UTC, delmaSong commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +    }
각 라벨에 과일 이름을 전달해주면 라벨 업데이트 하는 작업은 개별 라벨이 담당해서 하는 건 어떨까요? 그럼 노티피케이션도 필요 없을 것 같아요
현재 주문된 과일 개별 수량 라벨을 업데이트 해주기 위해서 노티를 사용하신 것 같은데 노티를 이용하지 않는 방법으로 개선해볼까요?

2021-03-17 13:47 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Error/JuiceMakerError.swift
> +    case inValidStock
카멜케이스 오류
```suggestion
    case invalidStock
```

2021-03-17 14:49 UTC, delmaSong commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +    }
값을 전달하는 방법으로 사용하신 NotificationCenter, 델리게이트 패턴, 클로져 등이 있는데 NotificationCenter를 선택하신 이유는 무엇인가요?

2021-03-18 06:26 UTC, Fezravien commented on JuiceMaker/JuiceMaker/CustomView/JuiceButton.swift
> +final class JuiceButton: UIButton {
🙆‍♂️

2021-03-18 06:27 UTC, Fezravien commented on JuiceMaker/JuiceMaker/CustomView/JuiceButton.swift
> +        super.init(coder: coder)!
xcode `required init` 자동완성을 사용해서 그렇게 된 것 같아요 
수정했어요 🙆‍♂️

2021-03-18 06:28 UTC, Fezravien commented on JuiceMaker/JuiceMaker/CustomView/JuiceButton.swift
> +    }
생각해보니 없을 것 같아서 하드코딩으로 수정했어요 🙃

2021-03-18 06:29 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/JuiceData.swift
> +    case mangoKiwiJuice = "망고 키위 쥬스 주문"
커스텀 버튼을 이용해 방식을 수정했습니다 🙂

2021-03-18 06:29 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Error/JuiceMakerError.swift
> +extension JuiceMakerError: LocalizedError{
🙆‍♂️

2021-03-18 06:31 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/FruitStorage.swift
> +    public private(set) var initValue = 0
public private(set) 
interal private(set) 
둘 다 읽기전용의 공통점과 과일 저장소의 범위를 접근을 public으로 사용했어요 🤔
initValue는 삭제했어요

2021-03-18 06:31 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/FruitStorage.swift
> +        fruits.updateValue(fruits[kind]! + amount, forKey: kind)
🙆‍♂️

2021-03-18 06:32 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +class JuiceMaker {
🙆‍♂️

2021-03-18 06:33 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
오류를 계속 던지다보니 중복되는 부분이 있는 것 같아서 수정했어요 🙆‍♂️

2021-03-18 06:35 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
사용하지 않고 있었네요 ㅠ
삭제했어요 🙆‍♂️

2021-03-18 06:42 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
[step 3]를 어렵풋이 고려하면서 재고 수정, 과일 소비를 생각했었는데 이번에 다시 개선해 볼게요 🤔
addFruitStock 삭제했어요

2021-03-18 06:43 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
중복을 최대한 피하게 오류처리를 마지막에 하고, 나머지는 성공 / 실패 여부로 반환값을 전달하도록 수정했어요  🙆‍♂️

2021-03-18 06:44 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        return String(fruitStorage.fruits[fruit]!)
지양 ! 🙆‍♂️

2021-03-18 06:46 UTC, Fezravien commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +    }
링크주신 부분을 읽어보니  🙆‍♂️

2021-03-18 06:47 UTC, Fezravien commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +        orderSuccessAlert(selectedFruit!)
네 !! 
`!` 지양할게요 🙆‍♂️

2021-03-18 06:50 UTC, Fezravien commented on JuiceMaker/JuiceMaker/ViewController/JuiceMakerViewController.swift
> +    }
여러번 화면에 따라 호출되는게 더 비효율적인 것 같아요 viewDidLoad에서 사용하도록 할게요 🙆‍♂️

> 값을 전달하는 방법으로 사용하신 NotificationCenter, 델리게이트 패턴, 클로져 등이 있는데 NotificationCenter를 선택하신 이유는 무엇인가요?

- 특별하게 선택한 이유가 없어서 좀 더 생각해보고 코드에 반영하도록 해볼게요 !

2021-03-18 06:50 UTC, Fezravien commented on JuiceMaker/JuiceMaker/Error/JuiceMakerError.swift
> +    case inValidStock
🙆‍♂️

2021-03-18 09:39 UTC, Fezravien commented
## [STEP 2] 쥬스 메이커 🧃- 3
@delmaSong 
안녕하세요 `delma`! 
Step 2 피드백 주신 부분에 대해서 고민해보고 수정했어요 👨‍💻

---


### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ⁉️

1. 오류 처리에 관해 

예를 들어, Int를 반환하는 경우 반환값을 사용하는 곳에서 옵셔널을 해제하지 않는 방법

```swift
func currentFruit(fruit: Fruits) -> Int {
        if let stock = fruitStorage.fruits[fruit] {
            return stock
        } else {
            // 어떤 값을 리턴할지
        }
}

strawberryLabel.text = String(juiceMaker.currentFruit(fruit: .strawberry))

--- 생각해 본 코드

func currentFruit(fruit: Fruits) -> Int {
        if let amount = fruitStorage.fruits[fruit] {
            return amount
        } else {
            NSLog(JuiceMakerError.invalidStock.localizedDescription)
            fatalError()
        }
   }
```

이러한 상황에서 오류 처리를 할 때 어떤 방법이 좋을지 잘 모르겠어요 🤔





2. 커스텀 라벨 활용법

>  각 라벨에 과일 이름을 전달해주면 라벨 업데이트 하는 작업은 개별 라벨이 담당해서 하는 건 어떨까요?

각 라벨에 과일 이름을 전달해 줬는데 라벨 업데이트 하는 작업을 개별 라벨에서 담당하는 부분이 해결되지 못했어요 😨

노티피케이션 센터 부분을 지우고 프로퍼티의 변화를 감지하기 위한 방법으로 델리게이트 패턴을 사용해 보려고 했어요. 과일의 값이 변화되는 부분에서 함수를 호출해주면 커스텀 라벨 클래스에서 text를 과일에 맞게 업데이트 하려고 시도를 해봤어요 🤔 

- 예시 

```swift
// JuiceData
protocol StockDelegate {
  	func currentStock(fruit: Fruits)
}

// FruitStorage
var delegate: FruitStockLabel?

func manageStorage(fruit kind: Fruits, amount: Int) {
    guard let stock = fruits[kind] else {
        return NSLog(JuiceMakerError.invalidStock.localizedDescription)
    }
    fruits.updateValue(stock + amount, forKey: kind)
    delegate.currentStock(fruit: kind)
}

// FruitStockLabel
func currentStock(fruit: Fruits) {
    self.text = "\(juiceMaker.fruitStorage.fruits[fruit]!)"
}
```

2021-03-19 15:14 UTC, delmaSong reviewed
수고하셨습니다! 이번 단계는 여기까지만 하고 아래 코멘트는 다음 단계에서 적용해보죠 ㅎㅎ 

`궁금한 점`

>오류 처리에 관해 (삭제를 하므로 해결은 되었지만, 궁금합니다 !)
예를 들어, Int를 반환하는 경우 반환값을 사용하는 곳에서 옵셔널을 해제하지 않는 방법

반환값을 사용하는 곳에서 옵셔널을 해제하지 않기 위해 에러를 던지려고 하시는 건가요?
어떤 기준으로 에러를 던질지 옵셔널을 반환할지를 판단하시는지 궁금합니다

>커스텀 라벨 활용법 (노티피케이션을 활용해서 각각의 라벨에서 관리하도록 해결했지만 델리게이트 패턴도 궁금합니다!)

오 예시 들어주신대로 코드에 바로 적용해도 되겠는데요? 뷰가 전달받은 데이터를 그냥 보여주기만 하는 역할이라서 더 좋은 것 같아요 ㅎㅎ

2021-03-19 15:14 UTC, merged

2021-03-20 09:38 UTC, Fezravien commented on JuiceMaker/JuiceMaker/CustomView/FruitStockLabel.swift
> +                                               object: nil)
`view`가 `model`에 직접적으로 관여하지 않고 `controller`에서 제어할 수 있도록 수정했어요 🙆‍♂️
- `controller`의 `viewDidLoad`에 옵져버를 사용하고 `controller`에서 `label class`를 호출

2021-03-20 09:40 UTC, Fezravien commented on JuiceMaker/JuiceMaker/CustomView/FruitStockLabel.swift
> +    private var juiceMaker = JuiceMaker.shared
이전 코멘트와 동일하게 `controller`를 거치도록 수정했어요 😀

2021-03-20 09:41 UTC, Fezravien commented on JuiceMaker/JuiceMaker/ViewController/AlertViewController.swift
> +    func lakeStockAlert(_ error: Error) {
새롭게 확장하는 부분이 아니라 ... 저희도 고민했었는데 다시 JuiceMakerViewController 에 넣었어요 🙆‍♂️