[Step1] James, Tak
yagom-academy/ios-juice-maker pull request #50
Opened 2021-03-13 12:34 UTC by Tak95

@idevjinie 
## 코드를 작성할 때 고민되었던 점:
 - struct와 class를 선택하는 기준
 - tuple과 dictionary 중 선택할 때 어느것이 더 적절한지에 대한 기준
 - 특정 메서드에서 특정 타입(딕셔너리나 튜플 등)의 프로퍼티에 접근할 때 자주 에러 발생
## 조언을 얻고싶은 부분:
 - 구현한 메서드를 더 쪼갤 필요가 있는지 (makeJuice() 메서드),
 - 앱과 연동 시 수정되어야 할 부분이 어느 부분일지..
 - extension, protocol 을 적절히 섞어서 쓰는 방법

> 신중하게 코드를 짜보려다가 몇번씩 갈아엎었는데 아직 문법적인 부분부터도 헷갈리는게 많고 어떻게 적용시켜야할지 어려운데 이럴 때 어떻게 공부하셨는지 궁금합니다.

2021-03-16 01:30 UTC, idevjinie requested changes
우선 두 분 정말 고생 많았습니다. 분명 깊게 고민한 보람이 있을 거예요. 🤞🤞

전반적으로 Swift API Design Guidelines에 따른 깔끔한 네이밍이 돋보였고, 타입과 메서드를 적절히 분리한 점도 좋았습니다.

<br>

> 구현한 메서드를 더 쪼갤 필요가 있는지 (makeJuice() 메서드)

주스를 만들기까지의 과정이 꽤나 복잡한데 간결하게 잘 구현했습니다. 다만 `makeJuice()` 메서드에 국한된 것은 아니고, `JuiceMaker` 타입 자체가 `재고를 증감하는 책임`을 가지고 있어요. 또 `makeJuice()` 메서드가 `juice.recipe`에 접근하고 있는데, 결국 레시피라는 게 주스에 필요한 과일의 재고를 차감하기 위한 용도니까 창고에서 스스로 확인하고 증감할 수 있다면 책임을 분리할 수 있습니다.

<br>

> 신중하게 코드를 짜보려다가 몇번씩 갈아엎었는데 아직 문법적인 부분부터도 헷갈리는게 많고 어떻게 적용시켜야할지 어려운데 이럴 때 어떻게 공부하셨는지 궁금합니다.

저는 프로그래밍에서 구조와 모델 설계가 가장 어렵다고 생각해요. 아마 제임스와 탁이 몇번이나 갈아엎은 원인도 설계 때문일 것 같은데, 당연한 말이지만 삽질 없이 단번에 해낼 수 있을까 싶어요. 야곰이 기능요구서에 Step 1까지만 해내도 훌륭하다고 명시한 게 괜한 말이 아니랍니다. 그리고 문법은 순서대로 한 챕터씩 해치우기 보다는 목차를 훑어보면서 어떤 문법이 있는지 먼저 살펴보세요. 그런 다음 코드를 작성하면서 필요한 문법을 자세히 보는 거죠. 캠프 초반이고 아직 프로젝트가 많이 남아있으니까 걱정하지 않아도 괜찮아요.

제가 설계 삽질을 통해 얻은 팁을 드리자면, 우선 상위 개체와 하위 개체를 구상해보세요. 예를 들면 `JuiceMaker`가 상위 개체, `Fruit`에 가까워질수록 하위 개체가 되는 거예요. 그리고 상위 개체를 먼저 작성하면서 필요할 때마다 하위 개체를 만들고 일을 시킵니다. 그럼 상위 개체가 하위 개체의 속성을 가져와 일할 필요가 없게 됩니다.

2021-03-16 01:30 UTC, idevjinie commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +
2줄...!

2021-03-16 01:30 UTC, idevjinie commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func increaseFruit(input: Fruit) throws {
입력받은 과일의 재고 수를 증가시키는 메서드니까 `increaseStock(of fruit: Fruit)`로 지으면 읽기에 더 수월할 것 같아요~

2021-03-16 01:30 UTC, idevjinie commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        fruitStorage.updateValue(stock + 1, forKey: input)
기본적으로는 수량이 1개씩 증가하고 감소하지만 옵션이 변경된다면 일일이 수정해야 해요.

2021-03-16 01:30 UTC, idevjinie commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            }
다른 `guard` 구문과 달리 `else`를 내려쓴 이유가 있나요?

2021-03-16 07:15 UTC, inwoodev commented on JuiceMaker/JuiceMaker/FruitStorage.swift
> +    static let shared = FruitStorage()
저희가 구현한 프로젝트를 기준으로 볼 때 만약 쥬스메이커 2호점을 생성하고 싱글톤을 활용한 과일저장소를 본점과 공유하게 되면 2호점에서도 본점에 있는 저장소로부터 과일을 수급하게 될 것이라 생각됩니다. 음...그럼 싱글톤을 활용하는 것이 저희 프로젝트에서 비교적 덜 적합한걸까요?

2021-03-16 07:23 UTC, inwoodev commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +}
Juice 열거형에 string type의 원시값을 넣어주었더니 더 이상 description property가 필요 없어진 것 같아서 해당 extention부분을 삭제하였습니다.

2021-03-16 08:15 UTC, Tak95 commented
**1차 피드백 반영.**
@idevjinie 
꼼꼼하게 코드 읽어주시고 피드백 주셔서 감사합니다! Jinie의 피드백에 기반해서 코드를 수정한 뒤 다시 커밋했습니다. 확인부탁드려요 :)

### 코드를 작성할 때 고민되었던 점:
 - Juice열거형의 extension을 없애고 열거형 자체에 String타입의 원시값을 할당하였는데 이 방식이 추후에 앱을 구현할 때 적절한 방법일지 궁금합니다.
 - 기존에는 데이터 저장소에는 메서드를 부여하지 않는게 비교적 안전하다고 생각했어요. 데이터는 데이터 자체만을 가지고 있는 것이 MVC디자인패턴에 부합하다고 생각해서 ViewController역할을 하는 JuiceMaker에게 모든 메서드를 할당했었는데, 이럴 경우에는 책임을 분리하는게 더 낫다고 생각하시나요??

2021-03-17 13:00 UTC, idevjinie approved these changes
몇 가지 피드백 남겼습니다. 머지할 테니 다음 스텝을 진행하면서 고려해봐도 좋고, 다음 프로젝트에서 반영해도 괜찮아요.
한 번에 소화하기 어려운 게 당연하니까 너무 고통받지 않았으면 좋겠어요. 고생 많았습니다 🏝

<br>

> Juice열거형의 extension을 없애고 열거형 자체에 String타입의 원시값을 할당하였는데 이 방식이 추후에 앱을 구현할 때 적절한 방법일지 궁금합니다.

제가 유도한 방향은 원시값과 `CustomStringConvertible` 프로토콜을 함께 적용하는 것이었어요. 직접적으로 코드를 보면 이해가 쉬울까요?

```swift
extension Juice: CustomStringConvertible {
    var description: String {
        return self.rawValue
    }
}
```

<br>

> 기존에는 데이터 저장소에는 메서드를 부여하지 않는게 비교적 안전하다고 생각했어요. 데이터는 데이터 자체만을 가지고 있는 것이 MVC디자인패턴에 부합하다고 생각해서 ViewController역할을 하는 JuiceMaker에게 모든 메서드를 할당했었는데, 이럴 경우에는 책임을 분리하는게 더 낫다고 생각하시나요??

MVC 각각의 역할을 다시 고민해보면 좋겠습니다. 모델은 앱이 무엇을 하는지 또는 데이터를 의미하고, 뷰는 화면에 표시할 UI를 의미해요. 마지막으로 뷰 컨트롤러는 데이터를 화면에 어떻게 표현할지 흐름을 제어하는 역할을 하는데, `JuiceMaker`는 어디에 해당할까요? 그리고 데이터는 데이터를 가진 저장소 자체에서 관리해야 더 안전하지 않을까요?

2021-03-17 13:01 UTC, merged

2021-03-18 06:31 UTC, inwoodev commented
2차 피드백 반영.
@idevjinie
덕분에 코드의 방향성이 더 잡힌 것 같아요. 감사드려요 :)
최대한 많은 부분 수정하려고 하였습니다. 그런데 private init 부분에 리터럴하게 담긴 값을 어떤식으로 수정을 해야할지 아직은 감이 안잡히네요. 일단 step2 진행하면서 좀 더 고민 해 봐야할 것 같아요. 그리고 init 부분 관련해서 조금 더 피드백을 주시거나 참고할 페이지 알려주시면 정말 감사하겠습니다. 항상 고생하십니다. step2도 열심히 해볼게요 :)