[STEP 2] Hailey, Kio
yagom-academy/ios-juice-maker pull request #52
Opened 2021-03-16 14:46 UTC by eunseo5355

@delmaSong 
안녕하세요 delma😃
기분 좋은 화요일 밤에 PR보내봅니다~!
~~과일쥬스가 점점 미워지네요😂~~

## 코드를 작성할 때 고민되었던 점
` JuiceMakerViewController.swift`
- 과일 재고 업데이트를 할 때 재고 변화가 있는 과일만 업데이트하는 방법
- `showOrderFailAlert()` 에서 "예" 선택시 `StockManagerViewController`로 화면 전환하는 방법

## 조언을 얻고 싶은 부분
`JuiceMaker.swift`, ` JuiceMakerViewController.swift`
- JuiceMaker 구조체에서 fruitStock() guard 구문에 오류는 던지는걸로 구현했는데 return으로 바꾸면 JuiceMakerViewController 클래스에서 updateFruitStock() do-catch 구문이 사라지게 되는데 어떤 방법이 더 좋은건지 궁금합니다!

 ` JuiceMakerViewController.swift`
- 쥬스 주문 버튼마다 따로 메서드를 구현해줬는데 실행문에서 다 똑같은 메서드가 호출돼서 혹시 하나의 메서드로 줄일 수 있을지 조언 얻고 싶어요
- @IBAction을 통해 기능을 구현했는데 각 버튼들을 @IBOutlet으로 선언해야하는 이유를 잘 모르겠습니다..! 실제로 코드 내에서는 각 버튼들의 변수를 사용하지 않았지만 없으면 오류가 나서 질문드립니다!
- Swift 문법책은 가지고 있는데 Swift UI 관련 서적도 가지고 있는 게 좋을까요? 어떤 기능들이 있는지 알지 못해서 검색할 때, 어떤 키워드로 검색해야할지 모르겠어서 질문드립니다

어떻게 하면 delma처럼 될 수 있을까요?😭

2021-03-17 14:46 UTC, delmaSong requested changes
Hailey와 Kio 수고하셨습니다! 깔끔하게 구현해주셨네요 ㅎㅎ
JuiceMaker가 들고있는 fruitInformation의 역할이 FruitStock과 중복되는 부분이 있어서 이 부분을 개선해주시면 좋을 것 같습니다.!

----
> do-catch

fruitStock()에서 에러를 던지지 않고 String?으로 반환하게 되면 사용하는 쪽에서 옵셔널 바인딩만 해주면 되니까 지금처럼 모든 케이스에 try를 붙이지 않아도 되어서 더 간결하지 않을까요?

> IBAction

여러 버튼에 하나의 동작을 하는 방법에 대해선 아래 코멘트를 확인해주세요! 
IBAction으로 기능을 구현했음에도 IBOutlet이 존재해야 하는 이유는 무엇일까요? 동작만 있다면 사용자는 무엇을 통해서 그 동작을 불러일으킬 수 있을까요? 동작만 있다면 화면에 보여지는 버튼의 크기나 색상등은 어떻게 표현할 수 있을까요?
추가적으로 SwiftUI 관련해서는 지금 당장 급한 문제는 아닌 것 같아요, 기본적인 UIKit에 대해 좀 더 익숙해진 다음에 봐도 충분할 것 같습니다! 어떤 기능들이 있는지 알지 못해 어렵다면 공식 문서를 보면서 실제로 만들어보는게 제일 좋습니다.! 보통 많이 하다보면 익숙해지는데 저같은 경우에는 UIButton을 구현해야 하는 것이라면 뷰 컨트롤러에 UIButton을 얹어놓고 `button.`을 타이핑 했을 때 에디터의 도움으로 쓸 수 있는 메서드나 프로퍼티들이 쫙 뜨니 하나하나 값을 변경해가면서 어떤 특징들이 있는지 확인했었어요 ..!

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Fruit.swift
> +final class FruitStock {
👍🏼
final 키워드의 의미는 무엇인가요 ? 👀

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    func isStockExist(_ requiredFruitAmount: Int) -> Bool {
의미가 훨씬 명확해서 좋네요 ㅎㅎ

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +
싱글톤으로 만든 이유가 무엇인가요?

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        .pineapple: FruitStock(.pineapple, 10)
기본값이 10에서 11로 바뀐다고 하면 매번 일일히 바꿔줘야겠군요
변수로 할당해서 쓰는 방법도 있어용

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
과일 재고 갯수를 던지는 거라면 count라는 어미가 들어가면 좋을것같아요 fruitStock이라니 재고째로 다 줘버리는 것 같아서

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        .strawberry: FruitStock(.strawberry, 10),
결국 이게 재고정보 아닌가요? FruitStock이 FruitTypes을 가지고 있는데 여기서 또 지정해주니 중복되는 것 같아요

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +class JuiceMakerViewController: UIViewController {
여기도 상속할 여지가 없다면 final 키워드를 붙여줍시다!

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    }
스토리보드에서 IBAction을 위해 드래그해서 뷰컨트롤러로 끌어올 때 같은 동작을 하는 버튼의 경우 전부 한 곳으로 끌어오면 된답니다!

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
여기서 꼭 에러를 던져야 하나요?

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +            }
fruitStock에서 에러를 던지지 않으면 여기서 try 하지 않아도 되겠네요

2021-03-17 14:46 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    }
값을 전달하는 방법으로  NotificationCenter나 델리게이트 패턴등 여러가지가 있는데 노티피케이션 센터를 이용하신 이유가 무엇인가요?

2021-03-18 02:37 UTC, Kioding commented on JuiceMaker/JuiceMaker/Fruit.swift
> +final class FruitStock {
final은 오버라이드를 막을 수 있는 기능으로, FruitStock 클래스가 상속될 필요가 없다고 생각하여 final을 사용하였습니다.

2021-03-18 02:46 UTC, Kioding commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +
초기에는 JuiceMakerViewController에서 인스턴스로 만들어줬었는데
StockManagerViewController에서도 사용할 것을 생각해보니 
JuiceMaker 클래스에서 싱글톤으로 만들어주면 전역 인스턴스로 활용할 수 있어 사용하였습니다!

2021-03-18 03:06 UTC, Kioding commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    }
이번 주 Notification Center에 대해 배워서 적용해보려고 했습니다. 
다른 부분을 아직 몰라 생각을 해보지 않았습니다.
말씀해주신 것처럼 KVO, Delegate 여러가지가 있더라구요! 이 점은 찾아보겠습니다 :)

2021-03-18 07:28 UTC, Kioding commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    }
```
    func fruitStockCount(of fruit: FruitTypes) -> String? {
        guard let fruitStock = fruitInformation[fruit] else { return nil }
        return String(fruitStock.stock)
    }
```
fruitStockCount으로 이름을 바꾸고 반환값을 String?으로 변경했습니다!

2021-03-18 13:08 UTC, Kioding commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        .pineapple: FruitStock(.pineapple, 10)
```
    init(_ fruit: FruitTypes, _ stock: Int = 10) {
        self.fruit = fruit
        self.stock = stock
    }
```
이렇게 변경하였습니다!

2021-03-18 13:28 UTC, Kioding commented
@delmaSong 
delma! 리뷰 감사합니다.
코멘트 주신 부분 고쳐보았는데 계속 해보았는데 어렵네요😭 😭 😭 

### 첫번째 질문
- JuiceMaker/JuiceMaker/JuiceMaker.swift
```
    var fruitInformation: [FruitTypes: FruitStock] = [
        .strawberry: FruitStock(.strawberry, 10),
```
- FruitStock안에 있는 속성을 이용하여 하려고 했는데, 속성에 접근하는 법이나, 이를 이용해서 하는 부분을 해결 못했습니다..



### 두번째 질문
- JuiceMaker/JuiceMaker/JuiceMakerViewController.swift 
- init을 통해 초기화한 값이 10이면 그대로 viewDidLoad()에서 10으로 보이는데 10 이외에 다른 숫자를 설정하게 되면 첫 숫자가 10으로 고정되어 있습니다. 초기화면을 위한 method를 만들면 바꿀 수 있는데, 기존에 있는 updateFruitStock(_ notification: Notification)를 viewDidLoad()에서 활용할 수 있을지 궁금합니다!

### 세번째 질문
- JuiceMaker/JuiceMaker/JuiceMakerViewController.swift - updateFruitStock()
- 각 과일에 해당하는 Label이 다른데 FruitTypes를 비교하지 않고 어떻게 Label.text를 바꿔야 할지 감이 잘 안옵니다ㅠㅜ 새로운 method를 또 만들어줘야할까요? 😭

2021-03-18 13:33 UTC, eunseo5355 commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +    }
오! 좋은 방법이 있었네요😄 수정해서 PR 보냈습니다!

2021-03-19 17:08 UTC, delmaSong approved these changes
수고하셨습니다! 이번 단계는 여기까지하고 아래 코멘트는 다음 스텝에서 반영해주세요~! 

`질문 주신 것들`

1. JuiceMaker에서 사용하는 fruitInformation이라는 변수의 타입이 FruitTypes을 키로 FruitStock을 밸류로 가지는 딕셔너리인데 이 때, FruitStock 내에서 FruitTypes이 중복되서 문제가 되는거니 FruitStock에서 아래와 같이 들고있는 건 어떨까요?
```swift 
final class FruitStock {
    var storage: [FruitTypes: Int] = [:]

    init(_ storage: [FruitTypes: Int]) {
        self.storage = storage
    }
...
}
```
그럼 JuiceMaker가 FruitStock째로 들고있으면 기존 사용하던 키-밸류 형식은 그대로 가져갈 수 있을 것 같기도 하네요 ㅎㅎ

2. 음 updateFruitStock(_ notification: Notification)는 인자로 notification을 받고있어서 viewDidLoad에서 바로 해당 메서드를 호출해주는 방식은 어려울 것 같아요. 그리고 노티를 활용하지 않고 재고의 초기값을 설정해주는 게 VC -> JuiceMaker -> FruitStock으로 가는 방향으로 만드는 게 데이터의 흐름을 생각했을 때 더 적절할 것 같습니다. 이부분은 1번을 수정하시면 다른 개선의 여지가 보일 것 같아요

3.  `각 과일에 해당하는 Label이 다른데 FruitTypes를 비교하지 않고` 
비교하지 말라고 코멘트를 드리지는 않았던 것 같은데 ..😅 개별 인스턴스의 값이 다르므로 라벨의 텍스트를 변경하기 위해서는 어떤 과일을 담고있는 라벨인지 인지할 수 있는 방법이 필요하겠죠?

2021-03-19 17:08 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +
싱글톤 값을 사용할 때 변수에 담아 접근하게 되면 다른 인스턴스를 참조하게 될 가능성이 생기므로 싱글톤을 사용 할 때는 JuiceMaker.shared로 직접 접근하는게 좋습니다.

2021-03-19 17:08 UTC, delmaSong commented on JuiceMaker/JuiceMaker/JuiceMakerViewController.swift
> +        }
새로운 과일이 생기면 매번 여기가 변경되어야 하지 않을까요?

2021-03-19 17:09 UTC, merged