[Step 2] Sunny, Steven
yagom-academy/ios-juice-maker pull request #56
Opened 2021-03-18 11:20 UTC by unme88

@seizze 하이디 2번째 PR 날려요 :)

## 고민한 점
Step1에 옵셔널 강제 추출 말씀해주신 부분 고민해봤습니다. [PR 리뷰 링크](https://github.com/yagom-academy/ios-juice-maker/pull/47#discussion_r595154371)

재고가 없을 때 앱이 종료된다고 하셨는데 저희가 테스트해본 결과 재고가 없어도 앱이 종료되지는 않았습니다. 저희가 강제 추출한 이유는 key의 타입이 Fruit이기 때문에 없는 키값으로 접근할 가능성이 0이라서 강제 언래핑을 사용했습니다.

이 부분에 대해서 조언 부탁드려요! ^.^

## 조언을 얻고 싶은 부분
ViewController.swift에서 보시다시피 저희가 touchUpStrawberryJuiceButton 이런 식으로 버튼 액션을 다 하나씩 만들어줬어요. 저희가 원하는 건 하나의 액션에 여러 버튼을 처리하고 싶어요. 다른 조들은 이 부분을 tag로 구현을 했는데요. 다른 리뷰어들이 tag를 사용하지 말고 다른 방법을 찾아보라고 조언하셨더라고요. 혹시 하이디라면 어떻게 구현하셨을 것 같나요? :)

2021-03-19 12:57 UTC, seizze requested changes
Sunny, Steven 수고하셨습니다~! 기능 구현을 훌륭히 잘 하셨네요 💯

> 재고가 없을 때 앱이 종료된다고 하셨는데 저희가 테스트해본 결과 재고가 없어도 앱이 종료되지는 않았습니다. 저희가 강제 추출한 이유는 key의 타입이 Fruit이기 때문에 없는 키값으로 접근할 가능성이 0이라서 강제 언래핑을 사용했습니다.

그러네요 ㅎㅎ 재고가 없을때 종료가 되진 않겠네요. 그럼 만약 키 `.strawberry`에 해당하는 value를 못 찾았을 땐 어떻게 될까요? 그런 경우가 절대로 발생할 수 없을까요?

> ViewController.swift에서 보시다시피 저희가 touchUpStrawberryJuiceButton 이런 식으로 버튼 액션을 다 하나씩 만들어줬어요. 저희가 원하는 건 하나의 액션에 여러 버튼을 처리하고 싶어요. 다른 조들은 이 부분을 tag로 구현을 했는데요. 다른 리뷰어들이 tag를 사용하지 말고 다른 방법을 찾아보라고 조언하셨더라고요. 혹시 하이디라면 어떻게 구현하셨을 것 같나요? :)

관련 코멘트 남겼으니 확인해 주세요 :)

마지막으로, 화면을 구현했을 땐 스크린샷을 코멘트에 함께 첨부하면 리뷰어의 이해도를 높여줘서 빠르고 정확한 피드백을 받을 수 있답니다~

2021-03-19 12:57 UTC, seizze commented on JuiceMaker/JuiceMaker/ViewController.swift
> +            if juiceMachine.checkStockAvailable(fruit: ingredient, requestedStock: amount) == false {
Bool 타입의 메서드는 보통 prefix로 is 또는 has 등등을 붙입니다. 여기선 isStockAvailable 정도가 되겠네요. 이에 관련된 정말 좋은 글이 있어서 공유드립니다. 변수에 관한 내용이지만, 함수에도 충분히 해당된다고 생각해요 :)

[Bool 변수 이름 제대로 짓기 위한 최소한의 영어 문법](https://soojin.ro/blog/naming-boolean-variables)

2021-03-19 12:57 UTC, seizze commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    func checkStockAndMakeJuice(_ juiceType: FruitJuice) {
외부에서 호출할 필요가 없는 메서드들 또한 private으로 선언해 주세요~

2021-03-19 12:57 UTC, seizze commented on JuiceMaker/JuiceMaker/ViewController.swift
> +        }
다른 코멘트에서 말씀드린 추상화 방법을 이용하면 여기 switch 문도 한 줄로 처리할 수 있습니다.

2021-03-19 12:57 UTC, seizze commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    }
코멘트에서 하나의 액션에 여러 버튼을 처리하고 싶다고 하셨는데요, 이런 생각이 들었다면 좋은 신호입니다. 제가 몇 번 말씀드렸던 추상화 방법의 필요성 중 하나를 직접 경험하신 것 같네요! ㅎㅎ 저번 PR의 [코멘트](https://github.com/yagom-academy/ios-juice-maker/pull/47#discussion_r593730578)에서 약간 언급된 내용입니다. 여기서는 쥬스 타입을 추상화해야겠네요~ 아래 힌트를 남겼으니 참고해 주세요.

- 추상화한 쥬스 타입을 만들고, 세분화하여 각각의 쥬스 타입들을 만듭니다.
- 버튼도 추상화하고 각 쥬스 버튼 타입들을 만듭니다.
- IBOutlet Collection을 이용해서 버튼을 배열로 관리합니다.
- 세분화된 쥬스 타입의 인스턴스를 어디서 생성할지가 중요합니다. 이 점 고민해 보시면 좋을 것 같아요 :)

도전적인 과제이지만, 앞으로 개발하면서 꼭 필요한 개념이라고 생각합니다 :)

2021-03-19 13:09 UTC, seizze commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    func checkStockAndMakeJuice(_ juiceType: FruitJuice) {
checkStock "And" MakeJuice 메서드 명에 And가 들어간다는 건 좋지는 않습니다. 좀 더 포괄해서 설명할 수 있는 이름을 고민해보면 어떨까요?

2021-03-21 01:40 UTC, unme88 commented on JuiceMaker/JuiceMaker/StockAddViewController.swift
> +    }
네 참고해서 바꿔볼게요! 감사합니다 :)

2021-03-21 01:41 UTC, unme88 commented on JuiceMaker/JuiceMaker/ViewController.swift
> -
넵 고민해볼게요!! 다음 프로젝트에 적용해보겠습니다 ^.^

2021-03-21 01:42 UTC, unme88 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    let juiceMachine: JuiceMaker = JuiceMaker(numberOfStocks: 20)
넵 다음 프로젝트 할 때 적용해볼게요!!

2021-03-21 01:44 UTC, unme88 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +            if juiceMachine.checkStockAvailable(fruit: ingredient, requestedStock: amount) == false {
return 타입이 Boolean 일때 함수명을 좀 더 명확하게 표현할 수 있게 고민해볼게요! ^.^

2021-03-21 01:45 UTC, unme88 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    func checkStockAndMakeJuice(_ juiceType: FruitJuice) {
네 private으로 선언할게요! :)

2021-06-06 05:33 UTC, closed without merging