[STEP 2] Bobby, SJ
yagom-academy/ios-juice-maker pull request #57
Opened 2021-03-18 11:45 UTC by SoKoooool

@corykim0829😻

juiceOrder🍓🍌🍍🥝🥭  메소드에서 쥬스메뉴를 변수에 담아 스위치문으로 변수의 값을 변경하는 식으로 사용했습니다
이럴 경우에 열거형을 사용하는 스타일과 다르지 않아 기본값으로 특정값을 줘야하는 현상이 발생했는데
이것을 어떻게 해결해야할지 조언 부탁드립니다.
그리고 스위치문에서 해당하는 쥬스가 없을때의 디폴트값에 예외처리를 어떻게해야 할지 감이 안잡힙니다
도와주시면 감사하겠습니다!😵

2021-03-18 15:52 UTC, corykim0829 requested changes
수고 정말 많으셨습니다!! 👏👏👏👏

리뷰 반영하고 올리실 때 이제 화면 구현이 들어가니 PR에도 스크린샷도 같이 첨부해주세요!!

화이팅입니다 💪

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    private let price: Int
let으로 하면 private까지는 꼭 할필요는 없습니다. 외부에서 값을 바꾸지 못하는게 객체지향적이기 때문이죠 참고하세요!

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                    if juiceIngredient.requiredAmount > remainedFruitStock {
여기 juiceIngredient 변수명도 중복되어서 코드가 읽기 힘든 것 같아요 ㅠ
읽기 쉽게 개선해보고, 할 수 있다면, indent를 하나 낮출 수 있다면 낮춰보세요!

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    @IBOutlet var mangoStock: UILabel!
이렇게 변수명만 보면 이 인스턴스가 어떤 역할을 하는 코드인지 알기 어렵습니다. UILabel이면 뒤에 Label을 붙이면 더욱 읽기도 쉽고 관리하기도 쉽습니다!

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    let fruitsStorageVC = UIStoryboard(name: "Main", bundle: .main).instantiateViewController(withIdentifier: "fruitsStorageVC")
UIViewController를 먼저 선언하지 말고 들어가야 할 때마다 인스턴스를 만들어서 처리해보세요!

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    @IBAction func juiceOrder(_ sender: UIButton) {
juiceOrder만 보면 명사형 함수 같습니다! 👀 함수명을 좀 더 개선해볼 수 있을 것 같아요!

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +            menu = ObjectIdentifier(MangoJuice.self)
switch로 하지 말고 각각의 버튼에 대한 IBAction을 만드는건 어떨까요?

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +        strawberryStock.text = String(juiceMaker.fruitsStorage.fruitsStock[ObjectIdentifier(Strawberry.self)]!)
여기 depth가 너무 깊다는 느낌이 드네요.
'여유'가 되신다면! juiceMaker에서 fruitStorage를 분리시켜도 좋을 것 같아요!
`fruitsStorage.fruitsStock` 에서 fruit이 중복되네요! 더 개선할 수 있을 것 같습니다.

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +        strawberryStock.text = String(juiceMaker.fruitsStorage.fruitsStock[ObjectIdentifier(Strawberry.self)]!)
그리고 `!` 사용도 없애볼 수 있을 것 같습니다! 😎

2021-03-18 15:52 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeJuice(_ juice: juiceRecipe.Key) -> Bool {
makeJuice인데 Bool 값을 반환하는게 어색하네요. 
여유가된다면 파라미터에 클로저를 이용하면 더 개선할 수 있을 것 같아요. completion 클로저로 많이 사용합니다.

2021-03-19 08:39 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/Fruit.swift
> +    private let price: Int
또 하나의 방법을 알아갑니다.
상수로 변경하여 선언하였습니다!

2021-03-19 08:41 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                    if juiceIngredient.requiredAmount > remainedFruitStock {
옵셔널 바인딩과 비교연산자 구문을 같은 라인에 작성하여 indent를 줄이고, juiceIngredient의 변수명을 ingredient로 수정하였습니다

2021-03-19 08:41 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    @IBOutlet var mangoStock: UILabel!
레이블 아웃렛 변수 네이밍에 Label을 추가하고, 버튼에도 Btn을 추가하였습니다

2021-03-19 08:43 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    let fruitsStorageVC = UIStoryboard(name: "Main", bundle: .main).instantiateViewController(withIdentifier: "fruitsStorageVC")
사용하는곳에서만 guard let으로 인스턴스 생성하여 수정했습니다!

2021-03-19 08:44 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    @IBAction func juiceOrder(_ sender: UIButton) {
orderJuice로 네이밍 변경했는데 적절할지 모르겠습니다😥

2021-03-19 08:46 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/ViewController.swift
> +            menu = ObjectIdentifier(MangoJuice.self)
처음에 버튼마다 액션 메소드를 지정해줬는데
코드의 내용이 너무 길어지는거 같아서 스위치문으로 재작성 하였습니다(기본값을 줘야하는 문제도 해결)
각 버튼마다 액션메소드를 만들어줘야 하는 이유를 알려주실수 있을까요 ?

2021-03-19 08:47 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/ViewController.swift
> +        strawberryStock.text = String(juiceMaker.fruitsStorage.fruitsStock[ObjectIdentifier(Strawberry.self)]!)
코멘트 내용대로 쥬스메이커를 통해 과일재고에 접근하는게 이상하다고 이해하여 새로이 fruitStorage의 인스턴스를 생성하여 접근하고, 옵셔널 바인딩으로 !옵셔널도 해제하였습니다

2021-03-19 08:48 UTC, SoKoooool commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    func makeJuice(_ juice: juiceRecipe.Key) -> Bool {
반환값을 제거하고 파라미터에 함수? 클로저?를 사용하였는데 맞게 사용한건지 모르겠습니다..😥

2021-03-19 08:50 UTC, SoKoooool commented
@corykim0829 😻
## [STEP 2-2] Bobby, SJ
### 리뷰 부탁드립니다!

2021-03-19 10:11 UTC, corykim0829 approved these changes
바비, SJ 수고 많으셨습니다!
👏👏👏👏👏👏

시간이 얼마남지 않았지만... 피드백 반영해서 step3 도전해보세요!! 🚀

2021-03-19 10:11 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                    completion(true, juice)
두개 이상 재료를 사용한 쥬스도 모든 재료가 정상적으로 감소되나요?

2021-03-19 10:11 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    @IBAction func orderStrawberryJuice(_ sender: UIButton) {
> 처음에 버튼마다 액션 메소드를 지정해줬는데
코드의 내용이 너무 길어지는거 같아서 스위치문으로 재작성 하였습니다(기본값을 줘야하는 문제도 해결)
각 버튼마다 액션메소드를 만들어줘야 하는 이유를 알려주실수 있을까요 ?

➡️ switch의 default처리를 안해줘도 되고, 각 버튼에 대한 IBOutlet을 또 선언해주지 않아도 됩니다. 다른 쥬스를 만드는 버튼이 추가된다면, 그 버튼에 대한 outlet 추가 + switch문 수정이 필요합니다. 각 버튼으로 처리하면 해당 버튼의 action만 추가하면 됩니다.

2021-03-19 10:11 UTC, corykim0829 commented on JuiceMaker/JuiceMaker/ViewController.swift
> +    func juiceOrderAlert(result: Bool, name: juiceName.Key) {
UIAlertController이 여기 내부에서 나뉘어서 처리되는게 아쉬운 것 같습니다.
이 함수에서 완성 alert, 실패 alert를 모두 처리하고 있네요. 더 상위 로직에서 성공, 실패 여부가 파악되니 거기에서 처리하면 어떨까요??

2021-03-19 10:21 UTC, Babywalnut commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +                    completion(true, juice)
for ingredient in juiceIngredients로
수정을했는데 뭔가 엉킨거같습니다!! 
잘 작동합니다!

2021-06-06 05:33 UTC, closed without merging