[Step2] CODA, Summer
yagom-academy/ios-juice-maker pull request #58
Opened 2021-03-19 02:41 UTC by dacodaco

안녕하세요 붱이! Step 2 PR을 보내려합니다 :) @O-O-wl 
+) 원래 2-coda 브랜치로 올려야 하지만, 저희가 main.swift 파일을 임의로 수정해버리는 바람에 2-coda 브런치가 돌아올 수 없는 강을 건너버렸습니다. 화면이 아예 실행되지 않는 fatal 오류로 인해, 고민끝에 2-summer의 브랜치로 step 2 PR을 보내게 되었습니다. 

1. 구현하고자 했던 것 
- 재고를 하나의 class에서 담당하고, 이를 다른 view controller에서 가져가 Label 에서 활용할 수 있도록 했습니다. 
- Alert 창을 실행 시, '예'를 누르면 재고추가 화면으로 이동하도록 설정하였습니다.
- 코드에서 필요없는 인스턴스를 삭제했습니다.
- 아이폰 12 미니를 기준으로 시뮬레이터를 진행했습니다!

2. 궁금했던 점
- Run을 했을 때 콘솔로그에 'screen parameter unexpected'와 같은 출력이 나오는데, 이렇게 나오는 원인을 잘 모르겠습니다. 혹시 오토레이아웃이 문제인가 싶어 오토레이아웃을 모두 지우고 진행해보았는데 콘솔창에 여전히 출력되었습니다.
- 재고를 위한 인스턴스를 static var를 활용해 구현해보았는데, 읽기 전용으로 구현했다보니, 이를 UIStepper로 입력해줄 수 없는 상황이 발생했습니다. 비록 Step 2와 관련된 내용은 아니지만, Step 3에 앞서서 어떻게 해결을 해야 좋을지 여쭤보고 싶습니다. 

항상 좋은 피드백과 애정어린 말씀 감사합니다!

2021-03-19 06:51 UTC, O-O-wl requested changes
첫 앱을 완성하셨군요 써머 코다!
축하드립니다 짝짝🎉
커밋에서 간절함이 느껴지네요 🙃

궁금한 점들이 있어서 리뷰남겨보았습니다. 
전체적으로 access control도 한번 고민해보셔도 좋을 것 같아요 
화이팅팅 하세요!

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    static var shared = FruitStock()
싱글턴 패턴을 구현하신 이유가 궁금해요

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    static var shared = FruitStock()
var 로 선언하신 이유가 있을까요?

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/StockViewController.swift
> +    @IBOutlet weak var strawStepper: UIStepper!
IBOutlet 프로퍼티들도 외부에 공개되야하는 스테이트가 아니라면 접근제한을 하는 것도 좋을 것 같아요

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/StockViewController.swift
> +    }
메소드의 선언위치도 의도가 될 수 있어요
Swift / iOS 다른 기본 메소드들은 어떠한 순서로 메소드를 정의하고 있을까요?

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/ViewController.swift
>  class ViewController: UIViewController {
네이밍을 한번 해볼까요?!

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/ViewController.swift
> +        switch JuiceMaker().canMakeJuice(of: juice) {
switch문과 if문을 사용하는 기준이 있을까요?
답이있는 건 아니지만 switch문과 Bool형의조합이  낮설게 느껴지는 것 같아요

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/ViewController.swift
> +        switch JuiceMaker().canMakeJuice(of: juice) {
showAlert마다 JuiceMaker의 새로운 인스턴스를 생성하는 이유가 있을가요?

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    static var shared = FruitStock()
static 이라는 키워드는 어떤 키워드 일까요?

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +class JuiceMaker {
내부 프로퍼티(State)가 없이 메소드(Behavior)만 있는 것 같아요
메소드를 가두어두는 네임스페이스로 JuiceMaker가 있는 것 같은데, 프로퍼티와 메소드를 스코핑한 객체를 선언하는 방법으로 구현해보는 것도 좋을 것 같아요

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +        case .mangoJuice where compareStock(amount: FruitStock.shared.mango, subtract: 3):
FruitStock.shared에 직접 접근하는 것과 초기화시점(init)에서 해당 인스턴스를 주입받는 건 어떤 차이가 있을까요?

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +// ddsd
요것도 지워도 될것 같아요!

2021-03-19 06:51 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +            return true
여러 case가 동일한 로직을 수행한다면 한번에 처리하는 방법도 있답니다.
```swift
switch condition {
  case .caseA,
           .caseB,
           .caseC,
           .caseD: 
           return true
  default: 
           return false
             
}
```

2021-03-20 23:06 UTC, dacodaco commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    static var shared = FruitStock()
기존에는 하나의 인스턴스 속에 있는 또다른 인스턴스에 접근해야 재고에 접근할 수 있었는데,
싱글턴 패턴을 활용해서 각 view controller에서 직접적으로 재고에 접근할 수 있도록 하고자 했습니다!

2021-03-22 04:10 UTC, O-O-wl commented on JuiceMaker/JuiceMaker/JuiceMaker.swift
> +    static var shared = FruitStock()
각각의 디자인 패턴은 어떤 특정 상황에서의 문제들을 해결하는 방법에서 비슷한 패턴을 가져서 정리해놓은 선조들의 지혜(?)같은 것이라고 생각해요
싱글턴패턴은 어떤 문제를 해결하고자 고안된 패턴일까요?
이름이 싱글턴 인데에는 전역적으로 직접 접근하는 의도보다는 다른 의도가 내포된 네이밍이 아닐까 싶어요 🙃

2021-06-06 05:33 UTC, closed without merging