쥬스 메이커 [Step1] Shapiro, 테리
yagom-academy/ios-juice-maker pull request #65
Opened 2021-06-08 04:26 UTC by taelee42

안녕하세요 내일날씨맑음!!
@SungPyo 

저희 조 step1진행하고 풀리퀘 드립니다. 리뷰 부탁드릴게요!
플로우차트는 이번 프로젝트에서 언급이 안되어 있고 로직이 복잡하지 않아 쓸 내용이 별로 없는거 같아서 작성하지 않고 내부 회의에서 이야기하고 넘어갔습니다!!

밑에는 고민한 부분과 궁금한 점이에요😁

### 샤피로

#### 고민한 부분

- 자료구조 : 레시피, 재료, 과일 각각 어떤 자료구조로 나타낼 것인지 고민했습니다. 각각의 과일들을 따로 인스턴스를 생성하여 관리했는데 FruitStore에서 딕셔너리 같은걸로 과일:개수 이렇게 관리 하는 것이 좋을지 지금 상태가 좋을지 궁금합니다

- 딕셔너리 사용 : 딕셔너리를 사용할때 키값을 통해 값을 접근할때 옵셔널타입으로 반환 되는 등 딕셔너리 사용을 어떻게 하면 좋을지 고민했습니다

### 테리
#### 저희가 FruitStore에는 enum을 사용하지 않고 JuiceMaker에는 enum을 사용했는데요. 저희가 생각한 방식이 맞는지 궁금합니다.

FruitStore의 경우 과일의 이름을 JuiceMaker에서만 불러오기 때문에 enum을 사용하지 않고 문자열로 간편하게 만들었고
JuickeMaker의 경우 추후에 컨트롤러에서 쥬스를 만들때 어떤 쥬스가 있는지 모를 경우에 대비해서 enum을 만들었는데요.
이 생각이 괜찮은지 궁금합니다!!

2021-06-08 14:02 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private let mango = Fruit()
이유는 남겨주셨지만 과일에 대한 부분도 Juice 처럼 enum으로 만들었으면 어떘을까 하는 생각이 듭니다.
만약 과일이 100개라면 100개의 Fruit인스턴스를 만들어야 할테고, 그만큼 가독성도 떨어지겠죠?

2021-06-08 14:23 UTC, SungPyo commented
샤피로 테리 안녕하세요!
테리는 제가 리뷰를 하는게 처음이네요. 잘부탁드려요.
현재 프로젝트 코드 자체엔 기능이 많지도 않고, 간단한 로직뿐이며 제가 남겨놓은 코멘트 하나가 다른 부분까지도 다 공통되는 부분이라... 각각의 코멘트에 중복 코멘트를 달기가 뭐해서 한군데에만 달았습니다!

우선 전체적으로 코드가 이상하다고 생각되진 않습니다! 다만 코멘트에 달아놓았듯 Fruit에 대한 클래스가 클래스로써의 역할을 하는게 맞는지 다시한번 고민해 주셨으면 좋겠어요! Fruit에 대한 부분이 Enum으로 되어있고, Store에서 갯수를 관리한다면(딕셔너리든 튜플이든..) 더 좋은 코드가 나올 수 있을 것 같습니다.

오류처리에 대한 부분은 간단하지만 따로 Error case까지 작성해서 하셨더라구요! 이 부분은 칭찬 드립니다👍

한번 더 수정된 PR을 보고싶네요! 

프로젝트를 수정하면서 비즈니스 로직에 하드코딩되는 매직넘버와 문자열은 최대한 줄이도록 노력해보세요 :)

샤피로
고민한 부분
- 자료구조 : 레시피, 재료, 과일 각각 어떤 자료구조로 나타낼 것인지 고민했습니다. 각각의 과일들을 따로 인스턴스를 생성하여 관리했는데 FruitStore에서 딕셔너리 같은걸로 과일:개수 이렇게 관리 하는 것이 좋을지 지금 상태가 좋을지 궁금합니다
ㄴ`개개인마다 생각하는 방법이 다르고, 그 여러가지 방법이 정상적으로 동작한다면 모두 옳은코드라는게 저의 생각입니다. 하지만 저는 샤피로가 생각하신 방법에 더 마음이 가네요 :)`

-딕셔너리 사용 : 딕셔너리를 사용할때 키값을 통해 값을 접근할때 옵셔널타입으로 반환 되는 등 딕셔너리 사용을 어떻게 하면 좋을지 고민했습니다
ㄴ`음.. 어떤 부분이 문제실까요? 현재 프로젝트에서 사용하신 방법에서는 전혀 문제가 일어나지 않은것 같은데 키를 통해 값에 접근할때 옵셔널 타입이여도 전혀 문제될게 없습니다. 옵셔널을 무서워 하지 마세요 :)`

테리
- 저희가 FruitStore에는 enum을 사용하지 않고 JuiceMaker에는 enum을 사용했는데요. 저희가 생각한 방식이 맞는지 궁금합니다.
FruitStore의 경우 과일의 이름을 JuiceMaker에서만 불러오기 때문에 enum을 사용하지 않고 문자열로 간편하게 만들었고
JuickeMaker의 경우 추후에 컨트롤러에서 쥬스를 만들때 어떤 쥬스가 있는지 모를 경우에 대비해서 enum을 만들었는데요.
이 생각이 괜찮은지 궁금합니다!!
ㄴ`위에 제가 답변한 부분 + 샤피로가 질문한 부분에 대한 짬뽕인것 같은데, 현재 상황에서는 어떠한 방법이든 둘 다 옳다고 생각됩니다. 현재는 프로젝트 크기가 너무 작다보니 이게 맞는지 틀린지 알 수 없는게 정상이라고 생각됩니다. 프로젝트가 좀 더 커지고, 가독성에 문제가 생길때쯤이면 굳이 질문하지 않으셔도 문제가 있다는걸 스스로 깨닫게 되는 시기가 올거에요! 현재 상황에서 제 의견을 드리자면, 저는 enum으로 만드는게 더 좋습니다 :)`

2021-06-09 17:46 UTC, SungPyo requested changes
왜 추가 pr이 안오나 했더니 제가 리뷰를 남기고 체크를 안했네요!

2021-06-10 03:21 UTC, taelee42 commented
저희가 validateEnoughStocks함수에서 검증을 하고 useStocks에서 실제로 수량을 줄이는데요.
이때 이미 검증을 validateEnoughStocks에서 했으므로 검증을 여기서 또하는게 맞는가에 대한 이야기를 나눴습니다. 

여기서 두가지 의견이 나왔었는데요.

1. 이미 검증을 했으니 또 검증하면 코드의 중복이 일어날 수 있다.
2. 지금처럼 validateEnoughStocks와 useStocks가 함께 쓰이지 않을때를 대비해서 useStocks 내부에 검증 코드를 넣어주는게 맞다.

내일날씨맑음은 어떻게 생각하시는지 궁금합니다.

검증을 했을 때 코드는 아래에 작성해봤습니다.

```swift
func useStocks(ingredients: [Fruit: Int]) throws {
        for (fruit, amount) in ingredients {
            guard let stock = fruits[fruit] else {
                throw FruitStoreError.invaildFruit
            }
            if stock < amount {
                throw FruitStoreError.outOfStock
            }
            fruits[fruit]? -= amount
        }
    }
```

2021-06-10 03:22 UTC, taelee42 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private let mango = Fruit()
말씀해주신 반영해서 enum으로 한번 작성해봤습니다!

2021-06-10 17:14 UTC, SungPyo commented
### **`추가 pr에는 우측 상단의 re-request review 를 눌러주세요!`**

궁금한 질문에 대한 답변
-
음.. 어떤 고민인지는 알것 같아요. 물론 정답은 없겠지만 저같은 경우 이런 상황에서는 함수의 역할에 대해서 다시한번 고민합니다. 
예를들어서 use~는 말 그대로 사용하겠다는 함수이고 validate~는 어떠한 유효성을 검사하겠다 라고 보여지거든요! 그래서 현재 리뷰하는 코드를 봤을때 '딱히 문제가 보이지 않는다!' 라고 말씀드릴 수 있을 것 같아요.
물론 현재 프로젝트 상황을 봤을때 코멘트로 주신 코드도 잘못된 코드는 아니라고 생각됩니다. :)
궁금증이 좀 해결되셨을까요?

총평
-
수정된 코드가 100% 마음에 드는건 아니지만 학습기간 대비 매우 괜찮다고 생각됩니다 :)
다만 아쉬운점은. 사용하지 않는 코드가 있다는 점(decreaseStock), 그리고 recipe가 [:[:]] 형태인점 이 조금 아쉬워요. 

하지만 훌륭한 코드라고 생각됩니다 

고생하셨어요

2021-06-10 17:14 UTC, merged