쥬스메이커 [Step1] Jiwon, Hosinging
yagom-academy/ios-juice-maker pull request #66
Opened 2021-06-08 06:08 UTC by jyoon54

안녕하세요 쿠마 ! @leejun6694 
Step1 PR을 보내봅니다!

하면서 저와 호싱잉이 궁금했던 점들을 정리해 보았습니다.

호싱잉:
1.Recipe Enum타입을 선언하고 연관값을 주어, 주스를 만드는 메소드에서 switch문을 통해 recipe를 확인하고, 연관값을 사용하여 재고를 확인하는 형태로 만들보았는데요. 서로 배운 것을 최대한 활용해보고자 하였는데 그걸로 인해 쉽게 만들 수 있는 것들을 오히려 어렵게 만든건 아닌가 생각이 들었습니다.

2. 접근제어자의 개념과 내용은 알겠는데 이런 프로젝트에서는 어떤 기준에 의해 사용을 해야할지, 반드시 접근제어자를 사용해야하는 것일지 궁금합니다.

지원:

접근제어를 어떻게 해야 하는지 잘 모르겠습니다.  일단은 기본인 internal 로 남겨두었는데, 이런 경우 어떤 문제가 생기는지 알고 싶습니다.

** makeJuice 함수안의 print("재고부족")은 재고가 부족한 경우의 대응이 기능상세서에 명시되지 않아 임시로 만들어 둔 것입니다. 차후에 적절한 기능으로 대체 할 예정입니다.

2021-06-09 12:39 UTC, leejun6694 requested changes
코드를 이해하는데 어려움이 없었습니다. 고생 많으셨어요 👍 
1. 배운 것을 최대한 활용해보는 노력이 보였습니다. 저도 생각이 많아지는 부분이었는데, 좀 더 정리해서 다음 리뷰 때 의견드릴게요!
2. 접근 제어자를 사용하는 사례를 찾아볼까요!?

반복되는 코드들이 있으므로, 구조에 대해 고민하는 시간을 가졌으면 해요 : )

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +	var strawberryStock: Int
strawberryStock 을 외부에서 직접 접근해서 수량을 조절할 수 있겠네요...!
우리는 왜 아래 method 들을 만든 것일까요?

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +			self.strawberryStock += number
생략할 수 있는 코드가 있네요!

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +	func addFruits(fruit:Fruit, number:Int){
현재 요구 사항은 add, consume, hasEnough 가 있지만, 추후에 기능을 추가해달라고 하면 어떨까요?
switch 문이 또 생길 것이고, case 들의 비슷한 구현도 반복될 것 같네요.
요구 사항이 그대로 코드로 옮겨졌다고 생각이 드는데, 구조에 대해 고민해보는 시간이 있었으면 좋겠습니다 : )

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
store 를 이곳저곳에서 쓰게되었다고 생각해볼까요?
1번, 2번 화면이 있다고 예를 들어볼게요! 1번 화면에서 과일이 추가가 되었고, 2번 화면에서 과일을 사용하려해요. 이 때, 우리는 어떤 것을 주의해야할까요!?

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberryJuice(let strawberryNeeded):
반복되는 코드가 있다면, 위에서 코멘트 드렸던 것처럼 구조에 대해 다시 한번 생각해볼 필요가 있을 것 같습니다 : )

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +	init(defaultStock:Int = 10) {
요구 사항 대로라면 init 도 불필요할 수 있을 것 같네요!

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
JuiceMaker 는 `struct` 고 FruitStore 는 `class` 로 구현되어 있네요!
이런 기본 구현도 잘 활용해보면 좋을 것 같아요~~!

2021-06-09 12:39 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +	case strawberryJuice(strawberryNeeded: Int = 16)
associated value 로 구현을 할 수도 있군요 👍 
저도 이부분은 좀 더 생각해보고, 다음 p/r 때 공유드릴게요ㅎㅎ!

2021-06-09 13:43 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>  class FruitStore {
fruitStore가 같은 주소를 참조하도록 신경써야 할 것 같습니다. 그런데 FruitStore는 이미 참조타입인 클래스로 구현되어 의도대로 동작하고 있다고 보아도 될까요?

2021-06-09 13:43 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +	var strawberryStock: Int
생각해보니 그렇네요... 프로퍼티들에 한해서는 접근수준을 낮춰도 될거같습니다!

2021-06-09 13:43 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +	func addFruits(fruit:Fruit, number:Int){
파라미터이름과 매끄럽게 이어지도록 add(fruit:Fruit, number: Int) 로 바꾸는것이 좋겠네요!

스위치 케이스 반복에 관해서는 생각해보지 못했는데, 고민해보니 
[Fruit:Int] 의 딕셔너리로 재고관리를 한다면 
dic[Fruit] += number 한줄로 모든 코드를 대체할 수 있겠네요!

2021-06-09 13:43 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +			self.strawberryStock += number
self가 굳이 필요하지 않군요!

2021-06-09 13:43 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +	init(defaultStock:Int = 10) {
init(defaultStock: Int) 는 저희가 매직넘버를 최대한 피하고자 약간 억지로 만들었던 생성자입니다.
생각해보니  defaultStock 상수를 선언하고 활용하는편이 더 깔끔할 것 같습니다...

2021-06-09 13:43 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        case .strawberryJuice(let strawberryNeeded):
음.. 이건 고민해봐도 어떻게 간단히 할지 생각이 잘 안나네요 ㅠㅠ Recipe 열거형부터가 문제인걸까요?

2021-06-11 03:15 UTC, leejun6694 approved these changes
피드백 내용을 알맞게 반영해주셨습니다 💯 
다만, 아직 띄어쓰기나 줄바꿈에서 불필요한 부분 또는 형식과 맞지 않는 부분들이 있는데, 좀 더 신경을 쓰면 좋을 것 같네요.
다음 스텝에선 정리된 모습으로 뵙겠습니다~~!
고생 많으셨습니다 : )

2021-06-11 03:15 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +		for (fruit, amount) in recipe.ingredients {
for 문이 굳이 두개가 아니여도 될 것 같네요...?

2021-06-11 03:15 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +	let connectedStore = FruitStore.fruitStore
네이밍을 간단하게 해도 될 것 같습니다 : )

2021-06-11 03:15 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
여기도 굳이 줄바꿈이 필요 없을 것 같네요ㅎㅎ

2021-06-11 03:16 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +			return [Fruit.strawberry: 16]
생략 가능한 코드가 있습니다 : )

2021-06-11 03:16 UTC, merged

2021-06-11 08:57 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +		for (fruit, amount) in recipe.ingredients {
for 문 하나에서 consume 함수로 수량을 변경할 경우, 필요재료가 두가지 이상일때 버그가 생길 수 있다 판단하여 위 같은 방식으로 만들었습니다.  예를들어 딸바쥬스는 딸기 10개, 바나나 1개가 필요한데, 바나나만 없는 경우 딸기의 갯수가 차감되고 주문에 실패하게 됩니다.  모든 재료가 있는지 먼저 확인하려고 for문을 두개 썼는데, 한번에 해결할 수 있다면 좀 더 생각해 보겠습니다!