[STEP1] Geon, jint
yagom-academy/ios-juice-maker pull request #68
Opened 2021-06-08 09:32 UTC by filmcanister

@YebinKim 

1. 나름대로 유지보수가 편할것 같은 방법으로 구현해봤습니다. 새로운 레시피가 생긴다면? 이라는 가정하에 과일과 메뉴에 대한 열거형을 정의하여 각 부분만 추가하면 되도록 해봤습니다.

2. 클래스와 구조체의 다른점을 이용한 코드 작성이 이루어지지 않은것 같습니다. 상속할 일도 없었고, 참조타입과 값타입을 이용한 일도 없는것 같습니다. 혹시 나중에 ViewController 에서 재고관리 View로 넘어갈때에 FruitStore를 참조타입으로 넘겨주어 과일 개수가 같이 바뀌는데 사용될지...? 모르겠습니다.

3. 2번과 관련해서 - 다음스텝에서 재고관리 view로 화면이 전환될 때에, 새로운 StorageViewController.swift 파일이 꼭 필요할 까요? 아니면 이미 존재하는 ViewController에서 두 화면을 모두 manage 하게 해도 될까요? 어떤 문제가 있을지 모르겠습니다.

4. 열거형이 두개 (Fruits, JuiceMenu) 있는데, 각자 파일을 만들어 놓는게 맞을지 궁금합니다.

5. 접근제어를 확실히 하고싶은데 어디에 뭘 쓰면 좋을지 모르겠네요. 혹시 여기에 추가하면 좋을 접근제어가 있다면 알려주세요!

2021-06-09 13:10 UTC, YebinKim requested changes
건, 진트 안녕하세요~
쥬스메이커 프로젝트 리뷰를 맡은 비비입니다 😄
깔끔한 Step1 코드 작성 잘 보았습니다-!
라인별 리뷰는 아래에서 드리고 우선 질문부터 답변 드릴게요 😊

---

### 1. 나름대로 유지보수가 편할것 같은 방법으로 구현해봤습니다. 새로운 레시피가 생긴다면? 이라는 가정하에 과일과 메뉴에 대한 열거형을 정의하여 각 부분만 추가하면 되도록 해봤습니다.

새로운 레시피 추가를 진행한다면 JuiceMenu에 case를 추가한 후 **neededFruits 프로퍼티에서 구현이 강제**되며
새로운 과일을 추가하는 경우에도 Fruits에 case를 추가한 후 **FruitStore 내부의 각 메서드에서 구현이 강제**되기 때문에 유지보수에 좋을 거 같네요!
enum 설계를 아주 훌륭히 진행하셨다고 생각합니다! 박수 드려요 😆👏



---

### 2. 클래스와 구조체의 다른점을 이용한 코드 작성이 이루어지지 않은것 같습니다. 상속할 일도 없었고, 참조타입과 값타입을 이용한 일도 없는것 같습니다. 혹시 나중에 ViewController 에서 재고관리 View로 넘어갈때에 FruitStore를 참조타입으로 넘겨주어 과일 개수가 같이 바뀌는데 사용될지...? 모르겠습니다.

현재 **생성자**를 사용하는 클래스/구조체가 없고, **상속**을 사용하는 구조가 없고, **모든 프로퍼티가 초기값을 가지기 때문에** 그 차이가 좀 더 불명확하게 다가왔을 거 같아요.
저는 상속 구조를 적용해보자면 FruitStore는 특수화 된 서브 클래스로 사용하고, Store라는 일반화 된 수퍼클래스를 적용해봄으로써 **다른 종류의 주스를 만들고자 할 때의 확장성**을 고려해볼 수 있을 거 같은데요.
같은 맥락으로 JuiceMaker 또한 다양한 종류의 Store를 적용시킬 수 있고, 어떤 Store를 적용할지에 대한 결정은 외부에서 할 수 있도록 (모델 내에서 초기화를 하지 않도록) 구현해보는 방법도 있을 거 같아요 ☺️

현재의 구현으로도 충분히 기능은 동작하겠지만, 이후의 확장성과 상속 구조의 이해를 위해 리팩토링 해보는 것도 좋을 거 같습니다!
이건 필수로 드리는 코멘트는 아니니 건과 진트가 상의해본 후 적용 진행해보시면 돼요~



---

### 3. 2번과 관련해서 - 다음스텝에서 재고관리 view로 화면이 전환될 때에, 새로운 StorageViewController.swift 파일이 꼭 필요할 까요? 아니면 이미 존재하는 ViewController에서 두 화면을 모두 manage 하게 해도 될까요? 어떤 문제가 있을지 모르겠습니다.

StorageViewController.swift 가 재고관리 View를 가질 뷰컨트롤러일까요?
서로 다른 기능을 가진 화면을 보여줘야 한다면 두 개의 ViewController를 사용하여 분리하는 편이 좋다고 생각해요.
왜냐하면 기능 단위로 뷰컨트롤러를 분리하는 것이 클래스의 캡슐화에 좋고 확장성도 좋아지기 때문이에요 😊



---

### 4. 열거형이 두개 (Fruits, JuiceMenu) 있는데, 각자 파일을 만들어 놓는게 맞을지 궁금합니다.

현재와 같이 각자 파일을 만들어둬도 문제 없다고 생각합니다!
아래 라인별 리뷰에서도 말씀드리겠지만, enum 설계를 정말 잘 하신 거 같아요 ㅎㅎ



---

### 5. 접근제어를 확실히 하고싶은데 어디에 뭘 쓰면 좋을지 모르겠네요. 혹시 여기에 추가하면 좋을 접근제어가 있다면 알려주세요!

프로퍼티와 메서드의 사용 용도를 봐야 더 명확히 확인해볼 수 있겠지만, 현재도 접근제어를 잘 사용하셨다고 생각해요~
가능하면 외부에서 사용하지 않는 프로퍼티와 메서드는 모두 private 처리를 해주는 것이 좋습니다 😊



---

Step1 고생 많으셨습니다! 😊🙌
수정이 필요한 코멘트가 많지는 않은데요.
2번 질문에 대해서는 건과 진트가 고민이 필요하실 거 같아서 일단 Request Changes로 코멘트 드릴게요~

그리고 혹시 jint만 커밋을 남긴 이유가 있을까요?

2021-06-09 13:10 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var mango = 10
내부 프로퍼티를 외부에서 쉽게 접근할 수 없도록 private 키워드를 사용해 은닉화를 잘 진행하셨군요!
프로퍼티의 변경은 메서드라는 인터페이스를 통해서만 적용되도록 구현한 점도 멋집니다 🤩

2021-06-10 07:54 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(of fruit: Fruits, amout: Int) {
오타였네요..ㅠㅜ

2021-06-10 07:54 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var strawberry = 10
그렇네요~ 디폴트 변수를  추가하였고, 이니셜라이저 추가하여 가독성을 높였습니다 :)

2021-06-10 07:55 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func makeJuice(of menu: JuiceMenu) -> Bool {
22222

2021-06-10 07:56 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Model/JuiceMenu.swift
> +    case strawberryJuice = "딸기쥬스"
![image](https://user-images.githubusercontent.com/52707151/121487166-c6e13b80-ca0c-11eb-8234-00018ba71edd.png)
문서를 정독하였는데..야곰이 이렇게 했더라구요...저희는 무죄입니다 ㅎㅎ

2021-06-10 07:57 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func minusStock(of fruit: Fruits, amout: Int) {
네이밍 가이드라인을  다시 정독해야겠군요...(subtract 사전에서 찾아본건 비밀로 해주셔용 ㅎㅎ)

2021-06-10 08:00 UTC, jgkim1008 commented
@YebinKim 

바쁘실텐데 리뷰 감사합니다~
아쉬운 부분들에 대해서는 진트와 같이 상의하여 보완해보았습니다.
클래스와 구조체는 아직 감을 못잡아서 좀더 진행해보고 말씀드리겠습니다:)

2021-06-10 13:37 UTC, YebinKim commented
리뷰 반영 확인했습니다~!
고생 많으셨어요 😊👏

클래스와 구조체 관련해서는 의문이 계속 남으시면 같이 회의실에서 얘기를 좀 나눠봐도 좋을 거 같아요!
필요하다면 언제든 말씀해주세요 🙌

2021-06-10 13:43 UTC, merged