쥬스 메이커 [STEP 1] Nala, Joey
yagom-academy/ios-juice-maker pull request #71
Opened 2021-06-09 04:15 UTC by joey-ful

@YebinKim 

## 고민 / 어려웠던 점

- enum은 보통 case 위주로 구현하고 구조가 복잡해지면 struct를 사용한다고 들었는데 구현의 어려움 때문에 Juice enum에 여러 연산 프로퍼티를 추가했습니다. enum을 Juice enum처럼 크게 만들어도 괜찮은지, 만약 아니라면 어떻게 개선하면 좋을지 궁금합니다.
- **재고를 확인하는 기능**을 기존에는 JuiceMaker의 `checkStock()`에서 구현했다가 FruitStore 클래스의`hasMoreThan()` 메서드가 해당 기능을 하도록 변경했는데 어떻게 생각하시는지 궁금합니다 :D
- 주스의 재료는 [Fruits: Int] 형태의 딕셔너리를 리턴합니다. `checkStock()` 과 `blend()` 에서 재료를 모두 확인하기 위해 딕셔너리에 반복문을 돌리는데 이 부분은 어떻게 개선하면 좋을지 고민입니다. 재료를 리턴 혹은 저장하는 더 좋은 방법은 없을까 궁금합니다.
- `checkStock()` 과 `blend()` 의 depth가 너무 깊어서 고민입니다. 과일 주스의 재료는 Fruits라는 과일 이름 enum을 리턴하는데, 저희는 FruitStore라는 과일 클래스에 접근해야하기 때문에 Fruits enum과 FruitStore 클래스를 딕셔너리로 연결했습니다. 딕셔너리의 값을 조회할 때 옵셔널 바인딩을 해야해서 depth가 더 깊어졌는데 과일명을 보고 과일 인스턴스에 바로 접근하는 더 좋은 방법이 혹시 있다면 조언 부탁드립니다!

저희 둘 다 struct랑 class에 익숙하지 않아서 전체적인 구조를 잡는데 어려움이 있었는데 많은 조언 부탁드립니다! 바쁘셨을텐데 저번에 질문 답변해주신 것도 감사합니다! 잘 부탁드립니다 🥰

2021-06-10 13:32 UTC, YebinKim requested changes
날라, 조이 안녕하세요~
쥬스메이커 프로젝트 리뷰를 맡은 비비입니다 😄
꼼꼼한 플로우차트와 UML 다이어그램 잘 봤습니다-! 👍
라인별 리뷰는 아래에서 드리고 우선 질문부터 답변 드릴게요 😊

---

### 1. enum은 보통 case 위주로 구현하고 구조가 복잡해지면 struct를 사용한다고 들었는데 구현의 어려움 때문에 Juice enum에 여러 연산 프로퍼티를 추가했습니다. enum을 Juice enum처럼 크게 만들어도 괜찮은지, 만약 아니라면 어떻게 개선하면 좋을지 궁금합니다.

enum에 필요한 연산 프로퍼티를 추가하는 것은 좋은 생각이에요!
enum과 struct의 가장 큰 차이점은 크게 두 가지가 있는데요.
1. enum은 저장 프로퍼티를 가질 수 없고, struct는 가능하다는 점
2. enum은 case가 추가될 경우 각 case에 대한 추가 구현을 강제할 수 있다는 점

이 두 가지를 고려했을 때 현재의 enum 사용은 적절하다고 생각해요 😊
다만, 2번에서 조금 더 생각해볼 점이 있다면 Fruits가 추가되었을 때 JuiceMaker의 fruits에서 딕셔너리 추가를 놓칠 수도 있을 거 같아요.
필수로 개선이 필요한 정도는 아니지만 



---

### 2. **재고를 확인하는 기능**을 기존에는 JuiceMaker의 `checkStock()`에서 구현했다가 FruitStore 클래스의`hasMoreThan()` 메서드가 해당 기능을 하도록 변경했는데 어떻게 생각하시는지 궁금합니다 :D

필요한 재고의 수를 매개변수를 통해 전달할 수 있고, FruitStore의 store 프로퍼티 은닉화를 지킬 수 있기에 FruitStore의 hasMoreThan() 메서드를 구현하는 방향이 좋은 거 같아요~!
고민을 많이 하셨음이 느껴집니다! 😊



---

### 3. 주스의 재료는 [Fruits: Int] 형태의 딕셔너리를 리턴합니다. `checkStock()` 과 `blend()` 에서 재료를 모두 확인하기 위해 딕셔너리에 반복문을 돌리는데 이 부분은 어떻게 개선하면 좋을지 고민입니다. 재료를 리턴 혹은 저장하는 더 좋은 방법은 없을까 궁금합니다.

저는 이 부분 ingredients가 하나 이상의 재료를 가질 수 있기 때문에 컬렉션 구조를 가질 수 밖에 없어서 반복문 또한 사용할 수 밖에 없다고 생각하는데요.
반복문 구문을 사용하지 않기 위해 고차함수를 사용하거나 더 복잡한 로직을 사용할 수도 있겠지만..
현재로서는 이 방법이 가장 로직을 이해하기 쉽고 간단한 구현이라고 생각됩니다 😊



---

### 4. `checkStock()` 과 `blend()` 의 depth가 너무 깊어서 고민입니다. 과일 주스의 재료는 Fruits라는 과일 이름 enum을 리턴하는데, 저희는 FruitStore라는 과일 클래스에 접근해야하기 때문에 Fruits enum과 FruitStore 클래스를 딕셔너리로 연결했습니다. 딕셔너리의 값을 조회할 때 옵셔널 바인딩을 해야해서 depth가 더 깊어졌는데 과일명을 보고 과일 인스턴스에 바로 접근하는 더 좋은 방법이 혹시 있다면 조언 부탁드립니다!

현재 fruits는 매번 옵셔널 바인딩이 필요해서 depth가 깊어지는 것에 대한 고민이 있으셨을 거 같아요.
사실 fruits는 Fruits enum의 각 case에 대한 값을 가지기 때문에 옵셔널이 아닌 것이 명확한 값이지만, 구현 상 옵셔널 강제 언래핑을 피하기 위해 매번 옵셔널 바인딩을 하게 되죠 😅

이 부분을 개선하기 위해서는 **fruits의 선언**과 **각 모델의 역할을 한 번 재점검** 해보는 것이 필요할 거 같은데요.
작성해주신 UML 다이어그램처럼 JuiceMaker는 Fruits 타입을 가지고 있지 않도록 구현해보는 것이 어떨까요?
모든 종류의 Fruits에 대해서는 FruitStore가 관리할 수 있도록 하고, JuiceMaker는 FruitStore 타입과 Juice 타입만을 가질 수 있게요! 😆
작성해주신 UML 다이어그램을 보면서 현재 작성한 모델들의 동작을 한 번 재점검 해보시면 수정 방향에 가닥이 잡히실 거 같아요! (혹시 어렵다면 다시 질문 주세요😊)



---

전체적으로 구조에 관한 고민을 많이 하셨음이 느껴지는 코드였어요!
구조체/클래스의 캡슐화와 은닉화가 잘 지켜지고 있으며,
작성하신 UML 다이어그램처럼 구조가 조금 수정된다면 각 구조체/메서드가 가져야 할 책임과 역할 또한 훌륭하게 지켜질 것이라 기대됩니다 😆👍

개선 사항이 조금 있어서 우선 Request Changes로 코멘트 드릴게요~
답변 중 궁금한 점이 있으면 언제든 질문 주세요! 😄

2021-06-11 01:38 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var ingredients: [Fruits: Int] {
재료를 [Fruits: Int] 형태의 딕셔너리로 표현했는데 옵셔널 바인딩을 해줘야하는 불편함이 있습니다.
이것을 튜플로 바꾸면 꺼내보기가 훨씬 편할 것 같은데 딕셔너리를 사용하는 것의 이점이 따로 있을까요?
튜플은 언제 사용하면 좋을지도 궁금합니다 🧐

2021-06-11 01:49 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var description: String {
- rawValue를 사용하지 않는 것이 좋다는 이야기를 들어서 CustomStringConvertible을 사용해보았는데
날라가 잘 설명을 해주셨습니다! case와 직접적으로 연관된 값은 원시값에 저장하는 것이 자연스럽고
매직넘버와 같이 저희 가 따로 의미부여한 값은 원시값보다는 다른 방식으로 하는 것이 더 좋다고 설명을 들었습니다

- 그리고 CustomStringConvertible 문서를 확인해보니 String 타입이 아닌 경우에 String을 리턴하고 싶으면 활용하는 것이라는 이야기를 보았습니다.
여기서는 원시값을 사용하는 것이 좋다고 생각되어서 비비 말씀대로 원시값을 활용해보도록 하겠습니다!!

- String 원시값을 바로 리턴하는 점에 대해 질문이 있습니다!
이 경우 바로 String rawValue를 리턴하면 되는 것인지 아니면 CustomStringConvertible을 채택해서 리턴하면 되는 것인지 궁금합니다
```swift
// 그냥 원시값 리턴
enum Juice: String {
    case strawberryJuice = "딸기 주스"
    case bananaJuice = "바나나 주스"
    
    var juiceName: String {
        return self.rawValue
    }
}

// CustomStringConvertible 채택
enum Juice: String, CustomStringConvertible {
    case strawberryJuice = "딸기 주스"
    case bananaJuice = "바나나 주스"
    
    var description: String {
        return self.rawValue
    }
}
```

2021-06-11 01:54 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func consumeStock(of number: Int) {
재고가 추가됐을 때 Stepper가 추가된 수량이 아닌 수정된 수량인 value를 반환하기 때문에
일정 수량 추가되는 기능은 필요하지 않다고 판단해 추가하지 않았습니다.
대신 updateStock() 메서드에서 바로 새 재고로 업데이트할 수 있도록 했습니다.
이 부분은 저희가 아직 뷰랑 연결짓는 부분을 완벽히 파악하지 못 해서 일정 수량 추가 기능이 필요하다면 추가해보겠습니다! 🤓

2021-06-11 02:00 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    ]
타입 어노테이션을 명시하는 기준이 궁금합니다!
- 위의 fruits처럼 타입 추론을 해야할 타입이 복잡한 경우에 어노테이션을 하고 비교적 간단한 타입은 하지 않는 것이 좋은지,
- 아니면 어떤 타입인지 코드를 읽는 사람이 바로 알기 힘든 경우에만 어노테이션을 하면 좋은지 기준이 궁금합니다
  - ex. `let stock = 10` 처럼 바로 Int인지 알 수 있으면 추론, `let stock = showStock()` 처럼 바로 알기 힘들면 어노테이션

2021-06-11 02:02 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
오오 그러네요!! 에러를 추가해보도록 하겠습니다!

2021-06-11 02:11 UTC, joey-ful commented
친절한 리뷰 감사합니다!!! 덕분에 많은 궁금증이 해결되었습니다!
피드백 해주신 부분 잘 반영해서 다시 풀리퀘 올리도록 할게요
감사합니다 🥰

---
추가 질문이 몇 가지 있습니다 🤓

1. 메서드 없이 타입 정의만 했을 때 커밋을 하는 경우 커밋의 메세지의 타입을 저희는 `feat`로 했는데 이 부분이 적절한지 궁금합니다.

2. UML 다이어그램과 FruitStore 구조에 관해 질문이 있습니다. "UML 다이어그램처럼 JuiceMaker는 Fruits 타입을 가지고 있지 않도록 구현해보는 것이 어떨까요?"라고 말씀해주셨는데 
UML에서 JuiceMaker내부에 `fruits: [Fruits: FruitStore]` 가 존재하는데 Fruits 타입을 가지고 있지 않다는 것은 어떤 의미인지 궁금합니다
혹시 화살표가 이어져있지 않아서 그런 것일까요? 🤔

3. "UML 다이어그램을 보면서 현재 작성한 모델들의 동작을 한 번 재점검 해보시면 수정 방향에 가닥이 잡히실 거 같아요!" 라고 말씀해주셨는데 UML을 보면서 모델들의 동작을 재점검한다는 것의 의미를 분명히 파악하지 못했습니다. UML은 그저 각 타입에 무엇이 들어갈지만 미리 설계해보는 용도로 만들어서 이를 코드랑 동작과 접목해서 활용할 수 있다고 생각하지 못했습니다 🤯  혹시 비비 시간이 괜찮으시다면 UML 활용 방법에 대해 설명해주실 수 있을까요? 🤩

2021-06-11 02:11 UTC, jazz-ing commented
꼼꼼하고 친절한 리뷰 감사합니다😆
리뷰해주신 것들 조이와 함께 고민해서 반영하도록 하겠습니다!
감사합니다❤️

2021-06-11 08:33 UTC, joey-ful commented
@YebinKim 
### 구현 사항
- 비비의 피드백을 반영해 FruitStore 클래스를 리팩토링 했습니다. 기존에 과일 하나만 저장하던 것을 딕셔너리 형태로 모든 과일을 저장하도록 했습니다.
- 저희가 FruitStore 메서드에서 딕셔너리를 열어보는데 실패하는 등의 경우 모두 에러를 throw하도록 처리했습니다. 그리고 해당 에러를 상위 함수로 계속 전달하도록 했습니다. ViewController에서 결국 JuiceMaker의 `order(juice: Juice)` 를 호출할 것이라 생각했고, 아랫단에서 발생한 모든 에러를 ViewController에게 전달하기 위함입니다. 굉장히 많은 에러 처리를 하게 되었고 또 에러를 forwarding하게 되었는데 이러한 구현방식이 적절한지 궁금합니다!

### 궁금한 점
#### 1. 딕셔너리 옵셔널 체이닝
- 아래 함수같은 경우 guard let으로 옵셔널 바인딩을 하지 않아도 fruitList에 있는 과일 재고를 추가하는데 문제가 없습니다.
  - 없는 과일이라면 옵셔널 체이닝때문에 아무 일도 일어나지 않는 것으로 알고 있습니다! 
- 하지만 잘못된 과일이 들어왔을 때 아무 처리를 하지 않는 것보다 에러를 던지는 것이 좋다고 생각해서 에러 처리를 해주었는데 어느 방식이 더 나은지 궁금합니다.
```swift
// 에러 처리를 해준 경우
func addStock(of fruit: Fruit, by amountToAdd: Int) throws {
    guard let _ = fruitList[fruit] else {
        throw FruitStoreError.invalidFruit
    }
    fruitList[fruit]? += amountToAdd
}

// 잘못된 과일이 들어와도 에러 처리를 하지 않는 경우
func addStock(of fruit: Fruit, by amountToAdd: Int) throws {
    fruitList[fruit]? += amountToAdd
}
```

#### 2. checkStock() 함수명과 호출 위치
원래는 checkStock()을 JuiceMaker에서 실행하는 경우 직접 재고를 확인하는 것처럼 보여서 FruitStore에서 구현하려고 했습니다.
하지만 사실 진짜 재고를 확인하는 함수는 `hasMoreThan()`이고 `checkStock()`의 경우 FruitStore에 물어보는 역할만 하는 것이어서
`checkStock()`이 JuiceMaker에 위치하는 것이 더 적절하다고 생각했습니다.
그래서 `checkStock()`이라는 메서드명을 stock과 직접적인 관련이 없어보이게 변경하려고 했는데 적절한 메서드명이 떠오르지 않았습니다🤯
- 현재 구현한 방식
```swift
// FruitStore
class FruitStore {
  func hasMoreThan(of fruit: Fruit, by requiredAmount: Int) throws {
      guard let stock = fruitList[fruit] else {
          throw FruitStoreError.invalidFruit
      }
      if stock < requiredAmount {
          throw FruitStoreError.outOfStock
      }
  }

// JuiceMaker
struct JuiceMaker {
    let fruitStore = FruitStore()
    
    func order(juice: Juice) throws {
        try checkStock(of: juice)
        try blend(juice: juice)
        print(juice)
    }
    
    func checkStock(of juice: Juice) throws {
        for (fruit, amount) in juice.ingredients {
            try fruitStore.hasMoreThan(of: fruit, by: amount)
        }
    }
}

```
- checkStore()를 FruitStore에서 구현하는 방식
```swift
// FruitStore
class FruitStore {
   func hasEnough(ingredients: [Fruit: Int]) throws {
        for (fruit, requiredAmount) in ingredients {
            guard let stock = fruitList[fruit] else {
                throw FruitStoreError.invalidFruit
            }
            if stock < requiredAmount {
                throw FruitStoreError.outOfStock
            }
        }
    }
}
// JuiceMaker
struct JuiceMaker {
    let fruitStore = FruitStore()

    func order(juice: Juice) throws {
        try fruitStore.hasEnough(ingredients: juice.ingredients)
        try blend(juice: juice)
        print(juice)
    }
```


#### 3. UIStepper기능을 코드로 구현
`reduceStock()` 메서드에서 재고가 음수값이 될 경우 에러 처리를 해주었습니다.
근데 attribute inspector에서 스테퍼의 최솟값을 0으로 정해둘 수 있다는 것을 발견했는데요,
그러면 해당 처리를 UIStepper에서 자체적으로 하니까 모델에서 따로 구현할 필요가 없을까요?
```swift
//FruitStore
func reduceStock(of fruit: Fruit, by amountToReduce: Int) throws {
    guard let stock = fruitList[fruit] else {
        throw FruitStoreError.invalidFruit
    }
    guard stock - amountToReduce >= 0 else {
        throw FruitStoreError.outOfRange
    }
    fruitList[fruit]? -= amountToReduce
}
```

---
# 친절한 리뷰 감사합니다!!!! 🥰

2021-06-14 03:02 UTC, YebinKim approved these changes
날라, 조이 안녕하세요~
굉장히 공들여 수정한 티가 나는 코드네요..!! 😆
고생 많으셨습니다-! 👏👏
우선 질문해주신 부분부터 답변 드릴게요~

---

### 1. 메서드 없이 타입 정의만 했을 때 커밋을 하는 경우 커밋의 메세지의 타입을 저희는 `feat`로 했는데 이 부분이 적절한지 궁금합니다.

커밋 타입은 함께 협업하면서 정하기 나름이라 뭐가 적절할지는 날라, 조이가 생각한 방향이 맞다고 생각해요-!
현재 카르마 스타일의 feat 타입은 "주로 사용자에게 새로운 기능이 추가되는 경우"로 보이는데요. 
타입 또한 사용자에게 필요한 기능을 나타낼 수 있으니 저도 적절하다고 생각합니다 😊



---

### 2. UML에서 JuiceMaker내부에 `fruits: [Fruits: FruitStore]` 가 존재하는데 Fruits 타입을 가지고 있지 않다는 것은 어떤 의미인지 궁금합니다.

제가 말씀드린 의미는 **JuiceMaker에서 Fruits 타입을 알지 못 하도록** 하는 것이 어떻겠냐는 뜻이었어요!
현재 UML 다이어그램에 의하면 FruitStore는 JuiceMaker로의 직접 연관 관계를 가지고 있지만, 
Fruits는 JuiceMaker로의 연관 관계를 가지고 있지 않기 때문에 설계 상 모르는 것이 좋지 않을까해서 드린 의견이었구요.
질문해주신 것 처럼 화살표가 이어져 있지 않아서 드린 말도 맞습니다 😊

UML 다이어그램을 봤을 때 Fruits의 변경이 있을 경우에는 **Fruits와 관계를 가진 FruitStore의 수정만 예상**해볼 수 있는데요.
변경 전 구조에 따르면 **Fruits에서 case가 추가되었을 때 JuiceMaker 또한 변경을 적용**해야 했기 때문에(ingredients에 초기화 값 추가) 설계와 구현에 차이가 있어 보였어요!
현재 수정하신 방향대로라면 Fruits에 case가 추가되더라도 FruitStore에만 영향을 주기 때문에 작성한 UML 다이어그램과 동일한 설계를 가져간다고 생각해요~ 수정하느라 고생 많으셨습니다! 😆👍



---

### 3. 혹시 비비 시간이 괜찮으시다면 UML 활용 방법에 대해 설명해주실 수 있을까요? 🤩

그럼요! 저도 더 물어보고 싶은 내용이 있어서 시간 잡아보면 좋겠습니다 ㅎㅎ
이번주 저녁 시간 중 만나서 얘기를 나눠봐요🤩



---

### 4. 딕셔너리 옵셔널 체이닝

에러가 발생할 수 있는 부분에 대해 꼼꼼히 생각해보셨군요!👏
저는 둘 중에 고르자면 에러를 던지는 것이 좋다고 생각해요!

에러를 던지면 사용자 입장에서 **오류 동작에 관한 피드백**을 받을 수 있게 되고,
나아가 개발자 입장에서도 **어느 지점에서 에러가 발생했는지 수집**할 수 있게 되기 때문에
에러를 던지는 편이 좋다고 생각했어요~



---

### 5. checkStock() 함수명과 호출 위치

오오 두 가지 방식을 모두 구현해보고 적절한 메서드명도 고민을 해보셨군요! ☺️
둘 중 어느 방법이 정답이라고 할 수는 없지만, 저라면 현재 조이, 날라가 구현하신 방식처럼 `checkStock(of:)` 을 JuiceMaker 구조체에 선언하는 구조를 사용할 거 같은데요.

왜냐하면 각 구조체와 클래스의 협력과 역할, 책임을 생각해보았을 때,
JuiceMaker는 **주스를 만드는 역할**을 수행하기 위해 **주스를 만들기 위한 과일을 꺼내고, 주스를 만드는 책임**을 수행하는 구조체고 
FruitStore는 **과일을 관리하는 역할**을 수행하기 위해 **가지고 있는 과일의 종류와 개수를 관리하는 책임**을 수행하는 클래스라고 생각했어요.

이때 JuiceMaker는 과일을 꺼내는 책임을 수행하기 위해 `checkStock(of:)` 메서드를 호출하지만 **종류별 과일의 개수를 확인하는 역할을 직접 수행할 수 없기 때문에 이에 대한 책임을 FruitStore로 넘기는데요**. 
책임을 넘겨 받은 FruitStore는 `hasMoreThan(of:by:)` 메서드를 호출해 재고를 확인하고 그 결과를 JuiceMaker에게 반환함으로써 협력하고 있어요.

저는 이와 같은 협력 구조를 생각한다면 `checkStock(of:)` 을 JuiceMaker 구조체에 선언하는 방식이 더 좋아 보입니다😊
설계에 있어 정답은 없기 때문에 조이와 날라가 생각하는 각 구조체, 클래스의 역할과 책임이 다르다면 구현 방식도 충분히 달라질 수 있어요-!

네이밍은 `checkStock(of:)`과 `hasMoreThan(of:by:)`이 메서드의 내용을 적절히 나타내고 있어서 따로 수정이 필요하진 않아보여요~



---

### 6. UIStepper기능을 코드로 구현

UI에서 설정을 통해 최솟값을 설정할 수 있더라도 모델 또한 최솟값에 대한 처리를 명시적으로 구현하는 게 좋다고 생각해요-!
왜냐하면 모델에서 코드로 작성해두면 **모델이 최솟값을 가진다는 것을 알 수 있고**, **수정이 쉬우며**, **모델이 잘못된 값을 가지는 것을 방지**해줄 수 있기 때문이에요.
attribute inspector에서 적용해둔 설정은 다른 사람의 코드를 볼 때도, 나중에 자신의 코드를 다시 볼 때도 놓치기 쉬워요 😅 그래서 가능하면 코드를 통해 설정을 관리하는 것을 추천드려요~



---

코멘트 드린 부분의 의도를 잘 이해하고 수정해주신 거 같아서 뿌듯합니다!!
설계와 코드 작성에 대해 고민을 많이 하셨음이 느껴졌어요~👍
이번에 질문 주신 것 처럼 의문 생기는 점이 있으면 언제든 질문 주세요!
Step1은 이대로 머지할게요! 고생 많으셨습니다 ☺️ 🙌

2021-06-14 03:03 UTC, merged

2021-06-14 03:17 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var description: String {
현재의 구현대로면 CustomStringConvertible의 채택은 필요하지 않아 보여요~
날라가 설명해주신 것 처럼 저도 case와 직접적으로 연관된 값은 원시값에 저장하는 것이 자연스럽다고 생각해서 코멘트로 말씀을 드렸었는데요.
원시값으로 String을 가지는 경우 String으로의 변환 또한 필요하지 않기 때문에 CustomStringConvertible은 불필요한 키워드이지 않을까 하는 생각 또한 드네요..! 🤔

2021-06-14 08:57 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    var description: String {
String으로의 변환이 필요하지 않으니 CustomStringConvertible을 채택하지 않고 그냥 연산 프로퍼티만 활용해서 구현해보겠습니다!

2021-06-14 09:12 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +}
앗 다시 보니 outOfRange 에러가 어떤 에러인지 불분명하네요!
저희는 재고가 최솟값 0을 넘어 음수가 되었을 때를 생각해서 만든 에러였는데 에러명을 수정해보도록 하겠습니다!
재고의 최댓값을 넘어갔을 때에도 에러를 추가하면 어떨까 싶은 생각을 해보았는데
해당 에러는 위 에러와 합치는게 좋을지 분리하면 좋을지도 고민해보도록 하겠습니다!

2021-06-14 09:13 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
오오!! 확장성을 위해서는 확실히 초기 재고를 인자로 넘겨받는게 좋겠네요!
하지만 과일 재고를 각기 다르게 초기화하고 싶은 경우는 조금 더 복잡해질 것 같네요...😭
잘 연구해보겠습니다!!

2021-06-14 09:15 UTC, joey-ful commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            try fruitStore.reduceStock(of: fruit, by: amount)
에러는 비비가 말씀해주신대로 뷰컨트롤러에서 진행할 생각으로 구현했습니다!
Step2 진행하면서 에러 처리 문제는 다시 잘 고민해보겠습니다 🤓

2021-06-14 09:19 UTC, joey-ful commented
## 비비의 상세한 설명 감사합니다!! 🤩 🥰
모호했던 부분이 비비의 설명을 듣고나니 명쾌해졌어요!
비비의 피드백 잘 반영해서 Step2 코드 진행해보겠습니다!
오늘 밤에 뵐게요 감사합니다 🙏😍