쥬스메이커 [STEP1] Jiss, Coden
yagom-academy/ios-juice-maker pull request #72
Opened 2021-06-09 06:18 UTC by ictechgy

@leejun6694
안녕하세요 쿠마! __STEP1__ 코드 작성하여 PR 날립니다. 

## 고민이 되는 점
1. FruitStore 소스파일에 changeForJuice(_:)메소드가 있습니다. 이 메소드는 먼저 쥬스로 만드려는 해당 과일이 있는지, 갯수는 충분한지 확인한 뒤에 change(numberOf:crop:isAdd:)메소드를 호출합니다. 그런데 change()메소드에서도 검증을 하는 부분이 있어 이 부분이 옳게 구현된 것인지 궁금합니다. (외부에서 change메소드를 바로 호출하는 경우도 있을 것이라고 생각하고 이렇게 만들기는 했지만 고민이 되네요)   
2. JuiceMaker 파일 내 produce메소드의 do-catch구문이 현재 오류별로 나뉘어있는데 이 부분을 줄일만한 방법이 있을까요? 아니면 이대로 두는 것도 괜찮은 걸까요?
3. JuiceMaker 소스파일 중 JuiceMenu열거형에 레시피를 반환하는 메소드 menuRecipe()가 있습니다. 이 메소드의 구현 형태가 적절한 것인지 궁금합니다. 코드 자체가 약간 하드코딩된 형식으로 되어있는 것 같아서 고민입니다.   
&nbsp;
잘부탁드려요 쿠마~ 👍

2021-06-09 17:06 UTC, leejun6694 requested changes
커밋도 잘 나눠서 올려주신 것 같고, 코드에도 고민의 흔적들이 보였습니다 👍 
코딩도 글쓰기와 같다고 생각합니다. 너무 서사가 되는 것도 문제지만, 같이 공유해서 이해해야하는 글이라면 너무 함축되는 것도 때론 어려움을 줄 수 있습니다. method 에 역할을 하나만 주고, 좀 더 풀어서 쓴다면 이해에 도움이 될 것 같습니다 ㅎㅎ

1, 2번 고민은 코드 코멘트로 답을 드렸고, 3번의 경우 더 좋은 방법이 있다면 저도 궁금할 것 같네요ㅎㅎ 너무 개의치 마시고, 발전 가능성이 더 많이 보이는 부분들을 생각하는 시간을 가지면 좋을 것 같습니다 : )

2021-06-11 05:41 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func change(numberOf number: Int, crop: Fruit, isAdd: Bool) throws {
확인해 보니 메소드를 분리하는게 좋을 것 같아서 메소드를 기능별로 최대한 분리 하였습니다!

2021-06-11 05:43 UTC, ictechgy commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    enum InventoryManagementError: Error {
넵 맨위로 옮겨두었습니다! enum을 맨 위에 작성하는 이유는 가독성때문인건가요?

2021-06-11 05:55 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private var inventory: [Fruit: Int] = Fruit.allCases.reduce([Fruit: Int]()) { bag, crop in
맞습니다 생략이 가능한 걸 깜빡했습니다. 수정 완료 했습니다.🙆🏻‍♂️

2021-06-11 05:57 UTC, ictechgy commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        bag[crop] = initialNumberOfFruits
첫번째 프로젝트를 진행했을 때 이전 기수분께서 변수명에 타입 이름이 들어가는 것은 지양하라고 하셨었거든요. 그래서 crop이라는 이름을 썼었습니다. 일단은 fruit라는 이름들로 일관성 있게 변경을 하긴 했는데 이 부분에 대해 어떤 특별한 컨벤션이 있는건가요? API Design Guideline을 봐도 잘 모르겠습니다..

2021-06-11 06:01 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                recipe = [(Fruit.strawberry, 10),(Fruit.banana, 1)]
수정 완료 했습니다!!!

2021-06-11 06:01 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            outcomeCreated =  .success(description: "\(menuName)\(JuiceMakingResult.completeOrderMessage)")
수정 완료 했습니다!!!

2021-06-11 06:03 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        } catch FruitStore.InventoryManagementError.outOfStock {
FruitStore.InventoryManagementError 의 에러 부분 메시지는 해당 열거형에서 가져와 지도록 하였습니다.

2021-06-11 06:04 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                recipe = [(Fruit.strawberry, 16)]
전부 수정 하였습니다!!

2021-06-11 06:04 UTC, ictechgy commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    let warehouse: FruitStore
해당 프로퍼티명을 fruitStore로 변경하였습니다. warehouse라고 이름지었던 이유는 위의 crop과 같습니다.!

2021-06-11 06:05 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        fileprivate func menuRecipe() -> [(requiredCrop: Fruit, requestedAmount: Int)] {
receiveRecipes() 로 수정하였습니다!

2021-06-11 06:06 UTC, hrjy6278 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    private func checkExistAndGiveBackNumber(of crop: Fruit) throws -> Int {
메소드를 분리하기가 너무 어려워, 나누지는 못하였고
메소드 네이밍을 giveBackNumberIfExist(of:) 로 변경하였습니다...

2021-06-14 16:58 UTC, leejun6694 approved these changes
리뷰 내용을 본인들의 스타일대로 여러 고심과 함께 적용해주는 모습이 인상적입니다 🥇 
step2 에서도 이유 있는 코드를 같이 고민해봤으면 좋겠네요 : )
고생 많으셨습니다!

2021-06-14 16:58 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    enum JuiceMakingResult {
Result 와 Error 를 구분해서 구현해보면 좋을 것 같네요 : )
보내드린 파일을 참고해보세요ㅎㅎ!

2021-06-14 16:58 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func changeAmount(of fruit: Fruit, to number: Int) {
추가/감소가 아닌, 해당 number 로 할당해버리는 걸까요!?

2021-06-14 16:58 UTC, merged