쥬스메이커 [STEP1] Jost, yun
yagom-academy/ios-juice-maker pull request #73
Opened 2021-06-09 07:00 UTC by YongHoonJJo

@TaeJoongYoon 

안녕하세요 tyler! STEP1 코드 작성하여 PR 날립니다. 리뷰 부탁드리겠습니다.

### 고민이 되는 점
- 에러 핸들링을 적용해 봤는데, 이런식으로 하는 것이 맞는지 궁금합니다.
- 열거형에 문자열을 저장하고 싶을때, 원시값을 이용하는 것과, CustomStringConvertible을 사용 하는 것, static let을 사용하는 것의 차이를 잘 모르겠습니다. 각 각의 장단점과 용도를 알고싶습니다!
- 화면상 재고를 더하는 버튼과 빼는 버튼이 있는데, 이를 `addStock()` 메서드 하나로 처리 하였습니다. 두개에 대해 각각 처리하는것에 대해 어느것이 더 나은지 판단이서질 않아 하나로 진행을 했는데, 이 부분에 있어서는 보통 나워서 진행하는것을 좋은지, 위에 처럼 하나로 진행하는 것도 괜찮은지에 대해 의견을 듣고 싶습니다.
- 네이밍에 대해서는 항상 고민이 많은 것 같습니다. 이부분도 같이 확인해주시면 감사하겠습니다.
- FlowChart 의 경우 기존 프로젝트는 단순히 코드만 작동시키는 방식이라 프로그램의 시작과 끝나는 지점이 명확하였는데, 이번 프로젝트에서는 화면이 존재하고, 버튼들이 존재하여, 화면에 대해 이벤트를 발생시킬수 있는(예를들어 버튼) 것을 기준으로 그려봤고, 또한 버튼을 눌렀을 때, 즉 어떤 액션이 발생했을 때, 메서드(혹은 클로저 등의 코드블럭)가 실행될 것이라 생각이 되어 그런 부분을 분리해서 표현을 해봤는데, 이런식으로 진행하는 것이 맞는지 궁금합니다.
- UML 관련, 아래의 내용을 생각하여 작성하였는데, 적절하게 표현을 한 것인지에 대해서도 확인(의견) 부탁드리겠습니다.
  - JuiceMaker 는 FruitStore 를 소유하고 있다.
  - JuiceMaker 는 Juice 열거형과 Message 열거형에 의존한다.
  - FruitStore 는 typealias, JuiceMakerError, Fruit 에 의존한다.

### 참고
- 알럿처리하는 부분에 대해서는 우선 print 로 처리 하였습니다.

2021-06-10 07:24 UTC, TaeJoongYoon commented
안녕하세요 Jost, Yun!
이번 쥬스메이커 프로젝트 리뷰를 하게된 타일러라고 합니다. 잘 부탁드립니다 :)

Step1 코드들을 봤는데 프로젝트에 대한 고민과 여러가지 시도한 흔적이 많이 보여서 좋았습니다 ㅎㅎ
먼저 남겨주신 고민에 대한 의견드려볼게요.

---
### 1. 에러 핸들링을 적용해 봤는데, 이런식으로 하는 것이 맞는지 궁금합니다.
Custom Error를 정의하고 각 error case를 만든 것과 이 Error가 발생할 수 있는 상황에 throws 구문을 이용하여 함수를 만드신 것은 훌륭합니다! 
이 함수를 호출하는 부분에서는 do catch로 적절하게 감싸주신건 좋지만 아직 catch부분에서는 각 error case에 대해 이후 상황이 정의되지 않은 것 같아요. 이건 추후 task로 봐도 되겠죠?? 😀

### 2. 열거형에 문자열을 저장하고 싶을때, 원시값을 이용하는 것과, CustomStringConvertible을 사용 하는 것, static let을 사용하는 것의 차이를 잘 모르겠습니다. 각 각의 장단점과 용도를 알고싶습니다!
열거형의 값 혹은 변수 접근에 관해서 어떻게 정의하는게 좋을 지 고민하신 부분같네요 :)
열거형의 각 case가 값을 가지는 경우는 원시값을 이용하시면 됩니다. 하지만 추가적인 값이 필요하거나 계산하는 과정이 필요하다면 열거형 내부에 property를 정의하는 방향으로 사용하면 될 것 같아요.
`CustomStringConvertible`은 해당 객체의 description을 정의할 때 필요한 protocol인데요. 열거형의 값을 표현할때는 적절하지 않은 protocol인 것 같아요. [CustomStringConvertible](https://swiftdoc.org/v4.2/protocol/customstringconvertible/) 이 문서를 한번 참조해보시면 좋을 것 같습니다.
`static let`은 상수를 표현할 때 사용한다고 생각하시면 됩니다. `Enum.case`와 `static let`이 비슷하게 닷(dot) 구문으로 접근하다보니 고민이 되신 것 같은데요. 열거형의 case는 말그대로 종류를 의미, static let 은 특정 상수를 표현할때 사용한다고 구분하시면 좋을 것 같습니다.

### 3. 화면상 재고를 더하는 버튼과 빼는 버튼이 있는데, 이를 addStock() 메서드 하나로 처리 하였습니다. 두개에 대해 각각 처리하는것에 대해 어느것이 더 나은지 판단이서질 않아 하나로 진행을 했는데, 이 부분에 있어서는 보통 나워서 진행하는것을 좋은지, 위에 처럼 하나로 진행하는 것도 괜찮은지에 대해 의견을 듣고 싶습니다.
커밋상으로는 나중에 useStock()이 추가되어서 재고를 더하는 경우/ 소모하는 경우에 대하여 각각 함수가 정의된걸로 보이는데요. 혹시 잘못봤다면  말씀해주세요. :)
만약 addStock() 함수 하나로 처리하는게 맞다면 저는 역할을 분리하는 것을 권해드리고 싶어요. 왜냐하면 함수의 네이밍과 그 역할은 이어진다고 보고 있기 때문이에요. 하지만 addStock()이 재고를 빼는 역할도 한다면 `재고를 빼는 함수를 추가`하여 역할을 분리하거나 네이밍을 `재고를 관리하는 함수`로 변경하는게 맞다고 생각합니다.

### 4. 네이밍에 대해서는 항상 고민이 많은 것 같습니다. 이부분도 같이 확인해주시면 감사하겠습니다.
저도 네이밍에 관해서는 항상 고민이 많고 어려운 부분 중 하나라고 생각해요. 저 같은 경우는 먼저 몇가지 기준을 놓고 네이밍을 하는데요.
1. [Swift API Design Guidelines - Naming](https://swift.org/documentation/api-design-guidelines/#naming) 규칙에 맞게
2. 제가 지은 네임이 해당 변수나 함수의 역할과 맞는가
3. 네이밍이 해당 역할을 과하게 가지고 있거나 부족하게 가지고 있는 경우 다시 네이밍을 진행하거나 해당 변수/함수의 역할을 분리
4. 2-3 반복..

간단하게 위와같은 과정을 거치는데요. 가장 중요하게 생각하는 것은 `네이밍은 단순하게 이름을 짓는 것이라고 생각 하지 않고 그 역할에 딱 맞는 이름을 갖는가`입니다. 네이밍이 가장 어려우면서도 다른 사람과 협업할 때 중요한 부분이니까 고민하는 시간이 오래 걸린다고 우려하지 않으셔도 돼요 🙂

### 5. FlowChart 의 경우 기존 프로젝트는 단순히 코드만 작동시키는 방식이라 프로그램의 시작과 끝나는 지점이 명확하였는데, 이번 프로젝트에서는 화면이 존재하고, 버튼들이 존재하여, 화면에 대해 이벤트를 발생시킬수 있는(예를들어 버튼) 것을 기준으로 그려봤고, 또한 버튼을 눌렀을 때, 즉 어떤 액션이 발생했을 때, 메서드(혹은 클로저 등의 코드블럭)가 실행될 것이라 생각이 되어 그런 부분을 분리해서 표현을 해봤는데, 이런식으로 진행하는 것이 맞는지 궁금합니다.
프레임 별로 구분하여 작은 행동 단위로 flow를 그려 이해하는 건 좋은 것 같아요. 문제를 해결할때는 큰 문제더라도 작은 문제로 나누어 보면 쉽게 해결가능하기 때문인데요, 이런 습관은 많이 도움이 될 것 같습니다 :)
이제는 나뉘어진 각 frame을 합쳐보면 좋을것 같아요.
우선 주문에 목적이 있고 종류는 중요하지 않은것 같아 쥬스 주문 버튼은 각 종류별로 두지말고 하나의 버튼으로 정의해도 될 것 같습니다.
또한, FlowChart에서 각 모양(Symbol)은 각자 역할이 있는데요. 이를 한번 참고해보시고 그리시면 더욱 이해도가 올라갈 것 같습니다!

### 6. UML 관련, 아래의 내용을 생각하여 작성하였는데, 적절하게 표현을 한 것인지에 대해서도 확인(의견) 부탁드리겠습니다.
혹시 UML작성하시는 법을 따로 배운적이 있으실까요??? 각 class의 관계나 class가 가지고 있는 속성, 연산 등에 대한 표현을 최대한 하시려고 노력하신것 같아요 !!!
정의해주신 UML관계에 대해서는 저도 한번 더 생각해볼게요. 
---

첫 번째 STEP인데도 불구하고 많은 기능 정의와 다양한 고민을 하셨는데 정말 고생많으셨습니다.
각 목적에 맞는 캡슐화나 기능 단위로 분리하는 작업은 잘 하신 것 같아요. 다만 **은닉화**에 대해서는 좀 더 고민해볼 필요는 있을 것 같습니다.
이외에 크게 이상한 부분은 없고 의문점이 가는 부분은 따로 코드에 코멘트를 남겨둘게요 :) 고생 많으셨습니다 😃

2021-06-10 07:30 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        let fruitList = Fruit.makeFruitList()
Fruit enum에 CaseIterable protocol을 이용함으로써 모든 case에 대한 과일 종류에 대응하게 작업하셨네요. 훌륭한 아이디어입니다 👍

2021-06-10 07:30 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +typealias JuiceRecepe = (Fruit, UInt)
Recepe는 오타인가요???

튜플로 정의하신 이유가 있을까요???

2021-06-10 07:30 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/Juice.swift
> +    }
Juice에 필요한 재료들을 내부 변수로 미리 정의하여 추가적인 실수를 피할 수 있게 설계하셨다니 좋아요 ㅎㅎ

2021-06-10 07:30 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/Message.swift
> +}
만약 Message가 쓰이는 곳이 특정 class/struct밖에 없다면 지금과 같이 따로 정의하는 것과 해당 객체 내에 정의하는 것, 어떤 차이가 있을까요??

2021-06-10 07:33 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
재료에 대한 재고관리 역할은 JuiceMaker와 FruitStore중 어느 객체가 어울릴까요???

2021-06-10 07:40 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(fruitName: Fruit, count: Int) {
함수명을 지을때는 argument와 parameter에 대한 네이밍을 적절히 하는 것이 중요하다고 생각해요.
이 함수를 호출할 때, `@@.addStock(fruitName:"", count:0)`보다 더 문맥에 맞는 네이밍을 하면 좋을 것 같습니다 :)

2021-06-10 07:48 UTC, TaeJoongYoon requested changes
첫 번째 STEP인데도 불구하고 많은 기능 정의와 다양한 고민을 하셨는데 정말 고생많으셨습니다.
각 목적에 맞는 캡슐화나 기능 단위로 분리하는 작업은 잘 하신 것 같아요. 다만 은닉화에 대해서는 좀 더 고민해볼 필요는 있을 것 같습니다.
이외에 크게 이상한 부분은 없고 의문점이 가는 부분은 따로 코드에 코멘트를 남겨둘게요 :) 고생 많으셨습니다 😃

2021-06-10 11:20 UTC, blanche37 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +typealias JuiceRecepe = (Fruit, UInt)
레시피에 필요한 정보가 어떤 과일인지와 그 과일의 갯수라고 생각을 했습니다. 단순이 이 두개의 정보만 필요했기 때문에 튜플이 가장 적합하다고 생각하였고, typealias 를 이용하여 타입을 별도로 정의하여 사용하였습니다. yun 의 경우 딕셔너리를 사용하는 것이 어떻냐고 하였는데, 딕셔너리 인스턴스보다 튜플의 인스턴스가 메모리 등 더 가볍다고 생각하였고, 딕셔너리의 어떠한 기능(특정 메서드)을 이용하는 것도 아니었으며, 딕셔너리는 키에 대해 벨류를 찾는 것이 주된 목적인데 이부분에 대해선 목적과 조금 맞지 않다고 판단하여 저(Jost)의 의견으로 튜플을 선택하여 사용하게 되었습니다.

2021-06-10 11:20 UTC, blanche37 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +typealias JuiceRecepe = (Fruit, UInt)
typealias 네이밍 오타 수정하였습니다!

2021-06-10 11:26 UTC, blanche37 commented on JuiceMaker/JuiceMaker/Model/Message.swift
> +}
클래스/구조체 내부에 열거형을 정의하게 되면, 그 클래스/구조체 내부에서만 사용가능한 열거형이 되고, 그 타입에서만  사용하는 메세지라는 것을 강조 할 수 있을 것 같습니다.

2021-06-10 12:06 UTC, blanche37 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        }
재고관리 역할는 FruitStore에서 하는 것이 바람직한 것 같습니다.  관련내용 수정했습니다.

2021-06-10 12:56 UTC, blanche37 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(fruitName: Fruit, count: Int) {
`addStock(of:count:)` 와 같이 변경했습니다. 인스턴스와의 관계를 고려해서 이렇게 지어봤는데, 의견 부탁드리겠습니다!

2021-06-10 13:14 UTC, blanche37 commented
@TaeJoongYoon 
안녕하세요. 타일러! 🥤
고민했던 부분에 대해서 자세히 답변해주셔서 감사합니다.
피드백 주신부분 수정 반영하였습니다. 이번 리뷰도 잘부탁드립니다!

- Error Case에 대해서는 추후 task로 진행할 예정입니다.
- Juice열거형에서 쥬스이름이 세부사항에 해당하지 않는 것 같아서, CustomStringConvertible프로토콜을 삭제하였습니다.
  -  원시값을 적용하였고, rawValue 를 그대로 사용하지 않고, juiceName 이라는 연산 프로퍼티를 활용한 이유는 case 의 값과 원시값의 스트링 문자열이 다르기 때문에, 원래의 case 값을 그대로 사용한다면  rawValue 를 직접 사용해도 된다고 생각하지만, 그렇지 않기 때문의 별도의 이름으로 가독성을 올리고자 연산프로퍼티를 활용하게 되었습니다.
- addStock(of:count:)과 minusStock(of:count:)메소드를 분리하였습니다.

2021-06-13 14:22 UTC, TaeJoongYoon approved these changes
안녕하세요 Jost, Yun ㅎㅎ
짧은 시간인데도 불구하고 피드백을 빠르게 흡수하시고 이렇게 작업하시다니 대단하십니다..👍
타입 설정, 네이밍, 캡슐화 등 많은 부분이 개선된게 보입니다 😊
반복되는 부분관련해서 간단히 몇 부분만 코멘트 남겨봤습니다. 두 분이 너무 잘해주셔서 확인해보시면 좀 더 나은 코드가 될 거라 믿습니다 !!
다음 스텝에서 뵙겠습니다 고생하셨습니다 ㅎㅎㅎㅎ

2021-06-13 14:22 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func getFruitStock(of fruit: Fruit) throws -> UInt {
getFruitStock 함수는 FruitStore 내부에서만 사용하는 걸로 보이는데, 앞으로도 그렇다면 접근제어자를 추가해주시는게 나을 것 같아요 !

2021-06-13 14:22 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +            fruitStocks[fruitName] = fruitStock - count
useStocks와 minusStock 내부 구현이 비슷해보이는데요! 혹시 어떤 차이점이 있을까요???
같은 구현이 반복되면 해당 구현부를 하나의 함수로 정의하는 것도 좋은 방법입니다!

2021-06-13 14:22 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +        }
현재 fruitStock을 가져오는 이부분이 FruitStore 대부분의 함수에 있는걸로 보이는데요.
이렇게 반복되는건 함수마다 작성하기보다 연산프로퍼티나 또 하나의 함수로 작성하는것이 좋아보여요 ㅎㅎ

2021-06-13 14:26 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +typealias JuiceRecepe = (Fruit, UInt)
좋습니다 ㅎㅎㅎㅎ 어떤 타입을 선택하시더라도 지금처럼 충분한 고민과 이유있는 결정이라면 어느 코드든 환영입니다 😄
딕셔너리의 키-밸류 특성, 튜플의 값묶음 특성에 대해 공부하시고 고민하신게 멋지다고 느껴집니다 ㅎㅎㅎ

2021-06-13 14:31 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func addStock(fruitName: Fruit, count: Int) {
호출하는 입장에서 좀 더 명확하고, 문장구조적으로 나아진 것 같습니다 ㅎㅎ 💯

2021-06-13 14:31 UTC, merged