쥬스 메이커 [Step2] Shapiro, Terry
yagom-academy/ios-juice-maker pull request #78
Opened 2021-06-11 07:30 UTC by shapiro711

@SungPyo 
안녕하세요 내일날씨맑음!! 저희 step2를 완성하여 풀리퀘스트 보냅니다! 잘부탁드려요 :)

## 고민한 부분
---
샤피로
1. 수량 표시해주는 label을 각각 따로 변수에 지정하여 기능을 구현했습니다. 저희가 생각한 다른 방향이 있었는데, label들을 모아주는 배열을 만들고 for문을 통해 라벨의 태그와 매칭하여 각각의 과일 수량을 감소시키는 방법이었습니다. 둘중 어느 방법이 더 좋을까요? 그리고 같은 기능을 하는 ui들이 나열 되어 있을때 어떻게 관리하는지 궁금합니다.
2. 현재 IBOutlet으로 label을 담고 있는데 강제 언래핑을 사용하였습니다. 이러한 경우에도 옵셔널 처리를 해주는 것이 좋을지 강제 언래핑을 사용해도 괜찮은지 궁금합니다.
```swift
@IBOutlet weak var strawberryStockLabel: UILabel!
@IBOutlet weak var bananaStockLabel: UILabel!
@IBOutlet weak var pineappleStockLabel: UILabel!
@IBOutlet weak var kiwiStockLabel: UILabel!
@IBOutlet weak var mangoStockLabel: UILabel!
```

테리
1. 저희가 알림창(alert) 부분을 함수로 구현했는데요. 쥬스 만들기 성공 알림은 쥬스마다 다른 알림이 떠야 하기때문에 매번 만드는게 괜찮지만 수량부족으로 인한 실패 알림은 항상 똑같은 내용으로 알림이 생성됩니다. 이때 매번 새로운 alertController를 생성하고 알림이 끝나면 사라지고를 반복하는데요. 이렇게 알림을 구현해도 괜찮은지 궁금합니다. 
다른 조의 풀리퀘를 살짝 보니 알림을 다른 클래스로 구현해서 만들어놓은 인스턴스를 계속 재활용하더라고요.  내일날씨맑음은 어떻게 생각하시는지 궁금합니다.

2021-06-12 05:42 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateStockLabels), name: isChangedFruit, object: nil)
NotificationCenter.default를 사용하신 이유가 있나요? 다른 방법은 없을까요?
이 방법을 자주 사용하는 사람도 있긴 하지만 저는 가능하면 사용하지 않는편입니다. 
이유는. 많아지면 코드를 분석하는데 방해가 되기 때문이죠.
또한 메모리에 계속 상주해 있는 아이라 특정 상황에 맞춰 지워줘야 하기도 하구요.
개인적인 생각이지만
`하나짜리 화면임에도 Notification으로밖에 데이터 교환을 할 수 없다면, 구조를 다시 생각해봐야 한다고 생각합니다.`

2021-06-12 05:57 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        guard let juiceName = sender.titleLabel?.text?.components(separatedBy: " ").first,
좋은 생각을 하신것 같지만 조금 아쉽습니다.
내가 선택했을때, 어떤 쥬스의 라벨인지 알 수 있다면 얼마나 좋을까요?

2021-06-12 06:03 UTC, SungPyo requested changes
각 코멘트로 달려고 했으나, 질문하신 부분과 겹치는 부분이 많아 전체 코멘트로 대체할게요!

기본적인 기능들이 잘 조합되어 있네요 👍

고민한 부분에 대한 답변
-
샤피로
1. 수량 표시해주는 label을 각각 따로 변수에 지정하여 기능을 구현했습니다. 저희가 생각한 다른 방향이 있었는데, label들을 모아주는 배열을 만들고 for문을 통해 라벨의 태그와 매칭하여 각각의 과일 수량을 감소시키는 방법이었습니다. 둘중 어느 방법이 더 좋을까요? 그리고 같은 기능을 하는 ui들이 나열 되어 있을때 어떻게 관리하는지 궁금합니다.
ㄴ`우선 현재 방법, for문으로 돌리는 방법 등 좋고 나쁜 방법을 제가 판단할 수 없습니다. 그 방법은 본인이 직접 느껴야 하는게 맞다고 생각되기때문에 제가 판단하기에는 조금 힘드네요!. 저의 경우에는 같은 기능을 하는 여러 Label들이 나뉘어져 있다면, UILabel을 상속받은 별도의 클래스를 만들어 사용합니다.`

2. 현재 IBOutlet으로 label을 담고 있는데 강제 언래핑을 사용하였습니다. 이러한 경우에도 옵셔널 처리를 해주는 것이 좋을지 강제 언래핑을 사용해도 괜찮은지 궁금합니다.
ㄴ`다른 분들의 생각과 저의 생각이 다를 수 있습니다. 하지만 저는 스토리보드나 Xib에서 연결하여 사용하는 IBOutlet 같은경우 강제 언래핑을 사용합니다. 그리고 사용해도 상관없다고 생각합니다.`

테리
1. 저희가 알림창(alert) 부분을 함수로 구현했는데요. 쥬스 만들기 성공 알림은 쥬스마다 다른 알림이 떠야 하기때문에 매번 만드는게 괜찮지만 수량부족으로 인한 실패 알림은 항상 똑같은 내용으로 알림이 생성됩니다. 이때 매번 새로운 alertController를 생성하고 알림이 끝나면 사라지고를 반복하는데요. 이렇게 알림을 구현해도 괜찮은지 궁금합니다. 다른 조의 풀리퀘를 살짝 보니 알림을 다른 클래스로 구현해서 만들어놓은 인스턴스를 계속 재활용하더라고요. 내일날씨맑음은 어떻게 생각하시는지 궁금합니다.
ㄴ `제가 겪은 실무의 프로젝트들 에서는 각각 다른 에러의 의 알림이 적게는 수십개부터 많개는 100개이상이 존재합니다. 그 많은걸 다 함수로 한다면 어떤 문제가 발생할까요? 그리고 그 문제를 어떻게 해결하는게 좋을까요? 답변은 이렇게 대체하겠습니다!`

빠른속도로 이정도 까지 결과물이 나온것으로 보아 리팩토링을 반복하고 계속 고민하다 보면 좋은 코드가 나올 수 있을것 같다는 생각이 드네요.  리뷰를 바탕으로 한번 더!

2021-06-14 03:11 UTC, shapiro711 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateStockLabels), name: isChangedFruit, object: nil)
저희가 kvo, NotificationCenter, label에 표기되는 FruitStore의 재고 수량의 업데이트를 버튼을 누를때 작동되는 방식 3가지를 생각했었습니다.  스탭3에서 재고 수량을 조절하는 화면이 추가적으로 있어서 NotificationCenter를 최종적으로 선택하였는데 어떤 방법이 괜찮을까요?

2021-06-14 07:44 UTC, shapiro711 commented
@SungPyo
안녕하세요 내일날씨맑음! 리뷰해주신 부분을 생각해보고 수정해보았습니다!
저희가 변경한 내용입니다.

+ 알림창 부분 수정
기존의 함수에서 알림을 생성하고 보여주는것 까지 했었는데, 각각의 알림을 프로퍼티로 가지고 사용할 수 있도록 변경하였습니다.

2021-06-14 15:49 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateStockLabels), name: isChangedFruit, object: nil)
현재  재고를 사용하는 뷰 한개와 재고를 수정하는 뷰 한개. 총 2개의 뷰가 있습니다.
저라면 공통으로 사용하는 Manager를 만들어 사용하겠습니다.
위에서 말씀드렸듯 Notification 은 많으면 많아질수록 코드를 읽는데 불편함이 있으며, (다 추척해야 하기 때문)
메모리 관리를 소홀히 하면 메모리 누수의 원인이 되기도 합니다.

2021-06-14 15:54 UTC, SungPyo approved these changes
앗 아아...  고민과 시도는 매우 좋았습니다만 결과물이 제가 생각한 그것이 아니네요. 
저런 컨트롤러를 전역에 여러개 만들어놓게 되면 무슨 문제가 발생할까요?
100개의 함수가 100개의 변수로 변경 되었을 뿐 그 외의 큰 차이점은 발견할 수 없었습니다.
꼭 인스턴스를 생성해두지 않아도 됩니다. 그때그때 생성해서 보여줘도 된다는 뜻이죠!

한번 더 수정된 step2를 보고싶지만. 정리가 그래도 나름 잘 되어있어서 step2도 후딱후딱 넘어가고
step3가 올라오면 step1~step3 까지의 전체 리팩토링을 진행해 봅시다 :)

고생하셨습니다!

2021-06-14 15:54 UTC, merged