쥬스 메이커 [STEP 1] Soll, EHD
yagom-academy/ios-juice-maker pull request #79
Opened 2021-06-11 07:45 UTC by soll4u

@TaeJoongYoon

안녕하세요! 스텝1을 완료해서 PR을 보내드립니다 :)
딕셔너리 형태로 레시피를 받는 거에 도움 주셔서 감사합니다!

---

## 코드를 작성할 때 고민되었던 점
- 딕셔너리를 통해 과일의 재고와 레시피를 관리하다보니, 값이나 키를 통해서 사용할 때마다 변수나 상수에 할당해서 사용할 수 밖에 없더라구요. 이것이 최선인지..? 궁금합니다.
- 모델에서 이렇게 함수가 많아져도 되는지 궁금합니다. 컨트롤러에 있어도 될 것 같은 로직들이 모델에 있는 것 같아서요.
- JuiceMaker.swift에 21번째줄에서 [.strawberry : 16] 같이 하나하나 써주는 것보다 함수화시켜서 쓰면 깔끔할 것이라고 생각해서 수정해보려고 했어요.  예를들어
``` swift
func prepareIngredient(과일종류:Fruitstore.Fruit, 필요갯수: Int) {
return[Fruitstore.Fruit : Int]
} 
```
이런식으로 해서 각 케이스별로 해당 함수를 소환하고 과일종류, 필요갯수 매개변수에 이름이랑 숫자만 쓰면 보기 편하니까요.
그런데 생각해보니 필요한 과일이 두개일 때는 [과일1:x , 과일2:y] 이런식으로 표현하기가 어려운 거예요. 
혹시 이런식으로 명료하게 레시피를 리턴할 수 있는 방법이 없을까요?

---
## 해결이 되지 않은 점
- 아직 에러 처리를 넣지 않았는데요, 다음 스텝에 포함할 것 같습니다.

---
## 조언을 얻고 싶은 부분
- static 변수를 이용해 storage의 값을 전역에서 사용한다는 것은 알았는데, 사용이 잘 된 것 같은지 궁금합니다.
- JuiceMaker와 FruitStore를 struct와 class로 사용했는데, 이렇게 사용하지 않아도 큰 문제가 없을 것 같아요. 그럴땐 기본으로 뭘 사용해야 할까요?

확인부탁드릴게요! 감사합니다.

2021-06-13 14:42 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let defaultStock: UInt = 10
`defaultStock`은 FruitStore에서만 사용되는 값으로 보이는데 `static`으로 사용하지 않아도 충분히 값을 표현할 수 있을것 같아요 ㅎㅎ

`storage`도 마찬가지로 FruitStore에서만 사용되는걸로 보여서 마찬가지로 수정해도 좋을것 같아요!


이 때, 은닉화와 관련해서 접근 제어자를 추가해주시면 더욱 좋을 것 같아요 ㅎㅎㅎ

2021-06-13 14:42 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    }
과일의 종류를 enum으로 관리하는 것 좋은 선택으로 보입니다 ㅎㅎㅎ

2021-06-13 15:26 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
`JuiceMaker`는 쥬스를 만드는 객체인데 레시피재료 같은 경우는 `JuiceMaker`와 `Menu`중 어디서 관리하는게 좋을까요??

2021-06-13 15:26 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
와.. 함수 내의 변수명이 정말 깔끔하네요 💯💯
변수 네이밍이 간결하면서도 필요한 정보를 잘 담고 있는것 같아요! 너무 좋습니다 ㅎㅎ

`isJuiceAvailable(menu:)`는 전달받은 Menu에 대해 만들수 있는 재료가 충분한 지 검사하는 함수로 보이는데요 ㅎㅎ
재고 관리는 어느 객체에서 맡으면 좋은 지 좀 더 고민해보시면 좋을 것 같아요!

2021-06-13 15:26 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
`neededIngredientCount`는 미사용 변수로 보이는데 혹시 나중을 위해 남겨둔 변수일까요?!

`recipeNumber`와 `storageNumber`의 네이밍은 좀 더 의미있게 바꾸면 좋을 것 같아요 ㅎㅎ
그리고 recipeNumber와 storageNumber를 구하는 과정을 좀 더 줄일 수 있을 것 같아요. `orderedJuiceRecipe`와 `neededIngredient`의 관계를 다시 한번 살펴보면 힌트가 될것 같습니다!

2021-06-13 15:28 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let fruitStore = FruitStore()
`JuiceMaker`는 `FruitStore`를 소유하기 때문에 이렇게 함수 내 지역변수로 선언하는 것 보다 객체 내에 선언해서 사용하는 것이 좀더 유용할것 같아요 :)

2021-06-13 17:06 UTC, TaeJoongYoon commented
안녕하세요 Soll, EHD ~ 리뷰를 맡은 타일러라고 합니다 :)
한 주간 많은 걸 공부하시고 주어진 조건에 따라 개발하는게 쉽지 않으셨을텐데 너무 고생많으셨어요 ㅎㅎㅎ
두 분이 밤늦게까지 회의하시고 다양한 시도를 하시는 모습이 너무 보기 좋았습니다.. 당사자들은 힘드셨겠지만요🥲
설령 시간이 오래걸리더라도 다양한 시도를 통해 새로운 경험과 스스로의 답을 이끌어낼수 있고 그것을 계기로 더 나아가고 또 새로운 시도를 할 수 있다고 생각해요.
한번에 많은 요구사항들을 개발하고 이뤄내기는 힘든 법인것 같아요. 주어진 문제가 당장 해결하기 어렵다면 작은 문제로 구분하고 하나씩 천천히 해결하는것도 좋은 방법이라고 생각합니다!

그렇다면 이제 하나씩 살펴볼게요!

---
# 코드를 작성할 때 고민되었던 점

- 딕셔너리를 통해 과일의 재고와 레시피를 관리하다보니, 값이나 키를 통해서 사용할 때마다 변수나 상수에 할당해서 사용할 수 밖에 없더라구요. 이것이 최선인지..? 궁금합니다.

 => 과일의 재고와 레시피를 관리하는데에 가장 중요하고 고민스러운 점이 **과일의 종류** 와 **과일의 갯수**일 거에요. 이 때문에 솔과 애드도 딕셔너리를 활용하여 `과일의 종류를 키`로 `과일의 갯수를 값`으로 하셨는데요. 이렇게 되면 해당 딕셔너리에 과일의 종류가 키값으로 존재한다면 빠르게 해당 과일의 갯수에 접근할 수 있지만, 만약 키값이 없다면 접근에 실패하는 경우가 될 거에요. 이를 보완하기 위해서라면 과일의 모든 종류가 키값으로 들어가 있어야겠죠???? 이건 `CaseIterable` protocol을 한번 살펴보시는걸 추천드릴게요 :)
딕셔너리가 아니라면 튜플 타입을 이용할수도 있을거에요. 과일의 종류과 갯수를 한 튜플 타입으로 묶어서도 활용이 가능합니다. 어떤 방식이 나은지는 두 분이 상의를 통해 결정하시면 될것 같아요 ㅎㅎ 다만 모든 결정에는 근거가 있어야 한답니다! 🤔

- 모델에서 이렇게 함수가 많아져도 되는지 궁금합니다. 컨트롤러에 있어도 될 것 같은 로직들이 모델에 있는 것 같아서요.

 => 지금 구현하는 부분이 MVC중에 모델에 해당하는 부분이어서 모델에만 함수가 많아지고 있어요. 이때문에 그렇게 느끼시는것 같은데 당연한 상황입니다! 저희는 지금 과일, 쥬스 등과 관련된 모델에 대한 타입정의, 기능구현 등을 하고있어요 ㅎㅎ 컨트롤러는 이후 STEP2에서 뷰를 구현하면서 같이 모델과 연결되는 부분을 자연스레 구현하게 될거에요 :) 걱정하지 않으셔도 됩니다. 잘하고 있으세요 ㅎㅎ

- JuiceMaker.swift에 21번째줄에서 [.strawberry : 16] 같이 하나하나 써주는 것보다 함수화시켜서 쓰면 깔끔할 것이라고 생각해서 수정해보려고 했어요. 예를들어
```swift
func prepareIngredient(과일종류:Fruitstore.Fruit, 필요갯수: Int) {
return[Fruitstore.Fruit : Int]
} 
```
이런식으로 해서 각 케이스별로 해당 함수를 소환하고 과일종류, 필요갯수 매개변수에 이름이랑 숫자만 쓰면 보기 편하니까요.
그런데 생각해보니 필요한 과일이 두개일 때는 [과일1:x , 과일2:y] 이런식으로 표현하기가 어려운 거예요.
혹시 이런식으로 명료하게 레시피를 리턴할 수 있는 방법이 없을까요?

 => 현재 구상중인 아이디어로는 하나의 짝밖에 받지를 못하겠네요. 그렇다면 Collection Type으로 받으면 어떨까요???
앞서 말씀드린 튜플형태의 배열로 받거나 현재처럼 딕셔너리 형태로 받으면 해결이 가능할것으로 보입니다 :)

---
# 해결이 되지 않은 점

- 아직 에러 처리를 넣지 않았는데요, 다음 스텝에 포함할 것 같습니다.
 
 => 네 좋습니다! 아직 넣지 않았더라도 어느 상황에 에러가 발생할 수 있는지에 대한 아이디어는 정해두시는게 좋을것 같아요 ㅎㅎ

---
# 조언을 얻고 싶은 부분
- static 변수를 이용해 storage의 값을 전역에서 사용한다는 것은 알았는데, 사용이 잘 된 것 같은지 궁금합니다.
 
 => static 변수를 어떻게 사용하느냐에 따라 다르지만, 쥬스메이커 프로젝트 STEP1에서는 아직 굳이 사용할 이유는 없어보여요. 간단하게 `JuiceMaker`는 `FruitStore`를 소유하고 있는 구조기 때문에 리뷰에 적어드린대로 내부에 객체로 가지고 있고 그 객체를 활용하면 되는 구조에요. `storage`같은 경우도 FruitStore내부에서만 사용가능하게 만들수 있기때문에 이번 STEP에서는 static 변수사용을 지양하는쪽으로 개발해보면 어떨까 해요! 이와 관련되서는 **캡슐화**와 **은닉화** 그리고 **static 변수가 어떻게 활용되고 있는가**에 대해서 찾아보시고 고민해보시면 좋을 것 같습니다 :)

- JuiceMaker와 FruitStore를 struct와 class로 사용했는데, 이렇게 사용하지 않아도 큰 문제가 없을 것 같아요. 그럴땐 기본으로 뭘 사용해야 할까요?

 => 애플 가이드라인에 따르면 기본은 struct를 사용하지만, 몇가지 상황에 따라서는 struct와 class를 적절히 사용해야한다고 말하고 있습니다. 해당 링크는 아래 첨부할게요 :)

[Choosing between struct and class](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)

---

먼저 고민이 되는 부분에 대해서 간략하게 제 생각을 전달드렸어요.
저번 회의와 마찬가지로 아직 과일의 재고관리에 대한 부분에서 어려움을 느끼시는 것 같은데 위의 내용을 토대로 좀 더 고민해보시면 쉽게 풀어내실수 있을거라 믿습니다 :)

코드를 살펴보니 커밋과 네이밍에서 놀랐는데요. 기능단위로 세세하게 나누어서 커밋하신 점은 아주 훌륭합니다 💯
이렇게 되면 다른사람이 보기에도 편하고 기능단위로 커밋이 작성되었기 때문에 이후에 잘못된 부분을 발견했다면 수정하거나 되돌리기도 쉽습니다.
기능을 세세하게 나눈다고 커밋이 많아질까봐 두려워하지 마시고 지금처럼 어떤 기능이 필요한지 정하고 해당 기능만을 구현하는 데에 집중해서 커밋을 작성해주시면 좋을것 같아요 😀😀
그리고 코드 코멘트에도 적었지만 네이밍이 훌륭합니다. 변수명이 길어지더라도 그 변수만이 가지고 있는 역할에 대해서 잘 네이밍하신것 같아요.
저는 변수/함수명은 항상 그 역할에 맞는 것이 좋은 네이밍이라 생각하고 역할에 벗어나거나 과한 역할을 가지는 네이밍은 지양해야 한다고 생각하는데 아주 잘 네이밍을 해주신것 같습니다 👍

코드에 대한 부분은 코드 라인별로 코멘트를 적어두었고, 이에 더해 전체적으로 **캡슐화**와 **은닉화**에 대해서 좀 더 신경써주시면 좋을 것 같아요 :) 한 주 동안 너무 고생많으셨고 새로운 주도 화이팅입니다 !!

2021-06-13 17:08 UTC, TaeJoongYoon requested changes
안녕하세요 Soll, EHD ~ 리뷰를 맡은 타일러라고 합니다 :)
한 주간 많은 걸 공부하시고 주어진 조건에 따라 개발하는게 쉽지 않으셨을텐데 너무 고생많으셨어요 ㅎㅎㅎ
두 분이 밤늦게까지 회의하시고 다양한 시도를 하시는 모습이 너무 보기 좋았습니다.. 당사자들은 힘드셨겠지만요🥲
설령 시간이 오래걸리더라도 다양한 시도를 통해 새로운 경험과 스스로의 답을 이끌어낼수 있고 그것을 계기로 더 나아가고 또 새로운 시도를 할 수 있다고 생각해요.
한번에 많은 요구사항들을 개발하고 이뤄내기는 힘든 법인것 같아요. 주어진 문제가 당장 해결하기 어렵다면 작은 문제로 구분하고 하나씩 천천히 해결하는것도 좋은 방법이라고 생각합니다!

그렇다면 이제 하나씩 살펴볼게요!

---
# 코드를 작성할 때 고민되었던 점

- 딕셔너리를 통해 과일의 재고와 레시피를 관리하다보니, 값이나 키를 통해서 사용할 때마다 변수나 상수에 할당해서 사용할 수 밖에 없더라구요. 이것이 최선인지..? 궁금합니다.

 => 과일의 재고와 레시피를 관리하는데에 가장 중요하고 고민스러운 점이 **과일의 종류** 와 **과일의 갯수**일 거에요. 이 때문에 솔과 애드도 딕셔너리를 활용하여 `과일의 종류를 키`로 `과일의 갯수를 값`으로 하셨는데요. 이렇게 되면 해당 딕셔너리에 과일의 종류가 키값으로 존재한다면 빠르게 해당 과일의 갯수에 접근할 수 있지만, 만약 키값이 없다면 접근에 실패하는 경우가 될 거에요. 이를 보완하기 위해서라면 과일의 모든 종류가 키값으로 들어가 있어야겠죠???? 이건 `CaseIterable` protocol을 한번 살펴보시는걸 추천드릴게요 :)
딕셔너리가 아니라면 튜플 타입을 이용할수도 있을거에요. 과일의 종류과 갯수를 한 튜플 타입으로 묶어서도 활용이 가능합니다. 어떤 방식이 나은지는 두 분이 상의를 통해 결정하시면 될것 같아요 ㅎㅎ 다만 모든 결정에는 근거가 있어야 한답니다! 🤔

- 모델에서 이렇게 함수가 많아져도 되는지 궁금합니다. 컨트롤러에 있어도 될 것 같은 로직들이 모델에 있는 것 같아서요.

 => 지금 구현하는 부분이 MVC중에 모델에 해당하는 부분이어서 모델에만 함수가 많아지고 있어요. 이때문에 그렇게 느끼시는것 같은데 당연한 상황입니다! 저희는 지금 과일, 쥬스 등과 관련된 모델에 대한 타입정의, 기능구현 등을 하고있어요 ㅎㅎ 컨트롤러는 이후 STEP2에서 뷰를 구현하면서 같이 모델과 연결되는 부분을 자연스레 구현하게 될거에요 :) 걱정하지 않으셔도 됩니다. 잘하고 있으세요 ㅎㅎ

- JuiceMaker.swift에 21번째줄에서 [.strawberry : 16] 같이 하나하나 써주는 것보다 함수화시켜서 쓰면 깔끔할 것이라고 생각해서 수정해보려고 했어요. 예를들어
```swift
func prepareIngredient(과일종류:Fruitstore.Fruit, 필요갯수: Int) {
return[Fruitstore.Fruit : Int]
} 
```
이런식으로 해서 각 케이스별로 해당 함수를 소환하고 과일종류, 필요갯수 매개변수에 이름이랑 숫자만 쓰면 보기 편하니까요.
그런데 생각해보니 필요한 과일이 두개일 때는 [과일1:x , 과일2:y] 이런식으로 표현하기가 어려운 거예요.
혹시 이런식으로 명료하게 레시피를 리턴할 수 있는 방법이 없을까요?

 => 현재 구상중인 아이디어로는 하나의 짝밖에 받지를 못하겠네요. 그렇다면 Collection Type으로 받으면 어떨까요???
앞서 말씀드린 튜플형태의 배열로 받거나 현재처럼 딕셔너리 형태로 받으면 해결이 가능할것으로 보입니다 :)

---
# 해결이 되지 않은 점

- 아직 에러 처리를 넣지 않았는데요, 다음 스텝에 포함할 것 같습니다.
 
 => 네 좋습니다! 아직 넣지 않았더라도 어느 상황에 에러가 발생할 수 있는지에 대한 아이디어는 정해두시는게 좋을것 같아요 ㅎㅎ

---
# 조언을 얻고 싶은 부분
- static 변수를 이용해 storage의 값을 전역에서 사용한다는 것은 알았는데, 사용이 잘 된 것 같은지 궁금합니다.
 
 => static 변수를 어떻게 사용하느냐에 따라 다르지만, 쥬스메이커 프로젝트 STEP1에서는 아직 굳이 사용할 이유는 없어보여요. 간단하게 `JuiceMaker`는 `FruitStore`를 소유하고 있는 구조기 때문에 리뷰에 적어드린대로 내부에 객체로 가지고 있고 그 객체를 활용하면 되는 구조에요. `storage`같은 경우도 FruitStore내부에서만 사용가능하게 만들수 있기때문에 이번 STEP에서는 static 변수사용을 지양하는쪽으로 개발해보면 어떨까 해요! 이와 관련되서는 **캡슐화**와 **은닉화** 그리고 **static 변수가 어떻게 활용되고 있는가**에 대해서 찾아보시고 고민해보시면 좋을 것 같습니다 :)

- JuiceMaker와 FruitStore를 struct와 class로 사용했는데, 이렇게 사용하지 않아도 큰 문제가 없을 것 같아요. 그럴땐 기본으로 뭘 사용해야 할까요?

 => 애플 가이드라인에 따르면 기본은 struct를 사용하지만, 몇가지 상황에 따라서는 struct와 class를 적절히 사용해야한다고 말하고 있습니다. 해당 링크는 아래 첨부할게요 :)

[Choosing between struct and class](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)

---

먼저 고민이 되는 부분에 대해서 간략하게 제 생각을 전달드렸어요.
저번 회의와 마찬가지로 아직 과일의 재고관리에 대한 부분에서 어려움을 느끼시는 것 같은데 위의 내용을 토대로 좀 더 고민해보시면 쉽게 풀어내실수 있을거라 믿습니다 :)

코드를 살펴보니 커밋과 네이밍에서 놀랐는데요. 기능단위로 세세하게 나누어서 커밋하신 점은 아주 훌륭합니다 💯
이렇게 되면 다른사람이 보기에도 편하고 기능단위로 커밋이 작성되었기 때문에 이후에 잘못된 부분을 발견했다면 수정하거나 되돌리기도 쉽습니다.
기능을 세세하게 나눈다고 커밋이 많아질까봐 두려워하지 마시고 지금처럼 어떤 기능이 필요한지 정하고 해당 기능만을 구현하는 데에 집중해서 커밋을 작성해주시면 좋을것 같아요 😀😀
그리고 코드 코멘트에도 적었지만 네이밍이 훌륭합니다. 변수명이 길어지더라도 그 변수만이 가지고 있는 역할에 대해서 잘 네이밍하신것 같아요.
저는 변수/함수명은 항상 그 역할에 맞는 것이 좋은 네이밍이라 생각하고 역할에 벗어나거나 과한 역할을 가지는 네이밍은 지양해야 한다고 생각하는데 아주 잘 네이밍을 해주신것 같습니다 👍

코드에 대한 부분은 코드 라인별로 코멘트를 적어두었고, 이에 더해 전체적으로 **캡슐화**와 **은닉화**에 대해서 좀 더 신경써주시면 좋을 것 같아요 :) 한 주 동안 너무 고생많으셨고 새로운 주도 화이팅입니다 !!

2021-06-15 13:50 UTC, soll4u commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    static let defaultStock: UInt = 10
말씀하신대로 static 키워드를 제거하였습니다! 그리고 storage 딕셔너리 초기화를 위해 FruitStore 인스턴스를 생성해서 defaultStock을 초기화값으로 넣어주었습니다. 
private 키워드는 defaultStock이 초기화를 위해 사용된 후 외부에서 접근이 필요하지 않을 것 같아 지정했습니다.

```swift
class FruitStore {
    private let defaultStock: UInt = 10
    
    enum Fruit {
        case strawberry
        case banana
        case pineapple
        case kiwi
        case mango
    }
    
    static var storage: [Fruit: UInt] = [.strawberry: FruitStore().defaultStock,
                                         .banana: FruitStore().defaultStock,
                                         .pineapple: FruitStore().defaultStock,
                                         .kiwi: FruitStore().defaultStock,
                                         .mango: FruitStore().defaultStock]
}
```

2021-06-15 13:59 UTC, Brian2931 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
저희는 만드는 입장에서의 ```JuiceMaker```를 생각해서 레시피재료를 ```JuiceMaker``` 안에 넣었어요. 그런데 타일러의 생각도 들어보니 메뉴 안에서 해당 메뉴의 재료를 관리하는 것도 좋은 것 같다고 생각이 들었습니다. 그래서 
![image](https://user-images.githubusercontent.com/73944268/122065766-2b493400-ce2d-11eb-9be5-eaa612857097.jpeg)

이것과 

![image](https://user-images.githubusercontent.com/73944268/122066016-59c70f00-ce2d-11eb-91dd-8b647c660a1b.jpeg)

이것처럼 두가지의 방법으로 메뉴 안에 넣어보았습니다.

2021-06-15 14:07 UTC, Brian2931 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    }
앗... 저희는 재고관리는 `FruitStore`의 `modifyStock()`이 담당하고 `JuiceMaker`의 `isJuiceAvailable(menu:)`는 쥬스를 만들 수 있는지 없는지에 대한 가치판단을 내려주는 것이라고 생각했어요. 혹시 `isJuiceAvailable(menu:)`이 `FruitStore`에 들어가는 것이 더 나을까요? 잘 모르겠습니다...

2021-06-15 15:10 UTC, soll4u commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +            }
말씀하신대로 `recipeNumber` 를 `necessaryFruitNumberForMenu` 로 바꾸고, `storageNumber`를 `currentRemainedFruitNumber` 로 변경했습니다!

그리고 둘을 짧게 할 방법을 못찾아서 그나마 조금 줄여보았어요.

```swift
    func isJuiceAvailable(menu: Menu) -> Bool {
        var isIngredientRemain: Bool = true
        let orderedJuiceRecipe = defaultJuiceRecipe(juiceMenu: menu)
        let neededIngredient = Array(orderedJuiceRecipe.keys)
        
        for i in 0..<orderedJuiceRecipe.count {
            guard let necessaryFruitNumberForMenu = orderedJuiceRecipe[neededIngredient[i]],
                  let currentRemainedFruitNumber = FruitStore.storage[neededIngredient[i]]
            else {
                return false
            }
            
            if necessaryFruitNumberForMenu > currentRemainedFruitNumber {
                isIngredientRemain = false
            }
        }
        return isIngredientRemain
    }
```

2021-06-15 15:32 UTC, soll4u commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +        let fruitStore = FruitStore()
넵 말씀하신대로 JuiceMaker 구조체 내에서 선언하도록 수정했습니다!

```swift
struct JuiceMaker {
    enum Menu {
        case strawberry
        case banana
        case kiwi
        case pineapple
        case strawberryBanana
        case mango
        case mangoKiwi
    }
    
    let fruitStore = FruitStore()
    // 생략
}
```

2021-06-15 16:20 UTC, soll4u commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +    func defaultJuiceRecipe(juiceMenu: Menu) -> [FruitStore.Fruit: UInt]{
수정했습니다!

2021-06-16 14:25 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +
storage는 static으로 남겨두신 이유가 있을까요???

과일재고를 담당하는 storage또한 FruitStore외부에서는 알지 않아도 되는 변수라고 생각합니다 :)

2021-06-16 14:30 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                  let currentRemainedFruitNumber = FruitStore.storage[neededIngredient[i]]
orderedJuiceRecipe를 통해 neededIngredient를 가져왔기 때문에
`for i in 0..<orderedJuiceRecipe.count` 보다 `for fruit in neededIngredient`를 이용하면 좀 더 쉽게 접근가능하지 않을까 생각해서 지난번에 피드백을 드렸습니다 ㅎㅎㅎ

그래도 지난번보다 `neededIngredient`를 가져오는 과정을 훨씬 단순화 시키신건 아주 좋습니다 :)

2021-06-16 16:41 UTC, TaeJoongYoon approved these changes
저번 PR에 대해 여러 피드백을 드렸는데 많은 부분을 이해하시고 또 질문을 주셔서 감사합니다 !!

우선, 제가 느끼기에 가장 큰 어려움은 `defaultJuiceRecipe`와 `isJuiceAvailable` 등과 같이
함수가 어느 객체에 들어가야 할지 정하는 것이라고 보여지는데요.
저 같은 경우는 먼저 함수의 역할과 객체의 역할을 고려하여 생각합니다.

먼저 `defaultJuiceRecipe`는 저처럼 Menu에서 관리 혹은 두분의 의견처럼 JuiceMaker에서 관리해도 괜찮을 것 같습니다.
그런데 `isJuiceAvailable`같은 경우는 재고의 유무에 따라 반환값이 결정되므로 재고관리를 담당하는 FruitStore가 더 알맞지 않을까 생각합니다 ㅎㅎ

모델 설계에 있어서 이렇다할 정답은 없지만 저 같은 경우는 위에 말씀드린데로 역할에 초점을 두어서 결정합니다. 제 의견이 정답이라고 생각하지 마시고 의견을 참고해서 두분만의 결정방식을 정하는 방향으로 가셨으면 좋겠습니다 ㅎㅎㅎ STEP1을 마무리하는데 오랜시간 노력하셔서 고생하셨습니다. 몇가지 피드백 남긴건 두분 의논하셔서 다음 STEP에 적용해주시면 감사하겠습니다 ㅎㅎ

정말로 고생많으셨습니다 :)

2021-06-16 16:43 UTC, merged

2021-06-18 09:18 UTC, soll4u commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +
곧 보낼 Step2 PR 에서 수정하였습니다!

2021-06-18 09:19 UTC, soll4u commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +                  let currentRemainedFruitNumber = FruitStore.storage[neededIngredient[i]]
이것도 Step2에서 수정했습니다 😀 조언 감사드립니다!