쥬스메이커 [Step 2] Jiwon, Hosinging
yagom-academy/ios-juice-maker pull request #80
Opened 2021-06-11 08:33 UTC by jyoon54

@leejun6694 

안녕하세요 쿠마! 
피드백 해주신 내용 참고하여 이전 스텝 부분 수정하고 스텝 2 완성하여 보냅니다.

고민되었던 점 / 궁금한 점

지원

얼럿을 표시하는것과 선택시 화면전환 하는 부분에서 통용되는 보편적인 스타일이나 형식이 있는것인지 궁금했습니다. 또, 활동학습시간에 KVO와 Notification 에 대하여 배우고 프로젝트에 활용하는 방안을 생각해보았는데, 어디에 쓰는것이 좋을지 아직 잘 모르겠습니다.  레이블의 값이 변할경우에 현재는 함수를 이용해 레이블의 값들을 새로고침 하는 방법을 쓰고 있는데, 이 부분을 KVO나 Notification을 이용해 처리하는 것이 더 좋은지 궁금합니다.

호싱잉

1. 말씀해주신 싱글톤 패턴을 FruitStore클래스 내에서 구현했고, FruitStore.fruitstore로 접근할 수 있게 했습니다. 싱글톤 패턴으로 만들어진 NotificationCeneter의 NotificationCenter.default 나 다른 싱글톤으로 만들어져있는 것들의 속성이나 메소드에 접근할 때 중간에 사용되는 프로퍼티의 네이밍에 대해서 적절하게 잘 것인지 고민이 되었습니다.  혹시 싱글톤임을 나타내는 키워드의 기준이 있다면 그 점을 알고싶습니다.
2. 싱글톤 패턴을 타입 프로퍼티로 선언했기 때문에 FruitStore.fruitstore.으로 해서 그 클래스에 속한 다른 속성이나 메소드에 접근할 수 있는데, 저희는 juiceMaker라는 구조체 안에서 connectedStore라는 상수에 FruitStore.fruitstore를 할당해서 해당 상수를 활용했는데요. 싱글톤으로 만든 것을 따로 상수에 넣어서 사용하는 것이 괜찮을지, 싱글톤임을 그대로 나타내는(예: FruitStore.fruitstore)것이 괜찮을지.. 궁금했습니다.

2021-06-13 13:43 UTC, leejun6694 requested changes
지난 피드백 내용을 잘 반영해주었고, extension 을 활용하는 모습이 인상적입니다 💯 

- iOS View, 전환 방식의 스타일이나 형식 관련해서, 찾아본 문서나 자료가 있을까요?
- 현재 label 을 업데이트 해주는 방식도 좋지만, 배운 내용을 적용해보는 것도 경험치가 쌓이겠네요 : )
- default, shared 등 많이 보이는 키워드는 있습니다. 참고해서 문서를 찾아볼까요??
- 굳이 선언하지 않고, (현재 구현된 상태로는) `FruitStore.fruitstore` 를 사용해도 될 것 같네요~~

추가된 리뷰 확인 부탁드려요. 혹시 궁금한 점이 있다면, 언제든 디스코드로 연락주세요~~!

2021-06-13 14:51 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +	case strawberryJuice = "딸기쥬스"
네 확인했습니다~! 해당 내용 반영해서 정리해보겠습니다~!

2021-06-13 15:12 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        refreshStockLabel()
viewDidLoad는 뷰의 컨트롤러가 메모리에 로드되고 난 후에 호출되고, viewWillAppear는 뷰가 로드된 다음 뷰가 나타나기 직전에 호출 되는 것으로 알고있습니다. viewDidLoad가 리소스 초기화나 초기 화면 구성에 사용하는 용도로 사용한다고해서 리소스 초기화 용도의 refreshStockLabel()을 해당 위치에서 호출하였는데 viewWillAppear에서 호출해 주는 것이 적절했을 까요?😭

2021-06-13 15:25 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/SecondViewController.swift
> +        // Do any additional setup after loading the view.
네 확인했습니다~!

2021-06-13 15:28 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +class ViewController: UIViewController {
단순하게 화면 구성과 데이터에 따라 화면을 업데이트하고,  사용자에게서 발생한 이벤트를 처리할 수 있게 멤버(프로퍼티, 메소드)를 정의하는 클래스 정도로 알고 있었는데 확실하게 ViewController 역할에 대해서 확인할 수 있었습니다.

UIKit 앱의 View계층 구조를 관리하는 객체로 주요 역할은 다음과 같습니다. 
1. 데이터 변화에 따라 view content를 업데이트
2. 사용자와 view간의 상호 작용에 응답
3. view를 리사이징하고 전체적인 인터페이스의 레이아웃을 관리
4. 앱 내에서 다른 뷰 컨트롤러를 포함해서 다른 객체와 함께 앱 구성

2021-06-13 15:36 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +	func canMakeJuice(recipe: Recipe) -> Bool {
이 메소드 명을 작성할 때 참고하진 않았지만, 기존에 선배 기수의 리뷰를 받을 때 공유 받았던 Bool타입의 네이밍 관련 자료(아래 링크 첨부)에서 봤었던 적이 있어서 사용가능할 것으로 판단해서 사용했었습니다. 
https://soojin.ro/blog/naming-boolean-variables

2021-06-14 03:15 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func lookUpStocks() -> [Fruit: UInt] {
private로 만든 딕셔너리를 직접 반환하는것 대신, 각각의 과일의 수량을 필요한 때에 불러 올 수 있도록 
변수를 추가적으로 만들어 보라는 뜻으로 이해했는데, 맞을까요? 그렇게 하면 KVO도 사용이 더 간편 할 것 같습니다!

2021-06-14 03:15 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +			return 0
이부분과 consume은 추후에 Step3 에서 stepper를 사용할 때 stepper의 값만큼 수량을 추가해 주기 위해서 정수값을 반환하는 함수로 바꾸었는데요, 만약 수량이 nil이라면 개수를 추가하지 않기 위해서 0을 반환하도록 하였습니다.  생각해보니 굳이 값을 반환하지 않아도 될 것 같습니다...

2021-06-14 03:15 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +		guard let stock = fruitStocks[fruit], stock >= number else {
guard hasEnough(...) else 로 대체해도 똑같으니 코드를 재활용 하는것이 좋을것 같네요!

2021-06-14 03:15 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +			_ = fruitStore.consume(fruit: fruit, number: amount)
consume 과 add가 값을 리턴하는 것에 대해서는 저희도 맞지않다 생각하여 추후 수정할 예정입니다!  for 문을 2번 사용하는 것에 대해서는 이전 PR에 코멘트하였는데, 어떻게 생각하시는지 의견이 궁금합니다!

2021-06-14 10:42 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +    func lookUpStocks() -> [Fruit: UInt] {
고민해 보다가 읽기 전용으로 설정하는 방법을 생각해봤는데, 이쪽이 좀더 말씀하신 내용과 맞아떨어지는것 같아요!

2021-06-15 14:10 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    @IBAction func orderDdalbaJuice(_ sender: UIButton) {
각 각의 버튼을 하나의 IBAction에 연결하고, 버튼의 타이틀에 의해 분기되어 작동되게 할 수 있을 것 같아서 그렇게 수정해봤습니다.

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    func refreshStockLabel() {
외부에서 사용하지 않는 method 로 보이네요!?

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    func orderJuice(recipe: JuiceRecipe) {
이 친구도 외부에서 사용되지 않는 것 같아요!

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    @IBAction func orderJuice(_ sender: UIButton) {
이 친구도 외부에서 사용되지 않는 것 같아요!

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    override func viewDidLoad() {
취향 차이지만, 저는 property - life cycle - 그 외 method 로 보통 순서를 정하고 있습니다.
ViewController 는 거의 대부분 property 와 life cycle 이 정의되기 때문에, 고정으로 위에 둬서 규칙을 주고 있습니다.
life cycle 도 순서대로 작성하고 있구요ㅎㅎ
참고하면 좋을 것 같아서 공유해요 : )

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        super.viewDidLoad()
추가로 구현되는 로직이 없다면, method 는 제거해도 될 것 같네요ㅎㅎ

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        refreshStockLabel()
`super.viewWillAppear()` 가 제거되었네요.
이유가 궁금합니다.
또, 없다면 어떤 일이 발생할까요?

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    let juiceMaker = JuiceMaker()
외부에서 사용하지 않는 property 네요 ~~

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        switch sender.titleLabel?.text {
피드백을 본인들만의 스타일대로 잘 적용해주셨네요 💯 
불필요하게 같은 역할을 하는 method 들이 제거되었네요!

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        switch sender.titleLabel?.text {
다만, 값을 비교하는 로직에서 UI 값은 storyboard 에 직접 타이핑으로 정의되어 있고, switch 문에선 button name 을 가져오고 있어서 안전하지 못한 부분도 있는 것 같습니다.
이런 부분도 나중에 고민해보시면 좋겠네요 : )

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Extension/UIAlert+UIVIewController.swift
> +enum Message: String {
Message 는 범위가 너무 넓은 것 같네요. 어떻게 생각하시나요!?

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Extension/UIAlert+UIVIewController.swift
> +            guard let addStockViewController = self.storyboard?.instantiateViewController(identifier: "moveToSecondViewController") else { return }
closure 내 self 등의 `어떤 property` 들은 사용에 주의해야합니다.
아직 안배운 내용일 수도 있어서, 언급만 드려요.
추후에 알아보시면 좋을 것 같네요 : )

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
불필요한 줄바꿈들이네요!

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    let juiceMaker = JuiceMaker()
UI 관련 property 들과는 줄바꿈을 하나 해주면 어떨까요?

2021-06-15 16:41 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
> +			return 0
네ㅎㅎ 오히려 error 가 더 어울리는 상황 같네요~

2021-06-15 16:45 UTC, leejun6694 approved these changes
추가로 코멘트 드린 부분들이 있습니다. 좀 더 생각해볼 수 있는 부분들이 있는데, 코멘트 내용을 참고해서 공부해보시면 좋을 것 같네요 👍 
step3 에서도 창의적인 코드들이 기대됩니다~~!

2021-06-15 16:45 UTC, merged

2021-06-15 17:13 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        switch sender.titleLabel?.text {
네 결국 문자열끼리 비교를 하기 때문에 위험한 부분이 있는 것이 맞는 것 같습니다. 지금 가진 지식에서.. 생각나는 방법으로는 tag를 주고 tag를 활용한 분기를 하면 어떨까 생각이 드는데 이 방법 외에 시도해볼만한 다른 방법이 있다면 키워드를 알려주실 수 있으실까요?

2021-06-16 02:29 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +        refreshStockLabel()
viewWillAppear작성중 의도치 않게 삭제 된거같습니다. 공식 문서에 따르면 super.viewWillAppear는 아무것도 하지 않는다고 나와 있지만, super.viewWillAppear없이 먼저 코드를 쓰게 되면 예상치 못한 문제가 발생할 수 있어 되도록이면 쓰는것이 권장된다고 합니다!

2021-06-16 03:26 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Extension/UIAlert+UIVIewController.swift
> +enum Message: String {
같은 생각이어서 타입이름을 OrderResultMessage로 수정했습니다.

2021-06-16 03:34 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Model/JuiceMaker.swift
> +
네 해결했습니다.