쥬스 메이커 [Step3] 샤피로, 테리
yagom-academy/ios-juice-maker pull request #86
Opened 2021-06-15 14:02 UTC by taelee42

@SungPyo 내일날씨맑음 저희 step3작성해봤습니다!
리뷰 잘 부탁드립니다.
## Step3 구현내용
1. Notification 위치를 FruitStore의 fruits변수에 프로퍼티 감시자를 만들어서 그 내부로 옮겼습니다.
2. JuiceMaker를 Singleton으로 바꿨습니다.
3. ViewController가 2개의 씬을 다 제어하던것을 ChangeStockViewController로 나눠서 각각의 뷰를 담당하는 것으로 변경

## 궁금한점
저희가 화면에 따라 ViewController를 2개 만들어줬는데요. 나누기 전에 하나의 뷰컨트롤러에서 제어하던 부분이 있어서 새로 만든 ViewController가 기존 ViewController를 상속하게 했습니다. 이렇게 하면 기존 뷰컨트롤러에서 연결되어있는 IBOulet을 그대로 쓸 수 있고 기존에 선언한 함수 또한 그대로 쓸 수 있는 장점이 있는데요. 이렇게 해도 되는지 궁금합니다.

2021-06-15 17:05 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +class ChangeStockViewController: ViewController {
개인적으로 굉장히 싫어하는, 매우 좋지 않다고 생각하는 상속입니다.
코멘트에 남겨주셨듯 재사용에 대한 이점은 있지만, 상속을 하는 경우에는 매우 신중해야 합니다.
SOLID 원칙에 대해서 공부해 보시면 상속과 관련된 항목이 있습니다.

2021-06-15 17:06 UTC, SungPyo commented on JuiceMaker/JuiceMaker/Controller/ChangeStockViewController.swift
> +        setStepperInitialValue()
이 부분은 상속에 관련된 코멘트를 달았기에 별도의 코멘트를 달지 않겠습니당.

2021-06-15 17:20 UTC, SungPyo requested changes
테리, 샤피로 안녕하세요 step3 까지 오셨네요. step1,2 리뷰에 대한 리팩토링이 조금 되어있었으면 하는 아쉬움이 있네요. 먼저 궁금한 점에 대한 답변부터 말씀드릴게요.

궁금한점에 대한 답변
-
1. 저희가 화면에 따라 ViewController를 2개 만들어줬는데요. 나누기 전에 하나의 뷰컨트롤러에서 제어하던 부분이 있어서 새로 만든 ViewController가 기존 ViewController를 상속하게 했습니다. 이렇게 하면 기존 뷰컨트롤러에서 연결되어있는 IBOulet을 그대로 쓸 수 있고 기존에 선언한 함수 또한 그대로 쓸 수 있는 장점이 있는데요. 이렇게 해도 되는지 궁금합니다.
ㄴ `안되진 않습니다. 하지만 제가 보기엔 매우 불편한 코드입니다. 따로 코멘트를 달아 놓았으니 코멘트를 참고해 주세요 :)`

Step3까지 작업하시느라 고생하셨습니다.

## 1차적으로 몇가지 미션을 드릴게요. 물론 다 하지 못해도 상관 없습니다. 

1. 굉장히 치명적인 문제가 있는데, 아래와 같은 상태가 왜 지속되는지 한번 생각해 보시고 생각을 공유해 주세요.

![스크린샷 2021-06-16 오전 1 58 05](https://user-images.githubusercontent.com/19344776/122095383-470e0380-ce48-11eb-8364-61c133f0d9cf.png)

2. ViewController에 있는 Alert의 경우도 Alert을 밖에 두고있는게 아닌, 메시지나 title등을 받아 한번에 처리하는 형태로 한번 리팩토링 해보시겠어요?

3. 화면간 데이터 전달에 대해 공부해 보시고 NotificationCenter가 아닌 다른 방법으로 적용해 보세요. (배우지 않으셨다면 Delegate와 Closure, 배우셨다면 복습을.. ) 

일단 요렇게 3가지 정도만 드려볼게요.

2021-06-18 03:57 UTC, taelee42 commented
@SungPyo 
말씀해주신대로 코드를 수정해봤습니다

## 코드 수정사항
1. 모든 노티피케이션 관련 코드를 삭제하고 델리게이트 패턴을 사용해서 2번재 화면의 재고 수정이 끝났음을 1번째 화면에게 알려주었습니다.
2. Alert을 1개의 함수내에서 인자를 달리해서 관리하는식으로 만들었습니다.
3. 2번째 뷰컨트롤러가 1번째 뷰컨트롤러를 상속하는 방식이 아닌 별도로 생성해서 만들었습니다.

## 궁금한점
1. 메모리 누수에 대해 많이 고민해봤는데 이유를 잘 모르겠습니다.
코드를 고치다보니 메모리가 많이 줄기는 했는데 왜 줄었는지도 확실히 모르겠습니다.
2번재 화면에서 1번째 화면으로 올 때 뭔가가 메모리가 계속 쌓이는 것 같아서 2번째 화면의 deinit을 확인해서 잘 해제되는 것도 확인했습니다.
또한 뭔가 누적되는게 혹시 2번째 화면의 네비게이션 컨트롤러 때문인가 싶어서 네비게이션 컨트롤러를 통하지 않게 세그를 만들어봤지만 메모리는 바뀌지 않았습니다.
현재 코드에서는 메모리 부분이 괜찮은지 그리고 왜 그런 현상이 일어났던 것이었는지 궁금합니다~

2. 2개의 뷰컨트롤러에서 직접 모델에 접근해서 데이터를 가져와도 되는지 궁금합니다.
2개의 뷰컨트롤러가 모두 JuiceMaker.shared.fruitStore.fruits에 접근해서 데이터를 가져오는데 첫번째 뷰컨트롤러가 데이터를 받아오고 이것을 2번째 화면에게 전달했다가 다시 수정된 정보를 회수하는식으로 작성해야하는건지도 궁금합니다.
아니면 프로퍼티 감시자를 통해서 2개의 컨트롤러가 각각 모델과 직접 통신해야하는지 궁금합니다.

2021-06-20 15:09 UTC, SungPyo commented
step3 도 고생하셨습니다.

시간이 딱 정해져 있어서 모든 코드에 대해서 하나하나 알려드릴 수 없는게 아쉽네요. (예: Alert 등..)
프로젝트간 발견했던 문제나 변경된 코드의 스타일을 다음 프로젝트에 적용할 수 있으면 좋을 것 같네요!

고생하셨습니다!

궁금한점에 대한 답변
-
1. 메모리 누수에 대해 많이 고민해봤는데 이유를 잘 모르겠습니다.
코드를 고치다보니 메모리가 많이 줄기는 했는데 왜 줄었는지도 확실히 모르겠습니다.
2번재 화면에서 1번째 화면으로 올 때 뭔가가 메모리가 계속 쌓이는 것 같아서 2번째 화면의 deinit을 확인해서 잘 해제되는 것도 확인했습니다.
또한 뭔가 누적되는게 혹시 2번째 화면의 네비게이션 컨트롤러 때문인가 싶어서 네비게이션 컨트롤러를 통하지 않게 세그를 만들어봤지만 메모리는 바뀌지 않았습니다. 현재 코드에서는 메모리 부분이 괜찮은지 그리고 왜 그런 현상이 일어났던 것이었는지 궁금합니다~
ㄴ `메모리 누수에 관련된건 제가 리뷰에 말씀 드렸던 것 처럼 Notification center를 잘못 사용하면 메모리 누수를 발생 시킵니다. 가독성도 당연히 떨어지구요. 사용하지 않는 Notification Center는 remove해 주어야 합니다. 델리게이트로 변경되면서 deinit이 잘 불리게 변경된것 같네요 :)`

2. 2개의 뷰컨트롤러에서 직접 모델에 접근해서 데이터를 가져와도 되는지 궁금합니다.
2개의 뷰컨트롤러가 모두 JuiceMaker.shared.fruitStore.fruits에 접근해서 데이터를 가져오는데 첫번째 뷰컨트롤러가 데이터를 받아오고 이것을 2번째 화면에게 전달했다가 다시 수정된 정보를 회수하는식으로 작성해야하는건지도 궁금합니다.
아니면 프로퍼티 감시자를 통해서 2개의 컨트롤러가 각각 모델과 직접 통신해야하는지 궁금합니다.
ㄴ `직접 모델에 접근해서 데이터를 가져오면 안되는 이유는 없죠. 하지만 그건 다 디자인 패턴에 대한 문제이다 보니 사용하는 디자인 패턴에 따라서 데이터를 어떻게 가져올 것이고 어떻게 비즈니스 로직을 구성할 것인지 나뉘게 됩니다. 디자인 패턴에 따라 좋을수도, 나쁠수도 있습니다. 올바르게 동작한다면 일단 정답이구요 :)`

2021-06-20 15:10 UTC, merged