쥬스메이커 [Step2] Geon
yagom-academy/ios-juice-maker pull request #90
Opened 2021-06-16 10:03 UTC by jgkim1008

@YebinKim 

안녕하세요 비비~ 
방금 작성한 따끈한 step2를 가져왔습니다~ 아직은 개념이 확실히 잡히지 않아서 이것저것 적용해보느라 시간이 많이 걸렸습니다..
이번 리뷰도 잘 부탁드려요~

궁금한점 : 

1. ErrorCase 파일을 따로 만들어서 ErrorCase열거형을 따로 작성하였는데요, Fruits도 마찬가지고 사실 코드 내용이 길지 않은데 구분하기 쉬워보이려고 만들었는데 해당방법이 좋은 방법일까요??(혹시 추가해야할 error가 또 있을까요 ?)

2. 알수없는 에러에 대해서 alert를 띄우게 구현하였는데 굳이 만들필요가 없었을까요??

3. touchUpJuiceMenu 메써드를 통해 해당 메뉴를 터치하는 구분을 메뉴마다 tag값을 설정하여 switch문으로 결과를 구분하였는데 , IBOutlet으로  메뉴에 대해 프로퍼티 생성하여 해당 값을 비교하는 방법이 있더라구요. 어떤방법이 더 효율적일 까요??

4.화면 전환에 있어서 navigationContoller가 있어 push 화면전환을 사용하였는데요. 왜 navigationContoller 가 2개가 있는지 잘 모르겠습니다..

2021-06-16 19:25 UTC, YebinKim requested changes
건 안녕하세요~
Step2 진행 정말 고생 많으셨습니다 😊👏
많이 찾아보고 다양한 시도를 해본 노력이 보이는 코드였어요!! ☺️
상세한 라인별 코멘트는 아래에서 드리고 우선 질문부터 답변 드릴게요~!

---

### 1. ErrorCase 열거형을 담은 ErrorCase 파일을 만든 것이 좋은 방법일지, 추가할 ErrorCase가 있을지

현재 ErrorCase는 여러 클래스/구조체에 걸쳐 사용되고 있으며, 이름또한 범용적인 이름 `ErrorCase` 을 가지고 있는데요.
이 경우에는 파일을 따로 분리해주는 것 또한 괜찮다고 생각해요~

기능과 관련해서 추가할만한 ErrorCase로는 실제 재고와 화면에 보이는 재고의 불일치, 화면 전환 실패 등 정의하기 나름이지만 
현재 기능명세서와 작성한 코드를 고려했을 때는 추가로 정의할만한 ErrorCase가 없어보여요 😊



---

### 2. 알 수 없는 에러에 대해서 alert를 띄운 방식이 어떤지

알 수 없는 에러에 대비해서 에러 처리를 작성하신 부분 먼저 박수 드립니다! 😆👏
발생한 에러에 대해 얼럿 메세지로 출력해주시고자 한 부분 또한 좋다고 생각해요!

다만, 에러를 그대로 출력하게 되면 사용자 입장에서는 **에러타입의 인스턴스를 그대로 출력한 내용**을 보게 되기 때문에 알 수 없는 내용을 전달받을 것으로 보이는데요.
Error 타입 인스턴스가 가진 String 타입의  `localizedDescription` 프로퍼티를 활용하면 이 문제를 개선해볼 수 있을 거 같아요! 공식문서와 함께 참고해서 보시면 좋을 거 같습니다 ☺️
(https://developer.apple.com/documentation/swift/error)

또한, 얼럿을 띄우는 메서드 `alertMessage(juice:makeJuice:unknownErrorMessage:)` 는 개선할 부분이 보이는데요.
메서드의 네이밍을 다시 한 번 고민해보고, 반복되는 코드를 줄이기 위한 방향으로 아래 라인별 코멘트에서 언급 드렸어요!
확인 한 번 부탁드립니다 😄



---

### 3. 메뉴를 터치하는 메서드 중 메뉴마다 tag값을 설정하여 switch문으로 결과를 구분하는 방법과 IBOutlet으로 메뉴에 대해 프로퍼티 생성하여 해당 값을 비교하는 방법 중 어느 것이 더 좋은 방향일지

버튼의 태그값과 switch 구문을 함께 활용해보는 발상 정말 좋았어요! 👍
다만, 매칭된 케이스의 숫자와 Fruits 속성은 서로 연관성이 없고, 각 버튼이 어떤 태그를 가진지는 알 수 없기 때문에 아쉬움이 있어요 😥
예를 들어 설명해보자면 현재는 `case 0` 에서의 0이라는 숫자와 `.bananaJuice` 의 속성은 연관성이 없고, 각 버튼이 어떤 태그값을 가지는지는 디버깅을 통해 확인해볼 수 밖에 없는데요.
이때, 속성이 중간에 추가되거나 하나의 케이스가 사라지게 되면 수정이 번거로워지게 될 것으로 보여요.

IBOutlet으로 메뉴에 대해 프로퍼티 생성하여 해당 값을 비교하는 방법이 어떤 방법인지 질문만 보고는 잘 와닿지 않았는데요..!
이 방법으로도 한 번 수정을 해본 후 아래의 사항을 고려하여 수정 방향을 잡아보시는 걸 추천드립니다! 😊
1. 메서드가 하나의 일만 하고 있는지
2. 중복되는 코드가 없는지
3. 이후에 새로운 종류의 메뉴가 추가되었을 때 수정이 원할한지



---

### 4. 화면 전환에 있어서 navigationContoller 2개가 필요한 이유

뷰컨트롤러에 navigationController를 붙여주는 이유는 **뷰컨트롤러를 navigationController로 관리**하거나 **화면에 navigationBar를 붙이기 위함**인데요.
현재와 같이 push로 화면 전환을 하게 되면 navigationController가 굳이 필요하지 않았을 거 같아요~

화면 전환에는 **navigation push 방식**과 **modal presentation 방식**이 있는데요.
둘 중 navigation push 방식을 사용하신 이유를 알 수 있을까요? 🤔



---

건, Step2 완성하느라 고생 많으셨어요~!!
전체적으로 네이밍과 관련해서 코멘트를 드렸는데요.
각 메서드, 매개변수, 프로퍼티, 클래스의 용도를 더 쉽게 파악할 수 있는 네이밍을 고민해보시면 좋을 거 같아요~
네이밍은 혼자 고민하기 어려운 부분이라.. 혹시 고민이 길어지시면 언제든 DM 주세요! 저도 함께 생각해볼게요 😆 (집단지성 해봅시닷!)

그리고 UI 오류와 얼럿을 띄우는 메서드를 이번 스텝에서 같이 개선해본 후 머지 진행하면 좋을 거 같아서 Request changes 로 코멘트 드릴게요!
리뷰 확인해보신 후 궁금한 점이 있으면 언제든 질문주세요~! 👀🙌

2021-06-17 14:20 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
>  class ViewController: UIViewController {
아무래도 초기화면이니깐 mainControllerViewController 또는 OrderJuiceViewController 로 생각을 하다가 
OrderJuiceViewController가 아무래도 더 명확한것 같아서 이렇게 진행하였습니다~

2021-06-17 14:20 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func currentStockOfFruits() {
음..dispalyStockOfFruits() 또는 showStockOfFruits()가 제일 와닿는것 같은데요
showStockOfFruits()로 하기로 했습니다~ 비비 생각은 어떻신가요??

2021-06-17 14:20 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            }
이번 좋은 방법이 있었다니 ㅠㅜ 유용하게 써먹겠습니다ㅎㅎ

2021-06-17 14:25 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func alertMessage(juice: JuiceMenu?, makeJuice: Bool, unknownErrorMessage: String?) {
메써드는 동사로 권장을 해주셨고,  주문에 대한 결과를 나타내는것이니깐 showResultOfOrder 로 수정을 해보았어요.
이름 짓는게 제일 어렵군요!!😵‍💫

2021-06-17 14:32 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +            present(errorAlert, animated: true, completion: nil)
함수 하나의 기능만 하게 구현하는게 중요하다는걸 다시 깨달았어요..
다시 쳐보면서 곱씹어 보고 있습니다..
가야할길이 멀군요 ㅎㅎ 😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫

2021-06-17 14:35 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/View/Base.lproj/Main.storyboard
> +                                                <rect key="frame" x="0.0" y="129.33333333333334" width="148.33333333333334" height="20.333333333333343"/>
IBOutl으로 끌어가다가 실수가 생겼던것 같아요ㅠㅠ

2021-06-17 15:43 UTC, jgkim1008 commented
@YebinKim 

비비 꼼꼼한 리뷰 감사해요~ 오늘 비비 덕분에 많은걸 배워갑니다 :)

pr 리뷰에 대한 답변과 아직 잘모르겠는 부분이에요..

* navigation push 방식을 사용한 이유: 

  ViewController의 view를 바꿔치기 ,ViewController가 다른 ViewController 호출(present) , NavigationController 사용하여 화면전환(push) , 화면전환용 객체 Segue 사용  총 4가지 방식이 있다고 봤는데요
  NavigationController가 있으니깐 당연히 push를 써야되는지 알았습니다. 하지만 찾아보니깐 ViewController가 다른 ViewController 호출(present) 이 Modal 방식이고 , NavigationController 사용하여 화면전환(push)이 navigation 방식이군요.
  Modal방식은 화면/정보의 흐름과는 상관없이 이루어질때 사용하고 , Navigation 방식은 정보의 흐름이 깊어질때 (depth)가 생길때 쓴다고 배웠습니다. 그래서 StorageViewController로 이동할떄는 정보의 흐름이 이어져야 되니깐 Navigation 방식으로 진행해야 될것 같습니다.

* 현재와 같이 push로 화면 전환을 하게 되면 navigationController가 굳이 필요하지 않았을 거 같아요~

  이부분은 어떤말씀인지 잘 모르겠어요 ㅠㅜ

* localizedDescription 해당 부분은 확실하게 이해를 하지 못했습니다 ㅠㅜ

  OS에서 나타나는 구체적인 에러메세지 (ex: 네트워크 오류, 저장공간 부족 오류 등) 를 전달해준다라고 이해하면 될까요?? (기존에는 instance 에 나타나는 오류)

참조 링크 : (https://twih1203.medium.com/swift-ios-%ED%99%94%EB%A9%B4%EC%A0%84%ED%99%98%ED%95%98%EA%B8%B0-5e5998679d3a)

2021-06-18 12:38 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func currentStockOfFruits() {
show 또는 display 둘 다 명확하게 보여준다는 뜻을 가지고 있어서 좋네요!
개인적으로 display는 무언가를 전시하는 뜻을 가지고, show는 무언가를 보여준다는 뜻을 가진 것으로 보여 show라는 네이밍이 좋다고 생각합니다 😊

2021-06-18 12:41 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +    private func alertMessage(juice: JuiceMenu?, makeJuice: Bool, unknownErrorMessage: String?) {
showResultOfOrder 라는 네이밍은 명확하다고 생각합니다!
wasMakeJuice는 과거형을 나타내다 보니 어색한 감이 있고 canMakeJuice는 나쁘지 않은 거 같아요~
다만 Swift API Design Guideline에서 Bool 타입은 is로의 명명을 권장하고 있기 때문에 현재의 isPossibleToMakeJuice 가 셋 중 베스트로 보여요! 🤩

2021-06-18 12:48 UTC, YebinKim approved these changes
건 안녕하세요~
리네이밍과 메서드 분리, 코드 재사용성 향상을 훌륭하게 적용하셨네요!! 😆👍
일부 질문에 대한 답변은 회의실에서 따로 진행하기도 했었는데요.
한 번 더 정리해서 답변 작성해볼 수 있도록 할게요! 😊

---

### 1. navigation push 방식을 사용한 이유에 관한 답변

정보의 흐름이 이어져야 한다는 생각 또한 맞다고 생각해요! 😊
말씀하셨다시피 ViewController의 화면 전환 기법에는 크게 4가지 기법이 있는데요.
이 중 화면 전환 방식은 **Navigation Push**와 **Presentation Modal** 두 가지 방식으로 나뉘어요.
Navigation Push 방식은 말씀하신 것 처럼 정보의 흐름이 깊어질 때 사용할 수 있고,
Presentation Modal 방식은 해당 화면에서 추가적인 정보를 표시하고 간단한 액션을 수행하고자 할 때 사용할 수 있어요.

Navigation Push 방식은 **NavigationController를 사용해 화면간의 계층**을 가지고, 네비게이션 바를 이용해 화면의 흐름을 제어할 수 있다는 특징이 있고 (네비게이션 바를 숨길 수도 있어요!)
Presentation Modal 방식은 **해당 화면으로부터 바로 다른 화면을 띄우고** 별도의 버튼 또는 pageSheet로 화면을 띄웠을 경우에는 드래그다운을 통해서도 닫을 수 있다는 특징이 있어요.

그래서 두 방식은 화면을 띄우기 위한 주체가 각각 NavigationController와 현재 ViewController로 구분되는데요.
코드로 예를 들어보자면 아래와 같아요.

```swift
// Navigation Push
self.navigationController?.pushViewController(nextViewController, animated: true)
// 화면 전환의 주체가 navigationController

// Presentation Modal
self.present(nextViewController, animated: true, completion: nil)
// 화면 전환의 주체자 self (UIViewController)
```

두 방식의 차이를 이해하고 적절히 사용하는 것이 중요하다고 생각해 질문을 드렸습니다 😆
현재의 방식이 어떤가에 대해서는 아래 질문 답변을 통해 말씀드릴게요.



---

### 2. 지난 리뷰 중 '현재와 같이 push로 화면 전환을 하게 되면 navigationController가 굳이 필요하지 않았을 거 같아요~' 에 관한 보충 설명

이 부분은 modal 방식으로 화면을 띄워봤을 때 현재 프로젝트의 기능명세를 따르려면 navigationController의 필요성을 느끼게 되셨을 거라는 뜻이었는데요.
modal 방식으로 `StorageViewController` 를 띄우게 되면 상단에 네비게이션 바가 없는 것을 보실 수 있었을 거에요.
기능명세를 따르려면 `StorageViewController` 역시 네비게이션 바를 가져야 하는데.. modal 방식은 navigationController를 가지지 않기 때문에 네비게이션 바가 보이지 않는 상황인 것이죠.
그래서 **`StorageViewController`도 네비게이션 바를 가질 수 있도록 자신만의 navigationController를 가져야 하는데요**. (이때의 `StorageViewController`의 navigationController와 `OrderJuiceViewController`의 navigationController는 서로 다른 navigationController에요!)
정리하자면 `OrderJuiceViewController` 는 **`StorageViewController` 의 navigationController를 화면에 modal 방식으로 띄우게 되는 것**이죠.

현재와 같이 push로 화면 전환을 하게 되면 `StorageViewController` 는 `OrderJuiceViewController` 의 navigationController로 부터 띄워진 것이기 때문에 네비게이션 바를 가진 상태였을 거에요. 즉, `StorageViewController` 의 네비게이션 바를 보여주기 위한 별도의 navigationController가 필요하지 않은 상황인거죠.

이 내용을 좀 더 이해하려면 `StorageViewController` 를 modal로도 한 번 띄워보는 것을 추천드립니다 😊



---

### 3. localizedDescription 에 관한 보충 설명

localizedDescription는 정확히 얘기하자면 **해당 error가 가질 수 있는 상세 설명**을 말해요.
그래서 미리 정의한 에러 메세지가 있다면 해당 에러 메세지를 보여줄 수도 있고,
에러 메세지가 없다면 빈 문자열을 반환할 수도 있고,
커스텀한 에러 케이스에 대해 에러 메세지를 보여줄 수도 있어요!
OS에서 나타나는 구체적인 에러에 관해 에러 case와 localizedDescription이 정의되어 있다면 해당 에러의 메세지를 보여줄 수도 있을 거구요 😊 (정의되어 있지 않다면 빈 문자열을 반환하겠죠?)

커스텀 에러의 localizedDescription 확장 활용 방법에 대해서는 아래 링크를 참조할 수 있는데요.
아직 익히지 않은 문법을 활용하게 되기 때문에 가볍게 보고 넘기는 것을 추천드려요 ☺️
https://stackoverflow.com/a/39176551



---

Step2 수정 고생 많으셨습니다 😄
이번 스텝까지 필수로 구현해야 하는 사항에 대해서는 이전부터 적용이 완료되어 있었고,
저도 필수로 수정이 필요한 사항은 더 없다고 생각해 머지를 진행할게요~! 🥳

함께 회의실에서 실시간으로 리뷰를 진행하고, 또 Step2 마무리까지 매듭짓기 위해 정말 고생 많으셨어요.
**한 스텝을 진행하더라도 제대로 진행하는 것이 목표**기 때문에 모든 스텝을 진행하는 것보다 한 스텝씩 꼼꼼히 진행하는 것이 더 중요하다는 것!! 다시 한 번 말씀드리구요 😊
이번 2주동안 고생한 만큼 주말 푹 쉬고 재충전해서 다음 프로젝트도 힘내봅시닷!! 💪😆
쥬스메이커 프로젝트는 여기서 마무리할게요~

2021-06-18 12:48 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    @IBOutlet weak var touchMangoJuice: UIButton!
touch로 시작하는 네이밍은 메서드와 헷갈릴 우려가 있어보여요 🤔
이 부분 네이밍을 개선하기 위해 (명사)Button 또는 button(명사) 같이 해당 프로퍼티가 버튼임을 명확히 보여주면 어떨까요?

2021-06-18 12:48 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +        }
tag를 사용했을 때 보다 훨씬 가독성이 좋아졌네요! 😆👍
회의실에서 질문해주셨다시피 sender의 케이스를 한정하지 못해 default 케이스를 작성해야 하고, 
버튼이 추가되었을 때 switch문의 구현을 강제하지 못 한다는 점이 아쉬움이 남는 거 같아요.

현재 구현에서의 아쉬움을 이해했으니 다음 구현에서는 다른 방법을 시도해보는 것 또한 좋을 거 같습니다 ☺️

2021-06-18 12:48 UTC, YebinKim commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    private func showResultOfOrder(selectedJuice: JuiceMenu?, isPossibleToMakeJuice: Bool) {
매개변수 이름이 길어질 때는 **전달인자 레이블**과 **매개변수 이름**을 구분함으로써 메서드 안에서 사용할 이름은 좀 더 간략하게 표현해볼 수도 있어요~! 😊🙌

2021-06-18 12:48 UTC, merged

2021-06-21 13:52 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    @IBOutlet weak var touchMangoJuice: UIButton!
음...bananaJuiceButtonTouch 로 바꿨는데 어떻게 생각하시나요??
바나나주스의 버튼을 터치했다. 이렇게 해석되면 명확하다고 생각이 되서요~

2021-06-21 13:57 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +        }
네네 비비 ㅠㅜ 
다음에는 다른 방법을 시도해볼게요!

2021-06-21 14:11 UTC, jgkim1008 commented on JuiceMaker/JuiceMaker/Controller/OrderJuiceViewController.swift
> +    private func showResultOfOrder(selectedJuice: JuiceMenu?, isPossibleToMakeJuice: Bool) {
음...이부분은 이해가 잘 안되요 ㅠㅜ
전달 인자 레이블은 함수 사용자의 입장에서 매개변수의 역할을 좀더 명확하게 표현할때 사용하고, 함수 내부에서는 매개변수 이름으로 사용해야한다고 알고있는데요
더 간략해지는게 어떤건지 모르겠어요.. 함수를 호출할때 전달인자 레이블로 값을 전달하니까 간략해지는건가요??😵‍💫

2021-06-21 14:33 UTC, jgkim1008 commented
@YebinKim 
비비~ 즐거운 주말 보내셨나요??🥳
상세하게 잘 설명해주셔서 감사합니다~~ 꼼꼼히 읽고 PR리뷰에 대한 답변을 남깁니다~~
해당 프로젝트를 게속 진행하려는건 아니고, 리뷰해주신 내용을 읽다가 궁금해서 여쭤보아요!!

말씀하신대로 모달방식으로도 띄워봤어요~ 네비게이션바가 없더라구요!!👏

1.  그러면 push를 하면 StorageViewController 는 OrderJuiceViewController 의 navigationController로 부터 띄워진 것이기 때문에 StorageViewController 의 네비게이션 바에 설정한 내용은 적용이 안되는건가요??

2. StorageViewController 네비게이션 바를 삭제해도 동작하더라구요..그러면 현재 코드에서 StorageViewController에서  네비게이션바에 제목을 추가하려면 OrderJuiceViewController 에서 설정을 하는건가요??🤔