쥬스메이커 [Step 3] Hosinging, Jiwon
yagom-academy/ios-juice-maker pull request #91
Opened 2021-06-16 13:07 UTC by jyoon54

@leejun6694 

안녕하세요 쿠마! 스텝 3 완성하여 보냅니다! 궁금한 내용은 금일 미팅에서 해결하였기 때문에 별도로 적지 않겠습니다.

추후에 생기면 코멘트로 여쭤 보겠습니다!

2021-06-17 18:03 UTC, leejun6694 requested changes
피드백 내용을 잘 반영해주셔서, 코드를 읽는데 도움이 많이 되었습니다 💯 
고민을 해보면 좋을 것 같은 코드에 코멘트를 추가했는데, 혹시 이해가 안되는 부분이 있다면 언제든 말씀 부탁드립니다!

피드백 반영 후, 한번 더 코드를 확인하고 얘기 나눠보고 싶네요~~!

2021-06-17 21:25 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +		refreshStockLabel(strawberryStockLabel: strawberryStockLabel, bananaStockLabel: bananaStockLabel, pineappleStockLabel: pineappleStockLabel, kiwiStockLabel: kiwiStockLabel, mangoStockLabel: mangoSto
레이블묶음을 순회하는 방식으로 하는것이 좋겠네요!

2021-06-17 21:26 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +//MARK:- Private Functions
Method는 객체 내부에서 작성된 함수입니다! 용어선택이 적절하지 못했네요...

2021-06-17 21:29 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Controller/StockModifyViewController.swift
> +enum FruitStepperTag: Int {
기존에 만들어 두었던 Fruit Enum에 원시값을 주는것으로 완전히 대체 가능하겠네요!

2021-06-17 21:38 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Controller/StockModifyViewController.swift
> +		guard let strawberryStock = FruitStore.shared.fruitStocks[.strawberry],
재고 수정화면을 띄울때 각 스텝퍼의 tag값에 현재 수량을 넣는 방법도 있을거 같아요!

2021-06-18 02:01 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +		super.viewWillAppear(true)
헛... 별생각없이 애니메이션이 있으면 좋은거 아닌가해서 넣었는데.. 위의 animated로 동일하게 해주는게 더 좋겠네요

2021-06-18 10:29 UTC, jyoon54 commented on JuiceMaker/JuiceMaker/Controller/StockModifyViewController.swift
> +		guard let strawberryStock = FruitStore.shared.fruitStocks[.strawberry],
스탭퍼의 Tag값은 과일의 원시값으로 하여 어떤 과일의 스텝퍼인지 알 수 있게 하였고, 화면이 로드될 때 불러온 레이블숫자를 저장해두고 원래의 재고량으로 활용했습니다.

2021-06-20 14:15 UTC, leejun6694 approved these changes
코드를 개선하려고 여러 방면으로 생각하는 모습이 인상적입니다.
처음 적용해본 구조들은 좀 더 공부를 하면 좋을 것 같네요.

고생 많으셨습니다 : )

2021-06-20 14:15 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/StockModifyViewController.swift
> +//	private struct previousStocks {
불필요한 주석은 제거해주세요~~!

2021-06-20 14:15 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/StockModifyViewController.swift
> +
줄바꿈되어있네요 @.@

2021-06-20 14:15 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    private var fruitLabels = [UILabel]()
전체적으로 들여쓰기가 안맞는 부분들이 있는데, 깃헙에서만 그런건지 궁금하네요.
제가 다운로드 받아서 확인하면 제대로 되어있는데,,

2021-06-20 14:15 UTC, leejun6694 commented on JuiceMaker/JuiceMaker/Extension/UILabel+UIViewController.swift
> +extension UIViewController {
현재 프로젝트 내, 여러 UIViewController 에서 사용되는 method 여서 extension 안에 method 를 만든 것으로 보이네요.
프로젝트가 확장될 수록 오히려 한정적인 method 들이 될 것 같은데 어떻게 생각하시나요?

2021-06-20 14:15 UTC, merged

2021-06-21 01:26 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/StockModifyViewController.swift
> +//	private struct previousStocks {
놓친 부분이 있었네요🤤. 반영했습니다.

2021-06-21 01:26 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/StockModifyViewController.swift
> +
놓친 부분이 있었네요🤤. 반영했습니다.

2021-06-21 01:27 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Controller/JuiceOrderViewController.swift
> +    private var fruitLabels = [UILabel]()
이상이 없었던 것 같은데 피드백 내용 반영하면서 파일별로 Ctrl + i로 다시 정렬했습니다.

2021-06-21 01:33 UTC, Hosinging commented on JuiceMaker/JuiceMaker/Extension/UILabel+UIViewController.swift
> +extension UIViewController {
네 쿠마가 말씀해주신 것처럼 프로젝트가 확장될 수록 한정적인 method들이 될 것 같습니다.
저희도 이 부분을 각 각의 뷰컨트롤러에 작성을 해야할까 고민을 해보다가 일단은 많은 고려없이 바로 사용할 수 있고, 메소드의 위치가 다른 파일 보다는 뷰컨트롤러에 위치하는게 적절하다는 판단으로 익스텐션으로 기울었었던 것 같습니다. 

제가 생각하기로는 뷰 컨트롤러에서 다른 뷰컨트롤러의 상속, 싱글톤으로 구현된 FruitStore로 위치 이동, 스위프트 파일을 하나 만들어서 그 파일에 타입 메소드로 선언 정도가 생각이 드는데 혹시 쿠마라면 어떤 방법이 적절할 것 같으신지 궁금합니다.