쥬스메이커 [STEP3] Jost, yun
yagom-academy/ios-juice-maker pull request #99
Opened 2021-06-18 08:32 UTC by YongHoonJJo

@TaeJoongYoon 

안녕하세요 tyler ! STEP 3 진행 후 PR 드립니다.
STEP2 의 머지 후 리뷰에 대해서도 피드백 반영하였습니다 리뷰 부탁드릴게요!! 2주동안 자세하게 리뷰해쥬셔서 정말 감사했습니다.

- 피드백 내용으로 Dictionary 대시 메서드를 활용하는 방식으로 변경하였으며, 두 뷰컨트롤러에서 같은 기능을 사용하여 프로토콜 및 익스텐션으로 분리해봤습니다.
- 피드백 반영 내용으로 버튼 및 스테퍼에 tag 값을 적용하여 하나의 IBAction 으로 해결하는 방법으로 진행하였습니다. 의도에 맞게 반영한 것인지 확인 부탁드리겠습니다!
- 재고추가 view 컨트롤러에서 dismiss() 를 호출할경우 원래 뷰에서 viewWillAppear() 가 호출되지 않는 이슈가 있어서, 버튼을 통해 해당 뷰로 이동시 modalPresentationStyle 을 fullScreen 으로 적용해서 해결했습니다. 또한 메인뷰의 우측 상단의 버튼은 세그로 연결했는데, 처음에 show 로 연결했을때 역시 dissmiss() 이후 viewWillAppear() 가 호출되지 않는 이슈가 있었는데, segue type 을 present modally 로 변경하니 present 옵션을 설정할 수 있어서, 여기서 Full Screen 으로 적용해서 해당 이슈를 해결하였습니다.
- ViewController 에서 init() 함수를 활용하는 점에서 리뷰를 주셨는데, 단순히 호출하니깐 잘 안되었습니다. 이부분은 조금더 서칭할 필요가 있을것 같아 아직 적용을 못해봤습니다. ㅜ
- viewController에 레이블, 버튼 마다 IBOutlet, IBAction을 만들어줬는데, 코드가 너무 길어지는 것 같은 느낌을 받았습니다.  IBOutlet과 IBAction을 익스텐션으로 분리해서 적용하는 방법이 있다고 들었는데, 이런식으로 정의하는 것에 대한 의견을 여쭙고 싶습니다.

2021-06-18 10:55 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Model/FruitStore.swift
>      init(initialValue: UInt = 10) {
싱글톤패턴을 적용시킬땐 init함수를 private으로 접근제어해주는게 좋습니다 ㅎㅎ
그래야 되부에서 객체 생성을 막을수 있어요 :)

2021-06-18 10:55 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Protocol/LabelUpdatable.swift
> +}
protocol의 네이밍이나 중복되는 부분을 따로 함수로 빼셨군요 ㅎㅎㅎ 좋은 방법인것 같습니다!

2021-06-18 10:56 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Controller/StockManagerViewController.swift
> +            stepperMaximumValue
잘못 줄바꿈이 들어간것 같아요!

2021-06-18 10:58 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Controller/StockManagerViewController.swift
> +    }
하나의 함수는 하나의 역할만 하는것이 좋습니다!
stock을 업데이트 하는 부분과 label을 업데이트하는 부분을 분리하는건 어떨까요?

2021-06-18 11:00 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Controller/StockManagerViewController.swift
> +    private let fruitStore: FruitStore = FruitStore.shared
ViewController에서 만들어진 FruitStore를 전달받기 힘들어서 싱글턴으로 만드신걸까요??

2021-06-18 11:04 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        stockManagerNC.modalPresentationStyle = .fullScreen // viewWillAppear() 호출 보장.
ios13부터 present시에 기본 modalPresentationStyle이 변경되었어요. 이를 참고해보시면 좋을것 같습니다 ㅎㅎ

2021-06-18 11:13 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Controller/StockManagerViewController.swift
> +        initStepperValue()
이미 데이터는 준비되었고 뷰의 값 초기화 하는 함수들 같은데 `viewDidLoad`가 아닌 `viewWillAppear`에서 실행한 이유가 있으신가요??

2021-06-18 11:15 UTC, TaeJoongYoon commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +
저번에 말씀드렸던 피드백을 바로 적용해보셨군요... 바로 이해하시다니 역시 멋지십니다 💯 💯 💯

2021-06-18 12:18 UTC, TaeJoongYoon commented
안녕하세요 Jost, yun. 타일러입니다 ㅎㅎ
벌써 STEP3까지 마무리하셨군요 ㅎㅎㅎ 2주간 고생많으셨습니다~~👍

STEP3에서도 크게 이상한 부분은 안보이네요. 역시.. 이해력이 좋으신것 같아요 ㅎㅎ
몇가지 의견을 남겨드리자면

---
#### 1. IBOutlet, IBAction을 익스텐션으로 빼는 방법?
저는 시도해보지 않았지만.. IBOutlet은 저장 프로퍼티라서 익스텐션에 따로 정의할수가 없어서 아마 안될것 같아요. 하지만 IBAction같은 경우는 함수이기때문에 가능은 할것 같아보이네요 ㅎㅎㅎ

#### 2. tag 값 정의
지금처럼 IBOutlet객체에 직접접근해서 tag값을 설정할 수 있지만, 현재 프로젝트처럼 storyboard를 사용한다면 storyboard내에서 버튼, 스테퍼의 attributes inspector에서 tag값을 변경해 줄 수 있습니다. 이렇게 되면 코드라인을 줄일 수 있는 장점이 존재합니다 ㅎㅎㅎ
tag뿐만 아니라 많은 설정값들을 조절 할 수 있으니 이 방법도 참고해보세요 :)

#### 3. 화면 간 데이터 공유
지금 화면 간 데이터를 공유할 게 크게 FruitStore가 존재하죠. ViewController에서 만든 FruitStore 객체를 StockManagerViewController에 넘겨주면 편할 것 같은데 지금은 싱글턴 패턴을 적용하셨어요 ㅎㅎ
단순 데이터를 넘겨주는 거라면 아래와 같이 `init()에 데이터를 넣어서 생성`하거나, `뷰 컨트롤러 변수를 만든 후 변수를 대입`시켜주는 방법 등이 있어요.
```swift

// init()이용
func present() {
  let viewController = ViewController(fruitStore: self.fruitStore)
  self.present(viewController, animated: true)
}

// 변수대입
func present() {
  let viewController = ViewController()
  viewController.fruitStore = self.fruitStore
  self.present(viewController, animated: true)
}
```

하지만 A화면에서 B화면의 변화를 알아야 한다면 클로져나 딜리게이트패턴 혹은 저번에 말씀해주셨던 KVO 등도 이용할 수 있을것 같습니다 ㅎㅎ


#### 4. ViewController init ?!
ViewController는 class이기때문에 init()을 이용할수 있다고 말씀드렸는데요. ViewController내에 바로 init()을 만들면 에러 메세지가 나올거에요. 이건 왜냐하면 ViewController는 UIViewController라는 부모 class를 상속받고 있기 때문이라서, UIViewContoller의 필수 생성자를 만들어야 하기 때문입니다. 관련해서는 아래 문서를 읽어보시면 도움이 되실것 같아요!
[Swift Language Guide - Initialization](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html)

---

2021-06-18 12:20 UTC, TaeJoongYoon requested changes
안녕하세요 Jost, yun. 타일러입니다 ㅎㅎ
벌써 STEP3까지 마무리하셨군요 ㅎㅎㅎ 2주간 고생많으셨습니다~~👍

STEP3에서도 크게 이상한 부분은 안보이네요. 역시.. 이해력이 좋으신것 같아요 ㅎㅎ
몇가지 의견을 남겨드리자면

---
#### 1. IBOutlet, IBAction을 익스텐션으로 빼는 방법?
저는 시도해보지 않았지만.. IBOutlet은 저장 프로퍼티라서 익스텐션에 따로 정의할수가 없어서 아마 안될것 같아요. 하지만 IBAction같은 경우는 함수이기때문에 가능은 할것 같아보이네요 ㅎㅎㅎ

#### 2. tag 값 정의
지금처럼 IBOutlet객체에 직접접근해서 tag값을 설정할 수 있지만, 현재 프로젝트처럼 storyboard를 사용한다면 storyboard내에서 버튼, 스테퍼의 attributes inspector에서 tag값을 변경해 줄 수 있습니다. 이렇게 되면 코드라인을 줄일 수 있는 장점이 존재합니다 ㅎㅎㅎ
tag뿐만 아니라 많은 설정값들을 조절 할 수 있으니 이 방법도 참고해보세요 :)

#### 3. 화면 간 데이터 공유
지금 화면 간 데이터를 공유할 게 크게 FruitStore가 존재하죠. ViewController에서 만든 FruitStore 객체를 StockManagerViewController에 넘겨주면 편할 것 같은데 지금은 싱글턴 패턴을 적용하셨어요 ㅎㅎ
단순 데이터를 넘겨주는 거라면 아래와 같이 `init()에 데이터를 넣어서 생성`하거나, `뷰 컨트롤러 변수를 만든 후 변수를 대입`시켜주는 방법 등이 있어요.
```swift

// init()이용
func present() {
  let viewController = ViewController(fruitStore: self.fruitStore)
  self.present(viewController, animated: true)
}

// 변수대입
func present() {
  let viewController = ViewController()
  viewController.fruitStore = self.fruitStore
  self.present(viewController, animated: true)
}
```

하지만 A화면에서 B화면의 변화를 알아야 한다면 클로져나 딜리게이트패턴 혹은 저번에 말씀해주셨던 KVO 등도 이용할 수 있을것 같습니다 ㅎㅎ


#### 4. ViewController init ?!
ViewController는 class이기때문에 init()을 이용할수 있다고 말씀드렸는데요. ViewController내에 바로 init()을 만들면 에러 메세지가 나올거에요. 이건 왜냐하면 ViewController는 UIViewController라는 부모 class를 상속받고 있기 때문이라서, UIViewContoller의 필수 생성자를 만들어야 하기 때문입니다. 관련해서는 아래 문서를 읽어보시면 도움이 되실것 같아요!
[Swift Language Guide - Initialization](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html)

---

2021-06-19 09:33 UTC, merged

2021-06-19 10:02 UTC, YongHoonJJo commented on JuiceMaker/JuiceMaker/Controller/StockManagerViewController.swift
> +    }
다음 플젝시에 같이 고민하면서 진행하겠습니다! :)

2021-06-19 10:05 UTC, YongHoonJJo commented on JuiceMaker/JuiceMaker/Controller/StockManagerViewController.swift
> +    private let fruitStore: FruitStore = FruitStore.shared
싱글턴 적용한것을 설명을 못드렸던 것 같아 죄송합니다. 사실 넘기는 방법이 있다고는 들었는데, 방법이 잘 확인 되지 않았습니다. 또한, 이 플젝을 진행하면서 싱글턴을 같이 학습을 하게되어서 겸사겸사 적용해보게 되었습니다.

또한, 타일러께서 종합 리뷰에 남겨주신 내용과, 다른 캠퍼중 이를 적용한 캠퍼가 있어서 학습에 도움이 되었습니다. 다음 플젝때는 적용해보겠습니다!!

2021-06-19 10:06 UTC, YongHoonJJo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        stockManagerNC.modalPresentationStyle = .fullScreen // viewWillAppear() 호출 보장.
디테일한 내용까지 알려주셔서 감사합니다!

2021-06-19 10:07 UTC, YongHoonJJo commented on JuiceMaker/JuiceMaker/Controller/StockManagerViewController.swift
> +        initStepperValue()
이 뷰내에서 다른 화면으로 이동했다 돌아올 상황이 생길수도 있지 않을까 하는 생각에 `viewWillAppear` 에서 진행을 하게 되었는데, 너무 앞서 나갔던걸까요? ㅜㅜ

2021-06-19 10:07 UTC, YongHoonJJo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +
덕분에 많은 것을 배우게 된 것 같습니다!!

2021-06-19 10:18 UTC, YongHoonJJo commented
@TaeJoongYoon 

- 다른 캠퍼중 프로퍼티 및 라이프사이클을 제외한 IBAction 및 메서드등을 익스텐션으로 분리해 놓은 코드를 보았는데, 코드가 깔금하게 분리된 것 말고는 다른 이점에 대해서는 아직 잘 와닿진 않고 있습니다. ㅎㅎ

- tag 값을 inspector 에서 정의하게 되면 말씀하신것 처럼 코드의 양이 줄어들 수 있다는 장점이 생긴다고 생각합니다 하지만 휴먼에러? 실수할 확률이 조금더 올라가지 않을가 하는 걱정이 좀 들었는데, 말그대로 걱정일지 궁금합니다!

-  화면 간 데이터 공유의 경우 자세하게 셜명해주셔서 감사합니다. 다음 프로젝트에 적용해보겠습니다. 궁금한것이 이동하게될 viewController 에서 FruitStore 의 인스턴에 대한 프로퍼티를 만들 필요가 있을것 같은데, 다른 캠퍼의 코드를 보니 옵셔널로 정의가 되어 있었습니다. 이렇게 진행하는것이 일반적인 패턴인지 궁금합니다. 

- ViewController init 에 대해서는 조금도 공부해보고 적용해보겠습니다!! 

자세하게 리뷰 남겨주셔서 정말 감사했습니다!!

2021-06-19 13:18 UTC, YongHoonJJo commented on JuiceMaker/JuiceMaker/Controller/ViewController.swift
> +        stockManagerNC.modalPresentationStyle = .fullScreen // viewWillAppear() 호출 보장.
디폴트가 13 이전에는 .Fullscreen 이었는데, 13 부터는 .Popover 로 변경 되었다는 내용 확인했습니다!